### ISSUE TITLE
lineation in two column memoir doc

### ISSUE THREAD

**Issue by camatkara** [maieul/ledmac#102]
Hi, I was having trouble with lineation in a two column memoir document (it would switch sides). I asked for help on stackexchange, thinking I was missing something. Here's the post, which has an explanation and mwe:

http://tex.stackexchange.com/questions/87306/eledmac-line-numbering-out-of-margin-at-top-of-column-memoir

A very helpful user, David Carlisle, helped to get things looking pretty good, but not perfect. In terms of use, if you scroll down that page, you can see an example of a Sanskrit commentary which is very useful to have in 2 column format with eledmac. Hoping this is possible! Thanks.

**Comment by maieul** [comment]
no answer. I close this issue.
