### ISSUE TITLE
Pouvoir marquer qu'il s'agit du enime lem identique d'une ligne

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#110]
Exemple 

<code>
ἡ καθ’ ἡμέραν τὰς καθ’ ἡμέραν
</code>

Je veux mettre une note sur le deuxième ἠμέραν. Il faut que je puisse indiquer le premier ἠμέραν. Il faudrait que si le premier et le second soit sur la même ligne, l'indicateur de lemme note la position, et si ce n'est pas le cas, qu'il ne la note pas.

**Comment by maieul** [comment]
sorry for this bug. Try new version.

**Comment by stenskjaer** [comment]
The latest version solves this issue. Very nice!
