### ISSUE TITLE
Wrong indents (ragged left) for verses following a verse that is as width as \textwidth

### ISSUE THREAD

**Issue by tweh** [maieul/ledmac#138]
There seems to be a bug, as you can se in the image the verses of the second stanza are set ragged left but indeed they shouldn’t be …

![ragged left verses](https://f.cloud.github.com/assets/3011538/1386530/b40a95a2-3b75-11e3-9748-214977b62399.png)

    \documentclass{scrbook}% [1] using book instead
    
    \usepackage{eledmac}
    \usepackage[%
    	shiftedpstarts% [2] disabling this
    ]{eledpar}
    
    \setstanzaindents{1,0}% [3] replacing 1 by 0
    \setcounter{stanzaindentsrepetition}{1}
    
    \begin{document}
    \begin{pages}
    \begin{Leftside}
    	\beginnumbering
    	\stanza
    	xxxxxx xx x xxxxxx xxxxxxxx xxxxxxx. xxxxx &
    	xxxx xxxxx xxxxxxx xxxxxx xxxxxxx xxxxxxx.
    	\&
    	
    	\stanza
    	xxx xxxxx xxxxx xxxxxx xxx xxxxxx, xxxxx &
    	xxx xxxxxxx xxxxxxxxx xxxxx xxxxxxx xx xxxx: &
    	xxxx xxxxxx xxxxxx, xxxx xxxxxxx, xxxxx xxxxxxx &
    	\&
    	\endnumbering
    \end{Leftside}
    \begin{Rightside}
    	\beginnumbering
    	\stanza
    	xxxxxx xx xxxxxxxx xxxxxx, xxxx xxx xxxxxxx xxx xxxxxx xxxxxx xxxxxxxxxxxx. &
    	Die Hand selbst brachte als hellklingende Stellvertreterin der Zunge die Stimme hervor.
    	\&
    	
    	\stanza
    	xxxxx xxx xxx xxxxx xxxx xxx xxxxx xxx xxxxx xxx xxxx, xxxxxxx xxx xxxxxx &
    	xxxxxx xxx xxx xxxx xxxäxxxxxx xxxx xx xxxxx xxxxxxxxxx &
    	xxxx xxxxx xxxx xxxxxxx xxx, xxxx xxxxx, xxx xxx xxx xxxxxxxxxx &
    	\&
    	\endnumbering
    \end{Rightside}
    \Pages 
    \end{pages} 
    \end{document}

I guess the problem is that the second verse has nearly exactly the same width as `\textwidth`, removing some letters will solve the problem. Furthermore [1] replacing the document class (which changes `\textwidth`), [2] disabling `shiftedpstarts` and [3] setting the first indent to `0` will “solve” the problem but all these are no option for me …

I hope you got a quick fix for this because the book should be published very soon.

**Comment by maieul** [comment]
I have reopened this issue. Could you confirm to me that the branch "issue138" solve this problem and allow space between the end of the verse and the & ?

**Comment by tweh** [comment]
Seems to work fine! With the current CTAN-version I had the problem that the right line number was missing, which is kind of strange since I didn’t saw this problem in my real document, but with this branch the number is shown and every thing works.

**Comment by maieul** [comment]
thanks !

**Comment by maieul** [comment]
I will publish on CTAN tomorrow, I think.

**Comment by tweh** [comment]
Thanks … maybe you can have a look at #257 before publishing the new version :-)
