### ISSUE TITLE
Footnotes equally spanning through both pages in bilingual edition done by ledpar.

### ISSUE THREAD

**Issue by psps** [maieul/ledmac#17]
Currently, critical aparatus/footnnotes are confined to the (single language) page
where the note is done. I use notes only for single language, leaving the page with
second language without commentaries. It would be nice if the footnotes could optionally
run through both left/right facing pages leaving approximately the same size for the text.

It might be that this enh request is not easily doable with the current internal structure of ledpar --
if so feel free to close this issue in such case.
Thanks.

**Comment by maieul** [comment]
la version dans la branch issue17-ter devrait permettre de résoudre à moitié le problème. Pour le choix page de gauche/page de droite, juste attendre ce week-end.

**Comment by maieul** [comment]
note perso pour moi pour savoir comment gérer les notes réservé gauche/réservé à droite
1) On définit des options pour dire "cette note est pour la gauche" / "cette note est pour la droite" (ou mieux, page impaires/paires).
2) pour l'affichage, c'est assez simple : l'affichage de la note dans la routine de sortie est conditionnée à la parité de page, en fonction du règlage. C'est juste des test conditionnels.
3) par contre le pb c'est que les pages de gauche vont perturber le pagegoal des pages de droites, en faisant comme si c'était réservé
4) du coup il faut essayer de "deviner" de combien tex vamodifier le pagegoal de droite en fonction de ce qui reste à gauche. Et du coup l'augmenter d'autant.
5) il faut donc pour chaque série de notes un système qui repère quel est la taille de la note, qui le stocke, et qui voit à la fin la taille de la note sorti. Ainsi on sait ce qui reste à ressortir, et on peut jouer la compensation.

**Comment by maieul** [comment]
une solution a tester : plutot que de faire des calcul, dire au début de chaque page de droite que les le paramètre des notes réservé à gauche est égale à 0. Evidement il faut rétablir lorsqu'on bascule à gauche...
