### ISSUE TITLE
Section heading jammed against preceding numbered paragraph

### ISSUE THREAD

**Issue by thomasowenmclean** [maieul/ledmac#229]
Thanks very much for what looks like an enormous amount of work in maintaining a very useful package. I have a bug which can be easily solved by using eledsection, so please don't treat it as important. Still, it seems worth reporting:

Any (*)section header following a numbered paragraph is jammed up against the preceding paragraph, as below:

```
\documentclass{article}
\usepackage{eledmac}
\begin{document}
\beginnumbering
\section{This works}

\pstart A paragraph of numbered text goes here. \pend

\section{This doesn't.}

The heading above is jammed up against the preceding paragraph. The bug does not appear using eledsection, or if the preceding paragraph is not numbered -- that is, not between pstart and pend

\endnumbering

\end{document}
```

**Comment by maieul** [comment]
you should use the optional argument of a \pend, like in 392506f.

In any case, the branch issue229 should solve this problem.

**Comment by thomasowenmclean** [comment]
The optional argument solution works perfectly, thank-you, which is enough of a solution for me.

However, the branch issue229 introduces a new bug: if a numbered paragraph is followed by a numbered paragraph without an intervening section, a vertical space appears between them.

**Comment by maieul** [comment]
sorry, I don't see the problem, but maybe I don't understand what you mean. But as the optional option is working, I will close this issue and reject my correction, which could have boarding effect=
