### ISSUE TITLE
bug minipage

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#230]
\documentclass{article}

\usepackage{lipsum,eledmac}
	\footparagraph{A}

\begin{document}
	
	\beginnumbering
		\pstart
			\lipsum[1]
		\pend
		\pstart
			This is a test. All is still well.
		\pend
	\endnumbering
	
	\vfill
	
	\begin{minipage}{\textwidth}
		\beginnumbering
			\pstart
				This is a \edtext{test}{\Afootnote{try}}. Wrong line number.
			\pend
		\endnumbering
	\end{minipage}

	\vfill
	
	\begin{minipage}{\textwidth}
		\beginnumbering
			\pstart
				This is a \edtext{test}{\Afootnote{try}}. Wrong line number.
			\pend
		\endnumbering
	\end{minipage}

	\vfill
\end{document}

**Comment by maieul** [comment]
please @djdekker try new branch issue230.

**Comment by djdekker** [comment]
Le problème avec les minipages est résolu. Un grand merci à vous, Maïeul!

**Comment by maieul** [comment]
de rien. Je vais publier cela sur le CTAN vendredi
