### ISSUE TITLE
\sameword: numbering of exponents

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#235]
I have a problem, when I use the sameword mechanism after and independent of a critical note with the lemma command inside. The exponents are confused. 

But, when the text containing the lemma command is placed at the end of the MWE, the result will be as expected. 

\beginnumbering
\pstart
panis parvus, quod \edtext{speculum}{\lemma{speculativus}\Afootnote{speculatius}} appello. 
\pend

\pstart
imaginum \edtext{\sameword{quedam}}{\Afootnote{quem}} vera, \sameword{quedam} fantastica.
\pend

\pstart
et hec duplex invenitur, \edtext{\sameword{aut}}{\Afootnote{at}} naturalis, \edtext{\sameword{aut}}{\Afootnote{ast}} artificialis.
\pend
\endnumbering

**Comment by maieul** [comment]
which version of eledmac do you have ?

with your MWE and the last version of eledmac, I obtain

1 speculativus] speculatius 2 quedam1 ] quem
3 aut1 ] at
3 aut2 ] ast

which is right (or I am very tired !)

**Comment by sonator** [comment]
The result of your compilation is correct! 

I have used v1.15.1 with the result shown below. Perhaps there is a conflict between the packages loaded in my preamble and the sameword-mechanism. 



![exemplumsw](https://cloud.githubusercontent.com/assets/7208920/5858414/3f51304a-a253-11e4-9e5c-6501cd21a3a1.png)

**Comment by sonator** [comment]
Postscriptum: 
Indeed, there must be an incompatibility in my configuration. 
The following MWE with a reduced preamble runs with correct result. 

\documentclass{book}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{eledmac} 

\firstlinenum{1}  \linenumincrement{1}

\begin{document}

\beginnumbering
\pstart
panis parvus, quod \edtext{speculum}{\lemma{speculativus}\Afootnote{speculatius}} appello.
\pend

\pstart
imaginum \edtext{\sameword{quedam}}{\Afootnote{quem}} vera, \sameword{quedam} fantastica.
\pend

\pstart
et hec duplex invenitur, \edtext{\sameword{aut}}{\Afootnote{at}} naturalis, \edtext{\sameword{aut}}{\Afootnote{ast}} artificialis.
\pend
\endnumbering

\end{document}

**Comment by sonator** [comment]
Secundum Postscriptum: 
When I load eledpar (v1.10.1), too, the wrong exponents occur as described in my first note.

\documentclass{book}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{eledmac}
\usepackage{eledpar}

\firstlinenum{1}  \linenumincrement{1}

\begin{document}

\beginnumbering
\pstart
panis parvus, quod \edtext{speculum}{\lemma{speculativus}\Afootnote{speculatius}} appello. 
\pend

\pstart
imaginum \edtext{\sameword{quedam}}{\Afootnote{quem}} vera, \sameword{quedam} fantastica.
\pend

\pstart
et hec duplex invenitur, \edtext{\sameword{aut}}{\Afootnote{at}} naturalis, \edtext{\sameword{aut}}{\Afootnote{ast}} artificialis.
\pend
\endnumbering

\end{document}

**Comment by maieul** [comment]
ok, I think the problem was indeed with eledpar. Please try the branch issue235=

**Comment by sonator** [comment]
Problemata mea soluta sunt. Exponentes in notis criticis nunc rectos accipiunt numeros. Unde ego gratiam plurimam et salutem tibi dico Majolo!

**Comment by maieul** [comment]
I have no bravery to write in Latin tonight. So: you're welcome.

I will publish relase tomorrow or this week-end. I am just waiting for a test by @doc73 on #237
