### ISSUE TITLE
Use of \pstartinfootnote not compatible with eledpar

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#237]
I am preparing a critical edition of a greek text accompanied by an english translation. The lines of each paragraph have to be separately enumerated; so, the lineation is set as \lineation{pstart}. Whereas line numbers of various lemmata in the apparatus are normaly printed with eledmac, this is not the case when adding a translation of the greek text by means of ledpar; only the first paragraph’s number gets printed in the apparatus. I added \pstartinfootnote in the preamble to make it work, but there was no luck (I know this is not needed, since the lineation is set to „pstart“). I am attaching a sample regarding this difficulty and I would be more than thankful for any advice…

\documentclass[12pt,a4paper]{book}
\usepackage[english,polutonikogreek]{babel}
\usepackage[iso-8859-7]{inputenc}
\usepackage{eledmac}
\usepackage{eledpar}

\lineation{pstart}

\pstartinfootnote

\footparagraph{A}
\footparagraph{B}

\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
<Ομώνυμα \edtext{λέγεται}{\Afootnote{\textlatin{a variant of the 1st paragraph in apparatus A}}} <~ων >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος κα`ι τ`ο γεγραμμένον; τούτων γ`αρ >όνομα \edtext{μόνον}{\Bfootnote{\textlatin{a variant of the 1st paragraph in apparatus B}}} κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος. <Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος κα`ι τ`ο γεγραμμένον; τούτων γ`αρ >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\pstart
<Ομώνυμα λέγεται <~ων \edtext{>όνομα}{\Afootnote{\textlatin{a variant of the \textbf{2nd paragraph} in apparatus A}}} μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος κα`ι τ`ο γεγραμμένον; τούτων γ`αρ >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος. <Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος κα`ι τ`ο \edtext{γεγραμμένον}{\Bfootnote{\textlatin{a variant of the \textbf{2nd paragraph} in apparatus B}}}; τούτων γ`αρ >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\selectlanguage{english}
\beginnumbering
\pstart
This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample.
\pend
\pstart
This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample.
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}

**Comment by maieul** [comment]
that is indeed a bug. Please try issue237, which should solves it. (Read https://github.com/maieul/ledmac#debug to know how to test)

**Comment by NiAgio** [comment]
Many thanks for your reply, but I am afraid that I do not undestand... What do you mean by saying that I should "try issue 237, which should solve" the problem?

**Comment by maieul** [comment]
please read the handbook I have written and linked...

**Comment by NiAgio** [comment]
Problem not solved...

**Comment by maieul** [comment]
are you sure to have made the good thing? In local, with your MWE + my corrections, I obtain

 
1. 1 λέγεται ] a variant of the 1st paragraph in apparatus A 2. 1 ὄνομα ] a variant of the 2nd paragraph in apparatus A

1. 3 μόνον ] a variant of the 1st paragraph in apparatus B 2. 5 γεγραμμένον ] a variant of the 2nd paragraph in apparatus B

**Comment by NiAgio** [comment]
Apparently I am making something in the wrong way... I have downloaded the issue folder and run the relevant tex file with texmaker... What is MWE? Am I doing something wrong? Sorry, not good with technologies, I went way beyond myself even to have used Latex :)

**Comment by maieul** [comment]
Not a problem. A MWE means "Minimal Working Example". You provides it. see http://www.tex.ac.uk/cgi-bin/texfaq2html?label=minxampl.

However, you didn't run fully my handbook for debuging. I write two points you omitted

	� Run the .ins files with pdflatex, to obtain the .sty files.
	� Put the .sty files with your test files (in the same folder).

**Comment by NiAgio** [comment]
Ok, thanks again for your time and effort and sorry for me being ignorant. So, there are two *.ins files in the "issue237" forlder: eledmac and elepar.ins. How do I run them with pdflatex? I thought that running the issue237.tex file with texmaker was enough...

**Comment by maieul** [comment]
juste open these files with texmaker and run them as you do for .tex file. It will produce .sty file...

**Comment by NiAgio** [comment]
Opened the file, run it with pdflatex and gave me a message saying that the log file was not found...

**Comment by maieul** [comment]
sorry? I have just tried now, and I obtained the right .sty files. Was the error "nopage of output" ? in this case, it's normal.

In any case, I have pushed the .sty file in the zip. Just reload it and try (I do it because it's a short problem, for much complex problem, you should make .sty file yourself)

**Comment by NiAgio** [comment]
DONE! Thank you so much, you are the best!!!

**Comment by maieul** [comment]
you're welcome. I will publish it in ctan in two days
