### ISSUE TITLE
Problems with KOMA script and recent eledmac

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#238]
Thank you very much for your great packages! I am working on a book with an ancient text, translation and commentary. I am trying your package for that.

My problem since I updated eledmac: As soon as I am trying to use eledmac with KOMA script, I do get error messages. The first one is:

! Missing number, treated as zero.
<to be read again> 
                   \let 
l.7 \section{Test-Section}

Is there any chance that those two packages are working together? (This did not happen with eledmac 1.7)

My package versions:
 scrbook.cls    2009/07/24 v3.04a KOMA-Script document class (book)
scrkbase.sty    2009/07/24 v3.04a KOMA-Script package (KOMA-Script-dependent ba
sics and keyval usage)
 scrbase.sty    2009/07/24 v3.04a KOMA-Script package (KOMA-Script-independent 
basics and keyval usage)
  keyval.sty    1999/03/16 v1.13 key=value parser (DPC)
scrlfile.sty    2009/03/25 v3.03 KOMA-Script package (loading files)
tocbasic.sty    2009/06/08 v3.03b KOMA-Script package (handling toc-files)
scrsize12pt.clo    2009/07/24 v3.04a KOMA-Script font size class option (12pt)
typearea.sty    2009/07/24 v3.04a KOMA-Script package (type area)
inputenc.sty    2008/03/30 v1.1d Input encoding file
    utf8.def    2008/04/05 v1.1m UTF-8 support for inputenc
   t1enc.dfu    2008/04/05 v1.1m UTF-8 support for inputenc
  ot1enc.dfu    2008/04/05 v1.1m UTF-8 support for inputenc
  omsenc.dfu    2008/04/05 v1.1m UTF-8 support for inputenc
   babel.sty    2008/07/08 v3.8m The Babel package
 english.ldf    2005/03/30 v3.3o English support from the babel system
 eledmac.sty    2015/02/09 v1.17.0 LaTeX port of EDMAC
   xargs.sty    2008/03/22 v1.1  extended macro definitions  (mpg)
 xkeyval.sty    2008/08/13 v2.6a package option processing (HA)
 xkeyval.tex    2008/08/13 v2.6a key=value parser (HA)
etoolbox.sty    2011/01/03 v2.1 e-TeX tools for LaTeX
    etex.sty    1998/03/26 v2.0 eTeX basic definition package (PEB)
  suffix.sty    2006/07/15 1.5 Variant command support
 xstring.sty    2010/03/28  v1.5d  String manipulations (C Tellechea)
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
ragged2e.sty    2009/05/21 v2.1 ragged2e Package (MS)
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
 eledpar.sty    2015/01/23 v1.11.0 eledmac extension for parallel texts

Example code:
\documentclass[twoside,12pt]{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{eledmac,eledpar}
\begin{document}
\chapter{Test-Chapter}
\section{Test-Section}
\end{document}

**Comment by maieul** [comment]
sorry, but I don't have any problem with these versions. So update also koma ...

scrbook.cls    2015/01/14 v3.15 KOMA-Script document class (book)
scrkbase.sty    2015/01/14 v3.15 KOMA-Script package (KOMA-Script-dependent basi
cs and keyval usage)
 scrbase.sty    2015/01/14 v3.15 KOMA-Script package (KOMA-Script-independent ba
sics and keyval usage)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
scrlfile.sty    2015/01/14 v3.15 KOMA-Script package (loading files)
tocbasic.sty    2015/01/14 v3.15 KOMA-Script package (handling toc-files)
scrsize12pt.clo    2015/01/14 v3.15 KOMA-Script font size class option (12pt)
typearea.sty    2015/01/14 v3.15 KOMA-Script package (type area)
inputenc.sty    2014/04/30 v1.2b Input encoding file
   babel.sty    2014/09/25 3.9l The Babel package
 english.ldf    2012/08/20 v3.3p English support from the babel system
 eledmac.sty    2015/02/09 v1.17.0 LaTeX port of EDMAC
   xargs.sty    2008/03/22 v1.1  extended macro definitions  (mpg)
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
etoolbox.sty    2011/01/03 v2.1 e-TeX tools for LaTeX
    etex.sty    1998/03/26 v2.0 eTeX basic definition package (PEB)
  suffix.sty    2006/07/15 1.5a Variant command support
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
ragged2e.sty    2009/05/21 v2.1 ragged2e Package (MS)
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
 eledpar.sty    2015/01/23 v1.11.0 eledmac extension for parallel texts

**Comment by baem2** [comment]
Yes, you are right. Sorry for harassing you ... Thanks again!

**Comment by maieul** [comment]
you are welcome.
