### ISSUE TITLE
Bug regarding the use of \setcounter{pstart}{} and \numberpstarttrue with \lineation{pstart}

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#239]
Hello! I need some help with the following issue: "true" paragraph numbers are printed in the apparatus, instead of the "false" ones provided by the \numberstarttrue and \setcounter{pstart}{} commands.Take a look in the MWE:

\documentclass[12pt,a4paper]{book}
\usepackage[english,polutonikogreek]{babel}
\usepackage[iso-8859-7]{inputenc}
\usepackage{eledmac}
\usepackage{eledpar}

\lineation{pstart}

\footparagraph{A}
\footparagraph{B}
\footparagraph{C}

\numberonlyfirstinline[A]
\numberonlyfirstinline[B]
\numberonlyfirstinline[C]

\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
Περ`ι \edtext{<ερμηνείας}{\Afootnote{\textlatin{this variant should be printed with NO paragraph number 1}}}
\pend
\setcounter{pstartL}{1}
\numberpstarttrue
\pstartinfootnote[B]
\pstart
<Ομώνυμα λέγεται <~ων \edtext{>όνομα}{\Afootnote{\textlatin{this variant should be printed under paragraph number 1, not 2}}} μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος κα`ι τ`ο γεγραμμένον; τούτων γ`αρ >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος. <Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος κα`ι τ`ο γεγραμμένον; τούτων γ`αρ >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\pstart
<Ομώνυμα λέγεται <~ων \edtext{>όνομα}{\Afootnote{\textlatin{this variant should be printed under paragraph number 2, not 3}}} μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος κα`ι τ`ο γεγραμμένον; τούτων γ`αρ >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος. <Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος κα`ι τ`ο γεγραμμένον; τούτων γ`αρ >όνομα μόνον κοινόν, <ο δ`ε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\numberpstartfalse
\endnumbering
\end{Leftside}

\begin{Rightside}
\selectlanguage{english}
\beginnumbering
\pstart
English Title
\pend
\setcounter{pstartR}{1}
\numberpstarttrue
\pstart
This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample.
\pend
\pstart
This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample.
\pend
\numberpstartfalse
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}

**Comment by NiAgio** [comment]
Notice also the following problem: whereas the left text is numbered with a "pstart" lineation, this is unexpectedly not the case in the right text.

**Comment by maieul** [comment]
for the second problem, you must use 
\lineationR (read the handbook of eledpar !) or 
\lineation* (which do it for both side)

**Comment by NiAgio** [comment]
Thanks!

**Comment by maieul** [comment]
for the first problem, I have to found a better way. When I have implemented pstart in //, I didn't think that some one wouldn't want to number the pstart not in continuous from the begining �
i will look for it this afternoon, after eating

**Comment by NiAgio** [comment]
Yes, there can be variants for the title of a given work. The title cannot be concidered though as a paragraph in these cases... Thanks for taking the time to fix the problem. Bon appétit!

**Comment by maieul** [comment]
during this time, try to obtain .sty file from the .ins file.

just run pdflatex on the .ins file� you should obtain .dtx file.

I won't add to github the .sty file, it's in many case a bad idea.

**Comment by maieul** [comment]
do you know that 
\numberonlyfirstinline[A]
 \numberonlyfirstinline[B]
 \numberonlyfirstinline[C]

can be simplified by 

 \numberonlyfirstinline[A,B,C]
or better

 \numberonlyfirstinline

(if you don't use D notes)

**Comment by maieul** [comment]
I have to refactor some code. The test wil be released soon.

**Comment by NiAgio** [comment]
Ok, thanks a lot! I am looking forward to it.

**Comment by maieul** [comment]
ok, it should be solve. More complex than though (and so one, less perfomant). Please try the branch "issue239".

**Comment by NiAgio** [comment]
That's so great! Thanks a lot!  I'll check it as soon as I get home and let you know. 

---- Ο χρήστης Maïeul Rouquette έγραψε ----

**Comment by maieul** [comment]
hi, some news?

**Comment by NiAgio** [comment]
Hi! I have been trying all morning to make the ins files run on pdflatex 
in order to produce some sty file. I keep receiving a message saying 
that the log file could not be found... i uninstalled and installed 2 
times miktex and texmaker, but no luck... I saw in the internet that 
there are others who face the same problem as well. I did not find any 
solution though. Would you have any ideas on the subject?

Am 15/2/2015 um 12:07 μμ schrieb Maïeul Rouquette:

**Comment by Doc73** [comment]
Dear NiAgio,
sorry for my intrusion, but I would suggest to you to install TeXLive 
in place of Miktex.

Surely, Miktex is an eccellent distribution, but.... is too old and 
poorly developed:.
Many of your problems can arise from this fact, although I have no time 
to teste your code.



Il giorno dom 15 feb 2015 alle 13:37, NiAgio <notifications@github.com> 
ha scritto:

**Comment by maieul** [comment]
hum, I will look, but I don't use texmaker and miktex (texlive and texshop for me).

before I solve it, you can use the .sty file that I have uploaded ...

**Comment by maieul** [comment]
indeed, many people said me than miktex is problematic (especially because not installing default package, and installing "on the fly" is many time blocked by antivirus...

**Comment by NiAgio** [comment]
Ok, I see... I shall try the .sty and let you know shortly.

**Comment by NiAgio** [comment]
You are the Gandalf of LaTex! The .sty file is simply marvelous... It works fine, it is exactly what I needed. Thank you very much once again.

Dear Doc73, you do not intrude. Actually, I am thankful for your advice. I shall give it a try at some point, but not right now. I already have a LOT to work on regarding the philological issues of my edition, there is no time for shortcomings of Latex...

**Comment by Doc73** [comment]
Are you editing grammatical texts? Good, very good!
I edited platonic scholia, therefore we are cousins!


Il giorno dom 15 feb 2015 alle 13:54, NiAgio <notifications@github.com> 
ha scritto:

**Comment by NiAgio** [comment]
I am editing byzantine scholia on Aristotle, we are indeed very close cousins. The old man in your picture and the man standing next to him verify the fact.... :)

**Comment by maieul** [comment]
I have tried in my virtualbox. I think you problem is miktex + antivirus -> block the auto install fo update.

I will ask sometone ton check my english and publish it

**Comment by NiAgio** [comment]
Will do it!

**Comment by maieul** [comment]
do what?

**Comment by NiAgio** [comment]
check the antivirus, if it actually creates any problem.

**Comment by maieul** [comment]
ok. are you english native speaker ?

**Comment by NiAgio** [comment]
No, still learning...

**Comment by maieul** [comment]
ok.
