### ISSUE TITLE
bug indexation hyperref.

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#241]
https://github.com/maieul/indextools/issues/1#issuecomment-75041415

**Comment by maieul** [comment]
@ralessi : je n'arrive pas à reproduire le bug. J'imagine qu'il se produit sur du eledpar, dans certaines conditions.

**Comment by ralessi** [comment]
Oui. Il faut: 1) eledpar 2) des marques d'index sur les pages de droite.

**Comment by maieul** [comment]
la branche issue241 devrait r�soudre ce pb. Peux tu tester et me faire un retour ?

**Comment by ralessi** [comment]
Cette fois les liens sont bien actifs. J'ai cependant des fichiers `.ind` qui se présentent comme suit:
````\begin{theindex}

  \item ἄγω, \hyperlinkR{$&1568}{29-5}
  \item ἀδελφιδῆ, \hyperlinkR{$&581}{15-7}
  \item ἀδελφός, \hyperlinkR{$&1090}{23-3}
  \item ἀεί, \hyperlinkR{$&1110}{23-5}, \hyperlinkR{$&1267}{25-2}, 
		\hyperlinkR{$&1299}{25-6}
    \subitem fl., \hyperlinkR{$&1172}{23-9}
  \item ἀθρόος, \hyperlinkR{$&561}{15-6}
```
etc. Mais je suppose que c'est normal?

Par ailleurs, les numéros des lignes sont faux. Pas de beaucoup, mais décalés d'une ou deux lignes en fait. Évidemment, les numéros sont aussi faux dans l'apparat. Aïe.

Je vais essayer de compiler 50 fois, mais je n'ai pas d'avertissement. Je vais tester sur la branche normale.

**Comment by ralessi** [comment]
Ah non! Pardon!

Les numéros sont bons, ce sont les numéros dans la marge qui ne sont pas en face des bonnes lignes! Par exemple, face à la ligne 3, j'ai le numéro 5. Je poursuis les tests.

**Comment by maieul** [comment]
hein? mauvais numero en face des lignes? c'est la premi�re fois que je vois ca� mais attention, a chaque compilation faut refaire...

**Comment by ralessi** [comment]
J'avais pourtant compilé au moins 20 fois. Je suis retourné à la dernière version publiée, et les numéros sont en face des bonnes lignes maintenant. Je vais refaire un test avec la branche issue241 à partir ce que j'ai.

**Comment by ralessi** [comment]
Au fait, as-tu vu que je n'ai toujours pas \hyperlink dans les fichiers .ind?

**Comment by maieul** [comment]
avec mon MWE je les ai...

**Comment by ralessi** [comment]
J'ai remis la branche 241. Je vois que tu as aussi travaillé le problème des espaces blancs dans générés entre les mots par les marques d'index.
Après je ne sais combien de compilations et plus de messages m'invitant à recompiler, j'ai ça dans mon grec.ind avec la branche 241:
````
  \item ἄγω, \hyperlinkR{$&1568}{29-5}
  \item ἀδελφιδῆ, \hyperlinkR{$&581}{15-7}
  \item ἀδελφός, \hyperlinkR{$&1090}{23-3}
  \item ἀεί, \hyperlinkR{$&1110}{23-5}, \hyperlinkR{$&1267}{25-2}, 
````

Et pour les numéros des lignes, le problème est en fait un décalage: au début de chaque page, la ligne 3 a le numéro 5, puis la numérotation suit de 5 en 5. Ce qui est certain, c'est que le pb apparaît avec la branche 241. Avec la version publiée, j'ai des bons numéros, mais de gros espaces blancs parfois entre les mots, et des hyperliens qui ne marchent pas dans les index.
Voici un exemple d'espaces blancs avec la version publiée (mais non plus avec la 241).
![capture](https://cloud.githubusercontent.com/assets/389498/6271191/5ad8770c-b85f-11e4-8b45-9b61081555a4.png)

**Comment by ralessi** [comment]
Précision: toujours avec la branche 241, même avec les `\hyperlinkR{}{}` les liens sont actifs, ce qui n'est pas le cas avec la branche publiée.

**Comment by maieul** [comment]
il me faut un MWE, l� je peux pas reproduire...

**Comment by ralessi** [comment]
Cela ne viendrait-il pas des `\elesection \eledchapter`? Par exemple au début de mon traité, j'ai un `\eledchapter` suivi d'un `\eledsection`, et le décalage est ensuite de 2 lignes partout dans les pages suivantes: 3-->5.

Puis à la deuxième section du traité, je n'ai qu'un `\eledsection`: et le décalage systématique est ensuite de 1 ligne systématiquement: 4--5.

Évidemment, à chaque nouvelle section, je redémarre un environnement \Pages dans un fichier séparé.

Je vais essayer de partir de là pour te faire un mwe.

**Comment by maieul** [comment]
je viens de faire des tests. Oui je pense que cela vient du eledsection. Je crois savoir le commit qui a provoqu� cela. J'ai trop voulu simplifier sans faire de tests...

**Comment by ralessi** [comment]
Ah, ok. Je vais en tout cas bien réviser mes fichiers, car je ne les ai plus touchés depuis pas mal de versions, c'est-à dire avant l'apparition des `\eledsection`. J'avais aussi \Pages avant la fermeture de l'environnement et pas après. Il faut que je remette tout à jour.

Je suis dessus. Une fois que c'est bon, je t'envoie un possible mwe.

**Comment by maieul** [comment]
essai la nouvelle version que j'ai envoy�

**Comment by ralessi** [comment]
même branche 241?

**Comment by maieul** [comment]
oui..

**Comment by ralessi** [comment]
ok. J'y vais.

**Comment by maieul** [comment]
ma politique : une branche par issue. Lorsqu'un probl�me est r�solue on merge la branche dans la branche de release (qui porte le num�ro de la future version). Lorsqu'on estime une branche stable ou avec suffisament d'ajoute, on merge dans master. On tague alors la version.

**Comment by ralessi** [comment]
Il va falloir que je m'inspire de tout ça, même si eledmac est d'une complexité effrayante, alors que je ne ferai que des choses assez simples.

**Comment by maieul** [comment]
si tu fais un luaarabtex, je suis pas s�r que tu aura affaire qu'� des choses simples...

**Comment by maieul** [comment]
apr�s c'est ma politique pour des projets publics. Pour mes projets perso (genre ma th�se) je me contente de commiter au fur et � mesure et de taguer les versions que j'envois � mon directeur...

**Comment by ralessi** [comment]
Je peux dire que les lectures que j'ai faites jusqu'ici me montrent que ce sera compliqué en effet! Mais c'est indispensable. luatex doit avoir son arabtex.
Tu fais aussi ta thèse sur git?

**Comment by maieul** [comment]
oui. ca me permet 
1) de garder facilement un �tat de ce que j'envoie � chaque prof (bon, en fait c'est pas vrai parce que je tag pas mes packages auxiliaires, mais au moins sur le contenu)
2) d'avoir une sauvegarde distante des donn�es (j'ai un depot git priv� h�berg� par un copain)
3) de me forcer � �crire par morceau logique, pour avoir des commits unitaires.

**Comment by ralessi** [comment]
C'est très intéressant. Et mon travail devient tellement compliqué que cela me donne des idées. En fait, je synchronise mes fichiers sur un serveur personnel qui est chez moi et sur lequel j'héberge aussi des sites d'associations. J'en maintiens aussi un ou deux (par exemple http://www.aplaes.org j'ai réussi à trouver un webmestre, mais je maintiens toujours et j'ajoute des nouvelles fonctions quand on me le demande, comme pour les revues, etc.)
Je synchronise avec rsync, et je conserve toujours 4 sauvegardes avec mon script. C'est pluôt rudimentaire...
Je vais voir comment monter un dépôt git pour la suite, et cela dès le mois de mars.

**Comment by ralessi** [comment]
Pour la dernière 241, ça marche! J'ai juste une page de fin de section qui ne s'est pas remise à 0 et dont le 1er numéro de ligne est 15, mais qui suit bien la page d'avant. Je vais recompiler encore pour voir.

**Comment by ralessi** [comment]
Mais j'ai toujours les `\hyperlinkR{}{}`. Les liens sont actifs.

**Comment by maieul** [comment]
pour monter un depot git c'est assez simple : il faut
1) que git soit install� sur le serveur
2) que le serveur soit accessible en ssh, si possible via clef publique/priv�

Comme tu sera le seul utilisateur, pas la m�me de sa fatiguer avec des outils de gestion de comptes...

**Comment by maieul** [comment]
attend, je suis pas toujours certains de comprendre. Il me faut vraiment un MWE l�...

**Comment by ralessi** [comment]
Ça va aller vite. Le ssh sans mot de passe est déjà en place ;)

**Comment by ralessi** [comment]
Je t'envoie le mwe dans un instant.
Ce que je veux dire est qu'avec la dernière version tout fonctionne: les numéros sont en face des bonnes lignes, et les index renvoient aux bonnes pages et aux bons numéros de ligne.
On peut aussi cliquer sur les numéros dans les index, donc les hyperliens sont actifs et marchent parfaitement.
Mais quand on ouvre les fichiers `.ind`, on a ceci:
````
  \item ἄγω, \hyperlinkR{$&1568}{35-5}
  \item ἀδελφιδῆ, \hyperlinkR{$&581}{17-2}
  \item ἀδελφός, \hyperlinkR{$&1090}{27-5}
````
etc.
Je croyais qu'à la place de `\hyperlinkR{$&1568}{35-5}` on devrait avoir dans le fichier .ind: `\hyperlink{35-5}`.
C'était ce que je voulais dire. mwe dans 2 minutes.

**Comment by maieul** [comment]
alors si tu a un git dessus tu cr�e un depoi avec
git init --bare
et tu le clone en local avec
git clone user@serveur:cheminversledport

**Comment by ralessi** [comment]
Voici le mwe:
````
\documentclass{article}
\usepackage{fontspec}
\usepackage{amsmath}
\defaultfontfeatures{Ligatures=TeX}
\setmainfont{Linux Libertine O}

\usepackage{indextools}

\usepackage{eledmac}
\makeindex[name=latin, title={Index des mots}]
\makeindex[name=arabe, title={Index des mots arabes}]

\usepackage{hyperref}

\usepackage{polyglossia}
\setdefaultlanguage{french}
\setotherlanguage{arabic}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}
\usepackage[voc]{arabxetex}
\newcommand{\ta}{\textarab}
\robustify{\textarab}

\let\aemph\veryundefinedcommand

\begin{document}

\beginnumbering

\pstart Je ne \edindex[latin]{savoir}sais si cela va
\edindex[latin]{marcher}marcher... \ta{\edindex[arabe]{\ta{دخل}!f01@\ta{daxala}}daxala
  \edindex[arabe]{\ta{بسم}!f08@\ta{ibtasama}}mubtasimaN} \pend

\endnumbering

\printindex[latin]
\printindex[arabe]

\end{document}
````
Et le fichier latin.ind:
````
\begin{theindex}

  \item marcher, \hyperlink{$&2}{1-1}

  \indexspace

  \item savoir, \hyperlink{$&1}{1-1}

\end{theindex}
````

**Comment by ralessi** [comment]
Au fait, bien sûr que j'ai un git dessus! Je vais essayer ça.

**Comment by ralessi** [comment]
Mais c'est peut-être normal d'avoir `\hyperlink{$&2}{1-1}` dans `latin.ind`?

**Comment by maieul** [comment]
je vois pas le souci.
- \hyperlink est pour les pages de gauche ou pages de droite si pas en //
- \hyperlinkR est pour les pages de droite si en //

**Comment by ralessi** [comment]
Oui. Mais que voulais-tu dire ici: https://github.com/maieul/indextools/issues/1#issuecomment-75046773 ?

**Comment by ralessi** [comment]
Faisais-tu allusion aux marques des edlabel qui ne devraient pas apparaître?

**Comment by maieul** [comment]
c'�tait une erreur, je croyais que tu aurais du avoir \hyperlink, mais en fait le pb venait d'ailleury (en gros je ne placai pas l'�tiquette pour que hyperref trouve sa place)

**Comment by ralessi** [comment]
Donc alors tout est bon cette fois.

**Comment by ralessi** [comment]
Juste une question hors-sujet: l'option `parapparatus` sert bien à pouvoir faire des sauts de paragraphe dans les `\Aendnote`?

**Comment by maieul** [comment]
heu, ca sert pour les notes de bas de page. je ne sais pas pour les Aendnotes.

**Comment by maieul** [comment]
il y a tellement d'options que j'ai un peu du mal � suivre, m�me moi...

**Comment by ralessi** [comment]
C'est vrai!
Je n'ai pas essayé dans les notes de bas de page, mais dans les notes de fin, ça ne marche pas. Tout ce qu'on peut faire est aller à la ligne avec `\\`. `\par` ne marche pas non plus.

**Comment by maieul** [comment]
ouvre un autre ticket. Un ticket par probl�me, sinon je m'en sort pas ;-)

**Comment by ralessi** [comment]
En fait je construis mon commentaire, qui est continu à la fin, à l'aide de \Aendnote{\input{note-yxz.tex}}. Je ne sais pas si c'est une bonne méthode, mais ça donne assez bien.
Fais-tu ainsi toi-même pour ton commentaire?

**Comment by ralessi** [comment]
Ok je vais ouvrir un ticket, mais je ne sais pas si c'est un problème!

**Comment by maieul** [comment]
je n'ai pas de commentaire continue. pour tout dire l'�dition de texte est une toute, toute petit partie de la th�se...

**Comment by maieul** [comment]
si ce n'est pas un probl�me, c'est une demande ;-)

**Comment by ralessi** [comment]
C'est fait. En tout cas, la nécessité de faire des apparats t'aura conduit vraiment très loin!
