### ISSUE TITLE
Sauts de paragraphe dans les `\Xendnote`

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#242]
Je me demande s'il est possible d'avoir des sauts de paragraphe dans les `\Xendnote`. L'option `parapparatus` ne le permet pas.

Tout ce qu'on peut faire est aller à la ligne avec `\\`. car `\par` ne marche pas non plus.

Mais est-ce un problème? Je ne sais pas.

**Comment by ralessi** [comment]
Je pose cette question car je dois après mon édition construire un commentaire continu sur des dizaines de pages. Il me semble que mettre le commentaire dans des notes de fin est une solution élégante car elle permet d'avoir un commentaire relié aux pages et aux lignes du texte commenté...

**Comment by maieul** [comment]
oui, tout � fait. et la technique du fichier inclus est une tr�s bonne technique je pense. Ca permet de garder un code lisible ...

Le 19 f�vr. 2015 � 20:00, Robert Alessi <notifications@github.com> a �crit :

**Comment by maieul** [comment]
bug assez simple. La branch issue242 doit l'avoir r�solu.

**Comment by ralessi** [comment]
En effet, ça marche!
