### ISSUE TITLE
\eledsections get repeated after one line in ledmac-1.18.0-1.12.0 

### ISSUE THREAD

**Issue by Latechneuse** [maieul/ledmac#243]
Hi Maïeul, 
in the ledmac-1.18.0-1.12.0 you sent me two days ago on Stackexchange (I mean this thread: http://tex.stackexchange.com/questions/227837/eledmac-eledpar-luatex-right-alignment-of-rtl-text-paragraphs-in-pages-envirome ), there is still a bug. 
If I'm using LuaTex + RTL typesetting (Syriac), \eledsection* and \eledsubsection* are now typesetted correctly on the right side, and the \ledsidenote{} command works as well. But an RTL \eledsection and \eledsubsection is *repeated* in the first line of the subsequent paragraph in a left-aligned way. 

See this MWE: 

```
\documentclass{scrartcl}
\usepackage{fontspec}

%To be tested with the ledmac-1.18.0-1.12.0 snapshot you sent me 
\usepackage{ledmacNeuB/eledmac}
\usepackage{ledmacNeuB/eledpar}

\newfontfamily\syriacfont
    [Script=Syriac, Scale=1.2, ] {estre.otf}

\newcommand{\textsyriac}[1] % Syriac inside LTR
	   {\bgroup\luatextextdir TRT\syriacfont #1\egroup}
\newcommand{\n}         [1] % for digits inside Arabic text
	   {\bgroup\luatextextdir TLT #1\egroup}

\newenvironment{syriac}     % Syriac paragraph
	   {\luatextextdir TRT\luatexpardir TRT\syriacfont}{}

\begin{document}

%% MWE 
  \begin{pages}
    \begin{Leftside}
    \begin{syriac}
    \beginnumbering
       \pstart
	   \eledsection*{\textsyriac{ollaH ܡܿܟܪܟܝ}}
       \pend
    
       \pstart
		1ܘܟܕ 2ܡܿܟܪܟܝ3ܢܢ ܐܪܟ4ܐܢܐ ܗ̄ 5ܡܘܪܐ6 ܗܿܝ ܩ7ܕܡܝܬܐ

		\n{X}
		\ledsidenote{Test source}
       \pend
    \endnumbering
    \end{syriac}
    \end{Leftside}
	
    \begin{Rightside}
    \beginnumbering
       \pstart
	   \eledsection*{English headline} 
       \pend
       \pstart
		Some english text. 
       \pend
    \endnumbering
    \end{Rightside}
    
    \Pages
    \end{pages} 

\end{document}
```

**Comment by maieul** [comment]
please try branch issue243

**Comment by Latechneuse** [comment]
It seems to be fixed on the level of the MWE. Thanks! 
(I will run it on a bigger document this afternoon).

**Comment by maieul** [comment]
you'r welcome. Send to 1.18.0-1.12.0.

**Comment by Latechneuse** [comment]
All right, after testing it on a whole chapter I can confirm that the issue is fixed. 

There is another point maybe worth mentioning: The right-alignment of \eledsection* and \eledsubsection* works now, but only for the *-variant of the commands. Numbered sections in RTL text with \eledsection or \eledsubsection are still printed left-aligned. 
I noticed this only accidentally as I'm not using numbered sections. I'm not sure how easily this can be fixed as well. If you want I can do further testing of course!

**Comment by maieul** [comment]
i have corrected for numbered section. I am still awaiting english correction to publish...

**Comment by Latechneuse** [comment]
Yes, the numbered headlines appear right aligned now in the 1.18.0-1.12.0 branch. 
Maybe there is still a small issue with horizontal spacing though: The number is not fully aligned to the right endge of the column; and there is no horizontal space between number and text of the headline. It seems as if the number is put in some kind of box but with left-alignment within the box (instead of right alignmnet): 

![gh1](https://cloud.githubusercontent.com/assets/11145425/6329174/54573e10-bb6e-11e4-9afc-58fd8ba2f142.jpg)

**Comment by maieul** [comment]
these 2 issue are not dependant of eledmac/eledpar.

try

````
\documentclass{scrartcl}
\usepackage{fontspec}
\parindent=0pt
\usepackage[showframe]{geometry}
%To be tested with the ledmac-1.18.0-1.12.0 snapshot you sent me 

\newfontfamily\syriacfont
[Script=Syriac, Scale=1.2, ] {estre.otf}

\newcommand{\textsyriac}[1] % Syriac inside LTR
{\bgroup\luatextextdir TRT\syriacfont #1\egroup}
\newcommand{\n} [1] % for digits inside Arabic text
{\bgroup\luatextextdir TLT #1\egroup}

\newenvironment{syriac} % Syriac paragraph
{\luatextextdir TRT\luatexpardir TRT\syriacfont}{}

\begin{document}
\begin{syriac}
\section{\textsyriac{ܡܿܟܪܟܝ}}

1ܘܟܕ 2ܡܿܟܪܟܝ3ܢܢ ܐܪܟ4ܐܢܐ ܗ̄ 5ܡܘܪܐ6 ܗܿܝ ܩ7ܕܡܝܬܐ

\end{syriac}
\end{document}
`````

**Comment by Latechneuse** [comment]
Yes I see. Thank you!
I will ask on stackexchange maybe someone knows at which point the section command itself needs modification in LuaTeX RTL environments.

**Comment by maieul** [comment]
if you modify section command inside LuaTeXRTL  env, use \patchmd and not \renewcommand, as eledmac/eledpar itself modify them in eledmac section.

**Comment by Latechneuse** [comment]
Ok :) 
Excellent work, thank you very much. I'm glad I can typeset the unnumbered headlines correctly now (and I have only unnumbered headlines).

**Comment by Latechneuse** [comment]
Note: I posted the solution to this last problem (which was not eledmac dependent) in http://tex.stackexchange.com/questions/229698/luatex-rtl-text-wrong-horizontal-spacing-in-headlines

**Comment by maieul** [comment]
ok, and so it's also working with eledmac ?

**Comment by Latechneuse** [comment]
Uff, no, it doesn't. This starts being weired now. Do you explicitly use the \luatextextdir TRT commands in the package? 
Do you want a new MWE?

**Comment by maieul** [comment]
yes, please, provides a new MWE. On a new issue.

**Comment by Latechneuse** [comment]
OK :)
