### ISSUE TITLE
LuaTeX and RTL text: \eledsections have wrong hspace 

### ISSUE THREAD

**Issue by Latechneuse** [maieul/ledmac#244]
Numbered \eledsection in RTL (syriac, arabic) text environments within the eledmac pages structure: 
The section number is not typesetted RTL. This results 1) in a wrong order of secion number and subsection number and 2) in the horizontal space being placed on the wrong side of the number (it should be between headline and number, not to the right of the number). 

Using a syriac text environment in normal text (outside eledmac structures), this works correctly if \luatexbodydir TRT is used. However, this does not take effect within the \eledsecion and \eledsubsection commands. 

The following MWE compares all scenarios. 

```
\documentclass{scrartcl}
\usepackage{fontspec}

% To be used with eledmac 1.18.0-1.12.0 
\usepackage{ledmac20150223/eledmac}
\usepackage{ledmac20150223/eledpar}

\newfontfamily\syriacfont
    [Script=Syriac, Scale=1.2 ]{estre.otf}

\newcommand{\textsyriac}[1] % Syriac inside LTR
	   {\bgroup\luatextextdir TRT\syriacfont #1\egroup}
\newcommand{\n}         [1] % for digits inside Arabic text
	   {\bgroup\luatextextdir TLT #1\egroup}
\newenvironment{syriac}     % Syriac paragraph
	   {\luatextextdir TRT%
	   \luatexpardir TRT%
	   \luatexbodydir TRT% This solves the hspacing problem for normal
				% \sections but has no effect on \eledsection 
	   \syriacfont}{}

\setlength{\parindent}{0pt}

\begin{document}

\section{English section} 

Horizontal spacing in english headlines works well. Also in Syriac headlines
as can be seen here: 

\begin{syriac}
	\section{\textsyriac{ܡܿܟܪܟܝ}}
	\subsection{\textsyriac{ܡܿܟܪܟܝ}}
	1ܘܟܕ 2ܡܿܟܪܟܝ3ܢܢ ܐܪܟ4ܐܢܐ ܗ̄ 5ܡܘܪܐ6 ܗܿܝ ܩ7ܕܡܝܬܐ
\end{syriac}

\section{This is just to increase section counter}

\begin{pages}
\begin{Leftside}
	\begin{syriac}
	\beginnumbering
	\pstart
	       	\begin{syriac}
			\eledsubsection{\textsyriac{ܡܿܟܪܟܝ}}
	       	\end{syriac}
	\pend
    
	\pstart
		\begin{syriac}
			1ܘܟܕ 2ܡܿܟܪܟܝ3ܢܢ ܐܪܟ4ܐܢܐ ܗ̄ 5ܡܘܪܐ6 ܗܿܝ ܩ7ܕܡܝܬܐ
		\end{syriac}
	\pend
	\endnumbering
	\end{syriac}
	\end{Leftside}
	
	\begin{Rightside}
	\beginnumbering
	\pstart
		\eledsubsection{English subheadline} 
	\pend
    
	\pstart
		But in syriac text within eledmac pages structure, the
		horizontal space next to the headline number is on the wrong
		side. 
	\pend
	\endnumbering
	\end{Rightside}
    
	\Pages
	\end{pages} 

\end{document}
```
Here the correct typesetting of the upper part of the MWE (non-eledmac case): 
![gh3](https://cloud.githubusercontent.com/assets/11145425/6346581/7a22864c-bc11-11e4-980a-857a0282dee7.jpg)

Here the incorrect typesetting using \eledsubsection: 
![gh5](https://cloud.githubusercontent.com/assets/11145425/6346604/b9c1641c-bc11-11e4-8aa4-bde3be30c757.jpg)

**Comment by maieul** [comment]
please try issue244.

**Comment by Latechneuse** [comment]
Yes it seems to work now! (tested on an extended MWE)

**Comment by maieul** [comment]
I will publish it saturday.
