### ISSUE TITLE
\boxlinenum for endnotes

### ISSUE THREAD

**Issue by mepherl** [maieul/ledmac#249]
This is a feature-request: It would be wonderful to have \boxlinenum for endnotes as well! 

Maieul, thanks for your wonderful work! It saved a lot of time for me!

**Comment by maieul** [comment]
please send a MWE example (I could do it, but I have not a lot of time !)

**Comment by mepherl** [comment]
This would be a MWE:

\documentclass{scrbook}

\usepackage{eledmac}


\begin{document}

\beginnumbering

\pstart

What I try to \edtext{achieve}{\Aendnote{acheave}} is a list of 
corrections \edtext{to}{\linenum{|4|||9}\Aendnote{ot}} the main text, 
where the linenumbers are printed in a seperate column, just as boxline 
does with footnotes.

\pend

\endnumbering

\doendnotes{A}

\end{document}


Thank you very much!
Martin



Am 12.03.2015 um 14:19 schrieb Maïeul Rouquette:
> please send a MWE example (I could do it, but I have not a lot of time !)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/maieul/ledmac/issues/249#issuecomment-78477308>.
>

-- 
Martin Anton Müller
Projekt: Arthur Schnitzler - Kritische Edition (Frühwerk)
Institut für Germanistik
Universitätsring 1
A-1010 Wien
Tel.: + 43 1 4277 42198
E-Mail: martin.anton.mueller@univie.ac.at

**Comment by maieul** [comment]
please try branch issue249 (read https://github.com/maieul/ledmac#debug to know how to do it). It provides a new command \boxXendlinenum, similar to \boxlinenum, but for end notes.

**Comment by maieul** [comment]
I have also integrated the correction for \inplaceofnumber. `\symlinenum{}` is no more needed.

**Comment by mepherl** [comment]
Wow, both works! Fantastic! Thank you for the fast help! You're incredible!

**Comment by maieul** [comment]
your'r welcome. I will release it next thursday.
