### ISSUE TITLE
Spurious space after heading

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#251]
There's a weird little space after the heading on pdf-page 2 in the following example, when I do not have the \newpage in line 11, so the lines on left and right pages are not exactly on the same position. When the \newpage is there, there's no such problem.

Am I doing something wrong? Is it a bug?

I'm using the latest version eledmac 1.19.1 (thanks for the spurious-page-fix!) and the eledpar coming with that version (with pdflatex).

Here's the example:

```
\listfiles
\documentclass{book}
\usepackage[german]{babel} 
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{blindtext}
\usepackage{eledmac,eledpar}
\begin{document}
Ein einleitender Text.

\newpage
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
\section{Das erste Kapitel}

\subsection{Der erste Abschnitt}

Der Originaltext: \blindtext[2] Ja, das ist er!
\pend

\pstart
\subsection{Der zweite Abschnitt}

Der Originaltext: \blindtext[3] Ja, das ist er!
\pend
\endnumbering   
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
\section{Das erste Kapitel}

\subsection{Der erste Abschnitt}

Der übersetzte Tex, das ist er! \blindtext[4]\\
\skipnumbering
\pend

\pstart
\subsection{Der zweite Abschnitt}

Der übersetzte Text, das ist er! \blindtext[3]
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
```

**Comment by maieul** [comment]
About heading, please look at files examples/sections-with-critical-notes-in-parallel-pages.tex and sections-parallel-not-in-line-numbering

**Comment by baem2** [comment]
Ah, okay, I wasn't aware that one /must/ put them in the optional argument, I thought you just can choose between \eledchapter (with line numbers) and \chapter (without).

Seems to work fine. Thanks!

**Comment by maieul** [comment]
yes you must, because in other case eledmac try to split them as line
