### ISSUE TITLE
Critical footnotes with f. / ff.  and slash.

### ISSUE THREAD

**Issue by mepherl** [maieul/ledmac#252]
I needed to implement to "hacks" into eledmac as I have to follow a pre-existing layout. 

1.) Critical footnotes referencing more than one line should denote as "5f."/"5ff." instead of "5-6" or "5-9". This saves space and is common practice in German editions.

2.) I'm preparing an edition where a new chapter has been introduced in a later print of the book. This of course happens between lines. So if a new chapter is introduced after line 112 I don't have a lemma to attach this to. Instead it should read: "112/113 Chapter seperation introduced in 3rd edition".

I've got a working solution, which is not a good one: The first problem is easy, i use a counter for it. The second one was more difficult, i misused the value of the first pagemark and set it to -1.

```javascript
if (isAwesome){
  return true
}
\documentclass{scrbook}
\usepackage{eledmac}

\firstlinenum{0} \linenumincrement{1}

\newcounter{inbetween}

\makeatletter
\def\printlines#1|#2|#3|#4|#5|#6|#7|{%
\setcounter{inbetween}{#2}
\stepcounter{inbetween}
\begingroup
\setprintlines{#1}{#2}{#3}{#4}{#5}{#6}%
\ifnum#5>\value{inbetween}\hspace{-1em}{#2}ff. \else       % This line is new
\ifnum#5=\value{inbetween}\hspace{-0.5em}{#2}f. \else
\ifnum#1=-1 \hspace{-0.5em}{#2}/\arabic{inbetween} \else \ifnum#5=#2 \hspace{-0.5em}{#2} \fi \fi \fi
\endgroup}
\makeatother

\newcommand{\insertpartmark}{\edtext{}{\linenum{-1}\Afootnote[nosep]{\hspace{-1em}New chapter mark introduced in 3rd edition}}}

\begin{document}
\beginnumbering      
\pstart
\edtext{What}{\Afootnote{Whit}} a \edtext{piece}{\Afootnote{peace}} of work is man! how noble in reason! 
\pend
\pstart
Dann bekleidete sie mit seinen weichen, weiten Filz
pantoffeln, in denen sie versanken, \edtext{ihre Fuesschen,}{\Afootnote{test}}
welche von Kuessen verwundet waren, und stampfte gravitaetisch
mit einer sehr wuerdigen und kaiserlichen Miene und sang, indem sie mit dem Kopfe den Takt dazu pendelte, ein altes feierliches Kirchenlied. Aber plötzlich, aufrecht auf einem Beine, schnellte sie mit dem Schwunge des andern den Schuh hoch, um ihn durch eine flinke und zuversichtliche Gebaerde wieder aufzufangen. In dieser anmutigen Pose verweilte sie. Sie stiess den Laden nach dem Garten auf, aus welchem der Flieder suesse Gruesse schickte.{\insertpartmark}
\pend

\endnumbering
\end{document}

**Comment by maieul** [comment]
Thanks for your code from stackexchange.

As I understand you have four  needs.

1) Use f/ff. 

I could add this week-end such feature. But i don't understand why don't use it for 9/10

2) Use / instead of -, but I am not sur to understand if you need it. In this case, you should redefine \endashchar.

3) Allow to refers to a line where the edtext is not called. In this case, the best way is to use \edlable \xxref. I suppose you have somewhere the line 10 in your document.

4) Don't print space when lemma separator is not printed. In this case, the best way is to compensat the afterlemmaseparator by setting \inplaceoflemmaseparator{-0.5em}

Could you confirme I have well understand you're problem ? In this case I will post a more detailed answer in stackexchange.

**Comment by mepherl** [comment]
Dear Maïeul,

Am 17.03.2015 um 14:54 schrieb Maïeul Rouquette:
> 1) Use f/ff.
>
> I could add this week-end such feature. But i don't understand why 
> don't use it for 9/10
>
For once, because I have to, as I have to follow an existing layout. And 
because it is shorter, the linenumbers get quite high and there 
4454–4455 needs way more space than 4454f.

> 2) Use / instead of -, but I am not sure to understand if you need it. 
> In this case, you should redefine \endashchar.
>
That's true, I didn't think of that. But i need it only in the very rare 
moments, when a new chapter is introduced in a later edition.

To clarify an invented example:
===
1st edition:
line 1 Never while I live shall I lose the remembrance of
line 2 that horrible day on which I saw my father and
line 3 mother barbarously butchered before my eyes,
line 4 and my sister ravished.
line 6 When the Bulgarians retired we searched in vain

2nd edition:
Never while I live shall I lose the remembrance of that horrible day on 
which I saw my father and mother barbarously butchered before my eyes, 
and my sister ravished.

\chapter{16 What happened after the Bulgarians retired}

When the Bulgarians retired we searched in vain for my dear sister.
===
If I want to print the first edition and want to show that there is a 
new chapter introduced in a later edition i would have the following 
line in the critical apparatus:

5/6  2nd edition: "Chapter 16 What happened..."

> 3) Allow to refers to a line where the edtext is not called. In this 
> case, the best way is to use \edlable \xxref. I suppose you have 
> somewhere the line 10 in your document.
>
Yes, this makes sense! Thank you for pointing it out!

> 4) Don't print space when lemma separator is not printed. In this 
> case, the best way is to compensat the afterlemmaseparator by setting 
> \inplaceoflemmaseparator{-0.5em}
>
That makes good sense as well!
Could you confirme I have well understand you're problem ? In this case 
I will post a more detailed answer in stackexchange.

Yes, it seems you understood everything, or else I have been able now to 
clarify. Thank you for your help, which is greatly appreciated!
Best regards,
Martin

**Comment by maieul** [comment]
> 
> > 1) Use f/ff.
> >
> > I could add this week-end such feature. But i don't understand why 
> > don't use it for 9/10
> >
> For once, because I have to, as I have to follow an existing layout. And 
> because it is shorter, the linenumbers get quite high and there 
> 4454�4455 needs way more space than 4454f.
> 

what I don't understand, is why for case of the chapter break you use / and not ff. It seems in some specific case you need full reference, and not just with f.

In this case I could implemente
1) a \iftwolines hook. Used as \iftwoline{f.}.
2) a \ifmorethantwolines hook. Used as \ifmorethantwolines{ff.}.
3) [fulllines] option when  you don't want to use the f. or the ff.

**Comment by mepherl** [comment]
This implementations sound wonderful!

As for the difference between "f." and "/": This is an existing layout 
which I have to follow. But the reasoning behind it is somewhat sound: 
"f." for reference to words in two lines, "/" für stuff that happens 
between lines.

Am 17.03.2015 um 16:01 schrieb Maïeul Rouquette:

**Comment by maieul** [comment]
Ok, I will try to do it this week-end. It should be easy.

**Comment by mepherl** [comment]
I am astonished by your effort, you are doing a wonderful thing in 
keeping eledmac running! I appreciate it a lot!
Martin

Am 17.03.2015 um 16:49 schrieb Maïeul Rouquette:

**Comment by maieul** [comment]
could you try branch "issue252"? (read https://github.com/maieul/ledmac#debug to know how to test). I have implemented it.

I have just change the name of the two command. Now it is shorter : `\twolines`
`\morethantwolines`. See the file issue252.tex.

If I have a positive  answer tomorrow night, I could add it to the release of thursday.

**Comment by maieul** [comment]
ps : you have two account on tex.stackexchange. you should ask to merge them...

**Comment by mepherl** [comment]
I just did, thank you. I will check out your new implementations later today and get back to you! Thank you for doing it and for the incredible speed!

**Comment by mepherl** [comment]
yes, this works like a charm! thank you so much!
martin

Am 18.03.2015 um 00:54 schrieb Maïeul Rouquette:
>
> could you try branch "issue252"? (read 
> https://github.com/maieul/ledmac#debug to know how to test). I have 
> implemented it.
>
> I have just change the name of the two command. Now it is shorter : 
> |\twolines|
> |\morethantwolines|. See the file issue252.tex.
>
> If I have a positive answer tomorrow night, I could add it to the 
> release of thursday.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/maieul/ledmac/issues/252#issuecomment-82645431>.
>

-- 
Martin Anton Müller
Projekt: Arthur Schnitzler - Kritische Edition (Frühwerk)
Institut für Germanistik
Universitätsring 1
A-1010 Wien
Tel.: + 43 1 4277 42198
E-Mail: martin.anton.mueller@univie.ac.at

**Comment by maieul** [comment]
you're welcome. Should be published tomorrow. Please when it will be done, validate the answer in stackexchange.

**Comment by mepherl** [comment]
i sure will!

Am 18.03.2015 um 11:45 schrieb Maïeul Rouquette:
> you're welcome. Should be published tomorrow. Please when it will be 
> done, validate the answer in stackexchange.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/maieul/ledmac/issues/252#issuecomment-82888880>.
>

-- 
Martin Anton Müller
Projekt: Arthur Schnitzler - Kritische Edition (Frühwerk)
Institut für Germanistik
Universitätsring 1
A-1010 Wien
Tel.: + 43 1 4277 42198
E-Mail: martin.anton.mueller@univie.ac.at

**Comment by ingoboerner** [comment]
Dear @maieul,

sorry to bother you with this again, but I think, we have an issue, that is related to this thread. 

As @mepherl explained, that we have to distinguish between two separators in the line number: "–" and "/"

Until now, we only had the case, in which we changed it globally. But in a forthcoming volume we have to use both separators in one document:

We have to output something like this:

114f. hin und herführen. . . . .] hin und her fahren. . . . . MzN
201/202 Absatztrennung fehlt
513-515 von der Decke […] durch den Kopf] fehlt EA GW 

As a MWE:

\documentclass{scrartcl}
\usepackage[ngerman]{babel} 
\usepackage{reledmac}


\Xtwolines{f.}
\Xmorethantwolines{ff.}


%\renewcommand{\endashchar}{/} %Change the separator globally

%Manipulate line number: \linenum{|4|||7|||}, eg. \edtext{First line of text and\newline second line of text.}{\linenum{|4|||/5|||}\lemma{First line [\dots] second line of text.}\Afootnote[fulllines]{Text of footnote}} 
%There is no way, to change the separator...



\begin{document}
	
	\beginnumbering
	


	\pstart
	\edtext{First line of text,\newline second line of text and \newline third line of text.}{\lemma{First line [\dots] third line of text.}\Afootnote[fulllines]{Text of footnote 1}} 
	\pend
	
	
	\pstart
	\edtext{First line of text and\newline second line of text.}{\lemma{}\lemma{}\Afootnote[fulllines, nosep]{Text of footnote 2}} 
	\pend
	
	
	\pstart
	\edtext{First line of text,\newline second line of text and \newline third line of text.}{\lemma{First line [\dots] third line of text.}\Afootnote{Text of footnote 3}} 
	\pend
	\endnumbering
	\newpage
	\doendnotes{A}
	
\end{document}



In the second footnote I would like to change the separator from "–" to "/".
Is this possible? Shall I open a new issue for that?

Thanks!
Best, Ingo

**Comment by maieul** [comment]
you shall open a new issue, and link to this thread.
