### ISSUE TITLE
Feature: Create labels containing the \linenum info of a lemma

### ISSUE THREAD

**Issue by stenskjaer** [maieul/ledmac#254]
It can often be necessary to refer to a note in the apparatus / lemma with notes in the apparatus.
Would it be an idea to make an `\applabel` (or something) that can be used in the second argument of `\edtext` to refer to the linenum-info of the lemma?

Let me give an example:
```latex
\pstart 
Si propter indigentiam motoris, aut ergo \edtext{propter 
indigentiam}{\applabel{note1}\Afootnote{\emph{om.} M}} 
motoris primi aut appropriati.
\pend
```

Here the `\applabel` would create *two* labels called ([name]_beg and [name]_end or whatever) refering to the beginning and end of the lemma. So here `\lineref{note1_beg}` and `\lineref{note1_end}` would refer to the line numbers of the beginning and end of the lemma discussed in the apparatus.

In this way it would be possible to create simple and consistent references to passages treated in the apparatus without too many `\edlabel`s in the text.

**Comment by maieul** [comment]
I see. I would look this week-end.

**Comment by maieul** [comment]
Such feature could not work for the position of the anchor for hyperref package.

**Comment by stenskjaer** [comment]
I'm not sure I understand the message. Are you saying that it is not possible to implement the feature?

**Comment by maieul** [comment]
no. Just that such label could not work with the system of anchor of the hyperref package. That is, there won't be hypertext link on the \edlineref{sss:start}. Because I could add for the first line but not for the end.

**Comment by maieul** [comment]
I have pushed on branch issue254 such feature. Could you try? I have choose to use `:end` and `:start`.

**Comment by stenskjaer** [comment]
The MWE just gives the following error:
```latex
Runaway argument?
{\if@edtext@ \ifcsundef {the@label##1}{\csdef {the@label##1}{applabel\ETC.
! File ended while scanning use of \@argdef.
<inserted text> 
                \par 
l.4 \makeatletter
```

**Comment by maieul** [comment]
oups, it was a pastebine mistake. Should be solved now. I have added 
````
\appref{note1}

\apprefwithpage{note1}
````

which insert the reference with the start and end linenumber in the same way as in footnote or in endnote.

So if call \appref{note1} with a note in line 1-2, you will have 1-2, and if you dot it with a not in line 1 only, you will have 1.

**Comment by stenskjaer** [comment]
Yes! Certainly very elegant. I like this solution.
One note:
```latex
\newcommand*{\printnpnum}[1]{p.#1) }
```
Should probably be
```latex
\newcommand*{\printnpnum}[1]{p. #1}
```
or similar.

**Comment by maieul** [comment]
this question was already aborded in other post, and I said that, despite p. #1 will be better, I don't want to break compatibility. So juste renewcommand it and it's ok.

**Comment by stenskjaer** [comment]
A quick last question: Could we maybe make a prefix for the line number that depends on whether it refers to a single or more lines.
Just an example name:
```latex
\renewcommand*\apprefprefixsingle{line~}
\renewcommand*\apprefprefixmore{lines~}
```
So let's say `\applabel{note1}` outputs refers to line 43, then `\appref{note1}` it will output *line 43*, and if it refers to line 43--45, then `\appref{note1}` will output *lines 43--45*.

**Comment by maieul** [comment]
yes, it could. I am looking for a other issue, but could be done

**Comment by stenskjaer** [comment]
I have found a small problem in the new feature.
When you call `\appref`before the `\applabel` of that note has been defined in the text, you get the following error:
```latex
ABD: EverySelectfont initializing macros
! Undefined control sequence.
<argument> twolines@\@currentseries 
                                    
l.8 \appref{note1}
```

Compare the result of these two MWE's

```latex
\documentclass{article}

\usepackage[paperheight=5cm]{geometry}
\usepackage{eledmac}

\begin{document}

\appref{note1}

\apprefwithpage{note1}

\beginnumbering
\pstart \applabel{note1} Si propter
\edtext{indigentiam}{\lemma{lemma}\applabel{test}\Bfootnote{infinitatis
    P}} motoris, aut ergo \edtext{propter indigentiam et plus long
  parce qu'on veut tester plusieurs
  lignes}{\applabel{note1}\applabel{note1}\Afootnote{\emph{om.  } M}}
motoris primi aut appropriati.  
\pend
\endnumbering

\end{document}
```
and
```latex
\documentclass{article}

\usepackage[paperheight=5cm]{geometry}
\usepackage{eledmac}

\begin{document}

\beginnumbering
\pstart \applabel{note1} Si propter
\edtext{indigentiam}{\lemma{lemma}\applabel{test}\Bfootnote{infinitatis
    P}} motoris, aut ergo \edtext{propter indigentiam et plus long
  parce qu'on veut tester plusieurs
  lignes}{\applabel{note1}\applabel{note1}\Afootnote{\emph{om.  } M}}
motoris primi aut appropriati.  
\pend
\endnumbering

\appref{note1}.

\apprefwithpage{note1}

\end{document}
```
The first hits the error, while the second works fine.

**Comment by maieul** [comment]
oh, yes of course. There is a problem, the `\twolines` hooks, which could be use to print line as 1sq is for line in notes, not outside. I will correct it.

**Comment by maieul** [comment]
Now, this probel should be fixed. So if you use `\twolines{sq.}` or ` \twolinesappref{sq.}` a more than two lines reference will print the first line and then sq.

**Comment by maieul** [comment]
And now, the 
````
\renewcommand*\apprefprefixsingle{line~}
\renewcommand*\apprefprefixmore{lines~}
`````
feature should also work.

**Comment by stenskjaer** [comment]
This works very well. 
Thank you!

**Comment by maieul** [comment]
I have documented the new features. Could you check the handbook is understandable? You just have to dowload the new version of the branch, and run the eledmac.dtx file with pdflatex.

The features are documented in "10.3 References to lines commented in the apparatus"
