### ISSUE TITLE
LuaTeX and RTL text: line numbers of \eledsections appear on wrong side

### ISSUE THREAD

**Issue by Latechneuse** [maieul/ledmac#255]
Hi Maieul, 
there's one more issue with the typesetting of RTL headlines with LuaTeX. If I make line numbers appear on the inner side, the line numbers of \eledsection \eledsubsection \eledsubsubsection still appear on the outer side. Check the following MWE for demonstration: 

    \documentclass{scrartcl}
    \usepackage{fontspec}

    \usepackage{lipsum} 
    \usepackage{eledmac,eledpar}

    \newfontfamily\syriacfont
    [Script=Syriac, Scale=1.2 ]{estre.otf}
    
    \newcommand{\textsyriac}[1] % Syriac inside LTR
           {\bgroup\luatextextdir TRT\syriacfont #1\egroup}
    \newcommand{\n}         [1] % for digits inside Arabic text
           {\bgroup\luatextextdir TLT #1\egroup}
    \newenvironment{syriac}     % Syriac paragraph
           {\luatextextdir TRT\luatexpardir TRT\luatexbodydir TRT%
           \syriacfont}{}
    

    \linenummargin{inner} %line numbers on inner margin

    \setlength{\parindent}{0pt}
    
    \begin{document}
    
    \begin{pages}
    	\begin{Leftside}
    	\begin{syriac}
    	\beginnumbering
 
	\pstart 
    		\lipsum[5]
    	\pend
    
    	\pstart  %%% Here you can use either of the following three cases: 
    %		\eledsection*{Section}
    		\eledsubsection*{Subsection}
    %		\eledsubsubsection*{Sububsection}
	\pend

    	\endnumbering
    	\end{syriac}
    	\end{Leftside}
        
    	\begin{Rightside}
    	\beginnumbering

	\pstart
    		Hallo
    	\pend
    
	\pstart
    		Hallo 
    	\pend
    
    	\endnumbering
    	\end{Rightside}
    \end{pages} 
    \Pages
    \end{document}

![se-2015-03-20](https://cloud.githubusercontent.com/assets/11145425/6753613/9704ae70-cf17-11e4-83e4-28839640d130.jpg)

**Comment by maieul** [comment]
please try branch "issue255". I have also corrected the way line number is printed. That is "10" and not "01".

**Comment by Latechneuse** [comment]
It looks very good on the MWE, thank you! 
I will let my co-worker test it on a bigger project as well. As soon as I have the result I will confirm again. (May take until tomorrow.)

**Comment by maieul** [comment]
Ok, I don't think there is any reason to have a different behavior for a longer text. So I will do the merge with the develloper branch now, because I hope to release it tomorrow.
In any case, you could also made any new test. I will wait 4 pm before publishing� and even if I publish before the find a new bug, that doesn't matter. I have project for a new release next week.
