### ISSUE TITLE
\skipnumbering in long verses

### ISSUE THREAD

**Issue by tweh** [maieul/ledmac#257]
Hi,

it seems like the use of `\skipnumbering` in a verse which is long on one and short on the other side causes troubles with the syncing/numbering of the following verses. In fact if the verse is longer than one line the number is skipped for the first line only, as the following MWE shows in verses 3.6 and 5.3:

    \documentclass{scrbook}
    \listfiles
    \usepackage{eledmac}
    \usepackage[%
    %    shiftedpstarts% [2] disabling this
    ]{eledpar}
    
    \setstanzaindents{1,0}
    \setcounter{stanzaindentsrepetition}{1}
    \firstlinenum{1}
    \linenumincrement{1}
    
    \begin{document}
    \begin{pages}
    \begin{Leftside}
        \beginnumbering
        \stanza
        left verse 1.1 &
        left verse 1.2 &
        left verse 1.3 &
        left verse 1.4 &
        left verse 1.5 &
        left verse 1.6 &
        left verse 1.7 &
        left verse 1.8 &
        left verse 1.9 &
        left verse 1.10
        \&
    
        \stanza
        left verse 2.1 &
        left verse 2.2 &
        left verse 2.3 &
        left verse 2.4 &
        left verse 2.5 &
        left verse 2.6 &
        left verse 2.7 &
        left verse 2.8 &
        left verse 2.9 &
        left verse 2.10
        \&
    
        \stanza
        left verse 3.1 &
        left verse 3.2 &
        left verse 3.3 &
        left verse 3.4 &
        left verse 3.5 &
        \skipnumbering left verse 3.6 &
        left verse 3.7 &
        left verse 3.8 &
        left verse 3.9 &
        left verse 3.10
        \&
        
        \stanza
        left verse 4.1 &
        left verse 4.2 &
        left verse 4.3 &
        left verse 4.4 &
        left verse 4.5 &
        left verse 4.6 &
        left verse 4.7 &
        left verse 4.8 &
        left verse 4.9 &
        left verse 4.10
        \&
    
        \stanza
        left verse 5.1 &
        left verse 5.2 &
        \skipnumbering left long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long verse 5.3 &
        left verse 5.4 &
        left verse 5.5 &
        left verse 5.6 &
        left verse 5.7 &
        left verse 5.8 &
        left verse 5.9 &
        left verse 5.10
        \&
    
        \stanza
        left verse 6.1 &
        left verse 6.2 &
        left verse 6.3 &
        left verse 6.4 &
        left verse 6.5 &
        left verse 6.6 &
        left verse 6.7 &
        left verse 6.8 &
        left verse 6.9 &
        left verse 6.10
        \&
    
        \endnumbering
    \end{Leftside}
    \begin{Rightside}
    \firstlinenum{1}
    \linenumincrement{1}
        \beginnumbering
        \stanza
        right verse 1.1 &
        right verse 1.2 &
        right verse 1.3 &
        right verse 1.4 &
        right verse 1.5 &
        right verse 1.6 &
        right verse 1.7 &
        right verse 1.8 &
        right verse 1.9 &
        right verse 1.10
        \&
    
        \stanza
        right verse 2.1 &
        right verse 2.2 &
        right verse 2.3 &
        right verse 2.4 &
        right long  2.5 &
        right verse 2.6 &
        right verse 2.7 &
        right verse 2.8 &
        right verse 2.9 &
        right verse 2.10
        \&
    
        \stanza
        right verse 3.1 &
        right verse 3.2 &
        right verse 3.3 &
        right verse 3.4 &
        right verse 3.5 &
        \skipnumbering right long long long long long long long long long long long long long long long long long long long long long long long long long long long verse 3.6  &
        right verse 3.7 &
        right verse 3.8 &
        right verse 3.9 &
        right verse 3.10
        \&
    
        \stanza
        right verse 4.1 &
        right verse 4.2 &
        right verse 4.3 &
        right verse 4.4 &
        right verse 4.5 &
        right verse 4.6 &
        right verse 4.7 &
        right verse 4.8 &
        right verse 4.9 &
        right verse 4.10
        \&
    
        \stanza
        right verse 5.1 &
        right verse 5.2 &
        \skipnumbering right verse 5.3 &
        right verse 5.4 &
        right verse 5.5 &
        right verse 5.6 &
        right verse 5.7 &
        right verse 5.8 &
        right verse 5.9 &
        right verse 5.10
        \&
    
        \stanza
        right verse 6.1 &
        right verse 6.2 &
        right verse 6.3 &
        right verse 6.4 &
        right verse 6.5 &
        right verse 6.6 &
        right verse 6.7 &
        right verse 6.8 &
        right verse 6.9 &
        right verse 6.10
        \&
        \endnumbering
    \end{Rightside}
    \Pages 
    \end{pages} 
    \end{document}

----

__Background:__ I came to this issue while trying to define a `\hidenumbering` macro which hides the number in the output but without changing the actual numbering of the line itself and the followings. This is necessary because I have marginal titles which overlap with the numbers otherwise.

I tried two definition wich worked except the above mentioned syncing problem …

Definition 1:

    \newcommand*{\hidenumbering}{%
       \ifledRcol
         \write\linenum@outR{\string\n@num}%
       \else
        \write\linenum@out{\string\n@num}%
       \fi
    }

Definition 2:

    \newcommand*{\hidenumbering}{%
       \skipnumbering%
       \advanceline{1}%
    }

For me the first definition seems better but I’d be glead to hear, what you think about them. And maybe you like to add (your optimized) definition of `\hidenumbering` to the package(s).

**Comment by maieul** [comment]
it won't be for tomorrow release ;-) But I hope to look at this point this week-end or the following week.

**Comment by tweh** [comment]
Thanks – There's no rush. I just thought it would be not to send to many updates to the (small) CTAN team … the publication where I use this is planned to be printed in autumn, so there’s enough time to find a solution ;-)

**Comment by maieul** [comment]
I try to do not more than one upload by week

**Comment by tweh** [comment]
Well thats quite frequently, and good for us users but I guess the team will be happier with less updates :-)

**Comment by maieul** [comment]
I think so, but there is also some time where I didnt push nothing � see the historic of the release

https://github.com/maieul/ledmac/releases

**Comment by maieul** [comment]
make a release is also long for me. I have to
1) ask for english syntaxis
2) set the checksum
3) write the changelog for annoucment
4) tag
5) run

**Comment by tweh** [comment]
Don’t get me wrong I did’t want to blame you for frequent updates and I know that the update process isn’t that easy, since I develop(ed) some packages too … I just wanted to say that the team at CTAN won’t mind less but bigger updates. :-)

**Comment by maieul** [comment]
this bug look quite hard to solve, but I think I will find � I have to think to a special way for skipnumbering for stanza

**Comment by tweh** [comment]
I feared that it won’t be easy to fix …

For my purpose I also tested to redefine `\ledlinenum` to prevent the output but I came to troubles with grouping, the redefinition either was globally from that point on affecting all following numbers or in a group and didn’t affect any number at all …

**Comment by maieul** [comment]
please try issue257 branch.

**Comment by tweh** [comment]
Hm  unfortunatly this doesn't work … in this simply document no line is skipped.

    \documentclass{scrbook}
    \usepackage{eledmac}
    \usepackage{eledpar}
    
    \setstanzaindents{1,0}
    \setcounter{stanzaindentsrepetition}{1}
    \firstlinenum{1}
    \linenumincrement{1}
    
    \begin{document}
    \begin{pages}
    \begin{Leftside}
        \beginnumbering
        \stanza
        left verse 1.1 \skipnumbering &
        left verse 1.2 &
        left verse 1.3 &
        left verse 1.4 &
        left verse 1.5 &
        left verse 1.6 &
        left verse 1.7 &
        left verse 1.8 &
        left verse 1.9 &
        left verse 1.10
        \&
        \stanza
        left verse 2.1 &
        left verse 2.2 &
        left verse 2.3 &
        left verse 2.4 &
        left verse 2.5 &
        left verse 2.6 &
        left verse 2.7 &
        left verse 2.8 &
        left verse 2.9 &
        left verse 2.10
        \&
        \endnumbering
    \end{Leftside}
    \begin{Rightside}
    \firstlinenum{1}
    \linenumincrement{1}
        \beginnumbering
        \stanza
        right verse 1.1 \skipnumbering &
        right verse 1.2 &
        right verse 1.3 &
        right verse 1.4 &
        right verse 1.5 &
        right verse 1.6 &
        right verse 1.7 &
        right verse 1.8 &
        right verse 1.9 &
        right verse 1.10
        \&
        \stanza
        right verse 2.1 &
        right verse 2.2 &
        right verse 2.3 &
        right verse 2.4 &
        right long  2.5 &
        right verse 2.6 &
        right verse 2.7 &
        right verse 2.8 &
        right verse 2.9 &
        right verse 2.10
        \&
        \endnumbering
    \end{Rightside}
    \Pages 
    \end{pages} 
    \end{document}

**Comment by maieul** [comment]
indeed, that work with long verse but not short.
see next week-end ...

**Comment by tweh** [comment]
Thanks, and: no hurry :-)

**Comment by maieul** [comment]
yes, but I don't like to have a too great queue ;-)

**Comment by maieul** [comment]
couly you try again? I think it should be ok. (in my test, that is !)

**Comment by tweh** [comment]
Sure … I'll take a look at it tomorrow in the train.

**Comment by tweh** [comment]
Yep  this seems to work in my test and in the real document too. I opened another issue for my problems with hiding a number (#267) and would be glad if you take a look at it :-)
