### ISSUE TITLE
Wrong column gap in two columned notes

### ISSUE THREAD

**Issue by tweh** [maieul/ledmac#259]
This priblem came up as a question on TeX.SX ([How to format eledmac’s two-column footnotes](http://tex.stackexchange.com/q/234258/4918)) but I guess it is a bug so it should be discussed here …

Acually I was only able to reproduce the to wide gap and not the zero width gap, shown in my TeX.SX question.

    \documentclass{scrbook}
    
    \usepackage{geometry}
    \geometry{%
    	textwidth=118mm,
    }
    
    \usepackage{etoolbox,eledmac}
    \patchcmd{\twocolfootfmtX}{\raggedright}{}{}{}
    \hsizetwocolX[C]{\dimexpr.5\columnwidth-.75em\relax}
    \hsizetwocol[C]{\dimexpr.5\columnwidth-.75em\relax}
    \foottwocolX{C}
    \let\footnote\footnoteC
    
    \usepackage{lipsum}
    \begin{document}
       Lipsum\footnote{\lipsum[1]} \lipsum[1]
       Lipsum\footnote{\lipsum[2]} \lipsum[3]
       Lipsum\footnote{\lipsum[1-4]} \lipsum[1]
    \end{document}

![too wide gap](https://cloud.githubusercontent.com/assets/3011538/6770190/5d836292-d0b9-11e4-8b35-f61cfd6dec98.png)

The problem doesn't show if I uncomment the `textwidth` setting from `\geometry` …

**Comment by maieul** [comment]
with the full example, the problem is easier to understand... I din't see in your previous screen shot the differenc between the max text and the note.

**Comment by maieul** [comment]
older versiont won't have this bug. I think to know which feature added this. I check.

**Comment by maieul** [comment]
please try issue259.

**Comment by tweh** [comment]
Thanks! Seems to fix the bug :-) At least my real document shows all columns with the correct gap.

But some comlumns got different legth, which is absolutly ok, but I wonder if I can influence this and make some manual adjustments … in this example it would be better if note 12 is completly in the left column and note 13 starts the right.

![example](https://cloud.githubusercontent.com/assets/3011538/6771936/58271772-d0ef-11e4-9729-d153d346e0a6.png)

**Comment by maieul** [comment]
it will be hard!

**Comment by tweh** [comment]
I feard that …
