### ISSUE TITLE
Some issues with \Xend...

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#271]
Sorry, it's me again. We found an issue with the new endnotes commands (and probably with the footnotes commands as well, I didn't test those, though).

The main problem occurs when the "lemma" is stretching over a page break. It ends up with something like "p. 1 l. 101p.2 l.sq." (beside the fact this is looking strange, the "–" is missing as well as the space after the second "l."). For this case I think it's best if it ignores all the \Xend settings and just writes it all out.

(Tested with the current 1.21)

**Comment by maieul** [comment]
please provides a MWE

**Comment by baem2** [comment]
Totally forgot about that, sorry!

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[series={A}]{eledmac}
\usepackage{blindtext}
\renewcommand*{\printnpnum}[1]{%
p.~#1, l.}
\Xendtwolines{sq.}
%\Xendmorethantwolines{sqq.}
\Xendtwolinesbutnotmore
\begin{document}
\beginnumbering
\pstart \edtext{Lorem}{\Aendnote{1ligne}\Afootnote{1ligne}} ipsum dolor amet, \edtext{sit transit gloria mundi, veni vidi vici, le petit chat est mort, trouver des exemples dans ma présence c'est compliqué.
 \edtext{Bon on continue.}{\Afootnote{Sur 2 lignes}\Aendnote{Sur 2 lignes}}
 Allez, je vais y aller ! Et ca recommence ! Franchement c'est fatiguant}{\Afootnote{Sur trois lignes}\Aendnote{Sur trois lignes}}
\pend

\pstart \blindtext \edtext{Lorem}{\linenum{|||2|8}%
\Aendnote{Test: Next page, smaller line number!}} \blindtext[2]
\pend

\pstart \blindtext \edtext{Lorem}{\linenum{|||3|45}%
\Aendnote{Test: Next page, same line number!}} \blindtext[2]
\pend

\pstart \blindtext \edtext{Lorem}{\linenum{|||3|77}%
\Aendnote{Test: Next page, line number plus one!}} \blindtext[2]
\pend

\pstart \blindtext \edtext{Lorem}{\linenum{|||4|110}%
\Aendnote{Test: Next page, higher line number!}} \blindtext[2]
\pend

\endnumbering

\doendnotes{A}
\end{document}
```

**Comment by maieul** [comment]
it should be very easy. But it's Easter Week-end. So Thursday ;-)

**Comment by baem2** [comment]
Cool! Have a nice Easter week-end!

**Comment by maieul** [comment]
I have 
1) corrected the default result
2) added \Xendtwolinesonlyinsamepage feature: if `\Xendtwolinesonlyinsamepage` is called, the \Xendtwolines will be available only for line in the same page.

Please try branch issue271

**Comment by baem2** [comment]
Oh, I just see you've done some changes here.

With \Xendtwolinesonlyinsamepage it is working for me exactly as expected. Thank you very much!

When \Xendtwolinesonlyinsamepage is not set, but \Xendtwolinesbutnotmore is set, there are problems with the examples "Next page, smaller line number", "Next page, same line number", "Next page, line number plus one": In these examples it puts "sq", while it's a lemma that reaches somewhere on the next page. "Next page, higher line number" is working fine anyway.

I think \Xendtwolinesonlyinsamepage should be automatically activated by \Xendtwolinesbutnotmore.

One little thing that has not been fixed is the fact that in the example there's no space after the second "l." when the lemma reaches over more than one page (even when all \Xend... is not in use). I could open a separate issue for that if you prefer.

**Comment by maieul** [comment]
please open a separate issue for the last problem. One issue by issue ...

**Comment by maieul** [comment]
"I think \Xendtwolinesonlyinsamepage should be automatically activated by \Xendtwolinesbutnotmore."

no, I prefer not to automatically activate separate hooks. People will read the handbook...

**Comment by maieul** [comment]
"Next page, smaller line number!" "Next page, same line number!" "Lorem Test: Next page, line number plus one!" is non sens if you don't use lineation by page... And if you use it, all is working (see this example https://github.com/maieul/ledmac/blob/5ca9b5e9d761cfef604a353b546e0abb542dd135/issue271.tex with the last version of branch issue271"

**Comment by baem2** [comment]
Okay, thank you again! This issue can be closed then.

**Comment by maieul** [comment]
ok, thanks. Closing will be done later, when the new version will be released
