### ISSUE TITLE
AtEveryPend causes autopar to "explode"

### ISSUE THREAD

**Issue by sk4p** [maieul/ledmac#273]
I'm trying to use a vskip in AtEveryPend to put a small skip between paragraphs.

Try the first MWE below with the \AtEveryPend line in the preamble commented out, and it works correctly.  But with the command there, it chokes.  It prints the first paragraph, then the numbers for a ton of empty paragraphs until the stack fills up, and the second and subsequent paragraphs never render.  It looks something like:

```
1. Paragraph 1 goes here.
2.
3.
4.
5.
[...]
2458.
```
Here's the broken MWE.
```
\documentclass{book}
\usepackage[series={A}]{eledmac}
\AtEveryPend{\vskip 5ex}

\begin{document}

\begingroup
\beginnumbering
\numberpstarttrue

\autopar

Paragraph 1 goes here.

Paragraph 2 goes here.

\endnumbering
\endgroup
\end{document}
```
The second MWE, for your convenience, is the same, but using explicit \pstart\pend pairs.  Even with the AtEveryPend, it works cleanly.
```
\documentclass{book}
\usepackage[series={A}]{eledmac}
\AtEveryPend{\vskip 5ex}

\begin{document}

\begingroup
\beginnumbering
\numberpstarttrue

\pstart
Paragraph 1 goes here.
\pend

\pstart
Paragraph 2 goes here.
\pend

\endnumbering
\endgroup
\end{document}
```

**Comment by maieul** [comment]
This issue was solved in the development branch. Please use branch 1.21.0-1.15.0

**Comment by sk4p** [comment]
This fixes the "autopar blows up" problem itself, but now I find that the indentation differs on the first paragraph:

http://imgur.com/xzprJUV

(Adding a paragraph 3 and 4, they have the same indent as 2.)

Interestingly when I test this with eledpar on facing pages, the indentation is _correct_ on both pages!

**Comment by maieul** [comment]
try branch issue273

**Comment by sk4p** [comment]
issue273 fixes the indentation and autopar continues to work correctly.  Thanks.

**Comment by maieul** [comment]
you'r welcome. Will be release soon
