### ISSUE TITLE
eledmac/par and linespread

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#274]
Dear M.,

sorry that we're bothering you again, we found another issue.

When there are symbols under letters, it can happen that eledmac/par raises the line spread, for example with \d{g}. Usually, it seems to just ignore that and always keep the line spread. Could you please have a look?

Here's an example with code (commented out) to try to improve the situation:
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[series={A}]{eledmac}
\usepackage{eledpar}
\usepackage{blindtext}
% \renewcommand{\d}[1]{%
% \ooalign{#1\cr\hfil\raisebox{-.78ex}{.}\hfil}%
% }
% \linespread{%
% % 1.135%so reicht's mit normalem \d
% 1.113%so reicht's mit umdefiniertem \d
% }
\begin{document}
\noeledsec
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart \blindtext Original text with dot-below accents: \d{a}, \d{g}. \blindtext Original text with dot-below accents: \d{a}, \d{g}. \blindtext
\pend
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\pstart  \blindtext Translation without dot-below accents: a, g. \blindtext Translation without dot-below accents: a, g. \blindtext
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
```

In this little example you can see that in normal circumstances the line spread just stays the same.
```
\documentclass{article}
\usepackage[german]{babel}
\usepackage[utf8]{inputenc}
\usepackage{blindtext}
\begin{document}
\blindtext Originaltext mit Unterpunkten: \d{a}, \d{g}. \blindtext Originaltext mit Unterpunkten: \d{a}, \d{g}. \blindtext
\end{document}
```

**Comment by maieul** [comment]
sorry, I don't see or understand your problem ...

**Comment by baem2** [comment]
Okay, I'm trying to be a bit more elaborate.

If you pdflatex the example, the line spread between line 10 and line 11 (and between 22 and 23) is bigger than for the other lines, which leads to the fact that all following lines are no longer on the same height as on the right page.

The line spread is bigger because of \d{g}. In my second example, without eledmac/par, the line spread stays the same even if \d{g} is used.

Please let me know when there are any questions about this problem.

**Comment by maieul** [comment]
actually, eledmax and eledpar are designed to work with an uniform linespread.

I could look for it, but it will be for next release. For now, I just want to close 1.21.0 release

**Comment by baem2** [comment]
Sure, no hurries with this one.

The wanted behaviour are uniform lines, but for some reason eledmac/par is producing a bigger spread in example one. The second example shows that the lines keep the same spread without eledmac/par.

**Comment by maieul** [comment]
you can solve this issue by adding 

\let\ledstrutL\relax
\let\ledstrutR\relax

in your preamble. 

I don't know why these strut why added by Peter Wilson in ledpar. But it seems that is the origin of problem.

**Comment by baem2** [comment]
That's working, thanks!

**Comment by maieul** [comment]
that is nice. However, Peter Wilson does not remember why it add this feature. I will ask for more test before deleting this.

**Comment by maieul** [comment]
no bad answer, I integrate it in the main code.

**Comment by baem2** [comment]
Great, thanks!
