### ISSUE TITLE
Endnotes: Lemmata and spaces

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#275]
In endnotes, when a lemma is reaching over more than one page, there's a problem with the spacing: With out any changes, it looks like this:

p.1  11–p.2 8

Note that after p.1 there are two spaces, after p.2 there's only one.

If you now redefine the macro like this:
```
\renewcommand*{\printnpnum}[1]{%
p.~#1, l.}
```
You'll have one space after p.1 and no spaces after p.2.

Example code:
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[series={A}]{eledmac}
\usepackage{blindtext}
%\renewcommand*{\printnpnum}[1]{%
%p.~#1, l.}
\begin{document}
\beginnumbering
\pstart \blindtext \edtext{Lorem}{\linenum{|||2|8}%
\Aendnote{Test: Next page, smaller line number!}} \blindtext[2]
\pend

\pstart \blindtext \edtext{Lorem}{\linenum{|||3|45}%
\Aendnote{Test: Next page, same line number!}} \blindtext[2]
\pend

\pstart \blindtext \edtext{Lorem}{\linenum{|||3|77}%
\Aendnote{Test: Next page, line number plus one!}} \blindtext[2]
\pend

\pstart \blindtext \edtext{Lorem}{\linenum{|||4|110}%
\Aendnote{Test: Next page, higher line number!}} \blindtext[2]
\pend

\endnumbering

\doendnotes{A}
\end{document}
```

Could you please have a lookt into this?

**Comment by maieul** [comment]
please try branch issue275, which fixes this (historic !) spurious space

**Comment by maieul** [comment]
please send by a feedback quickly. I would like to pre-release tomorrow

**Comment by baem2** [comment]
Fix confirmed, thank you very much!

**Comment by baem2** [comment]
D'oh, we found an issue with the new code. It has probably nothing to do with issue 275, but it is at least in the code of branch issue275 (and probably more branches).

The "sections" are no longer on the same height left/right.

Try this example (it's not about my example, it also happens with sections-parallel-not-in-line-numbering.tex when I try with the new code):
```
\documentclass{book}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[series={A}]{eledmac}
\usepackage{eledpar}
\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart[\section{Das erste Kapitel}]

Original text: Ja, das ist er!
\pend
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart[\section{Das erste Kapitel}]

Der übersetzte Tex, das ist er!
\pend
\endnumbering
\end{Rightside}
\end{pages}

\Pages
\end{document}
```

**Comment by maieul** [comment]
please open ONE issue by problem, and don't continue issue for an other problem...

**Comment by baem2** [comment]
Sorry, I was unsure if it is related, as it only happens in the new code. I'm gonna open a new one!
