### ISSUE TITLE
\section has extra space on right page

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#276]
D'oh, we found an issue with the new code. It has probably nothing to do with issue 275, but it is at least in the code of branch issue275 (and probably more branches).

The "sections" are no longer on the same height left/right pages.

Try this example (it's not about my example, it also happens with sections-parallel-not-in-line-numbering.tex when I try with the new code):
```
\documentclass{book}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[series={A}]{eledmac}
\usepackage{eledpar}
\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart[\section{Das erste Kapitel}]

Original text: Ja, das ist er!
\pend
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart[\section{Das erste Kapitel}]

Der übersetzte Tex, das ist er!
\pend
\endnumbering
\end{Rightside}
\end{pages}

\Pages
\end{document}
```

**Comment by maieul** [comment]
please try issue276

**Comment by baem2** [comment]
As far as I can see, this issue is fixed and all the other/new features seem to work really fine. Thank you very much!

**Comment by maieul** [comment]
nice, closing this issue.

the 1.21.0 could be released soon, after english correction
