### ISSUE TITLE
Brackets in endnotes

### ISSUE THREAD

**Issue by annazago86** [maieul/ledmac#282]
Bonjour!
Is it possible to put bracket (if needed) in \Aendnote, \Bendnote, and so on?
This is very easy with \Afootnote, \Bfootnote, etc., but I can't find a way to solve the problem with something similar for endnotes (something like \Aendnote{note} vs \Aendnote[nosep]{note}).

Thank you very much for your excellent work!

**Comment by maieul** [comment]
I will look for it this week-end.

**Comment by maieul** [comment]
please try the branch issue282. This branch provides a new command
`\Xendlemmaseparator`, that you can use with

`\Xendlemmaseparator{\rbracket}` for example to add the right bracket (as for critical footnotes).

As for footnote, you can use a optional argument to this command to enable it only for one series.

use `\Xendbeforelemmaseparator` / to add more space before and `Xendafterlemmaseparator` to add more space after (default : 0.5em). 

If you use [nosep] option in a `\Aendnote` the separator will be deleted for this particular note. In this case a space of 0.5 em will be add instead, but you can use `Xendinplaceoflemmaseparator` to change it (note that 0.5em is keept because it was the previous value, and I don't want to break backward compatibility)

**Comment by annazago86** [comment]
Thank you! I followed the instruction I found on CTAN (I went to the project page, I chose the correct branch in the "branch" menu, I clicked on the cloud, in the right side, I ran the `.ins` files with pdflatex, to obtain the `.sty` files, I put the `.sty` files with mytest files and with the file called 'issue283.tex', in the same folder). I tried to compile the 'issue283.tex' file, but the result is 

This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./issue283.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
(c:/texlive/2014/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(c:/texlive/2014/texmf-dist/tex/latex/base/size10.clo)) (./eledmac.sty
(c:/texlive/2014/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(c:/texlive/2014/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(c:/texlive/2014/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(c:/texlive/2014/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(c:/texlive/2014/texmf-dist/tex/latex/xargs/xargs.sty)
(c:/texlive/2014/texmf-dist/tex/latex/etoolbox/etoolbox.sty
(c:/texlive/2014/texmf-dist/tex/latex/etex-pkg/etex.sty))
(c:/texlive/2014/texmf-dist/tex/latex/bigfoot/suffix.sty)
(c:/texlive/2014/texmf-dist/tex/generic/xstring/xstring.sty
(c:/texlive/2014/texmf-dist/tex/generic/xstring/xstring.tex))
(c:/texlive/2014/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
(c:/texlive/2014/texmf-dist/tex/latex/ms/ragged2e.sty
(c:/texlive/2014/texmf-dist/tex/latex/ms/everysel.sty)))
! Undefined control sequence.
<recently read> \Xendlemmaseparator 
                                    
l.3 \Xendlemmaseparator
                       {\rbracket}
? 
What am I doing wrong? I'm sorry I'm not able to help you in the best way, but I am quite inexperienced...
Thank you so much!
Anna




----Messaggio originale----

Da: notifications@github.com

Data: 18/04/2015 17.13

A: "maieul/ledmac"<ledmac@noreply.github.com>

Cc: "annazago86"<zagoa@libero.it>

Ogg: Re: [ledmac] Brackets in endnotes (#282)




please try the branch issue282. This branch provides a new command

\Xendlemmaseparator, that you can use with


\Xendlemmaseparator{\rbracket} for example to add the right bracket (as for critical footnotes).


As for footnote, you can use a optional argument to this command to enable it only for one series.


use \Xendbeforelemmaseparator / to add more space before and Xendafterlemmaseparator to add more space after (default : 0.5em). 


If you use [nosep] option in a \Aendnote the separator will be deleted for this particular note. In this case a space of 0.5 em will be add instead, but you can use Xendinplaceoflemmaseparator to change it (note that 0.5em is keept because it was the previous value, and I don't want to break backward compatibility)

**Comment by maieul** [comment]
hum, when did you make the test? maybe you have not the last zip file.

in local, all is working

**Comment by annazago86** [comment]
Sorry, my mistake! I tried again and it works perfectly!
Thank you very much!

Have a nice sunday,
Anna





----Messaggio originale----

Da: notifications@github.com

Data: 18/04/2015 23.04

A: "maieul/ledmac"<ledmac@noreply.github.com>

Cc: "annazago86"<zagoa@libero.it>

Ogg: Re: [ledmac] Brackets in endnotes (#282)



hum, when did you make the test? maybe you have not the last zip file.



in local, all is working

**Comment by maieul** [comment]
you'r welcome.
