### ISSUE TITLE
Pararaphed endnotes

### ISSUE THREAD

**Issue by annazago86** [maieul/ledmac#283]
Bonjour!
Is it possible to paragraph \Aendnote, \Bendnote, and so on?
This is very easy with \footparagraph{A}, \footparagraph{B} and so on, but I can't find a way to solve the problem with something similar for endnotes.

Thank you very much again for your excellent work!

**Comment by maieul** [comment]
the new version of eledmac 1.21.0, which has been published on CTAN two days ago allow it, with the  option parapparatus

**Comment by annazago86** [comment]
I really thank you for your answers: I succeded in installing the updated package, and I solved the problem of the double \Xendnote (issue #284)!
Issue #283 about paragraphed endnotes was badly formulated (my fault, sorry!): I don't know why, but I can only obtain paragraphed \Xendnotes, which is not what I want... I posted a MWE here (http://www.guitex.org/home/it/forum/14-edizioni-critiche/100964-ancora-su-problemi-di-formattazione-nelle-endnotes#100972).

I will be very grateful if you or anyone else could explain which is my error, because I'm pretty sure that it's my fault if it's not working!

Thank you very much for you kind help!
Have a nice day,
Anna





----Messaggio originale----

Da: notifications@github.com

Data: 15/04/2015 14.22

A: "maieul/ledmac"<ledmac@noreply.github.com>

Cc: "annazago86"<zagoa@libero.it>

Ogg: Re: [ledmac] Pararaphed endnotes (#283)



the new version of eledmac 1.21.0, which has been published on CTAN two days ago allow it, with the  option parapparatus

**Comment by maieul** [comment]
please try branch issue283 (which also includes code for #282).

It provides \Xendparagraph which make only one paragraph by series of notes.

Notes that \Xendparagraph can take as optional argument a comma separated list of series.

An horizontal space of 1em plus.4em minus.4em is inserted between each note.  You can change it using `Xendafternote`. You can also define a symbol as separator with `\Xendsep`.
