### ISSUE TITLE
Double \Xendnote in the same lemma

### ISSUE THREAD

**Issue by annazago86** [maieul/ledmac#284]
I think there's a problem with a double \Xendnote whitin the same couple \edtext + \Xendnote. For exemple, in \edtext{text}{\Aendnote{variant1}\Bendnote{variant2}} the \Aendnote works correctly, while the \Bendnote makes "variant2" figure inside the numbered text (without printing it in \doendnotes{B}).

Is there any problem with the syntax I used?
Thank you very much!

**Comment by maieul** [comment]
the version 1.21.0 has solved this problem. Actually, texlive is frozen, so you can't upgrade it via tlmgr but you can:
- dowload it on CTAN
- run the eledpar.ins and eledmac.ins file to obtain new .sty files
- put the in along your .tex file or in a local texmf folder. Read http://tex.stackexchange.com/a/1138/7712 for details.

If you use miktex, you should use package manager to update your file http://docs.miktex.org/manual/pkgmgt.html

**Comment by maieul** [comment]
and please next time provide a full MWE.
