### ISSUE TITLE
v21.1, \textbardbl as symbol in critical notes

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#288]
In the MWE the new eledmac v1.21 does not accept the symbol \textbardbl between two critical notes in the same line, as the prior versions did. Would it be better to insert another symbol? 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{lmodern}

\usepackage[series={A,B,C},noend,noeledsec]{eledmac}
\usepackage{eledpar}

\footparagraph{A}
\numberonlyfirstinline[A]
\symlinenum[A]{\textbardbl}

\begin{document}

\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
Memoria \edtext{humana}{\Afootnote{animalis}} \edtext{labilis}{\Afootnote{stabilis}} est.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Das menschliche Gedächtnis ist schwach.
\pend
\endnumbering
\end{Rightside}

\Columns
\end{pairs}

\end{document}

**Comment by maieul** [comment]
in general I use directley `$||$` however this bug is not normal. I am looking for it

**Comment by sonator** [comment]
A good solution, thank you!

	-----Original-Nachricht----- 

	Betreff: Re: [ledmac] v21.1, textbardbl as symbol in critical notes
(#288) 

	Datum: Sun, 19 Apr 2015 19:52:07 +0200 

	Von: Maïeul Rouquette <notifications@github.com> 

	An: maieul/ledmac <ledmac@noreply.github.com> 

	in general I use directley $||$ however this bug is not normal. I am
looking for it 

	—
Reply to this email directly or view it on GitHub [1].    

 Profitieren Sie von der sicheren E-Mail-Übertragung Ihrer Daten mit
einer kostenlosen E-Mail-Adresse der Telekom.
www.t-online.de/email-kostenlos

Links:
------
[1] https://github.com/maieul/ledmac/issues/288#issuecomment-94301216

**Comment by maieul** [comment]
I have found the bug. Will publish it quiclky for test

**Comment by ralessi** [comment]
> in general I use directley `$||$` however this bug is not normal. I am looking for it
To my opinion one should put `$\parallel$` instead of `$||$`.

**Comment by maieul** [comment]
@sonator please try branch issue288.

@ralessi oh, do you think ? we could change the handbook in this case.  in any case could you look for the english in https://github.com/maieul/ledmac/compare/english1...issue288 ? I dont want to merge in 1.22.0 before Rebecca look at it.

**Comment by sonator** [comment]
A good idea, thanks!

	-----Original-Nachricht----- 

	Betreff: Re: [ledmac] v21.1, textbardbl as symbol in critical notes
(#288) 

	Datum: Sun, 19 Apr 2015 20:27:43 +0200 

	Von: Robert Alessi <notifications@github.com> 

	An: maieul/ledmac <ledmac@noreply.github.com> 

	  > in general I use directley `$||$` however this bug is not normal.
I am looking for it
 To my opinion one should put `$parallel$` instead of `$||$`.

	—
Reply to this email directly or view it on GitHub [1].    

 Profitieren Sie von der sicheren E-Mail-Übertragung Ihrer Daten mit
einer kostenlosen E-Mail-Adresse der Telekom.
www.t-online.de/email-kostenlos

Links:
------
[1] https://github.com/maieul/ledmac/issues/288#issuecomment-94303652

**Comment by ralessi** [comment]
I have been away from office for a few days.  Is there still something
I can do?

**Comment by maieul** [comment]
yes, look at the change in

https://github.com/maieul/ledmac/compare/1.22.0-1.15.0...issue290

I have no news of Rebecca, so I think I will publish only with your check

**Comment by ralessi** [comment]
Ok Maïeul, I will check these lignes before noon.

As for my previous revision, I think if you can still follow the
thread going through the revised lines, it means that everything is
just fine! ;)

**Comment by maieul** [comment]
I am afraid I need to revert this solution, which has broken the `inplaceofnumber` feature. The commands inside argument of \symlinenum must be robust.

**Comment by sonator** [comment]
Would it be better to use $||$, or $\parallel$, as proposed by Robert Alessi ?

**Comment by maieul** [comment]
I have no idea of the precise ≠ between then. But $\parallel$ seems more semantic. In any case, the problem is more linked to LaTeX than to eledmac.

**Comment by sonator** [comment]
For me there is no problem to change, thank you for the hint!
