### ISSUE TITLE
v21.1, Afootnote in edtabular environment

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#289]
The critical note inside an edtabular environment causes an error.
Sorry for disturbing the week-end peace! 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{lmodern}

\usepackage[series={A,B,C},noend,noeledsec]{eledmac}
\usepackage{eledpar}

\begin{document}

\beginnumbering
\pstart
\begin{edtabularl}
Memoria \edtext{humana}{\Afootnote{animalis}} & Memoria animalis \\
Memoria labilis & Memoria stabilis
\end{edtabularl}
\pend
\endnumbering

\end{document}

**Comment by maieul** [comment]
that is the noend option which was badly implemented. I will look for it.

**Comment by maieul** [comment]
please try issue289 (which also include code for #288)

**Comment by maieul** [comment]
@ralessi same question, could you look for change in https://github.com/maieul/ledmac/compare/english1...issue289 (which contain changes of https://github.com/maieul/ledmac/compare/english1...issue288)

**Comment by sonator** [comment]
Both MWEs are running perfectly, thank you very much! 
Now I test a greater manuscript.

**Comment by sonator** [comment]
Addendum: 
Another problem occured. It concerns, as it seems, the use of \textlangle and \textrangle, in which I enclose added words. I will send a MWE tomorrow. 
At the moment thank you for the rapid help, good evening!

**Comment by maieul** [comment]
open a new issue for the mwe

**Comment by sonator** [comment]
Le problème concernant \textlangle etc. était en vérité un problème de l'utilisateur. Hier soir j'avais simplement oublié de charger le package textcomp. Actuellement la compilation marche très bien. Merci beaucoup!

**Comment by maieul** [comment]
parfait alors!
