### ISSUE TITLE
v1.12.0 spaces between paragraphed critical notes

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#290]
Did you change the default spaces between paragraphed critical notes, depending on whether a symbol is set or not? The space before \symlinenum is greater than before a linenumber.

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{lmodern}

\usepackage[series={A,B,C},noend,noeledsec]{eledmac}
\usepackage{eledpar}

\footparagraph{A}
\numberonlyfirstinline[A]
\symlinenum[A]{\textbardbl}

\begin{document}

\beginnumbering
\pstart
\edtext{Gaudeamus}{\Afootnote{gaudeat}} igitur, iuvenes dum sumus; post iucundam iuventutem, post \edtext{molestam}{\Afootnote{serenam}} senectutem \edtext{nos}{\Afootnote{me}} habebit \edtext{humus}{\Afootnote{humor}}. 
\pend
\endnumbering

\end{document}

**Comment by sonator** [comment]
Sorry, I use v.1.21.0!

**Comment by maieul** [comment]
no, it was just a typo in the solve of #289. Try issue290 branch

**Comment by maieul** [comment]
no, you are using v1.22.0 in dev which is not the same

**Comment by sonator** [comment]
Perfectum. All spaces are equal. Thank you very much!
