### ISSUE TITLE
alignment of  line number in note 

### ISSUE THREAD

**Issue by mepherl** [maieul/ledmac#291]
Dear Maieul,
i'm sorry to bother you again and i have no clue, if this is difficult to implement. I need the linenumber of the ednotes to be flushed to the right, so that the decimal-numbers stand on top of each other:
now it's
```
6          lemma] text
10        lemma] text
193      lemma] text
```

but it should be
```
  6    lemma] text
 10    lemma] text
193    lemma] text
```
i had a look at other (german) editions, this is often to be found (e.g. in the extensive Robert Walser-edition currently under way).

and i need the same for the endnotes, where the line numbers should be similar.

the main problem i see is, when there are two lines involved:
```
  6/7  lemma] text
 10     lemma] text
193f.   lemma] text
```
tell me please, is this possible?
best regards,
martin

**Comment by maieul** [comment]
please, provides a MWE ;-).

If I understand well, it is possible. Juste let me time to look at it tonight

**Comment by mepherl** [comment]
The MWE! Sorry, i forgot! I just made something up. Thank you for looking into it!
Martin

```
\documentclass[paper=A5]{scrbook}
\usepackage{eledmac}

\twolines{f.}
\morethantwolines{ff.}


\begin{document}
\beginnumbering\pstart
At the extremity of the \edtext{roadstead}{\Afootnote{road}} of Brest, in the \edtext{open space that lies stretched out between the Ile Longue and Point Kelerne}{\lemma{open \ldots Kelerne}\Bendnote{nothing much to add}}, may be seen two rocks crowned with massive granite buildings, and standing boldly up. On the former, the lazaretto of Trébéron has been established; the latter, which in other days was used as a burial-ground and thence took its name of the Ile des Morts, now contains the principal powder-magazine of the naval arsenal. The two rocks separated by an arm of the sea, are about six miles distant from Brest. In appearance these little islands are not unlike. \edtext{Beyond}{\Bendnote{Bbyond}} the ground occupied by the buildings upon them, they offer nothing to the eye save a succession of stony slopes, dotted here and there with coarse moss and prickly thorn-broom. Vainly there might you look \edtext{for any other shelter than that than that afforded}{\lemma{for \ldots afforded}\Afootnote{nothing much to say}} by the fissures of the rocks, for any other shade than that of the walls, for any other walk than the short terrace contrived in front of the buildings. Naked and sterile, the two isles remind you of a couple of immense sentry-boxes in stone, placed there for the purpose of keeping guard over the sea, which is roaring beneath them. But if the foot that treads them remains imprisoned within a narrow circle, the view from their summit extends over an infinite space. Here, you have the bay of Lanvoc, bordered by a dull-looking and stunted vegetation; there, \edtext{Roscanvel}{\Afootnote{Roscanvel}} with its shadows crossed by the graceful spire of its church; there, Spanish Point bristling with batteries; and lastly, close upon the horizon lies \edtext{Brest}{\Bendnote{Breast}}
\pend\endnumbering
\newpage
\doendnotes{B}

\end{document}

```

**Comment by maieul** [comment]
ps : please next time don't write "feature request" as title. There is many feature request, and such title can't help to know about what the issue is.

**Comment by maieul** [comment]
for your problem you have use two steps
1) first, you must box the line number with `\boxXendlinenum`  and `\boxlinenum` available in the current version of eledmac.
2) then, you have to define the alignement inside the ligne number, with \boxlinenumalign{R}
\boxXendlinenumalign{R}, which is defined by the version 1.23.0 in the branch issue291. See at the file issue291.tex as example

However, there is a problem with end note :what should be the alignment of the pages number. In the exemple I have deleted the page number, because it's what you have provided as example in your first question.

**Comment by mepherl** [comment]
dear maieul, as always i am greatly indebted to you! it works like a charm! well except for two things: it breaks this:

    \numberonlyfirstinline[A]
    \inplaceofnumber[A]{26mm}

any value of inplaceofnumber is ignored.
the other thing is more difficult: sq. and pageranges destroy the column-appearance.
it looks like this:

       1
     2–3
       3
     7f.

but in fact should be

       1
       2–3
       3
       7f.

is this possible? thank you for looking into it!

**Comment by maieul** [comment]
I dont think the inplaceofnumber was broken by that. It was broken before.

I am afraid the alignement is not by the dash is not possible by the way. I have to think to an other method, but ...

I will look at this this week-end

**Comment by mepherl** [comment]
I see that it is difficult. Thank you for having a look!

**Comment by maieul** [comment]
the problem with `\inplaceofnumber` was (re)-introduced  again by 1.22.0, in order to solve #288. I have corrected it in 1.22.1  (which I will publish now on CTAN)  and reported it in this branch


ps : re-introduced  because it was existing before you ask me to correct it)

**Comment by maieul** [comment]
I am not sur to understand which is the alignement you need. Could you run the new issue291.tex file and confirm me you want to have a alignement like in the output. If yes, I could implement it this week-end.

**Comment by mepherl** [comment]
now the problem with inplaceofnumbers is fixed. basically the output is correct: the linenumbers should stand on top of each other, so that the single digits, the tens and numbers are in distinct reading columns. – this works. unfortunately there is a second rule applying for page-ranges: the second argument (–4 or sq.) is placed to the right of the first linenumber without moving it. you should be able to see it in my example from yesterday.

**Comment by maieul** [comment]
I am not sure to understand exactly what you mean.

Could you confirm me that the "Second test" in the new issue291.tex file is what you want ?

**Comment by mepherl** [comment]
Please compare these two images: This one is from the printed book (unfortunately you can't see the right align, but it is) 
https://www.dropbox.com/s/8k21ppljsl18akn/Untitled-p1.jpg?dl=0
and this is a screenshot of the output with eledmac:
https://www.dropbox.com/s/ssxz3sx83irc40u/Untitled-p2.jpg?dl=0
as you can see, the f. should move more to the right.

**Comment by maieul** [comment]
did you look at my question about the file issue291.tex? what about the second test in the following example
![image](https://cloud.githubusercontent.com/assets/636640/7412362/4f674906-ef42-11e4-87d8-2122236bfcd2.png)

**Comment by mepherl** [comment]
Sorry, i missed this part of your question. Yes, first test would be my prefered outcome!

**Comment by maieul** [comment]
ok. So I will implement both solution this night, tomorrow or this week-end.

**Comment by maieul** [comment]
so the new branch issue291 implementes four new settings:

- `\boxstartlinenum` which boxes the first part of a line number range in a footnote. Text is put at the right of the box. Use `\boxXendstartlinenum` for endnotes
- `\boxendlinenum` which boxes the last part of a line number range in a footnote (so the dash + last line number of the "f."/"ff." command).  Text is put at the left of the box. Use `\boxXendendlinenum` for endnotes.

See the example issue291.tex in the zip file to understand how to use it.

Please send me feedback also about handbook (green lines in 67c40f8)

**Comment by maieul** [comment]
hi, some feedback?

**Comment by mepherl** [comment]
Sorry! I've seen you've done something and i greatly appreciate it. I will return to the university on monday and then I will try everything. Thank you, Maieul, and a nice weekend!
Martin

**Comment by mepherl** [comment]
Dear Maieul, it works wonderful! Great job! One thing i notice: now latex produces more \badboxes. But that is not really a concern! Thank you for putting your effort into this! 
Martin

**Comment by maieul** [comment]
open an issue for the badxboxes. It should not have change between two version of eledmac.
