### ISSUE TITLE
eledpar / eledchapter and epigraph (or verbatim)

### ISSUE THREAD

**Issue by vchalmel** [maieul/ledmac#293]
Hi,

I'm translating english novels in french, and using eledpar to get a  wonderful bilingual two-pages edition. Thanks a lot for your work on this !

However, there are in my current work a few epigraphs or verbatim that I must write on top of the chapter name.

I would normally use the package epigraph to do so, which allow to define, just after the \chapter{} a text with \epigraphead{} to write on the space between the top of the page and the chapter name ; it doesn't show up with eledchapter however, for now I can't have the two verbatims (french and english) face to face on my two pages, I have to put them before leftside{} and rightside{} on the same page.

Could you tell me if there is a way with eledpar to handle a berbatim and its translation on top of the two eledchapters ?

**Comment by maieul** [comment]
plese, provides a MWE of 
1) your test
2) what do you want to obtain

**Comment by maieul** [comment]
I am still waiting your MWE

**Comment by vchalmel** [comment]
Of course, I'm sorry, didn't had time to work on it during the week.

**Comment by vchalmel** [comment]
Here is the basic, working way to use epigraph, to put a paragraph before the chapter title.
With eledpar I would like two epigraphs before the eledchapter titles, but obvioulsy it doesn't work and I'm not sufficiently used to browse a package commands to modify epigraphead accordingly.

*******************************************************************

\documentclass[a4paper, 11pt]{book}
\usepackage[UTF8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[cyr]{aeguill}
\usepackage[polutonikogreek,francais]{babel}
\usepackage{epigraph}

\title{titre}
\author{Auteur}
\date{date}

\begin{document}

	\renewcommand{\contentsname}{Sommaire}	
	\renewcommand{\partname}{Livre}
	\setlength{\parindent}{4em}
	\setlength{\parskip}{1em}

%	***************
%	*Page de Titre*
%	***************
	\begin{titlepage}
		\pagenumbering{gobble}
		\maketitle
	\end{titlepage}

%	*********
%	*Préface*
%	*********
	\frontmatter
	\chapter*{Préface}
		Ceci est le texte de la préface
%	**********
%	*Prologue*
%	**********
	\chapter*{Prologue}
	\setlength{\epigraphwidth}{0.5\textwidth}
	\epigraphhead[20]{Ceci est l'épigraphe placée avant le titre}
		Texte du chapitre
\end{document}[/code]

**Comment by vchalmel** [comment]
This is how I currently use it (the two epigraphs are on a single page before the chapter)
********************************************************
\documentclass[a4paper, 11pt]{book}
	\usepackage[UTF8]{inputenc}
	\usepackage[T1]{fontenc}
	\usepackage[cyr]{aeguill}
	\usepackage[polutonikogreek,english,francais]{babel}
	\usepackage{etex,eledmac,eledpar}
	\usepackage{epigraph}
	
	\newcommand{\mybeginen}{
	\selectlanguage{english}
	\begin{Leftside}
	\beginnumbering
	}
	\newcommand{\mybeginfr}{
	\selectlanguage{francais}
	\begin{Rightside}
	\beginnumbering
	}
	\newcommand{\myenden}{
	\endnumbering
	\end{Leftside}
	\selectlanguage{francais}
	}
	\newcommand{\myendfr}{
	\endnumbering
	\end{Rightside}
	\Pages
	}
	
	\title{Titre}
	\author{Auteur}
	\date{Date}
	
	\begin{document}
	
		\renewcommand{\contentsname}{Sommaire}	
		\renewcommand{\partname}{Livre}
		
		\setlength{\parindent}{4em}
		\setlength{\parskip}{1em}
		
		\numberlinefalse
		\numberpstartfalse
		\sidepstartnumfalse 
	
	%	***************
	%	*Page de Titre*
	%	***************
		\begin{titlepage}
			\pagenumbering{gobble}
			\maketitle
		\end{titlepage
	
	%	*********
	%	*Préface*
	%	*********
		\frontmatter
		\beforeeledchapter
		\begin{pages}
	    	\mybeginen
	    	   	\pstart
	    	   		\eledchapter{PREFACE}
	    	   	\pend
		        \pstart
	               Preface
		        \pend
			\myenden
			\mybeginfr
	    	    \pstart
	    	    	\eledchapter{PR\'EFACE}
	    	    \pend
	    	    \pstart
	    	       Préface
		        \pend
			\myendfr 
		\end{pages} 
	
	%	**********
	%	*Prologue*
	%	**********
		\beforeeledchapter
		\begin{pages}
			\setlength{\epigraphwidth}{0.5\textwidth}
			\epigraphhead[100]{Persons who do not like tiresome prologues, need not read this one. It is essential only to the situation, not to the story.\newline\noindent\rule{\epigraphwidth}{0.4pt}\newline Les personnes n'aimant pas les prologues fastidieux peuvent s'épargner la lecture de celui-ci. Il n'est essentiel qu'à la compréhension de la situation, non à celle de l'histoire.}
	    	\mybeginen
	    	   	\pstart
	    	   		\eledchapter*{PROLOGUE}   	   	
	    	   	\pend
		        \pstart
					texte anglais
				\pend
			\myenden
			\mybeginfr
				\pstart
	    	   		\eledchapter*{PROLOGUE}   	   	
	    	   	\pend
		        \pstart
					texte français
				\pend
			\myendfr
		\end{pages}
	\end{document}

**Comment by maieul** [comment]
je regarde. Mais je rappelle qu'un MWE ne doit pas contenir de command perso, sauf si le problème  est justement la création de commande perso.
Ceci est un vrai MWE https://github.com/maieul/ledmac/blob/96892091d508aa502ba510c6d76a6f0643832961/issue293.tex

**Comment by maieul** [comment]
bon, alors \epigraphhead ne peut pas fonctionne vu qu'il influencie sur l'apparence du l'entête de la prochaine page, et que dans le cas présent il y a 2 pages.

Il faut donc utiliser la commande \epigraph dans l'argument optionel de \pstart (lire les doc respectives de epigraph et de eledmac). Néanmoins s'ajoute un second problème : si on veut conserver le parallélisme des titres, il faut que chaque épigramme ait la même taille. Pour ce faire, on va créer une command \ledepigraph qui reprend \epigraph mais qui impose une hauteur commune à tous les épigraphes. (Argument optionel de \minipage).

Donc au finale cela donne 

https://github.com/maieul/ledmac/blob/74523c7601cca4def4fddf388ad6d833eacf5460/issue293.tex.

Je n'intégrerai pas une telle commande dans le core de eledmac car cela n'a pas directement a voir avec le projet.
