### ISSUE TITLE
[eledpar] page numbering with \beforeeledchapter{}, and same page number on the two facing/ two language pages 

### ISSUE THREAD

**Issue by vchalmel** [maieul/ledmac#294]
Hi,

When I use eledchapter, even if I use a cleardoublepage and/or beforeeledchapter, the first page number will be 2 because the "Pages" environnement start on the odd page

Second question, quite related, Is there a way to make eledpar put the same page number on the two facing "\rightside" and "\leftside" to have the same page number for the original text and its translation ?

**Comment by maieul** [comment]
1) provides a MWE for the first problem, 
2) Also provides a MWE for the second. I I have though to this problem, for now I have some idea but not implemented it

**Comment by vchalmel** [comment]
What do you call a MWE ?

**Comment by maieul** [comment]
read http://www.tex.ac.uk/cgi-bin/texfaq2html?label=minxampl or http://minimalbeispiel.de/mini-en.html or

**Comment by maieul** [comment]
hi, any news?

**Comment by maieul** [comment]
I cite you

>When I use eledchapter, even if I use a cleardoublepage and/or beforeeledchapter, the first page number will be 2 because the "Pages" environnement start on the odd page

Yes, it's normal. I you have pages, you need to start on a left page. I don't understand your question

**Comment by vchalmel** [comment]
Thanks, I will provide a MWE for the other issue asap.

So, there is no way to make Latex start the numbering on a right page ? Not that it wouldn't make sense, just asking.

**Comment by maieul** [comment]
there is way, but it would not make sense. Do you need it? or do you need just same number in two page?

**Comment by vchalmel** [comment]
Then it's fine, I prefer to make sense. ^^ only the same number on the two pages then indeed.

**Comment by maieul** [comment]
ok. I have same idea, but require many change. It won't be tested before I close #292.

**Comment by maieul** [comment]
Notes pour implémenter cela

1) on ne peut pas jouer sur la valeur du counter page, car il est requis pour distinguer les pages gauches des pages droites.
2) il faut donc que cela se joue uniquement à l'affichage. Les personnes devront faire un \renewcommand{\thepage} (on pourrait du reste le faire en standard, au niveau du \AtBeginDocument, via `\patchcmd{\thepage}{page}{toto}{}{}`. Celui-ci comprendrait deux commands:
a) \getparallelpagenumber pour calculer la valeur du compteur parallepagenumber.
b) une commande classique tel \arabic{parallepagenumber} pour afficher ce compteur.

l'enjeu est donc au niveau de `\getparallelpagenumber` comment le calculer?
1) si on est pas en train de processer les pages, parallelpagenumber = page
2) sinon il faut calculer. A = affichage effectif. P = compteur normal de Page D = première page du \Pages. A = d+((p-d)/2). En espérant que TeX arrondisse 2/1 à 0, et pas à 1.

Question subsidiaire:comment on nomme l'option qui permet de choisir cela?

**Comment by maieul** [comment]
et bien non \dim expr arrondi au supérieur. Par contre \divide arrondi à l'inférieur. Donc je vais un test en fonction de la parité de la page.

**Comment by maieul** [comment]
remarque : en fait on va patcher \thepage directement après le \begingroup de \Pages. Cela permettra de  faire des \renewcommand{\thepage} entre les \Pages.

**Comment by maieul** [comment]
@vchalmel merci de tester la branche issue294 qui propose l'option sameparallelpagenumber à eledpar. Celle-ci permet lorsqu'on utilise \Pages d'avoir le même nombre à gauche et à droite.
