### ISSUE TITLE
v1.22.0, indexing: white space behind \edindex commands

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#295]
I carried out your instructions (in Geekographie) to create multiple indices containing german Umlaute and linenumbers with indextools, xindy, splitindex, hyperref and eledmac -- with success. Thank you!

In a numbered text the XeLaTeX run causes a white space behind the word where an \edindex command is placed. The behaviour seems to deal with the hyperindex=false option.

\documentclass{scrbook}

\usepackage{fontspec}
\setmainfont{Linux Libertine O}
\usepackage{xunicode}
\usepackage{polyglossia}
\setmainlanguage{german}

\usepackage[xindy,splitindex]{indextools}%On précise qu'on veut utiliser xindy + splitindex
\usepackage[series={A},noeledsec,nofamiliar,noend,xindy,xindy+hyperref]{eledmac}
\usepackage[hyperindex=false]{hyperref}

\makeindex[name=verb,title=Index verborum]

\begin{document}

\beginnumbering
\pstart
In \edtext{principio}{\Afootnote{fine\edindex[verb]{finis}}} erat vinum\edindex[verb]{vinum}.
\pend
\endnumbering

\printindex[verb]

\end{document}

**Comment by maieul** [comment]
try branch issue295

**Comment by sonator** [comment]
My file runs as expected, the white space disappeared, thank you very much!

**Comment by maieul** [comment]
you'r welcome. will be published as 1.22.2 in the next week
