### ISSUE TITLE
Spring cleaning

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#297]
Please answer before 10th of june 2015.

Technical aspects:
- <s>split .dtx file in smaller files</s> -> on ne fait pas finalement
- <s>unformize name of some internal command between footparagraph/footnormal/foottwocol</s>
- <d>suppress all \renewcommand of eledpar and move to eledmac</d>
- <del>create generic command which write to to the auxiliary file in right/left side depending of the current side.</del> plus tard, quand on fera une version + complexe de eledpar.

Handbook:
- check all english (@ralessi)
- <del>move user "hacks" from the code handbook to the user handbook</del>
- <del>make 2 handbook: one for user, the other one for code.</del> we do not do it.

Code/feature/commands:
- suppress any need to call `\renewcommand` and prefer command with argument: Notamment
  - <s><code>\l@d@section</code></s> on garde, car trop technique d'envisager une nouvelle commande pour ca
  - <code>sidenotesep</code>
  - \parledgroupnotespacing
- <del>suppress \endstanzaextra and \startstanzahook, prefer command with argument</del>.
- <s>suppress `\chapterinpages`</s>
- <del>suppress all command marked as "deprecated" (like `\ledsection`)</del> done
-  <s>suppress support of multiple index with memoir, use in any case imakeidx/etoolbox</s> done
- <s>\footparagraph/ \foottwocol and related will becomes `\Xfootface[<series>]{paragraph/twocol/threecol/normal}` the option eledmac-compatibility will allow to use old version</s>. Done
- <s>name of command setting for notes (like \numberonlyfirstinline) will be unified (the option eledmac-compatibility will allow to use old version.):
  - name prefixed by X for setting of critical notes
  - name prefixed by Xend for setting of end notes
  - name suffixed by X for setting of familiar notes</s>
- <s>improve quotation / quote patching by patchcmd</s>.

**Comment by baem2** [comment]
One thing that just came to my mind: Instead of the commands
```
\begin{pages}
...
\end{pages}
\Pages

\begin{pairs}
...
\end{pairs}
\Columns
```
... it makes more sense to have just one environment, let's call it eledpar:
```
\begin{eledpar}
...
\end{eledpar}
```
And then, depending on the output the users wants, he could either use \Columns or \Pages. This way one can easily change the output, for example when the text grows. The user'd have to change only one command.

You could also think about changing \Columns or \Pages to less generic commands like \eledColumns and \eledPages.

**Comment by maieul** [comment]
you are right. That could be a first way to a more generic system to produce //isme not only for two texts (but that will be later). I don't think eledpar is a good name, anyway.

**Comment by maieul** [comment]
@baem2 I have just thought that we need to keep a distinct environment for pages and columns, because we need to know if we are in column or in page before processing left/right side.

**Comment by baem2** [comment]
I don't know the internals, so this might just not be possible. My idea is the following: We have something like this:
```
\begin{parallel}
\being{left}
left text
\end{left}
\begin{right}
right text
\end{right}
\end{parallel}
```
This is just needed to get & save the texts. Then we have two commands (\Pages and \Columns) that do all the processing: They read out left/right and put it in the correct form for their respective  output.

This is not too important, though; so if it's not easily possible, just leave it out.

**Comment by maieul** [comment]
yes, it is not possible

**Comment by baem2** [comment]
Would you have some time to have another look into #274 when working on that spring cleaning?

**Comment by maieul** [comment]
not in working in spring cleaning. spring cleaning should be at feature constant. But I hope to have time this summer, _after_ the spring cleaning.

Your problem is a big problem, so I prefer not to mix it with spring cleaning.

**Comment by baem2** [comment]
Okay, thx.

**Comment by floriandk** [comment]
> suppress support of multiple index with memoir, use in any case imakeidx/etoolbox

I am not sure which part of the index-support stems from `memoir`, but I'd like to mention, that multiple indices until now work just fine with the very flexible combination of the `index`-package and `xindy`. I'd really appreciate, if you could make sure that this way will not be broken by your spring-cleaning.

**Comment by maieul** [comment]
for now, there is two possibilite when using memoir + eledmac:
- use native memoir multiple index
- use memoir + imakeidx or memoir + indextool.

This situation force me to maintain two codes, and to multiply by two the risk of error.

That why, as I make a spring cleaning, I will suppres the use of native memoir multiple index in order to have only the code for indextool/imakeidx to maintain.

**Comment by maieul** [comment]
reledmac is released !
