### ISSUE TITLE
sameword and greek

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#301]
Hey there,

I tried to use the sameword-feature with greek text, but this brought up error messages. Could you have a look, maybe I'm doing something wrong:

```
\documentclass{article}
\usepackage[series={A}]{eledmac}
\usepackage[polutonikogreek,english]{babel}
\usepackage[utf8]{inputenc}

\begin{document}

\newcommand*{\gk}[1]{{}\foreignlanguage{polutonikogreek}{#1}{}}
%
%\begin{ledgroup}
%\beginnumbering
%\begin{otherlanguage}{polutonikogreek}
%\pstart
%φρέαρ τῆς κρήνης, ἐν \sameword{ᾧ} ηὗρον καὶ τὸν Κόττιν τὸν ἑαυτῶν ἀρχηγόν,
%ἐν \edtext{\sameword{ᾧ}}{\Afootnote{\gk{ᾦ} TK}} τόπῳ κατέλιπον αὐτόν. ὃς ἀτενίσας καὶ ἰδὼν αὐτοὺς ἐξεπλάγη,
%\pend
%\end{otherlanguage}
%\endnumbering
%\end{ledgroup}

\begin{ledgroup}
\beginnumbering
\begin{otherlanguage}{polutonikogreek}
\pstart
\noindent φρέαρ τῆς κρήνης, ἐν ᾧ ηὗρον καὶ τὸν Κόττιν τὸν ἑαυτῶν ἀρχηγόν,
ἐν \edtext{ᾧ}{\Afootnote{\gk{ᾦ} TK}} τόπῳ κατέλιπον αὐτόν. ὃς ἀτενίσας καὶ ἰδὼν αὐτοὺς ἐξεπλάγη,
\pend
\end{otherlanguage}
\endnumbering
\end{ledgroup}

\end{document}
```

This code is running fine. As soon as I add \sameword (as in the commented out code), it stops working ...

Using eledmac 1.21

**Comment by maieul** [comment]
For now, sameword mechanism can work only with engine with use natif utf8 (Like LuaLaTeX and XeLaTeX), and not with inputenc + utf8 option. In general, use native UTF8 engine is easier when you have to manipulate it. I will look for compatibility with inputenc, but I can't ensure I will find an answer.

**Comment by maieul** [comment]
I am afraid it could not be possible to implement compatibility with pdflatex + inputenc without many error message and, worse, many bad output. 

This problem won't be fixed. Use LuaLaTeX or XeLaTeX instead of pdfLaTeX + inputenc.

**Comment by maieul** [comment]
I have asking people on http://tex.stackexchange.com/q/244538/7712, but I am afraid there is no solution except use UTF8 engine (and in many case, it is better)

**Comment by maieul** [comment]
good news, there is a solution. I will report it this week-end. 

However, I still encourage you to use utf8 engine

**Comment by maieul** [comment]
(that is for me)

utiliser une syntaxe de type

\expandafter\csgdef\expandafter{\detokenize{ᾧ}}{toto}

notons que cela peut poser problème pour XeTeX

http://sourceforge.net/p/xetex/bugs/108/

donc utiliser ifxetex en attendant

**Comment by baem2** [comment]
Thanks for looking into this issue, that's great!

**Comment by maieul** [comment]
My tests work perfectly. I have just to implemente them. But as I have no more battery, it will be for tomorrow ;-)

**Comment by maieul** [comment]
please try branch "issue301"

**Comment by maieul** [comment]
hi, some news?

**Comment by baem2** [comment]
Sorry for the late response, I'm on holiday at the moment and internet is a bit tricky. I right away checked your example, and it is working as expected. Thank you very much, that's great!

**Comment by maieul** [comment]
ok. I will close it. I will also add warning for unicode normalization

**Comment by maieul** [comment]
ok, I will suppose it's ok. However, I still recommand to use lualatex or xelatex, for many reason
