### ISSUE TITLE
 Supressing the delimiter (right bracket "]" after the lemma) without killing it for all lemmata of the same series

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#307]
Is there any solution about it in eledmac? It would be helpful in order to define the text of the footnote lemma in case let's say of omissions. I am not refering to "\nolemmaseparator" or commands which would either influence the whole series of notes.

Regarding this matter Mr. Dekker had proposed for an \abb command (http://www.djdekker.net/ledmac/) which apparently does not work for eledmac:

"Copy and paste the following five lines into your preamble:
\newcommand{\abb}[1]{#1%
\let\rbracket\nobrak\relax}
\newcommand{\nobrak}{\textnormal{}}
\newcommand{\morenoexpands}{%
\let\abb=0}
… and then redefine the format(s) of the relevant footnote apparatus(es) (adjust to suit):
\renewcommand{\Bparafootfmt}[3]{%
\ledsetnormalparstuff
\notenumfont\printlines#1|\enspace%
{\select@lemmafont#1|#2\rbracket}\enskip   % mind the braces!
\notetextfont
#3\penalty-10}  "

Thanks!

**Comment by maieul** [comment]
I suppose you need the [nosep] option. 

`\edtext{something}{\Afootnote[nosep]{some comment}`.

However I am not sur to have well understanding your question.


the Dekker hack should not be used anymore. The aim of eledmac, compared to ledmac, is to avoid such hack

**Comment by NiAgio** [comment]
[nosep] leaves unwanted space after the lemma and sometimes a critical footnote contains a palaeographical remark or simply should not contain the lemma... ckeck the "space hack" (\hspace{-0.2cm}) in the second lemma of the following example in order to avoid unwanted space:

\documentclass[12pt,a4paper]{book}
\usepackage[english,polutonikogreek]{babel}
\usepackage[utf8x]{inputenc}
\usepackage{eledmac}


\newcommand{\tl}{\textlatin}


\footparagraph{A}

\numberonlyfirstinline


\begin{document}
\beginnumbering
\pstart
Ὅτι σοῦ ἐστιν ἡ βασιλεία \edtext{καὶ ἡ δύναμις}{\Afootnote[nosep]{\tl{om. D}}} \edtext{καὶ ἡ δόξα}{\Afootnote[nosep]{\hspace{-0.2cm}\tl{om. D}}} εἰς τοὺς αἰῶνας;
ἀμήν.
\pend
\endnumbering
\end{document}

**Comment by NiAgio** [comment]
The idea here is to dismiss the right bracket
1. without having unwanted space between lemma and the rest of the footnote
2. without applying it to the rest of the footnotes of the same series.

**Comment by maieul** [comment]
yes, that is documented: the `\inplaceoflemmaseparator` setting is used if the separator is not printed. (§5.4.2 of the handbook). By default it is 1em. But you can change it. See this example : 3b63a7e

**Comment by NiAgio** [comment]
Ok, got it! Thanks a lot!

**Comment by maieul** [comment]
you'r welcome. However, next time, please read the handbook. And open an issue only if you need a  new feature. If you need help use tex.stackexchange or eledmac list before.
