### ISSUE TITLE
Error with \@lemma in *.1

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#313]
A friend of mine has the following error message with version 1.23:

```
! Package etoolbox Error: Boolean '\iflemmacommand@0' undefined. 
```

This seems to happen because ```\@lemma``` is written into the mother.1-file.

Do you know under which circumstances ```\@lemma``` is written into the *.1-files?

I'm asking because my friend has two big projects running with eledmac/par, one runs fine with version 1.23, the other one throws this error. When we know what we have to look for, it might be easier to compile a MWE.

**Comment by maieul** [comment]
hum. please send a MWE (quickly)

**Comment by baem2** [comment]
Sorry, as it is a very big project, it might take a moment to compile a MWE without hints why this might happen. Looking into it. I'll let you know asap.

**Comment by maieul** [comment]
ok. "a priori" it should be easy to solve it, but for a quick look, now, I don't see where could be the problem.

**Comment by baem2** [comment]
My friend was able to iron out the problem: Usage of \lemma in \edtext, I found additionally that it only happens on right pages.

```
\listfiles
\documentclass{book}
\usepackage[german]{babel} 
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{blindtext}
\usepackage[series={A},noeledsec,noledgroup]{eledmac}
\usepackage{eledpar}
\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart

Der Originaltext: \blindtext[2] Ja, das ist er!
\pend
\endnumbering   
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart

Der \edtext{übersetzte Text}{%
\lemma{Übersetzter Text}
\Aendnote{Kommentar: %\blindtext[3]
}}: \blindtext[3] \edtext{Ja}{\Aendnote{Kommentar: \blindtext}}, das ist er!
\pend

\endnumbering
\end{Rightside}
\end{pages}
\Pages

\section{Kommentierende Anmerkungen}

\doendnotes{A}
\end{document}
```

**Comment by maieul** [comment]
as usual... Please try branch issue313

**Comment by baem2** [comment]
As I heard from my friend this seems to work perfectly, thank you!

**Comment by maieul** [comment]
you'r welcome
-----
Ma�eul Rouquette
www.maieul.net
http://geekographie.maieul.net/

Le 20 mai 2015 � 14:37, Philipp <notifications@github.com> a �crit :

**Comment by maieul** [comment]
I have send it to the CTAN.
