### ISSUE TITLE
error in line 85

### ISSUE THREAD

**Issue by mepherl** [maieul/ledmac#314]
hello maieul,
the new installation of miktex on a computer led to an error when running a simple mwe:

```javascript
\documentclass{scrbook}
\usepackage{eledmac}

\begin{document}
\beginnumbering
\pstart
Test
\pend
\endnumbering
\end{document}
```

This is the error message 
5	! Undefined control sequence. 	
		
	746	<recently read> \reserveinserts 			
	747	                                 			
	748	l.85 \reserveinserts 			
	749	                    {32} 			
	750	The control sequence at the end of the top line 			
	751	of your error message was never \def'ed. If you have 			
	752	misspelled it (e.g., `\hobx'), type `I' and the correct 			
	753	spelling (e.g., `I\hbox'). Otherwise just continue, 			
	754	and I'll forget about whatever was undefined. 			
	755				
	756				
	757	! LaTeX Error: Missing \begin{document}. 			
	758				
	759	See the LaTeX manual or LaTeX Companion for explanation. 			
	760	Type  H <return>  for immediate help. 			
	761	 ...                                               			
	762	                                                   			
	763	l.85 \reserveinserts{3 			
	764	                      2} 			
	765	You're in trouble here.  Try typing  <return>  to proceed. 			
	766	If that doesn't work, type  X <return>  to quit. 

Everything worked fine on my computer before, but when i installed miktex from the scratch on mine  as well, the same error appeared. and on the output a "32" is showing at the very beginning of the document. 
Can you help?
Thank you and best regards,
Martin

**Comment by maieul** [comment]
I don't reproduce. HAve you updated all package? 

could you insert a \listfiles in order to let me know which versions of package do you use. also send the full .log file, in order to allow me to know which version of pdflatex/xelatex you use.

**Comment by mepherl** [comment]
sure, thank you for looking into it! this is the log-file, my previous working installation was LaTeX2e <2014/05/01>
:::

This is XeTeX, Version 3.14159265-2.6-0.99991 (MiKTeX 2.9 64-bit) (preloaded format=xelatex 2015.5.28)  28 MAY 2015 12:40
entering extended mode
**mweff.tex
(mweff.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 69 languages loaded.
("C:\Program Files\MiKTeX 2.9\tex\latex\koma-script\scrbook.cls"
Document Class: scrbook 2015/05/06 v3.17a KOMA-Script document class (book)
("C:\Program Files\MiKTeX 2.9\tex\latex\koma-script\scrkbase.sty"
Package: scrkbase 2015/05/06 v3.17a KOMA-Script package (KOMA-Script-dependent 
basics and keyval usage)

("C:\Program Files\MiKTeX 2.9\tex\latex\koma-script\scrbase.sty"
Package: scrbase 2015/05/06 v3.17a KOMA-Script package (KOMA-Script-independent
 basics and keyval usage)

("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty"
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks14
)
("C:\Program Files\MiKTeX 2.9\tex\latex\koma-script\scrlfile.sty"
Package: scrlfile 2015/05/06 v3.17a KOMA-Script package (loading files)

Package scrlfile, 2015/05/06 v3.17a KOMA-Script package (loading files)
                  Copyright (C) Markus Kohm

))) ("C:\Program Files\MiKTeX 2.9\tex\latex\koma-script\tocbasic.sty"
Package: tocbasic 2015/05/06 v3.17a KOMA-Script package (handling toc-files)
)
Package tocbasic Info: omitting babel extension for `toc'
(tocbasic)             because of feature `nobabel' available
(tocbasic)             for `toc' on input line 124.
Package tocbasic Info: omitting babel extension for `lof'
(tocbasic)             because of feature `nobabel' available
(tocbasic)             for `lof' on input line 125.
Package tocbasic Info: omitting babel extension for `lot'
(tocbasic)             because of feature `nobabel' available
(tocbasic)             for `lot' on input line 126.
Package tocbasic Info: defining new hook before heading of `' on input line 154
8.
Class scrbook Info: File `scrsize11pt.clo' used instead of
(scrbook)           file `scrsize11.clo' to setup font sizes on input line 2152
.

("C:\Program Files\MiKTeX 2.9\tex\latex\koma-script\scrsize11pt.clo"
File: scrsize11pt.clo 2015/05/06 v3.17a KOMA-Script font size class option (11p
t)
Requested font "cmr10" at 10.95pt
)
("C:\Program Files\MiKTeX 2.9\tex\latex\koma-script\typearea.sty"
Package: typearea 2015/05/06 v3.17a KOMA-Script package (type area)

Package typearea, 2015/05/06 v3.17a KOMA-Script package (type area)
                  Copyright (C) Frank Neukam, 1992-1994
                  Copyright (C) Markus Kohm, 1994-

\ta@bcor=\skip41
\ta@div=\count80
\ta@hblk=\skip42
\ta@vblk=\skip43
\ta@temp=\skip44
\footheight=\skip45
Package typearea Info: These are the values describing the layout:
(typearea)             DIV  = 10
(typearea)             BCOR = 0.0pt
(typearea)             \paperwidth      = 597.50793pt
(typearea)              \textwidth      = 418.25555pt
(typearea)              DIV departure   = -6%
(typearea)              \evensidemargin = 47.2316pt
(typearea)              \oddsidemargin  = -12.5192pt
(typearea)             \paperheight     = 845.04694pt
(typearea)              \textheight     = 595.80026pt
(typearea)              \topmargin      = -25.16531pt
(typearea)              \headheight     = 17.0pt
(typearea)              \headsep        = 20.40001pt
(typearea)              \topskip        = 11.0pt
(typearea)              \footskip       = 47.6pt
(typearea)              \baselineskip   = 13.6pt
(typearea)              on input line 1485.
)
\c@part=\count81
\c@chapter=\count82
\c@section=\count83
\c@subsection=\count84
\c@subsubsection=\count85
\c@paragraph=\count86
\c@subparagraph=\count87
LaTeX Info: Redefining \textsubscript on input line 4430.
\abovecaptionskip=\skip46
\belowcaptionskip=\skip47
\c@pti@nb@sid@b@x=\box26
\c@figure=\count88
\c@table=\count89
\bibindent=\dimen102
) ("C:\Program Files\MiKTeX 2.9\tex\latex\eledmac\eledmac.sty"
Package: eledmac 2015/05/20 v1.23.1 LaTeX port of EDMAC

("C:\Program Files\MiKTeX 2.9\tex\latex\xkeyval\xkeyval.sty"
Package: xkeyval 2014/12/03 v2.7a package option processing (HA)

("C:\Program Files\MiKTeX 2.9\tex\generic\xkeyval\xkeyval.tex"
("C:\Program Files\MiKTeX 2.9\tex\generic\xkeyval\xkvutils.tex"
\XKV@toks=\toks15
\XKV@tempa@toks=\toks16
)
\XKV@depth=\count90
File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
))
("C:\Program Files\MiKTeX 2.9\tex\latex\xargs\xargs.sty"
Package: xargs 2008/03/22 v1.1  extended macro definitions  (mpg)
\xargs@max=\count91
\xargs@toksa=\toks17
\xargs@toksb=\toks18
)
("C:\Program Files\MiKTeX 2.9\tex\latex\etoolbox\etoolbox.sty"
Package: etoolbox 2015/05/04 v2.2 e-TeX tools for LaTeX (JAW)
\etb@tempcnta=\count92
)
! Undefined control sequence.
<recently read> \reserveinserts 
                                
l.85 \reserveinserts
                    {32}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.


! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.85 \reserveinserts{3
                      2}
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

("C:\Program Files\MiKTeX 2.9\tex\latex\bigfoot\suffix.sty"
Package: suffix 2006/07/15 1.5a Variant command support
)
("C:\Program Files\MiKTeX 2.9\tex\latex\xstring\xstring.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\xstring\xstring.tex"
\@xs@message=\write3
\integerpart=\count93
\decimalpart=\count94
)
Package: xstring 2013/10/13  v1.7c  String manipulations (C Tellechea)
)
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifluatex.sty"
Package: ifluatex 2010/03/01 v1.3 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX not detected.
)
("C:\Program Files\MiKTeX 2.9\tex\latex\ms\ragged2e.sty"
Package: ragged2e 2009/05/21 v2.1 ragged2e Package (MS)

("C:\Program Files\MiKTeX 2.9\tex\latex\ms\everysel.sty"
Package: everysel 2011/10/28 v1.2 EverySelectfont Package (MS)
)
\CenteringLeftskip=\skip48
\RaggedLeftLeftskip=\skip49
\RaggedRightLeftskip=\skip50
\CenteringRightskip=\skip51
\RaggedLeftRightskip=\skip52
\RaggedRightRightskip=\skip53
\CenteringParfillskip=\skip54
\RaggedLeftParfillskip=\skip55
\RaggedRightParfillskip=\skip56
\JustifyingParfillskip=\skip57
\CenteringParindent=\skip58
\RaggedLeftParindent=\skip59
\RaggedRightParindent=\skip60
\JustifyingParindent=\skip61
)
("C:\Program Files\MiKTeX 2.9\tex\generic\ifxetex\ifxetex.sty"
Package: ifxetex 2010/09/12 v0.6 Provides ifxetex conditional
)
\@l@dtempcnta=\count95
\@l@dtempcntb=\count96
\section@num=\count97
\l@dnumpstartsL=\count98
\line@margin=\count99
\c@firstlinenum=\count100
\c@linenumincrement=\count101
\c@firstsublinenum=\count102
\c@sublinenumincrement=\count103
\lock@disp=\count104
\sublock@disp=\count105
\linenumsep=\skip62
\led@toksa=\toks19
\led@toksb=\toks20
\line@num=\count106
\subline@num=\count107
\absline@num=\count108
\@lock=\count109
\sub@lock=\count110
\page@num=\count111
\endpage@num=\count112
\endline@num=\count113
\endsubline@num=\count114
\@inputcheck=\read1
\last@page@num=\count115
\insert@count=\count116
\linenum@out=\write4
\@edtext@level=\count117
\raw@text=\box27
\num@lines=\count118
\one@line=\box28
\par@line=\count119
\c@pstart=\count120
\ballast@count=\count121
\c@ballast=\count122
\@k=\count123
\@h=\dimen103
\old@hsize=\dimen104
\l@d@end=\write5
\Afootins=\insert233
\mpAfootins=\insert232
\footinsA=\insert231
\mpfootinsA=\insert230
\c@footnoteA=\count124
\Aend@bysection=\count125
\Bfootins=\insert229
\mpBfootins=\insert228
\footinsB=\insert227
\mpfootinsB=\insert226
\c@footnoteB=\count126
\Bend@bysection=\count127
\Cfootins=\insert225
\mpCfootins=\insert224
\footinsC=\insert223
\mpfootinsC=\insert222
\c@footnoteC=\count128
\Cend@bysection=\count129
\Dfootins=\insert221
\mpDfootins=\insert220
\footinsD=\insert219
\mpfootinsD=\insert218
\c@footnoteD=\count130
\Dend@bysection=\count131
\Efootins=\insert217
\mpEfootins=\insert216
\footinsE=\insert215
\mpfootinsE=\insert214
\c@footnoteE=\count132
\Eend@bysection=\count133
\Zfootins=\insert213
\mpZfootins=\insert212
\footinsZ=\insert211
\mpfootinsZ=\insert210
\c@footnoteZ=\count134
\Zend@bysection=\count135
\ipn@skip=\skip63
Requested font "cmr9" at 9.0pt
\c@line=\count136
\c@subline=\count137
\sidenote@margin=\count138
\l@dlp@rbox=\box29
\l@drp@rbox=\box30
\ledlsnotewidth=\dimen105
\ledrsnotewidth=\dimen106
\ledlsnotesep=\dimen107
\ledrsnotesep=\dimen108
\c@labidx=\count139
\@emptytoks=\toks21
\l@denvbody=\toks22
\stanza@count=\count140
\stanzaindentbase=\skip64
\c@stanzaindentsrepetition=\count141
\stanza@modulo=\count142
\l@dampcount=\count143
\l@dcolcount=\count144
\hilfsbox=\box31
\hilfsskip=\skip65
\Hilfsbox=\box32
\hilfscount=\count145
\dcoli=\dimen109
\dcolii=\dimen110
\dcoliii=\dimen111
\dcoliv=\dimen112
\dcolv=\dimen113
\dcolvi=\dimen114
\dcolvii=\dimen115
\dcolviii=\dimen116
\dcolix=\dimen117
\dcolx=\dimen118
\dcolxi=\dimen119
\dcolxii=\dimen120
\dcolxiii=\dimen121
\dcolxiv=\dimen122
\dcolxv=\dimen123
\dcolxvi=\dimen124
\dcolxvii=\dimen125
\dcolxviii=\dimen126
\dcolxix=\dimen127
\dcolxx=\dimen128
\dcolxxi=\dimen129
\dcolxxii=\dimen130
\dcolxxiii=\dimen131
\dcolxxiv=\dimen132
\dcolxxv=\dimen133
\dcolxxvi=\dimen134
\dcolxxvii=\dimen135
\dcolxxviii=\dimen136
\dcolxxix=\dimen137
\dcolxxx=\dimen138
\dcolerr=\dimen139
\@hilfs@count=\count146
\edtabcolsep=\skip66
\edfilldimen=\dimen140
\c@addcolcount=\count147
\HILFSskip=\skip67
\Hilfsskip=\skip68
\tabhilfbox=\box33
\tabHilfbox=\box34
\eled@sectioning@out=\write6
) (mweff.aux)
LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.

ABD: EverySelectfont initializing macros
LaTeX Info: Redefining \selectfont on input line 5.
 Section 1 (mweff.1) (mweff.eledsec1)
Requested font "cmsl10" at 10.95pt

[1

] (mweff.aux)

 *File List*
 scrbook.cls    2015/05/06 v3.17a KOMA-Script document class (book)
scrkbase.sty    2015/05/06 v3.17a KOMA-Script package (KOMA-Script-dependent ba
sics and keyval usage)
 scrbase.sty    2015/05/06 v3.17a KOMA-Script package (KOMA-Script-independent 
basics and keyval usage)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
scrlfile.sty    2015/05/06 v3.17a KOMA-Script package (loading files)
tocbasic.sty    2015/05/06 v3.17a KOMA-Script package (handling toc-files)
scrsize11pt.clo    2015/05/06 v3.17a KOMA-Script font size class option (11pt)
typearea.sty    2015/05/06 v3.17a KOMA-Script package (type area)
 eledmac.sty    2015/05/20 v1.23.1 LaTeX port of EDMAC
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
   xargs.sty    2008/03/22 v1.1  extended macro definitions  (mpg)
etoolbox.sty    2015/05/04 v2.2 e-TeX tools for LaTeX (JAW)
  suffix.sty    2006/07/15 1.5a Variant command support
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
ragged2e.sty    2009/05/21 v2.1 ragged2e Package (MS)
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
   mweff.1
   mweff.eledsec1
 ***********

 ) 
Here is how much of TeX's memory you used:
 4800 strings out of 428760
 74031 string characters out of 3164296
 224043 words of memory out of 3000000
 8149 multiletter control sequences out of 15000+200000
 4592 words of font info for 17 fonts, out of 3000000 for 9000
 1096 hyphenation exceptions out of 8191
 41i,7n,54p,1842b,187s stack positions out of 5000i,500n,10000p,200000b,50000s

Output written on mweff.pdf (1 page).

**Comment by maieul** [comment]
it seems is related with new format xelatex 2015.5.28.

I have send a patch to issue314. Please try it. I have also to ask more about it on LaTeX team.

**Comment by maieul** [comment]
(for Maieul:http://tex.stackexchange.com/q/247428/7712)

**Comment by mepherl** [comment]
thank you, yes your patch works like a charm! as usual! with your magnificent speed! merci bien!

**Comment by maieul** [comment]
you're welcome. However I will change the patch to have a better one. I will send you a message about that. I am just waiting more answer from the LaTeX team.

**Comment by mepherl** [comment]
thank you! i'm afraid i will have to open up another issue in a second...

**Comment by maieul** [comment]
please try the new version of the branch issue314. I will look for this.

**Comment by mepherl** [comment]
thank you! I just double-checked! It works! all my best! martin
