### ISSUE TITLE
\numberonlyfirstinline and twoline-apparatus-entries

### ISSUE THREAD

**Issue by mepherl** [maieul/ledmac#315]
Sorry to bring up two issues on the same day (and right before leaving, so not able to respond until tomorrow) but there is an inconsistency in the use of \numberonlyfirstinline: 

this MWE
```
\documentclass{scrbook}
\usepackage{eledmac}

\numberonlyfirstinline[A]

\begin{document}
\beginnumbering
\pstart
\edtext{Test1}{\Afootnote{First Word}} Test2 Test3 Test4 Test5
Test6 Test7 Test8 Test9 Test10
Test15 Test14 \edtext{Test13 Test 14}{\Afootnote{Second Word}}
\pend
\endnumbering
\end{document}
```
shows the second entry into the apparatus without a linenumber, but it should be 1–2

thank you for helping me out!
martin

**Comment by maieul** [comment]
as explained on �5.4.1 you should use in this case \numberonlyfirstintwolines.

See ac6f954

**Comment by mepherl** [comment]
I'm sorry, i pledge to read the handbook more often! Thank you! (and i'll look at issue 314 right away)

**Comment by maieul** [comment]
don't take time for issue314. My proposition was bad. Its now ok.
