### ISSUE TITLE
Error with spacing and lines (+ widowpenalty)

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#316]
Usually I'm using code like this (and more similarly) in my documents:
```
\clubpenalty = 10000
\widowpenalty = 10000
```

This leads to various problems with eledmac, I isolated one issue here (there are more problems, but I wasn't able to find a good MWE). So hopefully fixing this one also fixes the other ones!

Here's my MWE. When I leave the last line in the first paragraph on the left side empty, eledmac does not count the first line on the left page (so nr. 5 occurs on line 6) and, even worse, the 2nd paragraph on the right page is not on the same height as the one on the left.

I know, there's an easy workaround: Not leaving the line empty. But as I said, I think this just shows a problem that pops up for me in other occasions as well.

```
\listfiles
\documentclass{book}
\usepackage[german]{babel} 
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{blindtext}
\usepackage[series={},noeledsec,noledgroup]{eledmac}
\usepackage{eledpar}

\clubpenalty = 10000
\widowpenalty = 10000


\begin{document}

\numberpstarttrue

\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
\blindtext
%the following line is empty – or not ...

\pend

\pstart
\blindtext
\pend
\endnumbering   
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Dies hier ist ein Blindtext zum Testen von Textausgaben. Wer diesen Text liest,
ist selbst schuld. Der Text gibt lediglich den Grauwert der Schrift an. Ist das wirk-
lich so? Ist es gleichgültig, ob ich schreibe: „Dies ist ein Blindtext“ oder „Huardest
gefburn“? Kjift – mitnichten! Ein Blindtext bietet mir wichtige Informationen. An
ihm messe ich die Lesbarkeit einer Schrift, ihre Anmutung, wie harmonisch die Fi-
guren zueinander stehen und prüfe, wie breit oder schmal sie läuft. Ein Blindtext
sollte möglichst viele verschiedene Buchstaben enthalten und in der Originalsprache
gesetzt sein.
\pend

\pstart
\blindtext
\pend

\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
```

I hope there's a fix for that, as otherwise I'd have to do my whole document without the said options (widowpenalty) ...

**Comment by baem2** [comment]
I just realised that the problem even occurs with clubpenalty only, but it gets worse with both options set.

**Comment by maieul** [comment]
but why do want to have a last line empty ?

**Comment by baem2** [comment]
You are right, there's no reason for that. But I think that this bug directs to some problems in the code, that occur for me in my larger documents on other occasions (without leaving that line empty). I just did not yet find out exactly how to reproduce it in a smaller document – beside the MWE here ... :(
