### ISSUE TITLE
`\startstanzahook` and `\endstanzaextra` commands not called when using two-column format with `eledpar`

### ISSUE THREAD

**Issue by apollo77x** [maieul/ledmac#318]
I am making a critical edition in two columns using `eledmac` and `eledpar`.  The text contains some verses, and I want to add some space before and after each verse using the `\startstanzahook` and `\endstanzaextra` commands.  Unfortunately, they are not executed in two-column format due to the fact that the hooks are called when `\pstart` is called and not when `\Columns` or `\Pages` is called.

```\documentclass{article}

\usepackage{eledmac}

\usepackage{eledpar}

\begin{document}

\begin{pairs}

\begin{Rightside}

\setstanzaindents{0,1,1}
    \newcommand*{\startstanzahook}{\vspace{9pt}}
    \def\endstanzaextra{\vspace{9pt}}

\beginnumbering
    \autopar

\begin{astanza}
First line of verse 1&
Second line of verse 1\&              
\end{astanza}

\begin{astanza}
First line of verse 2&
Second line of verse 2\&
\end{astanza}

\begin{astanza}
First line of verse 3&
Second line of verse 3\&
\end{astanza}

\endnumbering

\end{Rightside}


\begin{Leftside} 

\setstanzaindents{0,1,1}
    \newcommand*{\startstanzahook}{\vspace{9pt}}
    \def\endstanzaextra{\vspace{9pt}}

\beginnumbering
    \autopar

\begin{astanza}
First line of verse 1&
Second line of verse 1\&
\end{astanza}

\begin{astanza}
First line of verse 2&
Second line of verse 2\&
\end{astanza}

\begin{astanza}
First line of verse 3&
Second line of verse 3\&
\end{astanza}

\endnumbering

\end{Leftside}

\end{pairs}

\Columns

\end{document}

**Comment by maieul** [comment]
As an `astanza` environment is a `\pstart`...`\pend` structure, you could use `\AtEveryPstart` and `\AtEveryPend` like in https://github.com/maieul/ledmac/blob/6a7a46b11a522bf41fcd2ff40eb26f9729a0323a/issue318.tex.

However, the `\AtEveryPend` and `\AtEveryPstart` was not implemented in eledpar 1.16.2. So please try the branch "issue318" and make feedback.

**Comment by apollo77x** [comment]
Yes, the MWE at "issue318" is still missing the space.  Do you mean that `\AtEveryPstart` was implemented in previous versions of `eledpar` but not the latest one?  I noticed in the version history of `eledpar` that v1.10.0 included compatibility with this.  Also, is `\AtEveryPstart` an `eledmac` command?  I couldn't find it in the manual.

**Comment by maieul** [comment]
No, \AtEveryPstart and \AtEveryPend (which are documented in � 4.2.3 of eledmac handbook) are implemented in all version of eledmac/eledpar.

However, actually it doesn't work with \Columns. That is why I have implemented it in the branch issue318. And I ask you to try it. To it you have to run the .ins file in order to obtain the last .sty file. Just put the .sty fila along the .tex file, and try.

**Comment by maieul** [comment]
hi, some news?

**Comment by apollo77x** [comment]
Sorry, I don't know what the .ins file or the .sty file are or how to run them.

**Comment by maieul** [comment]
please read https://github.com/maieul/ledmac#debug-and-feature-requests... all thing are explained!!!

**Comment by apollo77x** [comment]
Hmmm.  I don't know how that worked, but now it is working.  Do I just need to include the .sty files with the LaTeX files for my project?

**Comment by maieul** [comment]
yes, just put the new .sty files along your .tex files.

**Comment by apollo77x** [comment]
OK, thanks.  By the way, I may need to number the verses.  I suppose the solution to this would be similar to this one.

**Comment by maieul** [comment]
sorry? what is the relationship between number the verses and the question you have asked?

**Comment by apollo77x** [comment]
I was thinking that since the numbering of verses would be controlled by `\AtEverypStart` there would be the same problem that it would not be called in two-column format.

**Comment by maieul** [comment]
the numbering of verse was never controlled by `\AtEverypStart`. Why was you thinking that?

**Comment by apollo77x** [comment]
I suppose it would be `\startstanzahook` then

**Comment by maieul** [comment]
no, verse are numbered without any intervention....

**Comment by maieul** [comment]
every 5 verse, the number is printed by default

**Comment by apollo77x** [comment]
Oh, no, sorry, I mean the numbering of the verses, not the lines of the edition.  So after every verse there would be a number:

First line first verse.
Second line of first verse. (1)

First line of second verse.
Second line of second verse. (2)

First line of third verse.
Second line of third verse. (3)

**Comment by maieul** [comment]
hum, stricly speakin `First line of third verse.
Second line of third verse. (3)` is two verse, not one.

**Comment by maieul** [comment]
So that is an other question. Please answer for the first question an open an issue for the second one.

**Comment by apollo77x** [comment]
depends how you define the words.  Usually "verse" means the same thing as "stanza."  `first line of third verse. second line of third verse. (3)` would be two lines of one verse, not two verses.

**Comment by apollo77x** [comment]
but I suppose "verse" can mean the same thing as "line".

**Comment by maieul** [comment]
To be sure to understand between us, please use the eledmac vocabulary: stanza is a series of verse. Each verse finish by a &.

**Comment by apollo77x** [comment]
It's because of the confusion between English and French.  Although "vers" means "a line of verse" in French, in English "verse" usually means "stanza" and "line" means "line of verse."

**Comment by maieul** [comment]
ok. but what do you need? and what about the first problem? if the first problem is solve, please close this issue and open a new one

**Comment by maieul** [comment]
indeed, my english  dictionnary said for verse "� archaic a line of poetry.". But as for now it have been used with this meaning in eledmac handbook...

**Comment by apollo77x** [comment]
Yes, the first problem is solved, thanks.  By the way, where is a good place to look for information on .ins and .sty files and what their function is?

**Comment by maieul** [comment]
the .sty file is the code of the package. It is the file loaded by the command \usepackage. In general (but not all time) the .sty file is produced when running the .ins file from the .dtx file. The .dtx file is a file which contains both code and handbook. It is used to produce the .pdf handbook.


In many case, when you use the TeXLive/MikTeX updating system, you have not to avoid about the .sty file: it is installed for you. In the present case, as I ask you to test the future version of eledmac/eledpar, I have asked you to produce the .ins file from the git repository.

About the .sty file: http://tex.stackexchange.com/q/1137/7712

about the .dtx and .ins file http://ctan.mackichan.com/info/dtxtut/dtxtut.pdf

**Comment by maieul** [comment]
I have changed the way `\AtEveryPend` and `\AtEveryPstart` are implemented for column. 

Before that `\AtEveryPstart{\vspace{9pt}}` was inserting 9pt + 9pt = 18 pt. Now, it insert 9pt in left and 9pt in right. So only 9pt vertically.
