### ISSUE TITLE
package soul and eledmac

### ISSUE THREAD

**Issue by mepherl** [maieul/ledmac#320]
hello maieul,
for reasons unknown to me, letter spacing with soul does not work properly in the critical apparatus:

```
\documentclass{book}
\usepackage{soul}
\usepackage{eledmac}

\boxlinenum{2em}
\boxstartlinenum{2em}
\boxendlinenum{2em}
\afternumberinfootnote{2em}

\begin{document}
\beginnumbering
\pstart
This is \edtext{normal word}{\Afootnote{this is quite alriqht}} and this a 
\edtext{\so{word with spacing}}{\Afootnote{this does not work so well}}.
\pend
\endnumbering
\end{document}
```

as you can see, the second entry is placed too far to the left. i can, of course always correct it manually by using \lemma and some whitespace. but maybe you know a better solution?
Thank you!
Martin

**Comment by maieul** [comment]
I don't know exactly why we have that. Both soul and eledmac package are complex. But you have a very easy solution: prefix your \so by \null

\pstart
This is \edtext{normal word}{\Afootnote{this is quite alriqht}} and this a 
\edtext{\null\so{word with spacing}}{\Afootnote{this does not work so well}}.
\pend

if you use many time \so, you can automatize this prefixing with `\pretocmd{\so}{\null}{}{}` in your preamble

**Comment by mepherl** [comment]
Wow, great! Thank you very much!
