### ISSUE TITLE
eledmac/par and beamer

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#322]
I'm preparing a lecture. On the handout I do use eledmac/par to have columns with greek texts and translations.

Now I tried to copy some of that text in my presentation made with beamer. It's working as expected, but I get the error

```
! LaTeX Error: Command \lemma already defined.
```

That's probably because the  beamer package has an environment called "lemma" ...

Is there any possibility to avoid this error message? Maybe another option "nolemma"? Or maybe eledmac could disable the lemma command automatically when nocritical and noend is set? (Or series={}?)

MWE:
```
\documentclass{beamer}
\usepackage[english]{babel}
\usepackage[utf8]{inputenc}

\usepackage[T1]{fontenc}

\usepackage[series={},noeledsec,noend,nocritical,nofamiliar,noledgroup]{eledmac}
\usepackage{eledpar}

\begin{document}

\begin{frame}{Test}

\begin{minipage}{\textwidth}
\begin{pairs}
\begin{Leftside} 

\beginnumbering
\pstart
Left text.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Right text.
\pend
\endnumbering
\end{Rightside}
\end{pairs}
\Columns
\end{minipage}

\end{frame}
\end{document}
```

**Comment by maieul** [comment]
in my sense, the best way is to load beamer with \documentclass[noamsthm]{beamer}, because some time you need in a beamer the eledmac `lemma`, but it is not often you need lemma environment in a beamer when using eledmac.

However, the branch issue322 disable \lemma when using  nocritical.

**Comment by baem2** [comment]
Oh, okay, I did not know that beamer is loading ams! So it's working fine for me with noamsthm!

I tried your fix anyway, it's also working great. Thank you!
