### ISSUE TITLE
faire commencer une édition avec un numéro de page impair à gauche

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#323]
Bonjour Maïeul,

J'ai découvert avec ravissement la nouvelle option `sameparallelpagenumber`.

Toutefois, je n'ai pas réussi à faire *démarrer* mon édition avec la toute première page, donc à gauche, numérotée 1.

Je me place dans le cas d'une édition avec une longue introduction numérotée en chiffres romains (`frontmatter`), puis, une fois l'introduction finie, le titre du traité en belle page (`\part*{}`), puis, immédiatement au verso, le début de l'édition bilingue, avec une première page, à gauche, numérotée 1. L'édition se présente donc avec des pages 1-1 2-2- 3-3, etc.

Avec l'option `sameparallelpagenumber`, tout est parfait si la première page de l'édition, à gauche. est paire. Mais si elle est impaire, il y a un décalage: toutes les pages `Leftside` deviennent `Rightside`, et *vice versa*.

Voici un mwe:
````
\documentclass[openany]{book}

\usepackage{fontspec}
\usepackage{eledmac}
\usepackage[sameparallelpagenumber]{eledpar}
\usepackage{lipsum}

\begin{document}

\part*{Hippocrate\\
       Épidémies II}

\addtocounter{page}{-1}

\begin{pages}

  \begin{Leftside}
    \beginnumbering

    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend

    \endnumbering
  \end{Leftside}

  \begin{Rightside}
    \beginnumbering

    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend

    \endnumbering
    
  \end{Rightside}

\end{pages}

\Pages

\end{document}
````
Dans cet exemple, si on enlève `\addtocounter{page}{-1}`, tout est parfait, sauf que l'édition commence en page 2.

**Comment by maieul** [comment]
Essayons de résumer le problème pour entrevoir une solution.

1) pour savoir si une page est de gauche ou de droite, eledpar (et LaTeX en général) se base sur la parité du compteur "page". Donc le système de "sameparallelpagenumber" ne peux pas jouer sur ce compteur, mais uniquement sur l'affichage du compteur.
2) donc ton \addtocounter{page}{-1} perturbe tout, c'est pour cela qu'il faut l'enlever.
3) mais du coup effectivement tu veux commencer ton affichage à -1 du compteur reel
4) donc il faut que ton \Pages recoive un argument optionel de type "pagenumbershift" qui indique le décalage.

Donc je dirais implémenter quelque chose du type `\Pages[pagenumbershift=-1]`

Par la même occasion il faudrait envisager que les pages blanches insérées par \Pages pour commencer systématiquement à gauche puisse au choix : 
- ne pas être numérotée
- ne pas avoir d'entête et pied de page.

Exemple dans le cas suivant : 

\documentclass[openany]{book}

\usepackage{fontspec}
\usepackage{eledmac}
\usepackage{eledpar}
\usepackage{lipsum}

\begin{document}

%\part*{Hippocrate\\
%       Épidémies II}

%\addtocounter{page}{-1}

\begin{pages}

  \begin{Leftside}
    \beginnumbering

    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend

    \endnumbering
  \end{Leftside}

  \begin{Rightside}
    \beginnumbering

    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend

    \endnumbering

  \end{Rightside}

\end{pages}

\Pages

Une pseudo page de transition. Elle on veut la numéroter, mais pas à droite.
````
\documentclass[openany]{book}

\usepackage{fontspec}
\usepackage{eledmac}
\usepackage{eledpar}
\usepackage{lipsum}

\begin{document}

%\part*{Hippocrate\\
%       Épidémies II}

%\addtocounter{page}{-1}

\begin{pages}

  \begin{Leftside}
    \beginnumbering

    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend

    \endnumbering
  \end{Leftside}

  \begin{Rightside}
    \beginnumbering

    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend

    \endnumbering

  \end{Rightside}

\end{pages}

\Pages

Une pseudo page de transition. Elle on veut la numéroter, mais pas à droite.

\begin{pages}

  \begin{Leftside}
    \beginnumbering

    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend

    \endnumbering
  \end{Leftside}

  \begin{Rightside}
    \beginnumbering

    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend
    \pstart
    \lipsum[1]
    \pend

    \endnumbering

  \end{Rightside}

\end{pages}

\Pages
\end{document}
````

la page de droite de la pseudo-page de transition devrait ne pas être numérotée... 

Donc trois options, à implémenter à la fois pour chaque \Pages individuelle et de manière plus globale.

Qu'en penses tu ? quelles serait les noms idéaux?

**Comment by ralessi** [comment]
Bien compris le problème, et l'idée du `\Pages[pagenumbershift=-1]` est excellente, car elle permet d'adapter l'édition à des comportements différents, selon les classes de document et les options choisies comme `openany`, etc.

Pour le deuxième cas de figure, je suggérerais `prevnoheadfoot` pour «ni en-tête ni pied de page dans la précédente page» ou `prevpgcleared` pour «style de page précédente: cleared».

Pour le troisième cas de figure, c'est plus délicat, car la page à ne pas numéroter n'est pas la page de transition, mais la suivante. Je dirais: `nextoddpgcleared` pour «la première page impaire qui suit sans rien».

C'est un peu barbare, mais on peut s'en souvenir...

**Comment by maieul** [comment]
Le 25 juin 2015 � 22:43, Robert Alessi <notifications@github.com> a �crit :

> Bien compris le probl�me, et l'id�e du \Pages[pagenumbershift=-1] est excellente, car elle permet d'adapter l'�dition � des comportements diff�rents, selon les classes de document et les options choisies comme openany, etc.
> 
> Pour le deuxi�me cas de figure, je sugg�rerais prevnoheadfoot pour �ni en-t�te ni pied de page dans la pr�c�dente page� ou prevpgcleared pour �style de page pr�c�dente: cleared�.
> 
prevpgempty (pour renvoyer au \pagestyle{empty}).  Mais il faut dire que c'est conditionn� � la page vide. typiquement dans mon exemple, si mon texte de de transition entre les 2 �ditions avait �t� sur 2 page, la page pr�c�dente le second \Pages n'aurait pas du �tre vide ...
> Pour le troisi�me cas de figure, c'est plus d�licat, car la page � ne pas num�roter n'est pas la page de transition, mais la suivante. Je dirais: nextoddpgcleared pour �la premi�re page impaire qui suit sans rien�.


comment ca? mais en fait c'est absurde ce troisi�me cas de figure : c'est juste une variante de pagenumbershift=-1 conditionn�e au fait qu'on ait �t� oblig� de mettre un \pageclear.

Bon du coup cela fait avancer dans la reflexion et on peux r�sumer ainsi :
- dans tout les cas le reglage concerne la page vide ins�r�e pour commencer � gauche
- il y a deux r�glages : d�calage de num�rotation et style de la page vide

**Comment by ralessi** [comment]
>Bon du coup cela fait avancer dans la reflexion et on peux r�sumer
>ainsi :
>- dans tout les cas le reglage concerne la page vide ins�r�e pour
>commencer � gauche
>- il y a deux r�glages : d�calage de num�rotation et style de la page
>vide

C'est juste!

**Comment by maieul** [comment]
Donc on partirai sur `prevpgempty` et `numbershift=xxx` (typiquement -1, mais ca pourrait être autre chose). Et on expliquerait en documentation que cela est conditionné à la présence d'une page de droite sans contenu avec la page de gauche?

**Comment by ralessi** [comment]
> Donc on partirai sur `prevpgempty` et `numbershift=xxx` (typiquement -1, mais ca pourrait être autre chose). Et on expliquerait en documentation que cela est conditionné à la présence d'une page de droite sans contenu avec la page de gauche?

Oui, je pense que c'est la bonne solution.

**Comment by maieul** [comment]
ok je vais voir quand je peux faire cela. p-� la semaine prochaine

**Comment by ralessi** [comment]
En reprenant les règles de composition des livres, j'ai vu qu'en fait la page de titre de style `\part{}` est bien numérotée 1. Donc le début de l'édition qui suit est de type 2-2, 3-3-, etc.

**Mais** supposons que le texte édité soit en plusieurs sections, et que chaque nouvelle section soit dans un environnement `pages` propre. Dans ce cas, le système actuel ne peut fonctionner que si la *première page* de la section 2 est une page paire. Si ce n'est pas le cas, la section 2 commence par une page vide à droite, puis une page de gauche avec un contenu de page de droite!

**Comment by maieul** [comment]
je ne suis pas s�r de suivre ce que tu dis. \Pages s'arrange pour commencer syst�matiquement sur une page impaire, donc de gauche

**Comment by ralessi** [comment]
Voici un mwe qui montre le problème que je pourrais formuler de la manière suivante: «Avec `sameparallelpagenumber`, il ne faut pas qu'une section `pages` se termine sur une page paire à droite car cela perturbe l'ordre des pages de la section suivante.»

````
\documentclass{book}

\usepackage{eledmac}
\usepackage[sameparallelpagenumber]{eledpar}

\begin{document}

\begin{pages}

\begin{Leftside}
  \beginnumbering

\pstart
\eledsection*{Section 1}
\pend

\pstart
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche
\pend

  \endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering

\pstart
\eledsection*{Section 1}
\pend

\pstart
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite
\pend

\endnumbering  
\end{Rightside}

\end{pages}

\begin{pages}

\Pages

\begin{Leftside}
  \beginnumbering

\pstart
\eledsection*{Section 2}
\pend

\pstart
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche
\pend

  \endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering

\pstart
\eledsection*{Section 2}
\pend

\pstart
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite
\pend

\endnumbering  
\end{Rightside}

\end{pages}

\Pages

\end{document}
````

**Comment by ralessi** [comment]
Pardon: je n'ai pas mis `\Pages` au bon endroit. Voici le mwe avec un titre `\part`:

````
\documentclass[openany]{book}
\usepackage{fontspec}
\usepackage{eledmac}
\usepackage[sameparallelpagenumber]{eledpar}

\begin{document}

\part*{Titre du traité}

\begin{pages}

\begin{Leftside}
  \beginnumbering

\pstart
\eledsection*{Section 1}
\pend

\pstart
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche
\pend

  \endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering

\pstart
\eledsection*{Section 1}
\pend

\pstart
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite
\pend

\endnumbering  
\end{Rightside}

\end{pages}

\Pages

\begin{pages}

\begin{Leftside}
  \beginnumbering

\pstart
\eledsection*{Section 2}
\pend

\pstart
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche
gauche gauche gauche gauche gauche gauche
\pend

  \endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering

\pstart
\eledsection*{Section 2}
\pend

\pstart
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite droite droite droite droite
droite droite droite droite droite droite
\pend

\endnumbering  
\end{Rightside}

\end{pages}

\Pages

\end{document}
````

**Comment by maieul** [comment]
ok, je testerai tout cela lorsque j'aurai fini reledpar 

Le 5 juil. 2015 � 11:19, Robert Alessi <notifications@github.com> a �crit :

**Comment by maieul** [comment]
bon, je m'attaque à ca maintenant.  Je change un peu:
-prevpgempty devient prevpgstyle=empty (ca permet de changer éventuellement le style)
- a priori pas de raison de faire un shift, faut juste ne pas numéroté. Du coup je met prevpgnotnumbered

**Comment by maieul** [comment]
@ralessi peux tu tester la branche issue 323 ? la doc est fournit en 6ef8a81

**Comment by ralessi** [comment]
Bon je résume ici mes essais.

Dans mon gros fichier d'édition, j'ai ceci (classe `book` + `openany`):
````
\mainmatter
\part*{Épidémies~II}
\phantomsection
\addcontentsline{toc}{part}{Épidémies~II}
\subfile{epid2-1}
\subfile{epid2-2}
\subfile{epid2-3}
[...]
````

Ce qui veut dire que je dois avoir une page de titre avec «Épidémies II» centré au milieu, et que cette page est la page 1. Puis vient l'édition elle-même, avec:
- première page de traduction: page 2
- deuxième page de texte critique: page 3
- etc.

Maintenant viennent les tests. Donc activation de `sameparallelpagenumber`.
1. Avec la branche actuelle de `reledpar`, les numéros sont bien les mêmes sur les pages en vis à vis, mais il n'est pas tenu compte de `\frontmatter`, autrement dit la numérotation est continue, et passe simplement des chiffres romains aux chiffres arabes, sans interruption de numérotation.
2. avec la branche `issue 323`:
  - la page de titre correspondant à `\part{Épidémies~2}` est numérotée 0 (avec un pagesyle plain, ce qui est attendu).
  - puis vient l'édition: 1-1 2-2 3-3, etc.
  - **remarque**: ne devrait-on pas avoir: titre = p. 1, puis édition: 2-2 3-3 4-4, etc.?
  - le reste de l'édition est parfait, et les changements de «section» (`\Pages`) n'induisent aucune erreur.
3. pour tester les deux options `prevpgstyle` et `prevpgnotnumbered`, j'ai pris un mwe.
  - après activation de `\frontmatter` et `\mainmatter`, et `reledpar` chargé avec `sameparallelpagenumber`, je perds le numéro de la première page de la partie `\frontmatter`, et la page suivante est numérotée i, alors qu'elle devrait l'être ii.
  - la page de titre est numérotée alors qu'elle devrait être 1
  - toujours avec le mwe, rien ne se passe si j'ajoute `prevpgstyle=empty` (j'ai un style plain à la place, voir le numéro 0 dans le pied de page)
  - rien ne se passe non plus avec l'option `prevpgnotnumbered` en plus.

Voici le mwe. Dans ce mwe, au départ, je n'avais mis ni `\frontmatter/`\mainmatter`, ni `\part`, mais simplement «une page», «une autre page» avec des sauts de page pour que l'édition soit appelée soit p. 1, soit p. 2. Le comportement est toujours le même, que je mette `prevpgstyle=empty, prevpgnotnumbered` ou non.
````
\documentclass[openany]{book}

\usepackage{fontspec}

\usepackage{reledmac}
\usepackage[sameparallelpagenumber, prevpgstyle=empty,
prevpgnotnumbered]{reledpar}

\usepackage{lipsum}

\begin{document}
\frontmatter

Une page

\newpage

Une autre page

\mainmatter
\part{Le livre}

\begin{pages}
  \begin{Leftside}
    \beginnumbering
    \pstart
    \lipsum[1]
    \pend
    \endnumbering
  \end{Leftside}
  \begin{Rightside}
    \beginnumbering
    \pstart
    \lipsum[1]
    \pend
    \endnumbering    
  \end{Rightside}
\end{pages}

\Pages

\end{document}
````

**Comment by maieul** [comment]
> 
> 	� premi�re page de traduction: page 2
> 	� deuxi�me page de texte critique: page 3
> 	� etc.
> Maintenant viennent les tests. Donc activation de sameparallelpagenumber.
> 1. Avec la branche actuelle de reledpar, les num�ros sont bien les m�mes sur les pages en vis � vis, mais il n'est pas tenu compte de \frontmatter, autrement dit la num�rotation est continue, et passe simplement des chiffres romains aux chiffres arabes, sans interruption de num�rotation.

oui, c'est quelque chose que j'ai corrig� ;-)
> 2. avec la branche issue 323:
> 
> 	� la page de titre correspondant � \part{�pid�mies~2} est num�rot�e 0 (avec un pagesyle plain, ce qui est attendu).
> 	� puis vient l'�dition: 1-1 2-2 3-3, etc.
> 	� remarque: ne devrait-on pas avoir: titre = p. 1, puis �dition: 2-2 3-3 4-4, etc.?
si, ce n'est pas normal
> 	� le reste de l'�dition est parfait, et les changements de �section� (\Pages) n'induisent aucune erreur.
> 		� pour tester les deux options prevpgstyle et prevpgnotnumbered, j'ai pris un mwe.
> 	� apr�s activation de \frontmatter et \mainmatter, et reledpar charg� avec sameparallelpagenumber, je perds le num�ro de la premi�re page de la partie \frontmatter, et la page suivante est num�rot�e i, alors qu'elle devrait l'�tre ii.
> 	� la page de titre est num�rot�e alors qu'elle devrait �tre 1
> 	� toujours avec le mwe, rien ne se passe si j'ajoute prevpgstyle=empty (j'ai un style plain � la place, voir le num�ro 0 dans le pied de page)
> 	� rien ne se passe non plus avec l'option prevpgnotnumbered en plus.
> Voici le mwe. Dans ce mwe, au d�part, je n'avais mis ni \frontmatter/\mainmatter, ni\part, mais simplement �une page�, �une autre page� avec des sauts de page pour que l'�dition soit appel�e soit p. 1, soit p. 2. Le comportement est toujours le m�me, que je metteprevpgstyle=empty, prevpgnotnumbered` ou non.
> 

je test, mais je paris que c'est \part qui perturbe (vu que mes MWE sans \part fonctionnaient)

**Comment by maieul** [comment]
> 
> 
> 	� la page de titre correspondant � \part{�pid�mies~2} est num�rot�e 0 (avec un pagesyle plain, ce qui est attendu).
> 	� puis vient l'�dition: 1-1 2-2 3-3, etc.
> 	� remarque: ne devrait-on pas avoir: titre = p. 1, puis �dition: 2-2 3-3 4-4, etc.?

ceci est corrig� dans la nouvelle branche. merci de ta vigilance ;-)
> 	� le reste de l'�dition est parfait, et les changements de �section� (\Pages) n'induisent aucune erreur.
> 		� pour tester les deux options prevpgstyle et prevpgnotnumbered, j'ai pris un mwe.
> 	� apr�s activation de \frontmatter et \mainmatter, et reledpar charg� avec sameparallelpagenumber, je perds le num�ro de la premi�re page de la partie \frontmatter, et la page suivante est num�rot�e i, alors qu'elle devrait l'�tre ii.
> 	� la page de titre est num�rot�e alors qu'elle devrait �tre 1
corrig� �galement  (en fait c'est le m�me point a75f211)
> 	� toujours avec le mwe, rien ne se passe si j'ajoute prevpgstyle=empty (j'ai un style plain � la place, voir le num�ro 0 dans le pied de page)
> 	� rien ne se passe non plus avec l'option prevpgnotnumbered en plus.

ca c'est normal. ta page de droite ici est une page provoqu�e par \part{Le livre}, pas une page provoqu�e par \Pages. C'est � dire que \part est TOUJOURS � droite. Donc cela ne rentre pas dans le cas de ce que reledpar doit patcher en fonction des options. Si tu veux avoir des \part non num�rot�es et empty, tu peux faire ceci

\patchcmd{\part}
  {\secdef}
  {\thispagestyle{empty}%
  \setcounter{par@page}{0}%
  \secdef}
  {}{}


Mais il ne faut pas que reledpar touche � cela

**Comment by ralessi** [comment]
Bien compris. En fait, la seule petite erreur (page de titre = 0) est donc corrigée. Je n'avais pas bien compris le sens de l'option `prevpgstyle=`.

**Comment by maieul** [comment]
ce n'est pas �vident � expliquer, il faut dire. Si tu trouve mieux comme formulation (outre les points d'anglais) je suis preneur.

**Comment by ralessi** [comment]
> ce n'est pas évident à expliquer, il faut dire. Si tu trouve mieux comme formulation (outre les points d'anglais) je suis preneur.

Je vais regarder.
