### ISSUE TITLE
ordre de chargement des packages

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#324]
Ceci n'est pas un rapport de bug, mais plutôt un élément qui pourrait entrer dans la documentation.

Tout récemment, j'ai été confronté à une erreur de type `no room for a new \count`. Pour voir d'où cela pouvait venir, j'ai commenté dans `eledmac.sty` les lignes:
````
\RequirePackage{etex}
\reserveinserts{32}
```
puis j'ai mis au début de mon préambule:
````
\usepackage{etex}
\reserveinserts{32}
````
ce qui a supprimé le problème. Ensuite, j'ai descendu progressivement ces lignes dans le préambule pour voir ce qui provoquait le problème. J'ai découvert que c'était `biblatex` et toutes les lignes de configuration qui suivent dans mon préambule.

Pour faire disparaître le problème, il suffit de charger `eledmac,eledpar` *avant* `biblatex`, surtout si on utilise massivement la bibliographie dans le document.

**Comment by ralessi** [comment]
Je viens d'écrire:
> Pour faire disparaître le problème, il suffit de charger `eledmac,eledpar` *après* `biblatex`, surtout si on utilise massivement la bibliographie dans le document.
Mais il faut lire *avant*. je viens de corriger!

**Comment by maieul** [comment]
c'est un point pour moi encore obscure. Parce que ce 
````
\RequirePackage{etex}
\reserveinserts{32}
`````
 avait été inséré justement pour éviter cela.  voir #108, et qu'il avait résolu le pb.

Mais j'ai essayé d'en savoir plus suite à un changement de comportement d'etoolbox http://tex.stackexchange.com/a/247433/7712. Et j'avoue ne pas avoir compris vraiment la réponse...

du coup oui, la solution la plus simple serait d'indiquer dans la doc... mais je n'aime pas trop les système qui impose des ordre de chargement de package.

**Comment by ralessi** [comment]
Je n'ai pas non plus très bien compris cette réponse, et je suis du
même avis concernant l'ordre de chargement des packages, même si on
est bien obligé de passer par là parfois, comme dans le cas de
`hyperref` ou `bidi`...

En tout cas j'ai compris qu'il ne fallait plus utiliser
de `\newinsert`. As-tu lu ceci:
http://www.texdev.net/2014/12/28/fixing-latex2e/
et la discussion qui suit?

**Comment by maieul** [comment]
non le \newinsert qu'on ne doit plus utiliser c'est pour le flottant (tableaux, images etc). CPar contre il y a des tas de bonne raison d'utiliser encore \newinsert, notamment pour les notes de bas de page (parce que de toute facon on ne peux pas faire autrement et que c'est pr�vu pour). De ce point de vu cela ne change pas grand chose pour (r)eledmac.

Du coup c'est aussi pour cela qu'il faut optimiser le chargement du package eledmac. si tu a besoin juste de la serie A de notes classiques pour texte principal, passer les options nofamiliar/noeledgroup/series={A} fait gagner bcp de ressources (et de temps).

Du coup pour ce ticket on fait comment? juste une remarque dans la doc ? ou bien on fait comme bidi qui impose de charger APR�S certains packages?

**Comment by ralessi** [comment]
Je dirais faire une sorte d'avertissement, sans imposer un ordre de chargement. du genre «si vous rencontrez un pb du genre..., on vous conseille de charger eledmac *avant* (pas après!) tels packages»...

Puisque l'idée est de charger eledmac assez tôt, mais sans qu'on doive le charger trop tôt en fait. Dans mon cas, c'est le recours massif à la biblio qui a tout fait sauter, car je mets des insertions de biblio dans l'apparat critique presque à chaque ligne. C'est assez particulier, j'ai même dû adapter les formats de citation pour cela.

Combien d'utilisateurs seront concernés? Peut-être pas beaucoup.

**Comment by maieul** [comment]
ok. tu pourrais r�diger ce message et l'int�grer dans la doc de reledmac?

Le 25 juin 2015 � 22:56, Robert Alessi <notifications@github.com> a �crit :

**Comment by ralessi** [comment]
D'accord. Je le fais demain en même temps que la réponse pour la
poésie arabe.

**Comment by maieul** [comment]
on pourrait mettre cela en même tps que la solution pour #353.

**Comment by ralessi** [comment]
Tu veux dire pour la poésie arabe?

**Comment by maieul** [comment]
heu non� je voulais dire parler de l'ordre des chargement  des packages au m�me endroit que les infos sur morewrites

**Comment by ralessi** [comment]
J'avais perdu le fil.

**Comment by maieul** [comment]
ca peut se comprendre. bon, c'est résolu.
