### ISSUE TITLE
\numberpstarttrue perturbe le texte critique

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#329]
Je ne suis pas vraiment sûr de pouvoir faire un mwe pour cette question.

Voici: j'ai activé des deux côtés dans une édition bilingue \numberpstarttrue. Puis pour avoir les bonnes informations dans les en-tête de page, j'ai mis de chaque côté, soit avant `\begin{Right|Leftside}`:
````
\makeatletter
\renewcommand{\thepstartL}{{\bfseries I.\@arabic\c@pstartL}. }
\newcommand{\thepstartLmk}{{I, \@arabic\c@pstartL}}
\renewcommand{\thepstartR}{{\bfseries I.\@arabic\c@pstartR}. }
\newcommand{\thepstartRmk}{{I, \@arabic\c@pstartR}}
\makeatother
````
Pour pouvoir ensuite reprendre dans `\rightmark` ou `\markboth`, selon le cas: `\thepstartRmk` ou `\thepstartLmk`.

Résultat: du côté de la traduction tout se passe bien. Mais du côté du texte critique, qui est très lourd de notes, j'observe les trois phénomènes suivants:
- la numérotation des lignes est totalement perturbée;
- dans les en-tête, ce sont les derniers `\markright/\makrboth` de chaque page qui sont repris, et non les premiers comme il se doit. Je sais que cela vient de la façon dont `eledpar` gère le remplissage des pages, avec `\Pages`;
- des lignes d'apparat critique disparaissent.

Mais comment faire un mwe, puisque le phénomène n'apparaît qu'à un certain degré de complexité?

Si je désactive les `\numberpstarttrue` et que je fais à la main des `\markboth`, tout redevient normal.

**Comment by maieul** [comment]
je suis assez �tonn�. Comment d�finit tu ton markboth \ markright? peux tu me fournir un MWE sans les erreur, juste que je comprennent ce que tu fais exactement

**Comment by ralessi** [comment]
> je suis assez étonné. Comment définit tu ton markboth \ markright? peux tu me fournir un MWE sans les erreur, juste que je comprennent ce que tu fais exactement

Voici un mwe. Tu remarquera que les informations portées dans les en-tête ne sont pas bonnes: à gauche, c'est la référence au dernier paragraphe. À droite, c'est la référence au permier paragraphe.

Et encore: si l'on veut vraiment respecter les règles d'un livre, on devrait avoir 4 en haut et à droite de la page 5, car la page 5 commence par la fin du § 4... Mais cette dernière erreur est aussi vieille que LaTeX et la classe book!

````
\documentclass{book}

\usepackage{lipsum}

\usepackage{eledmac,eledpar}

\begin{document}

\begin{pages}

\begin{Leftside}
  \beginnumbering

\pstart
\markboth{1}{}1
\lipsum[1]
\pend

\pstart
\markboth{2}{}2
\lipsum[1]
\pend

\pstart
\markboth{3}{}3
\lipsum[1]
\pend

\pstart
\markboth{4}{}4
\lipsum[1]
\pend

\pstart
\markboth{5}{}5
\lipsum[1]
\pend

\pstart
\markboth{6}{}6
\lipsum[1]
\pend


  \endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering

\pstart
\markright{1}1
\lipsum[1]
\pend

\pstart
\markright{2}2
\lipsum[1]
\pend

\pstart
\markright{3}3
\lipsum[1]
\pend

\pstart
\markright{4}4
\lipsum[1]
\pend

\pstart
\markright{5}5
\lipsum[1]
\pend

\pstart
\markright{6}6
\lipsum[1]
\pend


  \endnumbering  
\end{Rightside}

\end{pages}

\Pages

\end{document}
````

**Comment by ralessi** [comment]
Tiens les 4 apostrophes inversées ne marchent pas pour mettre en valeur du code?

Depuis que j'ai abandonné l'idée de numéroter mes paragraphes avec `\numberpstarttrue` et que je le fais à la main, j'ai supprimé les marques dans les pages de gauche. D'ailleurs, dans les Budé, il n'y en a pas. Ouf.

Quant à l'erreur traditionnelle des pages de droite, eh bien, je pense que je les corrigerai à la main en mettant des `\markright` faux le cas échéant. Une chose qu'on ne devrait pas avoir à faire, mais qu'il faut faire une fois le travail tout à fait terminé.

![bude](https://cloud.githubusercontent.com/assets/389498/8500684/ae02acce-219e-11e5-9907-85abcdea3150.png)

**Comment by maieul** [comment]
bon, je regarderai tout cela dans le courant de l'�t�...
la liste des bugs � r�soudre s'accumule...

**Comment by ralessi** [comment]
Honnêtement, eledmac/eledpar marchent extraordinairement bien avec des textes d'une complexité effrayante. Il s'agit là bugs microscopiques.

**Comment by ralessi** [comment]
Voici comment le problème peut être résolu, et il n'a rien à voir avec eledmac. Il faut lire la documentation de `fancyhdr`, point 9 pages 9-10:
>The \leftmark contains the Left argument of the Last \markboth on the page, the \rightmark contains the Right argument of the fiRst \markboth or the only argument of the fiRst \markright on the page. If no marks are present on a page they are “inherited” from the previous page.

Tel est le mécanisme de LaTeX.

Le point 19 du même document fournit une piste vers une solution dont voici un premier mwe qui marche parfaitement.

Reste le problème relatif à `\numberpstarttrue` dans les pages avec un grand nombre de notes critiques.

````
\documentclass{book}

\usepackage{extramarks}
\usepackage{fancyhdr}
\fancyhead{}
\fancyhead[LE,RO]{page \thepage}
\fancyhead[LO]{section \firstrightxmark}
\fancyhead[RE]{section \firstleftxmark}
\pagestyle{fancy}


\usepackage{lipsum}

\usepackage{eledmac,eledpar}

\begin{document}

\begin{pages}

\begin{Leftside}
  \beginnumbering

\pstart
\extramarks{1}{}1
\lipsum[1]
\extramarks{1}{}
\pend

\pstart
\extramarks{2}{}2
\lipsum[1]
\extramarks{2}{}
\pend

\pstart
\extramarks{3}{}3
\lipsum[1]
\extramarks{3}{}
\pend

\pstart
\extramarks{4}{}4
\lipsum[1]
\extramarks{4}{}
\pend

\pstart
\extramarks{5}{}5
\lipsum[1]
\extramarks{5}{}
\pend

\pstart
\extramarks{6}{}6
\lipsum[1]
\extramarks{6}{}
\pend


  \endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering

\pstart
\extramarks{}{1}1
\lipsum[1]
\extramarks{}{1}
\pend

\pstart
\extramarks{}{2}2
\lipsum[1]
\extramarks{}{2}
\pend

\pstart
\extramarks{}{3}3
\lipsum[1]
\extramarks{}{3}
\pend

\pstart
\extramarks{}{4}4
\lipsum[1]
\extramarks{}{4}
\pend

\pstart
\extramarks{}{5}5
\lipsum[1]
\extramarks{}{5}
\pend

\pstart
\extramarks{}{6}6
\lipsum[1]
\extramarks{}{6}
\pend


  \endnumbering  
\end{Rightside}

\end{pages}

\Pages

\end{document}
````

**Comment by ralessi** [comment]
Deux précisions:
1. on aura compris que le recours au package `extramarks` n'est indispensable que si l'on veut avoir un affichage correct des en-tête des pages de gauche. Pour les pages de droite, il suffit de répéter la commande `\markboth{}{}` en début et en fin de paragraphe.
2. l'ordre
````
\pstart
\markboth{}{}
[...]
\markboth{}{}
\pend
````
perturbe la mise en page et finit par provoquer des débordements de pages de droites sur des pages de gauche quand les notes critiques sont très abondantes. En revanche:
````
\pstart[\markboth{}{}]
[...]
\pend[\markboth{}{}]
````
ne semble poser aucun problème.

**Comment by ralessi** [comment]
Et pour terminer, je me demande si le problème que j'ai soulevé dans ce billet, à savoir que `\numberpstarttrue` perturbe le texte critique, ne vient pas du fait que mes `\markboth` étaient placés juste *après* `\pstart` et non pas *en option* à `\pstart`.

**Comment by ralessi** [comment]
Confirmé: l'élément perturbateur était bien `\markboth{}{}` *après* `\pstart`, et c'est l'activation de `\numberpstarttrue` qui a révélé cela.

En revanche, on ne peut utiliser la valeur retournée par le compteur `\thepstartX` dans la zone d'en-tête sans rencontrer le problème que je décris plus haut. Pour avoir un formatage correct, il faut passer par la solution que je suggère. Sauf à l'intégrer dans le mécanisme de comptage des `\pstart`?

Mais il n'y a pas de bug, cher Maïeul!

**Comment by maieul** [comment]
j'ai pas tout suivi, mais l'essentiel est que cela soit résolu :-)
