### ISSUE TITLE
[Feature request] mise en page des notes de fin

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#330]
Est-il possible de rendre disponibles les numéros des pages (ou pour certains des `pstart`) utilisés dans les notes de fin pour les zones d'en-tête des pages?

De sorte que l'on pourrait avoir dans les en-tête: «Notes relatives aux pages xx-yy».

**Comment by maieul** [comment]
a priori oui, il y a la commande \printendnum qui recoit le num�ro de page. Reste � envisager de mettre un hook dessus pour executer une commande

**Comment by ralessi** [comment]
Ce serait un pas supplémentaire vers un package non plus seulement d'édition critique, mais d'édition critique et commentée.

À ce titre, il pourrait être intéressant de pouvoir ajouter au milieu des notes de fin des paragraphes non liés à des lignes précises du texte, mais qu'on pourrait intercaler pour présenter, dans le commentaire, des exposés généraux avant le commentaire ligne à ligne lui-même.

On peut actuellement y arriver en supprimant les numéros dans les notes de fin. Mais ici, je veux parler de paragraphes éventuellement précédés d'intertitres, comme ici:
![extrait](https://cloud.githubusercontent.com/assets/389498/8512323/8fe0f476-233d-11e5-8441-06c00bb293f4.jpg)

**Comment by Doc73** [comment]
Yes! This is nearly what I meant in #328!

Maieul, you could merge the two issues!

**Comment by ralessi** [comment]
Hi Domenico,

So it happens that we are trying to achieve the same.  I came with good news: I just tried to insert a `\subsection{}` command *within* some `\Aendnote{}`, and it worked.  Outstanding, isn't it?

It sounds to me as though everything is in order. Most needed are facilities for easily constructing running headers of the form “Commentary to pp. xx--yy”.

**Comment by Doc73** [comment]
In truth, I was thinking of something more simple, but it is clear that such a development will make ```eledmac``` considerably more powerful!
Thank you very much to both!

**Comment by ralessi** [comment]
You are quite right on this point.  But given that structuring commands are accepted in `\Xendnote{}`-like environments, we may content ourselves with setting up a few high-level commands that will do the job.

**Comment by ralessi** [comment]
@maieul 

Il y a un moyen de tout faire marcher simplement avec des commandes de haut niveau. Il faut évidemment adapter, mais voici au moins un scenario qui fonctionne sans erreur:

- Mettre ceci dans le préambule:
````
\newcommand{\Acomnote}[1]{%
\Aendnote{\markboth{(P. \xpageref{#1})}{(P. \xpageref{#1})}\input{note-#1}}}
\robustify{\Acomnote}
````

- Dans le texte critique, on dispose désormais d'une commande `\Acomnote{}`. Voici comment on l'utilise:
  - juste avant `\edtext{}{}` mettre un `\edlabel{<label>}`
  - insérer ensuite dans le 2e argument de `\edtext{}{}`: `\Acomnote{<label>}`
  - ouvrir un nouveau fichier `note-<label>.tex
  - saisir dans ce fichier le commentaire: dans ce commentaire, on peut mettre des notes de bas de page (!), des paragraphes séparés, et même des commande de type `\section{}`.
- compiler.

On obtient alors un commentaire lié au texte critique, avec une zone d'en-tête qui reprend automatiquement le numéro de la page que l'on est en train de commenter. On peut même ajouter le numéro de la ligne dans l'en-tête si l'on veut.

J'ai choisi de mettre le commentaire dans des petits fichiers séparés pour ne pas perturber la lecture du code dans le texte critique. À mon avis, c'est ce qu'il faut faire.

Conclusion: comme cette commande est très simple, est-il utile de compliquer le code? Voici ce que cela donne. À comparer avec l'image que je donne au début.

![capture](https://cloud.githubusercontent.com/assets/389498/8512881/d3ebb458-2356-11e5-89fe-487ade40a11d.png)

**Comment by maieul** [comment]
ok, l� j'ai du mal � suivre. je reprendrai tout cela au propre apr�s la sortie de reledmac/reledpar

**Comment by ralessi** [comment]
Bon courage pour cela. Le problème soulevé ici est bien pris en charge par les fonctions d'eledmac. C'est juste une affaire de documentation. Après tout, on trouve bien déjà dans le manuel des conseils pour faire ce type de commande (p. 21-22).

**Comment by ralessi** [comment]
En fait, pour arriver à faire un vrai commentaire suivi attaché au texte avec eledmac/elepar, ne manque que l'option `nonum` (entendue comme nopage + nonum) suggérée par @Doc73 dans son ticket #328.

C'est dans ce type de note qu'on pourrait mettre des introductions à certaines sections du texte commenté.

**Comment by maieul** [comment]
bon, je relis tout cela, et je ne suis pas sûr de comprendre exactement ce que vous voulez. En gros il s'agirait de pouvoir introduire du texte ENTRE les notes? ou c'est plus que cela ?

**Comment by ralessi** [comment]
Oui, entre les notes, comme quand on lit «638-89: First stasimon» dans l'image du 3e post plus haut. C'est un début de note, sous la forme d'un titre, et ce n'est pas numéroté.

Mais avec l'option `nonum` pour les notes de fin, c'est désormais possible: il suffit d'appeler une note `nonum` au début d'une section, par exemple sur le premier mot du titre d'une section, et le tour est joué, puisqu'on peut mettre des `\section` dans la note de fin elle-même, c'est-à-dire dans le commentaire.

**Comment by maieul** [comment]
du coup, tu pense qu'il y a plus besoin de faire quelque chose en plus ? dans ce tu pourrais propose un MWE ?

ps : d�clarer une command avec \newcommand + la robustifer avec \robustify peut se faire en une seule �tape : \DeclareRobustCommand

**Comment by ralessi** [comment]
> du coup, tu pense qu'il y a plus besoin de faire quelque chose en plus ? dans ce tu pourrais propose un MWE ?
> ps : déclarer une command avec \newcommand + la robustifer avec \robustify peut se faire en une seule étape : \DeclareRobustCommand

Pas de problème: je vois cela demain matin.

**Comment by maieul** [comment]
je clos. fais une pull request lorsque tu aura ton exemple.

**Comment by ralessi** [comment]
Ah j'avais oublié.
