### ISSUE TITLE
\eledchapter{} out of sync

### ISSUE THREAD

**Issue by mxordn** [maieul/ledmac#337]
With the newest version of eledmac/eledpar and KOMA-Script there's a strange behaviour regarding `\eledchapter*{}`. The parallel pages are not in sync but instead there's a blank page inserted, which causes the leftside to start on the right side. After that three blank pages are inserted again to get the right side started on a right side.

With the book-class everything works fine so the reason could be a change in the KOMA script-class and maybe this has also something to do with the issue #331 about the `\paragraph{}`-sectioning which I opened a few days ago. Is there a chance to get scrbook working again?

Here's an MWE:
```
\documentclass[11pt,a4paper,BCOR=12mm,DIV=14]{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[ngerman, latin]{babel}
\usepackage[T1]{fontenc}
\usepackage{eledmac}
\usepackage{eledpar}

\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
\eledchapter*{Hallo}
\pend
\endnumbering
\end{Leftside}
%ENDE LINKE SEITE


%BEGINN RECHTE SEITE
\begin{Rightside}
\beginnumbering
\pstart
\eledchapter*{Hallo}
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
```

**Comment by mxordn** [comment]
The redefinition of the \chapter command solved the problem. But I don't know if there a more elegant solution dealing with KOMA-script.

```
\documentclass[11pt,a4paper,BCOR=12mm,DIV=14]{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[ngerman, latin]{babel}
\usepackage[T1]{fontenc}

    \makeatletter
    \renewcommand\chapter{\par%
      \thispagestyle{\chapterpagestyle}%
      \global\@topnum\z@
      \@afterindentfalse
      \secdef\@chapter\@schapter}
    \makeatother
    
\usepackage{eledmac}
\usepackage{eledpar}
\usepackage{palatino}
\renewcommand{\paragraph}[1]{\noindent\textbf{\sffamily #1}\quad}

\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
\eledchapter*{Hallo}
\pend
\endnumbering
\end{Leftside}
%ENDE LINKE SEITE


%BEGINN RECHTE SEITE
\begin{Rightside}
\beginnumbering
\pstart
\eledchapter*{Hallo}
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
```

**Comment by maieul** [comment]
please try branch "issue337-366"  (based on reledpar/reledmac).

**Comment by Doc73** [comment]
The above sample is fine, but I must confess to you that, in the meantime, I switched to standard book class. :-D

**Comment by maieul** [comment]
I think it is a better way. However, I can think problem is solved.

**Comment by Doc73** [comment]
:+1:
