### ISSUE TITLE
One migration readme

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#339]
Hey,

I just tried the migration to reledmac with one of my projects and apart from some minor things it seems to be working great.

One thing I think would be good to have: If you could add one "migration readme", consisting only of the required appendix chapters of reledmac and -par. This way migration should be way easier, as currently when some command seems to be broken I have to search through the whole document and then again through the other one in the worst case ...

**Comment by maieul** [comment]
I could add a README refering to the chapter in the handbook, but this appendix is printed in the TOC. I can't understand you didn't find it.

**Comment by baem2** [comment]
I found it, that's not the point.

But during migration, I tried to TeX my project files, and then I got the error "command XYZ not found". Now I had to search through both documents until I found the new command. I know, there's just two tables where I can look for the deprecated commands, all I am saying is it would be way faster if those two tables would be in one small document: So there's one place to look and search, and it's just the required info in that doc, not 300 more pages.

As said, that's just an item on the whishlist.

**Comment by maieul** [comment]
I don't understand why you need a smaller file instead of a section in the file. Is it because of the pdf searching engines?

**Comment by baem2** [comment]
Yes, searching for a command can take a while, also because you have to click through all the findings in the code documentation ...

**Comment by maieul** [comment]
Ok. Maybe I will out all the migration handbook

**Comment by maieul** [comment]
would such file  be what you need ? 
http://geekographie.maieul.net/IMG/pdf/migration-example.pdf

**Comment by baem2** [comment]
Yap, exactly, thank you very much!

**Comment by maieul** [comment]
ok, so integrated on branch reledmac. we can close.
