### ISSUE TITLE
Right line numbers on left side now

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#340]
With reledmac, it seems the line numbers of the right pages/columns are on the left side of the text now. Before they were on the right side of the text.

MWE: Just look into the example files.

**Comment by maieul** [comment]
ok, I will look tonight. It should not be hard to restore previous behavior.

**Comment by maieul** [comment]
the version on the reledmac branch should solve this problem.

**Comment by baem2** [comment]
Yup, working fine in reledmac branch, thanks.
