### ISSUE TITLE
Some minor issues in reledmac doc

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#341]
Dear Maieul, I tested ```reledmac``` in my major project and all went fine.

Here some corrections in tab at pag. 260 of doc:
- Missing ```\noXlemmaseparator```
- ```\Xnumberonlyfirstintwolines``` instead of ```\XnumberonlyfirstinXtwolines```

**Comment by maieul** [comment]
thanks for your test. I am glad all is fine. I will correct your issue this night!

**Comment by maieul** [comment]
You are right, `\noXlemmaseparator` should become `Xnolemmaseparator`. It is done now.
The second problem was not in the handbook, but in the code. The good command is indeed `\Xnumberonlyfirstintwolines`.

Thanks for you accuity.
