### ISSUE TITLE
\bhookXnote customisation ignored in paragraph-style footnotes

### ISSUE THREAD

**Issue by talazem** [maieul/ledmac#342]
I am using \bhookXnote{\linespread{\mylinespacing}} in order to set line spacing when the footnote are printed. When the footnotes are in blocks, the \bhookXnote works fine. When they are in paragraph (using \footparagraph{A}, for example), then my custom line spacing is ignored. 

Notice, in my MWE below, that the \Afootnote stream, which is in paragraph-style, is ignoring my custom linespacing, while the \footnoteB stream, which is in block-style, is implementing it.

Does \bhookXnote{\linespread{\mylinespacing}} not apply to footnotes typeset as one paragraph?

- - -

\TeXXeTstate=1

\documentclass[11pt,a4paper]{memoir}
\usepackage{fontspec} 

\DisemulatePackage{setspace}
\usepackage{setspace}

%%% CRITICAL EDITION APPARATUS 

\usepackage[series={A,B,C}]{eledmac}

\footparagraph{A}
\bhookXnote{\linespread{\mylinespacing}}
\bhooknoteX{\linespread{\mylinespacing}}
\def\mylinespacing{1.1}

\fnpos{critical-familiar}

\newcommand{\VAR}[2]{\edtext{#1}{\Afootnote{#2}}}
\newcommand{\NOTE}[1]{\footnoteB{#1}}

%%% DOCUMENT %%%

\begin{document}

\beginnumbering
\begin{Spacing}{1.6}
\pstart

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque molestie dictum quam non congue. This is a note. Integer ut dolor vel mi vestibulum molestie vel et nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\NOTE{Maybe this could have been ‘elite’.} Pellentesque molestie dictum quam non congue. Integer ut dolor vel mi vestibulum molestie vel et nulla. \VAR{AjEeB}{L : Morbi id justo vitae quam rhoncus tincidunt ut adipiscing nisi amos namos nomos stratos delerious C} Lorem ipsum \VAR{dolor}{L : Oh dear.} sit amet, consectetur adipiscing elit. Pellentesque molestie dictum quam non congue. Integer ut dolor vel mi vestibulum molestie vel et Ghazzī.\NOTE{Perhaps this is Raḍī al-Dīn Muḥammad b. Aḥmad al-ʿĀmirī al-Ghazzī (811–864/1409–1459), a Shāfiʿī historian of Damascus who authored a biographical dictionary of Shāfiʿīs entitled Bahjat al-nāẓirīn. See Ziriklī, 5:333.} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque molestie dictum quam non congue. Integer ut dolor vel mi vestibulum molestie vel et nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque molestie dictum quam non congue.Integer ut dolor vel mi vestibulum molestie vel et nulla C. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi id justo vitae quam rhoncus tincidunt ut adipiscing nisi. Pellentesque molestie dictum quam non congue. Integer ut dolor vel mi vestibulum molestie vel et Ghazzī.\NOTE{Perhaps this is Raḍī al-Dīn Muḥammad b. Aḥmad al-ʿĀmirī al-Ghazzī (811–864/1409–1459), a Shāfiʿī historian of Damascus who authored a biographical dictionary of Shāfiʿīs entitled Bahjat al-nāẓirīn. See Ziriklī, 5:333.}

\pend
\end{Spacing}
\endnumbering

\end{document}

**Comment by maieul** [comment]
paragraphed footnotes are very difficult to obtain, and many tools of normal footnotes don't work with it. As you can see, I have many issue to close, so I can't say you when I will have time for this issue.

**Comment by maieul** [comment]
For paragraphed notes, that should be made notes before inserting the notes in list of notes, but before typesetting then, when building the paragraph. Please try branch issue342 which provides \Xbhookgroup to do it (see the file issue342.tex). 

Note that is implemented only in reledmac, eledmac is not maintened anymore.

**Comment by maieul** [comment]
hi @talazem should it be possible to have feedback ?

**Comment by talazem** [comment]
Da Maïeul,

My apologies for the delay but I haven't been able to test yet. I hope to do so soon and get back to you. 

Talal

**Comment by maieul** [comment]
hi @talazem some feedback?

**Comment by maieul** [comment]
hi @talazem I let you to next week-end to try. After that I will merge in the stable branch.

**Comment by maieul** [comment]
ok, too late, I close.
