### ISSUE TITLE
[Support] place de \setspace

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#344]
Où faut-il mettre la commande `\setspace` pour ne modifier l'espacement que d'un seul côté avec `eledpar`?

**Comment by maieul** [comment]
actuellement ce n'est pas possible ...

c'est une demande r�currente, mais qui n�cessite pas mal d'adaptation. Il faudrait que j'imagine un AtEveryLeftPage et un AtEveryRightPage

**Comment by ralessi** [comment]
Aïe. Merci de ta réponse.

Après examen à la loupe de plusieurs volume de Budé, je me suis rendu
compte qu'ils rattrapaient les décalages entre le côté français (plus
long) et le côté grec (plus concis) par un interlignage légèrement
supérieur du côté grec.

Je tourne en rond sur cette question de la synchronisation depuis deux
semaines. J'ai modifié dans tous les sens les commandes \checkpageL et
\checkpageR, mais sans arriver à trouver un bon facteur.

**Comment by maieul** [comment]
oui, je sais.  A mon sens typographiquement c'est pas terrible, mais peut �tre qu'en terme de synchronisation cela serait le mieux�
cela �tant ce n'est pas une fonction tr�s compliqu� � int�grer (par contre AtEveryLeftPage est peut �tre pas terrible comme nom, trop g�n�rique). Il faut regarder du c�te des fonctions clearpage et tuti quanti, qui sont charg�es de faire la bascule entre gauche et droite�

MAIS cela voudra dire qu'il ne faudra plus compter sur le comptage des lignes par eledpar (le fameux minoftwo) pour la synchronisation. Et du coup algorithmiquement on en prend un coup�

**Comment by ralessi** [comment]
Alors je ne sais pas si c'est un bénéfice, même si tous les essais que
j'ai faits pour intervenir sur la synchronisation ne m'ont pas permis
d'y voir clair sur cette question. Je pense que cela vaut la peine
d'essayer pour voir.

En fait, il y a détail qui me chiffonne: quand on parle de
synchronisation de textes parallèles, c'est facile à comprendre:
chaque début de paragraphe doit être aligné avec le paragraphe
correspondant. Jusqu'ici, ok.

Mais quel peut-être le sens de shiftedpstarts si justement on
maintient l'idée de synchronisation? Vouloir coller les paragraphes
les uns aux autres, n'est-ce pas, justement, ne pas vouloir de
synchronisation?

Ce qu'il faudrait avoir, c'est la possibilité d'avoir, d'un côté, une
édition critique compacte, comme si on la sortait en recto-verso avec
seulement eledmac, et, de l'autre côté, une traduction totalement
indépendante, en texte non numéroté. On pourrait y mettre des notes de
bas de page classiques, ou des notes de fin si l'on veut.

Enfin, une fois le travail fini, une seule commande simple permettrait
de faire des coupures pour que la traduction corresponde bien au texte
édité en face.

Bref, une sorte de reledpar, mais avec un seul côté d'édition.

Actuellement, sous reledmac, on peut insérer du texte entre \pend et
\start. Avec reledpar, on ne peut pas.

**Comment by maieul** [comment]
> 
> Mais quel peut-�tre le sens de shiftedpstarts si justement on
> maintient l'id�e de synchronisation? Vouloir coller les paragraphes
> les uns aux autres, n'est-ce pas, justement, ne pas vouloir de
> synchronisation?
> 

le sens de shiftedpstarts c'est de rattraper la synchronisation � chaque page. Il faut se dire : on fait comme si on avait uns synchronisation par paragraph, sauf que sur une m�me page on "remonte" les lignes. 
Autrement dit, si j'ai 25 lignes par pages. Si � gauche j'ai 25 pleine et � droite 23 pleine et 2 vides, avec shiftedpstarts les 2 vides seront syst�matiquement � la fin ;-)  
> 
> Actuellement, sous reledmac, on peut ins�rer du texte entre \pend et
> \start. Avec reledpar, on ne peut pas.

si on peut. c'est justement le but des arguments optionnels de \pend et de \pstart.

Je te rejoins sur l'id�e d'une alternance gauche/droite sans souci aucun de synchronisation

**Comment by ralessi** [comment]
> Autrement dit, si j'ai 25 lignes par pages. Si à gauche j'ai 25 pleine et à droite 23 pleine et 2 vides, avec shiftedpstarts les 2 vides seront systématiquement à la fin ;-)  

L'idée est bonne pour rattraper la synchronisation. Mais tout est dit dans cette phrase: on veut synchroniser, et il y a un décalage à rattraper. Cependant, avec `shiftedpstart` les débuts de paragraphes à gauche et à droite ne sont plus synchronisés...

> si on peut. c'est justement le but des arguments optionnels de \pend et de \pstart.

Tu penses bien que j'ai essayé! Ça marche, mais on doit garder le même nombre de `\pstart \pend` de chaque côté, et on est rattrapé par la synchronisation au bout de quelques lignes.

> Je te rejoins sur l'idée d'une alternance gauche/droite sans souci aucun de synchronisation

Tout est là. En fait, il n'y a pas 36 possibilités:
1. édition monolingue → (r)eledmac seul;
2. deux textes édités en parallèle, comme ici: un texte grec et sa traduction latine en parallèle, avec ses variantes manuscrites → (r)eledmac + (r)eledpar;
![capture](https://cloud.githubusercontent.com/assets/389498/8676843/13e103dc-2a4c-11e5-8644-b99c699214d6.png)
3. **une** édition critque avec sa traduction en vis à vis: (r)eledmac + (r)eledpar/2, soit un demi (r)eledpar, car l'utilisation de notes critiques sous la traduction n'a aucun sens.

C'est cette dernière fonction essentielle qui fait actuellement défaut. Mais je suis tout près de trouver une solution. Actuellement, j'ai presque tout ce dont j'ai besoin. ce qui est intéressant, c'est que pour obtenir mon mwe actuel, je n'ai pas du tout chargé `eledpar`. Dans le préambule, je n'ai que:
````
\usepackage{eledmac}
\footparagraph{A}
````
Donc j'y suis presque. Je t'envoie le pdf car il ne passe pas ici. Dis-moi ce que tu en penses.

**Comment by maieul** [comment]
j'ai l'impression que ce ticket aurait du être clos automatiquement, mais cela n'a pas marché. Je ferme. Rouvrir un nouveau ticket si besoin
