### ISSUE TITLE
unexpected space around \edindex command

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#345]
In the first MWE (with xindy) a space occurs at the place, where the \edindex command is set. 
In the second MWE the space disappears. 
I am using v1.24.3.

\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[xindy]{indextools}
\usepackage[xindy,xindy+hyperref]{eledmac}
\usepackage[hyperindex=false]{hyperref}
\makeindex[title=Index verborum]

\begin{document}
\beginnumbering
\pstart
Ne bis in idem\edindex{idem}.
\pend
\endnumbering
\printindex
\end{document}

Second MWE:

\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage{indextools}
\usepackage{eledmac}
\makeindex[title=Index verborum]

\begin{document}
\beginnumbering
\pstart
Ne bis in idem\edindex{idem}.
\pend
\endnumbering
\printindex
\end{document}

**Comment by maieul** [comment]
please try branch issue345.

**Comment by sonator** [comment]
The MWEs with and without xindy are running perfectly. Thank you!
