### ISSUE TITLE
problème avec sameparallepagenumber

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#346]
ce qui expliqué par @ralessi ici https://github.com/maieul/ledmac/issues/323#issuecomment-118529211 constitue un bug distinct de #323. Donc ce ticket sera pour résoudre le bug de sameparallepagenumber + plusieur \Pages, le #323 restant pour le pb de la première numérotation. Ne melangeons pas tout.

**Comment by ralessi** [comment]
En effet!

**Comment by maieul** [comment]
j'ai trouvé l'algorithme pour résoudre ce pb. Il me reste plus qu'à le documenter...

**Comment by ralessi** [comment]
Magnifique!

**Comment by maieul** [comment]
j'ai parl� trop vite. mon algo r�gle le pb du \Pages suivants, mais maintient un autre probl�me tout aussi grave : LaTeX se basant sur la parit� du num�ro de page pour savoir si une page est gauche ou droite, il faut absolument, si on veut ne pas avoir de probl�me de positionnement des num�ro de notes de bas de page, que le counter page soit syst�matiquement reconstruit en num�ro pair pour une page de gauche.

la seule solution : apr�s un \Pages, tester la parit� du num�ro, voir s'il y a un d�calage, et si oui le stocker. Ensuite patcher \thepage pour afficher le comptuer page avec un d�calage�
pf� technique !

**Comment by ralessi** [comment]
Et cela sans conséquence sur le reste du document? Par ailleurs (mais je n'en sais rien), certaines classes de document ne patchent-elles pas elles aussi \thepage?

**Comment by maieul** [comment]
> 
>  Par ailleurs (mais je n'en sais rien), certaines classes de document ne patchent-elles pas elles aussi \thepage? 

tr�s certainement. mais le patch en question est l'ajout de deux commandes, respectivement en d�but et en fin. Pour s'assurer qu'un autre package ne surcharge pas ce patch, on utilise AtBeginDocument.

Mais je viens de me rendre compte que \frontmatter \mainmatter etc modifie aussi \thepage. Du coup il faudrait les patcher pour qu'elle patche \thepage�
pf,, je fais encore un test, mais j'int�grerai tout cela demain (les tests sans \mainmatter, \frontmatter fonctionne parfaitement, et c'est la seule piste viable : g�rer cela uniquement au niveau de l'affichage. Tout cela parc que tex ne sait pas reconnaitre nativement une page de gauche d'une page de droite�)

**Comment by maieul** [comment]
peut tu tester la branche issue346 ? normalement cela devrait être bon.

**Comment by ralessi** [comment]
Je viens de faire le test en triturant le fichier issue346.tex. Il me semble que tout marche parfaitement.

Demain, je comptais migrer tout mon travail d'édition actuel sous reledmac/reledpar: je ferai aussitôt le test, puis je confirmerai que tout marche. Mais là, je n'ai pas de doute, je suis sûr que ce sera bon.

**Comment by maieul** [comment]
ok, du coup pour l'anglais on fait quoi ? tu veux un diff maintenant, ou on remet cela � des jours meilleurs?

**Comment by ralessi** [comment]
Je commencerai à relire l'anglais à partir de jeudi, après avoir travaillé, un peu tous les soirs. Je n'ai pas du tout vu encore quel est le volume, mais a priori, je pense qu'entre jeudi et dimanche ça devrait être bon.

Donc ok pour le diff.

**Comment by maieul** [comment]
voil� donc le diff pour #346.  j'attendrai tes corrections avant de supprimer la branche. on va dire que la r�solution de ce bug est un bonus de reledmac. (j'ai du reste pas encore r�dig� le changelog de reledmac)

https://github.com/maieul/ledmac/compare/34267ca...issue346

**Comment by ralessi** [comment]
Ok, merci!

**Comment by ralessi** [comment]
Je viens de faire le test avec la dernière version dans la branche ledmac-reledmac et un gros fichier, et cette fois les numéros des pages sont bons, même quand on change de «section».

**Comment by maieul** [comment]
on ferme, le diff n'est de toute facon plus pertinent suite au modif en #351

**Comment by ralessi** [comment]
> on ferme, le diff n'est de toute facon plus pertinent suite au modif en #351

ok. je prendrai le travail disons à partir de dimanche?

**Comment by maieul** [comment]
yep, je pensais sortir reledmac dimanche

**Comment by ralessi** [comment]
Parfait. Je commencerai donc le travail dimanche, ou même demain soir si le diff est prêt.

**Comment by maieul** [comment]
il n'y aura pas de diff possibble, trop de changement depuis eledmac

**Comment by ralessi** [comment]
> il n'y aura pas de diff possibble, trop de changement depuis eledmac

Donc on prendra le texte par petits bouts. Tu me donneras un ordre de
priorité, et je relirai. Pas besoin de diff.

**Comment by maieul** [comment]
je dirais que la priorit� est la doc utilisateur, notamment l'introduction. Mais bon, on n'a qu'� faire de mani�re lin�aire...

**Comment by maieul** [comment]
en fait si il y a une priorit� : les fichiers qui d�crivent les �tapes de migration. c'est ce que le gens vont lire au moment de sortir reledmac. 

il faut aussi que je pr�pare la doc de eledmac pour dire que obsol�te + mettre une option noreledmac comme pour noeledmac (par contre est-ce que je modifie ledmac, pour signaler que reledmac est sorti?)

**Comment by ralessi** [comment]
Donc si j'ai bien compris, il faut attendre que reledmac soit sorti pour bosser sur le texte? Ou pas?

**Comment by maieul** [comment]
en fait cela ne change pas grand chose. si tu veux bosser sur tout le texte de reledmac, note juste � partir de quel commit tu travail ;-)

par contre je pense qu'il serait pas mal de relire deja maintenant les fichiers 
https://github.com/maieul/ledmac/blob/reledmac/doc-include/migrate-mac.dtx
et
https://github.com/maieul/ledmac/blob/reledmac/doc-include/migrate-par.dtx

sur la partie concernant reledmac (qui � relire encore apr�s si j'ajoute des choses)

**Comment by ralessi** [comment]
Parfait. Cela me donne un ordre de travail. Je commence demain soir.
