### ISSUE TITLE
Multiple series of endnotes not working on different places

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#348]
http://tex.stackexchange.com/q/255598/7712

**Comment by maieul** [comment]
Le pb est le suivant: lorsqu'on clot un fichier pour pouvoir lire son contenu, cela veut dire que lorsqu'on l'ouvre après, pour y réécrire, on en efface tout le contenu. Conclusion : ici le \doendnotes{A} fait perdre les notes B stockées. On pourrait reinjecter les notes A, mais non, car il se peut que notre auteur veuille des notes A ≠ pour le second texte. La seule solution : séparer les fichiers des notes, un par série... (pf, ca va encore bouffer...)

**Comment by maieul** [comment]
was asked by @mepherl

**Comment by maieul** [comment]
@mepherl : could you try branch "issue348". It is based on reledmac, that means you should maybe changes some little things in your preamble.

**Comment by mepherl** [comment]
@maieul  thank you for writing code for this! the mwe works fine! it is the first time i heard of your reledmac-efforts, which i understand and which are very welcome. nevertheless i obtain several errors in my real document and i was wondering, if you keep a list where i can find the old command next to the new ones. or do i have to go through all the examples?

**Comment by maieul** [comment]
of course, there is a list ;-). It will be included in the handbook. You can dowload the list of modification to do  here
http://geekographie.maieul.net/IMG/pdf/migration-example.pdf

I am waiting for a mwe from @ralessi, and I think reledmac could be done

**Comment by maieul** [comment]
d'après @ralessi en #353, vérifié par moi, le MWE ne fonctionnait pas. On rouvre.

**Comment by maieul** [comment]
fause allerte, on referme. Tester avec le bon package c'est mieux ;-)
