### ISSUE TITLE
[reledmac/reledpar] index non généré avec indextools + makeindex

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#351]
Soit le mwe suivant:
````
\documentclass{book}

\usepackage{fontspec}
\usepackage{libertine}
\usepackage{lipsum}

\usepackage{indextools}
\usepackage{reledmac}
\usepackage{reledpar}

\makeindex[name=mots, title={Index verborum}]

\begin{document}

\begin{pages}

\begin{Leftside}  
  \beginnumbering
  \pstart
  Voici un \edindex[mots]{premier}premier mot que je veux indexer.
  \pend
  \endnumbering
\end{Leftside}

\begin{Rightside}
  \beginnumbering
  \pstart
  Voici un \edindex[mots]{deuxième}deuxième mot que je veux indexer.
  \pend
  \endnumbering
\end{Rightside}

\end{pages}

\Pages

\printindex[mots]

\end{document}
````

L'index demandé à la fin du document n'est pas généré. Voir l'erreur dans les fichiers mots.idx` et `mots.ilg`.

**Comment by maieul** [comment]
haha ! c'est la r�solution de #341 qui cr�e ce pb !!!!

bon, reste � voir comment on r�soud le pb (en fait assez facilement, en th�orie du moins)

**Comment by maieul** [comment]
la branch issue351 devrait corriger le pb de génération du .idx. Il y a par contre un problème avec indextools, qui ne génère pas le .ind mais c'est indépendant..

**Comment by maieul** [comment]
a non c'est mon indextools local qui avait des problèmes ;-)

**Comment by maieul** [comment]
donc : peux tu tester ?

**Comment by ralessi** [comment]
Cette fois c'est bon, les index sont là. J'ai cependant ceci au moment où, à la compilation, les fichiers générés sont insérés:
````
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\c@page' on input line 217.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\numexpr' on input line 217.
````

etc. Mais les index sont bons d'après tout ce que j'ai pu vérifier.

**Comment by maieul** [comment]
non, ca va pas, il y a un pb avec #341 en ce qui concerne les num�ros de page dans la table des mati�res...

**Comment by maieul** [comment]
depuis tout à l'heure je parle de #341 alors qu'il s'agit de #346.

**Comment by ralessi** [comment]
C'est exact, je viens de le vérifier en consultant la table des matières de mon édition. Cela m'avait échappé.

**Comment by maieul** [comment]
et comble d'ennui,  la r�solution de #348 provoque des no room for \newwrite lorsqu'on ajout une table des mati�res. 
Bon je vais supprimer la s�rie Z et dire qu'on utilise le package morewrite, mais c'est vraiment pas top, car ca ralenti consid�rablement les choses.

Je me demande si on ne pourrait pas faire autrement pour les notes de fin. A priori elle sont toujours APR�S le texte, du coup il n'y a pas de raison de le stocker dans un fichier. On pourrait les ajouter � une commande mais
1) pas s�r que plus optimal en terme de performance non plus
2) et puis quid si quelqu'un veut mettre les notes de fin au d�but ? ou dans un fichier � part ?

**Comment by ralessi** [comment]
Les notes de fin au début? Je pense que personne ne voudra le faire: `endnote` n'a pas de sens dans ce cas. Dans un fichier à part, je ne comprends pas ce que cela veut dire.

**Comment by maieul** [comment]
je suis d'accord que des notes de fin au d�but n'ont gu�re de sens, mais il y a parfois des cas tellement surprenants que je me m�fie.

tu pourrais avoir un volume de texte et un volume de notes ;-) et du coup c'est un des int�r�t d'avoir les notes de fin dans un fichier auxiliaire plutot que dans une commande.

Je crois qu'on va rester le package morewrites, mais j'ai vraiment l'impression que cela ralenti. Une solution serait alors de dire dans la doc de le charger au cas o�� mais les gens ne lisant pas la doc...

**Comment by ralessi** [comment]
Pour les notes dans un volume séparé, il y a l'excellentissime package subfiles. Il suffit de déclarer le volume de notes comme subfile, et c'est tout. On peut même, au choix, soit compiler le fichier maître, soit n'importe lequel des subfiles déclarés.

C'est ce que j'utilise depuis longtemps.

**Comment by maieul** [comment]
a je ne connaissais pas.

bon j'arrive enfin au bout dun pb #351 + #346. On va juste g�rer notre propre compteur � part� je t'envoie un mail d'ici 20 minutes pour test

**Comment by ralessi** [comment]
> a je ne connaissais pas.

À découvrir d'urgence!

**Comment by maieul** [comment]
peux tu tester la branche issue351 ? elle tente de résoudre #346 sans engendrait les ≠ pb qu'on a listé (et comme tjr : simple is beautiful : d8cd122)

**Comment by ralessi** [comment]
Cette fois, la table des matières est bonne, et je n'ai plus les avertissements de hyperref.

Mais il faut le dire: `morewrites` ralentit considérablement la compilation.

**Comment by ralessi** [comment]
Exemples de temps de compilation sur le fichier actuel de mon édition:
- reledmac+reledpar+morewrites: 1:04:50
- eledmac+eledpar (dernière version): 00:38;73

No comment. Je me demande s'il est bien la peine de stocker les notes de fin dans un fichier. Si c'est seulement pour pouvoir les mettre dans un volume séparé, je pense que la regression dans le temps de compilation ne vaut pas le bénéfice, d'autant que `subfiles` fait parfaitement l'affaire. Si c'est pour d'autres raisons, c'est autre chose.

**Comment by maieul** [comment]
oui, c'est embetant. On en parle en #353 ?

**Comment by ralessi** [comment]
> oui, c'est embetant. On en parle en #353 ?

Ok
