### ISSUE TITLE
pb de morewrite.

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#353]
- morewrite est désormais nécessaire lorsqu'on utilise les notes de fin avec bcp de series + tableofcontents + des indexs.
- mais cela ralentit considérablement
- plusieurs solutions possibles:
  - ne pas le charger automatiquement et laisser les personnes s'en charger tout seul.
  - le charger de manière conditionnel, si nbr de series > 5 + endnotes + eledsec
  - <s>ne pas utiliser \immediate, mais je ne suis pas sur que cela marche (non en fait cela ne marche pas, c'est le \newwrite qui pose souci)</s>
 - ne pas stocker les notes dans un fichier mais dans une commande, avec des \apptocmd. Mais j'ai des doutes sur l'efficacité en terme de vitesse. apptocmd est une commande lourde...

**Comment by ralessi** [comment]
Dans mon cas (pour prendre un exemple), j'ai (en plus de la toc):
- deux séries de notes critiques (A, B)
- deux index
- une série de notes de fin

Pour les solutions:
- évidemment, si, dans un cas tel que le mien je pouvais m'en passer, je le ferais volontiers, quitte à y avoir recours si j'ajoute de nouvelles couches à mon travail.
- le charger de manière conditionnelle? Pas sûr. Un avertissement dans la doc suffit à mon avis, du genre de celui qu'on a pour `goalfraction`
- ne pas stocker dans un fichier: oui, mais si à la fin on est aussi ralenti, ça ne vaut vraiment plus le coup!

**Comment by maieul** [comment]
cela est en lien avec la demande de #348 de @mepherl

**Comment by ralessi** [comment]
Je suis allé voir: pourquoi dans son mwe les `\Bendnote` ont-elles disparu?

**Comment by maieul** [comment]
dans ton cas tu n'en aurais pas besoin, sous reserve que tu précise bien series={A,B}. Du coup j'imagine que l'information en doc  pourrais être la bonne solution. Pour ne pas stocker en fichier, le pb c'est que je n'ai aucune idée en terme de perf de ce que cela peut donner... Sans compter que pour imiter le comportement actuel, je risque d'avoir des cas tarabiscotés (il faudrait vider les commandes de stockages). Pas convaincu. C'est vraiment pénible cette limite de tex.

**Comment by ralessi** [comment]
Oui, j'ai bien précisé `series={A,B}`.

Mais le pb de @mepherl est en effet un vrai problème que `subfiles` ne peut permettre de contourner.

**Comment by ralessi** [comment]
Finalement, je pense que tu as raison: oui, le mieux est de stocker en fichier. C'est infiniment plus simple.

**Comment by maieul** [comment]
tu utilise quel outils pour faire tes benchmarks? je vais faire quelque tests l� entre �crire dans un fichier, utiliser un apptocmd et ecrire dans un fichier avec morewrite

**Comment by ralessi** [comment]
Le bon vieux chrono qui me sert pour la piscine!

**Comment by ralessi** [comment]
C'est la première fois que je fais ce test. J'ai appuyé sur la touche entrée et sur le chrono en même temps...

**Comment by maieul** [comment]
> Je suis allé voir: pourquoi dans son mwe les \Bendnote ont-elles disparu?

parce que tu utilise la version bugé de eledmac, pas le bon reledmac tout neuf ;-)

**Comment by maieul** [comment]
pdftex propose 
	� \pdfelapsedtime

pour les tests cela suffira

**Comment by ralessi** [comment]
Mais oui bien sûr... Vive le bon reledmac tout neuf. D'ailleurs, va-t-il arriver sur le ctan?

**Comment by maieul** [comment]
bah il viendra quand  #353 aura �t� corrig� ;-)

**Comment by ralessi** [comment]
> pdftex propose 
> 	� \pdfelapsedtime

Je ne connaissais pas du tout!

**Comment by maieul** [comment]
test rapide avec les fichiers balancés.
- écriture en fichier : 2032,8 de moyenne sur 5 essais
- commande : 1834,4 de moyenne sur 5 essais
- écriture de fichier + morewrites : 6653,6 de moyenne.

Il y a pas photo. Reste à savoir si l'avantage des commandes est décisif. Je vais faire un test avec des fichiers plus gros.

**Comment by ralessi** [comment]
C'est énorme.

**Comment by maieul** [comment]
Bon, par contre les commandes super longues, non. En bouclant 9999 fois on obtient 30 299 pour les fichiers, et 2 416 449 pour les commandes.

Conclusion : on en reste au système par fichier. Je vais supprimer l'appel à morewrite et mettre un paragraphe expliquant que faire en cas de pb. Je pensais mettre cela après le § 3 sur les options. tu pense que c'est mieux où ? (je vais du reste diviser la doc sur les options en deux : optimisation et général)

**Comment by ralessi** [comment]
C'est très net.

Pour la place, j'aurais vu:
- plutôt en 17 (Known and suspected limitations)
- avec en effet un petit avertissement en 3 et un renvoi en 17. Le petit renvoi en 3, je l'aurais mis à l'endroit où est introduite l'option `series=`

Mais je complique peut-être les choses?

**Comment by maieul** [comment]
17 oui c'est bien.par contre pas sur que renvoi depuis 3 est utile.

**Comment by ralessi** [comment]
> 17 oui c'est bien.par contre pas sur que renvoi depuis 3 est utile.

En effet, pas sûr.

**Comment by maieul** [comment]
ca va nettement plus vite sans le morewrites. Allez, c'est résolu, on ferme.

**Comment by ralessi** [comment]
> ca va nettement plus vite sans le morewrites. Allez, c'est résolu, on ferme.
Du coup où est la der de der de reledmac/reledpar? C'est la branche
issue353?

**Comment by maieul** [comment]
non, la branch reledmac. Les branches "issuexxx" sont tjr instables
