### ISSUE TITLE
reledpar : faire un résumé des options

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#357]
comme dans reledmac.

**Comment by maieul** [comment]
hi @tweh do you have the "courage" to write a summary of option of reledpar, as there is for reledmac ?

**Comment by tweh** [comment]
Sure … I’ll give it a try. But it may take some time to finish it …

**Comment by maieul** [comment]
there is no emergency. When you will do it, send the pull request to master

**Comment by tweh** [comment]
OK :-)

**Comment by maieul** [comment]
@tweh when do you think to have time?

**Comment by tweh** [comment]
Hi, I think I can finish it in the next week. OK?

**Comment by maieul** [comment]
will be nice ;-). thanks.

**Comment by tweh** [comment]
Hi :-) which branch should I start from to make the option list? (I’ll make a new branch in my repo to make the changes but, I’m not sure which one of your’s to clone …)

**Comment by maieul** [comment]
from the branch 2.2.0-2.4.0 on commit 9aca298

**Comment by tweh** [comment]
I sent a pull request :-)

**Comment by maieul** [comment]
close by #412
