### ISSUE TITLE
Optional argument of a single pstart

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#358]
The optional argument of the second pstart of the MWE has influence on the first line of the next paragraph: The hspace behind the pstart number is being ignored. 

This is not the case, when I use: \AtEveryPstart{\vskip \baselineskip{\hfill ***\hfill\strut}\vskip \baselineskip}

Sometimes it is useful to insert a vertical space before a single paragraph. 
Is there a mistake in my code? I'm using v1.24.4. 

\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage{eledmac}

\renewcommand{\thepstart}{\textbf{\arabic{pstart}.}\hspace{.2em}}

\numberpstarttrue
\firstlinenum{1}
\linenumincrement{1}

\begin{document}

\beginnumbering
\pstart
In principio erat verbum et verbum erat apud Deum et Deus erat verbum, hoc erat in principio apud Deum. Omnia per ipsum facta sunt, et sine ipso factum est nihil. Quod factum est in ipso vita erat, et vita erat lux hominum. Et lux in tenebris lucet, et tenebrae eam non comprehenderunt.
\pend

\pstart[\vskip \baselineskip{\hfill ***\hfill\strut}\vskip \baselineskip]
In principio erat verbum et verbum erat apud Deum et Deus erat verbum, hoc erat in principio apud Deum. Omnia per ipsum facta sunt, et sine ipso factum est nihil. Quod factum est in ipso vita erat, et vita erat lux hominum. Et lux in tenebris lucet, et tenebrae eam non comprehenderunt.
\pend

\pstart
In principio erat verbum et verbum erat apud Deum et Deus erat verbum, hoc erat in principio apud Deum. Omnia per ipsum facta sunt, et sine ipso factum est nihil. Quod factum est in ipso vita erat, et vita erat lux hominum. Et lux in tenebris lucet, et tenebrae eam non comprehenderunt.
\pend
\endnumbering

\end{document}

**Comment by maieul** [comment]
it was a bug linked that a classical behavior of TeX

\foo something -> space after \foo is gobble
\foo[] something -> space after \foo is kept.

The branch issue 358 should solve it. Notes eledmac is not maintened anymore, so you must migrate to reledmac (read http://geekographie.maieul.net/IMG/pdf/migration.pdf about how to migrate

**Comment by sonator** [comment]
I have kept the opportuneness to migrate my current project to reledmac/reledpar. Thanks to the instructive documentation the procedure is run without any difficulty. Chapeau!

**Comment by maieul** [comment]
and so the bug ?

**Comment by sonator** [comment]
Sorry, there is, of course,  no longer a bug!
