### ISSUE TITLE
shiftedpstarts et parledgroup

### ISSUE THREAD

**Issue by Circeb** [maieul/ledmac#359]
Bonjour,

Quand j'utilise l'option shiftedpstarts et parledgroup, la commande pour contrôler l'espacement dans l'apparat n'a plus d'effet. Voici le code

\documentclass[12pt]{book}
\usepackage{reledmac}
\usepackage{setspace}
\onehalfspacing
\Xarrangement[A]{paragraph}
\usepackage[shiftedpstarts, parledgroup]{reledpar}
\let\parledgroupnotespacing\singlespacing

\begin{document}

\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
\begin{ledgroup}
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche\edtext{gauche}{\Afootnote{gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche }}

gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche\edtext{gauche}{\Afootnote{gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche }}
\end{ledgroup}
\pend
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\pstart
\begin{ledgroup}
droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite 

droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite 
\end{ledgroup}
\pend
\endnumbering
\end{Rightside}

\end{pages}
\Pages

\end{document}

**Comment by maieul** [comment]
dans reledpar, la redefinition de parledgroupnotespacing a �t� remplac� par l'emploi de \setparledgroupnotespacing. cf d10cec9

cela �tant il reste un pb que je regarde derechef

**Comment by maieul** [comment]
peux tu essayer la version dans la branch "issue359" ?

**Comment by Circeb** [comment]
ça m'a l'air de bien marcher.

**Comment by Circeb** [comment]
Y a-t-il un moyen de régler le problème sur l'ancien eledmac ?

**Comment by Circeb** [comment]
Autre question : est-il possible de n'appliquer shiftedpstarts que localement ?

**Comment by maieul** [comment]
1) on peut mettre sur l'ancien eledpar, la modification tient en deux lignes 
https://github.com/maieul/ledmac/commit/3f2d8c3
toutefois je ne le ferai pas. Le principe de reledmac et de stopper le maintient de eledmac. Je ne vais pas commencer � faire des exceptions, sinon je ne m'en sortirai jamais.
2) pour une application local de shiftedpstarts, mettre \shiftedpstartstrue\setgoalfraction{0.95} avant le \Pages d'applications et  \shiftedpstartstfalse\setgoalfraction{0.9} avant le \Pages sans application.

**Comment by maieul** [comment]
merci de me laisser clore moi même les tickets. cela me permet d'y voir plus clair
