### ISSUE TITLE
Roman numeration pages

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#361]
Cher ami,

**Comment by maieul** [comment]
le message est coupé :)

**Comment by heinrichffleck** [comment]
Voici ancore une fois le message et l'attaché zip en extension .jpg
Salutations, Enrico Macchia
![psammites](https://cloud.githubusercontent.com/assets/13473498/8860601/314708d2-3185-11e5-8662-966af9a21628.jpg)
