### ISSUE TITLE
Roman numeration pages

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#362]
Voci le file zip (en extension .jpg) pour le problem dit: l'impossibilitè de numeration pages en Roman.
Salutations a toi et a toute le monde, Enrico Macchia
![psammites](https://cloud.githubusercontent.com/assets/13473498/8860457/3599adfa-3184-11e5-8e84-59a25943d3ee.jpg)

**Comment by maieul** [comment]
Cher ami,

je regarde cela. Mais merci la prochaine fois de produire un vrai MWE. Lire ceci sur ce qu'est un minimal working example : http://meta.tex.stackexchange.com/questions/3300/minimum-working-example-mwe dans le cas présent, je n'avais besoin que de pas grand chose pour avoir un MWE.

Le https://github.com/maieul/ledmac/blob/7bb87ab98f3d26d6f149ee66e1d9bb4d78fc101a/issue362.tex suffit largement.

**Comment by heinrichffleck** [comment]
Excuse oi, je ne l'avais pas bien entendu ça. Salut. Enrico

**Comment by maieul** [comment]
pas grave. sache juste qu'en g�n�ral c'est ce qui est demand� pour obtenir de l'aide en latex. le pb vient visiblement de la classe memoir, qui pose toujours des soucis sp�cifi

**Comment by heinrichffleck** [comment]
J'ai aussi changè de classe mais inutilment. Enrico M.

**Comment by maieul** [comment]
si, si, avec article cela fonctionne parfaitement ;-)

**Comment by maieul** [comment]
par contre \frontmatter{Roman} cela n'existe pas. c'est \frontmatter tout cour. Ou \pagenumbering{roman}.

**Comment by maieul** [comment]
le problème est résolu dans la branche 2.0.1-2.1.0, que j'espère publier dimanche sur le ctan. tu peux lire ici les instructions pour la faire fonctionner en local temporairement.
https://github.com/maieul/ledmac#debug-and-feature-requests

par contre il faut que tu fasse un \let\lineref\edlineref. Il y a un bug sur le mode eledmac-compat, que je vais résoudre de ce pas.

**Comment by heinrichffleck** [comment]
Tres tres tres merci mon cher ami, a bientot. Encore salutations et 
bonne soir, Enrico M.

**Comment by heinrichffleck** [comment]
Le probleme etait le package footmisc: il doit etre chargee avant de reledpar. C'etait ça l'origine de chaque probleme. Je vous remercie. Enrico M.

**Comment by maieul** [comment]
ce n'est pas impossible en effet qu'il pose pb. cela étant reledmac/reledpar propose des systèmes de notes similaires à footmisc.
