### ISSUE TITLE
Pages in Roman: numeration in the file index

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#370]
Cher ami, mon problem avec la numeration en Roman regarde le pages indicisées:

\documentclass[10pt,a4paper,twoside]{scrbook}
................
\usepackage{imakeidx}
\makeindex[title=Indice dei nomi]
\usepackage[series={A,B,C,D,E}]{reledmac}
\usepackage{reledpar}
...............
\begin{document}
\input{frontespice}\thispagestyele{empty}
\pagenumbering{Roman}
\input{criteria}
\pagestyle{plain}
\mainmatter
\include{biografia}
\include{libro-I}
\end{document}

le paroles indicisèes sub le fichier <<criteria>> (numeration en Roman) NE SONT PAS indicisées, mais seulment quelle avec un \include. Mais si je ecrive \include{criteria} he n'ai pas plus la numeration en Roman.

Très mersi pour votre aide. Salutation, Enrico M.
\printindex

**Comment by maieul** [comment]
votre MWE n'est pas complet. il manque les fichiers inclus.

**Comment by maieul** [comment]
please also reread the handbook. its expressly said that \makeindex must be called AFTER eledmac has been loaded.

**Comment by maieul** [comment]
Je disais : lisez aussi le manuel. Il est expressement expliqué que  \makeindex doit être appelé après que reledmac ait été chargé. 

Je close cet issue. Si le problème se pose toujours, rouvrir un ticket avec un VRAI mwe.

**Comment by heinrichffleck** [comment]
Cher ami, je l'ai charge après come dites vous,

*\usepackage[series={A,B,C,D,E}]{reledmac}
\usepackage{reledpar}
\usepackage{imakeidx}
\makeindex[title=Indice dei nomi]

*mais ma dans ce cas le systeme me dit.*

! Package reledmac Error: Imakeidx must be loaded before eledmac..**
**See the reledmac package.*

e ja' une interruption pendant la compilation. Alors: avant ou après?

Salutations e toujours tres merci, Enrico M.

Il 29/07/2015 14.26, Maïeul Rouquette ha scritto:

**Comment by maieul** [comment]
relisez la doc �12.1
1) charger imakeidx
2) charger reledmac
3) utiliser \makeindex.

Donc



\usepackage{imakeidx}
\usepackage[series={A,B,C,D,E}]{reledmac}
\usepackage{reledpar}
\makeindex[title=Indice dei nomi]

**Comment by heinrichffleck** [comment]
Je l'aavais déjà essayé cette solution. Elle marche pendant la 
compilation, mais les pages indicisèes avec en chiffres Roman ne sont 
pas indexés.

Enrico M.

Il 29/07/2015 14.46, Maïeul Rouquette ha scritto:

**Comment by maieul** [comment]
comme je vous l'ai demand� 2 fois, merci de me fournir un exemple complet. "Chez moi ca marche" avec cet exemple 

````
\documentclass[10pt,a4paper,twoside]{scrbook}

\usepackage{imakeidx}

\usepackage[series={A,B,C,D,E}]{reledmac}
\usepackage{reledpar}
\makeindex[title=Indice dei nomi]
\begin{document}

\pagenumbering{Roman}
\beginnumbering
\pstart
Cicero\edindex{Cicero}
\pend
\endnumbering

\printindex
\end{document}

````


c'est donc que vous utilisez autre choses. Mais comme je ne peux pas savoir quoi, je ne peux pas vous aider�.
