### ISSUE TITLE
[reledmac] Typo in doc

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#372]
Chapter 4.2.3 and 4.2.4 are duplicates. :smile:

**Comment by maieul** [comment]
no,

4.2.3 "Content before specific \pstart and after specific \pend"
4.2.4 "Content before every \pstart and after every \pend"

before ≠ every.

**Comment by Doc73** [comment]
Ok, but I will confess to you that the documentation is not very clear.
In particular, I'can't understand the use of these commands and their specific difference.

I ask you this question, because I'm writing an italian translation/adaptation for newbies of your documentation. If I'll finish it, I'll send to you.

**Comment by maieul** [comment]
the difference is very clear. 

\AtEveryPstart is to insert something before every pstart. For example it could be 

````
\AtEveryPstart{\vskip 2cm}
````

to add vertical space of 2cm. It is particulary useful when using // pages.

optional argument argument is to insert between a specific \pstart.

For example to insert a title 

````
\pstart[\section{title}]
````


the difference is clear in English : every or specific� I can't see how I could explain more (except by making example� but that is done in examples folder)

**Comment by Doc73** [comment]
Yes, but both 4.2.3 and 4.2.4 have, as marginal note,
```tex
\DescribeMacro{\AtEveryPstart}
\DescribeMacro{\AtEveryPend}
```
As I can understand, the marginal note would refer only to the chapter 4.2.4.

**Comment by maieul** [comment]
oh, you are right. corrected. thanks
