### ISSUE TITLE
Labelling footnotes with stanza and line number in reledmac

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#373]
https://tex.stackexchange.com/q/258233/7712

**Comment by maieul** [comment]
here the instruction for  muk.li

a) dowload the branch issue373 https://github.com/maieul/ledmac/archive/issue373.zip
b) run .ins file in order to obtain .sty file
c) put them along you .tex file.

This branch had three features:

1) \numberstanzatrue to add stanza number in margin. You can use \setcounter{stanza} to change it.
2) \Xstanza to add stanza number in note
3) \Xstanzaseparator{<sep>} to change the separator between stanza number and line number in note.

See the file issue373.tex in the zip. Also read the § in the handbook 

a) https://github.com/maieul/ledmac/blob/74379760e5d05d917e44ebcb96f080d2d5c20b5d/reledmac.dtx#L2185
b) https://github.com/maieul/ledmac/blob/74379760e5d05d917e44ebcb96f080d2d5c20b5d/reledmac.dtx#L1625

Please make reports and question in this page (you have to create a free account)

**Comment by ppasedach** [comment]
Thanks for this! To start, as you asked me to read the handbook, I am trying to build the documentation, `xelatex reledmac.dtx` but after page 12 it stops,

[12] Section 1 (./reledmac.1)
! Undefined control sequence.
<argument> ...etcounter {stanzaL}{\the \c@stanzaL 
                                                  }\noexpand \csuse {vAfootn...
l.1072 % \Afootnote{Jones C, D.}}

. I'll try to understand the new commands directly from your dtx file now and let you know if I get them to work. If you need any more information from me let me know.

**Comment by ppasedach** [comment]
After moving the new reledmac.sty out of the directory I was able to build the documentation.

**Comment by maieul** [comment]
yes, but i won't work. 
I have made test using both reledmac and reledpar, and I forgot some people don't use reledpar.

try the new version just send on github.

Don' try to understand the new command directly via the code in the .dtx. Because some of them use many conceptual level of reledmac ("hooks"). Use the handbook and or the eample issue373.tex

**Comment by ppasedach** [comment]
Looking at your issue373.tex file, the footnote register part is fine once I comment out the \Xstanzaseparator, as I didn't need the dot there. The result I then get was exactly I what I was referring to in my post on tex.stackexchange.com. But then something I forgot to mention in my tex.stackexchange.com post was that I used to not have _any_ automatically printed line numbers in my text, or the margin rather. In my edition, as is convention in most editions of metrical Sanskrit works, the verse number appears where you can also see it in my example, at the end of the verse, enclosed in "||"s. This number I just used to insert manually, and then I used to suppress the printing of the stanza number by changing the definition of \startstanzahook to _not_ \numberit . The footnote label in the apparatus would still be keyed to the number incremented there though.

Now I've seen that I can turn off the numbering by commenting out \numberstanzatrue but that seems to be turning off any processing of \stanza, not what I want, so I uncommented it again. I tried to do \renewcommand{\thestanza}{}, but that was only slightly better, as although I guess in that case the counter stanzanum is incremented, as the line numbers are reset at the next \stanza, the footnote label doesn't contain stanzanum anymore either. So it would be nice to be able to turn off the printing of stanza numbers  in the margin of the text but keep them in the footnotes.

The same is true for the line numbers, I don't print them in the margin, only in the footnote label. For this though my old solution of setting \firstlinenum{5} would still work, as long as your verses are always four lines only you'll never reach the fifth line. I now realise that I was lucky never needing to edit a verse of for example six lines, which do exist.

**Comment by maieul** [comment]
Hi, I comment "under the lines"

> Looking at your issue373.tex file, the footnote register part is fine once I comment out the \Xstanzaseparator, as I didn't need the dot there. The result I then get was exactly I what I was referring to in my post on tex.stackexchange.com.
perfect !

> But then something I forgot to mention in my tex.stackexchange.com post was that I used to not have any automatically printed line numbers in my text, or the margin rather. In my edition, as is convention in most editions of metrical Sanskrit works, the verse number appears where you can also see it in my example, at the end of the verse, enclosed in "||"s.
strange, but why not. However, you could open an new issue to create a way to insert it at the end of line of verse (I don't know when I could look for this, but it could be fun)

> This number I just used to insert manually, and then I used to suppress the printing of the stanza number by changing the definition of \startstanzahook to not \numberit .
I don't understand this sentence.

> The footnote label in the apparatus would still be keyed to the number incremented there though.
Still don't understanding (English is not my native language)
> 
> Now I've seen that I can turn off the numbering by commenting out \numberstanzatrue but that seems to be turning off any processing of \stanza, not what I want, so I uncommented it again.
yes, as explained in the handbook, \Xstanza works only if you use \numberstanzatrue

> I tried to do \renewcommand{\thestanza}{}, but that was only slightly better, as although I guess in that case the counter stanzanum is incremented, as the line numbers are reset at the next \stanza, the footnote label doesn't contain stanzanum anymore either.
yes, because \thestanza is called in footnote

> So it would be nice to be able to turn off the printing of stanza numbers in the margin of the text but keep them in the footnotes.

I have thought to that. You can redefine \stanzanumwrapper (it is documented).

For example
\renewcommand{\stanzanumwrapper}[1]{}
> 
> The same is true for the line numbers, I don't print them in the margin, only in the footnote label. For this though my old solution of setting \firstlinenum{5} would still work, as long as your verses are always four lines only you'll never reach the fifth line. I now realise that I was lucky never needing to edit a verse of for example six lines, which do exist.
> 

in this case, you could do \firstlinenum{2599}, or better, use \numberlinefalse.

**Comment by ppasedach** [comment]
\stanzanumwrapper was the last missing piece, thanks! My small example looks good now, next I'll try to convert a real file wit several registers and commentary to reledmac and let you know.

**Comment by maieul** [comment]
althought you have overriden the way ledmac insert notes, it should be easy.

I will delete the branch issue373. You will find the code in branch 2.1.0-2.2.0, which I hope to publish next week.
