### ISSUE TITLE
\goalfraction \maxhXnotes et \onlyXside

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#375]
Cher ami,
avec cette routine
%--------------------------------------------------
\usepackage[series={A,B,C,D,E,F,G,H,I,J},noend,noeledsec,noledgroup,noreledmac]{eledmac}
\usepackage{eledpar}
\renewcommand*{\goalfraction}{0.999}
%\renewcommand*{\goalfraction}{1.5}
\maxhXnotes{0.25\textheight}
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A}) }
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\textbf{\theBtest\ - B}) }
\newcounter{Ctest}
\def\Ctest{\stepcounter{Ctest}(\textbf{\theCtest\ - C}) }
\onlyXside[B]{L}
%--------------------------------------------------
......
\begin{document}
.....
\end{document}

la compilation marche bien. Mais si je ecrive

\usepackage[series={A,B,C,D,E,F,G,H,I,J},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}

le systeme reponde ! LaTeX Error: \goalfraction undefined.                   ET 
Undefined control sequence.
l.43 \maxhXnotes
                {0.25\textheight}                                                                      ET 
! Undefined control sequence.
l.204   \onlyXside
                 [B]{L} ........ etc. etc. etc.

Salutations, Enrico Macchia

**Comment by maieul** [comment]
merci de lire le fichier qui explique comment migrer de eledmac à reledmac. un certains nombre de commandes ont changé de non. tout est expliqué dedans. http://mirrors.rit.edu/CTAN/macros/latex/contrib/reledmac/migration.pdf

vous trouverez aisément les noms des nouvelles commandes.

**Comment by heinrichffleck** [comment]
Merci et salutations, Enrico M.
