### ISSUE TITLE
Strange horizontal spacing with \Xbhooknote 

### ISSUE THREAD

**Issue by ppasedach** [maieul/ledmac#377]
In the following example I am adding a \Xbhooknote for my second register of footnotes, which I use for recording textual variants in the commentary to the verse, thus the prefix. I have noticed that adding the \Xbhooknote leads to weird spacing in its footnote register. 

```
\documentclass{memoir}
\usepackage{reledmac}
\setstanzaindents{4,1,2,1,2,3,3,1,2,1}
\numberstanzatrue
\Xbhooknote[B]{\footnotesize Comm.}
\Xstanzaseparator[B]{.}
\Xstanza
\Xarrangement[A]{paragraph}
\Xarrangement[B]{paragraph}
\begin{document}
\beginnumbering
\linenumberstyle{alph}
\stanza
This is my first verse line&
\edtext{My second}{\Afootnote{A; Second B.}} line &
third line &
fourth line \&
\endnumbering
\vspace{\baselineskip}
\beginnumbering
\linenumberstyle{arabic}
\setcounter{linenumincrement}{5}
\pstart
\textbf{Commentary A:} This is a bit of \edtext{commentary}{\Bfootnote{em.; commmmentary MS.}}. And then another \edtext{test}{\Bfootnote{A; useful test B.}}
\pend
\endnumbering
\end{document}
```
![auswahl_025](https://cloud.githubusercontent.com/assets/11517856/9073717/a25d8b90-3b03-11e5-9b77-4d03062f6311.png)

A related question: Is there any possibility of having the \Xbhooknote (or something similar) displayed only before the first footnote of its register on a page?

**Comment by maieul** [comment]
branch issue377 should solve first problem. For the second one, you should use \Xtxtbeforenotes instead of \Xbooknote.

**Comment by maieul** [comment]
hi, some feedback?

**Comment by ppasedach** [comment]
Sorry for the late response, I didn't get to testing this until now. It works for paragraphed footnotes, but if you comment out the \Xarrangement[B]{paragraph} you get the same problem again, an indentation at the beginning of the line.

**Comment by maieul** [comment]
hum,

historically, Xbhooknote is for adding code at the begining of a note, not for adding text. So using it for adding text is a mesuse, which provokes this indent. 
I have corrected it, but as I said, this use of Xbhooknote is not "orthodox" (because who would like to insert the same text at each note??)�

I would also let know you that you can simplify

````
\Xarrangement[A]{paragraph}
\Xarrangement[B]{paragraph}
````

by 

````
\Xarrangement[A,B]{paragraph}
````


or simpler

````
\Xarrangement{paragraph}
````

**Comment by maieul** [comment]
ok, my test are ok with your example. I close it.
