### ISSUE TITLE
Insert figure in \pstart \pend

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#378]
Cher ami,

Si je insére une image dans cette séquence de reledmac-reledpar

declarations etc
..................................................................... 
\usepackage[series={A,B,C,D,E},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}
\renewcommand*{\setgoalfraction}{0.9}
\renewcommand*{\setgoalfraction}{1.5}
\Xmaxhnotes{0.25\textheight}
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A}) }
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\textbf{\theBtest\ - B}) }
\newcounter{Ctest}
\def\Ctest{\stepcounter{Ctest}(\textbf{\theCtest\ - C}) }
\Xonlyside[B]{L}
\Xonlyside[C]{R}
\begin{document}
......................... etc
\pend
\pstart\relax
Un paragraph de 4 lignes (derniere ligne = 104!!!)
\includegraphics[width=0.999\linewidth]{image}
Un autre paragraphe
\pend
........... etc
\end{document}

après (par exemple) le texte qui a la numeration de ligne 104, à côté de l'image j'ai la numérotation 105 que je ne peux pas supprimer ni avec \ballast{..} ni avec \pausenumbering et puis \resumenumbering. Y at-il peut-etre une solution pour ne pas compter l'image comme si elle était une ligne de texte?

Salutations, Enrico M.

**Comment by maieul** [comment]
utiliser l'argument optionel de pstart / pend
