### ISSUE TITLE
Possible typo, reledmac.dtx, line 5811

### ISSUE THREAD

**Issue by dariok** [maieul/ledmac#381]
Maieul,
investigating a different issue, I came across what is most likely just a typo:

Line 5811 reads

    {\write\linenum@out{\string\n@l[\the\c@page][\thepage]}}%

As `\n@l` is undefined, I assume that this should be `\@nl` as the other calls:

    {\write\linenum@out{\string\@nl[\the\c@page][\thepage]}}%

Regards,
Dario

**Comment by maieul** [comment]
you are right. it is corrected for the next release

**Comment by maieul** [comment]
thansk.

**Comment by dariok** [comment]
Glad I could help.
