### ISSUE TITLE
Headlines and sidenotes

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#384]
When using a numbered headline (like eledchapter), sidenotes are not a problem. When using an unnumbered one (\chapter), it is not working.

I don't know if that's technically possible at all, what do you think?

Here's an example of what I mean (commented out):
```
\listfiles

\documentclass{report}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{reledmac}
\usepackage{blindtext}

\begin{document}
\beginnumbering
\pstart
\eledchapter*{This\ledsidenote{HL 1} is a headline with note}
\pend

\pstart%[\chapter*{This\ledsidenote{HL 1} is a headline with note}]
\blindtext
\pend
\endnumbering
\end{document}
```

**Comment by maieul** [comment]
hum, maybe with classical notes

**Comment by maieul** [comment]
as text inserted by optional argument are NOT splitted by reledmac, it should work

**Comment by maieul** [comment]
I confirm. \pstart[\chapter*{This\marginpar{HL 1} is a headline with note}] is working. I close this issue.
