### ISSUE TITLE
problem with \edindex commands?

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#385]
The first version of the MWE runs perfectly and generates the indices. 

In the second version the edindex commands are still existing, but I renounce to generate the indices. In this case the arguments of the edindex commands are placed in the main text of the pdf output. 

I can prevent this behaviour, when I create the indices with \makeindex, but do not print them. 

I am using v2.1.0

Please note, that this is not a pressing problem! 

First version: 

\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[xindy,splitindex]{indextools}
\usepackage[xindy,xindy+hyperref]{reledmac}
\makeindex[name=pers,title=Index personarum]
\makeindex[name=verb,title=Index verborum]
\usepackage[hyperindex=false]{hyperref}

\begin{document}
\beginnumbering
\pstart
Terentius\edindex[pers]{Terentius}: Quot homines, tot sententiae\edindex[verb]{sententia}.
\pend
\endnumbering

\printindex[pers]
\printindex[verb]
\end{document}

Second version: 

\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{reledmac}

\begin{document}
\beginnumbering
\pstart
Terentius\edindex[pers]{Terentius}: Quot homines, tot sententiae\edindex[verb]{sententia}.
\pend
\endnumbering
\end{document}

**Comment by maieul** [comment]
I don't see what I should do. Disable \edindex if you don't use imakeidx? people who use it know that.

For you, do 
````
\renewcommand\edindex[2][1]{}
````

**Comment by sonator** [comment]
I think my request has been misinterpreted. But, there is no need to pursue the matter further. 
Thank you for the solution.
