### ISSUE TITLE
line numbering by pstart in edtabular environment

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#386]
The line numbering by pstart causes in edtabular environments an empty line between the first and second row of the tabular. Please have a look on the MWE. Thank you.

\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage{reledmac}%v2.1.0

\lineation{pstart}
\firstlinenum{0}
\linenumincrement{1}

\begin{document}

\beginnumbering
\pstart
\begin{edtabularl}
linea prima \\
linea secunda \\
linea tertia 
\end{edtabularl}
\pend
\endnumbering

\end{document}

**Comment by maieul** [comment]
please try branch issue386

**Comment by sonator** [comment]
My tables are looking good again. Thank you for the quick correction!

**Comment by maieul** [comment]
I will publish it in ctan right now.
