### ISSUE TITLE
eledmac/eledpar and indextools

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#387]
Dear Maieul hi,

I am sorry to bother you again, but it seems your help is needed once more.

A few words about my critical edition (at the end of this not you can find the relevant sample): it is a greek text along with a parallel english translation. The text consists of:
1. section-titles which SHOULD NOT bear any enumeration
2. various smaller chunks of text (paragraphs) following them which SHOULD be enumerated.

The enumeration of the smaller chunks/paragraphs SHOULD NOT BE influenced by the intervening Titles. For instance,
Unnumbered title 1
numbered paragraph 1
numbered paragraph 2

Unnumbered title 2
numbered paragraph 3
.......

Now, I have tried to use the indextools package in order to provide and index with the greek terms. The references of the Index should have the following form:

"item", paragraph number.line number
or
ἄνθρωπος, 1.2

Note that the the paragraph number must refer ONLY to numbered paragraphs, NOT to unnumbered section-titles (stricktly speaking, unnumbered titles are also paragraphs, but they should not count as such in the index)

I have tried to use indextools but I keep receiving the error message "!Missing number, treated as zero."

Here follows my sample. Thank you in advance.

\documentclass[12pt,a4paper]{book}
\usepackage[english,polutonikogreek]{babel}
\usepackage[iso-8859-7]{inputenc}
\usepackage[makeindex]{indextools}
\usepackage[noreledmac]{eledmac}
\usepackage{eledpar}
\usepackage{lipsum}

\lineation*{pstart}
\sidenotemargin{inner}
\footparagraph{A}
\numberonlyfirstinline

\makeindex[title=\tl{Index},columns=2]{}

\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
Περ`ι <ερμηνείας 1
\pend
\numberpstarttrue
\pstart
<Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε \edindex[>άνθρωπος]{>άνθρωπος} και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος. <Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\pstart
<Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα \edindex[λόγος]{λόγος} τ~ης ο>υσίας <έτερος. <Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\numberpstartfalse
\pstart
Περι <ερμηνείας 2
\pend
\numberpstarttrue
\pstart
<Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος. \edindex[<ομώνυμα]{<Ομώνυμα} λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\selectlanguage{english}
\beginnumbering
\pstart
Title of the 1st section
\pend
\numberpstarttrue
\pstart
\lipsum[11]
\pend
\pstart
\lipsum[11]
\pend
\numberpstartfalse
\pstart
Title of the 2nd section
\pend
\numberpstarttrue
\pstart
\lipsum[11]
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages

\printindex
\end{document}

**Comment by maieul** [comment]
please next time provides A REAL MWE. In this case, // typesetting does not matter.


The optional argument [<ομώνυμα] and similar has no sens. It should be the index name...

to have the pstart and the page number, do 
````
\renewcommand{\thepageline}{%
  \thepstartL%
  \pagelinesep%
  \xlineref{\edindexlab\thelabidx}%
}
````

But there is still a problem with inputenc. Why should you not use xelatex? it is easier (however, I will look for it in future)

**Comment by NiAgio** [comment]
Thank you very much!

"The optional argument [<ομώνυμα] and similar has no sens." It has sense, because:
1. The word in \edindex{ } does not get printed, if I do not use the form \edindex[]{} -- see paragraph 3 in the MWE.
2. \edindex{<ομώνυμα} and \edindex{<Ομώνυμα} provide separate items -- see the Index in the MWE.

The command line for the pstart/page number does not work... the Index simply does not get printed.

There is also an additional problem with the alphabetical order: i.e. greek <ο for ὁ, <Ο for Ὁ, >ο for ὀ,  >Ο for Ὀ ο etc. are identified as different symbols...

"Why should you not use xelatex?" -- I do not know what it is and - most importantly - I do not have the time to learn what it is :)

Perhaps I should make the Index manually...

Anyhow a new MWE follows.

**Comment by NiAgio** [comment]
\documentclass[12pt,a4paper]{book}
\usepackage[english,polutonikogreek]{babel}
\usepackage[iso-8859-7]{inputenc}
\usepackage[makeindex]{indextools}
\usepackage[noreledmac]{eledmac}
\usepackage{eledpar}
\usepackage{lipsum}

\lineation*{pstart}


\sidenotemargin{inner}

\footparagraph{A}

\numberonlyfirstinline

\makeindex[title=\textlatin{Index},columns=2]{}

\renewcommand{\thepageline}{%
 \thepstartL%
  \pagelinesep%
  \xlineref{\edindexlab\thelabidx}%
}


\begin{document}


\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
Περ`ι <ερμηνείας 1
\pend
\numberpstarttrue
\pstart
<Ομώνυμα  λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε \edindex{>άνθρωπος} και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος. 
\pend
\pstart
<Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα \edindex{λόγος} τ~ης ο>υσίας <έτερος. 
\pend
\numberpstartfalse
\pstart
Περι <ερμηνείας 2
\pend
\numberpstarttrue
\pstart
 \edindex{<Ομώνυμα} \edindex{<ομώνυμα} λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\selectlanguage{english}
\beginnumbering
\pstart
Title of the 1st section
\pend
\numberpstarttrue
\pstart
\lipsum[11]
\pend
\pstart
\lipsum[11]
\pend
\numberpstartfalse
\pstart
Title of the 2nd section
\pend
\numberpstarttrue
\pstart
\lipsum[11]
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages

\printindex
\end{document}

**Comment by maieul** [comment]
Hum, you didn't understand the way \edindex work. It works exactly as \index work.

So
1. In never case it prints its mandatory argument. Or if it does it, it is a bug. So if you want it does it, create your own command 
````
\newcommand\myindex[1]{%
#1\edindex{#1}
````
2. The optional argument is to choice in which index you write (for example index for geographical name, index for personnal name)
3. The index is written in a .idx file.
4. Makeindex read this .idx to write a .ind file where file are ordered by alphabetical order.

So you problem of alphabetical order is linked to makeindex and not to reledmac. The problem is that makeindex is conceipted ONLY for English latin caracter. So you have two options:
- or migrate to xindy which works with other carachter (see for example http://geekographie.maieul.net/169)
- or use the syntax with @ (see https://en.wikibooks.org/wiki/LaTeX/Indexing#Sophisticated_indexing)

For xelatex, do you think I have time also time to maintain eledmac for old school system? Xelatex is native unicode and many problem with no english latin characters. So ALSO for you, migrate to xelatex will simplifiy many things. https://en.wikipedia.org/wiki/XeTeX

**Comment by NiAgio** [comment]
Ok, thanks!

**Comment by NiAgio** [comment]
The syntax with @ does the trick absolutely fine. Let me know, if you have any ideas on making paragraph number-line number work. The

\renewcommand{\thepageline}{%
  \thepstartL%
  \pagelinesep%
  \xlineref{\edindexlab\thelabidx}%
}

does not seem to work.

**Comment by maieul** [comment]
use 

`````
\renewcommand{\thepageline}{%
\the\value{pstartL}%
\pagelinesep%
\xlineref{\edindexlab\thelabidx}%
}
````
(but I really think you should read some tutoriel about the way an index is constructed, to understand well)

**Comment by maieul** [comment]
the branch issue387 should solve problem with non latin character without xelatex. please try it and send feedback.

**Comment by NiAgio** [comment]
Works perfectly! Thanks a lot!

**Comment by maieul** [comment]
ok. i will publish it on ctan next week.
-----
Ma�eul
http://blog.maieul.net
http://www.schtroumpfs.maieul.net/

Le 27 ao�t 2015 � 23:34, NiAgio <notifications@github.com> a �crit :
