### ISSUE TITLE
Inconsistent behavior regarding par indent

### ISSUE THREAD

**Issue by tweh** [maieul/ledmac#392]
Hi Maïeul,

I just noticed that the behavior of par indention is quite inconsistent between the different arrangements and does sometimes not what is said in the manual … I made a small (quickly handwritten) table to show the differences:

![indention in footnotes](https://cloud.githubusercontent.com/assets/3011538/9519340/21ed897a-4cbe-11e5-8920-8392a001d8d7.JPG)

- The lines represent text lines of the paragraphs in a footnote. **red** is the current result and **green** shows how it should be to be consistent and according to the manual.
- The circles mark the differences.
- A checkmark means “ok” as is.

This is my test document:

```latex
\documentclass{article}

\usepackage{reledmac}

%\Xarrangement{twocol}
%\arrangementX{twocol}

%\Xarrangement{threecol}
%\arrangementX{threecol}

\Xparindent
\parindentX

\usepackage{lipsum}

\begin{document}
Test\footnoteA{\lipsum[2-4]}
\beginnumbering
   \pstart \edtext{test}{\Afootnote{\lipsum[2-4]}} \pend
\endnumbering
\end{document}
```

I’d implement a fix to this but before I start I want to discuss what the result should then look like, so here are some questions:

1. Is my understanding of how the result should be (green lines) right?
2. A regular `\footnote{Text}` not typset via `reledmac` has no indention in the first paragraph but for all followings. Theres a little gap in front of the first paragraph because the number is right aligned in a box with a fixed width. Should `reledmac` behave as the standard footnotes? That would have two consequences
  - the first paragraph will never be indented independent of the `\Xparindent`/`\parindentX` setting
  - the number of familiar footnotes must be set in a box to get the same layout as standard footnotes.
While only the first point is relevant for this issue.
3. I noticed that you use `\…ledsetnormalparstuff…` macros to set the indention but only for the `normal` arrangement. Shouldn't this concept be extended to be used for the `…col` layouts too and also include the settings for a hang indention?

----

PS: Just to make it clear: I’ll try to implement this as far as I can, so you have no work with this issue except answering my questions ;-)

**Comment by maieul** [comment]
Yes, I know it is inconsistent. But the main problem is "in which part we accept to break compatibilty" ?.

However, 
1) you're exemple is right. I don't know why, but reledmac has broken feature \Xparindent
2) no, that is depending of language. For french for example, there is. I think we should let reledmac as it, in order to not break past.
3) maybe, it should.

Le 27 ao�t 2015 � 13:32, Tobias Weh <notifications@github.com> a �crit :

**Comment by tweh** [comment]
> Yes, I know it is inconsistent. But the main problem is "in which part we accept to break compatibilty" ?.
Yep, thats why I wanted to talk about it first.

Maybe we introduce a new option `oldparindentsettings` to leave everything as is but implement a more consistent default behavior.

> 1) you're exemple is right. I don't know why, but reledmac has broken feature \Xparindent
I know :-) … I think: In line 3575 (p. 181) you used `\noindent` instead of setting the par indent 

I just start to implement something an then make a pull so you can decide wether to use it or not …

**Comment by maieul** [comment]
please do it in two step
1) one branch only restart the normal behavior of \Xparindent / \parindentX
2) a other for the point two. I am not sur it is a so good idea. 

Le 27 ao�t 2015 � 14:22, Tobias Weh <notifications@github.com> a �crit :

**Comment by tweh** [comment]
ok … how is “normal behavior” defined?

**Comment by maieul** [comment]
normal behavior = using \Xparindent change the indent.

**Comment by tweh** [comment]
yea, thats clear but I’m not sure what exactly `\Xparindent` (and `\parindentX`) should trigger (according to my table). I.e. which of the cells in the table should be fixed in this step?

**Comment by maieul** [comment]
your green line are ok.

**Comment by tweh** [comment]
Then I implement it like this

`\(X)parindent(X)`  on  —>  **all** lines indented  
`\(X)parindent(X)`  off  —>  **no** line indented

and I’m going to define a new macro making all indent (par- and hang-) settings in all format macros.

OK?

**Comment by maieul** [comment]
Le 27 ao�t 2015 � 14:41, Tobias Weh <notifications@github.com> a �crit :

> Then I implement it like this
> 
> \(X)parindent(X) on �> all lines indented
> 
> \(X)parindent(X) off �> no line indented
> 
> and I�m going to define a new macro making all indent (par- and hang-) settings in all format macros.
> 
> OK?

ok, but 
1) be careful for paragraphed notes, in many case it does not works as expected (it is particular complex). 
2)  \�ledsetnormalparstuff� do more. look attentivly to it.

**Comment by tweh** [comment]
jep ok :-)

**Comment by tweh** [comment]
Actually the paragraphed footnotes seem to be broken in the current release. See #393 maybe you can take a look at this bevor I start playing around with the new implementation for the indentions …

**Comment by maieul** [comment]
hi, some feedback?

**Comment by tweh** [comment]
Hi … no not yet I got other things to do first but I’ll take a look at this in the next week …

**Comment by maieul** [comment]
ok. Is the possible to do it in the begining of the week? I would like to release before going to a new holiday.

**Comment by tweh** [comment]
Jep, I'll try :-)

—

Tobi W_


Tobias Weh
Spindelstraße 25
49080 Osnabrück

+49 (0)541 40757837

mail@tobiw.de
http://tobiw.de

**Comment by maieul** [comment]
your commit don't fix anything... \parindent on is style not working...

**Comment by maieul** [comment]
please try branch issue392 for two and three columns.

**Comment by tweh** [comment]
hi,

I�ll take a look at it tomorrow in the morning �
�

Tobi W_


Tobias Weh
Spindelstra�e 25
49080 Osnabr�ck

+49 (0)541 40757837

mail@tobiw.de
http://tobiw.de

**Comment by tweh** [comment]
Good morning :-)

The branch issue392 shows the correct behavior for `normal`, `twocol` and `threecol` arrangement, but has a side effect on `paragraph`: When the indent is activated it adds some extra space before the start of each note.

Did you change something for the `normal` notes? Because they work two. And my commit changed the former behavior to the desired one in my tests …

This is my test document (for reference):

```latex
\documentclass{article}

\usepackage[parapparatus]{reledmac}

\Xarrangement[A]{twocol}
\arrangementX[A]{twocol}

\Xarrangement[B]{threecol}
\arrangementX[B]{threecol}

\Xarrangement[C]{normal}
\arrangementX[C]{normal}

\Xarrangement[D]{paragraph}
\arrangementX[D]{paragraph}

\Xparindent
\parindentX

\newcommand{\sometext}{%
   Nam dui ligula, fringilla a, euismod sodales, sollicitudin vel, wisi. Morbi
   auctor lorem non justo. Nam lacus libero, pretium at, lobortis vitae, ultricies
   et, tellus.
}

\begin{document}
Test\footnoteA{\textbf{Normal A}: \sometext\par \sometext} \footnoteA{\textbf{Normal A}: \sometext}
Test\footnoteB{\textbf{Normal B}: \sometext\par \sometext} \footnoteB{\textbf{Normal B}: \sometext}
Test\footnoteC{\textbf{Normal C}: \sometext\par \sometext} \footnoteC{\textbf{Normal C}: \sometext}
Test\footnoteD{\textbf{Normal D}: \sometext\sometext} \footnoteD{\textbf{Normal D}: \sometext}

\clearpage
\beginnumbering
   \pstart
   \edtext{test}{\Afootnote{\textbf{Critical A}: \sometext\par \sometext}}
   \edtext{test}{\Afootnote{\textbf{Critical A}: \sometext}}
   \edtext{test}{\Bfootnote{\textbf{Critical B}: \sometext\par \sometext}}
   \edtext{test}{\Bfootnote{\textbf{Critical B}: \sometext}}
   \edtext{test}{\Cfootnote{\textbf{Critical C}: \sometext\par \sometext}}
   \edtext{test}{\Cfootnote{\textbf{Critical C}: \sometext}}
   \edtext{test}{\Dfootnote{\textbf{Critical D}: \sometext \sometext}}
   \edtext{test}{\Dfootnote{\textbf{Critical D}: \sometext \par \sometext}}
   \pend
\endnumbering
\end{document}
```

**Comment by maieul** [comment]
I don't understand your second paragraph. Your commit was not working for normal notes.

**Comment by maieul** [comment]
the new version of the branch should solve this problem with paragraphed notes (ps : there is still a problem with too much space before footnote rule in paragraphed notes, I try to solve it)

**Comment by tweh** [comment]
Yep seems to work but did you notice that the `normal` arragngment note are no longer notes …?

![bildschirmfoto 2015-09-02 um 14 18 32](https://cloud.githubusercontent.com/assets/3011538/9630901/8560596a-517d-11e5-8a93-8fe3adf83146.png)

**Comment by maieul** [comment]
I don't know which code your test, but for me, with the last issue392 (e. g. 9e2cec5), it's working nice.

![image](https://cloud.githubusercontent.com/assets/636640/9631959/96654ac0-5184-11e5-9074-c129f143123b.png)
![issue392-2](https://cloud.githubusercontent.com/assets/636640/9631972/a379bf84-5184-11e5-9bd0-a9acace4f724.jpg)

**Comment by tweh** [comment]
Ok … now ist works correct on my system too. Maybe there was a sync error or I forgot to generate a new `sty` file O:-)
