### ISSUE TITLE
Arrangement 'paragraph' doen’t work

### ISSUE THREAD

**Issue by tweh** [maieul/ledmac#393]
Seems like the `paragraph` arrangement is broken. In the following example there are no footnotes visible, only the two footnote rules …

```latex
\documentclass{article}

\usepackage{reledmac}

\Xarrangement{paragraph}
\arrangementX{paragraph}

\usepackage{lipsum}

\begin{document}
Test\footnoteA{\lipsum[2]}

\beginnumbering
   \pstart \edtext{test}{\Afootnote{\lipsum[2]}} \pend
\endnumbering
\end{document}
```

**Comment by maieul** [comment]
no, the main problem is that footparagraph CAN'T work with long notes, especially with \par inside.

try for example 

\documentclass{article}

\usepackage{reledmac}





\usepackage{lipsum}

\begin{document}
\Xarrangement{paragraph}
\arrangementX{paragraph}
Test\footnoteA{Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor posuere diam, sit amet tristique odio vulputate et. Ut nibh justo, rhoncus venenatis rutrum a, tincidunt nec massa. Sed tristique maximus quam in mollis. Suspendisse eu enim est. In porta vestibulum diam pellentesque imperdiet. Pellentesque in ultrices diam, vitae lacinia nisl. Donec lobortis sagittis justo quis vestibulum. Pellentesque neque dui, euismod vitae metus eu, lacinia tincidunt turpis. Nullam convallis tincidunt tellus, at consequat risus vehicula non. Suspendisse fermentum leo diam, porta vulputate turpis viverra sed.}

\beginnumbering
   \pstart \edtext{test}{\Afootnote{Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor posuere diam, sit amet tristique odio vulputate et. Ut nibh justo, rhoncus venenatis rutrum a, tincidunt nec massa. Sed tristique maximus quam in mollis. Suspendisse eu enim est. In porta vestibulum diam pellentesque imperdiet. Pellentesque in ultrices diam, vitae lacinia nisl. Donec lobortis sagittis justo quis vestibulum. Pellentesque neque dui, euismod vitae metus eu, lacinia tincidunt turpis. Nullam convallis tincidunt tellus, at consequat risus vehicula non. Suspendisse fermentum leo diam, porta vulputate turpis viverra sed.}} \pend
\endnumbering
\end{document}
-----
Ma�eul
http://blog.maieul.net
http://www.schtroumpfs.maieul.net/

Le 27 ao�t 2015 � 15:02, Tobias Weh <notifications@github.com> a �crit :

**Comment by tweh** [comment]
Ah … my bad … I forgot that `\lipsum` includes a `\par` even if there’s only one paragraph to typeset.
