### ISSUE TITLE
issue239 does not work any more

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#394]
Everything was fine until some days ago...

\documentclass[12pt,a4paper]{book}
\usepackage[english,polutonikogreek]{babel}
\usepackage[iso-8859-7]{inputenc}
\usepackage{eledmac}
\usepackage{eledpar}

\lineation{pstart}

\footparagraph{A}
\footparagraph{B}
\footparagraph{C}

\numberonlyfirstinline[A]
\numberonlyfirstinline[B]
\numberonlyfirstinline[C]

\begin{document}

\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
Περι \edtext{<ερμηνείας}{\Afootnote{\textlatin{this variant should be printed with NO paragraph number 1}}}
\pend
%\setcounter{pstartL}{1}
\numberpstarttrue
\pstartinfootnote[B]
\pstart
<Ομώνυμα λέγεται <~ων \edtext{>όνομα}{\Afootnote{\textlatin{this variant should be printed under paragraph number 1, not 2}}} μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος. <Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\pstart
<Ομώνυμα λέγεται <~ων \edtext{>όνομα}{\Afootnote{\textlatin{this variant should be printed under paragraph number 2, not 3}}} μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος. <Ομώνυμα λέγεται <~ων >όνομα μόνον κοινόν, <ο δε κατα το>ύνομα λόγος τ~ης ο>υσίας <έτερος, ο<~ιον ζ~ω|ον <ό τε >άνθρωπος και το γεγραμμένον; τούτων γαρ >όνομα μόνον κοινόν, <ο δε κατ`α το>ύνομα λόγος τ~ης ο>υσίας <έτερος.
\pend
\numberpstartfalse
\endnumbering
\end{Leftside}

\begin{Rightside}
\selectlanguage{english}
\beginnumbering
\pstart
English Title
\pend
\setcounter{pstartR}{1}
\numberpstarttrue
\pstart
This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. 
\pend
\pstart
This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. This is just a test sample. 
\pend
\numberpstartfalse
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}

**Comment by maieul** [comment]
sorry, but what does not work?  eledmac is not maintened any more, so I can't see why something modify "some days ago" could not work anymore.

**Comment by NiAgio** [comment]
![error](https://cloud.githubusercontent.com/assets/10960975/9521861/8d57edaa-4cd1-11e5-86c9-a3cbcb4d70b4.png)

**Comment by maieul** [comment]
just update your package with your package manager...

Le 27 ao�t 2015 � 15:37, NiAgio <notifications@github.com> a �crit :

**Comment by NiAgio** [comment]
Did that a couple of hours ago... still keep getting the same error message.

**Comment by maieul** [comment]
hum, which version of eledmac do you have in your computer ? which tex distribution do you use? which version of etoolbox do you have ?

**Comment by NiAgio** [comment]
packaged on 21.07.2015, Miktex. What is the etoolbox?

**Comment by NiAgio** [comment]
I mean eledmac version was packaged on 21.07

**Comment by maieul** [comment]
I asked for version number, not date number. etoolbox is a package which eledmac use.

Le 27 ao�t 2015 � 15:51, NiAgio <notifications@github.com> a �crit :

**Comment by NiAgio** [comment]
eledmac version 1.24.6, etoolbox version 2.2a

**Comment by maieul** [comment]
hum, very strange. it should works. try to insert \usepackage{etex} before loading eledmac.
Le 27 ao�t 2015 � 15:54, NiAgio <notifications@github.com> a �crit :

**Comment by NiAgio** [comment]
nope... still does not work...

**Comment by maieul** [comment]
hum, there should have an other problem. do you send the full error message ? i don't thinkg it will solve issue, but if you want to continue to use eledmac (which is not maintened any more), YOU MUST use the noreledmac option.

Le 27 ao�t 2015 � 15:56, NiAgio <notifications@github.com> a �crit :

**Comment by NiAgio** [comment]
Have tried that too... no luck. Anyway, I shall unistall and then install again the whole miktex texmaker thing and then see how it goes.

**Comment by NiAgio** [comment]
I know that eledmac is not maintained any more, but I am working on a project which has been written with eledmac and at this stage of my work (which is rather pressing) I would not like to move on with reledmac.

**Comment by maieul** [comment]
I thinks. I am afraid you have corruption in your installation. I can't explain otherwise that you have this problem (if you have really send all the message) which has been corrected.

however, a short way could be to insert 
\def\reserveinserts#{}

before loading eledmac. In many case it should not cause trouble, except if you use many package.
-----
Ma�eul
http://blog.maieul.net
http://www.schtroumpfs.maieul.net/

Le 27 ao�t 2015 � 16:09, NiAgio <notifications@github.com> a �crit :

**Comment by maieul** [comment]
I can't understand. But not maintening also means not debugging. 





Le 27 ao�t 2015 � 16:13, NiAgio <notifications@github.com> a �crit :

**Comment by NiAgio** [comment]
Until some hours ago there was no need to debug, thus to maintain, anything... The whole thing was  running fine. Let us see how the installation is going to run. I would be happy, however, to use reledmac for future projects.

**Comment by NiAgio** [comment]
Ok, reinstalled the whole thing... everything runs ok except the file "issue239". This is what I get us a message

![unbenanntes bild](https://cloud.githubusercontent.com/assets/10960975/9527814/85863d8c-4cf1-11e5-92a8-9dbe6389599e.png)

I will try to see how can I get around with reledmac tomorrow.

**Comment by maieul** [comment]
hum, could it be possible to have the FULL log ?

Le 27 ao�t 2015 � 19:27, NiAgio <notifications@github.com> a �crit :

**Comment by NiAgio** [comment]
Yes, of course, but I copied/pasted in a word document and it is more than 500 pages... You mean post it here?

**Comment by maieul** [comment]
pastebin it here https://gist.github.com/ and send the link

**Comment by NiAgio** [comment]
<script src="https://gist.github.com/NiAgio/6137787d677ecea55f99.js"></script>

**Comment by NiAgio** [comment]
https://gist.github.com/6137787d677ecea55f99.git

**Comment by NiAgio** [comment]
https://gist.github.com/6137787d677ecea55f99.git

**Comment by NiAgio** [comment]
https://gist.github.com/6137787d677ecea55f99.git

**Comment by NiAgio** [comment]
Does it work?

**Comment by maieul** [comment]
p. https://gist.github.com/NiAgio/6137787d677ecea55f99#file-issue239-revisited-L63
your eledmac package is not up to date. 



Le 27 ao�t 2015 � 20:03, NiAgio <notifications@github.com> a �crit :

**Comment by NiAgio** [comment]
How can this be possible? I have downloaded the whole miktex and updated it half hour ago...

![noway](https://cloud.githubusercontent.com/assets/10960975/9528928/b653c26c-4cf7-11e5-9627-6c915997fe1a.png)

**Comment by maieul** [comment]
https://gist.github.com/NiAgio/6137787d677ecea55f99#file-issue239-revisited-L62

you have an eledmac.sty file juste around your .tex file (cf the path, which is not standard)

**Comment by NiAgio** [comment]
I cannot believe that I lost half day with this shit (sorry for the expression)... I owe you at least a good word in the preface of my book.

The whole thing works again... I feel stupid.

**Comment by NiAgio** [comment]
THANK YOU!

**Comment by maieul** [comment]
thats is classical mistake. So don't forget to read all the log file. And also, when I ask you for test, don't forget to deleted the .sty file after test, when I said you "ok, it is uploaded on CTAN".
-----
Ma�eul Rouquette
www.maieul.net
http://geekographie.maieul.net/

Le 27 ao�t 2015 � 20:17, NiAgio <notifications@github.com> a �crit :
