### ISSUE TITLE
Arabic not displaying

### ISSUE THREAD

**Issue by Tim-at-AST** [maieul/ledmac#395]
# Summary
From the eledpar documentation (two columns, different languages) I have a MWE, using some Hebrew text and Hebrew chapter headings.

But when I changed the Hebrew to Arabic, although the main body of the text displays correctly, the chapter headings do not.

Following are the code samples (first Hebrew, then Arabic), and afterwards the output as PNG files.

# MWE code for the Hebrew, which works.

    \documentclass{book}
	\usepackage[a4paper]{geometry}
	\usepackage{fontspec}
	\setmainfont[Ligatures=TeX]{Linux Libertine O}
	\usepackage{xunicode,metalogo,hyperref}
	\usepackage{polyglossia}

	\usepackage[series={},nocritical,noend,nofamiliar,noledgroup]{reledmac}
	\usepackage{reledpar} 

	\linenumincrement*{1}
	\firstlinenum*{1}
	\setlength{\Lcolwidth}{0.42\textwidth}
	\setlength{\Rcolwidth}{0.42\textwidth} 

	\setmainlanguage{english}
	\setotherlanguage{russian}
	\setotherlanguage{hebrew}    
	\setotherlanguage{arabic}    
	\newfontfamily\arabicfont[Script=Arabic]{Scheherazade}
	\newfontfamily\hebrewfont[Script=Hebrew]{Linux Libertine O}
	\newfontfamily\russianfont[Script=Cyrillic]{Linux Libertine O}    

	\begin{document}
	\begin{pairs}

	\begin{Rightside} 
	\begin{RTL}
	\begin{hebrew}
	\beginnumbering
	\pstart
	\eledchapter{דבר דרב}\ledleftnote{s}
	\pend
	\pstart
	דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב 
	דבר דרב דבר דרב דבר דרב דבר דרב 
	דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב דבר דרב 
	\pend    
	\endnumbering
	\end{hebrew}
	\end{RTL}
	\end{Rightside}

	\begin{Leftside} 
	\begin{russian}
	\beginnumbering
	\pstart
	\eledchapter{Трактат Второй}   
	\pend 
	\pstart
	О краеугольных [принципах] Торы, имеется ввиду, которые [есть] основы и столпы на которых дом Б-жий опирается/нахон, и с существованием их может быть представлено существование Торы упорядоченной от Него, благословенного, и если бы было представлено отсутствие одного из них — упадет Тора в общем, [Б-же] упаси.
	\pend
	\endnumbering
	\end{russian}
	\end{Leftside}

	\end{pairs}
	\Columns
	\end{document}

# Here is the non-working code after I change to Arabic.

	\documentclass{book}
	\usepackage[a4paper]{geometry}
	\usepackage{fontspec}
	\setmainfont[Ligatures=TeX]{Linux Libertine O}
	\usepackage{xunicode,metalogo,hyperref}
	\usepackage{polyglossia}

	\usepackage[series={},nocritical,noend,nofamiliar,noledgroup]{reledmac}
	\usepackage{reledpar} 

	\linenumincrement*{1}
	\firstlinenum*{1}
	\setlength{\Lcolwidth}{0.42\textwidth}
	\setlength{\Rcolwidth}{0.42\textwidth} 

	\setmainlanguage{english}
	\setotherlanguage{russian}
	\setotherlanguage{hebrew}    
	\setotherlanguage{arabic}    
	\newfontfamily\arabicfont[Script=Arabic]{Scheherazade}
	\newfontfamily\hebrewfont[Script=Hebrew]{Linux Libertine O}
	\newfontfamily\russianfont[Script=Cyrillic]{Linux Libertine O}    

	\begin{document}
	\begin{pairs}

	\begin{Rightside} 
	\begin{RTL}
	\begin{Arabic}
	\beginnumbering
	\pstart
	\eledchapter{كلمة}\ledleftnote{s}
	\pend
	\pstart
	كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة 
	كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة 
	كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة كلمة ،كلمة كلمة كلمة كلمة كلمة  كلمة كلمة كلمة كلمة كلمة  
	\pend    
	\endnumbering
	\end{Arabic}
	\end{RTL}
	\end{Rightside}

	\begin{Leftside} 
	\begin{russian}
	\beginnumbering
	\pstart
	\eledchapter{Трактат Второй}   
	\pend 
	\pstart
	О краеугольных [принципах] Торы, имеется ввиду, которые [есть] основы и столпы на которых дом Б-жий опирается/нахон, и с существованием их может быть представлено существование Торы упорядоченной от Него, благословенного, и если бы было представлено отсутствие одного из них — упадет Тора в общем, [Б-же] упаси.
	\pend
	\endnumbering
	\end{russian}
	\end{Leftside}

	\end{pairs}
	\Columns
	\end{document}

# Hebrew output—good.

![mwehebrew](https://cloud.githubusercontent.com/assets/14029707/9562078/a40119d2-4e61-11e5-90f8-fc4f5ce9ac28.png)

# Here is the arabic -bad.

Notice the bad word for 'chapter' and the bad chapter heading.
![mwearabic](https://cloud.githubusercontent.com/assets/14029707/9562068/5cf34a2e-4e61-11e5-84a1-00041b847ee2.png)

**Comment by maieul** [comment]
As you can see in https://github.com/maieul/ledmac/blob/fa0e27a39e63f0d7dbf687884a06647cb606013d/issue395.tex

the problem also happens with classical \chapter. So the problem is not from reledmac, but from your choice of fonts which is not adapted for heading. Maybe @ralessi could help you, but for my part, I don't know. I think you should open a question on stackexchange with this mwe.

**Comment by Tim-at-AST** [comment]
I discovered something new, which makes me think that `reledmac` may the problem.
The MWE you gave above is incorrect: you can make it work  if you change line 10 to  `\setmainlanguage{Arabic}`

Also, from the TEX error log (see below), it seems that the `\MakeUppercase` is the problem.  Is Reled calling this?  Or is this polyglossia?  Arabic does not have uppercase so I wonder if that is the problem.

Does this new information help solve my problem?

My question at TEX Stackexchange has not gotten any comments or answers.  

    ./MWEArabic.tex:62: Undefined control sequence.
    <argument> \MakeUppercase 
                              {\ifnum \c@secnumdepth >\m@ne \if@mainmatter \@cha...
    l.62 \Columns

**Comment by maieul** [comment]
reledmac don't do \MakeUppercase 
-----
Ma�eul Rouquette
www.maieul.net
http://geekographie.maieul.net/

Le 5 sept. 2015 � 20:23, Tim-at-AST <notifications@github.com> a �crit :

**Comment by maieul** [comment]
and you can constate, that, if my MWE is incorrect, is is based in your MWE which is \setotherlanguage{arabic}.... \eledchapter just call the standard \chapter with some modification to insert line number. So the problem is definitivly not in reledmac.
