### ISSUE TITLE
Overflow of \Xafternote space across linebreaks in apparatus

### ISSUE THREAD

**Issue by stenskjaer** [maieul/ledmac#397]
Consider the following MWE:

```latex
\documentclass{article}

\usepackage{reledmac}

\Xarrangement[A]{paragraph}

\begin{document}
\beginnumbering
\pstart
Subiectum igitur huius scientiae est animal, secundum quod in
eo est principium motus ad somnum et uigiliam, et hoc est rationale,
quia ista scientia subalternatur
\edtext{scientiae}{\Afootnote{subiectae \emph{M}}} traditae in libro
Physicorum, et ideo subiectum huius continetur sub subiecto illius.
Somnus multipliciter describitur. Philosophus enim ponit duas
descriptiones somni; una est, quod somnus est impotentia sentiendi
propter excessum uigiliae, alia est, quod somnus est immobilitatio
sensuum \edtext{exteriorum}{\Afootnote{exteriori
        \emph{a. c. M}}}. Alias duas descriptiones ponit Commentator;
una est, quod somnus est sensus in potentia. Dormienti
\edtext{enim}{\Afootnote{\emph{om. L}}} uidetur, quod comedat et potet
et sentiat per omnes \edtext{quinque}{\Afootnote{\emph{s.  l. L,
            om. A}}} sensus, et secundum eum uigilia est sensus in
actu, et quandoque \edtext{contingit}{\Afootnote{conuenit \emph{M}}},
quod sensus in potentia exeat in actum, ut in somniis ueris
praenuntiatiuis mirabilium, et tunc sensus, qui est in potentia, est
nobilior, quam sensus, qui est in actu. Sensus autem in potentia, cum
fuerit falsus, tunc est uilis, et sensus in actu est nobilior eo. Alio
\edtext{modo}{\Afootnote{\emph{om. A}}}
\edtext{describit}{\Afootnote{descripsit \emph{A}}} Commentator somnum
sic: Somnus est \edtext{reuocatio}{\Afootnote{reuolutio \emph{A}}}
\edtext{caloris}{\Afootnote{calorum \emph{A}}} naturalis ad interius
ab \edtext{organis}{\Afootnote{orig(.) \emph{a. c. M}}} corporeis
\edtext{exterius}{\Afootnote{\emph{An} externis \emph{scribendum?}}},
et \edtext{sic}{\Afootnote{tunc \emph{AL}}} patet, quid est somnus.
\pend
\endnumbering
\end{document}
```

Notice how the whitespace between the critical notes spills over across linebreaks in the apparatus (before the note on line 15):
![skaermbillede 2015-08-31 kl 11 43 15](https://cloud.githubusercontent.com/assets/4047523/9576158/8ac2772a-4fd5-11e5-8144-1d6478fae47c.png)

Reledmac version: 2015/08/26 v2.1.2

**Comment by maieul** [comment]
hum, the mwe should not be the right. I does not obtain this.

![image](https://cloud.githubusercontent.com/assets/636640/9588106/a4673e94-5026-11e5-956f-189cbd0cc1e0.png)

**Comment by maieul** [comment]
![reledmac](https://cloud.githubusercontent.com/assets/636640/9588119/bbe048e0-5026-11e5-823f-64d423a71c4f.png)
the good one

**Comment by stenskjaer** [comment]
Well, for some reason, the line breaks differently. You only see the problem when the line in the apparatus is broken exactly between two lemmata, for example before the lemma for ‘exterius’ in line 15 in this case.
This exact MWE produces the first screen cap on my system (TeXLive 2015, Mac OS X 10.10, let me know it you want more details or testing on my end).

**Comment by maieul** [comment]
I suppose you have not the same default paper size as me. Could please send me the value of your \textwidth ?(and also the .log file)

**Comment by stenskjaer** [comment]
I apologize my slow response.
The textwidth is 345pt.
You can see the log file here: http://pastebin.com/WZq7QGyV

Just now I noticed that I don't experience the problem when compiling with xelatex rather than my usual lualatex.

**Comment by maieul** [comment]
ok, I will look this week-end (or try to look)

**Comment by maieul** [comment]
problem comes from commit a9bed0240d54b22ff6309b1786e380040934a1b2

**Comment by stenskjaer** [comment]
Let me know when you need me to test anything.

**Comment by maieul** [comment]
for now, I know where is the problem, but not how I could solve it :-(

**Comment by stenskjaer** [comment]
All right, well at least it only affects compilations with lualatex. Compilations with xelatex are unaffected and look as expected.

**Comment by maieul** [comment]
please try branch issue397 (with lualatex)

**Comment by maieul** [comment]
ok, I don't think we need more test. I close this branch and merge in the branch of release.
