### ISSUE TITLE
Add a line (left) in parallel pages

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#398]
Cher ami, moi je crois  de me souvenir qu'il ya une instruction pour forcer ledpar (dans l'option parallel pages) pour ajouter une ligne (à droite ou à gauche d'une page), mais je ne trouve pas cela dans le deux manuel. Pouvez-vous me rappeler gentiment si elle existe vraiment?

J'essayé avec \LineationL (dans mon cas la page de gauche mais rien. Est-ce-que peux tu m'aider?

salutations Enrico Macchia

**Comment by maieul** [comment]
c'est � dire ajouter une ligne ? un num�ro de ligne? augmenter le nombre de ligne uniquement d'un c�t� ? mettre une note marginale?
-----
Ma�eul
http://blog.maieul.net
http://www.schtroumpfs.maieul.net/

Le 1 sept. 2015 � 08:14, heinrichffleck <notifications@github.com> a �crit :

**Comment by heinrichffleck** [comment]
Cher ami, 
pour  -- ajouter une ligne -- je voulais dire ceci. 

Dans un document avec reledpar (parallel pages) et aussi avec nayurrelement reledmac,  nous prenons le cas que, 
 après la compilation, j'ai 50 lignes sur la page de gauche e 50 lignes sur la page de  droite. 

Mais (pour la page de gauche) le texte (la phrase) n'est pas complète et elle se tourne (termine)  à la page suivante  (toujours  de gauche)   seulement pour trois mots.  
 Je me demande: est-il une méthode pour forcer reledpar (ou reledmac) pour ajouter une ligne sur la page?
Je crois me souvenir de ça, oui, mais je ne peux pas trouver la déclaration correspondante sur votre manual.
Tres merci pour l'aide et salutations, Enrico Macchia

=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Martedì 1 Settembre 2015 10:28
 Oggetto: Re: [ledmac] Add a line (left) in parallel pages (#398)
   
c'est � dire ajouter une ligne ? un num�ro de ligne? augmenter le nombre de ligne uniquement d'un c�t� ? mettre une note marginale?-----
Ma�eul
http://blog.maieul.net
http://www.schtroumpfs.maieul.net/

Le 1 sept. 2015 � 08:14, heinrichffleck <notifications@github.com> a �crit :

**Comment by maieul** [comment]
il faut regarder du c�t� de \lednopb (relire la documentation, pour bien en comprendre les nuances)

**Comment by heinrichffleck** [comment]
Tres merci, c'etait ça l'instruction que je avais oubliè!salutations, Enrico M.
 
=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Martedì 1 Settembre 2015 18:04
 Oggetto: Re: [ledmac] Add a line (left) in parallel pages (#398)
   
Closed #398.—
