### ISSUE TITLE
Using \sublinenumberstyle within reledpar

### ISSUE THREAD

**Issue by apollo77x** [maieul/ledmac#400]
I am making an edition wherein a citation from a verse should be referred to by both the verse's number and the quarter of the verse that it appears in. The number of the verse should be a numeral and the quarter should be referred to by a letter, from 'a' to 'd.' For example, a citation of the second quarter of the third verse should be referred to in the critical apparatus by '3b'. To accomplish this in a standard edition with only one text using `reledmac` one can alphabetize the sub-line numbers and have them function as the component of the citation in the apparatus that refers to the quarter of the verse. 

However, I am making a document in which there are two columns of text using reledpar. Because the `\sublinenumberstyle` feature was not conceived with `reledpar` in mind, the sub-line numbers do not get converted to letters. 

<pre><code>
\documentclass{article}

\usepackage{reledmac}

\usepackage{reledpar}

\begin{document}

\setstanzaindents{0,0,0}

\begin{pairs}

\begin{Leftside} 

\beginnumbering
    \autopar
    
\newcommand{\choiceline}[2]{\linenum{|#1|#2||#1|#2}}
	\sublinenumberstyle{alph}
	\let\fullstop\relax

\noindent Arma virumque cano, Troiae qui \edtext{primus}{\Afootnote{A; primo B}} ab oris Italiam, fato profugus, Laviniaque venit litora, multum ille et terris iactatus et alto vi superum saevae memorem Iunonis ob iram; \edtext{multa}{\Afootnote{A; multo B}} quoque et bello passus, dum conderet urbem, inferretque deos Latio, genus unde Latinum, Albanique patres, atque altae moenia Romae.

\vspace{10pt}

\begin{stanza}
Musa, mihi causas \edtext{memora}{\choiceline{1}{1}\Afootnote{A; memorum B}}, quo numine laeso,&
quidve dolens, regina deum tot volvere casus\&
\end{stanza}

\vspace{10pt}

\begin{stanza}
\edtext{insignem}{\choiceline{2}{1}\Afootnote{A; insigni B}} pietate virum, tot adire labores&
impulerit. Tantaene animis caelestibus irae?\&
\end{stanza}

\end{Leftside}

\begin{Rightside} 

\setstanzaindents{0,0,0}

\beginnumbering
    \autopar
    
\newcommand{\choiceline}[2]{\linenum{|#1|#2||#1|#2}}
	\sublinenumberstyle{alph}
	\let\fullstop\relax

\noindent Arma virumque cano, Troiae qui \edtext{primus}{\choiceline{1}{3}\Afootnote{A; primo B}} ab oris Italiam, fato profugus, Laviniaque venit litora, multum ille et terris iactatus et alto vi superum saevae memorem Iunonis ob iram; \edtext{multa}{\Afootnote{A; multo B}} quoque et bello passus, dum conderet urbem, inferretque deos Latio, genus unde Latinum, Albanique patres, atque altae moenia Romae.

\vspace{10pt}

\begin{stanza}
Musa, mihi causas \edtext{memora}{\choiceline{1}{1}\Afootnote{A; memorum B}}, quo numine laeso,&
quidve dolens, regina deum tot volvere casus\&
\end{stanza}

\vspace{10pt}

\begin{stanza}
\edtext{insignem}{\choiceline{2}{1}\Afootnote{A; insigni B}} pietate virum, tot adire labores&
impulerit. Tantaene animis caelestibus irae?\&
\end{stanza}

\endnumbering

\end{Rightside}

\end{pairs}
\Columns

\end{document}
</code></pre>

![text](https://cloud.githubusercontent.com/assets/11613865/9607937/90336dba-50eb-11e5-90ea-16e513821334.jpg)

**Comment by maieul** [comment]
that is two different problem. Please open one issue by problem. This issue will be devoted to the first one.

**Comment by maieul** [comment]
ps : you should push 
````
   \newcommand{\choiceline}[2]{\linenum{|#1|#2||#1|#2}}
    \sublinenumberstyle{alph}
    \let\fullstop\relax
```` 

in your preamble.

**Comment by apollo77x** [comment]
Ah, yes, that seems to solve it!  Also I put all the notes in one register instead of using one register for each text.  There is still the problem in the one with multiple scripts tho.

**Comment by maieul** [comment]
you are right, that solve the problem, but that you should not. conceptually, we should be able to choice different style for both right and left side...

**Comment by maieul** [comment]
and as I said : one problem in same time� do you know there is 40 issue open? if you mix problem, I can't solve them...

**Comment by apollo77x** [comment]
Yes, I have changed the issues accordingly.  Thanks.

**Comment by maieul** [comment]
you should push it in the preamble, because it is just setting, and setting should be in the preamble.

**Comment by apollo77x** [comment]
I see.  Yes, it is a newbie's mistake, I'm learning all this myself as I go along.  However, for the other text in two scripts, even if it is in the preamble, the sub-line number doesn't show up for the second text.

**Comment by maieul** [comment]
yes, but that is an other problem. And your solution was not satisfactory, because line number in footnote should represented as line number in margin. And actually, that is not the case (if you decide to have, for example, line number in margin right in alphabetical form, it won't be in bottom).

**Comment by maieul** [comment]
please try branch "issue400" (read https://github.com/maieul/ledmac#debug-and-feature-requests to know how to test). It provides now:
- \sublinenumrep only for left side
- \sublinenumrepR only for right side
- \sublinenumrep* for both side.

**Comment by apollo77x** [comment]
OK, thanks.  I will have to try this tomorrow.

**Comment by maieul** [comment]
hi, some feedback?

**Comment by apollo77x** [comment]
Hi, using the `[numerals=false]` option for the Tibetan font seemed to do the trick.  However, this option doesn't seem to work for the Sanskrit font.

**Comment by maieul** [comment]
"However, this option doesn't seem to work for the Sanskrit font, not that I need it to get the letters in the line numbering."

I don't understand. In sanskrit, your does not need this option to have a letter. Could you reexplain? And my question was about, \sublinenumrepR  and \sublinenumrep*.

**Comment by apollo77x** [comment]
Never mind about the Sanskrit font, it is related to an unrelated problem.  After the `numerals=false` option for the Tibetan worked I didn't need to try `\sublinenumbrepR`, etc.  I will try them tomorrow and let you know.  Thanks.

**Comment by maieul** [comment]
ok. please check it, because I have explained in my answer, this will change for you.

**Comment by maieul** [comment]
hi, could you try ? I would like to publish it quickly ;-)

**Comment by apollo77x** [comment]
Yes, I tried.  It doesn't seem to work.  Before installing your fix, the second place in the Tibetan line numbering was just blank, i.e. it would read "2 " instead of "2a".  Now it prints a number instead of a letter , i.e. "21".

**Comment by maieul** [comment]
dead you really use
\sublinenumbrepR{alph}
or 
\sublinenumrep*{alph}

as I explained?

**Comment by apollo77x** [comment]
Sorry I forgot to put that in!  When I put this in after the \beginnumbering command:

     \sublinenumrep*{alph} 
	\let\fullstop\relax   

 it gives an error: 'Missing number, treated as zero'

When I put in

	\sublinenumbrepR{alph}
	\let\fullstop\relax   

It gives the error "undefined control sequence"

**Comment by maieul** [comment]
did you really put the new .sty file around you .tex file? could I obtain the log?

**Comment by apollo77x** [comment]
Yes, I put the .sty files with the file.

![image](https://cloud.githubusercontent.com/assets/11613865/9661473/974f4aac-527a-11e5-98bf-c2b8bbe8da34.png)

**Comment by maieul** [comment]
I can read the join file. You should have reledpar.sty and reledmac.sty file.
reledpar.sty should contain
\ProvidesPackage{reledpar}[2015/09/01 v2.3.0 reledmac extension for parallel texts]%
while reledmac.sty should contain

\ProvidesPackage{reledmac}[2015/08/26 v2.1.2 typesset critical edition]%


Le 3 sept. 2015 � 16:45, apollo77x <notifications@github.com> a �crit :

**Comment by apollo77x** [comment]
Yes, they both have those sentences.

**Comment by apollo77x** [comment]
Where do I upload the log files?

**Comment by maieul** [comment]
Hum, could you send me be email all your folder? There is something not normal�

**Comment by maieul** [comment]
send me all by email (myfirstname at myfirstanme dot net)
-----
Ma�eul Rouquette
www.maieul.net
http://geekographie.maieul.net/

Le 3 sept. 2015 � 16:59, apollo77x <notifications@github.com> a �crit :

**Comment by maieul** [comment]
ok, I know why it didn't work. I didn't ask you for the good command

\sublinenumberstyleR

and 

\sublinenumberstyle* 

are the good (equivalent to \sublinenumberstyle for right or both text, respectivly)

**Comment by apollo77x** [comment]
I tried with these commands, now the letter component in the apparatus for the Tibetan doesn't appear as before.

**Comment by maieul** [comment]
thats is normal, you don't use the optional argument for \setotherlanguage{tibetan} (that is nothing do see with this issue).

**Comment by maieul** [comment]
so all it's working if you use the correct option for tibetan language. I close.
