### ISSUE TITLE
Using \sublinenumberstyle in an eledpar document with multiple scripts

### ISSUE THREAD

**Issue by apollo77x** [maieul/ledmac#401]
I am making an edition wherein a citation from a verse should be referred to by both the verse's number and the quarter of the verse that it appears in. The number of the verse should be a numeral and the quarter should be referred to by a letter, from 'a' to 'd.' For example, a citation of the second quarter of the third verse should be referred to in the critical apparatus by '3b'. To accomplish this in a standard edition with only one text using `reledmac` one can alphabetize the sub-line numbers and have them function as the component of the citation in the apparatus that refers to the quarter of the verse.

However, I am making a document in which there are two columns of text using `reledpar`, each in a different language and script.  The problem seems to come from the use of multiple scripts used in my document, as the custom line numbering command (i.e. `\choiceline` here) works for both texts when they are both in Roman script, but here the sub-line numbers do not appear at all for the second text.

What happens is that the custom line numbering command works for the first text (in this case the Sanskrit text), but for some reason in the second (Tibetan) text the letter component of the citation (which is actually the sub-line value) doesn't show up.

It seems that the problem is that the custom line numbering command (i.e. `\choiceline`) should be defined again for the second text right after the `\beginnumbering` command, but if I do that there is an error that this command has already been defined.

You can get the Sanskrit font used in the MWE, Nakula, [here](http://bombay.indology.info/software/fonts/devanagari/), and the Tibetan font, Jomolhari, [here](https://collab.itc.virginia.edu/wiki/tibetan-script/Jomolhari.html).

<pre><code>

\documentclass{article}

\usepackage{reledmac}
   
\usepackage{reledpar}

\usepackage{fontspec}

\usepackage{polyglossia}
    \setmainlanguage{english}
    \setotherlanguage{sanskrit}
    \setotherlanguage{tibetan}
    \newfontfamily\devanagarifont{Nakula}
    \newfontfamily\tibetanfont{Jomolhari}
    
\usepackage{geometry}
    
\setlength{\Lcolwidth}{0.48\textwidth}
\setlength{\Rcolwidth}{0.48\textwidth} 
    
\newcommand{\choiceline}[2]{\linenum{|#1|#2||#1|#2}}
	\sublinenumberstyle{alph}
	\let\fullstop\relax    

\begin{document}

\begin{pairs}

\begin{Leftside} 

\setstanzaindents{0,0,0}
   
\beginnumbering
    \autopar

\devanagarifont
\begin{sanskrit}
\noindent तत्र \edtext{खलु}{\Afootnote{A; एव B}} भगवान् पुनरपि चन्द्रप्रभं बोधिसत्वमामन्त्रायते स्म॥ तस्मात् तर्हि कुमार बोधिसत्वेन महासत्वेन सर्वधर्मानां महाभिज्ञापरिकर्म परिशोधयितुकेमनायं समाधिः श्रोतव्यः॥

\begin{stanza}
महाभिज्ञापरिकर्म \edtext{अविवादेन}{\choiceline{1}{2}\Afootnote{B; अविवदेन A}} देशितः।&
विवादे यस्तु चरति नोद्गृह्णन् स विमुच्यते॥\&
\end{stanza}

\begin{stanza}
अभिज्ञा तस्य सा प्रज्ञा बोद्धं ज्ञानम् अचिन्तियम्।&
उद्ग्रहे \edtext{य}{\choiceline{2}{3}\Afootnote{B; यो A}} स्थितो भोन्ति ज्ञानं तस्य न विद्यते॥\&
\end{stanza}

\end{sanskrit}

\endnumbering

\end{Leftside}

\begin{Rightside} 

\setstanzaindents{0,0,0}

\beginnumbering
    \autopar

\tibetanfont
\begin{tibetan}

\noindent དེ་ནས་ཡང་བཅོམ་ལྡན་འདས་\edtext{ཀྱིས་}{\Bfootnote{A; ཀྱི་ B}}ཟླ་བ་གཞོན་ནུར་གྱུར་པ་ལ་བཀའ་སྩལ་པ། དེ་ལྟ་བས་ན་གཞོན་ནུ་བྱང་ཆུབ་སེམས་དཔའ་སེམས་དཔའ་ཆེན་པོ་ཆོས་ཐམས་ཅད་ལ་མངོན་པར་ཤེས་པའི་བྱི་དོར་བྱ་བ་སྦྱང་བར་འདོད་པས་ཏིང་ངེ་འཛིན་འདི་མཉན་པར་བྱ།

\begin{stanza}
།ཆོས་ཐམས་ཅད་ལ་མངོན་ཤེས་པ། །བརྩོད་པ་\edtext{མེད་པར་}{\choiceline{1}{2}\Bfootnote{A; མེད་པ་ B}}བསྟན་པ་སྟེ།&
།བསྩོད་པ་ལ་ནི་གང་གནས་པའི། །འཛིན་པ་དེ་ནི་མི་ཐར་རོ།\&
\end{stanza}

\begin{stanza}
།མངོན་ཤེས་\edtext{དེ་ཡི་}{\choiceline{2}{1}\Bfootnote{B; དེ་ཡིས་ A}}ཤེས་རབ་ཏེ། །སངས་རྒྱས་ཡེ་ཤེས་བསམ་མི་ཁྱབ།&
།འཛིན་པ་ལ་ནི་གང་གནས་པ། །དེ་ཡི་ཡེ་ཤེས་ཡོད་མ་ཡིན།\&
\end{stanza}

\end{tibetan}

\endnumbering

\end{Rightside}

\end{pairs}

\Columns

\end{document}

</code></pre>

![test 2](https://cloud.githubusercontent.com/assets/11613865/9607953/a95f0a42-50eb-11e5-9066-86c00b3dbbd5.jpg)

**Comment by maieul** [comment]
please, next time, send a real minimal working example. Cf my minimilazion in be9eda4

**Comment by maieul** [comment]
I close this issue. I have the answer. I will respond on tex.stackexchange.
