### ISSUE TITLE
Missing error about \par in paragraphed notes

### ISSUE THREAD

**Issue by tweh** [maieul/ledmac#402]
While testing on #392 unfortunately I came to another problem, which isn’t really bad but maybe could be fixed sometimes in the future … When using the `paragraph` arrangement a `\par` in the notes should not be used as stated clearly in the manual. But if the user does it should give an error, though.

If used in a critical note LaTeX throws an error complaning about the forbidden `\par` but when using a familiar note it doesn’t. In the latter case everything until the `\par` is silently gobbled. This is independ of the option `parapparatus`.

```latex
\documentclass{article}

\usepackage[
   parapparatus,
]{reledmac}

\Xarrangement[A]{paragraph}
\arrangementX[A]{paragraph}

\newcommand{\sometext}{%
   Nam dui ligula, fringilla a, euismod sodales, sollicitudin vel, wisi. Morbi
   auctor lorem non justo. Nam lacus libero, pretium at, lobortis vitae, ultricies
   et, tellus.
}

\begin{document}
Test\footnoteA{\textbf{Normal A}: \sometext\par \sometext}
Test\footnoteA{\textbf{Normal A}: \sometext}
Test\footnoteA{\textbf{Normal A}: \sometext}

\beginnumbering
   \pstart
   \edtext{Test}{\Afootnote{\textbf{Critical A}: \sometext\par \sometext}}
   \edtext{Test}{\Afootnote{\textbf{Critical A}: \sometext}}
   \edtext{Test}{\Afootnote{\textbf{Critical A}: \sometext}}
   \pend
\endnumbering
\end{document}
```

**Comment by maieul** [comment]
that happens only if you don't write the \par directly, but only in a \sub command.

See the difference in this MWE between the two call of \toto

\documentclass{article}
\usepackage{lipsum}
\begin{document}
\newcommand*{\toto}[1]{#1}
\def\titi{a\par b}
\toto{\titi}
\toto{a \par b}
\end{document}

I don't see why people should insert a \par inside a subcommand called in \Afootnote. And, further more, I don't know how to test the presence of a paragraph...

**Comment by tweh** [comment]
OK … I’m just irritated that `\footnoteA` doesn’t raise an error, while `\Afootnote` does. An I did use the `\par` directly … and even with a blank line in the input.

But I find a (partial) solution and send a pull request.

**Comment by maieul** [comment]
we we close with the comments...
