### ISSUE TITLE
\beforenotesX vs. nocritical option

### ISSUE THREAD

**Issue by tweh** [maieul/ledmac#407]
If the `no critical` option is active the command `\beforenotesX` (which is for familiar notes) doesn’t work. I.e. it thors a `Missing \begin{document}` error …

```latex
\documentclass{article}

\usepackage[%
   nocritical,
]{reledmac}

\beforenotesX{10pt}

\begin{document}
Test\footnoteA{Text}
\end{document}
```

**Comment by maieul** [comment]
please try branch issue407

**Comment by tweh** [comment]
Thanks. Now it works!

**Comment by maieul** [comment]
please let me close the issue. I close them only when moving in the release branch.

**Comment by tweh** [comment]
OK … sorry O:-)
