### ISSUE TITLE
\mainmatter intégré à \pages

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#408]
pb ici http://tex.stackexchange.com/q/267108/7712.

Piste de solution : proposer une options à \pages pour faire aussi le mainmatter. Cela aurait des repercussions  de ce type
````
\renewcommand*{\cleartol@devenpage}{%
  \ifdim\pagetotal<\topskip%  on an empty page
  \else
    \clearpage
    \pagenumbering{arabic}%
    \addtocounter{page}{1}%
    \addtocounter{par@page}{-1}%
    \patchcmd{\thepage}{page}{par@page}{}{}%  
  \fi
  \ifodd\c@page%
    \ifprevpgnotnumbered%
      \addtocounter{par@page}{-1}%
      \ifdef{\prevpgstyle}{\thispagestyle{\prevpgstyle}}{}%
    \fi%
    \hbox{}\clearpage%
  \fi%
}%
````

**Comment by maieul** [comment]
@nliautaud peux tu tester la branche issue408. Elle fournit une nouvelle option pour \Pages : [mainmatter]. Du coup pas besoin de \mainmatter. Voir https://github.com/maieul/ledmac/blob/issue408/issue408.tex

**Comment by nliautaud** [comment]
Ça m'a l'air parfait !

**Comment by maieul** [comment]
ok, je fusionne dans la branche de release.

**Comment by maieul** [comment]
@nliautaud j'ai posté une réponse à tes deux questions sur tex.stackexchange.

Peux tu voter en leur faveur et les valider ?

**Comment by nliautaud** [comment]
C'est fait, merci !

**Comment by ralessi** [comment]
Je ne comprends pas cette option: que faut-il écrire au juste: `\Pages[mainmatter]` --> cela me donne `undefined command name`.

Car dans mon édition, je viens de connaître ce problème de pages vides, alors que je ne l'avais pas auparavant...

**Comment by ralessi** [comment]
En fait, je me retrouve avec une paire de pages vides... Enfin, pas tout à fait: la première page, celle de gauche donc, n'est pas tout à fait vide: il y a juste un point au début de la première ligne. Je sens que le mwe ne sera pas facile à produire.

**Comment by ralessi** [comment]
Bon, je viens de vérifier la syntaxe sur TS, c'est bien `\Pages[mainmatter]`, et cela corrige mon problème.

Mais (car il y a un mais): que faire quand on a une stucture telle que:
````
\mainmatter
\part*{Titre du traité tout seul sur une belle page}
\phantomsection
\addcontentsline{toc}{part}{Titre du traité}
[édition proprement dite avec texte et traduction en vis à vis]
````

Dans ce cas, je suis bien obligé de mettre `mainmatter` juste avant `\part{}`, et je me retrouve avec deux pages vides.

**Comment by maieul** [comment]
je regarde ce week, ou peut �tre ce soir
-----
Ma�eul
http://blog.maieul.net
http://www.schtroumpfs.maieul.net/

Le 24 nov. 2015 � 00:56, Robert Alessi <notifications@github.com> a �crit :

**Comment by ralessi** [comment]
Merci!

**Comment by maieul** [comment]
a tu peux m'ouvrir un ticket specifique ? sinon je risque d'oublier...

**Comment by ralessi** [comment]
Ok.
