### ISSUE TITLE
trois mode de synchronisation

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#409]
Pour avance un peu sur les pb de @ralessi, qui rejoignent aussi http://tex.stackexchange.com/q/267101/7712, on peut imaginer trois modes de mise synchronisations des textes : (en ne tenant pas compte du contenu interpstart et des intertitres).

* mode actuel (1) : la rupture de page se fait : 
  * lorsqu'on atteint le maximum acceptée sur une page (goalfraction)
  * lorsque on dépasse le nombre miminum de ligne dans le couple page gauche/page droite au précédent tour
* mode shifted (2).  Même chose que le mode actuel MAIS on decale au sein d'une même page pour ne pas avoir de ligne blanche entre 2 pstart si le pstart de gauche est trop court
* mode decalée : mode shifted +on ne tient pas compte du nombre minimum de page. Du coup il n'y a plus du tout de synchronisation.

**Comment by maieul** [comment]
qu'en pensse @ralessi ?

**Comment by maieul** [comment]
(pour moi: bout de code pour le mode 3)
`````
\newif\if@notsynced
\newcommand*{\checkpageL}{%
  \l@dpagefulltrue
  \l@dsamepagetrue
  \check@goal
  \ifdim\pagetotal<\ledthegoal
    \ifnum\numpagelinesL<\l@dminpagelines
    \else
      \if@notsynced\else%
        \l@dsamepagefalse
        \l@dpagefullfalse
      \fi%
      \fi
  \else
    \l@dsamepagefalse
    \l@dpagefulltrue
  \fi%
  \ifprint@last@after@pendL%
     \l@dpagefullfalse%
     \l@dsamepagefalse%
     \print@last@after@pendLfalse%
  \fi%
  }%

\newcommand*{\checkpageR}{%
  \l@dpagefulltrue
  \l@dsamepagetrue
  \check@goal
  \ifdim\pagetotal<\ledthegoal
    \ifnum\numpagelinesR<\l@dminpagelines
    \else
      \if@notsynced\else%
        \l@dsamepagefalse
        \l@dpagefullfalse
      \fi%
    \fi
  \else
    \l@dsamepagefalse
    \l@dpagefulltrue
  \fi%
  \ifprint@last@after@pendR%
     \l@dpagefullfalse%
     \l@dsamepagefalse%
     \print@last@after@pendRfalse%
  \fi%
  }%
````

**Comment by maieul** [comment]
pour y voir plus clair les trois exemples 
1. https://drive.switch.ch/public.php?service=files&t=022d3ebd0bf33047b06a20de2a2cd725
2. https://drive.switch.ch/public.php?service=files&t=3a32baca59e3ff3309e5906f52090c1f
3. https://drive.switch.ch/public.php?service=files&t=58acc14dc4e5e4e22a51427e9a5673e2

**Comment by ralessi** [comment]
Je pense que l'introduction du mode 3 s'impose! C'est une excellente idée, et c'est en fait ainsi que fonctionnent les éditions imprimées.  De mon côté, c'est ce que je fais, au prix de quelques acrobaties pour le moment.

En fait, je ne synchronise pas du tout le côté de la traduction.  Ensuite, une fois l'édition critique stabilisée, j'équilibre la traduction à l'aide de commandes de rupture de page.

**Comment by maieul** [comment]
ok, je comprend mieux maintenant les demandes. Je ferais cela  ce week-end. L'essentiel est normalement deja l�, le reste n'est que fignolage...

**Comment by ralessi** [comment]
Ce sera une avancée majeure. Merci!

**Comment by maieul** [comment]
@ralessi et @nliautaud : pouvez vous tester la branche issue409. Elle fournit une option de reledpar nosyncpstarts. Voir les 3 fichiers examples/3-reledpar_sync_setting*tex

**Comment by nliautaud** [comment]
Si `nosyncpstarts` doit désactiver complètement l'alignement des paragraphes, ça semble fonctionner. Par contre ce n'est pas ce dont je parlais pour http://tex.stackexchange.com/q/267101/7712. J'aurais peut-être dû indiquer que l'objectif est de garder la synchronisation des textes. L'objet est de ne pas couper à droite à cause de la `footnoteXnomk` de gauche, s'il y a la place. Je ne sais pas si ça a avoir avec cette fonctionnalité donc, mais je suis peut-être passé à côté de ce qu'il fallait regarder ?

Nouvel exemple :

![capture](https://cloud.githubusercontent.com/assets/761761/9977505/58c8b50a-5f0b-11e5-8063-f7887eac538e.PNG)

Je mettrais à jour la question stackexchange si besoin.

**Comment by ralessi** [comment]
Je n'ai pas bien suivi la discussion, mais sur le point précis d'une option qui désactive la synchronisation des textes, je pense qu'elle est nécessaire. Actuellement, je force reledmac à ne sortir que les pages de droite (texte critique). Ce n'est pas très commode.

**Comment by maieul** [comment]
dans ton exemple Nicolas, la coupure de droite est directement li� au fait que le nombre de ligne atteint � droite est �quivalent au nombre de ligne atteint � gauche� et qu'on prend le minimum. Avec l'option nosyncpstart, on ne cherche pas � avoir exactement le m�me nombre.

Du coup on pourrait imaginer une autre option de synchronisation, qui correspondrait � un stade interm�diaire : on peut avoir un nombre diff�rente de ligne entre gauche et droite, mais on ne peut pas passer au � sur une page que si on passe au paragraphe suivant sur la page �quivalent...

**Comment by nliautaud** [comment]
@maieul Oui, ça me semble être tout à fait l'idée. J'imaginais que c'était le comportement par défaut d'ailleurs.

**Comment by maieul** [comment]
en tout cas Nicolas, avec l'exemple que tu a fournis, l'option notsyncpstarts r�pond totalement � tes besoins.

cf https://github.com/maieul/ledmac/blob/40e4e21d1e37de66ce3bbf30e4be8fef104d4928/issue409.tex

mais cela �tant, je pense qu'une quatri�me option serait vraiment utile, une qui se contenterai de ne pas surveiller le nombre minimum

**Comment by nliautaud** [comment]
Oui l'exemple de stackoverflow n'est pas suffisant comme je disais (je n'avais pas prévu qu'on puisse le résoudre en désactivant entièrement la synchronisation !). D'où le nouveau exemple de résultat attendu que j'ai rajouté au-dessus. Je peux faire un nouveau MWE basé là dessus si besoin.

**Comment by maieul** [comment]
oui, un nouveau MWE serait utile, pour v�rifier tout cela.

**Comment by nliautaud** [comment]
Voila : le deuxième paragraphe en anglais devrait pouvoir rentrer entièrement en page 5.

    \documentclass[a5paper,12pt]{book}
    \usepackage{geometry}
    \usepackage[greek,french]{babel}
    \usepackage[pangram]{blindtext}
    \usepackage{eledmac}
    \usepackage{eledpar}
    \maxhnotesX{0.4\textheight}
    
    \begin{document}
    \large
    \begin{pages}
        \begin{Leftside}
            \selectlanguage{greek}
            \beginnumbering
                \pstart
                    1. \blindtext[21]
                \pend\pstart
                    2. \blindtext[10]
                    \footnoteAnomk{\selectlanguage{french}\blindtext[13]}
                \pend\pstart
                    3. \blindtext[6]
                \pend
            \endnumbering
        \end{Leftside}
        \begin{Rightside}
            \beginnumbering
                \pstart
                    1. \blindtext[22]\footnoteAmk
                \pend\pstart
                    2. \blindtext[12]
                \pend\pstart
                    3. \blindtext[12]
                \pend
            \endnumbering
        \end{Rightside}
    \end{pages}
    \Pages
    \end{document}

**Comment by maieul** [comment]
quoi  qu'il en soit, j'ai un bug dans mon impl�mentation, qui fait que plus rien ne fonctionne. je regarde

**Comment by maieul** [comment]
bon j'arr�te pour ce soir. Plus complexe qu'envisageais initialement

**Comment by maieul** [comment]
donc le mode "nomax" a été introduit dans la branche 409.

Voir ici des  résultats avec les trois modes. 

https://drive.switch.ch/public.php?service=files&t=ca644717c88f88ccd623c8bbd04bd912

A tester donc avec des fichiers plus importamts (ne pas oublier de supprimer les fichiers numérotés avant de faire un test sur un nouveau mode)

**Comment by nliautaud** [comment]
Super, je teste de ce pas avec un projet plus conséquent. (c'est à dire supprimer les fichiers numérotés ?)

**Comment by maieul** [comment]
lorsque tu compile avec latex, reledmac produit des fichiers num�rot�s. (.1, .2, etc ; .1R, .2R). Avant tout nouveau test de synchronisation, il faut les supprimer (et puis refaire un tout de latexmk, jusqu'� ce qu'il soient stabilis�s)

**Comment by ralessi** [comment]
Je pourrai faire des tests à partir de mardi.

Ce que je vois sur les fichiers attachés me semble absolument parfait!

**Comment by nliautaud** [comment]
Ça m'a l'air tout bon !

(je teste via sharelatex qui me montre juste les sorties pdf, mais je n'ai aucun souci pour changer de mode de synchronisation en tout cas)

**Comment by maieul** [comment]
a priori je dirais que le mode nomax + shifted est le plus int�ressant. 

Il reste cependant encore un pb avec https://github.com/maieul/ledmac/blob/92cf6274cc15e5f760d9092bbf71a61f826b9cc1/issue409-bis.tex

les � sont mal align�s :(

**Comment by nliautaud** [comment]
@maieul Il y a un problème d'encodage dans tes messages qui m’empêche de bien comprendre. Qu'est-ce qui est mal aligné ?

**Comment by maieul** [comment]
les paragraphes. ils devraient être alignés et commencer sur la même page...

**Comment by nliautaud** [comment]
Oui, j'ai vu. Si tu n'as pas de piste je pourrais essayer tout à l'heure de réduire le projet sur lequel j'ai testé et qui semblait marcher, pour voir les différences avec le petit exemple qui ne marche pas.

**Comment by maieul** [comment]
non, j'ai des pistes. C'est justes des r�glages ultra sensibles, qui demande de prendre en compte pas mal de questions...

**Comment by maieul** [comment]
pb résolu, cf https://drive.switch.ch/public.php?service=files&t=5db8565603ae10046588474bcdce65e3.

Bon il reste encore un pb : il faudrait un mode avancé de shifted, qui ne compte pas les lignes blanches...

**Comment by nliautaud** [comment]
Ça a l'air super pour le nomax.
Pour le shifted on s'attendrait à ce que le texte remplisse l'espace gagné en bas effectivement, et que ce soit son comportement par défaut. En l'état ça réduit pas mal son utilité.

Tout ça est vraiment super en tout cas.

**Comment by maieul** [comment]
bon, j'ai trouvé un nouveau mode, qui s'appelle advancedshifted. Cela permet notamment de s'assurer que l'espace lié au shift ne soit pas pris en compte pour le calul de coupure de page, ce qui éviter d'avoir des pages à moitiés vides parce qu'on conserve l'espace de décalage en bas.

voir l'exemple  https://drive.switch.ch/public.php?service=files&t=0f962fb7833209e19caba4cc9b9e809f

**Comment by nliautaud** [comment]
Ça ne devrait pas être le comportement par défaut de shifted ? Je teste de ce pas.

Il me semble voir des petits problèmes avec nomaxlines (nouveau paragraphe qui apparaît en dernière ligne d'une page de gauche alors que la page de droite est pleine du paragraphe précédent; page blanche à gauche...), mais je ne parviens pas bien à les identifier pour l'instant.

**Comment by nliautaud** [comment]
J'ai une erreur fatale avec `advancedshift` appliqué à autre chose que l'exemple : 
```
Undefined control sequence.
\KV@packages/reledpar.sty@advancedshiftedpstarts ...
                                                  \fi \advancedshiftedpstart...
l.64 \newdimen
              \Lcolwidth
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

Normal \dimen register pool exhausted, switching to extended pool.
```

**Comment by maieul** [comment]
ca ne peut pas �tre le comportement par d�faut car cela entrainerait une rupture de compat.
il me reste encore des points � creuser. Je n'arrive pas � faire le shift + nomax en m�me tps, et c'est parfois necessaire

**Comment by maieul** [comment]
> �a ne devrait pas �tre le comportement par d�faut de shifted ? Je teste de ce pas.

non, le comportement par d�faut de shifted > juste coller les morceaux qui aurait �t� �tali� sur la page sinon�
il faut toujours partir de la mise en page par d�faut puis regarder shifted
> 
> Il me semble voir des petits probl�mes avec nomaxlines (nouveau paragraphe qui appara�t en derni�re ligne d'une page de gauche alors que la page de droite est pleine du paragraphe pr�c�dent; page blanche � gauche...), mais je ne parviens pas bien � les identifier pour l'instant.

attention il y avait un bug dans la version sur le serveur, j'envoie bient�t une nvl version

**Comment by maieul** [comment]
il me faut le mwe pour savoir d'o� vient le bug

**Comment by maieul** [comment]
donc voilà le mode advanced shifted + nomax est compatible. Voir les fichiers au commit cd58052

https://drive.switch.ch/public.php?service=files&t=477499251b99a7508dad7cd97fde3678

En résumé trois paramètres : 
- début de pstart alignés ou pas. Valeur par défaut. shifted et advance shifted désactive. Autrement dit : les lignes blanches sont-elles insérés entre les pstarts.
- nombre de lignes par pages, y compris lignes blanches, identiques ou pas. Valeur par défaut = identique. nomaxlines supprime.
- nombre de ligne, y compris blanche,  par pstart  en vis à vis calé sur le minimum. Advanced shiftedpstarts supprime cela (en plus de faire un shifte)

Reste à trouver comment on document cela. Je pense qu'il faudrait d'abord expliquer le comportement par défaut à savoir : 
- le nombre de lignes par pages, y compris blanche, est calé sur la page qui peut en contenir le moins, à cause des notes
- le nombre de lignes y compris blanche, par pstart en vis à vis, est calé sur le maximum contenable par pair

L'exemple 3-reledpar_sync_setting_default montre cela bien à la 4-5. Le § 3 de la page de 5 s'arrête pour avoir le même nombre de lignes sur la page à gauche et à droite. Le § 2 de la page 4 contient des lignes blanches pour avoir un total de lignes correspondant aux lignes effectives à droite.

Ensuite à partir de là : 
- shiftepstart se contente de "gober" les lignes du § 2 de p.4
- nomax se content que le § 3 de la p. 5 peut continuer
- advancedshifted "gobes" lies lignes du § 2 de p. 4. Mais à la page 7 le § 5 ne contient que 5 lignes, à cause du manque de place, donc le § 5 de la page 6 ne contient que 5 lignes.
- si on combien advancedshiftedpstart + nomax, on essaie de caler au maximum sur une page

**Comment by maieul** [comment]
et le mode nosync lui c'est juste l'alternance gauche/droite, sans tenir compte de la correspondance.

**Comment by nliautaud** [comment]
Ça a l'air de fonctionner.

En terme de rédaction d'une explication, j'aurais été aidé par quelque chose comme ça : 

**synchronisation, alignement**
Par défaut, eledpar synchronise les paragraphes correspondant entre les pages de gauche et les pages de droite pour qu'ils démarrent sur une même paire de page puis, au sein des pages, cale le début des paragraphes à la même hauteur, en rajoutant des lignes vides lorsqu'un de deux est plus court que l'autre. Trois modes additionnels permettent de désactiver la synchronisation ou l'alignement : 
* `nosync` : mode sans synchronisation. Les paragraphes sont placés à la suite sans considération pour le face à face.
* `shiftedpstarts` : mode sans alignement au sein des pages. Les paragraphes sont placés bout à bout, l'espace gagné est conservé en bas de page.
* `advancedshiftedpstarts` : mode sans alignement au sein des pages. Les paragraphes commencent bout à bout et utilisent l'espace disponible jusqu'en bas de la page.

**équilibre des lignes**
Par défaut, le nombre maximum de lignes dans les pages (qu'elles soient pleines ou vides) est le même à gauche et à droite. Lorsque l'espace disponible n'y est pas le même, dans le cas de bas de pages de différentes hauteur par exemple, l'option suivante permet de désactiver ce comportement : 
* `nomaxlines` : rend les pages de droite et de gauche indépendantes pour déterminer le nombre de lignes qu'elles peuvent contenir.

Là où le comportement par défaut privilégie l'alignement des textes au remplissage des pages, l'utilisation combinée des options `advancedshiftedpstarts` et `nomaxlines` permet d'éviter au maximum les espaces vides en gardant la synchronisation, et `nosync` permet de prendre la main sur la synchronisation en gardant l'alternance des pages.

**Comment by maieul** [comment]
oui, je crois que je vais formuler quelque chose de ce type, mais en plus pr�cis. 
@robertalessi : si j'�cris en fran�ais pour mon blog, tu pourrais traduire cela en anglais pour la documentation? je pense que cela devrait prendre autour d'une page ...

**Comment by ralessi** [comment]
Oui, avec plaisir!

**Comment by maieul** [comment]
ok, j'essaierai de r�diger cela ce soir

**Comment by ralessi** [comment]
D'accord. Je ferai la traduction au plus tard mercredi.

**Comment by maieul** [comment]
bon ca sera pour demain soir finalement.
Sinon il faut aussi que je mette une s�curit� pour s'assurer de tout recompiler (rejeter les fichiers num�rot�s) en cas de changement de mode

**Comment by ralessi** [comment]
Ou alors dire dans la doc qu'il faut le faire? Je crois bien l'avoir lu quelque part en fait. Ça doit donc y être.

**Comment by maieul** [comment]
je l'ai dit dans ce fil de discussion. Mais mettre une s�curit� n'est pas du luxe et pas trop compliqu� non plus.

**Comment by maieul** [comment]
Voilà ma proposition d'explication. Je fais d'abord un résumé rapide, puis je donne les détails. Je demeure convaincu maintenant que l'option nomaxlines + advancedshiftedpstarts est la meilleure.

Le processus de synchronisation passe par l’écriture dans les fichiers auxiliaires numérotés (.1, .1R, .2, .2R etc), dont le contenu change tant que la synchronisation n’est pas stabilisée. Ceci implique donc généralement plusieurs compilations. Nous vous conseillons donc d’utiliser un utilitaire tel que latexmk pour s’assurer que la synchronisation des pages est bien stabilisée.

Nous appelons « blocs » (chunck) la zone délimitée par un \pstart…\pend.

Pour faire bref, le réglage par défaut permet de s’assurer d’une synchronicité maximum entre les blocs correspondants, au détriment du remplissage des pages et en laissant des blancs entre les blocs. La combinaison des règlages advancedshiftedpstarts et nomaxlines permet de s’assurer de remplir aux maximum les pages, au détriment de la synchronicité des blocs, tout en s’assurant qu’un bloc commence toujours sur la page en vis-à-vis du bloc qui lui est associé. 

Pour comprendre plus finement les différentes options de synchronisation de reledpar, il est nécessaire de comprendre d’abord comment par défaut reledpar synchronise les blocs de gauche et droite. 

La synchronisation par défaut de reledpar vise deux objectifs :
-# S’assurer que les pages de gauche contiennent ce qui doit aller à gauche et les pages de droite contiennent ce qui doit aller à droite.
-# S’assurer que chaque bloc commence en face de son vis-à-vis.

Pour répondre à ce second objectif, reledpar s’assure que les règles suivantes soient respectées :
-# Le nombre de lignes d’une paire de blocs est identique. Pour que ce point soit respecté, reledpar insère des lignes blanches en bas du bloc le plus court, afin qu’il compte le même nombre de ligne que le bloc le plus long. 
-# Le contenu principal, excluant les notes critiques et les notes familières, de deux pages en vis-à-vis contient le même nombre de lignes, y compris blanches. C’est pourquoi si une page de gauche contient des notes plus longues qu’une page de droite, le bas de la page de droite sera vide.

Les options de synchronisation de reledpar permettent donc de modifier ces deux règles :
-#	En ce qui concerne le nombre de lignes par paire de blocs :
-## L’option shiftedpstarts se contente déplacer les lignes blanches de fin de bloc à la fin de page. Elle ne permet donc pas de mettre plus de lignes par page, mais simplement d’éviter au sein d’une page les espaces interblocs. Pour bien en comprendre le mécanisme, comparez les lignes de textes présentes sur une page avec ou sans cette option : vous constaterez que ce sont les mêmes, si
-##L’option advancedshiftedpstarts supprime l’insertion des lignes blanches de fin de bloc et leur décompte dans la taille de la page. Elle permet donc d’insérer plus de ligne par page. Notez cependant que :
-###Les lignes blanches restent prises en compte dans le calcul du moment où reledpar passe au bloc suivant. Ceci permet de s’assurer que deux blocs associés commencent systématiquement dans la même paire de pages.
-###En conséquence, les lignes blanches restent prises en compte dans le calcul du nombre de lignes par pair de pages. Ceci explique pourquoi lorsqu’un bloc courent sur deux pages, le bloc plus court correspondant court également sur deux pages, en dépit du fait qu’il puisse rester de la place sur sa première page.
-#En ce qui concerne le nombre de lignes, y compris blanches, par page, l’option nomaxlines supprime la règle d’égalité entre deux pages en vis-à-vis. Elle permet donc de mettre plus de contenu par page. Un mécanisme complexe est alors mis en œuvre pour s’assurer que deux blocs associés commencent sur deux pages en vis-à-vis, et pour qu’ils soient alignés, si l’option shiftedpstarts ou advancedshiftedpstarts n’est pas activée.

Enfin, il est possible de laisser de côté toute règle de synchronisation automatique et de se contenter de l’alternance entre les pages de gauche et les pages de droite. Pour ce faire, on utilisera l’option nosync.

Notez par ailleurs que tout changement de règle de synchronisation entre deux compilations entraîne ipso-facto l’annulation des fichiers numérotés, afin de s’assurer que reledpar ne tente pas de synchroniser selon des résultats archaïques.

**Comment by maieul** [comment]
et voilà, un message d'avertissement si on a changé les options entre deux passages.

**Comment by ralessi** [comment]
Tickety-boo.

Synchronization of left and right texts in parallel processing
requires some 'numbered' auxiliary files to be written (namely .1,
.1R, .2, .2R, and so forth), the content of which may change as long
as synchronization is not complete.  This usually requires LaTeX to be
run several times.  Therefore, it is advised to use in conjunction
utilities such as latexmk to ensure that synchronization is complete.

Numbered paragraphs which are contained between the \pstart and \pend
macros are thereafter called 'chunks'.

In short, the default setting is designed in such a way that
corresponding chunks of text are always kept in synchronization, even
at the cost of page padding, as it may result in leaving blank lines
between chunks of text.  Conversely, using in conjunction
'advancedshiftedpstarts' and 'nomaxlines' settings ensures that pages
are filled with text to full advantage—at the cost of the chunks not
being kept in synchronization—and every chunk starts on the facing
page of its corresponding chunk.

To understand better how each of the synchronization settings of
reledpar works, one must first understand how the default setting of
reledpar synchronizes the left and right chunks.

The aim of the default setting is twofold:
-# To ensure that left pages contain what is to be on left sides and
that right pages contain what is to be on right sides.
-# To ensure that every chunk starts on the page that is facing its
corresponding chunk.

As regards the latter, reledpar checks that both of the following
rules are respected:
-# The numbers of lines of every pair of chunks must be identical.  To
keep this rule, reledpar may insert some blank lines at the bottom of
the chunk that is shorter so that it may eventually have the same
number of lines as the one that is longer.
-# The main content of two facing pages, apart from critical and
familiar footnotes, must have the same numbers of lines, including
those that may be blank.  Consequently, if one left page contains more
notes than the corresponding right page, the bottom of the right page
must be left blank.

Each of these rules can be modified by a number of optional
synchronization settings in reledpar:
-# Regarding the number of lines a pair of chunks may have:
-## 'shiftedpstarts' setting merely moves any added blank lines from
the bottom of the chunks to the bottom of the page.  It does not allow
to have more lines on a given page as it just removes the blank lines
between the chunks and does nothing more.  To understand better how
this work, you may compare the total amounts of lines of text on a
given page whether you have activated this setting or not: you will
see that both amounts are the same.
-## 'advancedshiftedpstarts' prevents any blank lines from being
inserted at the bottom of the chunks, also taking them away from the
total amount of lines the page may have.  This allows to get more lines
on the pages.  However, please note that:
-### Blank lines are taken into account as reledpar moves from one to
the following chunk of text, so that every pair of chunks may always
start on the same facing pages.
-### Consequently, blank lines continue to be taken into account in
the calculation of the amount of lines a given pair of pages may have.
This is why when a longer chunk runs from one page to another the
shorter corresponding one also runs across pages, even if this may
result in some blank vertical space being left on the first page.
-# As regards the number of lines per page, including blank ones, the
'nomaxlines' setting disregards the rule that forces two facing pages
to have the same numbers of lines.  So it allows to have more text on
the pages.  Then, by a complex mechanism it is ensured that two
corresponding chunks may always start on the same facing pages,
provided that 'shiftedpstarts' or 'advancedshiftedpstarts' settings
shall be not activated.

Lastly, on may disregard all of the synchronization rules and content
himself with parallel texts typesetting.  To achieve this, please use
the 'nosync' setting.

Please note that every change of synchronization setting resets the
content of the 'numbered' auxiliary files to make sure that reledpar
does not try to make the synchronization with wrong calculations.

**Comment by maieul** [comment]
many thanks.

tu veux encore faire des tests o� je fusionne pour la branche pour la prochaine sortie?

**Comment by ralessi** [comment]
En fait, je n'ai pas encore eu le temps de tester. Mais Nicolas l'a fait. Je pensais faire mes tests entre ce soir et demain matin. Quand veux-tu publier cette version?

**Comment by maieul** [comment]
disons la semaine prochaine. J'aimerai demander vendredi pour lecture aux anglophones ;-)

**Comment by ralessi** [comment]
Cela laisse de temps. Merci.

**Comment by ralessi** [comment]
Au fait: c'est 'nosyncpstarts' qu'il faut lire plus haut.

**Comment by maieul** [comment]
c'est à dire ?

**Comment by ralessi** [comment]
Dans ce que j'ai traduit (avant-dernier paragraphe), il est question de l'option 'nosync', or dans la version de la branche 409, l'option qu'il faut mettre est 'nosyncpstarts'.

**Comment by maieul** [comment]
merci, mea culpa ;-)

**Comment by ralessi** [comment]
J'ai en fait commencé mes tests par cette option. Mais je vais essayer demain toutes les autres!

**Comment by ralessi** [comment]
Et plus haut aussi, lire évidemment: «Lastly, ***one*** may disregard...», et non pas «on» (toujours avant-dernier paragraphe).

**Comment by ralessi** [comment]
Je viens d'éditer mon post.

**Comment by maieul** [comment]
voilà

**Comment by maieul** [comment]
hop @ralessi des remarques sur les autres mode de synchronisations?

**Comment by ralessi** [comment]
J'ai pu constater qu'ils fonctionnent tous comme prévu!

En fait, sur certaines pages, j'ai tellement de notes critiques qu'il est impossible de ne pas avoir de "overfull vbox". Avec les nouvelles options, tout est cependant plus facile: sur ces pages, je fais un `\ledpb` pour qu'il n'y ait plus de dépassement. Ensuite, avec l'option `nosyncpstarts`, je mets où il faut les ruptures de pages du côté de la traduction.

Je sais que cela fait pas mal d'opérations manuelles, mais c'est ce que j'ai trouvé de mieux jusqu'à présent.

**Comment by maieul** [comment]
ok. je ferme. on regardera a nouveau par ailleurs la question du overfull vbox.

**Comment by ralessi** [comment]
Merci en tout cas pour ce travail important. Pour le reste, les notes paragraphées posent les problèmes qu'elles ont toujours posés...
