### ISSUE TITLE
alignement sans nouveau paragraphe

### ISSUE THREAD

**Issue by nliautaud** [maieul/ledmac#410]
Dans le cas où c'est possible, c'est à dire lorsqu'il y a plus d'une hauteur de ligne de différence entre les blocs précédents, serait-il possible de ne pas faire un nouveau paragraphe (en tout cas de rupture de ligne) au niveau du côté le plus long, et caler uniquement le côté le plus court ?

C'est à dire, côté utilisation, pouvoir ne pas considérer `\pstart...\pend` comme un bloc visuel détaché mais `\pend\pstart` comme un marqueur de l'endroit où aligner et couper *si besoin*, ce qui permettrait de pouvoir garder le flux original du texte sans rupture et pouvoir marquer des coupes au sein d'un paragraphe, voire d'une phrase.

A voir si c'est en lien avec #409.

![capture](https://cloud.githubusercontent.com/assets/761761/9873994/cbc07068-5ba3-11e5-9157-aaae5e9ddd79.PNG)
![capture_expected](https://cloud.githubusercontent.com/assets/761761/9873993/cbbfb48e-5ba3-11e5-9268-e5fe22d5fb91.PNG)

.

**Comment by maieul** [comment]
malheureusement ce n'est pas possible. Un \pstart par d�finition commence une nouvelle boite verticale, donc rupture de �.

On pourrait en revanche th�oriser un syst�me de marqueur autre qui demande � ce que deux points soient align�s, mais je ne suis pas certain de savoir comment faire, vu que le d�coupage en ligne pr�c�de l'alignement. 

Une piste (mais pour plus tard, il y a beaucoup de tickets ouverts) est la suivante.
Appelons A_r le point "stable" et "A_m" le point "movible". Au premier round on ne se pr�occupe pas, on note juste leur position sur la page
Au deuxi�me round on regarde si le point movible est situ� avant le point fixe. Dans ce cas on introduction automatiquement et artificiellement des lignes vides dans le \pstart�\pend. Ceci est le sch�ma th�orique. Mais j'ai quelque doutes sur
1) capacit� � implanter cela, notamment pour s'assurer de ne pas avoir des lignes faussements num�rot�es.
2) stabilit� du processus pour les run d'apr�s. J'ai peur qu'on arrive � des situations de "on tourne en rond".

La priorit� pour le moment serait #409. Voir ce que cela donne.

**Comment by nliautaud** [comment]
En effet, et s'il n'est pas possible de sortir temporairement de la découpe en boites j'imaginais qu'il soit possible de connaître les positions des ruptures de lignes et d'intégrer la fin du bloc précédent dans le nouveau bloc (dans l'exemple : `fume.`). Comme *décaler* la coupe au début de la ligne.

Mais je n'ai pas en tête les mécanismes, et je comprends tout à fait que ce ne soit pas une priorité.

**Comment by maieul** [comment]
non, car d'un point de vue interne, une rupture de ligne c'est juste une ligne dont toute la fin est vide� en fait chaque ligne est mise en boite. Et une fois les donn�es mise en boite, il est tr�s difficile de les r�cup�rer brut. La meilleure solution reste encore de faire de fausse lignes vides, plutot que de faire du collage

**Comment by maieul** [comment]
bon, avec les nouvelles options cela devrait jouer. On va voir à l'usage si on a encore besoin de cela, mais je vais me concentrer sur les autres tickets.

**Comment by maieul** [comment]
ne sera pas resolu. Trop prise de tete, a priori non utile avec les nouvelles options.
