### ISSUE TITLE
vertical space between endnotes

### ISSUE THREAD

**Issue by ingoboerner** [maieul/ledmac#411]
Dear @maieul, 
thank you for solving #335 . When @arthurali and i tested "Xendnumberonlyfirstinline" in our production environment, we discovered  a different issue, which might be not directly conected to the new features. Could you please have a look at it:

We generate endnotes and add spacing in between them with the reledmac command "\Xendbhooknote[B]{\vspace{1em}}", which produces the following output:
![output](https://cloud.githubusercontent.com/assets/12182347/10048975/cf4277f4-6215-11e5-9adc-0b12d2ef1c96.png)
There is a space between the two endnotes in line 10, which is the same as between all other notes 

We would like to reduce the space between the notes in the same line, so that it looks like that:
![desired_output](https://cloud.githubusercontent.com/assets/12182347/10048990/dbe610b0-6215-11e5-8d84-0d876b637b3c.png)

In the example above we used "\Xendinplaceofnumber[B]{\vspace{-2em}}". This produces the right output, but we get an error message "Illegal unit of measure (pt inserted). an.}}{B}{}". As stated in the documentation, "Xendinplaceofnumber" expects a length, not arbitrary code.

Is there a better way to add vertical space between endnotes and omit the space, if there are two or more endnotes in one line?

I tried to produce a kind of MWE:

\documentclass{scrartcl}
\usepackage[ngerman]{babel} 
\usepackage{reledmac}

% KOMMENTAR

%% Layout
\renewcommand*{\printnpnum}[1]{} %omits output of p.
\Xendbhooknote[A]{\vspace{1em}} %space between endnotes
\Xendnumberonlyfirstinline
\Xendlemmaseparator{:}
%\Xendafternumber{\newline} %should output newline after the line number; Error message "Illegal unit of measure (pt inserted). Wort1}{Kommentar1}{A}{}"
%\Xendinplaceofnumber[A]{\vspace{5em}} %changes vertical space between endnotes in the same line, Error message: Illegal unit of measure (pt inserted). Wort2}{Kommentar2}{A}{}

\begin{document}
	
	\beginnumbering
	
	
	\pstart
	\edtext{Wort1}{\Aendnote{Kommentar1}} und noch ein \edtext{Wort2}{\Aendnote{Kommentar2}}
	\newline
	Noch ein \edtext{Wort3}{\Aendnote{Kommentar3}} 
	\pend
	\endnumbering
	\newpage
	\doendnotes{A}
	
\end{document}

Could you please help us with that?
Thank you so much for all the effort, you are putting into this great package!

Best, 
Ingo

**Comment by maieul** [comment]
You have rightly analyzed the problem : these option should receipt only size, which are used to typeset horizontal space.

I could implement new tyools for adding arbitrary code before / after line number / place of number. What do you think about :
- Xendbhooklinenumber
- Xendahooklinenumber
- Xendbhookinplaceofnumber
- Xendahookinplaceofnumber

**Comment by ingoboerner** [comment]
Having the hooks would solve our problem, I think. "Xendb" .. is before, "Xenda.." after?  We would appreciate, if you could add the code. Thank you!

**Comment by maieul** [comment]
yes. Xendb -> before
I will look for it in next weeks� it should be ok...

**Comment by maieul** [comment]
ok, while rice cooking, I have implemented these four hooks. Look at the branch issue 411. Look especially on the syntax to ensure starting \vspace:

``````
\Xendbhooklinenumber{\endgraf\vspace{1cm}}
\Xendahooklinenumber{\endgraf}
\Xendbhookinplaceofnumber{\endgraf\vspace{0.5cm}}
``````

**Comment by ingoboerner** [comment]
Dear @maieul,
it works perfectly. Thank you very much!

**Comment by maieul** [comment]
please, let me close myself the issue. I have not yet documented the feature, and not added it in the main branch.

**Comment by ingoboerner** [comment]
OK, sorry

**Comment by ingoboerner** [comment]
Thanks!
