### ISSUE TITLE
Section dans apparat

### ISSUE THREAD

**Issue by Circeb** [maieul/ledmac#414]
Bonjour,

Y aurait-il un moyen de mettre le numéro de section dans l'apparat, exactement comme on peut mettre le numéro de pstart avec \Xpstart ? Ce serait notamment pratique si on choisit une numérotation de lignes par section.

Merci.

**Comment by maieul** [comment]
Le terme "section" �tant ambigu dans un contexte reledmac, pouvant signifier tant \section que \beginumbering, peux tu pr�ciser?
Dans tous les cas, il n'y a pas moyen directement maintenant, si ce n'est via le hook de notes (mais �a ne joue pas sur l'espacement)

**Comment by Circeb** [comment]
Je pensais à la \section. Le problème d'utiliser \Xbhooknote{\thesection } est 1) que le numéro de section apparait avant parafootsep, ce qui fait quelque chose comme 1 || 2, 1 étant le numéro de section, || le parafootsep et 2 le numéro de ligne ; 2) la section apparaît pour chaque note d'apparat, et ne prend donc pas en compte \Xnumberonlyfirstinline.

**Comment by maieul** [comment]
avant le parafootsep? quide alors de la premier note?

**Comment by Circeb** [comment]
La première note ne pose pas problème. Voilà ce à quoi ça ressemble dans mon apparat (les sections commencent par un T) : 
T1.5–6 οἱ φυσικοί] ἡ φυσική E T1. ∥7 τι λέγει om. E T1. ∥ καὶ DE : om. aF T2. ∥11–12 ἓν
εἶναι τὸ ὂν καὶ  κίνητον] ἓν καὶ τὸ ὂν καὶ τὸ κίνητον aF

**Comment by Circeb** [comment]
Avec 
\Xnumberonlyfirstinline
\Xparafootsep{ $\parallel$}
\Xbhooknote{\thesection .}

**Comment by maieul** [comment]
fournit moi un vrai MWE. L� je n'arrive pas � suivre

**Comment by Circeb** [comment]
\documentclass[12pt]{book}
\usepackage{reledmac}
\usepackage{reledpar}

\Xnumberonlyfirstinline
\Xparafootsep{ $\parallel$}
\Xbhooknote{\thesection .}
\renewcommand{\thesection}{\arabic{section}}
\Xarrangement[A]{paragraph}
\begin{document}

\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart[\section{gauche}]
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche \edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}}
\pend
\pstart[\section{gauche}]
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche \edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}}
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart[\section{droite}]
droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite 
\pend
\pstart[\section{droite}]
droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite 
\pend
\endnumbering
\end{Rightside}

\end{pages}
\Pages

\end{document}

**Comment by maieul** [comment]
donc tout marche ?

**Comment by Circeb** [comment]
Le rendu de l'apparat n'est pas bon : 
1. 5 gauche ] gauche 1. ∥9 gauche ] gauche 1. ∥ gauche ] gauche 2.
∥14 gauche ] gauche 2. ∥18 gauche ] gauche 2. ∥ gauche ] gauche

On attendrait :
1. 5 gauche ] gauche || 1. 9 gauche ] gauche || gauche ] gauche || 2. 14 gauche ] gauche || 2. 18 gauche ] gauche || gauche ] gauche

**Comment by maieul** [comment]
ok, je croyais que c'�tait cela que tu voulais. et du coup je trouvais la demande bizarre, d'o� ma question sur le premier num�ro. 

du coup il faudrait l'�quivalent du Xendbhooklinenumber pour les notes normales. Mais le pb c'est qu'on ne peut pas prendre Xbhooklinenumber, car cela signifierait l'insertion AVANT l'espace pr�s-notes et pas apr�s.

remarque l'autre solution pourrait �tre tout simplement de dire que le hook s'execute apr�s l'insertion du s�parateur...

**Comment by maieul** [comment]
@Circeb que penses tu de cette solution?

**Comment by Circeb** [comment]
Je n'arrive pas à compiler les fichiers.

**Comment by maieul** [comment]
heu, pour le moment je n'ai rien préparé du tout, donc normal que tu tu n'arrive à rien compilé. Ma question était : que penses tu des pistes de solution envisagé.

**Comment by Circeb** [comment]
Je ne suis pas sûre de ce à quoi ressemblerait la première solution. La seconde peut être bien ; il serait cependant mieux que le nom de section apparaisse seulement quand il y a un numéro de ligne, et prenne donc en compte \Xnumberonlyfirstinline.

**Comment by maieul** [comment]
bon, cela complique les choses. le coup de prendre en compte le \Xnumberonlyfirstinline(mais pas trop). Mon ordinateur est actuellement en panne. J'essaie de regarder celà la semaine prochaine, car il n'est pas très pratique pour moi de travailler sur l'ordinateur de remplacement.

**Comment by maieul** [comment]
ouf, enfin eu le temps de me pencher sur ce petit ajout. Donc la branche issue 414 propre desormais le hook \Xtxtbeforenumber. Voir le fichier 414.tex dans la branche pour un exemple. Merci de faire un retour, si possible rapidement.

**Comment by Circeb** [comment]
Ca m'a l'air de parfaitement marcher ! Merci !

**Comment by maieul** [comment]
ok, sera dans la prochaine release de reledmac, cette semaine, normalement.
