### ISSUE TITLE
latest version reledmac

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#416]
Cher ami j'ai fait l'upgrade de Latex et de reledmac. 
Pendant la compilation avec pdflatex j'ai maintenant:

! Undefined control sequence.
<recently read> \reserveinserts                                 
l.101 \reserveinserts
                     {32}

mais la compilation est normal. pourquoi ça?

Salutations, Enrico M.

**Comment by maieul** [comment]
quelle version exacte de reledmac ? quelle version de latex ? puis-je avoir le log?

sinon charger le package etex avant le package reledmac.

**Comment by heinrichffleck** [comment]
Voila mes versions:reledmac: v2.2.0, last revised 2015/09/29.

TeX Live 2015 versione 3.14159265-2.6-1.40.16 
 Salutations Enrico M.

=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Domenica 4 Ottobre 2015 17:39
 Oggetto: Re: [ledmac] latest version reledmac (#416)
   
quelle version exacte de reledmac ? quelle version de latex ? puis-je avoir le log?

sinon charger le package etex avant le package reledmac.—

**Comment by maieul** [comment]
merci de m'envoyer aussi le fichier de log. 
Je ne comprend pas que vous ayziez ce bug, normalement r�solu depuis bel luret.

me fournir �galement votre MWE

**Comment by heinrichffleck** [comment]
Cher ami tres merci. Voci le file log e le file .tex aussi long pour un MWE.
A bientot, salutations, Enrico M.


=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Domenica 4 Ottobre 2015 17:58
 Oggetto: Re: [ledmac] latest version reledmac (#416)
   
merci de m'envoyer aussi le fichier de log. 
Je ne comprend pas que vous ayziez ce bug, normalement r�solu depuis bel luret.

me fournir �galement votre MWE—

**Comment by heinrichffleck** [comment]
A integration de ma mail je m'oubliè de vous dire que j'ai sur la premiere page de fichier pdf le numeber 32:
comme da \reserveinserts
                     {32}
salutations, Enrico M.

=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Domenica 4 Ottobre 2015 17:58
 Oggetto: Re: [ledmac] latest version reledmac (#416)
   
merci de m'envoyer aussi le fichier de log. 
Je ne comprend pas que vous ayziez ce bug, normalement r�solu depuis bel luret.

me fournir �galement votre MWE—

**Comment by maieul** [comment]
les fichiers ne sont pas joints...

**Comment by heinrichffleck** [comment]
Cher ami de quelque jour j'ai des problem avec les  fichier attaché en yahoo.
J'ai telechargé les fiches via dropbox a cettes address ici:
Psammites-Arenario.tex
|   |
|   |  |   |   |   |   |   |
| Psammites-Arenario.texCondiviso con Dropbox |
|  |
| Visualizza su www.dropbox.com | Anteprima per Yahoo |
|  |
|   |


 https://www.dropbox.com/s/m14uoztmlooxarh/Psammites-Arenario.log?dl=0
Regardez-vous la premiere page du fichier PDF apres une compilation avec pdflatex. Moi je crois que le probleme n'esta pas dans reledmac parce que j'ai sur un autre ordinateur la meme derniere version de reledmac et elle marche bien.

Salutations, Enrico Macchia

     Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Lunedì 5 Ottobre 2015 9:18
 Oggetto: Re: [ledmac] latest version reledmac (#416)
   
les fichiers ne sont pas joints...—

**Comment by maieul** [comment]
Mettez 
\RequirePackage{etex}
\reserveinserts{40}

avant votre \documenclass.

Je contacte l'�quipe de latex pour comprendre ce qu'ils ont encore chang�...

**Comment by heinrichffleck** [comment]
Je l'ai fait mais c'est le kaos total: rien marche, pas de compilation.
Salutations, Enrico M.
 
=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Lunedì 5 Ottobre 2015 10:57
 Oggetto: Re: [ledmac] latest version reledmac (#416)
   
Mettez 
\RequirePackage{etex}
\reserveinserts{40}

avant votre \documenclass.

Je contacte l'�quipe de latex pour comprendre ce qu'ils ont encore chang�...—

**Comment by maieul** [comment]
pouvez vous me fournir votre MWE? là je ne peux RIEN faire.

**Comment by heinrichffleck** [comment]
Pardon!PARDON! Je m'etais trompé: il marche. salutations, Enrico
 
=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Lunedì 5 Ottobre 2015 10:57
 Oggetto: Re: [ledmac] latest version reledmac (#416)
   
Mettez 
\RequirePackage{etex}
\reserveinserts{40}

avant votre \documenclass.

Je contacte l'�quipe de latex pour comprendre ce qu'ils ont encore chang�...—

**Comment by maieul** [comment]
la version 2.2.1, que je vais envoyer sous peu sur le CTAN, corrige définitivement ce bug. Il faudra alors supprimer le 
\RequirePackage{etex}
\reserveinserts{40}

**Comment by heinrichffleck** [comment]
Merci pour votre aide. J'ai encore des problemes (\edlineref avec reledpar n'indique pas le nombre de line exact) mais ça plus tard quand j'aurais terminé mon travaille, à la fin.
Encore merci et salutations Enrico M.
 
=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Lunedì 5 Ottobre 2015 13:41
 Oggetto: Re: [ledmac] latest version reledmac (#416)
   
la version 2.2.1, que je vais envoyer sous peu sur le CTAN, corrige définitivement ce bug. Il faudra alors supprimer le 
\RequirePackage{etex}
\reserveinserts{40}—
