### ISSUE TITLE
pas de rejet de vers au 1er vers

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#418]
soulevé par @enimie. Valable dès la 1ere version de ledmac (enfin la première que j'ai récupéré)
`````
\documentclass[a4paper, oneside, notitlepage, 12pt]{article} 
\usepackage{fontspec}
\usepackage{xunicode}
\usepackage{polyglossia}
\setmainlanguage{french}
\usepackage[]{reledmac}

\begin{document}
\makeatletter


\setstanzaindents{14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0} %
\beginnumbering
\stanza


La deuxième sorte de tristesse est celle qu'engendrent la passion et la confusion de l'esprit,&
La deuxième sorte de tristesse est celle qu'engendrent la passion et la confusion de l'esprit,&
Et la paresse nuisible : elle n'a rien à voir avec la raison.&
Cette tristesse-là ne purifie pas l'âme mais la trouble d'un tourbillonnement impie:&
Elle peut la troubler, mais non la nettoyer.&
L'anxiété l'entretient, le désespoir l'engendre&
Et la nourrit du fleuve de son lait noir.\&

\endnumbering

\end{document}
`````

**Comment by maieul** [comment]
bon @enimie en fait le pb vient du fait que tu met des lignes vides après le \stanza.

C'est mal ! parce que c'est comme si tu mettez des sauts de paragraphe au sein de tes vers. Donc non seulement cela pourrit le rejet de vers, mais en plus cela t'insère des espaces verticaux indésirables :(. 

Je corrige parce que c'est sans doute une erreur fréquente. Mais c'est mal :(

**Comment by Enimie** [comment]
oh pardon.... je suis contrite... :-(

**Comment by maieul** [comment]
bah, ce n'est pas très grave. C'était du reste je pense un bug, car ledmac n'aurais jamais du permettre d'avoir des paragraphes dans des vers.
