### ISSUE TITLE
deux linéations différentes sur un même texte

### ISSUE THREAD

**Issue by Enimie** [maieul/ledmac#419]
Coucou,

Crois-tu qu'il serait possible d'avoir deux linéations différentes du même texte? J'ai par ex. un poème dont le premier vers est le 257eme de l'édition précédente, et je voudrais pouvoir faire apparaître, en plus de la numérotation normale de mes vers, celle de cet éditeur, entre parenthèses par exemple... 

Enimie

**Comment by maieul** [comment]
le d�calage est constant ?

**Comment by Enimie** [comment]
Oui: c'est juste que j'édite comme deux poèmes ce que l'ancien éditeur considère comme un seul. Comme c'est des vers, le décalage reste toujours le même.

**Comment by maieul** [comment]
bon, c'est un cas qui doit pas �tre tr�s fr�quent, donc j'h�site � impl�menter un m�canisme g�n�rique.

mais tu peux patcher la commande \ledlinenum

````
\patchcmd{\ledlinenum}
  {\linenumrep{\line@num}}
  {%
    \numdef{\decal}{\line@num+22}%
    \linenumrep{\line@num}
    (\linenumrep{\decal})%
  }%
  {}
  {}
````` 
(l� il y 22 num�ro d'�cart, mais tu peux �videmment changer�)

**Comment by maieul** [comment]
(évidememnt en entre \makeatletter / \makeatother ou dans un .sty). Par contre si c'est juste un poeme, tu  va sans doute devoir faire plutot

\newcommand{\afficheoriginal}{\numdef{\decal}{\line@num+22} (\linenumrep{\decal})}

\patchcmd{\ledlinenum}
  {\linenumrep{\line@num}}
  {%
    \linenumrep{\line@num}
    \afficheoriginal
  }%
  {}
  {}

pour ensuite faire un \let\afficheoriginal\relax après ton poeme et recommancer l'affichage normal

**Comment by Enimie** [comment]
J'ai ca pour deux ou trois poèmes...
Je n'avais  sans doute pas bien compris ta question sur le décalage, je pense..

Avec le patch que tu propose j'obtiens :

un vers
un vers
un vers
un vers
un vers   5 (263)
un vers
un vers
un vers
un vers
un vers   10 (268)

etc... (c'est déjà bien je trouve . mais...)
J'aimerais obtenir: 

un vers
un vers   (260)
un vers
un vers
un vers   5 
un vers
un vers  (265)
un vers
un vers
un vers   10

etc; c'est à dire vraiment une deuxième linéation...

**Comment by maieul** [comment]
arg ! l� c'est plus dur ;(

**Comment by maieul** [comment]
tu les affiche toutjours du m�me c�t� tes num�ro de ligne ?

**Comment by maieul** [comment]
avec ceci tu devrais avoir ton bonheur (si tu affiche les numéro de bvers à gauche)

`````
\makeatletter
\newcount\decal
\decal=22
\renewcommand{\do@insidelinehook}{%
\global\advance\decal by 1%
          %Calcul un peu compliqué pour obtenir un modulo et s'assurer de n'afficher que tout les N lignes
          \@l@dtempcntb=\decal
          \@l@dtempcnta=\decal
          \advance\@l@dtempcnta by-\c@firstlinenum
          \divide\@l@dtempcnta by\c@linenumincrement
          \multiply\@l@dtempcnta by\c@linenumincrement
          \advance\@l@dtempcnta by\c@firstlinenum
\ifnum\@l@dtempcnta=\@l@dtempcntb
  \llap{\numlabfont(\the\decal)\kern\linenumsep}%
\fi
}
`````

**Comment by Enimie** [comment]
Hmm... 

J'avais laissé le linenummargin par défaut -censément left? mais j'ai en fait la numérotation sur les marges extérieures. J'ai essayé avec \linenummargin{left}, mais ça reste dans les marges extérieures  (alors que  \linenummargin{right} passe bien tout à droite). dans tous les cas, je reste avec la numérotation normale..

**Comment by maieul** [comment]
hum. je comprend pas. c'est un autre probl�me non ? tu me dis que le syst�me de \linenummargin ne marche pas ? si oui peux tu ouvrir un ticket avec des exemples ?

**Comment by Enimie** [comment]
en fait moi ça m'est égal d'avoir ma numérotation sur les marges extérieures. C'est juste que tu disais qu'il fallait que j'affiche les numéros à gauche pour que ca marche - or je n'arrive pas à afficher les numéros à gauche (je t'envoie un exemple ds qq minutes)

**Comment by maieul** [comment]
non, ca peut marcher aussi � droite, juste faut que je modifie legerement le code ;-)

**Comment by Enimie** [comment]
Rectification.
Ca marche parfaitement bien (et la double numérotation aussi) quand je suis en texte que d'un côté.
Quand je passe en vis-à_s, en fait j'arrive à mettre ma numérotation à gauche (j'avais pas placé linenummargin{left} au bon endroit, mais  dans ce cas, la double numérotation ne fonctionne plus.

je te joins un exemple avec du vis a vis (attetion,le \& ne passe pas en preview)
 
<latex>
\documentclass[a4paper, oneside, notitlepage, 12pt]{article} 
\usepackage{fontspec}
\usepackage{xunicode}
\usepackage{polyglossia}
\setmainlanguage{french}
\usepackage[noend,noeledsec,noledgroup]{reledmac}
\usepackage[advancedshiftedpstarts]{reledpar}
\sethangingsymbol{[\,}


\linenummargin{left}

\makeatletter

\newcount\decal
\decal=22

\renewcommand{\do@insidelinehook}{%
\global\advance\decal by 1%
         \@l@dtempcntb=\decal
          \@l@dtempcnta=\decal
          \advance\@l@dtempcnta by-\c@firstlinenum
          \divide\@l@dtempcnta by\c@linenumincrement
          \multiply\@l@dtempcnta by\c@linenumincrement
          \advance\@l@dtempcnta by\c@firstlinenum
\ifnum\@l@dtempcnta=\@l@dtempcntb
  \llap{\numlabfont(\the\decal)\kern\linenumsep}%
\fi
}
\begin{document}


\begin{pages}
\begin{Leftside}
\setstanzaindents{14,0,0} %
\setcounter{stanzaindentsrepetition}{2}
\beginnumbering 
\stanza


La deuxième sorte de tristesse est celle qu'engendrent la passion et la confusion de l'esprit,&
Et la paresse nuisible : elle n'a rien à voir avec la raison.&
Cette tristesse-là ne purifie pas l'âme mais la trouble d'un tourbillonnement impie:&
Elle peut la troubler, mais non la nettoyer.&
L'anxiété l'entretient, le désespoir l'engendre&
Et la nourrit du fleuve de son lait noir.&
La deuxième sorte de tristesse est celle qu'engendrent la passion et la confusion de l'esprit,&
Et la paresse nuisible : elle n'a rien à voir avec la raison.&
Cette tristesse-là ne purifie pas l'âme mais la trouble d'un tourbillonnement impie:&
Elle peut la troubler, mais non la nettoyer.&
L'anxiété l'entretient, le désespoir l'engendre&
Et la nourrit du fleuve de son lait noir \&

\endnumbering
\end{Leftside}

\begin{Rightside}
\setstanzaindents{14,0,0} %
\setcounter{stanzaindentsrepetition}{2}
\beginnumbering \linenummargin{left}
\stanza
La deuxième sorte de tristesse est celle qu'engendrent la passion et la confusion de l'esprit,&
Et la paresse nuisible : elle n'a rien à voir avec la raison.&
Cette tristesse-là ne purifie pas l'âme mais la trouble d'un tourbillonnement impie:&
Elle peut la troubler, mais non la nettoyer.&
L'anxiété l'entretient, le désespoir l'engendre&
Et la nourrit du fleuve de son lait noir.&
La deuxième sorte de tristesse est celle qu'engendrent la passion et la confusion de l'esprit,&
Et la paresse nuisible : elle n'a rien à voir avec la raison.&
Cette tristesse-là ne purifie pas l'âme mais la trouble d'un tourbillonnement impie:&
Elle peut la troubler, mais non la nettoyer.&
L'anxiété l'entretient, le désespoir l'engendre&
Et la nourrit du fleuve de son lait noir \&

\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
<\latex>

**Comment by maieul** [comment]
a oui, c'est encore ce système absurde qui fait que pour changer un réglage de numérotation concernant la page de droite il faut être dans rightside, et qu'on peut pas le faire en preambule. cf #420. J'avais deja changé pour deux trois choses, mais pas la marge.

pour en revenir au problème du présent billet j'ai besoin d'y voir plus clair : 
- de quel côté as tu besoin de la double numérotation ?
- sur quelle marge ?

**Comment by Enimie** [comment]
En soi ça m'est égal. Disons de préférence la page de gauche, c'est là que je met mon texte latin.
Je suis sur la marge exterieure.

**Comment by maieul** [comment]
page de gauche + marge exterieur = marge de gauche. > cela devrait être bon avec le code que je t'ai fournit non ?

**Comment by maieul** [comment]
a non, je sais, cela ne peut pas marcher parce que le do@insidelinehook n'est pas implémenté en reledpar. Bon ca devrait pas être long, mais je ferais cela demain.

**Comment by Enimie** [comment]
Ok
Merci beaucoup en tout cas... (si un jour je finis ma thèse, tu seras dans les remerciements :-) )

**Comment by maieul** [comment]
bon, j'ai bien fait d'attendre aujourd'hui. En fait insidelinehook est implémenté, mais avec un nom différent en reledpar. Par ailleurs, j'ai pus constater que la version 1.15.0 de eledepar avait fait sauté les rejets de vers. Et j'ai pu corrigé. J'ai également pu implémenter #420. 

Bref si tu regarde la branch issue #419 tu pourra obtenir:
- les fichiers .sty corrigés 
- un exemple pour ton histoire de vers décalé

**Comment by Enimie** [comment]
Cela marche très bien, à un détail près: si la seconde  numérotation  tombe sur un vers avec rejet (dans l'exemple, le troisième vers), le numéro du vers apparait deux fois: une fois à sa place normale, une fois à côté du crochet devant le rejet.

**Comment by maieul** [comment]
la nouvelle version de la branche corrige cela. J'ai également légèrement optimisé le code.

Ps : http://www.brepolsonline.net/doi/10.1484/J.ASR.5.107504. tout content ...

**Comment by Enimie** [comment]
ouais, super la publication chez brepols!

**Comment by maieul** [comment]
oui, je suis assez content. Ca a quand même été assez long à publier. As tu pu tester la nouvelle version de la branche ?

**Comment by Enimie** [comment]
Ca marche!
Merci beaucoup!

**Comment by maieul** [comment]
ok, bon je clos cette issue.
