### ISSUE TITLE
bidi 17.9 perturbent les notes paragraphées

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#421]
Voici un mwe sans langue arabe dans le document. Tel qu'il est, tout va bien.

Mais si on active `\setotherlanguage{arabic}` ou bien `\usepackage{arabxetex}`, ou bien les deux, rien ne va plus. D'énormes espaces se glissent entre les notes, et aussi avant les notes.

Cette fois, je n'ai même pas eu besoin de mettre des mots arabes, cher Maïeul ;)

````
\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{xltxtra,xunicode,amsmath}

\usepackage{polyglossia}
\setdefaultlanguage{french}

\usepackage[series={A,B}]{reledmac}
\Xarrangement[A,B]{paragraph}

%% Au choix, on peut ici décommenter:
% 1. soit la ligne \setotherlanguage{arabic} (polyglossia)
% 2. soit la ligne \usepackage{arabxetex} (arabxetex)
% 3. soit les deux
% ... et cela donne des espaces énormes entre les notes.
%\setotherlanguage{arabic}
%\usepackage{arabxetex}

\let\aemph\veryundefinedcommand

\begin{document}

\beginnumbering

\pstart

\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.

\pend

\endnumbering

\end{document}
````

**Comment by ralessi** [comment]
Remarque: j'ai vu que `bidi` a été mis à jour tout récemment. Je suis donc revenu à la version précédente, et le problème a disparu. Le bug est donc peut-être dans `bidi`.

**Comment by maieul** [comment]
qu'est ce que cela donne sur des notes standards ?  (no reledmac)

**Comment by ralessi** [comment]
Un document simple avec des `\footnote{}` passe sans perturber les notes. Mais ce ne sont pas des notes paragraphées. Il faudrait essayer avec `bigfoot`, non?

Exemple:
````
\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{xltxtra,xunicode,amsmath}

\usepackage{polyglossia}
\setdefaultlanguage{french}

%% Au choix, on peut ici décommenter:
% 1. soit la ligne \setotherlanguage{arabic} (polyglossia)
% 2. soit la ligne \usepackage{arabxetex} (arabxetex)
% 3. soit les deux
% ... et cela donne des espaces énormes entre les notes.
\setotherlanguage{arabic}
%\usepackage{arabxetex}

\let\aemph\veryundefinedcommand

\begin{document}

Jean a vu\footnote{de ses yeux} Paul hier. Jean a vu\footnote{de ses
  yeux} Paul hier. Jean a vu\footnote{de ses yeux} Paul hier. Jean a
vu\footnote{de ses yeux} Paul hier. Jean a vu\footnote{de ses yeux}
Paul hier. Jean a vu\footnote{de ses yeux} Paul hier.

\end{document}
````

**Comment by maieul** [comment]
ah, j'avais pas lu que c'�tait en notes paragraph�es (pas eu le tps de tester, je m'occupe de #420 et #419). Oui il faudrait tester avec bigfoot

**Comment by ralessi** [comment]
Ok je fais cela dans un petit moment.

**Comment by ralessi** [comment]
Ceci passe sans erreur avec `bigfoot`:
````
\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{xltxtra,xunicode,amsmath}

\usepackage{polyglossia}
\setdefaultlanguage{french}

\usepackage[para]{bigfoot}
\DeclareNewFootnote[para]{A}

%% Au choix, on peut ici décommenter:
% 1. soit la ligne \setotherlanguage{arabic} (polyglossia)
% 2. soit la ligne \usepackage{arabxetex} (arabxetex)
% 3. soit les deux
% ... et cela donne des espaces énormes entre les notes.
\setotherlanguage{arabic}
%\usepackage{arabxetex}

\let\aemph\veryundefinedcommand

\begin{document}

Jean a vu\footnoteA{de ses yeux} Paul hier. Jean a vu\footnoteA{de ses
  yeux} Paul hier. Jean a vu\footnoteA{de ses yeux} Paul hier. Jean a
vu\footnoteA{de ses yeux} Paul hier. Jean a vu\footnoteA{de ses yeux}
Paul hier. Jean a vu\footnoteA{de ses yeux} Paul hier.

\end{document}
````

**Comment by maieul** [comment]
ok. bon alors on va essaer de regarder cela rapidement. 
peux tu me donner les r�sultats d'un \listfiles sur les fichiers qui posent probl�me, histoire de partir sur des bonnes base de test

**Comment by ralessi** [comment]
Voici:
````
polyglossia.sty    2015/08/06 v1.42.0 Alternative to Babel for XeLaTeX and LuaL
aTeX
reledmac.sty    2015/10/09 v2.2.2 typeset critical edition
gloss-arabic.ldf    polyglossia: module for arabic
    bidi.sty    2015/10/08 v17.8 Bidirectional typesetting in plain TeX and LaT
eX
biditools.sty    2015/10/03 v0.6 Programming tools for bidi package
latex-xetex-bidi.def    2015/10/08 v1.2.0 bidi adaptations for `latex.ltx' for 
XeTeX engine
footnote-xetex-bidi.def    2013/04/26 v0.8 bidi footnote macros for XeTeX engin
e
article-xetex-bidi.def    2010/07/25 v0.4 bidi adaptations for standard article
 class for XeTeX engine
amsmath-xetex-bidi.def    2014/09/04 v0.9 bidi adaptations for amsmath package 
for XeTeX engine
amstext-xetex-bidi.def    2013/04/04 v0.1 bidi adaptations for amstext package 
for XeTeX engine
graphicx-xetex-bidi.def    2012/01/01 v0.4 bidi adaptations for graphicx packag
e for XeTeX engine
ragged2e-xetex-bidi.def    2010/07/25 v0.2 bidi adaptations for ragged2e packag
e for XeTeX engine
loadingorder-xetex-bidi.def    2013/05/22 v0.95 making sure that bidi is the la
st package loaded
arabicnumbers.sty    2010/03/18 v0.2 Formatting of Arabic and Farsi digits and 
of Arabic abjad numerals
hijrical.sty    2010/07/12 v0.2 Islamic calendar
````

**Comment by ralessi** [comment]
Dans le `\listfiles` ci-dessus, je n'ai pas chargé `arabxetex` car il est clair que le bug n'est présent qu'avec la dernière version de `bidi`, quel que soit ce bug. Peut-être qu'un bisect sur bidi nous montrerait ce qui s'est passé?

**Comment by maieul** [comment]
tr�s certainement. reste � trouver le repos de bidi ;-)

**Comment by ralessi** [comment]
Attends, je suis en train de faire le diff.

**Comment by maieul** [comment]
de toute facon j'ai d'autres bugs en cours de correction, dont un tr�s important #422

**Comment by ralessi** [comment]
Celui-ci peut en effet attendre #422. Voici en tout cas le diff:
````
--- texmf/tex/xelatex/bidi/latex-xetex-bidi.def	2015-10-04 01:11:07.000000000 +0200
+++ /usr/local/texlive/2015/texmf-dist/tex/xelatex/bidi/latex-xetex-bidi.def	2015-10-08 22:41:20.000000000 +0200
@@ -17,7 +17,7 @@
 %%   by Vafa Khalighi.
 %% 
 %% 
-%% \CheckSum{44780}
+%% \CheckSum{44655}
 %% \CharacterTable
 %%  {Upper-case    \A\B\C\D\E\F\G\H\I\J\K\L\M\N\O\P\Q\R\S\T\U\V\W\X\Y\Z
 %%   Lower-case    \a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u\v\w\x\y\z
@@ -34,11 +34,11 @@
 %%   Grave accent  \`     Left brace    \{     Vertical bar  \|
 %%   Right brace   \}     Tilde         \~}
 %%
-\ProvidesFile{latex-xetex-bidi.def}[2015/02/01 v1.1.9 bidi adaptations  for `latex.ltx' for XeTeX engine]
+\ProvidesFile{latex-xetex-bidi.def}[2015/10/08 v1.2.0 bidi adaptations  for `latex.ltx' for XeTeX engine]
 \newcommand{\TeXXeTOn}{\TeXXeTstate=1 }
 \newcommand{\TeXXeTOff}{\TeXXeTstate=0 }
 \TeXXeTOn
-\def\bidi@RTL@everypar{\if@RTL{\setbox\z@\lastbox\beginR\ifvoid\z@\else\usebox\z@\fi}\fi}
+\def\bidi@RTL@everypar{{\setbox\z@\lastbox\if@RTL\beginR\else\beginL\fi\ifvoid\z@\else\usebox\z@\fi}}
    \let\bidi@o@everypar=\everypar
    \newtoks\bidi@n@everypar
    \bidi@n@everypar\expandafter{\the\bidi@o@everypar}
@@ -80,12 +80,12 @@
   \bgroup
   \aftergroup\egroup
  }\vbox}
-\def\LTR{\par\@RTLfalse\@RTL@footnotefalse\if@bidi@list@minipage@parbox\beginL\else\if@RTLtab\beginL\fi\fi\hsize\linewidth\parshape\z@}
+\def\LTR{\par\@RTLfalse\@RTL@footnotefalse\hsize\linewidth\parshape\z@}
 \def\endLTR{\par}
 \def\RTL{\par\@RTLtrue\@RTL@footnotetrue\hsize\linewidth\parshape\z@}
 \def\endRTL{\par}
 \def\setRTL{\@RTLtrue\@RTL@footnotetrue}
-\def\setLTR{\@RTLfalse\@RTL@footnotefalse\if@bidi@list@minipage@parbox\beginL\else\if@RTLtab\beginL\fi\fi}
+\def\setLTR{\@RTLfalse\@RTL@footnotefalse}
 \let\unsetRTL=\setLTR
 \let\unsetLTR=\setRTL
 \let\LR=\LRE
@@ -174,68 +174,6 @@
   \fi\fi\fi
   \parshape \@ne \@totalleftmargin \linewidth
   \ignorespaces}
-\def\@item[#1]{%
-  \if@noparitem
-    \@donoparitem
-  \else
-    \if@inlabel
-      \indent \par
-    \fi
-    \ifhmode
-      \unskip\unskip \par
-    \fi
-    \if@newlist
-      \if@nobreak
-        \@nbitem
-      \else
-        \addpenalty\@beginparpenalty
-        \addvspace\@topsep
-        \addvspace{-\parskip}%
-      \fi
-    \else
-      \addpenalty\@itempenalty
-      \addvspace\itemsep
-    \fi
-    \global\@inlabeltrue
-  \fi
-  \everypar{\if@bidi@list@minipage@parbox\if@RTL\else\beginL\fi\else\if@RTLtab\if@RTL\else\beginL\fi\fi\fi%
-    \@minipagefalse
-    \global\@newlistfalse
-    \if@inlabel
-      \global\@inlabelfalse
-      {\setbox\z@\lastbox
-       \ifvoid\z@
-         \kern-\itemindent
-       \fi}%
-      \box\@labels
-      \penalty\z@
-    \fi
-    \if@nobreak
-      \@nobreakfalse
-      \clubpenalty \@M
-    \else
-      \clubpenalty \@clubpenalty
-      \everypar{}%
-    \fi}%
-  \if@noitemarg
-    \@noitemargfalse
-    \if@nmbrlist
-      \refstepcounter\@listctr
-    \fi
-  \fi
-  \sbox\@tempboxa{\makelabel{#1}}%
-  \global\setbox\@labels\hbox{%
-    \unhbox\@labels
-    \hskip \itemindent
-    \hskip -\labelwidth
-    \hskip -\labelsep
-    \ifdim \wd\@tempboxa >\labelwidth
-      \box\@tempboxa
-    \else
-      \hbox to\labelwidth {\unhbox\@tempboxa}%
-    \fi
-    \hskip \labelsep}%
-  \ignorespaces}
 \long\def\@iiiparbox#1#2[#3]#4#5{%
   \leavevmode
   \@pboxswfalse
````

**Comment by maieul** [comment]
c'est bien cette ligne qui pose problème. reste à savoir pq.

**Comment by maieul** [comment]
ok, bon apparement il semblerait que cette mise à jour de bidi casse pas mal de chose. voir aussi par exemple https://github.com/persian-tex/bidi/issues/3.

Donc j'ai demandé avis. On verra.

**Comment by ralessi** [comment]
Merci. J'étais persuadé que le bug était là.

**Comment by maieul** [comment]
oui. j'avoue que pour le moment cela reste assez obscure, dans les tréfond du XeTeX. Donc attendons le retour de vafa, qui semble réagir vite aux tickets. En plus là il y en a deux sur le même sujet alors :-)

**Comment by maieul** [comment]
bon, Vafa me dit "c'est normal que c'est cassé, il faut changer (r)(e)ledmac, et si il y a un bug ce n'est pas la faute à bidi". Mais il ne dit pas comment changer eledmac. Et franchement vu la nature du problème, et surtout vu que je ne comprend que pouic aux système RTL de XeTeX, je ne vais pas perdre de temps à chercher maintenant. Apparemment cela a cassé aussi quelque chose chez lui, donc peut être qu'il va pouvoir m'expliquer les modifications à faire.

**Comment by ralessi** [comment]
Oui, j'ai vu passer la réponse! Vivement luatex! En attendant...  attendons. De mon côté, j'ai remis l'ancienne définition et je peux continuer à travailler normalement.

Le fait est que le système bidirectionnel de xetex est plutôt primitif. Rien à voir avec le système natif de luatex hérité d'Omega.

**Comment by maieul** [comment]
je t'avoue que je n'ai pas encore en tête tout les aspects de ces questions bidirectionels. Et LuaTeX m'a aussi donné du fil à retordre....

**Comment by maieul** [comment]
Je compte publié ce message sur mon carnet, parce que c'est un bug assez sérieux.

"This is an emergency message. The release 17.9 of bidi, which corrected one bug, have broken paragraphed notes of ledmac, eledmac and reledmac.

Vafa Khalighi, the maintenor of bidi package, is looking to a solution. Please don’t update bidi before the solution will be found."

Qu'en pense tu ?

**Comment by ralessi** [comment]
Je vois passer tous les messages envoyés par Vafa, et je ne doute pas que tout va s'arranger.

Bonne idée pour ce message, c'est nécessaire. Une autre possibilité serait de mettre un petit bidipatch.sty car je ne suis pas certain que tout le monde sache comment faire pour bloquer l'update de bidi. Mais je me trompe peut-être.

**Comment by maieul** [comment]
evidement, si les gens font des tlmgr update --all ils ne peuvent pas.

Je ne doute pas non plus que cela va s'arranger. Je pr�f�re cependant �viter de conseiller un patch qui risque de rester apr�s coup et de bloquer les corrections de bidi.

hop, publi�.

http://geekographie.maieul.net/187

**Comment by ralessi** [comment]
tlmgr update --all, c'est ce que je fais tous les matins après le café!

Mais tu as raison: on ne pense pas toujours à supprimer un patch.

**Comment by maieul** [comment]
disons que si une personne fait cela, elle doit en �tre consciente...

**Comment by ralessi** [comment]
Exact. J'ai pris cette habitude, car elle me permet de voir plus vite les difficultés quand elles apparaissent. Et c'est aussi une façon de suivre l'actualité, par exemple quand on voit passer un package qu'on ne connaît pas...

**Comment by maieul** [comment]
personnellement je m'abonne � la liste du ctan pour suivre l'actualit�� mais chacun proc�de comme il veut.

**Comment by ralessi** [comment]
Donc tu ne travailles pas forcément avec les versions les plus récentes du ctan?

**Comment by maieul** [comment]
non. j'aime savoir ce que je fais, donc je lis les informations envoy�s par les auteurs lors de la mise � jour.

**Comment by ralessi** [comment]
D'où la demande du \listfiles dans ce ticket. Le risque est que le changement de version de texlive soit violent, au moins une fois par an!

**Comment by maieul** [comment]
oui, mais dans ton cas il faut v�rifier apr�s chaque tlmgr que rien n'est cass�.

**Comment by ralessi** [comment]
C'est vrai, mais je le prends comme un bon exercice. Je suis passé à cette façon de travailler après avoir adopté pour mon système Linux le principe de la «rolling release». Parfois, une mise à jour casse un peu le système. Le mois dernier, c'était carrément le noyau. Mais cela permet d'enquêter à grand coups de git bisect, et de faire remonter les erreurs quand il y en a.  

J'y vois deux avantages: 1. rester toujours en prise directe 2. plus jamais de mise à jour majeure!

Mais il est vrai que pour texlive c'est un peu différent.

**Comment by maieul** [comment]
peux tu tester la branche issue421 ?

**Comment by ralessi** [comment]
C'est bon!

**Comment by maieul** [comment]
ok. bon je vais du coup pr�parer les paquet ce soir. Heureusement j'avais deux trois autres trucs � sortir.

**Comment by ralessi** [comment]
Merci. En ce moment c'est intense!

**Comment by maieul** [comment]
tr�s...
ce qui n'est pas vraiment pour m'arranger, � vrai dire. J'ai eu � traduire un texte d'Andr� de Cr�te (huiti�me si�cle) et il n'a pas un grec des plus communs, tant dans le vocabulaire que dans la syntaxe...

**Comment by ralessi** [comment]
Des vers ou de la prose? Oui, c'est vraiment très difficile. Je le mesure pour les auteurs médicaux, car je travaille à partir d'Hippocrate. Et ensuite, partant d'Hippocrate en passant par Galien, on a vite un bon millier d'années de langue grecque...

**Comment by maieul** [comment]
de la prose, heureusement. Mais l'auteur est connu pour �crire des vers par ailleurs, et je me demande si cela ne joue pas aussi parfois dans les constructions.

Surtout que pour moi le seul grec auquel je suis vraiment form� c'est celui du Nouveau Testament. Du coup je me retrouve � devoir me reformer au grec classique ET byzantins en m�me temps...

**Comment by ralessi** [comment]
Il est bien possible qu'il soit influencé. Pour la formation aux langues, on n'a jamais fini!

**Comment by maieul** [comment]
les langues ont ceci de commun avec  TeX�
bon sur ce je finis la publication sur le ctan de ce correctif, en trois branches diff�rentes

**Comment by ralessi** [comment]
Merci!
