### ISSUE TITLE
Change separator between line numbers on certain footnotes only

### ISSUE THREAD

**Issue by ingoboerner** [maieul/ledmac#424]
Dear @maieul,
the problem, as described in https://github.com/maieul/ledmac/issues/252

As @mepherl explained in the other issue, that we have to distinguish between two separators in the line number: "–" and "/"

Until now, we only had the case, in which we changed it globally. But in a forthcoming volume we have to use both separators in one document:

We have to output something like this:

114f. hin und herführen. . . . .] hin und her fahren. . . . . MzN
201/202 Absatztrennung fehlt
513-515 von der Decke […] durch den Kopf] fehlt EA GW 

As a MWE:

\documentclass{scrartcl}
\usepackage[ngerman]{babel} 
\usepackage{reledmac}

\Xtwolines{f.}
\Xmorethantwolines{ff.}

%\renewcommand{\endashchar}{/} %Change the separator globally

%Manipulate line number: \linenum{|4|||7|||}, eg. \edtext{First line of text and\newline second line of text.}{\linenum{|4|||/5|||}\lemma{First line [\dots] second line of text.}\Afootnote[fulllines]{Text of footnote}} 
%There is no way, to change the separator...

\begin{document}
	
	\beginnumbering
	

	\pstart
	\edtext{First line of text,\newline second line of text and \newline third line of text.}{\lemma{First line [\dots] third line of text.}\Afootnote[fulllines]{Text of footnote 1}} 
	\pend
	
	
	\pstart
	\edtext{First line of text and\newline second line of text.}{\lemma{}\lemma{}\Afootnote[fulllines, nosep]{Text of footnote 2}} 
	\pend
	
	
	\pstart
	\edtext{First line of text,\newline second line of text and \newline third line of text.}{\lemma{First line [\dots] third line of text.}\Afootnote{Text of footnote 3}} 
	\pend
	\endnumbering
	\newpage
	\doendnotes{A}
	
\end{document}

In the second footnote I would like to change the separator from "–" to "/".

Thanks!
Best, Ingo

**Comment by maieul** [comment]
you mean the separator in a range of page ?

**Comment by ingoboerner** [comment]
In the MWE the first part outputs a footnote:

1–3 First line [...]

I would need the second one to output

4/5 Text of footnote 2

**Comment by ingoboerner** [comment]
With  \linenum{|4|||7|||} i could manipulate the line numbers, but not the separator. I didn't find another option in the documentation to change it.

**Comment by maieul** [comment]
indeed, you can't change by this way.

plan is 

1) first integrate a tools to change the separator globaly with \renewcommand (because it is a deprecated way)
2) then integrate a tools to change it locally.

It should not be complex. Just require to have time for this.

**Comment by ingoboerner** [comment]
Thank you so much!

**Comment by maieul** [comment]
Ok, please try the branch issue424.

As you could see in the file issue424.tex, I have implemented:
- \Xlinerangeseparator  for the separator in critical footnote
- \Xendlinerangeseparator for the separator in critical endnote
- optional argument linerangesep=XXX to change for a specific case.

Juste for my curiosity, why do you need to change in some specific case?

**Comment by ingoboerner** [comment]
Dear @maieul,
it's working perfectly. I testet the new features in the MWE and in our production environment as well. It produces the desired output.

To explain, why we need it: Basically, @mepherl tried to explain it in https://github.com/maieul/ledmac/issues/252, we have to distinguish between text that spans across two or more lines (standard linerangesep), and a case, where we have to notate, that something is added oder missing between two lines (linerangesep=/).
E.g.
In two witnesses the following passage is missing:
![stelle2_text](https://cloud.githubusercontent.com/assets/12182347/10509866/00a671c6-7330-11e5-8747-fb83e257f34f.png)
reledmac produces this critical footnote:
![stelle2_apparat](https://cloud.githubusercontent.com/assets/12182347/10509877/13f77360-7330-11e5-9f03-d1d3f4c2f87f.png)

The special case, in which we need a different separator:
Our basetext reads as follows:
![stelle1_text](https://cloud.githubusercontent.com/assets/12182347/10509905/3bf07eca-7330-11e5-95bb-611134343859.png)
There is a line break after the colon. In the apparatus we note, that this line break is missing in one witness:
![stelle1_apparat](https://cloud.githubusercontent.com/assets/12182347/10510093/2f2014d4-7331-11e5-8f0a-f29451c094ec.png)

Thanks again for your help!

**Comment by maieul** [comment]
ok. I understand better. So I will document it tonight and push in a branch for next release.

**Comment by maieul** [comment]
documented, so I close it.
