### ISSUE TITLE
problème \setline sur la page de droite

### ISSUE THREAD

**Issue by Enimie** [maieul/ledmac#425]
Coucou,

J'ai un problème (qui a peut être à voir avec le problème de linenumR evoqué plus haut(#420)?) : je n'arrive pas à modifier la numérotation des lignes sur la page de droite avec \setline, alors que cela marche parfaitement sur la page de gauche.

Exemple:
<latex>
\documentclass[a4paper, oneside, notitlepage, 12pt]{article} 
\usepackage{fontspec}
\usepackage{xunicode}
\usepackage{polyglossia}
\setmainlanguage{french}
\usepackage[noend,noeledsec,noledgroup]{reledmac}
\usepackage[advancedshiftedpstarts]{reledpar}
\sethangingsymbol{[\,}

\makeatletter
\newcommand{\decalage}{0}
\newcount\@l@dtempcntc% Compteur temporaire
\newcommand{\tempcnt}{%
  \ifinserthangingsymbol\else%
    \@l@dtempcntc=\line@num%Prendre le numéro actuel de ligne, le stocker dans \@l@dtempcntc
    \advance\@l@dtempcntc by \decalage%Calcul du décalage
  					% Faire des calculs un peu complexes pour savoir si on affiche ou pas         
    \@l@dtempcntb=\@l@dtempcntc%\@l@dtempcntc
    \@l@dtempcnta=\@l@dtempcntc%
    \advance\@l@dtempcnta by-\c@firstlinenum%
    \divide\@l@dtempcnta by\c@linenumincrement%
    \multiply\@l@dtempcnta by\c@linenumincrement%
    \advance\@l@dtempcnta by\c@firstlinenum%
    % Si on affiche
  	\ifnum\@l@dtempcnta=\@l@dtempcntb%
  		\llap{\numlabfont(\the\@l@dtempcntc)\kern\linenumsep}%
  	\fi%
	\fi
}

\makeatother

\newcommand{\twolineations}[1]{\renewcommand{\decalage}{#1}\doinsidelineLhook{\tempcnt}}
\begin{document}

\begin{pages}
\begin{Leftside}
\setstanzaindents{14,0,0} %
\setcounter{stanzaindentsrepetition}{2}
\beginnumbering 
\stanza[\subsection*{I.}]
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers\&[\setline{0}\twolineations{11}]
%
\stanza[\subsection*{II.}]
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers\&
\endnumbering
\end{Leftside}

\begin{Rightside}
\setstanzaindents{14,0,0} %
\setcounter{stanzaindentsrepetition}{2}
\beginnumbering 
\stanza[\subsection*{I.}]
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers\&[\setline{0}]
%
\stanza[\subsection*{II.}]
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers&
Un vers\&
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
</latex>

J'obtiens la bonne numérotation à gauche (on repart à zero, mais l'ancienne numérotation continue entre parenthèses), mais la numérotation à droite ne repart pas à zero
Je précise que j'utilise la version de la branche #419

**Comment by maieul** [comment]
d�cidement c'est le jour des bugs reledmac. j'essaie de regarder ce soir apr�s #424.

**Comment by maieul** [comment]
bon, ce sera pour jeudi soir, vu que #424 m'a pris plus de tps qu'envisagé, pour faire les choses proprement.

**Comment by maieul** [comment]
bon, alors voilà: le problème est le suivant.
Les commandes qui change la numérotation des lignes (\setline, \advanceline etc.) doivent être lu DANS le contenu d'un \pstart…\pend. Or en mettant dans l'argument optionel tu exclus du \pstart.

Il n'y a aucune raison de mettre dans l'argument optionel. 

Regarde 7efcf4e pour voir comment faire fonctionner

**Comment by Enimie** [comment]
confusion avec setlinenum de ma part. Désolée de t'avoir dérangé pour rien...

**Comment by maieul** [comment]
pas de souci. ce 'est pas quelque chose d'�vident.
Et ca a permi de voir #426
