### ISSUE TITLE
Problème nouvelle version latex firstlinenum

### ISSUE THREAD

**Issue by Circeb** [maieul/ledmac#429]
Bonjour,

J'ai téléchargé les derniers updates de LaTeX, et depuis \firstlinenum me pose problème dans l'environnement pages. Voici mon document

\documentclass[12pt]{book}
\usepackage{reledmac}
\usepackage{reledpar}

\begin{document}

\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart[\section{gauche}]
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche \edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}}
\pend
\pstart[\section{gauche}]
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche \edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}}
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\firstlinenum{20}
\pstart[\section{droite}]
droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite 
\pend
\pstart[\section{droite}]
droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite 
\pend
\endnumbering
\end{Rightside}

\end{pages}
\Pages

\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart[\section{gauche}]
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche \edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}}
\pend
\pstart[\section{gauche}]
gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche gauche \edtext{gauche}{\Afootnote{gauche}} gauche gauche gauche\edtext{gauche}{\Afootnote{gauche}}
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\firstlinenum{20}
\pstart[\section{droite}]
droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite 
\pend
\pstart[\section{droite}]
droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite droite 
\pend
\endnumbering
\end{Rightside}

\end{pages}
\Pages

\end{document}

A la fin du \Pages, le document laisse deux pages blanches avant d'enchaîner sur la suite du document. Je ne suis pas parvenue à trouver où mettre la ligne de code pour qu'elle ait l'effet souhaité sans faire de bugs.

Merci.

**Comment by maieul** [comment]
je ne constate aucun problème avec ce MWE... et je vois mal en quoi firstlinenum (qu'il faudrait désormais mieux appeler via firstlinenumR dans le préambule) pourrais jouer sur le bug décrit (mais non constaté).

Donc merci de me refaire un exemple, ou si cette exemple est vraiment celui qui pose problème, m'envoyer le  fichier de log et le résultat d'un \listefiles

**Comment by Circeb** [comment]
Etrange : si j'écris \firstlinenumR au lieu de \firstlinenum, le problème disparaît sur cet exemple. Je ne comprends pas du tout d'où venait le bug, si ce n'est qu'il disparaissait quand j'enlevais \firstlinenum, mais puisqu'il est résolu si simplement, je vais m'en contenter.

**Comment by maieul** [comment]
non, ca ne va pas. On ne peut pas laisser un tel bug. Simplement je n'arrive pas à le constater. Donc merci de m'envoyer par courriel tout les fichiers qui pose pb (.log, .tex, .pdf).

**Comment by Circeb** [comment]
Très bien. Voici les fichiers en pièce jointe.

**Comment by maieul** [comment]
github n'accepte pas les pieces jointes via email. Me  les envoyer directement à mon courriel (monprenom@monprenom.net)

**Comment by maieul** [comment]
(cela étant il est mieux d'utiliser \firstlinenumR en préambule plutot que \firstlinenum en Rightside)

**Comment by maieul** [comment]
bon, la branche issue429 devrait résoudre. Peux tu me confirmer ?

**Comment by maieul** [comment]
bon, cela marche. Je met cela en branche de release et je ferme le ticket.
