### ISSUE TITLE
eledmac and glossaries: problem

### ISSUE THREAD

**Issue by lorloz84** [maieul/ledmac#437]
I am preparing a critical edition of a prose text and would like to insert at the end of the volume the index of names and a glossary that includes definitions of some terms .

\edindex is perfect because  it shows not only the pagem but even the exact line-number for each word.

Unfortunately with the package glossaries I don't get the same result : each word of the glossary is followed only by the page number and the line number is missing.

Is there a way to overcome the problem and show the line number in the glossary as well?
Thank you
here is a minimal example:

\documentclass[a4paper,11pt]{book}
\usepackage{polyglossia}
\setmainlanguage{italian}

%indice dei nomi
\usepackage{imakeidx}

%edizione critica
\usepackage{eledmac}
%glossario
\makeindex[title=Indice dei nomi]
\usepackage{glossaries}  
\makeglossaries
\newglossaryentry{monistero}{name={monistero},description={monastero}}  

%
\begin{document}
\beginnumbering
\firstlinenum{5}
\linenumincrement{5}
\linenummargin{outer}
\pstart
In queste nostre contrade fu, ed è ancora, un \gls{monistero} di donne assai famoso di santità 
(il quale io non nomerò per non diminuire in parte alcuna la fama sua), nel quale, non ha gran 
tempo, non essendovi allora più che otto donne con una badessa, e tutte giovani, era un buono 
omicciuolo d'un loro bellissimo giardino ortolano, il quale, non contentandosi del salario, fatta la 
ragion sua col castaldo delle donne, a Lamporecchio, là ond'egli era, se ne tornò. Quivi, tra gli 
altri che lietamente il raccolsono, fu un giovane lavoratore forte e robusto e, secondo uom di villa, 
con bella persona e con viso assai piacevole, il cui nome era Masetto\edindex{Masetto}; e 
domandollo dove tanto tempo stato fosse. Il buono uomo, che Nuto\edindex{Nuto} avea nome, 
gliele disse. Il quale Masetto\edindex{Masetto} domandò, di che egli il monistero servisse. 
\pend
\endnumbering
\printindex
\printglossaries

\end{document}

**Comment by maieul** [comment]
I should look to you problem, but for now I have not a lot of time...

**Comment by lorloz84** [comment]
thank you for your reply, I hope that you will find the time to look at my problem and fix it!
I cross my finger!
thanks again
Lorenzo

**Comment by maieul** [comment]
OK. The solution is not complex, if we know well how reledmac do to index with line number. The principle is the same for glossarie

1) Tel to the glossaries package to use not page counter, but pageline counter, a special "counter" of (r)(e)ledmac.
So load glossaries as following:
```\usepackage[counter=pageline]{glossaries}% Use the counter pageline (define by (r)(e)ledmac)```
2) You need to increment this pseudo-counter at each \gls command. So patch \gls with
````\pretocmd{\gls}{\doedindexlabel}{}{}% Call \doedindexlabel at the begining of \gls````
3) As by default reledmac use - to separate page and number, set the .ist file produce by makeglossaries to use it:
```\glsSetCompositor{-}% Use - as separator```

See the following file : https://github.com/maieul/ledmac/blob/6c07505c5ed8a76b4f665309d0c6dc4333f0594d/issue437.tex

So as \edindex, run  makeglossosary only after the third run, in order to have correctline numbers.

Please 
1) let me know if all right.
2) allow me to use your example as file example in the documentation
3) report this answer to the guit forum, wher you ask for it.

**Comment by lorloz84** [comment]
Thank you so much, it works perfectly!
so:
1) all perfect
2) you can use the example whenever and wherever you please
3) done: http://www.guitex.org/home/it/forum/14-edizioni-critiche/103867-eledmac-e-glossaries

You helped me a lot, thank you again

**Comment by maieul** [comment]
ok nice. However, I thank I will create an \edgls command, but I need to 
look if we can change the counter for a specific \gls command. For now, 
it is ok for you. But I think it will be better to provide a more 
integrated solution.

**Comment by maieul** [comment]
hi @lorloz84. I have modified reledmac in order to have a `\edgls` command, like `\gls` but for numbering line. So the hack I have presented to you is not more needs, except of course for `\glsSetCompositor{-}`

Could you try the branch "issue437" ? You will find a file issue437.tex as MWE.

**Comment by lorloz84** [comment]
Hi, I am sorry but I did not understand what you exactly mean by << try the branch "issue437">>? Can you explain me?
Thank you again for your help,
Lorenzo

**Comment by maieul** [comment]
Please read https://github.com/maieul/ledmac#debug-and-feature-requests about how to test a branch.

**Comment by lorloz84** [comment]
Sorry I do not manage to get the .sty file. 
After downloading "ledmac-issue437.zip" and unzipping it  I try to run the .ins file with the command "latex reledmac.ins" but with no succes. I get this message: <<I can't find file reledmac.ins>>
I am a very basic user, could you tell me precisely what to do or attach me directly the .sty file? So that I can try the MWE?

**Comment by maieul** [comment]
I don't see your error message. Which os do you use ? How do you try to get the .sty file ?
For now, you can download the .sty file here, https://drive.switch.ch/public.php?service=files&t=d8911fd2fd98377a3345194682bf960c

but it should be nice to solve you problem with the .ins file, as it is easier for me and other dev let you get the .sty file.

**Comment by lorloz84** [comment]
I downloaded the .sty file, I put it in the same folder of the "issue437.tex" file, I run with PdfLatex (with Texmaker) and everything worked perfectly.

Before I was trying to get the .sty file by running "latex reledmac.ins" in the Command Prompt, in the Start menu (Windows 7). That is what I figured from the internet but I think it was someway wrong.

**Comment by maieul** [comment]
Ok. I think you do not know how to use a windows command prompt to run latex. You was not not in the directory where the .ins was, so it is normal you get an error message.

You can use http://www.wikihow.com/Change-Directories-in-Command-Prompt.

However, you could have open the .ins file with your classical tex editor and run pdflatex inside you editor.

In any case, what I will do now is to merge this branch to the next release branch, the version 2.7.0.

So when the version 2.7.0 will be published on CTAN, you should update you miktex installation and delete the .sty file along your .tex file, to be sure to have the right version.
