### ISSUE TITLE
edlabel and ...lineref selon la nouvelle versione de reledmac

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#441]
Cher ami, 
J'ai trouvé enfin sur un autre ordinateur votre fichiers: PERDONNEZ MOI. Voila ici mes probleme

Si je ecrive 
 \edtext{\begin{greektext}\edlabelS{ text en grecque  \edlabelE{eudelon}  text en grecque}}{\Afootnote{\Atest  La dichiarazione...... }}  

 pour \SEref{eudelon} j'ai la numeration exact de la ligne: number 7.

Mais si je ecrive (dans la page de droit) \edlabelSE{magnitudo}, comme vous dites, <<to mark just one location in the text>> et puis \edlineref{magnitudo} (dans la page de gauche) ça me donne 000, et \SEref{magnitudo} me donne lignes 3R-3R : l'exact référence est seulment à la ligne 3R. 

En outre, j'ai une série de diagnostic dans la compilation de PDFLaTeX:

[77] [78] [79]
! Missing = inserted for \ifnum.
<to be read again> 
                   R
l.231 
? 
! Missing number, treated as zero.
<to be read again> 
                   R
l.231 
? ^C! Interruption.
\l@dlabel@parse ...3|#4|#5->\ifcase #5\or #1\or #2
                                                  \or #3\or #4\fi 

Salutations et merci pour l'aide, Enrico M.

**Comment by maieul** [comment]
bonjour,

merci de fournir les MWE DANS le message.... il faut qu'un lecteur externe qui n'a pas accès à mes courriels puissent y acceder.

Cela passe pour cette fois, mais sur le principe j'aimerai bien que vous respectiez un bug  = un ticket = un MWE.

**Comment by maieul** [comment]
note perso sur la cause du problème : 
problème de \flagref qui n'a rien à faire là : 
\expandafter\gdef\csname the@label#5\endcsname{#1|#2\@Rlineflag|#3|#4}% -> le flag devrait se trouver ailleurs.

il faut donc séparer cela, mettre le flag en dehors du numero de ligne. mais du coup:
- le rétablir pour \edlineref
- ne pas le rétablir pour \xlineref
- l'insérer le cas echant au bon endroit dans \printlines et \printendlines.

**Comment by maieul** [comment]
@heinrichffleck merci de tester la branch ci-jointe 
https://github.com/maieul/ledmac/archive/issue441.zip

n'oublier pas de produire le fichier reledmac.sty ET reledpar.sty

**Comment by maieul** [comment]
la suite sur #444.
