### ISSUE TITLE
cross references number linea

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#444]
Alors, j'ai telechargé reledmac et reledpar. Ce produit ça.
Dans les fichiers que vous connaissez avec \edlabelSE et \SEref la référence au numéro de la ligne est correcte.

Mais si je ajoute  pages avant de ces instructions, j'ai encore une référence à la linea du type. 21R-24R et non (correct) 24R.

Vous dites <justement> que  <<il faut qu'un lecteur externe qui n'a pas accès à mes courriels puissent y acceder>> mais, excusez moi, je   je ne suis capable de rendre un file MWE

PREAMBLE ESSENTIEL
\documentclass[10pt,b5paper,twoside,noinputencoding,]{memoir}
\usepackage[T1]{fontenc}             
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[french,latin.classic,greek,english,italian]{babel}
\usepackage{teubner}
\usepackage{fixltx2e}
%...............................
\usepackage[series={A,B,C,D,E},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}
%https://www.ctan.org/tex-archive/macros/latex/contrib/reledmac/examples
%----------------------------------------------------------
%\renewcommand*{\setgoalfraction}{0.9}
%\renewcommand*{\setgoalfraction}{1.5}
\setgoalfraction{0.95}
\Xmaxhnotes{0.45\textheight} % Spazio prima note. Era 0,25
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A}) }
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\textbf{\theBtest\ - C}) }
\newcounter{Ctest}
\def\Ctest{\stepcounter{Ctest}(\textbf{\theCtest\ - B}) }
\Xonlyside[B]{L}
\Xonlyside[C]{R}

FILE \INCLUDE LIBRO-I

PAGE DE GAUCHE
\pstart\relax
[5]   \begin{GRL} \edtext{\begin{GRL}t~w| meg'ejei talika'utan e>~imen\end{GRL}}{\Afootnote{\Atest: <<abbia tale grandezza che>>,   ln.  \SEref{magnitudo}. Il capitolo ........ }}, \begin{GRL} ...... \end{GRL} 	
\pend

PAGE DE DROIT
\pstart\relax
[5]  Suppone questi infatti .... sia pure posto nel Sole,   \edlabelSE{magnitudo} abbia tale grandezza   che   il cerchio [descritto], lungo il quale egli suppone che la Terra rivolga ....
\pend

Je ne sias pas faire   rien  de mieux, excusez moi.
Cordialmente, Enrico M.

**Comment by maieul** [comment]
Ceci ressemble deja mieux un un MWE. MAIS un MWE doit être minimum ET working, donc compilable. Ici j'ai du reinserer moi même les elements necessaires à la compilation.

Ceci est est un vrai MWE https://github.com/maieul/ledmac/blob/292e67339e098b5389a3ef2aa32431fc0cef084f/issue444.tex

merci la prochaine fois de produire rellement un MWE. J'ai deja suffisament de mal avec tout les tickets qui s'ouvrent pour ne pas en plus devoir faire moi même des MWE. Je ne prendrai pas en compte vos messages sans MWE.

Par ailleurs ce problème étant la suite d'une mauvaise correction de #441, il n'était pas forcément la peine d'ouvrir un nouveau ticket (et si vous voulez m'ecrire en italien, vous pouvez).

**Comment by maieul** [comment]
bon, par contre les fichiers que vous fournissez ne permettent pas de voir le bug que vous mentionnez.... merci de faire des efforts pour me fournir des fichiers utilisables...

**Comment by maieul** [comment]
bon, donc merci de m'envoyer un VRAI MWE qui montre le probleme. Là je ne peux rien faire n'ayant aucun exemple probèmatique sous la main.

**Comment by heinrichffleck** [comment]
Cher ami, 
 Je vous remercie de votre patience, mais -je répète- le problème apparait après plusieurs pages, pas sur une seule page et est incapable de le montrer dans un fichier MWE, ou, du moins, je ne suis pas capable de ça. 

Un'autre chose. Vous avez envoyé le fichier ledmac-issue441.zip . 
Pendant la compilatione (pdflatex reledpar.dtx) j'ai ça:
! Undefined control sequence.
\reserved@a ->\@nil                     
l.4190 ...lX}. Can be retrieved by \cs{xflagref}.}
? 
! Undefined control sequence.
\reserved@a ->\@nil 
l.4190 ...lX}. Can be retrieved by \cs{xflagref}.}
? 
! Undefined control sequence.
\reserved@a ->\@nil 
l.4190 ...lX}. Can be retrieved by \cs{xflagref}.}
? 

Toujours mes meilleures salutations et merci, cordialement Enrico M.

=======================
www.heinrichfleck.net
www.astronomiainumbria.org

      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it> 
 Inviato: Lunedì 2 Novembre 2015 9:52
 Oggetto: Re: [ledmac] cross references number linea (#444)
   
bon, donc merci de m'envoyer un VRAI MWE qui montre le probleme. Là je ne peux rien faire n'ayant aucun exemple probèmatique sous la main.—

**Comment by maieul** [comment]
et bien envoyer moi un zip complet, car là JE NE PEUX RIEN FAIRE.

Un MWE est :
- minimum : aussi petit que possible
- working : aussi grand que necessaire pour retrouver le pb.

Je ne sais pas comment vous dire plus clairement les choses. Là JE NE 
PEUX RIEN FAIRE.

**Comment by maieul** [comment]
merci de m'envoyer rapidement votre vrai MWE. J'aimerai résoudre ce problème rapidement, avant la sortie de la prochaine version de reledmac.

Concernant le problème de compilation de reledpar.dtx, il est corrigé dans la branche 2.5.0-2.6.0

**Comment by heinrichffleck** [comment]
Excusez moi, je l'espère le faire demain. Je suis actuellement malade, 
au lit, et.. <<assez>> vieux, pas jeune comme vous.

Con cordialità e riconoscenza per i suoi sforzi, Enrico M.

**Comment by maieul** [comment]
(notes perso)

Ok, le problème est le suivant

Soit le MWE suivant

````
\documentclass{article}
\usepackage[series=A,noend,noeledsec,noledgroup,nofamiliar]{reledmac}
\begin{document}
\beginnumbering
\pstart
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sodales egestas odio. Nulla odio ante, varius nec ex id, \edtext{ss\edlabel{lemma}}{\edlabel{arg}\Afootnote{s\edlabel{footnote}s}}mattis sagittis lectus. Ut metus nibh, efficitur at felis volutpat, dignissim ullamcorper velit. Integer bibendum dui massa, aliquet bibendum dui pellentesque sit amet. Sed nisl ligula, molestie nec lectus eget, porttitor lobortis tellus. Phasellus tincidunt dui risus, id condimentum sapien gravida vitae. Ut commodo mi odio, quis euismod magna ultricies quis. Nulla in lacinia nulla, at convallis ante.
\pend
\endnumbering
\end{document}
````

Produit le .1 suivant:

`````
\line@list@version{4}
\@nl[1][1]
\@nl[1][1]
\@lab\%arg
\@ref[1][
\@lab\%lemma
]
\@nl[1][1]
\@nl[1][1]
\@nl[1][1]
\@nl[1][1]
\@nl[1][1]
\@lab\%footnote
`````

`\@lab\%footnote` est recallé tout à la fin, au moment où on fait une écriture, alors qu'il devrait être après `\@lab\%lemma`.

**Comment by maieul** [comment]
@heinrichffleck vous ne devriez pas utiliser \edlabel (ou similaire) dans une \Cfootnote. Outre le bug actuel, cela renverra au numero de page de la ligne correspondant à l'appel de notes, pas de la note courante.

**Comment by maieul** [comment]
Bien, alors la branche issue444 devrait résoudre ce problème. Le problème était en partie de ma faute, ayant mal documenté l'utilisation de \edlabel.

Celui-ci ne pouvait normalement pas être utilisé dans une \Xfootnote. Je le déconseille du reste fortement. C'est un coup à ne plus savoir où on est. Cela étant la branche issue444 devrait résoudre ce problème, en renvoyant toutefois au numero de la première ligne seulement, si on est sur deux lignes. Le mieux est encore d'utiliser applabel pour renvoyer à un commentaire.

**Comment by maieul** [comment]
ps : merci si possible de me confirmer avant demain soir que cela marche.

**Comment by maieul** [comment]
ne faite pas de tests maintenant. Il y a encore un souci...

**Comment by heinrichffleck** [comment]
J'etais à vous ecrire.......

Bien, j'attende

**Comment by maieul** [comment]
voilà, la nouvelle version devrait être ok, je viens juste de l'envoyer. vous pouvez faire les tests.

**Comment by heinrichffleck** [comment]
Excusez moi, mais je ne comprends pas. Le fichier #444 est pour aide à des problems de \index.

Saluti, Enrico M.

**Comment by maieul** [comment]
La branche issue444 corrige (normalement) votre problème. Cf le fichier issue444.tex qui n'a rien à voir avec \edindex.

Il se trouve simplement qu'il a fallu que je m'assure qu'il ne casse pas en plus les index en réparant les crossref (car les deux sont liés, en internes). D'où le fichier issue444-pb-index.tex

Mais ma question à moi est : est-ce qu'avec les fichier .sty engendré depuis cette branche votre problème de crossref est résolu.

Donc merci de tester les fichier .sty et de me dire ce qu'il en est.

**Comment by heinrichffleck** [comment]
No, comme vous pouver voyer j'ai encore (dans votre fichier et avec votre dernier reledmac)
15–16 Nulla...orci ] Some comment.
Compilation avec xelatex

![screenshot_2015-11-05_20-51-47](https://cloud.githubusercontent.com/assets/13473498/10979843/1b5d4d70-83ff-11e5-871b-b5d751155efc.png)

**Comment by maieul** [comment]
donc j'attend une réponse d'ici demain midi. Au dela de quoi je considère le problème comme résolu et je  lance le processus de sorti de la nouvelle version de reledmac.

**Comment by heinrichffleck** [comment]
Pardonnez-moi mais,  c'est mon probleme, mais je ne peux pas bien comprendre votre demande.

 Vous m'avez envoyé le fichier issue444.tex et je l'ai  compiler en XeLaTeX  avec les packages reledmac et reledpar que vous me m'avez aussi  envoyé.

Ensuite, j'ai vous envoyé l'output comme picture (fichier Screenshot_2015-11-05_20-51-47.png). 

J'ai également compilé ce fichier  parmi mes fichiers

<<Pellentesque pas pichets dui. Donec UE pour libérer sollicitudin lobortis nisl eget Lacus nca. \{Edtext Rien pellentesque, neque ut tincidunt vestibule, avant que je purus Varius, cursus nca pichets neque ut pichets} {\ {lemme Rien \ ldots pichets} \ {Afootnote Certains commentaire \edindex {} rien.}} -OMISSIS-  Donec et condimentum quam, id ullamcorper nisl.

Mais la référence au numéro de ligne n'est pas correct: j'ai -pour example- 54 - 55 R et non 55R.

C'est tout. Si je ne l'ai pas bien compris vos instructions, s'il vous plaît pardonnez-moi, Cordiallment, Enrico M.

**Comment by maieul** [comment]
1) je ne vous ai jamais demandé de compiler le fichier issue444.tex. Juste VOS fichier.
2) vous me dites ENFIN qu'il y a encore un problème sur un de vos fichiers.  Voilà ce que je vous demandez.

**Comment by maieul** [comment]
merci de m'envoyer les fichiers qui posent problème. Je ne comprend rien à ce que vous testez, je suis totalement perdu et donc ne peux pas debuger...

**Comment by maieul** [comment]
j'ai verifier toutes les références dans le fichier exemple que vous m'aviez envoyé il y a quelques jours > donc merci de me renvoyer vos fichiers problématiques.

D'une manière générale, je me repete encore une fois, je ne peux rien debuger sans fichier d'exemples avec un bug...

**Comment by heinrichffleck** [comment]
Bien donnez mois quelque jour. J'espere cette fois de vous presenter un vrai MWE.
Cordialmente, Enrico M.

PS. J'ai compilé le fichier issue444.tex parce-que vous m'avez ecrit: <<....mais ma question à moi est : est-ce qu'avec les fichier .sty engendré depuis cette branche votre problème de crossref est résolu.>>

**Comment by maieul** [comment]
le fichier issue444.tex n'est pas un fichier .sty ...

**Comment by heinrichffleck** [comment]
ça je le sais....

**Comment by maieul** [comment]
donc à partir de ce moment là, je pouvais vous demander que sur vos ficheirs à vous, pas sur mes fichiers à moi, que j'ai deja testé...

**Comment by heinrichffleck** [comment]
Oui, certamente, a bientot Enrico

**Comment by maieul** [comment]
savez vous quand vous pourrez m'envoyer le MWE ? j'aimerai clore ce ticket pour pouvoir sortir la prochaine version de reledmac/reledpar.

**Comment by heinrichffleck** [comment]
Cher et patient ami, 
Je me suis  essayé à faire différents tests, avec les nouvelles routines de reledmac et reledpar, en particulier avec des nouveaux fichiers, mais c'était inutile. Mes nouveaux fichiers étaient aussi très longues, plusieurs pages, (: j'ai fait trois types différents et toujours avec reledpar et reledmac).

La référence incorrecte au nombre de ligne existe <<seulement>> pour les fichiers sur lesquels je travaille actuelment (grec et italien) et  malgré mes nombreux tests, je ne pouvais pas comprendre la raison de l'erreur,  qui   se produit <<seulment>>  sur mon vielles fichiers.

Par conséquent reledpar et reledmac, autant que je pouvais voir, ne s'ont pas des bug, et je suis désolé de vous avoir fait perdre beaucoup de temps.

Quand mon petut travail a été accompli, je vais vous invierò (envoyer) un fichier zip pour vous exame eventuelle.

salutations, Enrico M.

**Comment by maieul** [comment]
Très bien. Je suis encore un peu étonné, mais il est vrai que vos fichiers sont complexes. Peut être que vos problème de références sont lié à des labels que vous avez placé deux fois ? N'hésitez pas à regarder le fichier .log qui indique les "duplicate label".

**Comment by heinrichffleck** [comment]
No, pas des references places deux fois, c'est la premiere chose que j'ai examiné. Je croyais aussi qu'etait une questione de \pstart \pend pour chaque paragraphe, mais aussi en ecrivant 
\pstart
1 paragraph
2 paragraph
3 paragraph
4 paraghraph
\pend
dans mes nouvelles fichiers pro-test le references sont-elles corrects.

Enrico M.

**Comment by maieul** [comment]
bizarre, bizarre. envoyez moi votre fichier une fois tout cela prêt. Il doit encore y avoir un bug, mais où ?
