### ISSUE TITLE
Erroneous vertical space in astanza

### ISSUE THREAD

**Issue by CarolusMagnus** [maieul/ledmac#446]
I'm using astanza in a pairs environment. If a line gets too long, but there is no line breaking, an additional vertical space after the line is inserted, as can be seen in the attached example in line 9 (after γλυκὺν) and 14 (ἄγειν).

    \documentclass[twoside, DIV14, 11pt]{scrbook}

    \usepackage{fontspec}
    \setmainfont{Linux Libertine O}
    \usepackage{polyglossia}
    \setdefaultlanguage{german}
    \setotherlanguage[variant=ancient]{greek}
    \newfontfamily\greekfont{Linux Libertine O}
    \usepackage{reledmac}
    \usepackage{reledpar}
    \setstanzaindents{1,0}
    \setcounter{stanzaindentsrepetition}{1}
    \stanzaindentbase=1cm
    \setlength{\Lcolwidth}{0.4\textwidth}
    \setlength{\Rcolwidth}{0.55\textwidth}

    \begin{document}
    \begin{pairs}
	\begin{Leftside}
		\selectlanguage{greek}
		\beginnumbering
		\begin{astanza}
			\textbf{Ἀντιγόνη}\skipnumbering&
			οὐ γὰρ τάφου νῷν τὼ κασιγνήτω Κρέων&
			τὸν μὲν προτίσας, τὸν δ' ἀτιμάσας ἔχει;&
			Ἐτεοκλέα μέν, ὡς λέγουσι, σὺν δίκης&
			χρήσει δικαίᾳ καὶ νόμου  κατὰ χθονὸς&
			ἔκρυψε τοῖς ἔνερθεν ἔντιμον νεκροῖς·&
			τὸν δ' ἀθλίως θανόντα Πολυνείκους νέκυν&
			ἀστοῖσί φασιν ἐκκεκηρῦχθαι τὸ μὴ&
			τάφῳ καλύψαι μηδὲ κωκῦσαί τινα,&
			ἐᾶν δ' ἄκλαυτον, ἄταφον, οἰωνοῖς γλυκὺν&
			θησαυρὸν εἰσορῶσι πρὸς χάριν βορᾶς.&
			τοιαῦτά φασι τὸν ἀγαθὸν Κρέοντα σοὶ&
			κἀμοί, λέγω γὰρ κἀμέ, κηρύξαντ' ἔχειν,&
			καὶ δεῦρο νεῖσθαι ταῦτα τοῖσι μὴ εἰδόσιν&
			σαφῆ προκηρύξοντα, καὶ τὸ πρᾶγμ' ἄγειν&
			οὐχ ὡς παρ' οὐδέν, ἀλλ' ὃς ἂν τούτων τι δρᾷ,&
			φόνον προκεῖσθαι δημόλευστον ἐν πόλει.&
			οὕτως ἔχει σοι ταῦτα, καὶ δείξεις τάχα&
			εἴτ' εὐγενὴς πέφυκας εἴτ' ἐσθλῶν κακή.\&
		\end{astanza}
		\endnumbering
	\end{Leftside}
	\begin{Rightside}
		\beginnumbering
		\selectlanguage{german}
		\begin{astanza}
			\textbf{ANTIGONE.}\skipnumbering&
			Hat unsrer Brüder Kreon den des Grabes nicht&
			Sogleich gewürdigt, aber den voll Schmach beraubt?&
			Denn zwar Eteokles hat er, wie man sagt, gerecht&
			Und guter Ordnung folgend, gleich in Erde wohl&
			Verhüllt, damit ihm Ehre bei den Toten sei;&
			Polyneikes' elend umgekommnen Leib jedoch&
			Verbeut er, heißt es, unter Heroldsruf der Stadt&
			Zu klagen noch ins Grab zu tun; nein, diesen soll&
			Grablos sie lassen, unbeweint, zum süßen Fund&
			Den Vögeln, welche Fraßbegier herniedertreibt.&
			Dergleichen habe der edle Kreon, heißt es, dir&
			Und mir, auch mir ja, sag ich, angekündiget &
			Und kehre nochmals, allen noch Unkundigen&
			Es deutlich auszurufen, und betreibe nicht&
			Für nichts die Sache; sondern wer dagegen tut,&
			Dem droht des Steinwurfs herber Tod in offner Stadt.&
			Nun, so verhält sich dieses, und du zeigest bald,&
			Ob selbst du edel sprossest, ob von Guten schlecht.\&
		\end{astanza}
		\endnumbering
	\end{Rightside}
    \end{pairs}
    \Columns
    \end{document}

**Comment by maieul** [comment]
please try branch "issue446"

**Comment by CarolusMagnus** [comment]
Your fix seems to work for me. Thank you very much!

**Comment by maieul** [comment]
you're welcome.
