### ISSUE TITLE
\edindex, \index and italic text

### ISSUE THREAD

**Issue by mepherl** [maieul/ledmac#448]
Hello Maieul!

This 
```
\documentclass{scrbook}

\usepackage{imakeidx}
\usepackage{reledmac}

\makeindex
\begin{document}
A word\index{A word!Subitem@\emph{Subitem}} and another word\index{A word!Subitem@\emph{Subitem}} and an \emph{italic word\index{A word}}.

\beginnumbering\pstart
A word\edindex{A word!Subitem@\emph{Subitem}} and another word\edindex{A word} and an \emph{italic word\edindex{A word!Subitem@\emph{Subitem}}}.
\pend
\endnumbering
\printindex
\end{document}
```

Might be an ugly hack for styling the index, but I need to be able take control whether a subitem is in italics or not. Unfortunately because the last edindex is within \emph the output are two different index-entries instead of one. Do you know, why that is? Any idea how to avoid that behaviour?
Thank you and best regards!
Martin

**Comment by maieul** [comment]
1) First you should not use <code>\index{A word!Subitem@\emph{Subitem}}</code> but <code>\index{A word!Subitem@Subitem|emph}</code>, I thinks (to be confirmed, I have nevers used | + @
2) That is a problem of makeindex, which is not able to merge the two entries. Maybe xindy can solve it, but I have never do a test. For by book, I have written a script which merge two entries with the same number and differents appearence in the .ind. It is not related in any case to reledmac.

**Comment by maieul** [comment]
ps : my script is on https://github.com/maieul/latexhumain/blob/master/post-index.py#L11

**Comment by mepherl** [comment]
Thank you! Sorry for bothering with something not reledmac related! I'm a huge fan!

**Comment by maieul** [comment]
not a problem. But i think you will find some answer on https://tex.stackexchange.com/
