### ISSUE TITLE
make all -- examples

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#450]
Running the current ``make all`` brings up the following problem:

> make -C examples all
> make[1]: Entering directory '/home/XXXX/ledmac-master/examples'
> latexmk 3-reledpar_sync_setting_advancedshifted-nomax.tex
> make[1]: latexmk: Kommando nicht gefunden
> makefile:10: recipe for target '3-reledpar_sync_setting_advancedshifted-nomax.pdf' failed
> make[1]: *** [3-reledpar_sync_setting_advancedshifted-nomax.pdf] Error 127
> make[1]: Leaving directory '/home/XXXX/ledmac-master/examples'
> makefile:42: recipe for target 'dist' failed
> make: *** [dist] Error 2

So it does not find the command 'latexmk' in examples/ ...

**Comment by maieul** [comment]
hum, which distribution do have ? latexmk is a current commands provided by texlive...

**Comment by baem2** [comment]
I'm running debian 8 with texlive from the repos. I just installed latexmk (which is not part of the standard installation, it seems). So the make-script goes through further.

Next problem for the .../examples/: As reledmac.sty is not in the current folder, it loads the .sty from the main TeX installation, and that file is outdated. So I copied the recent reledmac.sty in /examples/

And now, the next problem:
```
Running 'latex  -recorder  "4-reledpar_titles_not_in_line_numbering.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./4-reledpar_titles_not_in_line_numbering.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 60 languages loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex
(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3unicode-data.def)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3dvips.def))
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX to function.
! 
! You must change your typesetting engine to, e.g., "xelatex" or "lualatex"
! instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.43  }
```

The package texlive-xetex is installed, the command ``xelatex`` is available ...?

**Comment by maieul** [comment]
I don't know anything to texlive on Debian ;-). It is so strange that the very useful latexmk command is not installed. And it is also so strange that the xelatex command is not available. That is two modern tools.

When I run a make command, I am always in my texmf folder, so I have no need to copy the new .sty file.

But do you know that all the files are available on CTAN?

**Comment by Doc73** [comment]
@baem2 
I'm sorry for my interference in this debate. but I am too a Debian 8 Jessie user.
I would suggest you to uninstall Debian Official Texlive and install instead Texlive from CTAN: it is newer and probably not affected by this problem.

**Comment by baem2** [comment]
Thanks for your answers!

@maieul: The strange part about that last error message is that xelatex /is/ in fact available, that's why I'm wondering about that error.

@Doc73: Thanks for that hint, but I'd rather stick to debian's texlive, as I usually have to install several machines (distributed over all Germany) with debian and TeX, and this way it is easier; and this way I also can easily make sure that all machines do have the exactly same versions of the TeX packages.

**Comment by maieul** [comment]
@baem2 please try to cp the file latexmkrc from the main folder to the example folder, and made feeback. I think the problem is that I have a global latexmkrc file in my computer, so I didn't see we need one for the subfolder.

**Comment by baem2** [comment]
This has been working. So I had to install some further packages for SIunits.sty, bidi.sty, ... and still there's some error:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "estre.otf" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.7 ...yriacfont[Script=Syriac,Scale=1.2]{estre.otf}
```

So probably I am going to stick with pdf-ing the files I need manually, not using make, as I have to install a lot of packages I don't really need this way. Thanks for your help, you can close here ... :)

**Comment by maieul** [comment]
you need to install the font estre.otf on your computer (as explained in the message !). You will found it on internet.
