### ISSUE TITLE
Numbering of familiar notes confused

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#452]
In the MWE the numbering of familiar notes is disturbed in the case of the notes are numbered by page via perpage package and are arranged in one paragraph. I'm using the version of issue436. 

\documentclass{book}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[series={A,B,C},noeledsec,noend]{reledmac}
\usepackage{reledpar}

\renewcommand*{\thefootnoteA}{\alph{footnoteA}}
\arrangementX[A]{paragraph}
\arrangementX[B]{paragraph}

\usepackage{perpage}
\MakePerPage{footnoteA}
\MakePerPage{footnoteB}

\begin{document}

\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart
Et quamquam Philon in tractatu suo de aqueductibus\footnoteA{Philon von Byzanz}. Magister Dominicus de Florentia\footnoteA{Dominicus von Florenz}
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Und obwohl ...
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\newpage

\setcounter{footnoteC}{0}
\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart
Et quamquam Heron\footnoteB{Heron von Alexandrien}. Magister Ptolemaeus\footnoteB{Ptolemaeus}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Und obwohl ...
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\end{document}

**Comment by maieul** [comment]
the problem is not related to perpage (despite I am afraid perpage could be problematic with this new feature, I have to make test) but to paragraphed footnotes. As you can see with the exemple on c521a6d.

I am looking on.

**Comment by maieul** [comment]
the branch issue452 should solve the problem for your example. I am looking on other MWE if perpage could be problematic.

**Comment by sonator** [comment]
Thank you! 
I can confirm that the MWE is running perfectly. But in a longer and more complexe file the numbering by page via perpage is being disabled, but not confused, id est the numbering is executed by section.

**Comment by maieul** [comment]
yes, I am working for the integration of perpage. sorry for this breaking, but it was need to have correct footnote number in we don't set one series by side.

**Comment by sonator** [comment]
Thanks! Please note, that this matter is not in a hurry.

**Comment by maieul** [comment]
the new version of the branch should solve the problem with perpage.

BUT you have to write

````
\MakePerPage{footnoteB@typeset}
````

and not 

````
\MakePerPage{footnoteB}
````

**Comment by sonator** [comment]
Très bien. La numérotation marche comme il faut! Merci beaucoup.

**Comment by maieul** [comment]
Ok. Je vais publier cela rapidement, puisque c'est un bug assez gênant.
