### ISSUE TITLE
Index entries with notenumber option in familiar notes

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#457]
If you have time, please have a look on the behaviour of the several versions of a MWE testing the notenumber option of indextools in familiar notes inside and outside ledgroup environments. I have used reledmac v.2.6.0 of issue452.

First Version:
Both \setcounter commands are working correctly. But, for index entries in familiar notes the notenumber option seems to be deactivated. 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex,notenumber]{indextools}
\usepackage[series={A,B,C},noeledsec,noend]{reledmac}
\usepackage{reledpar}
\makeindex[name=pers,title=Index personarum]

\begin{document}

\setcounter{footnote}{10}

Carolus Magnus\index[pers]{Carolus Magnus}, 
Ludovicus Pius\footnote{Ludovicus Pius\index[pers]{Ludovicus Pius}}

\setcounter{footnoteA}{4}
\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart
Seneca Maior\footnoteA{Seneca Maior\index[pers]{Seneca Maior}}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Plinius Minor\footnoteA{Plinius Minor\index[pers]{Plinius Minor}}.
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\printindex[pers]

\end{document}

------------------------------------------------------------------------------

Second Version: ledgroup environment
The first \setcounter{footnote} command is working correctly. The second \setcounter{footnoteA} command inside the ledgroup environment does not work. The notenumber option of indextools is working correctly, too.

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex,notenumber]{indextools}

\usepackage[series={A,B,C},noeledsec,noend]{reledmac}
\usepackage{reledpar}

\makeindex[name=pers,title=Index personarum]

\begin{document}
\setcounter{footnote}{10}

Carolus Magnus\index[pers]{Carolus Magnus}, 
Ludovicus Pius\footnote{Ludovicus Pius\index[pers]{Ludovicus Pius}}

\begin{ledgroup}
\setcounter{footnoteA}{4}
\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart
Seneca Maior\footnoteA{Seneca Maior\index[pers]{Seneca Maior}}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Plinius Minor\footnoteA{Plinius Minor\index[pers]{Plinius Minor}}.
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns
\end{ledgroup}

\printindex[pers]

\end{document}

----------------------------------------------------------------------

Third Version: From arabic to alphabetic numbering
Inside the ledgroup environment the numbering of familiar notes is changed from arabic to alphabetic. In the main text the alphabetic numbering runs correctly, but not in the apparatus. And the \setcounter{footnoteA} command is ignored. The notenumber option works optimally.

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex,notenumber]{indextools}

\usepackage[series={A,B,C},noeledsec,noend]{reledmac}
\usepackage{reledpar}
\renewcommand*{\thefootnoteA}{\alph{footnoteA}}
\makeindex[name=pers,title=Index personarum]

\begin{document}
\setcounter{footnote}{10}

Carolus Magnus\index[pers]{Carolus Magnus}, 
Ludovicus Pius\footnote{Ludovicus Pius\index[pers]{Ludovicus Pius}}

\begin{ledgroup}
\setcounter{footnoteA}{4}
\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart
Seneca Maior\footnoteA{Seneca Maior\index[pers]{Seneca Maior}}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Plinius Minor\footnoteA{Plinius Minor\index[pers]{Plinius Minor}}.
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns
\end{ledgroup}

\printindex[pers]

\end{document}

**Comment by maieul** [comment]
I will look on it this week-end.

**Comment by sonator** [comment]
Thank you!

**Comment by maieul** [comment]
please, next time open an issue by problem. Here you have two problems : some concerning indexing, some concerning note numbering. The two first problem should be solve in the branch issue457. I will look tomorrow for the third.

**Comment by maieul** [comment]
oh, the third problem is just the same as the second one. So it should be solved.

**Comment by sonator** [comment]
The MWEs are running as expected -- with very good results, and my longer edition files, too. Thank you very much! 

In matters of the MWEs I have an additional question, from which I don't know if it is to transmit to the indextools page. 

Does the notenumber option only work in combination with a symbolic name for an index? 

When no symbolic name is specified the MWE does not run. And the index command in the normal footnote causes an error message. Without the notenumber option it works. 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[makeindex,notenumber]{indextools}
\usepackage[series={A,B,C},noeledsec,noend]{reledmac}
\usepackage{reledpar}
\makeindex[title=Index personarum]

\begin{document}

\chapter{Carolus Magnus et alii quamplures}
Carolus Magnus\index{Carolus Magnus}, 
Ludovicus Pius\footnote{Ludovicus Pius\index{Ludovicus Pius}}

\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
Pippinus Maior\footnoteA{Pippinus Maior\index{Pippinus Maior}}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Pippinus Minor\footnoteA{Pippinus Minor\index{Pippinus Minor}}.
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\printindex

\end{document}

**Comment by maieul** [comment]
please open a new issue. It is not related. I want to have one issue by problem. It's help to have clearer code.

**Comment by maieul** [comment]
Oh, it is clearly related to indextools. So open it on indextools page.

**Comment by sonator** [comment]
Thanks, I have transfered the question to the indextools page.
