### ISSUE TITLE
More clearly separating consecutive footnotes

### ISSUE THREAD

**Issue by fps-vogel** [maieul/ledmac#458]
I'd like to more clearly distinguish consecutive footnotes. For example,
- by adding vertical space between footnotes in a column, as described in [this SE question](http://tex.stackexchange.com/questions/279249/add-vertical-space-around-footnote-rule-and-between-footnotes-in-reledmac), which can almost be done by adding vertical space in `\Xbhooknote` (problem: extra vertical space below the footrule).
- by indenting the first line of each column footnote
- by displaying lemmata in bold face, like what [this workaround](http://tex.stackexchange.com/questions/202134/how-can-i-change-the-lemma-in-a-paragraphed-footnote-into-bold-in-eledmac?rq=1) does, but for multiple series of critical notes. This would serve to distinguish paragraph as well as column notes more clearly.

If I more than one of these were possible, even better. But if there is a workaround for any of them, I'd love to know it. Thanks!

**Comment by maieul** [comment]
1. I will look on it.
2. Use \Xparindent and / or \parindentX. (§ 6.7 of the handbook)
3. Please open a new issue for this problem. One issue by problem.

**Comment by maieul** [comment]
For you first question, what about 
`````
\documentclass{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}
\usepackage{reledmac}
\usepackage{lipsum}
\Xbeforenotes[B]{10pt}  % adds space above footnote rule
\Xafterrule[A]{0pt}  % n
\Xbhooknote[A]{\endgraf\vspace{10pt}} 
\begin{document}
\beginnumbering
\pstart
\edtext{Lorem}{
  \Afootnote{A critical note}  % space between this note and the rule, and above the rule
  \Bfootnote{Critical note in series B}}
\edtext{ipsum}{
  \Afootnote{Another critical note}  % space between this and the first Afootnote
  \Bfootnote{Other critical note in series B}}
\lipsum*[1-6]
\pend
\endnumbering
\end{document}
````
(notes the `\endgraf`, required to insert the vertical space on the good position.

**Comment by maieul** [comment]
or better

`````
\documentclass{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}
\usepackage{reledmac}
\usepackage{lipsum}
\Xparindent
\Xbeforenotes[B]{10pt}  % adds space above footnote rule
\Xafterrule[A]{0pt}  % n
\Xbhooknote[A]{\vskip 10pt\noindent} 
\begin{document}
\beginnumbering
\pstart
\edtext{Lorem}{
  \Afootnote{A critical note}  % space between this note and the rule, and above the rule
  \Bfootnote{Critical note in series B}}
\edtext{ipsum}{
  \Afootnote{Another critical note}  % space between this and the first Afootnote
  \Bfootnote{Other critical note in series B}}
\lipsum*[1-6]
\pend
\endnumbering
\end{document}
`````

**Comment by fps-vogel** [comment]
Thanks, maieul. `\Xparindent` wasn't working for me before because I had set `\parindent` to zero and forgot about it. Your method for 1. is an improvement over what I tried before. Thanks!

**Comment by maieul** [comment]
ok. I post it on stackexchange. Please validate it.
