### ISSUE TITLE
Boldface lemmata

### ISSUE THREAD

**Issue by fps-vogel** [maieul/ledmac#459]
I'd like the option of displaying lemmata in bold face across multiple series of notes, something like what [this workaround](http://tex.stackexchange.com/questions/202134/how-can-i-change-the-lemma-in-a-paragraphed-footnote-into-bold-in-eledmac?rq=1) does. However, that workaround works only for a single series of notes.

**Comment by maieul** [comment]
will do it tomorrow.

**Comment by maieul** [comment]
Please try branch "issue459". It provides two new hook:
- `\Xlemmafont[<series>]{<cmd>}`
- `Xendlemmafont[<series>]{<cmd>}`

to execute TeX font command for cmd, like
````
\Xlemmafont{\bfseries}
````

You should use it in combination with the (already existing) `\Xlemmadisablefontselection` hook.

See the file issue459.tex

**Comment by fps-vogel** [comment]
Thanks, @maieul. But I'm having trouble--perhaps I'm doing something wrong. Here's my MWE:

    \documentclass[12pt]{article}
    \usepackage{lipsum}
    \usepackage{reledmac}
    \Xarrangement[A]{twocol}
    \Xlemmadisablefontselection[A]
    \Xlemmafont[A]{\bfseries}
    \begin{document}
    \beginnumbering
    \pstart
    \lipsum*[1-3]\edtext{Lipsum}{
        \Afootnote{\lipsum*[3]}}
    \pend
    \endnumbering
    \end{document}

The lemma appears in regular font.

**Comment by maieul** [comment]
my fault. Bad pastebin. New version should be ok.

**Comment by fps-vogel** [comment]
Perfect. Thank you so much! I believe that question on StackExchange (linked above) can now be answered.

**Comment by maieul** [comment]
yes, I will do it.

**Comment by maieul** [comment]
ps : you asked for a general tools. So you should do `\Xlemmafont{\bfseries}` and not `\Xlemmafont[A]{\bfseries}` to apply it to all series.
