### ISSUE TITLE
Hook: \Xhsize et \hsizeX

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#461]
Pour répondre à cette question http://tex.stackexchange.com/q/279491/7712, sans que la personne s'en preoccupe. Devrait contenir une expression parsable par `\dimexpr`.

Du type 
````
\Xhsize{\columnwith+\marginpar+\ledrsnotewidth}
```` 

S'occuperait de l'insertion au bon endroit selon le type de note.

**Comment by maieul** [comment]
@fps-vogel : please try the branch issue461. It provides two new hooks: \Xhsize and \hsizeX. Their mandatory argument is a dimension expression (parsable with \dimexpr). 

As usual, it can take an optional argument : a comma separated list of series.

See the example issue461.tex in the branch. 

Also look at
````
\AtBeginDocument{%
 \maxhnotesX{0.8\textheight}
 \Xmaxhnotes{0.8\textheight}
}
````

it is required to avoid footnote too height (because you change the geometry, and because the \textheight is defined only at `\begin{document}`.

**Comment by maieul** [comment]
please also read a20fff0 and tell if the handbook is ok for you.

**Comment by fps-vogel** [comment]
Everything looks good. Thanks so much! This should be the last feature request for the project I'm working on.

I thought I saw a page listing editions prepared with reledmac, but now I can't find it. If such a page exists, I'd be glad to add my project, though it'll be very short (~10 page Latin commentary of the Life of Einhard, for a grad seminar).

**Comment by maieul** [comment]
there is a list, but no many people full it  https://www.zotero.org/groups/critical_editions_typeset_with_edmac_ledmac_and_eledmac/items





Le 24 nov. 2015 � 01:36, fps-vogel <notifications@github.com> a �crit :

**Comment by maieul** [comment]
I have answered the question on stackexchanged. Please validate it.
