### ISSUE TITLE
\Pages[mainmatter] après \part{}

### ISSUE THREAD

**Issue by ralessi** [maieul/ledmac#463]
Comment faire quand on a une stucture telle que:
````
\mainmatter
\part*{Titre du traité tout seul sur une belle page}
\phantomsection
\addcontentsline{toc}{part}{Titre du traité}
[édition proprement dite avec texte et traduction en vis à vis]
````

Dans ce cas, on est bien obligé de mettre \mainmatter juste avant \part{}. De plus, \part{} peut générer des pages vides (une avant, et une après).

**Comment by maieul** [comment]
cf #408

**Comment by maieul** [comment]
Problème de double page:
- cause -> le `\null` dans `\@endpart`
- solution -> on ne peut pas vraiment faire de solution reledmac, car le pb se pose AVANT que `\Pages` ne soit appelés.  Solution : mettre 
````
\makeatletter
\patchcmd{\@endpart}{\null}{}{}{}
\makeatother
````
 dans le préambule. Et si on qu'un seul `\part` concerné, on fait ainsi:
````
\begingroup
\makeatletter
\patchcmd{\@endpart}{\null}{}{}{}
\makeatother
\part*{Titre du traité tout seul sur une belle page}
\addcontentsline{toc}{part}{Titre du traité}
\endgroup
`````

**Comment by maieul** [comment]
je ne suis pas s�r de bien saisir le probl�me avec mainmatter. Tu peux me faire un MWE en me disant pr�cisement ce qui ne va pas (suis un peu fatigu�� et beaucoup de code tex en ce moment)

**Comment by ralessi** [comment]
Je vais essayer avec les pistes que tu donnes. Pour le mwe, ce n'est pas facile, car celui que j'ai fait hier soir ne pose pas de problème, contrairement au fichier plus complexe de mon édition. Par exemple, ceci ne pose pas de problème:
````
\documentclass[openany]{book}
\usepackage{subfiles}
\usepackage{geometry}
\usepackage{fontspec}

\usepackage{reledmac}
\usepackage[sameparallelpagenumber, prevpgstyle=empty, advancedshiftedpstarts,
nomaxlines]{reledpar}

\begin{document}
\frontmatter
\chapter{Introduction}
Texte de l'introduction

\mainmatter
\part*{Titre du traité}
\subfile{livre1}
%\subfile{livre2}%, etc.
\end{document}
````
avec ceci:
````
\documentclass[mwe]{subfiles}

\begin{document}

\begin{pages}
  \begin{Leftside}
    \beginnumbering
    \pstart
    Texte du côté gauche.
    \pend
    \endnumbering
  \end{Leftside}
  \begin{Rightside}
    \beginnumbering
    \pstart
    Texte du côté droit.
    \pend
    \endnumbering
  \end{Rightside}
\end{pages}
\Pages

\end{document}
````

Il faut donc que je trouve comment produire l'incident. Je chercherai ce soir.

**Comment by maieul** [comment]
oui. essaie de me trouver un MWE. On pourra alors voir ce qui est int�grable ou pas dans reledpar. A mon avis il y a une solution autre que celle du patch de `\@afterpart` mais je suis un peu la t�te dans le brouillard pour �tre capable de bien analyser la mani�re dont reledpar proc�de...

**Comment by ralessi** [comment]
C'est d'accord. Actuellement, avec cette structure `\Pages` me donne deux pages vides, dont la première ne contient qu'un point (.). et avec `\Pages[mainmatter] une seule page vide avec un point, avec pour effet d'inverser les leftpages et les rightpages.

Plus de pb si j'enlève `\part`.

**Comment by maieul** [comment]
"cette structure" : laquelle?

**Comment by ralessi** [comment]
Avec comme tu le vois un télescopage dans la zone d'en-tête à droite. Editiones uel studia, c'est la liste des éditions utilisées dans l'apparat critique qui est générée dans `\frontmatter` par un `printshorthands` juste avant `\mainmatter`, etc.

![screenshot](https://cloud.githubusercontent.com/assets/389498/11364936/8d82a08c-92a3-11e5-8874-88f4b0f6aec8.png)

**Comment by ralessi** [comment]
La structure du mwe

**Comment by ralessi** [comment]
Et c'est quoi ce point? J'ai le même truc à chaque démarrage de section: une paire de pages vides, avec un point sur la première, et tout s'arrange si j'enlève se fichu `\part`.

Ce sera d'ailleurs peut-être la solution si je n'arrive pas à faire le mwe.

**Comment by maieul** [comment]
heu, tu peux me fournir ce qui produit le MWE qui a produit ce que tu as mis en copie d'ecran ? je decroche là

**Comment by ralessi** [comment]
Pardon: c'est moi qui ne suis pas clair. Ce qui a produit la copie d'écran, c'est mon édition, pas le mwe hélas!

**Comment by ralessi** [comment]
Précision: dans le fichier de mon édition, si je fais:
````
\mainmatter
% \part*{Épidémies~II}
% \phantomsection
% \addcontentsline{toc}{part}{Épidémies~II}
````
Donc en supprimant `part`, j'ai la double page. Mais avec:
````
%\mainmatter
% \part*{Épidémies~II}
% \phantomsection
% \addcontentsline{toc}{part}{Épidémies~II}
```
Donc en supprimant tout, c'est bon. Le problème ne vient donc pas de `\part`.

**Comment by maieul** [comment]
Je ne sais pas trop comment tu travailles. Moi j'ai fichier qui contient mon preambule classique, que je charge systematiquement. Si je constate un souci, je procède comme cela:
- faire un MWE sans ce preambule, et voir s'il y a souci.
- si ce MWE sans preambule n'a pas de souci, y rajouter mon preambule.

Vu que ton . apparaît uniquement sur ton fichier et pas ton MWE, alors test ton MWE avec ton preambule perso.

**Comment by ralessi** [comment]
Oui, c'est exactement ce que je suis en train de faire. Mais c'est compliqué, car juste avant mon `\mainmatter`, le `\frontmatter` se termine par un `\printshorthands` Il faut donc que je contruise un mwe qui génère quelque chose à ce niveau-là...

**Comment by maieul** [comment]
je comprend. l'exercice du MWE est tjr delicat.  mais souvent quand on l'a achev�, on a la solution...

**Comment by ralessi** [comment]
Et là, ce n'est pas facile! J'essaie ce soir.

**Comment by ralessi** [comment]
Ce n'est pas gagné pour ce ticket. J'essaierai de nouveau un peu plus tard, sinon il faudra vivre avec!

Ou alors un bisect avec la dernière version qui marchait. C'était avant l'introduction des options de synchronisation je crois.  J'essaierai de voir.

**Comment by maieul** [comment]
ce serait un bug reledmac? ou bien tu a chang� des choses chez toi ?

**Comment by ralessi** [comment]
Faute de mwe, je ne sais pas si c'est dû à reledmac, et je commence à en douter.

Ce qui est sûr, c'est que si je remplace:
````
\mainmatter
\part*{Titre du traité}
\phantomsection
\addcontentsline{toc}{part}{Titre du traité}
\subfile{livre1}
\subfile{livre2}
\subfile{livre3} % etc.
````
par
````
\mainmatter
\vspace*{.3\textheight}
\centerline{\Huge Titre du traité}
\phantomsection
\addcontentsline{toc}{part}{Titre du traité}
\vspace*{\fill}
\subfile{livre1}
\subfile{livre2}
\subfile{livre3}% etc.
````
Tout est parfait, et même pas besoin de passer par `\Pages[mainmatter]`.

Alors je me pose la question: si le problème, qu'il soit dû à reledmac ou pas, se limite à cela, à quoi bon se casser la tête?

Je propose de laisser le ticket ouvert une semaine, le temps que je refasse tout étape par étape. As-tu une idée de ce qui, dans le code de reledmac, pourrait laisser un point sur une page vide?

**Comment by maieul** [comment]
je ne vois vraiment pas. Mais le code de reledmac est complexe.

Si tu pense que ca marchait AVANT l'int�gration des options de synchronismes, alors teste peut �tre juste le pr�c�dent tags, � savoir https://github.com/maieul/ledmac/releases/tag/mac2.3.0-par2.5.0 ?

**Comment by ralessi** [comment]
Je vais essayer.

Mais il y a du nouveau: oui, je pense maintenant à un bug de reledmac. En fait, en parcourant mon édition, j'ai vu que si la première section sort bien avec l'astuce décrite ci-dessus, toutes les autres sections ont une deux pages vides avec un point sur la première des deux!

Alors j'ai essayé de supprimer le `\mainmatter` et de mettre pour les sections suivantes un `\Pages[mainmatter]`. Et voici le résultat:
````
! Undefined control sequence.
<argument> \c@par@par@page 
                           
l.1714 \Pages[mainmatter]
````
Catastrophe. Je vais tout annuler, et voir avec la branche dont tu parles.

**Comment by maieul** [comment]
a oui l� c'est clairement un bug de reledmac.

Peux-�tre faire un MWE sur ce bug ? si je le r�soud (ce week-end, j'au trop pass� de temps sur #464), peut �tre que les autres bugs seraient aussi r�solus?

**Comment by ralessi** [comment]
Oui, je vais m'acharner sur ce mwe.

Mais aussi peut-être procéder par regressions successives: première constatation: le bug est déjà présent dans la branche mac-2.3.0-par-2.5.0.

**Comment by ralessi** [comment]
On avance!

Le bug n'est pas dans la branche https://github.com/maieul/ledmac/releases/tag/mac2.2.2-par2.4.0

Il a donc été introduit dans la branche suivante! Il faut faire un bisect.

**Comment by maieul** [comment]
git c'est beau ;-)

**Comment by ralessi** [comment]
Ah oui, je suis bien d'accord!

La branche mac2.2.2-par2.4.0, je me souviens que c'est elle qui introduisait de grands espaces blancs entre les unités dans l'apparat critique. Ils sont de nouveau là.

**Comment by maieul** [comment]
ah ? je me souviens plus de ce bug. ils sont "de nouveau l�" o� ? sur la branch actuelle?

**Comment by maieul** [comment]
a je me souviens. et tu calomnie. Ce n'est pas reledmac qui a introduit cela, c'est bidi qui a cass� reledmac, lequel a du rattraper les choses apr�s coup...

**Comment by ralessi** [comment]
Ah mais oui, tu as parfaitement raison, bidi était le seul coupable, je m'en souviens maintenant! Du coup, comme un âne que je suis, j'ai beau régresser, j'ai toujours les espaces.

C'est en fait bidi qu'il faut régresser!

**Comment by ralessi** [comment]
Je vais devoir y aller, mais je serai au travail tôt demain matin.

**Comment by maieul** [comment]
yep. de toute facon je ne pense pas m'en occuper avant ce week-end.

Est-ce que tu penses par contre pouvoir corriger l'anglais pour la branche 2.7.0 ? il y a pas mal de correction de bugs importants, et j'aimerai bien la sortir rapidement

**Comment by ralessi** [comment]
Ok, je vois demain.

**Comment by maieul** [comment]
ok merci. D'ailleurs tu pourra constater qu'il y a tellement de modif que github n'est plus capable de les afficher pour reledmac.dtx

du coup il faut que tu fasse le diff toi m�me en te placant localement dans la branche 2.7.0-2.6.2

git diff english2 reledmac.dtx

**Comment by maieul** [comment]
bon, je clos ce ticket qui est vraiment confus. Rouvre en un nouveau dès que tu y vois clair sur ce qui posse problème et ou

**Comment by ralessi** [comment]
Je comprends. Je viens de constater que la dernière version présente évidemment le problème. Faute de temps, je m'en remets au hasard pour trouver ce qui ne va pas, et en attendant je bloque sur la version mac2.2.2-par2.4.0 + le patch de bidi. Qui sait? C'est peut-être la fin de mon édition de texte qui va régler ce problème que je suis apparemment le seul à avoir!

D'ailleurs, je trouve que la mise en page est meilleure qu'avec la dernière version qui me donne avec le même texte un nombre assez considérable de overfull hbox.

**Comment by maieul** [comment]
ah bon? des overfulls hboxes? ne devrait pas arriver...

**Comment by ralessi** [comment]
Oui, enfin, il faut savoir que je n'utilise pas polyglossia. Je coupe les mots à la main quand il le faut.

Cela dit, avec l'ancien reledmac, je n'avais plus un seul overfull hbox, et avec le nouveau j'en ai plein.

Mais c'est moins embêtant qu'une paire de pages vides avec un point à chaque nouvelle section.

**Comment by maieul** [comment]
peut �tre, mais c'est peut �tre reli�. 

Donc un MWE sur ce point avec un diff  serait sans doute un premier pas.

**Comment by maieul** [comment]
je m'explique : vu ce que j'ai modifi�, il n'y a AUCUNE raison d'avoir plus de overfull hbox. Donc c'est un effet de bord. et rien que ca c'est pas glop

**Comment by ralessi** [comment]
Oui c'est vrai. Mince alors. Et puis ce n'est pas bien de rester sur une ancienne version qui marche. Il faut que je voie pour ce mwe.

**Comment by maieul** [comment]
penses tu avoir le tps de faire ces MWE ? c'est vraiment stressant d'avoir une version que l'on sait bugée dans la nature.

**Comment by ralessi** [comment]
C'est que j'ai malheureusement très peu de temps en ce moment. Mes quelques tentatives n'ont pas abouti. Je me demande si le problème est dû non pas à une suite de commandes dans le préambule, mais plutôt à un certain niveau de complexité du texte et des notes critiques qui l'accompagnent. Il faudra que je reprenne la question, mais ce sera difficile de le faire à 100% avant fin janvier. Je ferai néanmoins des tentatives.

Car il me semble que le "dummy text" passe bien. Mais pas le vrai texte, sauf avec la version 2.2.2-2.4.0 qui ne me pose aucun problème.  Du coup, pour pouvoir continuer à travailler, je me suis bloqué sur cette version.

Je ne crois pas que le problème soit forcément lié à l'option mainmatter de \Pages, même si j'ai constaté un problème qui ne devrait absolument jamais arriver: d'une compilation à l'autre, sans rien changer j'ai un message 'undefined command' avec \Pages[mainmatter]

As-tu fait beaucoup de changements entre 2.2.2-2.4.0 et 2.3.0-2.5.0?

**Comment by maieul** [comment]
ok.

Non pas tellement de changement entre ces deux versions.

cf https://huit.re/l5tLzjw6

**Comment by maieul** [comment]
sans doute le changement à l'origine du pb est celui-ci https://github.com/maieul/ledmac/compare/mac2.2.2-par2.4.0...mac2.3.0-par2.5.0#diff-2e40dc64935bc56cb699a8c540e2b7a1L3334 (et l'équivalent à droite). Mais pourquoi cela te pose problème ? mystère. Je sais que j'ai fait le changement pour résoudre des bugs sur la poesie en colonnes.

**Comment by ralessi** [comment]
J'ai trouvé: je viens d'enlever les \linenummargin{inner} que j'avais dans les environnements Rightside pour les remplacer par un seul \linenummarginR{inner} dans le préambule, et je n'ai plus les doubles pages vides avec un point.

Nous avançons! Il reste à regarder dans le code où est l'erreur.

Il faut maintenant comparer le nombre d'overfull hboxes entre la version 2.2.1-2.4.0 et la dernière version.

**Comment by maieul** [comment]
ah ah ! bon ben je re-ouvre.

**Comment by maieul** [comment]
bon, pour clarifier le pb de points va migrer en #470

**Comment by maieul** [comment]
la branche #470 devrait resoudre le pb
