### ISSUE TITLE
Font-switching problems reledpar 

### ISSUE THREAD

**Issue by pharos-alexandria** [maieul/ledmac#464]
If I use ```\begin{greek} ... \end{greek}``` in the leftside-environment of my document (left side greek text - right side german text), I don't get the right footnote markers for the normal footnotes in the rightside-environment (i.e. they are in the greek font). This worked until recently. If, instead, I use ```\selectlanguage{greek}``` in the leftside-environment of my document, the footnote markers in the right side are ok (i.e. in the latin font), but for the critical footnote the latin font is used, too (and I have not found any possibility to change the font). 

```
\documentclass{book}

% \usepackage[utf8]{inputenc} 
% \usepackage[T1]{fontenc}
% \usepackage[greek,german]{babel}
\usepackage{fontspec}
\newfontfamily\greekfont[Mapping=tex-text,Script=Greek,Ligatures=Common]{GFS
Neohellenic}
\setromanfont[Mapping=tex-text,Numbers=Lowercase,Ligatures=Common]{Arial}
\usepackage{polyglossia}
\setdefaultlanguage{german}
\setotherlanguage[variant=ancient]{greek}
\usepackage[series={A,B},noeledsec,noend]{reledmac}
\usepackage{reledpar}

\renewcommand*{\thefootnoteA}{\alph{footnoteA}}
%\arrangementX[A]{paragraph}
\begin{document}

\begin{pairs}
\begin{Leftside}
\begin{greek}
%\selectlanguage{greek}
\beginnumbering
\pstart
Ἄνδρα μοι \edtext{ἔννεπε}{\Bfootnote{λέγε Q}}, Μοῦσα…
\pend
\endnumbering
\end{greek}
\end{Leftside}

\begin{Rightside} 
\beginnumbering
\pstart
Et quamquam Philon in tractatu suo de aqueductibus\footnoteA{Philon
  von Byzanz}. Magister Dominicus de Florentia\footnoteA{Dominicus von
  Florenz}
\pend
\endnumbering
\end{Rightside}
\end{pairs}
\Columns
\end{document}
```

**Comment by maieul** [comment]
sorry for the inconviance with footnote number. Is to provide the possibility to have good number order when having the same footnote series in left and right side, but there is many border effect.

Notes for me
> The first bad commit could be any of:
 3e28093221c0a043fb23e43e37ee465fbe518fef
 2b1d8417ca450bc315044aa5650db16476032f51
 dc815c183409c70270c332b97abdfbc9c6b2bd93
 9c51919515c9234f22c7ed6fb85126c8db2c877c
We cannot bisect more!

**Comment by maieul** [comment]
* 3e28093221c0a043fb23e43e37ee465fbe518fef-> pas un probleme.
* 2b1d8417ca450bc315044aa5650db16476032f51 -> peut être
* dc815c183409c70270c332b97abdfbc9c6b2bd93 > peut être
* 9c51919515c9234f22c7ed6fb85126c8db2c877c  > peut être

**Comment by maieul** [comment]
notes perso encore: le problème est que \thefootnoteA est désormais interprété au moment de l'insertion de la note. OR a ce moment là \@alph a été transformé par polyglossia en "\protect \greeknumber {#1}"-> mais pourquoi diable ai je cela ici ?

**Comment by maieul** [comment]
````
\documentclass{article}
\usepackage{polyglossia,fontspec}
\setmainfont{Linux Libertine O}
\setmainlanguage{english}
\setotherlanguage{greek}
\begin{document}
\makeatletter
\meaning\@alph
\selectlanguage{greek}
\meaning\@alph
\selectlanguage{english}

\meaning\@alph
\end{document}
`````
on voit clairement un bug

**Comment by maieul** [comment]
cf https://github.com/reutenauer/polyglossia/issues/119.

Bon d'ici que ce soit debugé, faut que moi je trouve une solution

**Comment by maieul** [comment]
@pharos-alexandria. So it was not a problem of font-switching, but of number-representation switching, linked to seems like a bug of polyglossia. Please try branch "issue464" which should solve it for reledmac.

**Comment by pharos-alexandria** [comment]
It works also with my files. Thanks!

**Comment by maieul** [comment]
you're welcome.
