### ISSUE TITLE
Automating the disambiguation of identical words in the apparatus

### ISSUE THREAD

**Issue by MarjorieBurghart** [maieul/ledmac#467]
Hello! 

When the same word occurs more than once on the same line in the base text of the edition, and a critical notes gives a variant reading for one of those words, reledmac offers a mechanism to disambiguate which occurrence word is the object of this critical note, with \sameword. 
But tagging with \sameword all words identical with a lemma is not very easy, and really time-consuming if done by hand. 

It would be really nice to have a feature that would automatically tag as \sameword words identical to a lemma that could occur on the same line. That would be especially useful when converting long texts from e.g. TEI XML. 

Thanks in advance for your help!

**Comment by maieul** [comment]
1. Maybe we could do it automatically, but it will be very time consuming when running LaTeX, and not very useful.
2. The best way would be to develop a generic script which automatically add \sameword.

**Comment by floriandk** [comment]
Just wondering whether you already know if or when you will find the time to implement an automatic `\sameword`-mechanism or provide a script for pre-processing. (not to pester, just to find out whether I'll need to find a solution myself for my current project or not...)

**Comment by maieul** [comment]
no I won't have time before many time, and this issue is on the bottom of my priority list on reledmac. 

Auxiliary script is I thinks the more efficient solution, but has many complication to be sure to not add command in sameword

**Comment by floriandk** [comment]
thanks a lot for your swift answer! I'll see what I can do myself

**Comment by stenskjaer** [comment]
@floriandk: If you get a chance to work on this, consider sharing the solution and let us know. I think it is something we all could use, and I would certainly be interested in contributing to the development of a script for that purpose. I agree with @maieul that maybe it would be too resource consuming to let LaTeX take care of the problem.

**Comment by floriandk** [comment]
I'm now struggeling with this problem again and have to realize that my attempts on preprocessing are very slow and error-ridden. You mention on [stackexchange](http://tex.stackexchange.com/q/280967) that you already have a python script doing this. Would you mind sharing it, so we could try to adapt it to our needs?

**Comment by maieul** [comment]
sorry, I can't, because my script is not clean, and the part which treat this problem is imbricated in other part…«

**Comment by stenskjaer** [comment]
That's fair enough. But I wonder: If you can locate the section or basic functionality that does the disambiguation, we might be able to make this sort of script together. I would also (as mentioned above) be interested in a solution to this.

**Comment by maieul** [comment]
Basically, I have a ordered list of all the words. When I ouput a word in my .tex file, I read in this list is there is the same word in n position before/later, and I add sameword if needed.

But I am very sorry, my code is too bad to be useful

**Comment by stenskjaer** [comment]
Well, that's a good place to start. It shouldn't be impossible to make something with that idea (although I can't do it right now, as I am busy with too many other things, but I will need myself soon). How many words distance do you find useful in identifying a possible conflict? 30?

**Comment by maieul** [comment]
yes, I think i set it to 30, but that could be set up to an other.

**Comment by stenskjaer** [comment]
Hi guys! Just to let you know, I have just now pushed my first stab at this problem to github. You can see my work here: https://github.com/stenskjaer/samewords.

Any feedback and bug reports are very welcome!

**Comment by maieul** [comment]
sorry, I have no time yet…

**Comment by floriandk** [comment]
@stenskjaer Perfect! Really happy you are sharing this. I'll be trying to get it to work and test on a big project the following days and weeks.

**Comment by maieul** [comment]
I close this issue. @stenskjaer when you will get a stable file, please push it on CTAN. I will mentionn it on the handbook.

**Comment by stenskjaer** [comment]
@floriandk Awesome! I will look forward to hearing how it works for you. Right now I'm implementing the last details with the nested samewords commands, and then there should be a working beta. But any comments or feedback are very welcome in the repo!

@maieul Sure. It won't be a TeX package. It's a python script, so I will put it on PyPi when it is stable enough. And then I'll let you know.

**Comment by maieul** [comment]
ok, but there is also some python script on CTAN, when related to TeX. (for exemple TLG2LaTeX)

**Comment by stenskjaer** [comment]
Cool... I'll put it up there too then. I didn't know if that was accepted (I couldn't really see it in there).

**Comment by maieul** [comment]
I don't understand your message. What about do you speak?

**Comment by stenskjaer** [comment]
I was just unsure whether any non-TeX software was welcome on CTAN. But as you wrote that it shouldn't be a problem, I'll but the same word disambiguation script that I have been working on (in Python) up there when it's stable.

**Comment by maieul** [comment]
yes it is not a problem to push it on CTAN, if it is related to TeX. There is many pre-processor script on it.

**Comment by stenskjaer** [comment]
So, sorry that I keep resurrecting this thread. Just want to say that I now have a beta version of my sameword annotation script that is usable for my use cases. It handles a good range of different situations flexibly, and is really simple to use. 
As mentioned, you can find it here: https://github.com/stenskjaer/samewords

The only thing is that I would love some help on testing it on texts that I have not made or processed myself to see how it handles that. 
So @floriandk or @MarjorieBurghart, if any of you get a chance to give it a try, I would be very interested in hearing about any problems you find.
And @maieul, I wonder whether you think we should put a note about this into the handbook now, although it is still in a relatively early phase, or you want to wait until it has matured a bit more? The good thing about making a note in the handbook would be that we could get more testers reporting problems.

I realize that installation may be a problem to some, but it should work on both Unix and Windows systems. So if you encounter any problems following the instructions in the readme, it is probably not clear enough. In that case, let me know.

**Comment by maieul** [comment]
I think the notes could be added now, as in any case I am not the maintener, I won’t get user message ;-)

Please open a pull request to the master branch
