### ISSUE TITLE
pb de overfullhboxes

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#468]
cf les remarques de @ralessi en #463.

J'ai le même problème sur un de mes textes. Je regarde.

**Comment by ralessi** [comment]
Ah, c'est presque bien, je dirais.

**Comment by maieul** [comment]
d'avoir le même problème ? oui.

**Comment by maieul** [comment]
tu utilise hyperref? il semblerait chez moi que les problèmes viennent de mes insertions de lien hypertexte pour les notes avec hyperref.

**Comment by ralessi** [comment]
Affirmatif: j'utilise hyperref.

**Comment by maieul** [comment]
et que donne une compile avec la derniere version sans hyperref ?

**Comment by maieul** [comment]
(au niveau des overfulle hboxes)

**Comment by maieul** [comment]
bon, peut tu tester la branche issue468 ? cela devrait résoudre le pb d'overfullhbox, si c'est bien le même que le mien.

**Comment by ralessi** [comment]
C'est beaucoup mieux en effet. Il en reste quelques uns cependant, mais à un niveau très acceptable.

J'ai cependant toujours le pb de deux pages vides avec un point à chaque début de section: retour à 2.2.1-2.4.0!

**Comment by maieul** [comment]
bah ca tant que j'ai pas tes fichiers je ne peux pas savoir. Envoie les moi tel quels et un coup de bisect me permettrait de voir la cause.

**Comment by maieul** [comment]
@ralessi peut tu tester avec la nouvelle version de la branche issue468? chez moi cela résoud le pb.

**Comment by ralessi** [comment]
Hélas pas chez moi. Voici ce qui se produit avec exactement les mêmes fichiers, et juste en passant de mac-2.7.1 à issue468:
- à la 2e passe, la 1re page de mon édition, page de droite, se termine sur la page de gauche suivante.
- si je reviens à mac-2.7.1: cette page passe normalement.

Je précise que c'est la seule différence constatée. Tout le reste me semble normal.

Autre précision: cette page est très complexe, il y a d'ailleurs dedans un \ledpb.

Mais je sens que tu vas me dire que je devrais avoir exactement le même résultat...

**Comment by maieul** [comment]
envoie moi tes fichiers, que je comprenne. on s'en sortira jamais sinon

**Comment by ralessi** [comment]
Bon j'ai du neuf. Ce matin, j'étais en train de te préparer l'échantillon qui ne passe pas, au moment où je me suis aperçu que j'avais laissé dans mon fichier les lignes de patch qui neutralisent la mise à jour de bidi:
````
\makeatletter
\def\bidi@RTL@everypar{\if@RTL{\setbox\z@\lastbox\beginR%
    \ifvoid\z@\else\usebox\z@\fi}\fi}
\makeatother
````
C'était pour pouvoir compiler avec la version de reledmac sur laquelle j'avais décidé de me bloquer il y a 15 jours.

Donc voici ce que je peux dire:
- avec ces lignes de patch, j'ai le problème, à savoir: compilation sans problème avec la version 2.7.1, et page de droite qui se termine sur une page de gauche avec issue468
- sans les lignes de patch (ce qui est normal), je confirme que je n'ai plus le problème.

Dis-moi si le fichier t'intéresse toujours, ou si tu peux fermer le ticket avec ces informations.

**Comment by maieul** [comment]
ouf, cela me rassure. donc oui on va pouvoir fermer.

**Comment by ralessi** [comment]
Parfait. Désolé d'avoir oublié ces lignes. Je passe donc à la poubelle les fichiers que j'allais t'envoyer.

**Comment by maieul** [comment]
pense tu pvr faire la correction de l'anglais aujourd'hui ? le bug �tait assez g�nant et j'aimerai sortir rapidement la nouvelle version. (il n'y a pas grand chose au niveau anglais)

https://github.com/maieul/ledmac/compare/english2...2.7.2-2.6.3#files_bucket

**Comment by ralessi** [comment]
D'accord. Je vois en début d'après-midi.

**Comment by maieul** [comment]
merci ! et d�sol� encore pour ce bug impromptu. Mais je continue de penser qu'un lien hypertexte interne est utile (notamment si on utilise des notes de fin plut�t que de bas de page)

**Comment by ralessi** [comment]
Tu as normalement les pull requests.
