### ISSUE TITLE
Problem with \Xhsize command

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#469]
In a long manuscript I am using the floatrow package to position a series of illustrations. The package contains the \Xhsize command, too. So I newly obtain an error message: Command \Xhsize already defined. 
Is this a serious problem?

\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage{floatrow}
\usepackage{reledmac}

\begin{document}

\beginnumbering
\pstart
Omne quod movetur ab aliquo movetur.
\pend
\endnumbering

\end{document}

**Comment by maieul** [comment]
now, it is not a serious problem. We could offer an alternative if reledmac is loaded after floatrow.
But:
- what if charged before -> not possible
- what should be the name?

**Comment by sonator** [comment]
Hm, a new name should correspond to the other names containing X... oder ...X. 
Perhaps something like \Xwidth and \widthX

**Comment by maieul** [comment]
ho, I was thinking to a new name only when floatrow is loaded, but you are right, maybe we could change in any case.

**Comment by sonator** [comment]
Your command names are indeed coherent. So it may be easier to rename the \Xhsize command of reledmac only in the case when floatrow is used.

**Comment by maieul** [comment]
Ok. So let do it: `\Xhsize` when not using floatrow, and `\Xwidth` when using it.

**Comment by maieul** [comment]
I have thought tonight. It is better to have coherent name when using floatrow. So `\Xwidth` and `\widthX`.

**Comment by maieul** [comment]
please try the branch "issue469"

**Comment by sonator** [comment]
The runs of two longer files using reledmac/par and floatrow (floatrow loaded before reledmac/par) have been successful. There are no error messages and no warnings. Thank you for the modifications!

**Comment by maieul** [comment]
you're welcome
