### ISSUE TITLE
sync of parallel text when having a second line in a sectioning-command on one side

### ISSUE THREAD

**Issue by mxordn** [maieul/ledmac#471]
Dear Maïeul,

I don't know if this is worth an issue, but I recently encountered a problem the the parallel pages typesetting when section commands contain different text, while one side needs to open a second row in the title and the other not. In this case the parallel text goes out of sync on that particular page.

I prepared an MWE that is unfortunatly not so minimal, because I was also testing to get to the next page:
https://dl.dropboxusercontent.com/u/5341925/reledmac-test/P1-test.tex

Maybe I did something wrong and I appreciate any help. Currently my workaround to solve the problem is putting \phantomtext{} behind the shorter title.

Best regards
Moritz

P.S: Another question is about this example is: Why is the line numbering per page is hanging over with one line to following page. This happens only here and not in other files I'm using.

**Comment by maieul** [comment]
@mxordn your first issue is the same as #379. I hope to have time a day for this problem. I close this issue and ask you to refer to #379. 

For you ps, see #472
Ps1: please avoid refering to external document. You can pastebin code here. 
Ps2: your MWE was not minimal. For example, many packages and setting do not mean for this problem
