### ISSUE TITLE
Indentation of paragraphed notes in a ledgroup environment

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#487]
In a ledgroup environment the paragraphs of paragraphed critical and familiar notes are unexpectedly indented. If you have time please have a look on the MWE.

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage{reledmac}

\Xarrangement[A]{paragraph}
\arrangementX[A]{paragraph}

\begin{document}

\begin{ledgroup}
\beginnumbering
\pstart
\noindent Omne \edtext{quod}{\Afootnote{quid}} movetur ab aliquo movetur\footnoteA{Arist., Phys. VII,1.}. 
\pend
\endnumbering
\end{ledgroup}

\end{document}

**Comment by maieul** [comment]
please try branch issue487

**Comment by sonator** [comment]
I have tried with success. Thank you very much for the solution!

**Comment by maieul** [comment]
you'r welcome ! and merry christmas!
