### ISSUE TITLE
reledmac \edgls: problem

### ISSUE THREAD

**Issue by lorloz84** [maieul/ledmac#488]
Dear Maieul,
I am sorry to bother you again. I am using the new command \edgls and it works perfectly. 
Do you think it would be possible to define a new command (maybe something like \edglslink) to allow to print alternative text for each glossary entry?
I send you the mwe

\documentclass{article}
\usepackage{polyglossia}
\setotherlanguage{english}
\setmainlanguage{italian}
\usepackage{fbb}
\usepackage[nocritical,noend,noeledsec,series={A},nofamiliar]{reledmac}

\usepackage{glossaries}
\glsSetCompositor{-}
\makeglossaries
\newglossaryentry{monistero}{name={monistero},description={monastero}}  
\newglossaryentry{magicien}{name={magicien},description={sorcier}}  
\newglossaryentry{prova}{name={prova},description={tentativo}}  

\let\glsnoun\glsuseri
%
\begin{document}

\begin{english}
\title{Glossaries}

\maketitle
\begin{abstract}
This file provides example of using \emph{glossaries} package with \emph{reledmac} package.
We use \verb+\edgls+ to add glossary entry referring to page and line number.

Note the use of \verb+\glsSetCompositor+ in the preamble.
\end{abstract}

\end{english}

\beginnumbering
\pstart
In queste nostre contrade fu, ed è ancora, un \edgls{monistero} di donne assai famoso di santità  
(il quale io non nomerò per non diminuire in parte alcuna la fama sua), nel quale, non ha gran 
tempo, non essendovi allora più che otto donne con una badessa, e tutte giovani, era un buono 
omicciuolo d'un loro bellissimo giardino ortolano, il quale, non contentandosi del salario, fatta la 
ragion sua col castaldo delle donne, a Lamporecchio \textbf{\edgls{prova}}, là  ond'egli era, se ne tornò. Quivi, tra gli 
altri che lietamente il raccolsono, fu un  giovane lavoratore forte e robusto e, secondo uom di villa, 
con bella persona e con viso assai piacevole, il cui nome era Masetto; e 
domandollo dove tanto tempo stato fosse. Il buono uomo, che Nuto avea nome, 
gliele disse. \textbf{\glslink{prova}{prove}} Il quale Masetto domandò, di che egli il monistero servisse. \edgls{magicien}
\pend
\endnumbering
\printglossaries

\end{document}

Thank you again for your great work

**Comment by maieul** [comment]
what do you mean by "alternative text" ? I think you problem is more linked to a specific glossary commands, so to the glossary package, than to a reledmac command.

**Comment by lorloz84** [comment]
Sorry if I have not been very specific!

Not so long ago you helped me by defining the command "\edgls" in order to show the line number (and not only the page) of each entry in the glossary of a critical edition.
It worked perfectly.

In my text (which is in italian) I have lots of verbs, that I have to register in the glossary in the infinitive form.
(example: "provare":  \newglossaryentry{provare}{name={provare},description={fare un tentativo}})

If in my texy a verb is in the conjugated form (example "provassimo") I need to refer to the infinitive form in the glossary. The same happens with plural forms, which are registered with the singular form in the glossary.

With the glossary package one can use the command \glslink
(example: \gslink{provare}{provassimo};  or: \gslink{prova}{prove})

Unfortunately, by doing this I do not get the line number for the "alternative form" (i.e. the conjugated form, or the plural form).
I was wondering if you could help me by creating a command similar to \glslink for eledpar, so that the line number is shown in the glossary even for the "alternative form".

I hope I was able to explain myself!
thank you so much
Lorenzo

**Comment by maieul** [comment]
Ok. I don't know glossary package. So be more specific in any case, I don't suppose you reader know you need. I will add this command now.

**Comment by maieul** [comment]
please try the branch issue488 which provides all commands of �6.2 of glossaries-user.pdf prefixed by \ed (and so \edglslink)

**Comment by lorloz84** [comment]
Sorry I don't understand what you mean...

**Comment by maieul** [comment]
please read https://github.com/maieul/ledmac#debug-and-feature-requests to know how to test the branch

**Comment by lorloz84** [comment]
I am trying but I do have some problems in understanding exactly what I should do...

1) I go here: https://github.com/maieul/ledmac/tree/issue488
2) I download the zip file
3) Run the reledmac.ins file with pdf latex
4) create the .sty file 
5) run issue 488.tex file and then report the result

**Comment by maieul** [comment]
Run the reledmac.ins file with pdf latex will create the .sty file. So the 4 does not exist (it is done by 3)

**Comment by lorloz84** [comment]
I get an error message when I run reledmac.ins with pdf latex, I keep trying

**Comment by maieul** [comment]
which is the error message ? are you on windows using miktex? many people have error with .ins file in miktex...

**Comment by lorloz84** [comment]
I am using Texmaker on windows (error: file log not found) and I downloaded texstudio too, but I get another error message. I am not using miktex anymore... I continue trying

**Comment by maieul** [comment]
ouf you are on windows, there is 90 % of chance you use miktex. Miktex is the main windows tex distribution. Stop loosing time, and just dowload the .sty here.

https://drive.switch.ch/public.php?service=files&t=5aa94c2b0a1e1df4c869de98f942b27c

**Comment by lorloz84** [comment]
Thank  you so much! I downloaded the .sty file and it all worked good!! The glossary shows page and line number of the entry!
thank you so much

**Comment by maieul** [comment]
you'r welcome
