### ISSUE TITLE
Reledmac: Add chapter into endnotes – Feature request

### ISSUE THREAD

**Issue by mepherl** [maieul/ledmac#492]
As asked here:
http://tex.stackexchange.com/questions/287148/reledmac-add-chapter-into-endnotes
it would be nice to be able to have text written into the endnotes so that i could produce a separation between numbered text based on the e.g. chapter title. 

At the end of the book, where the endnotes are printed, it should look like this

Letter 1
p. 4 Hotel Sayoy: Comment 1
p. 4 Sonnet: Comment Comment 2
Letter 2
p. 6 Bristol: Comment 3
Letter 3
p. 8 Whatever: Comment 4

Could you make this possible? Thank you!
Martin

**Comment by maieul** [comment]
I need time to do it. 
Should be easy ;-)

**Comment by mepherl** [comment]
Great! No hurry, though! Really! No hurry!

**Comment by maieul** [comment]
I have found time for this issue.

1) First, you have aleready \doendnotesbysection which could be use, as you make a `\beginnumbering` for each chapter. 
2) However, it could be useful to add sectionning command even if we don't restart the `\beginnumbering`. So I have added `toendnotes` command.

Please try the branch "issue492".
You can look on the issue492.tex file and / or read the handbook here https://github.com/maieul/ledmac/blob/1d3fc91fcb8cad7d459219f9c36820c0587bced1/reledmac.dtx#L1295.

Please let me know if you have no time for testing.

**Comment by mepherl** [comment]
thank you! i will test it right away!

**Comment by mepherl** [comment]
I managed to get  \toendnotes[A]{chapter-title} to work as it should, thank you! nice job! 
the only thing which i don't know whether you did it on purpose or not is that i have to put a \newline at the end so that the next endnote isn't printed in the same line. but this is something i can easily deal with.

**Comment by maieul** [comment]
i dont insert endline automatically, because it is simplier to insert manually that to told to don't do it.. Typically, I supposed you would have used \section command �

**Comment by mepherl** [comment]
i thought so! yes, it is no problem adding the new line. 
as for the section command: yes i will use it, but i'm setting up quite a large job with T.E.I.-XML-files (every letter is it's own file) which get translated to reledmac/xelatex automatically via xsl. in the process i have the content of the section in something like a variable, so i just can output it twice, once in the \section-command and the other time in the \toendnotes-command. this is basically what i will do, because the section-command is outside the letter. i don't know if i make myself clear, but a draft of my output would be:

\section{Letter, Aug. 2nd, 1977}

\beginnumbering
\pstart\toendnotes{A}{Letter, Aug. 2nd, 1977\newline}Content of the letter with notes and \edtext{explanations}{\Aendnote{This is a commentary-entry}} bla bla bla
\pend
\endnumbering

\section{Letter, Aug 14th, 1977}
and so on

\doendnotes{A}

**Comment by maieul** [comment]
I think you should use `\endgraf` (end of paragraph) instead of `\newline` (new line)

**Comment by maieul** [comment]
ps: I will post a answer on SE when it will be officialy released (I hope this week-end). Please valide them
