### ISSUE TITLE
setcounter numberpstart failed

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#498]
In the MWE I try to start the numbering of pstarts at the second paragraph with an arbitrary number. But I get an error message: no counter 'numberpstart' defined. Do I misunderstand the manual? If you have time, please have a look on the example. 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage[series={A,B,C},noeledsec,noend]{reledmac}

\begin{document}

\beginnumbering

\pstart
Pro declaratione speculi ardentis \ldots
\pend

\setcounter{numberpstart}{5}
\numberpstarttrue

\pstart
Pyramis orthogonia rotunda \ldots
\pend

\pstart
Superficies plana dividens \ldots
\pend

\endnumbering

\end{document}

**Comment by maieul** [comment]
it was a typo on the handbook

Use \setcounter{pstart}{value}

**Comment by sonator** [comment]
Mon Dieu, quelle simple solution. Merci!
