### ISSUE TITLE
Use of \color can colour line numbers.

### ISSUE THREAD

**Issue by ppasedach** [maieul/ledmac#504]
See the following example. The "5" gets coloured in blue, presumably because that's the active colour at the line break.
```
\documentclass{article}
\usepackage{xcolor,reledmac}
\firstlinenum{1} \linenumincrement{1}
\begin{document}
\beginnumbering
\pstart
\noindent something\\
{\color{blue}something in blue}\\
something else\\
{\color{blue}And now something a bit longer in blue, more than one line, let's see what happens!}\\
And back to normal.
\pend
\endnumbering
\end{document}
```
![auswahl_066](https://cloud.githubusercontent.com/assets/11517856/13426980/5ab1a40e-dfb1-11e5-81d4-5c2f753b1309.png)

**Comment by maieul** [comment]
You have to redefine \numlabfont, as described in  4.3.5 Other settings.

In your case `\renewcommand*{\numlabfont}{\normalfont\scriptsize\color{black}}`
