### ISSUE TITLE
listof command confuses columns

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#507]
Under reledmac 2.7.2 and reledpar 2.6.3 a code as cited in the MWE has worked without problems. Using the current versions the listof command is confusing the columns. But, if the listof command is called after the numbered text, the problem does not occur. 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{reledmac}
\usepackage{reledpar}

\makeatletter
\newcommand\listofSecretum{\section{Dictiones}\@starttoc{sec}}%new list
\newcommand\tsection[1]{\addcontentsline{sec}{section}{#1}}%
\makeatother

\begin{document}

\listofSecretum

\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
\tsection{Prohemium}
Iustum est primum Deo gracias agere etc. etc. etc. etc. etc. etc. etc. etc. etc. 
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Es ist gerecht, zuerst Gott zu danken etc. etc. etc. etc. etc. etc. etc. etc. etc. 
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

%\listofSecretum

\end{document}

**Comment by maieul** [comment]
3f2ed1ffc278da89e64ad33605d837662f7ba17e is the cause of problem. I look on it.

**Comment by sonator** [comment]
Thank you!

**Comment by maieul** [comment]
it is not `\listof` but `\section` which provokes the problem

**Comment by maieul** [comment]
please try  branch issue507

**Comment by sonator** [comment]
Respect! Your solution is running for part, chapter and subsection, too. I will test it on a 200 pages manuscript.

**Comment by maieul** [comment]
please, let me know, if possible quickly (it a a serious bug, but not very hard to solve)

**Comment by sonator** [comment]
As expected the test was successful. Once more thank you very much for the support!

**Comment by maieul** [comment]
your'e welcome. I will publish it right now on CTAN.
