### ISSUE TITLE
Columns : print the left line number, even if line is empty

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#509]
on #368, @Alessio-R

> I have tested your new package and it worked fine. Can you make possible to print the right column margin numbers in the left page margin, in place of those of the left column?

I have to add an option to print even if the left line is empty.

**Comment by Alessio-R** [comment]
Yes, it would be a very useful option.

**Comment by maieul** [comment]
personnal note

`````
\newcommand*{\do@lineL}{%
  \letcs{\ifnumberpstart}{numberpstart@L\the\l@dpscL}%
  \advance\countLline \@ne%
  \ifvbox\namebox{l@dLcolrawbox\the\l@dpscL}%
    {\vbadness=10000%
     \splittopskip=\z@%
     \do@lineLhook%
     \l@demptyd@ta%
     \global\setbox\one@line=\vsplit\namebox{l@dLcolrawbox\the\l@dpscL}%
                           to\baselineskip}%
    \IfStrEq{\splitfirstmarks\parledgroup@}{begin}{\parledgroup@notes@startL}{}%
    \unvbox\one@line \global\setbox\one@line=\lastbox%
    \@writepageofparL%
    \getline@numL%
    \ifnum\@lock>\@ne%
      \inserthangingsymboltrue%
    \else%
      \inserthangingsymbolfalse%
    \fi%
    \setbox\l@dleftbox%
    \hb@xt@ \Lcolwidth{%
      \ifl@dhidenumber%
        \global\l@dhidenumberfalse%
        \f@x@l@cks%
      \else%
        \affixline@num%
      \fi%
      \xifinlist{\the\l@dpscL}{\eled@sections@@}%
        {\add@inserts\affixside@note}%
        {\print@lineL}%
      }%
    \add@penaltiesL%
    \global\advance\@donereallinesL\@ne%
    \global\advance\@donetotallinesL\@ne%
  \else%
    \setbox\l@dleftbox \hb@xt@ \Lcolwidth{%
      \getline@numL%
      \affixline@num%
      \l@dld@ta %
      \new@lineL%
      \hspace*{\Lcolwidth}%
    }%
    \global\advance\@donetotallinesL\@ne%
  \fi%
}%
`````

mais il faut d'abord que j'acheve le travail sur #368 en résolvant #510

**Comment by Alessio-R** [comment]
How can I do to test it?

**Comment by maieul** [comment]
it is written "personnal note". so it just some piece of code for me. please wait me asking you to test.

**Comment by maieul** [comment]
so @Alessio-R, now you can try the branch issue509. It provides a new command `\linenumberLevenifblanktrue` which do what you want if called in the preamble. Just add also `\firstlinenumR{10000000}` to not print right line number. See the file issue509.tex for an example.

**Comment by Alessio-R** [comment]
Ok thank you! How can I do to install it? I found the .dtx here https://github.com/maieul/ledmac/blob/issue509/reledmac.dtx but if I replace the existing reledmac.dtx file in the tex folder it didn'works.

**Comment by maieul** [comment]
please read the handbook� https://github.com/maieul/ledmac#debug-and-feature-requests
you must run the two .ins file to get the .sty file, to put them along your .tex files.

**Comment by Alessio-R** [comment]
Ok I have tested it and it works perfectly. Thank you for adding this useful option!

**Comment by maieul** [comment]
your'e welcome. I have to modify the handbook, and then to publish it�
