### ISSUE TITLE
AtEveryStanza and AtEveryStopStanza

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#515]
Cf https://tex.stackexchange.com/a/302778/7712

**Comment by maieul** [comment]
@tweh the branch issue515 provides AtEveryStanza and AtEveryStopStanza. It will avoid you the hack mentionned in SE. COuld you test it ?

**Comment by maieul** [comment]
moved to the release branch on 2.10.0-2.9.0

**Comment by tweh** [comment]
Hi,

I’ll test it as soon as possible. :-)

Best,
Tobi

—

Tobi W_


Tobias Weh
Spindelstraße 25
49080 Osnabrück

+49 541 40757837

mail@tobiw.de
http://tobiw.de

**Comment by tweh** [comment]
The new feature works fine. Also in my real life project. Thanks!

**Comment by maieul** [comment]
Your welcome. Please validate the new answer on SE.
