### ISSUE TITLE
Overal direction of critical notes LTR with RTL text

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#517]
cf http://tex.stackexchange.com/a/306975/7712.

**Comment by maieul** [comment]
Robert Voogdgeert, please try branch issue517 (read https://github.com/maieul/ledmac#debug-and-feature-requests to know how to test it). You will find in the zip a issue517.tex file as example, with explanation,

Please made feebdack here, and not in SE:

**Comment by rvoogdgeert** [comment]
Maieul, it works really well. But only with one footnote systeem \Afootnote. As soon as I enter a \Bfootnote somewhere an 'undefined control sequence <argument> \Bfootnote' error is raised.

**Comment by rvoogdgeert** [comment]
Sorry, I just now read the complete preamble and saw the `\usepackage[noend,nofamiliar,noeledsec,series={A}]{reledmac}`
which I changed to
`\usepackage[noend,nofamiliar,noeledsec,series={A,B}]{reledmac}`
and of course now it does work.

**Comment by maieul** [comment]
Nice ! I wait for feedback from @ralessi with LuaLaTeX, and I hope to publish it next week-end.
