### ISSUE TITLE
Apparatus of manuscripts

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#522]
In some editions, you can see an "apparatus of manuscripts" above the "apparatus of textual variants". It shows the manuscripts that are in use for the given page. It makes sense in cases where you have fragmentary manuscripts.

So for example, you have manuscripts A and B. A runs from page 1 to 5, B has only page 2, 4, 5. So in that apparatus, you'd have "A, B" given on page 2, 4, 5 and only "A" given on page 1 and 3. This way you know why there are no textual variants given on page 1 and 3, as they are only attested in A, and not in B.

Is something like that possible with reledmac?

**Comment by maieul** [comment]
I see what you mean. I need it for my own project. I have some idea, but not tested. I have some idea, but I need some test. Let me the week-end to test

**Comment by maieul** [comment]
what about for page without note ?

**Comment by maieul** [comment]
and what if we have a change in the middle of the page ?

**Comment by baem2** [comment]
For pages without notes, the manuscripts should be shown anyway, so that you always know where the given text is attested.

For a change in the middle of the page, it could make sense to add the possibility to give line numbers; like this:

A; B (line 7--12)

Of course, things can be way more complex (and manuscripts can be very fragmented). But I think the precision of line numbers should be fine, it's not possible to be more precise, it will be too convoluted soon ...

**Comment by maieul** [comment]
OK, Here some personnal note for myself:

- Some case:
  - all the page : no line number
  - part of the page : begining list number / end line number. If the begining line is in an other page, use first line of the current page number. And if the beginin line is in an other page, use last line of the current page number.
- User interface : 
   -`\defms{<ms>}`, could be called in any line. Redefine the ms.
   - Will be inserted as a critical footnote, so with all the `\Xhook possible`.  
   - So user will have to set the critical note level used.
   - Will be printed as any other line critical note : line-number `<lemma> <lemmaseparator> <notecontent>`:
      - `<notecontent>` will be the manuscript
      - `<lemma>` will be by default "Manuscriptum" but could be redefined by user, 
- Implementation:
  - We will need to automatically insert note at the begining of any page, before any other thing. We will do it for the first series of MS of the page, not for the other one, which will be inserted in the good line
  - We will need automatically crossref (something like `beginms@<msnumber> `and `endms@<msnumber>`,, number will be increased on each `\defms`). 
  - *We also will need automatically line number of the first line of a page (how could we get it?) and of the last line*
  - In auxiliary file, we will note:
       -  `<msnumber>`
       -  `<ms>`
       - (absolute line number where `\defms` was called ? I dont think it is need, as `\nl` has counter).
       - (same think for page number)
 - When processing the second run we need 
   - for each `<msnumber>`:
      - the `<ms>`
      - the page number
      - the absolute  line number
  - a list of the absolute line number where a `\defms` is called (not necessary, could be manage by `
 - At the begining of each page (*HOW we do it?*), we will insert a footnote, by calling `v<series>footnote`:
        - get the last ms list of the previous page will be easy
        - The first line of the page will be easy. Will be print only if other `\defms` was called in the same page
        -  get the line number of the next  `\defms` will be easy. And so, get the page number should be also easy. If page number is the same as the current page, won't be printed. If there is no more \defms, will be easy so.
 - At EveryLine, we will look if there is a `\defms` is called for this line (normally, if i am right, with `\inserts@list`), and we will insert footnote using `v<series>footnote`. 
 - Other problem: do it compatibile with reledpar. We will use L or R mark.

**Comment by maieul** [comment]
note : `msdata` will be more semantically correct.

**Comment by maieul** [comment]
ok, I have worked this week-end, but there is many, many related problem. So for next week-end.

**Comment by maieul** [comment]
@baem2 I think I have a functional feature. I will document it tomorrow. But see this MWE.

For the need of the test, I made a test with  one manuscript only buy specifice section. On the right side, on note the begining of "msdata section". And in the footnote, there is automatically the start and stop line number in the current page, no line number if it is in the full page.

[issue522-21mai.pdf](https://github.com/maieul/ledmac/files/276057/issue522-21mai.pdf)

**Comment by baem2** [comment]
This is great, thanks! This is exactly what I meant and it is looking really good

Now two things should be possible:
a) That the manuscripts are overlapping or showing the same section of text.
b) That you can choose if the manuscripts names show on the side or in the footnotes or both.

Tomorrow in the morning I am flying to Rome to check a manuscript in the Biblioteca Apostolica, so I probably won't be able to check it before the week after that.

**Comment by maieul** [comment]
formally, your point a and b are not impacted by my implementation. It is just my example which is like this.
The only thing my implementation do is to allow to insert the "manuscript apparatus". The content if this manuscriptus apparatus could be any string.

**Comment by maieul** [comment]
So, now, I have written the handbook. You can read it on 

https://github.com/maieul/ledmac/blob/issue522/reledmac.dtx#L1490

And a example file is on https://github.com/maieul/ledmac/blob/issue522/issue522.tex

So If I understand, you could look on it on week of the 30th may?

**Comment by baem2** [comment]
I just tried it with my project, and it works like a charm. It is exactly what I needed! Thank you very much! And it is looking great, very professional.

One minor thing: If, as in your example, I use ``\setmsdatalabel{}``, there always is a space before the lemma separator, and I was not able to remove it.

**Comment by maieul** [comment]
It is not a space before the lemma separator, but after the line number;-).

You can delete it using `\Xafternumber[A]{0pt}`. I didn't see it because, in French beautiful typography, there is a space before the colon ;-).

Thanks for your tests and corrections. I will publish it in the week.

**Comment by baem2** [comment]
Good to know, thanks :)
