### ISSUE TITLE
\prenotesX broken

### ISSUE THREAD

**Issue by dariok** [maieul/ledmac#523]
Dear Maieul,
it seems that `\prenotesX` is broken. Using

    \documentclass{book}
    
    \usepackage{reledmac}
    \prenotesX{0.35\baselineskip plus 0.4\baselineskip minus 0.1\baselineskip}
    \afterruleX[A]{0.25\baselineskip}
    \afterruleX[B]{0.25\baselineskip}
    
    \begin{document}
        asdfa sdf \footnoteA{tst}
    \end{document}

throws `! Missing number, treated as zero.
<to be read again> 
                   \relax 
l.10 \end{document}`.

In a longer document in `nonstopmode`, I get `+0.25` (or `+0pt` if no `\afterrule` is present) written immediately above the first footnoterule of every page and quite a few `! Missing number` and `! Illegal unit of measure` at various places.

If you need more information, please let me know.

Thanks very much,
Dario

**Comment by maieul** [comment]
it seems flexible way has never work with prenotesX. So it is not broken, but not featured. Or do you have older version of eledmac/reledmac which was working ?

**Comment by maieul** [comment]
please try the branch "issue523". Should solve this issue.

**Comment by maieul** [comment]
hi @dariok some feedback ?

**Comment by dariok** [comment]
Hi Maieul,
thank you for your incredibly fast work!

As far as I can see, it now works well except when `\arrangementX[A]{paragraph}` is used. I guess this will be more complicated?

Dario

**Comment by maieul** [comment]
are you sure ? my example on https://github.com/maieul/ledmac/blob/332f51c1c58823fb970606abc4acc0f96eecdd69/issue523.tex works perfectly�

**Comment by maieul** [comment]
should it be possible to have quickly an answer ? I would like to release a fixbug release…

**Comment by dariok** [comment]
I have just retested it. The following:

    \documentclass{book}

    \usepackage{reledmac}
    \arrangementX[A]{paragraph}
    \prenotesX{0.35\baselineskip plus 0.4\baselineskip minus 0.1\baselineskip}
    \afterruleX[A]{0.25\baselineskip}
    \afterruleX[B]{0.25\baselineskip}

    \begin{document}
        asdfa sdf \footnoteA{tst}
    \end{document}

with XeLaTeX typesets »+0.25« just above the line but not, when `\arrangementX` is commented out.

I have the log file attached if that might help.
[issue523.log.txt](https://github.com/maieul/ledmac/files/267592/issue523.log.txt)

**Comment by maieul** [comment]
ho ! I tried with \Xarrangement and not \Xarrangement

will be corrected soon

**Comment by maieul** [comment]
please try new version of the branch.

**Comment by dariok** [comment]
I've tested it and as far as I can see it works really well :)

Thank you very much!

**Comment by maieul** [comment]
your'e welcome. I will publish it now.
