### ISSUE TITLE
auxiliary files in a seperate folder

### ISSUE THREAD

**Issue by manuel-kuehner** [maieul/ledmac#526]
I want to have the auxiliary files in a seperate folder - see also my questioen here:

[http://tex.stackexchange.com/questions/310238](http://tex.stackexchange.com/questions/310238)

Best regards and thanks a lot
Manuel

**Comment by maieul** [comment]
my priority for now is #522 and #524, which are quite complex. I can't tell you when I could work on this problem. 

I suggest you to learn git for your own need. It will allow you keep history of your version, and, you could deleted auxiliary file by `git clean -f -x`.

In any cause LaTeX will produce .aux, .toc and other file, on which reledmac have no control.

**Comment by maieul** [comment]
tex can't create automatically the subfolder. You will have to do it yourself.

**Comment by manuel-kuehner** [comment]
Ok. Thanks anyway!
Am 18.05.2016 20:53 schrieb "Maïeul Rouquette" <notifications@github.com>:

**Comment by maieul** [comment]
please try branch "issue526". It provides an auxdir option.

**Comment by manuel-kuehner** [comment]
Thanks. How do I use it, `auxdir="temp"` for example as a package option?

**Comment by maieul** [comment]
yes, but without quotation mark.
In general, in the branch XXX, I provide a file issueXXX.tex which provides to you a MWE

**Comment by maieul** [comment]
please make feedback as soon as possible. That is the last issue before releasing new version

**Comment by manuel-kuehner** [comment]
Hello, I tried to install the `dtx` files by using the command `latex reledmac.dtx`. I get the error message in the screenshot.

![screenshot 2016-06-07 00 37 18](https://cloud.githubusercontent.com/assets/19433666/15840131/19471e98-2c48-11e6-93ef-8b9516074424.png)
![screenshot 2016-06-07 00 37 23](https://cloud.githubusercontent.com/assets/19433666/15840132/19474b34-2c48-11e6-8328-9b3c4c950c3a.png)

**Comment by maieul** [comment]
try the new version, but you need to run the .ins file, not the .dtx

**Comment by manuel-kuehner** [comment]
I tried it with XeLaTeX and PDFLaTeX and both worked fine! Thank you for your effort.

**Comment by maieul** [comment]
your'e welcome
