### ISSUE TITLE
\ledinnernote \ledouternote

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#539]
Hi! There seems to be a problem when using \ledinnernote \ledouternote; normally, in both cases notes should be printed on the inner or outer margin of the page; for some reason in my document \ledinnernote prints text on the outer margin and \ledouternote on the inner margin (see MWE).

There seems to be another problem as well: marginal notes collide; e.g. after 80 pages of edited greek text and its parallel translation, marginal notes A, B, C corresponding to paragraphs 1, 2, 3 get printed with the marginal note D of paragraph 4 next to this paragrah (this problem cannot be attested in the MWE, since the text there is too short; therefore the problem must be related with the extent of the text of the edition).

And here follows the MWE, I would be grateful for a hint or two...

\documentclass[a4paper]{book}
\usepackage{polyglossia,fontspec,xunicode}
\setmainfont{Linux Libertine O}

\setmainlanguage{english}
\setotherlanguage[variant=polytonic]{greek}

\usepackage[makeindex]{imakeidx}

\usepackage[noreledmac]{eledmac}
\usepackage{eledpar}

\lineation{pstart}

\setlength{\ledlsnotesep}{2 \ledlsnotesep}

\footparagraph{A}
\footparagraph{B}
\footparagraph{C}

\numberonlyfirstinline[A]
\numberonlyfirstinline[B]
\numberonlyfirstinline[C]

\inplaceofnumber[A]{0pt}
\inplaceofnumber[B]{0pt}
\inplaceofnumber[C]{0pt}

\inplaceoflemmaseparator[A]{2pt}
\inplaceoflemmaseparator[B]{2pt}
\inplaceoflemmaseparator[C]{2pt}

\renewcommand{\thepageline}{%
\the\value{pstartL}%
\pagelinesep%
\xlineref{\edindexlab\thelabidx}%
}
\makeindex[title=Index rerum et nominum,columns=2]{}

\usepackage{fancyhdr}
\fancyhf{}
\pagestyle{fancy}
\fancyhead[CE]{\scshape Leonis Magentini}
\fancyhead[CO]{\scshape In Aristotelis Analyticorum priorum librum II}
\cfoot{\thepage}

\newcommand*{\sectionformat}{\centering\color{\sectioncolor}}

\newcommand{\om}{\textit{om. }}
\newcommand{\cf}{\textit{cf. }}
\newcommand{\post}{\textit{post }}
\newcommand{\add}{\textit{add. }}
\newcommand{\ante}{\textit{ante }}
\newcommand{\im}{\textit{i.m. }}
\newcommand{\secl}{\textit{secl. }}
\newcommand{\iter}{\textit{iter. et del. }}
\newcommand{\corr}{\textit{corr. }}
\newcommand{\suli}{\textit{s.l. }}
\newcommand{\del}{\textit{del. }}
\newcommand{\schol}{\textit{schol.} }
\newcommand{\pc}{\textit{p.c.} }
\newcommand{\ac}{\textit{a.c.} }
\newcommand{\diagr}{\textit{diagr.} }

\newcommand{\phil}{Philop. In Anal. Pr. comm.: CAG XIII 2, }
\newcommand{\philpost}{Philop. In Anal. Post. comm.: CAG XIII 3, }
\newcommand{\amm}{Amm. In Anal. Pr. I comm.: CAG IV 6, }
\newcommand{\alex}{Alex. In Anal. Pr. comm. I: CAG II 1, }
\newcommand{\alextop}{Alex. In Top. comm. I: CAG II 2, }
\newcommand{\ital}{Ital. Quaest., }
\newcommand{\phys}{Phys. }
\newcommand{\pr}{Anal. Pr. }
\newcommand{\topi}{Top. }
\newcommand{\marinus}{Marinus, De proposito Anal. Pr. II}
\newcommand{\leotop}{Magent., In Top. II, }
\newcommand{\leose}{Magent., In SE, }

\begin{document}
\thispagestyle{empty}

\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
\begin{center}
\ledouternote{t, XXXIr}\edtext{Ἀριστοτέλους Ἀναλυτικῶν προτέρων τὸ δεύτερον}{\lemma{\textbf{Tit.} Ἀριστοτέλους Ἀναλυτικῶν προτέρων τὸ δεύτερον}\Bfootnote[nonum]{εἰς τὰ δεύτερα τῶν προτάσεων D}}
\end{center}
\pend
\pstart
\subsubsection*{I}
\pend
\setcounter{pstartL}{1}
\numberpstarttrue
(52b38) \textit{Ἐν πόσοις μὲν οὖν \edtext{σχήμασι}{\lemma{\post σχήμασι}\Bfootnote[nosep]{\add καὶ διὰ ποίων καὶ πόσων προτάσεων D}}.}
διαφόρως τῆς παρούσης πραγματείας σκοπὸς ἀπεδόθη παρὰ τῶν παλαιῶν.
\edtext{Πρόκλος μὲν εἶπεν ὅτι ἐν τοῖς προλαβοῦσι περὶ τοῦ εἴδους τῶν συλλογισμῶν ἐδίδαξεν, ἤγουν τοῦ\ledinnernote{note which should be printed on the inner margin} συμπεράσματος (ἐν οἷς ἐδίδασκε ποταπὸν συμπέρασμα συνάγεται ἐκ δύο καταφατικῶν ἢ ἐκ μιᾶς ἀποφατικῆς, τῆς δ' ἑτέρας καταφατικῆς), ἐνταῦθα δὲ διδάσκει περὶ τῆς ὕλης τοῦ συλλογισμοῦ, ἤγουν τῶν προτάσεων·}{\lemma{Πρόκλος \ldots προτάσεων}\Afootnote{\cf \phil p. 387.8--11}}
διαψεύδεται δὲ προφανῶς· ἐν γὰρ τῷ \edtext{Περὶ εὐπορίας προτάσεων}{\Afootnote{\cf \pr II 27--31}} μέθοδον παρέδωκεν ἐφευρετικὴν τῶν προτάσεων.
\edtext{ὁ δὲ Μαρῖνος σκοπὸν \edtext{ἔχειν}{\Bfootnote{εἶχεν D}} ἐνταῦθα εἶπε διαλαβεῖν περὶ τῶν λυσιτελούντων εἰς τὴν διαλεκτικήν·
\ledouternote{note on the wrong margin}τίνα δέ εἰσι ταῦτα;
τὸ ἐκ ψευδῶν προτάσεων ἀληθὲς συνάγειν συμπέρασμα, τὸ ἐν ἀρχῇ αἰτεῖσθαι, ἡ ἐπαγωγὴ καὶ ἄλλα τινά·}{\lemma{ὁ δὲ Μαρῖνος \ldots ἄλλα τινά}\Afootnote{\marinus}}
διαψεύδεται δὲ καὶ οὗτος· πρῶτον μὲν ὅτι ὁ διαλεκτικὸς οὐ λαμβάνει ψευδεῖς προτάσεις, ἀλλὰ πιθανάς, ἕτερον δὲ ὅτι οὐκ εὐθὺς διδάσκει περὶ τῆς διαλεκτικῆς, ἀλλὰ περὶ τῆς ἀποδεικτικῆς.
\edtext{ὁ δὲ Ἀλέξανδρος δοκεῖ κρείττονα σκοπὸν ἀποδοῦναι εἰπὼν ὅτι διδάσκει ὅσα ἔφθασε παραλεῖψαι \edtext{παραδιδοὺς}{\Bfootnote{παραδοὺς D}} τὴν συλλογιστικὴν μέθοδον}{\lemma{ὁ δὲ Ἀλέξανδρος \ldots μέθοδον}\Afootnote{\cf \phil p. 387.6--7}}· ἔστι δὲ οὐδὲ τοῦτο ἀληθές· πάντα γὰρ τὰ συμπληρωματικὰ τῆς συλλογιστικῆς μεθόδου παρέδωκεν καὶ οὐδέν τι παρέλειψεν.
ἡμεῖς δὲ λέγομεν ὅτι ἐνταῦθα παραδίδωσι \edtext{τὰ παρεμποδίζοντα τὸν ἀποδεικτικὸν συλλογισμὸν}{\lemma{ἐνταῦθα \ldots συλλογισμὸν}\Afootnote{\cf \schol 14.4--5, \#\# 29.3--4, 30a.2--9 \#\#}} καὶ μὴ ἐῶντα προβαίνειν αὐτόν·
εἰσὶ δὲ ταῦτα \edtext{τὸ ἐκ ψευδῶν προτάσεων συλλογίζεσθαι, ἡ \edtext{κύκλῳ}{\Bfootnote{κυρίως D}} δεῖξις, τὸ ἐν ἀρχῇ αἰτεῖσθαι, ἡ ἐπαγωγή, \edtext{τό τε τεκμήριον καὶ τὸ σημεῖον}{\lemma{τό τε \ldots σημεῖον}\Bfootnote{καὶ τὸ σημεῖον, καὶ τὸ τεκμήριον  V}}}{\lemma{τὸ ἐκ ψευδῶν προτάσεων \ldots τεκμήριον}\Afootnote{\cf \pr II 2, 53b4--4, 57b17; 5, 57b18--7, 59a31; 16, 64b28--65a37; 23, 68b15--37; 27, 70a2--37, 70b1--6}}.
\edtext{ἐπεὶ καὶ τοὺς ἰατροὺς ὁρῶμεν \edtext{οὐ}{\Bfootnote{μὴ D}} μόνον τὰ πρὸς ὑγείαν λυσιτελοῦντα φάρμακα διδάσκοντας, ἀλλὰ καὶ τὰ \edtext{θανατηφόρα}{\Bfootnote{θανατοφόρα D}}, οὐχ ἵνα τούτοις χρῶνται ἰατρεύοντες, ἀλλ' ἵνα μᾶλλον ἐκφεύγωσι, καὶ ὁ Ἀριστοτέλης παρέδωκεν ἃ εἴπομεν ἐν τῇ παρούσῃ πραγματείᾳ, ἵνα ἀποδεικνύοντες μὴ τούτοις χρώμεθα, ὡς παρεμποδίζουσι τὴν ἀπόδειξιν}{\lemma{ἐπεὶ \ldots ἀπόδειξιν}\Afootnote{\cf \leotop 112.75--113.102; \leose 280.12--20}}:--
\pend
\endnumbering
\end{Leftside}
\begin{Rightside}
\firstlinenum{1000000000}
\beginnumbering
\pstart
\begin{center}
The Second Book of Aristotle's Prior Analytics
\end{center}
\pend
\pstart
\subsubsection*{I}
\pend
\setcounter{pstartR}{1}
\numberpstarttrue
\pstart
\textit{Through the numbers of figures.} The purpose of the treatise at hand was explained in various ways by the ancient interpreters.
Proclus said that in the preceding book Aristotle taught about the forms of deduction, or rather the kinds of conclusion (in that part of the work, where he taught what kind of conclusion is drawn from two affirmative premises or from one negative premise and another affirmative one), while here he teaches about the matter of deduction; that is the premisses of an argument.
But Proclus is deceived, for in the chapter On finding suitable premises Aristotle taught an inventive way of pursuing premises.
Marinus, on the other hand, said that here Aristotle's purpose is to treat things availing in regard to the dialectic reasoning.
Which are these?
To draw a true conclusion from false premises, to ask for the initial point, the induction, and some other things.
He is, however, deceived as well, because first of all the dialectician does not use false premises, but plausible ones; moreover, Aristotle does not teach outright about dialectic reasoning, but about demonstration.
Alexander, again, seems to have given a better account of the treatise's purpose after saying that Aristotle teaches whatever he omitted previously, in the course of explain\-ing the doctrine of deduction; but this is also not true, for Aristotle explained every aspect of the deduction doctrine and left nothing aside.
We, on the other hand, say that here he teaches about things impeding the demonstrative deduction and not allowing it to step forward; these are to infer a true conlusion from false premises, the circular proof, to ask for the initial point, the induction, both the evidence and the sign.
Since we observe physicians teaching not only about healing drugs, but even about the lethal ones, not in order that they should use them when healing, but in order that they should avoid them, so did Aristotle explain the things we mentioned in the treatise at hand;  in order that we should not make use of them when demonstrating, since they empede demonstrative deduction.
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
%\printindex
\end{greek}
\end{document}

**Comment by maieul** [comment]
eledmac is not more maintened. I will look at this bug on reledmac and eventually fix it.

**Comment by maieul** [comment]
ps: 
```
\numberonlyfirstinline[A]
\numberonlyfirstinline[B]
\numberonlyfirstinline[C]
`````

can simplified to `\numberonlyfirstinline[A,B,C]` (available for all setting command)

And if it is for all series, don't use the optional argument `\numberonlyfirstinline`

**Comment by maieul** [comment]
ps2: please next time provide MWE which does not provoke fails on compilation. 

Here my compilation bcaf643

**Comment by maieul** [comment]
Ok. I have seen the problem. I will do correction tomorrow, I hope.

For your other problem I can't see any typographicla solution, except have shorter notes or use less font size. In any case, I can't debug it without MWE (and please in this case open a new issue)

**Comment by maieul** [comment]
please try branch "issue539".

Ps: formally, an innernote on a {Leftside} environment is right note :-)

**Comment by NiAgio** [comment]
Dear Maieul,
thank you indeed for your most valuable corrections and hints! I know that eledmac is not maintained any more, but the greek text I am editing as well as its translation a. are written with eledmac (200 pages, give or take) and b. only a few steps before being delivered to the printing house; I think it is perhaps a bit late to migrate to reledmac... You are right, however, reledmac would simpler to use and therefore I promise that I will use it for the next big project. Once again, many thanks for your help!

**Comment by maieul** [comment]
The modification from eledmac to reledmac are very minor and listed. Juste some changes in the preamble.
In any case, this bug will be solve only on reledmac. But as you are in parallel typesetting, you can just use \ledleftnote and \ledrightnote, because the inner margin / outer margin don't move if you stay in the same side :-p

**Comment by maieul** [comment]
in any case, I consider this bug as solved.

**Comment by NiAgio** [comment]
:) : ) :) Ok... I have just noticed the change! Thanks!
