### ISSUE TITLE
Footnote spacing with accented characters

### ISSUE THREAD

**Issue by dariok** [maieul/ledmac#542]
Dear Maiuel,

there seems to be a problem with the line height in (familiar) footnotes when accented characters are present. Compare

    \documentclass{book}
    \usepackage[nocritical,noeledsec,noend,series={B}]{reledmac}
    \showoutput
    \begin{document}
    Apostelbriefen\footnoteB{Der Apostelbrief bestätigt dem Appellanten die Einlegung der Appellation
        und kann deren Annahme oder Zurückweisung dokumentieren. Der \'Appellant benötigt den
        Apostelbrief, wenn er die Appellation bei der höheren Instanz weiter verfolgen will.}
    \end{document}

with and without the accent or e.g. german Ä etc. It is the same in XeLaTeX with directly input Á or Ä etc.

The effect may be more pronounced with a different font:
![image](https://cloud.githubusercontent.com/assets/1765292/15964189/84b788b2-2f17-11e6-9726-98ee3edc1fe9.png)

If you need any additonal info, please let me know.
Thanks as always,
Dario

**Comment by maieul** [comment]
please try branch "issue542"

**Comment by maieul** [comment]
sorry. I forget to send the modification on github. now it is ok

**Comment by dariok** [comment]
Tried it, looks really good! Thanks!

**Comment by maieul** [comment]
There was a problem in my solution. I must find an other way.
