### ISSUE TITLE
sameword breaking endnotes

### ISSUE THREAD

**Issue by floriandk** [maieul/ledmac#543]
Changing the example file `2-lemma_disambigution.tex` from the documentation to use endnotes instead, shows that `\sameword` doesn't work with v2.10.0 (TL2016).

```latex
\documentclass[draft]{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}

\usepackage[series={A,B},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart
Leo \sameword{aut} ursus \sameword{aut} oryx \sameword{aut} ricinus \sameword{aut} equus \sameword{aut}
lupus \edtext{\sameword{aut}}{\Aendnote{et}\Bfootnote{monotone\ldots}} canis \sameword{aut} felix \sameword{aut} asinus \edtext{\sameword{aut}}{\Bendnote{et}} burricus.

\pend
\endnumbering

\subsection*{Series A}
\doendnotes{A}
\subsection*{Series B}
\doendnotes{B}

\end{document}
```

This code runs through and prints the endnotes as requested, but doesn't print the superscript-numbers.

When also changing the last remaining footnote-command `\Bfootnote{monotone\ldots}` to `\Bendnote{monotone\ldots}` the typesetting breaks completely:

```
Undefined control sequence.
<argument> \sw@list@inedtext 
                             
l.4 {aut}}{et}{A}{}{L}{edtxt@1}
```

(Same with v2.11.0a, just installed from ctan)

**Comment by maieul** [comment]
please try branch issue543

**Comment by floriandk** [comment]
wow that was fast! :)

Both the minimal example and the project I'm working on seem to handle `\sameword` in endnotes correctly with this branch. The project only has one note-series and until now only few `\sameword`s though, so I can only speak for this comparatively simple setup. I hope to do some more work on this within the next days and will get back to you if further problems should show up.

**Comment by maieul** [comment]
your'e welcome. I don't think any problem can happen now in the point of sameword+endnotes
