### ISSUE TITLE
\edtext appelé à gauche mais imprimer à droite

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#545]
Pour répondre au besoin exprimé par @GiulioGx en #544. 

Idée:
- À gauche on mettrait des commandes de `\edtextlater{lemma}{commande d'apparat}{identifiant unique}`
- À droite on appelerait `\edtextnow{identifiant unique}` à l'endroit censés correspondre. Ou bien, on fait automatiquement l'insertion si on est sur la ligne de même niveau que le `\edtextlater`.

Avantage de la seconde solution:
- plus simple pour l'utilisateur
- correspond plus facilement à la ligne

inconvénient
- pb avec les reglages non par défaut de synchronisation
- risque d'aboutir à un scénario du type impossible de trouver un état stable des fichiers auxiliares (?).

Piste  d'implantation:
- définition globale de commande de type `\edtextlater@idunique` comprenant:
- un edtext vide
- un lemma determiné par le précédent
- un `setlinenum` determiné par `\xxref`
- commande d'apparats

Point à vérifier: 
- pb de formatage du lemme (le fameux argument font qui pose tant de souci)
- hyperrlien.
- sameword

**Comment by maieul** [comment]
@GiulioGx as you can see there is many question. And I have many other issue. I won't have time for this before a long time, I afraid.

**Comment by maieul** [comment]
@GiulioGx : in any case, I don't think that is a good idea to print footnote on the side they don't have lemma. I suggest you, if your problem is to preserve space, to use Xarrangement{paragraph}.

**Comment by GiulioGx** [comment]
Thanks for your comments. Unfortunately the note layout is a strict requirement and I cannot change it although I think it too to be bad practice. If you come up with a quicker workaround than the \xxref one please let me know. 

P.S. in the old version (the one with the blank lines in the notes) the synchronizing was good, maybe there is a quick workaround only for the blank lines there?)

Thanks again!

**Comment by maieul** [comment]
no, the synchronism was not good. look on the way the notes was dispoted, using showframe of geometry package. It is only because notes were not good typeset, and overlapp the bottom of the page, that the synchronization was right. If the notes are right typeset, ie be included on the main frame of the page, then the synchronism problem will come back.

I think I could have time saturday afternoon for this problem, but only one saturday is not enough because there is many case problem

**Comment by maieul** [comment]
please try the branch issue545. It provides two command:
- `\edtextlater{<identifiant>}{<lemme>}{<footnotecommand>}` to be call in the left side. The first argument is a unique identifiant, will the two next arguments are classical argument on an `\edtext`
- `\edtextnow{<identifiant>}` to be called on the right side, in the approximatlivy corresponding line.

**Comment by maieul** [comment]
ps: not tested for now with \sameword and with hyperref… in next hour.

**Comment by maieul** [comment]
Personnal notes for sameword:
- s'arranger pour récuperer la liste `{(sw,line)(sw,line)(sw,line)}` même si on a pas de edtext à gauche
- ajouter un outil qui permet d'insréer n'importe quel code arbitraire avant de procédéer à l'insert suivant.

**Comment by maieul** [comment]
[en-cours-de-dev-not-use-it.zip](https://github.com/maieul/ledmac/files/321931/en-cours-de-dev-not-use-it.zip)

**Comment by maieul** [comment]
[issue545-sameword-a-migrer-en-dtx.zip](https://github.com/maieul/ledmac/files/321953/issue545-sameword-a-migrer-en-dtx.zip)

**Comment by GiulioGx** [comment]
I've tried the new command pair \edtextlater \edtextnow and they work fine. I cannot comment, however, on the synchronization because I have to adapt all Cfootnote to this new paradigm. I will do it asap (Unless there is some automatic way to do that :)) . I really do not know if it is possible but it would be nice not to have to specify an id: it should be sufficient to call (in a transparent way for the user) \edtextnow at the end of the corresponding chunk on the other side. I really don't know if it is complex/possible.

Thanks a lot! ;)

**Comment by maieul** [comment]
what is possible is to use a mechanism that make the \edtextnow called on position 4 to be equivalent of \edtextlater called on position 4. 

But what is the important point is that automatic synchronism is not possible. So that what why putting \edtextnow on the end of a \pend is not a good solution

**Comment by maieul** [comment]
I will implement the version without argument to night.

**Comment by maieul** [comment]
The new version:
- fix bug with \sameword
- fix bug the hyperref
- delete the first argument of the two macro. So \edtextlater 1 correspond to \edtextnow 1, \edtextlater 2 to \edtextnow 2 etc.

**Comment by maieul** [comment]
not: `\edtextnow` is a paramaterless macro, in many case you must use `{} after.

**Comment by GiulioGx** [comment]
Thanks! I guess I cannot have anymore two notes referring to same lemma if on facing pages with one command syntax:
\edtext{}{\Cfootnote{...}\Afootnote{}}  

I should use \edtextlater for the C and \edtext for the A. Am I right?

**Comment by maieul** [comment]
yes. but you can do 
`\edtextlater{\edtext{s}{\Afootnote{xx}}}{\Cfootnote{xx}}`

normally. If it does not work, make feedback.

**Comment by maieul** [comment]
(ps: but generally, people don't use \Cfootnote directly, and prefere create semantic command)

**Comment by GiulioGx** [comment]
I've tried the new solution (the one with the identifiers, the one without gives some compilation error) on the same example. The notes are fine and well placed but the synchronization is not very good. Chunks are usually broken in a bad way.

[mwe_edtextlater.zip](https://github.com/maieul/ledmac/files/322509/mwe_edtextlater.zip)

**Comment by maieul** [comment]
As I have told you three time: there is no possibility to make automatically synchronism. You have to place manually the \edtextnow in a position which will be ok.

**Comment by GiulioGx** [comment]
Yes, I understand but since my chunks are like 5-10 lines the position of edetextnow is wherever ok. However this is not the issue here, the problem is that the latin stanzas are broken in the middle of the chunk. Why is this happening?

**Comment by maieul** [comment]
Be clear: a chunck is not a block which can't be splitted, but a block which must be synchronized with the equivalent block on the other side. That was true in the past, and will be true everytime.

If you want to prevent pagebreak, you must use the \lednopb tool. 

In your case, your file seem to be quite complex too synchronism. You must use latexmk.

**Comment by GiulioGx** [comment]
Ok, thanks for all the suggestions!

**Comment by GiulioGx** [comment]
Last question for you! I swear I won't bother you again after this :)

I've added the \lednopb at each latin verse so the stanzas are not broken anymore. However the correspondent italian chunk gets broken no matter what. Is there a way to prevent this? I just would like that if the latin stanza is completely on one page the correspondent chunk is completely on the opposite page (provided there is enough space of course). Look for example of how the first italian chunk is needlessly broken.

Thanks a lot, man!

**Comment by maieul** [comment]
put to \lednopb in the italian page

**Comment by GiulioGx** [comment]
I've tried it, the problem is the italian part is not organized in verses. Do I have to put \letnopb at each word?

**Comment by maieul** [comment]
At each sentence ? I don't know. You try to do one thing for what reledpar is not concepted.

**Comment by GiulioGx** [comment]
I just want the italian chunk to be on the opposite page of the latin one. Instead it is broken in two pages.

**Comment by maieul** [comment]
Yes I know what you want� and I told you many time that is is not the concept of reledpar. So do test, and try. Or open an issue, but I won't have time to look on it before many, many, many days.

**Comment by maieul** [comment]
there was a bug in the version you tried. Please try new version of the branch. I dont't think it could solve your problem, but…
