### ISSUE TITLE
Problem with reledmac/reledpar after the last update

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#547]
Hi! After the last update of reledmac a couple of days ago the "rightside" text follows the end of the "leftside" text, whereas both texts should be printed facing one another.

**Comment by maieul** [comment]
3f6c67b is the origin of the bug. I have to look on it

**Comment by maieul** [comment]
please try branch issue547

**Comment by NiAgio** [comment]
I have just tried it, it does not work. The result is the same...

**Comment by NiAgio** [comment]
The right page of the translation is left always blank and the pertinent text gets printed after the text on the left page comes to an end.

**Comment by maieul** [comment]
sorry, I forget to commit the change! Please try again.

**Comment by NiAgio** [comment]
Ok, many thanks! Everything is nice and clean again ;)

**Comment by maieul** [comment]
I will publish this emergency fix now.

**Comment by maieul** [comment]
ps: please next time, if you don't want a code be online, let me know directly. I haved added your file in the git historic, and now, the github team must make a intervention to delete it.

**Comment by NiAgio** [comment]
Ok, I will do! Sorry for the inconvenience.
