### ISSUE TITLE
Footnotes on same line 

### ISSUE THREAD

**Issue by LorenzoFerrando** [maieul/ledmac#556]
How can I set footnotes on same line of words belonging to same line in text?
Thanks for your time.

Best regards

Lorenzo

**Comment by maieul** [comment]
I don't understand you need. Could you be more explicit ? maybe producing an example of desired output

**Comment by LorenzoFerrando** [comment]
Thanks for the answer. So, I have:

\documentclass[12pt, a4paper, oneside]{article}




\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lineno} 




\usepackage{reledmac}
\usepackage{reledpar}
\Xnotenumfont {\bfseries}
\Xnumberonlyfirstinline
\Xparindent


\begin{document}
\begin{linenumbers*}
\modulolinenumbers[5]
\beginnumbering
\pstart
 e \edtext{un}{\Afootnote{\textit{sps. a} il}} frastuono \edtext{di}{\Afootnote{\textit{da} dei}} motori e dei \edtext{clacson}{\Afootnote{\textit{segue} e piccoli gruppi di gente che si *affrontava ({\textit{da} affrontavano}) a volte urlando}}.


\pend\endnumbering


\end{linenumbers*}
\end{document}
I would like that the footnotes related to "un", "di" and "clacson" were on the same line, separeted with 3 blank spaces and without repeating the number of the line.
Many thanks!

**Comment by maieul** [comment]
and if on a other line, add a new line I suppose?

for now it is not possible. But I have an idea to make it possible

**Comment by LorenzoFerrando** [comment]
Yes, add a new line in notes if on another line

**Comment by maieul** [comment]
what about if a note is between two lines ?

**Comment by maieul** [comment]
you should not use lineno with reledmac: reledmac already number the line.

**Comment by LorenzoFerrando** [comment]
If a note is in the text between lines 1 and 2 I would like to mark 1-2 in the apparatus. And if the following note is in the line 2 I would like to repeat only the 2 in the footnote

**Comment by LorenzoFerrando** [comment]
(Thank you very much for the interest!)

**Comment by maieul** [comment]
my question was not about the footnote number, but about the footnoteposition.
Where should we put it ?

**Comment by LorenzoFerrando** [comment]
If they are in the same line in the text, in the same line also in the footnote. Otherwise in the following line

es.
1 un] sps. a il   di] da dei   clacson] segue e piccoli gruppi di gente che si *affrontava (da affrontavano) a volte urlando
2-3  alcuni fermi] segue e sorridenti
3 battevano] prima picchiavano   colpi] prima grandi

Thanks!

**Comment by maieul** [comment]
but what, for example, for a lemma on line 1-2?

**Comment by maieul** [comment]
I will propose both solution

**Comment by LorenzoFerrando** [comment]
Thanks very much I will try immediatly!

**Comment by maieul** [comment]
not implemented yet, I will tell you  when you should try

**Comment by maieul** [comment]
Ok, I have implemented, but only for normal footnote (so not in two or three columns typesetting) and not for ledgroup.

I will do that next week-end.

Please try branch "issue556" before. Read the handbook on 9632d57e7e385b25224ae2256a57ac7d71993/reledmac.dtx#L2213-L2226 to know how to do (please also make feedback on the handbook)

**Comment by LorenzoFerrando** [comment]
Thanks for your time. I ran issue556.tex and I read line 2213-2226 in the handbook, but an error was produced: "Undefined control sequence. \Xgroupbyline". As options I opted to use \Xgroupbyline in combination with \Xnumberonlyfirstintwolines

**Comment by maieul** [comment]
please read 
https://github.com/maieul/ledmac/#debug-and-feature-requests

to know how to make the test

**Comment by maieul** [comment]
hi
some feedback here? I would like to continue the implementation on the week-end, and so feedback for first test would be welcome.

**Comment by LorenzoFerrando** [comment]
Hi,

sorry for the long silent period. I tried the implementation and it works perfectly. Thanks. It would be great if in the case of 1-2 footnotes, it creates a new line:

1 bla bla bla bla 
1-2 ....
3

Thank you so much for the support.

Best regards

**Comment by maieul** [comment]
it is normally the case if you use 
`\Xgroupbylineseparetwolines`
isn't it ?

I will try to finish implementation tomorrow
