### ISSUE TITLE
variant pour le fichier 4-reledpar_column_mix_with_not_column-continuous-numbering.tex

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#557]
Cher ami, je suis à travailler un nouveau document. 
Sur la page de gauche devrait apparaître,   en deux colonnes, deux textes dans la même langue, mais dans des versions différentes,  la traduction sur la page droite. 
Le fichier <<4-reledpar_column_mix_with_not_column-continu numbering.tex>>
 est l'optimum pour la page de gauche, mais je ne suis pas bon à changer le fichier
 de sorte d'avoir deux versions du texte à gauche et une traduction sur la droite.
il n'y a pas  problèmes de langues, seulement   de mise en page.
Pouvez-vous me aider? 
Sincèrement, Enrico M.

**Comment by maieul** [comment]
problème souvent demandé, et malheureusement complexe à résoudre. Il me faudrait réécrirure quasiment tout reledpar.

je n'aurai pas le temps de travailler cela avant long, long, long temps.

je ferme, le problème étant abordé en #415.

**Comment by ralessi** [comment]
Pour information, je suis en train d'écrire un package qui devrait faire cela. Je ne peux pas encore annoncer une date de sortie, mais ce devrait être entre début et fin septembre. Le package fonctionnera sous LuaLaTeX.
Le projet consiste à réaliser un lexique gréco-arabe dans lequel les variantes des manuscrits sont prises en compte. Il repose sur trois packages: un pour la saisie de l'arabe, un autre pour les questions d'édition et de mise en page, et un troisième pour la saisie des éléments propres au dictionnaire.
Une précision très importante: ce package ne sera en aucun cas concurrent de reledmac/reledpar. Plus d'informations sur mon site personnel: https://www.robertalessi.net/greek-arabic-lexicon

**Comment by maieul** [comment]
houl� !
c'est une bonne id�e mais ca risque d'�tre tr�s sp�cifique.

il faut vraiment que je trouve le temps de faire cela pour reledmac / reledpar. Mais c'est un gros, gros grous boulot.

**Comment by ralessi** [comment]
Oui, je ne suis pas certain que beaucoup de gens l'utiliseront! L'idée de base est d'avoir la possibilité d'une sortie TEI xml en plus de la sortie PDF.

**Comment by maieul** [comment]
heu pourquoi tu encode pas directement en TEI pour ensuite faire du tex ? ca paraitrait plus simple non ?

**Comment by ralessi** [comment]
J'ai fait pas mal d'essais. Mes idées ne sont pas encore parfaitement claires, mais je ne suis pas sûr que ce soit plus simple. Il me semble aussi que la saisie LaTeX est plus naturelle pour beaucoup de gens.

**Comment by maieul** [comment]
ce qui est sur c'est qu'elle est moins verbeuse�
mais du coup tu g�re comment la triple synchronisation ? c'est quand m�me super complexe

**Comment by ralessi** [comment]
Je te fais un petit email séparé.

**Comment by heinrichffleck** [comment]
Avant tout, je dois vous remercier (Roberta et Maieul) pour votre efforts. 

A propos, cher Maïeul, vous savez, que pour les questions des caractères du paquet Teubner, qui sont incompatibles avec XeLaTeX et LuaLaTeX, je dois travailler seulement avec LaTeX2e.

Je remercie encore tes efforts et quelles de Roberta, mais je dois malheureusement commencer parce qu'il est déjà trop longtemps que je suis à la recherche de la solution optimale.
Au moment  je suis  indécis entre deux hypothèses différentes qui sont facilement réalisables par votre ficher d'exemple:

1ere solution: donner la priorité à l'édition philologique: les deux textes grecs sur des colonnes dans la page de gauche  et a suivre, sur la meme page!, le paragraphe relative a la traduction;
2eme solution, plus facile: utiliser la function standard de reledpar, celle que j'ai déjà utilisé pour le text de l'Arenaire d'Archimède: présenter la version grecque principale sur la  page de gauche, ecrire la deuxieme version, celle relative a les variante de le premiere texte en note (avec \Afootnote o -peut-être- meme en utilisant \footnote) sur la meme  page de gauche, la tradution sur la page de droit.
Mes salutations et remerciements,  cordialement
Enrico M.
 
=======================
www.heinrichfleck.net



      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Martedì 12 Luglio 2016 21:09
 Oggetto: Re: [maieul/ledmac] variant pour le fichier 4-reledpar_column_mix_with_not_column-continuous-numbering.tex (#557)
   
ce qui est sur c'est qu'elle est moins verbeuse�
mais du coup tu g�re comment la triple synchronisation ? c'est quand m�me super complexe —
