### ISSUE TITLE
Tradution de l'Arénaire de Archimede

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#558]
Cher ami,
la traduction italienne de l'œuvre d'Archimède Arènaire, réalisé avec reledmac et reledpar, est enfin dans mon site web à l'adresse http://www.heinrichfleck.net/Quaderni/quaderni.html .
Si vous voulez,   vous pouvez lister ce texte entre celles faites avec vos paquets reledmac et reledpar.

Je ne suis pas en mesure de résoudre l'autre question visée à mon précédent post #557

Avec amitié et de solidarité pour ce qui est arrivé à Nizza, une ville a nos italiens tres proche et tres chère.

Cordialmente, Enrico M.

**Comment by maieul** [comment]
merci pour l'information.

malheureusement je ne peux pas vous donner de délai pour le projet de mise ne // de plus de 2 textes. C'est très complexe.
