### ISSUE TITLE
Problem while compiling

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#564]
Hi! I have problems with compiling (I am not sure, however, whether this is a problem of reledmac, of reledpar, of both of them or of the last update of MikTex). The compiling lasts 3-4 minutes and the result is a 49649 blank pages long pdf document. Until yesterday everything worked perfect. Today I get the following error:
"Tex capacity exceeded, sorry [save size=50000].\font@name -> \EU1/LinuxLibertineO(0)/m/sl/10\end"

The MSW:

\documentclass[a4paper]{book}
\usepackage{polyglossia,fontspec,xunicode}
\setmainfont{Linux Libertine O}

\setmainlanguage{english}
\setotherlanguage[variant=polytonic]{greek}

\usepackage[noeledsec,noend]{reledmac}
\usepackage{reledpar}

\setlength{\ledlsnotesep}{2 \ledlsnotesep}

\Xarrangement[A,B]{paragraph}

\begin{document}
\begin{pages}
\begin{greek}
\begin{Leftside}
\beginnumbering
\pstart
Πρῶτον\ledrightnote{Randnotiz A} εἰπεῖν περὶ τί καὶ τίνος ἐστὶν ἡ σκέψις, ὅτι περὶ ἀπόδειξιν καὶ ἐπιστήμης ἀποδεικτικῆς.
\pend
\endnumbering
\end{Leftside}
\end{greek}

%Übersetzung

\begin{Rightside}
\beginnumbering
\pstart
We must first state the subject of our inquiry and the faculty to which it belongs: its subject is demonstration and the faculty that carries it out demonstrative science.
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}

**Comment by maieul** [comment]
what happens if you deleted the "noend" ?

**Comment by NiAgio** [comment]
Exactly the same thing... a pdf of 49649 blank pages (actually 49647, since pages containing the greek text and its translation are included)

**Comment by maieul** [comment]
"3c06a333eee0929640eca6ef4756e19a8e961ac6 is the first bad commit"

hum, that is problematic, because it is a merge commit.

**Comment by NiAgio** [comment]
Ok thank, I have deleted all auxiliary files and compiled all my files again... for the moment it seems it works fine. What does your second remark on the merge commit mean?

**Comment by maieul** [comment]
that means that I know WHEN the problem came, but not WHY ;-)

**Comment by NiAgio** [comment]
Thanks anyway! :)

**Comment by maieul** [comment]
I will look on this problem wenesday night

**Comment by maieul** [comment]
you could also use `series={X,X}` and define less or more than 5 series. In any case, it use a good idea to use the `series` option. 

I suppose there is a bug in LaTeX, but I need more investigation

**Comment by maieul** [comment]
that is the same problem than in #547, but I don't know why.

**Comment by NiAgio** [comment]
I see... unfortunately I am completely irrelevant with the technical aspects of the whole thing; I remember, though, that such difficulties come about whenever there is a new major update of MikTeX.

**Comment by maieul** [comment]
new major update of MikTeX means new version of reledmac� that is all. And there is a bug in reledmac.

**Comment by maieul** [comment]
for now, just use the series option, and should it be ok

**Comment by maieul** [comment]
(comment for myself)

regexp:`(\\.*)(=)(\\[abcdefghijklmnopqrstuvwxyz]*)([0123456789]*)`

**Comment by NiAgio** [comment]
Ok, done!

**Comment by maieul** [comment]
it seems it is a problem in LaTeX. I have to work with LaTeX team to fix it.

**Comment by NiAgio** [comment]
Ok, thanks for letting me know!

**Comment by maieul** [comment]
ok, so it was really a bug in LaTeX (after 2015/01/01). @davidcarlisle has fixed it and send the new version on CTAN. So just do tomorro a tlmgr update, and it will be ok.

Many thanks @davidcarlisle for your quick correction ;-)

**Comment by NiAgio** [comment]
That's great! Many thanks to both of you!
