### ISSUE TITLE
Problem with reledmac and luatexja-ruby

### ISSUE THREAD

**Issue by chriskern** [maieul/ledmac#568]
I had posted a question on this project previous on stackexchange, which turned out to be a bug in luatexja. This also might be a luatexja bug, but I wanted to ask here first.

This time I am getting the following error:
```
! You can't use `\lastbox' in vertical mode.
\lastbox ...ion.lastbox_hook()}\ltj@@orig@lastbox 
                                                  
l.14 \endnumbering
                
?
```

I'm having a very hard time determining exactly what is causing this error, but I think it has to do with the \ruby feature of luatexja-ruby. This is a way of using "ruby" text in Japanese, which puts small characters above the main line to show pronunciation. Basically \ruby{X}{Y} will make Y appear in small font above X.
The above error seems to occur when more than a few \ruby statements appear in one \pstart...\pend block. Here's one example:

```LaTeX
\documentclass{book}
\usepackage{luatexja}
\usepackage{luatexja-ruby}
\usepackage[noend]{reledmac}
\newcommandx{\parsenote}[2][1,usedefault]{\Afootnote[#1]{#2}}
\newcommandx{\variant}[2][1,usedefault]{\Bfootnote[#1]{#2}}
\begin{document}
\beginnumbering
\pstart [\section{The Birth of Genji}]
\edlabel{saki}先の世にも\edlabel{chigiri}\edtext{御}{\variant{おほむ　鑑賞}}契りや\edtext{深かかりけむ}
{\parsenote{ふかし RY + aux. けむ}}、
世になく\ruby{清}{きよ}らなる玉の\ruby{男}{お}の\ruby{子|御子}{こ|みこ}さへ生まれ給ひぬ。「いつしか」と
\edtext{心もとながらせ給ひて}{\parsenote{心もとながる (``show impatience'') MZ + hon. caus. す RY + 
hon. たまふ RY + て}}、急ぎ\edtext{参らせて}{\parsenote{humb. まいる MZ + caus. す RY + て}}、 
%\ruby{御|覧}{ご|らん}ずるに、めづらかなる
\pend
\endnumbering
\end{document}
```

This compiles, but if you remove the comment symbol (thus adding one additional \ruby to the block) it fails. You can also get it to work without the comment symbol by breaking the text into more \pstart...\pend blocks.

The text size also affects this. If you add \huge, even one \ruby tag will cause the error.

I don't know if the issue is with reledmac or luatexja-ruby, but I thought I would post it here to start.

Thank you!

**Comment by maieul** [comment]
There was a previous bug with luatexj
please, ask first on luatexj team

**Comment by maieul** [comment]
so it was solved by luatexja team? I close
