### ISSUE TITLE
Eledpar + versification (triplets, quadruplés, sextuplés) + numérotation.

### ISSUE THREAD

**Issue by menarinis** [maieul/ledmac#570]
Salut Maïeul. 
Je suis Donato, l'utilisateur du poste http://tex.stackexchange.com/questions/325575/best-setting-reledpar-reledmac?rq=1
J'ai finalement résolu mes problèmes avec la lecture à fond des manuels et des post sur Internet. Maintenant, j'ai un problème à résoudre.
Dans le livre, en deux langues, que je prévois, j'ai nombreux de poèmes qui ont différent versifications, triplés, quadruplés, sixtes, octaves, etc.
Est-il un moyen avec Reledpar/Reledmac de changer la numérotation dans chaque poème?
Par exemple Poèsie no.1 avec 9 triplets: je voudrais numéroter chaque 3 lignes (1,3,6,9). 
Dans la poésie n2 avec 10 quatrains: je voudrais les numéros chaque 4 (1,4,8,12,16 ...)
Dans la poésie n3 avec 7 octaves:  numerotation 1,8,16 ...
Certains poèmes sont longues et disposées avec une seule /begin /end astanza!

**Comment by maieul** [comment]
vous pouvez changez la fréquence de la numérotation des lignes en 
utilisant  \linenumincrement et  \linenumincrementR (voir le manuel). En 
théorie cela doit être fixé une fois pour tout dans le préambule, mais 
je pense qu'en le mettant dans l'argument optionnel du stanza qui 
commence vos poème cela doit pouvoir marcher.

A tester et à me dire. Sinon il faudra que je trouve du temps pour 
ajouter cette fonctionnalité (pas long, à priori, mais je finis ma thèse 
+ mon ordinateur est en panne!)

**Comment by menarinis** [comment]
La modification de la fonction de numérotation on a si je mets chaque poème (seulement une /stanza -astanza et seulement une /beginnumbering) dans une structure begin/pages end/pages /Pages dédiées. Donc, pour 100 poèmes, 100 structures! Aussi dans une poèmes avec triplets et quadruplets par exemple, en alternance, même si je voulez utilisez plusieurs de chambres la numérotation est un.
À mon avis, si vous impelemteret cette fonctionnalité pouvèz le faire dans les structures begin/end/stanza (astanza) ou (pstart) pas dans les structures /Righside /Leftside ou /Pages. 
Laissez-moi savoir quand vous faites. Merci beaucoup!

**Comment by maieul** [comment]
je n'ai pas compris. 
il me faudrait plus de pr�cision sur ce que vous voulez obtenir au final. je n'ai jamais travaill� la po�sie, donc j'ai du mal � comprendre quand vous utiliser des termes techniques

**Comment by menarinis** [comment]
Et voici un exemple de poèmes avec des rimes différente  et de la numérotation en dessous de la hanche. Les différents versets des poèmes sont ainsi définis par des espaces verticaux, peut-être même de différentes indentations horizontales et en particulier par la numérotation! J'espère maintenant il est clair. Sinon, je vais envoyer d'autres exemples.

[ex_poes_pour_numerot.zip](https://github.com/maieul/ledmac/files/448232/ex_poes_pour_numerot.zip)

**Comment by maieul** [comment]
L'exemple https://github.com/maieul/ledmac/commit/4e1bf963db7dbc255b6435beed09b2a811d8788c vous montre des cas d'alternance de numérotation des lines.

Le seule qui se pose est pour `linenumberlist` qui se plante si le poème court sur deux pages. C'est lié au fait qu'il n'y a qu'une commande pour les pages de gauche et les pages de droite.  Il faut que je fasse une implémentation distinguant. Je vais voir si j'ai du temps ce week-end, mais je ne garanti rien, j'ai deja un paquet de chose à faire.

**Comment by menarinis** [comment]
Merci Maieul. J'ai essayé l'exemple. 
Ok pour quelques et courts
poèmes, numberlist c'est vrai pour toutes les pages, malheureusement!
Cependant, ne vous inquiétez pas. Prenez votre temps pour ce upgrade.
Avant votre tesis, puis le reste.
 Je fini d'écrire le livre avec la
numérotation par défault, puis lorsque vous êtes prêt, ajouter la mise à
jour. 
Je prévois de préparer la publication plus tard cette année.

Malheureusement, je ne sais pas la programmation en Latex sinon je
pourrais vous donner un coup de main. 
Bon travail

Il 06.09.2016 20:47
Maïeul Rouquette ha scritto: 

> L'exemple 4e1bf96 [1] vous montre des
cas d'alternance de numérotation des lines. 
> 
> Le seule qui se pose
est pour linenumberlist qui se plante si le poème court sur deux pages.
C'est lié au fait qu'il n'y a qu'une commande pour les pages de gauche
et les pages de droite. Il faut que je fasse une implémentation
distinguant. Je vais voir si j'ai du temps ce week-end, mais je ne
garanti rien, j'ai deja un paquet de chose à faire. 
> 
> --
> You are
receiving this because you authored the thread.
> Reply to this email
directly, view it on GitHub [2], or mute the thread [3].
 



Con Smart 3 Giga a 9 euro/4 sett navighi veloce, chiami e invii SMS dal tuo smartphone verso tutti i fissi e mobili in Italia. Passa a Tiscali Mobile! http://casa.tiscali.it/mobile/

**Comment by maieul** [comment]
La version de reledmac/reledpar 2.16.0-2.14.0, en cours de dévellopement, que vous trouverez ici https://github.com/maieul/ledmac/archive/2.16.0-2.14.0.zip, résoud le problème des numéros de lignes apparaissant à des endroits précis.

Pour définir à gauche: `\gdef\linenumberlist{liste}`
Pour définir à droit: `\gdef\linenumberlist{liste}`.

Merci d'essayer et de me confirmer que je peux clore le ticket.

**Comment by menarinis** [comment]
Merci beuocoup,
miantenant je vais l'essayer

Il 27.09.2016 12:51
Maïeul Rouquette ha scritto: 

> La version de reledmac/reledpar
2.16.0-2.14.0, en cours de dévellopement, que vous trouverez ici
https://github.com/maieul/ledmac/archive/2.16.0-2.14.0.zip [1], résoud
le problème des numéros de lignes apparaissant à des endroits précis. 
>

> Pour définir à gauche: gdeflinenumberlist{liste}
> Pour définir à
droit: gdeflinenumberlist{liste}. 
> 
> Merci d'essayer et de me
confirmer que je peux clore le ticket. 
> 
> --
> You are receiving this
because you authored the thread.
> Reply to this email directly, view it
on GitHub [2], or mute the thread [3].
  


Con Smart 3 Giga a 9 euro/4 sett navighi veloce, chiami e invii SMS dal tuo smartphone verso tutti i fissi e mobili in Italia. Passa a Tiscali Mobile! http://casa.tiscali.it/mobile/

**Comment by maieul** [comment]
un retour? j'aimerai publier ceci dans la prochaine version de reledmac

**Comment by menarinis** [comment]
Je l'ai fait plusieurs tests.
 Dans tous les cas que cela fonctionne
sur les pages de gauche et seulement si enfermer chaque poème entre
/begin pages /end pages.
 Je joins deux exemples. 
J'ai aussi trouvé une
erreur dans votre manuel, filepages.jpeg. 
Le système proposé exige
toujours l'utilisation en latex du schema /begin pages /end pages /Pages
an /begin Leftside Rightside /endLefside Righside. Mais de toute façon
si je l'utilise le schema /begin pages /end pages /Pages; /begin pages
/end pages /Pages pour chaque poème , je reçois toujours le message
d'erreur que vous voyez dans le file error_pages.jpg.
Merci

Il
28.09.2016 15:15 Maïeul Rouquette ha scritto: 

> un retour? j'aimerai
publier ceci dans la prochaine version de reledmac 
> 
> --
> You are
receiving this because you authored the thread.
> Reply to this email
directly, view it on GitHub [1], or mute the thread [2].
 



Con Smart 3 Giga a 9 euro/4 sett navighi veloce, chiami e invii SMS dal tuo smartphone verso tutti i fissi e mobili in Italia. Passa a Tiscali Mobile! http://casa.tiscali.it/mobile/

**Comment by maieul** [comment]
je ne vois pas la pièce jointe. merci de me l'envoyer en passant par l'interface de github, et non pas par mail, cela ne passe pas.

**Comment by menarinis** [comment]
Voilà
[prova_Maieul2.zip](https://github.com/maieul/ledmac/files/501040/prova_Maieul2.zip)

**Comment by maieul** [comment]
Dans votre fichier  file p9_bis, le premier groupe "pages" ne contient pas de "rightside". Ceci est la cause du message d'erreur (qui est incorrecte, mais c'est un autre problème)

**Comment by menarinis** [comment]
Je présente mes excuses; vous avez raison  en était la hâte. Dans tous les cas, je joins le schéma correct qui ne me donne pas d'erreur dans la compilation du schèma pages (Leftside-Rightside). Merci
![correct_schema_pages](https://cloud.githubusercontent.com/assets/21281413/18996865/4ef237f4-8732-11e6-994e-83a04c241577.png)
)

**Comment by menarinis** [comment]
Hi Maieul how are you? Have some news about reledmac reledpar? Best

On 29 settembre 2016 17:31:03 CEST, "Maïeul Rouquette" <notifications@github.com> wrote:
>Reopened #570.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/maieul/ledmac/issues/570#event-807190533

Inviato dall'app Tiscali Mail.

**Comment by maieul** [comment]
hein? are you asking for this particular topic?
