### ISSUE TITLE
! Package reledmac Error: Fail to patch \@makecol command..

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#573]
In the latest version of `reledmac` (v. 2.15.1) appeared the bug in the subject.

After some tests, I noticed that there is an incompatibility with the package `fancyhdr`. This incompatibility is new: I use this package  for a long time.

Here is a MWE:
```tex
\documentclass[11pt,a4paper]{book}
\usepackage{fontspec}
	\setmainfont{Linux Libertine O}
\usepackage{polyglossia}
	\setmainlanguage[babelshorthands=true]{italian}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage{fancyhdr}
	\pagestyle{fancy}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\usepackage{indextools}
\usepackage[noeledsec,noledgroup,series={A,B,C}]{reledmac}
\usepackage{reledpar}

\begin{document}
Bla Bla Bla
\end{document}
```

**Comment by maieul** [comment]
fancyhdr have get a update recently. That is fancyhdr which breaks, not reledmac.

I will look on it tonight.

**Comment by Doc73** [comment]
Ah, yes! :+1:

**Comment by maieul** [comment]
the "more comics" is that the correction was made to prevent clash with some other package�







Le 12 sept. 2016 � 16:52, Domenico <notifications@github.com> a �crit :

**Comment by Doc73** [comment]
[OT]
I'm comparing the bibliography obtained with new versions of `biblatex-bookinother` with the old one: much better!

Many many thanks!
[/OT]

**Comment by maieul** [comment]
please try the branch issue573

**Comment by Doc73** [comment]
Good! Works very well both in MWE and in my Book.

**Comment by maieul** [comment]
ok, I publish right now on CTAN.
