### ISSUE TITLE
pb avec l'interdiction de changement de page si rupture de vers

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#576]
pour éviter de tourner en rond -> il faut qu'au 3eme round, on garde les marques qu'on a mis au 2nd.

**Comment by maieul** [comment]
@enimie : tu pourrais me refournir un exemple pour ce problème d'enpecher le changement de page sur une rupture de vers (en //)  ? merci

**Comment by maieul** [comment]
en fait c'est bon @enimie. C'est #445

**Comment by Enimie** [comment]
Voici. Il y a deux cas: v.68 et v.243

J'ai essayé de faire le plus propre possible mais bon..c'est du 
bidouillage à partir de  je ne peux pas donner d'exemple plus court, 
sinon le pb disparait

Ceci dit, je n'ai plus aucun problème de ce type depuis que je suis 
passé en 11pt et plus en 12 pt (c'est le cas avec cet exemple)
