### ISSUE TITLE
Diagnostico con \SEref

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#582]
Bonsoir cher ami,

j'ai telechargée la derniere version de reledmac et LaTeX est également mis à jour.

Mais maintenant pour 
**\edlabelS{evidenza-1}\`E dunque evidente... \edlabelE{evidenza-1}**
et ensuite
**vedi linea \SEref{evidenza-1} alla pagina \edpageref{evidenza-1}**,
pendant la compilation de pdflatex le systeme me donne:

**Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                \kern 1.66702pt
(hyperref)                removed on input line 80.
[49]
! Undefined control sequence.
<argument> \@apprefprefixsingle 
l.85 ...uello della Terra} (ln. \SEref{evidenza-1}
                                                   pag. \edpageref{evidenza-...
?** 

En continuant la compilation, l'output est perfecte, exactement: **linee 54R–56R alla pagina 17**.

\SEref n'est pas dant l'environment du packages reledmac/reledpar, mais aussi dan cette environment il y a le meme dignostique. Je crois  que le problem n'est pas dans reledmac, mais quelqu'un des fichiers met à jour par le team de TeX.

Qu'est-ce que vous pensez de cela?

Cordiali saluti, Enrico M.

**Comment by maieul** [comment]
je pense que c'est li� � hyperref, plus sp�cifiquement � l'emploi de \SEref dans une commande de sectionnement. A tester pour faire un MWE

**Comment by heinrichffleck** [comment]
Voici je repond selon #582; ça le text de la mail. 
Cher ami, A propos de diagnostique en object, il n y a plus le problem de hyperref pendant la compilation (sic!), mais (pendant la compilation de pdflatex) il y a un diagnostique d'erreur par \SEref    
   - [ ! Undefined control sequence \@apprefprefixsingle ..... ] 
mais, enfin la compilation est à bon fin et la reference exacte.En attachè mes `fichiers
Salutations et merci, Enrico`\documentclass[10pt,a4paper,twoside]{memoir}
\usepackage[T1]{fontenc}

\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[italian]{babel}
\usepackage[series={A,B,C,D},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}
\setgoalfraction{.85}
\AtBeginDocument{\Xmaxhnotes{0.5\textheight}}
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\theAtest\ - A)}
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\theBtest\ - B)}
\newcounter{Ctest}
\def\Ctest{\stepcounter{Ctest}(\theCtest\ - C)}
\Xonlyside[B]{L}
\Xonlyside[C]{R}\usepackage{graphicx} \usepackage{xcolor}
\usepackage%[hyperfootnotes=false]
{hyperref}%
\hypersetup{%
colorlinks,linkcolor=red,citecolor=red,urlcolor=red%
}%\begin{document}
\begin{pages}
 %PAGINE DI SINISTRA TESTO 
 \begin{Leftside}
 \setcounter{Atest}{0}
 \setcounter{Btest}{0}
 \setcounter{Ctest}{0}
 \beginnumbering
 \setlength\parindent{0pt}%
\pstart\relax
    testo \edlabelS{ref-1}testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo\edlabelE{ref-1} testo testo testo testo testo testo testo testo testo testo testo testo testo 
    \pend
    \endnumbering
\end{Leftside}

%PAGINE DI DESTRA TESTO 
\begin{Rightside}
    \setlength\parindent{0pt}
    \beginnumbering
    \pstart\relax 
    testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo --->>> VEDI LINEE \SEref{ref-1}  (riferimento corretto!)
    \pend
    \endnumbering
\end{Rightside} 

\end{pages} 

\Pages

\end{document}
=======================
www.heinrichfleck.net



      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Domenica 9 Ottobre 2016 11:12
 Oggetto: Re: [maieul/ledmac] Diagnostico con \SEref (#582)
   
Closed #582.—

**Comment by maieul** [comment]
avez vous testé la branche "issue582" ? elle devrait résoudre #582 et #583 (la prochaine fois, n'ouvrez qu'un ticket: il s'agit de l'affinage d'un problème, non de 2 problèmes distincts)
