### ISSUE TITLE
Diagnostico con \SEref #582

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#583]
Cher ami, 

A propos de diagnostique en object, il n y a plus le problem de hyperref pendant la compilation (sic!), mais (pendant la compilation de pdflatex) il y a un diagnostique d'erreur par \SEref 

- [ ! Undefined control sequence
    <argument> \@apprefprefixsingle ..... ] 

mais, enfin la compilation est à bon fin et la reference exacte.

En attachè mes `fichiers
Salutations et merci, Enrico

`\documentclass[10pt,a4paper,twoside]{memoir}
\usepackage[T1]{fontenc}             
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[italian]{babel}
\usepackage[series={A,B,C,D},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}
\setgoalfraction{.85}
\AtBeginDocument{\Xmaxhnotes{0.5\textheight}}
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\theAtest\ - A)}
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\theBtest\ - B)}
\newcounter{Ctest}
\def\Ctest{\stepcounter{Ctest}(\theCtest\ - C)}
\Xonlyside[B]{L}
\Xonlyside[C]{R}

\usepackage{graphicx} \usepackage{xcolor}
\usepackage%[hyperfootnotes=false]
{hyperref}%
\hypersetup{%
colorlinks,linkcolor=red,citecolor=red,urlcolor=red%
}%

\begin{document}
\begin{pages}
	%PAGINE DI SINISTRA TESTO 
	\begin{Leftside}
		\setcounter{Atest}{0}
		\setcounter{Btest}{0}
		\setcounter{Ctest}{0}
		\beginnumbering
		\setlength\parindent{0pt}%
		
		\pstart\relax
		testo \edlabelS{ref-1}testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo\edlabelE{ref-1} testo testo testo testo testo testo testo testo testo testo testo testo testo 
		\pend
		\endnumbering
	\end{Leftside}
		
	%PAGINE DI DESTRA TESTO 
	\begin{Rightside}
		\setlength\parindent{0pt}
		\beginnumbering
		\pstart\relax 
		testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo testo --->>> VEDI LINEE \SEref{ref-1}  (riferimento corretto!)
		\pend
		\endnumbering
	\end{Rightside}	
\end{pages} 
\Pages
\end{document}`

**Comment by maieul** [comment]
please try branch issue582

**Comment by maieul** [comment]
hi, some feedback?

**Comment by maieul** [comment]
je considère que les tests sont probants, vu les fichiers que vous m'avez envoyé. je publie.

**Comment by heinrichffleck** [comment]
Cher ami tres merci pour votre aide.
Maintenant tout est parfait avec votres fichiers.
salutations, Enrico M.
 
=======================
www.heinrichfleck.net



      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Mercoledì 12 Ottobre 2016 13:21
 Oggetto: Re: [maieul/ledmac] Diagnostico con \SEref #582 (#583)
   
je considère que les tests sont probants, vu les fichiers que vous m'avez envoyé. je publie.—
