### ISSUE TITLE
Reference to #582 closed

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#586]
Cher ami,

Aujourd'hui, je l'ai téléchargé la nouvelle version de reledmac du site de CTAN. 
Les instructions  qui font référence a  \Seref (EdlabelS et \EdlabelE) fonctionnent parfaitement  sans avoir besoin de les fichiers que vous me aviez envoyés.
Merci et salutations,

Enrico

**Comment by maieul** [comment]
de rien
