### ISSUE TITLE
 parallel text: keeping a translation in the outside column

### ISSUE THREAD

**Issue by theobear** [maieul/ledmac#591]
I'm using the parallel text for a latin translation. I would like to keep my translation on the outside column of the page (so on even pages it would be on the left and for odd pages on the right) 

example of what I'm trying to achieve:

               Left hand (even) page      |        Right hand (odd) page
       column 2              column 1     |      column 1              column 2
    _translation_  This is the main text  |  This is the main text  _translation_
    _translation_  This is the main text  |  This is the main text  _translation_
    _translation_  This is the main text  |  This is the main text  _translation_
    _translation_  This is the main text  |  This is the main text  _translation_
    _translation_  This is the main text  |  This is the main text  _translation_
    _translation_  This is the main text  |  This is the main text  _translation_
    _translation_  This is the main text  |  This is the main text  _translation_
    _translation_  This is the main text  |  This is the main text  _translation_
    _translation_  This is the main text  |  This is the main text  _translation_

instead of:

               Left hand (even) page        |        Right hand (odd) page
         column 1            columm 2       |         column 1          column 2
    This is the main text   _translation_   |  This is the main text  _translation_
    This is the main text   _translation_   |  This is the main text  _translation_
    This is the main text   _translation_   |  This is the main text  _translation_
    This is the main text   _translation_   |  This is the main text  _translation_

Thank you for considering this matter!

**Comment by maieul** [comment]
hello,

could you please try the branch "issue591" (read here to know how to try the branch)
https://github.com/maieul/ledmac#debug-and-feature-requests

it provides a `movecolumnspositiononrightpage` option of reledpar. Look on the file "issue591.tex" in the zip of the branch to have a exemple of use.

**Comment by theobear** [comment]
This seems to work beautifully! I will try and migrate my project over to this reledmac. Thanks so much.

**Comment by maieul** [comment]
I will publish it on CTAN next week (I have to write the handbook and to ask for english spell checking before)







Le 1 d�c. 2016 � 23:43, theobear <notifications@github.com> a �crit :

**Comment by maieul** [comment]
hi, I have just published the new version on CTAN. You should update your texlive in few day and delete your local .sty file.

Please also validate the answer on StackExchange and vote up.
