### ISSUE TITLE
[reledmac] Typo in Doc

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#592]
Pag. 52, § 11.1:

> Elsewhere in the text, either before or after the `\edlabel`, you can refer to its location via ```\edpageref{⟨lab⟩}```, or ```\edlineref{⟨lab⟩}``` will produce, respectively, the page, line, sub-line and pstart on which the ```\edlabel{⟨lab⟩}``` command occurred.

I would expect:

> Elsewhere in the text, either before or after the `\edlabel`, you can refer to its location via ```\edpageref{⟨lab⟩}```, ```\edlineref{⟨lab⟩}```**, `\sublineref{<lab>}` or `\pstartref{<lab>}`, that** will produce, respectively, the page, line, sub-line and pstart on which the ```\edlabel{⟨lab⟩}``` command occurred.

**Comment by maieul** [comment]
thanks, fixed for next release
