### ISSUE TITLE
\linenumincrement{} alone does not work

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#593]
If I only use \linenumincrement{2}, it has no effect, I always have to add \firstlinenum{something}. Is his a bug or by design?

Let me know if you need an MWE.

**Comment by maieul** [comment]
the default \firstlinenum is set to 5. So if you you do `\linenumincrement{2}`, nothing will appear before line 5.

So you will have line 5, 7, 9 etc. It is perfecly normal. Maybe I could change the default firstlinenum to 0, but I am afraid to break backward compatibility.

**Comment by baem2** [comment]
Right, I see. Just leave it as it is!
