### ISSUE TITLE
nomaxlines-Problems

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#597]
I just tried to change my edition to nomaxlines. This is working fine for the first 16 double-pages, but after that it comes out of sync. I ran TeX so often now that this can't be the problem.

Are you aware of any further limitations? It won't be easy to compile a MWE ...

**Comment by maieul** [comment]
it seems normal that nomaxlines, which is an exception of the normal way of synchronize, could make problem of synchronism�

**Comment by baem2** [comment]
Okay, then I maybe did not understand the functionality correctly.

I thought with nomaxlines, it tries to have the paragraphs on the same height, but if on one side a paragraph is longer, it just can add some more lines there. I'll re-read ... ;)

**Comment by maieul** [comment]
honestly, I don't remember exactly. That is a a very complex topic :)

**Comment by Doc73** [comment]
Ah! Just yesterday I had serious problems, which I have solved (at one o'clock, after hours of investigation) by disabling this option! 👍

**Comment by maieul** [comment]
I never thank this option was pertinent to get a full automatically sync pages. You must read carefully the technical handbook to understand the different options, and what should be the better in your case.

**Comment by maieul** [comment]
I have to admit that is a complexe topic (one of the more complex of reledpar!)

**Comment by maieul** [comment]
I close this issue, as there is no MWE, no pist of solution, and not well described problem.
