### ISSUE TITLE
problème d'espacement de section

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#599]
from @doc73

> Simply, after some pairs environment, LaTeX doesn't see the option
> \titlespacing*{\section}{0pt}{30pt}{10pt}
> and in particular the 30pt (= before spacing).

**Comment by maieul** [comment]
provoqué par 84db160d03d1583db1fffb5ef03547d5d7f7a10e

**Comment by maieul** [comment]
dear @doc73, please try the branch "issue599", and tell me, before saturday if possible.

**Comment by Doc73** [comment]
Very well!
I tested the branch in my whole book and all works very well!

Many many many thanks!

**Comment by maieul** [comment]
your welcome.

wille be published this week-end, I hope
