### ISSUE TITLE
no pagebreak within paragraphs

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#600]
In my MWE something must be wrong, but I cannot find the mistake. Page breaking does not work. 
I am using reledmac v2.16.6 and reledpar v2.14.4. 

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage[series={A},noeledsec,noend]{reledmac}
\usepackage{reledpar}
\usepackage{lipsum}

\begin{document}

\begin{ledgroup}

\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
\lipsum[1-3]
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
\lipsum[1-3]
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\end{ledgroup}

\end{document}

**Comment by maieul** [comment]
ledgroup va not concepted to have pairs inside� 
so it could not work, except if a take a long time for doing it� and honestyl, I have not (and also: I have many older bug to solve)

**Comment by sonator** [comment]
You are right. Indeed, it is not a substantial problem. 
Just I have remarked that the page breaking does not work, too, if the MWE is not placed inside of a ledgroup environment. 
In any case, thank you for answering so quickly!

**Comment by maieul** [comment]
that is a bug ;-)

**Comment by maieul** [comment]
ok, I think the bug (outside of ledgroup, and it seems inside of ledgrou�) has been solved in the futur version of reledmac / reledpar, that you could find on branch 2.16.7-2.15.0

I have added it in the past, I don't know exactly when. Normally, this version will be released this week-end

**Comment by sonator** [comment]
Il fait en quelque sorte curieux. But, using reledmac v2.8.2 and reledpar v2.7.1, I have worked on some texts placed in pairs within a ledgroup environment without any problems. This was and is a highly useful feature. 

Just I have tested the new version on a 7 pages long text in columns inside and outside of a ledgroup environment -- with perfect results. 

One observation is to indicate: reledmac is sending a lot of warnings related to the line, in which \Columns is placed. 

Once more thank you very much for the solution!

**Comment by maieul** [comment]
Le 9 d�c. 2016 � 17:44, sonator <notifications@github.com> a �crit :

> Il fait en quelque sorte curieux. But, using reledmac v2.8.2 and reledpar v2.7.1, I have worked on some texts placed in pairs within a ledgroup environment without any problems. This was and is a highly useful feature.
> 

so maybe it is working now, I don't know.
> Just I have tested the new version on a 7 pages long text in columns inside and outside of a ledgroup environment -- with perfect results.
> 
> One observation is to indicate: reledmac is sending a lot of warnings related to the line, in which \Columns is placed.
> 

with this MWE ? or with an older one? do you remember if these messages were here in the past?

**Comment by sonator** [comment]
Sorry for the delay!
The MWE below is running under v2.8.2 and v2.7.1 without any error messages and warnings. The page is broken within the paragraph. Similar constructions I have used in the past with good results. 

Under v2.16.7 and v2.15.0 the first warning I get indicates: 
PackageWarning{reledmac}{You are using a LaTeX version older than 2016/03/31 patch 3.%
   \MessageBreak You are strongly encouraged to use a newer version.}}%

Then are following 56 warnings of this sort: 
Package reledmac Warning: 1 on input line 34. 
Package reledmac Warning: 2 on input line 34. 

However, yesterday in the university I have used a fresh MiKTeX distribution. And the number of warnings has been the same. 

The mentioned older 7 pages text causes under the new versions 227 warnings: 
Package reledmac Warning: 1 on input line 154. 
Package reledmac Warning: 2 on input line 154. 
...
Package reledmac Warning: 7 on input line 154. 

Nevertheless in both cases the outputs are okay!

\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage{lipsum}
\usepackage{reledmac}
\usepackage{reledpar}

\begin{document}

\begin{ledgroup}

\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
\lipsum[1-3]
\pend
\endnumbering
\end{Leftside}


\begin{Rightside}
\beginnumbering
\pstart
\lipsum[1-3]
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\end{ledgroup}

\end{document}

**Comment by maieul** [comment]
oh, you are right. It was test message forgiven by me. The new version of the branch solve it.

The warning 
````
You are using a LaTeX version older than 2016/03/31 patch 3.%
\MessageBreak You are strongly encouraged to use a newer version.
````

is, I think, explicit ;-)

**Comment by sonator** [comment]
I would like to confirm that the collection of warnings has disappeared. 
Thank you very much for the solution!

**Comment by maieul** [comment]
so, we can close?

**Comment by sonator** [comment]
Yes, indeed, we can close. Thank you a lot!

**Comment by maieul** [comment]
I hope to publish this version tomorrow.
