### ISSUE TITLE
Apparatus of manuscripts – feature request

### ISSUE THREAD

**Issue by pharos-alexandria** [maieul/ledmac#606]
If the manuscripts change in the middle of a line, it would be good to have the change recorded to a lemma, i.e.

1-5 lemma : ABCD 5-15 lemma2 : ABC 

Manuscripts ABCD have the text until "lemma" in line 5, while manuscripts ABC have the text from "lemma2" in line 5. (line 1 being the first and line 15 being the last on the page)

Even better would be (in my view):

ABC D(desinit 5 lemma)

(and on the next page: ABC)

Would something like that be acheivable?

**Comment by maieul** [comment]
I dont see how I could automatically select the good lemma, as we don't work lemma by lemma.

**Comment by pharos-alexandria** [comment]
At the moment I use this workaround:

```
\documentclass[12pt,a4paper]{memoir}
\usepackage{lipsum} 
\usepackage{fontspec} 
\usepackage[english]{babel}
\usepackage{xunicode} 
\usepackage[series={A},noend,noeledsec]{reledmac}
\usepackage{reledpar} 
\Xarrangement{paragraph}
\Xnolemmaseparator[A]
\Xinplaceofnumber[A]{0em}
\Xinplaceoflemmaseparator[A]{0.25em}
\setmsdatalabel{}
\newcommand{\mspart}[3]{\edtext{#1}{\Afootnote[nosep]{#2}}\msdata{#3}}
\begin{document}
\chapter{Test chapter}
\beginnumbering
\pstart
\msdata{ABCD}\lipsum[1] \mspart{Text}{des. B}{ACD}
\pend
\pstart
\lipsum[1] \mspart{Text}{inc. E}{ACDE}
\pend
\pstart
\lipsum[1]
\pend
\pstart
\lipsum[1]
\pend
\endnumbering
\end{document}
```

which gives this:

```
1–13 ABCD 13–26 ACD 13 Text des. B 26 ACDE 26 Text inc. E
```

while I would like to have this (i.e. the \msdata coming after the regular Afootnote-entry):

```
1–13 ABCD 13 Text des. B 13–26 ACD 26 Text inc. E 26 ACDE
```

**Comment by maieul** [comment]
It was hard for me to understand the problem, but now, the solution is obvious.

Actually, the ms data are inserted, in a line, before regular notes.
I could add an option to insert if after regular notes.
The only difficulty is to find a name for this option�

**Comment by pharos-alexandria** [comment]
printmsdataafterregularnotes?

**Comment by maieul** [comment]
\msdataposition{regular-msdata}
\msdataposition{msdata-regular}

? as we have for the position of familiar/critical footnotes

**Comment by maieul** [comment]
but note that won't solve your problem if you have multiple change of manuscript in the same line, or if you want to have 

ms - lemma - ms - lemma

for this case, it would be considerably more complex, as ms apparatus must be repeated in each page

**Comment by pharos-alexandria** [comment]
Ok, I may be lucky and have no more complex cases...

**Comment by maieul** [comment]
we could start by that� I will try to talk a quart of hour for this need

**Comment by maieul** [comment]
please try the branch "issue606", which provides a `\setmsdataposition`

**Comment by pharos-alexandria** [comment]
Whit reledmac it works as expected, but with reledpar it does not work as expected. Position is msdata-regular, whether \setmsdataposition{regular-msdata} is set or not.

```
\documentclass[12pt,a4paper]{memoir}
\usepackage{lipsum} 
\usepackage{fontspec} 
\usepackage[english]{babel}
\usepackage{xunicode} 
\usepackage[series={A},noend,noeledsec]{reledmac}
\usepackage{reledpar} 
\Xarrangement{paragraph}
\Xnolemmaseparator[A]
\Xinplaceofnumber[A]{0em}
\Xinplaceoflemmaseparator[A]{0.25em}
\setmsdatalabel{}
\setmsdataposition{regular-msdata}
\newcommand{\mspart}[3]{\edtext{#1}{\Afootnote[nosep]{#2}}\msdata{#3}}
\begin{document}
\chapter{Test chapter}
\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart
\msdata{ABCD}\lipsum[1] \mspart{Text}{des. B}{ACD}
\pend
\pstart
\lipsum[1] \mspart{Text}{inc. E}{ACDE}
\pend
\pstart
\lipsum[1]
\pend
\pstart
\lipsum[1]
\pend
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\pstart
\lipsum[1]
\pend
\pstart
\lipsum[1]
\pend
\pstart
\lipsum[1]
\pend
\pstart
\lipsum[1]
\pend
\endnumbering
\end{Rightside}
\end{pairs}
\Columns
\end{document}
```

**Comment by maieul** [comment]
The new version of the branch should solve this problem.

**Comment by pharos-alexandria** [comment]
Thank you! Now it works.

**Comment by maieul** [comment]
your welcome.

I will publish it Friday, I think, as christmas gift�
