### ISSUE TITLE
\ledsidenote problem with reledpar

### ISSUE THREAD

**Issue by pharos-alexandria** [maieul/ledmac#607]
``\ledsidenote`` in left column does not work anymore with **reledpar**. It still works with reledmac only. See the following MWE:

```
\documentclass[twoside,14pt,onecolumn,openright ,a4paper]{memoir}
\usepackage{lipsum} 
\usepackage{fontspec} 
\usepackage[english]{babel}
\usepackage{xunicode} 
\usepackage[series={A},noend,noeledsec]{reledmac}
\usepackage{reledpar} 
\sidenotemargin*{outer}
\linenummargin{right}
\begin{document}
\chapter{Test chapter}
\begin{pairs}
  \begin{Leftside}
    \beginnumbering
    \pstart
    \ledsidenote{1}\lipsum[1]
    \lipsum[1]
    \pend
    \endnumbering
  \end{Leftside}
  \begin{Rightside}
    \beginnumbering
    \pstart
    \ledsidenote{2}\lipsum[1]
    \lipsum[1]
    \pend
    \endnumbering
  \end{Rightside}
\end{pairs}
\Columns 
\end{document}
```

**Comment by maieul** [comment]
did it work in the past? do you remember in which version?

**Comment by pharos-alexandria** [comment]
I was on TeXLive 2015 until recently. Does this help?

**Comment by maieul** [comment]
not a lot, as I don't remember which version was the last one in texlive. I will look anyway.

**Comment by pharos-alexandria** [comment]
It's \ProvidesPackage{reledpar}[2016/03/23 v2.8.0 reledmac extension for parallel texts]%

**Comment by maieul** [comment]
strange, it seems that 16341b822a77954518dd7897f6d52bea9a0a9951, which is related to #606, added the bug. I am looking on.

**Comment by maieul** [comment]
please try branch issue607

**Comment by pharos-alexandria** [comment]
It works, also with my real life files. Thanks again very much! Happy new year!

**Comment by maieul** [comment]
your'e welcome. And happy new year too!
