### ISSUE TITLE
Alphabetical lineation for texts over 26 lines

### ISSUE THREAD

**Issue by Alessio-R** [maieul/ledmac#609]
I'm trying to use the alphabetical lineation for a text that exceeds the current maximum number of alphabetical characters allowed (= the 26 letters of the english alphabet) and this results in an error which says "counter too large".
I would ask if it is possible to add a feature to support this kind of lineation, using e.g. aa, ab, ac ... ba, bb, bc and so on for line numbers over the 26th line.

Here is an MWE that shows this problem:

```
\documentclass[a4paper, 12pt]{article}

\usepackage[noend]{reledmac}
\usepackage[continuousnumberingwithcolumns]{reledpar}

\usepackage{lipsum}

\begin{document}

\pagenumbering{gobble}

\linenumberstyle*{alph}
\firstlinenum*{1}
\linenumincrement*{1}

\vspace*{1cm}

\beginnumbering
\pstart

\lipsum[1-3]

\pend
\endnumbering

\end{document} 
```

Thank you!

**Comment by maieul** [comment]
won't be possible before many time�
-----
Ma�eul
http://blog.maieul.net
http://www.schtroumpfs.maieul.net/

Le 9 janv. 2017 � 15:24, Alessio-R <notifications@github.com> a �crit :

**Comment by Alessio-R** [comment]
Ok, I will wait for a future implementation.

**Comment by maieul** [comment]
I am sorry, but for now, I have to add the remarks of my supervisor in my thesis, and it is quite desperating, because its seems that I am too bad for searching�

**Comment by Alessio-R** [comment]
Ok no problem, take all your time. I do not want you to be distracted from your thesis! I will eventually try to ask on Stackexchange about a possible interrelation between reledmac and alphalph package (http://tex.stackexchange.com/questions/52599/error-counter-too-large-with-alphcntr-and-cntr26)

**Comment by Alessio-R** [comment]
I have noticed that using alphalph package in combination with lineno package will print the line numbers alphabetical list as intended (even lineno package by default print only 26 alphabetical line numbers), as you can see in the following MWE:

```
\documentclass[a4paper, 12pt]{article}

\usepackage{lipsum}

\usepackage{alphalph}

\usepackage{lineno}
\renewcommand\thelinenumber{\alph{linenumber}}

\renewcommand{\thelinenumber}{\alphalph{\value{linenumber}}}

\begin{linenumbers}
\lipsum[1-3]
\end{linenumbers}

\end{document}
```

It is possible to use this command of the alphalph package in combination with reledmac?

**Comment by maieul** [comment]
if it would be possible directly, I would have add it to reledmac directly�
there is problem, because we work on TeX level, not LaTeX level, like lineno. But I will find�

**Comment by maieul** [comment]
after loading reledmac, add this line in your preamble

\def\linenumrep#1{\alphalph{\the#1}}

**Comment by Alessio-R** [comment]
Ok I did, but it gives the same error "counter too large"

**Comment by maieul** [comment]
This MWE is working :
\documentclass{article}
\usepackage[noend,noeledsec]{reledmac}
\usepackage{alphalph}
\linenumincrement{1}
\firstlinenum{1}

\def\linenumrep#1{\alphalph{\the#1}}

\begin{document}
\beginnumbering
\pstart
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur,
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur,
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
\pend
\endnumbering
\end{document}



Le 12 janv. 2017 � 15:17, Alessio-R <notifications@github.com> a �crit :

**Comment by sieversMartin** [comment]
Am 12.01.2017 um 15:17 schrieb Alessio-R:
> Ok I did, but it gives the same error "counter too large"
> 

You have to remove "\linenumberstyle*{alph}" as well

See Maieul's answer.

Best
Martin


-- 

Martin Sievers -- Einfach schöner publizieren

Im Alten Garten 5
54296 Trier

Telefon:  +49 (0) 651 4936567-0
Telefax:  +49 (0) 651 4936567-9
Mobil:    +49 (0) 179 7347726

Internet: http://www.schoenerpublizieren.de
E-Mail:   info@schoenerpublizieren.de

**Comment by Alessio-R** [comment]
Yes, you're right! Thank you, It works perfectly!! :D

**Comment by Alessio-R** [comment]
One last thing: how can I do now to alternate sections with arabic line numbers and sections with alphabetical line numbers?

**Comment by maieul** [comment]
just call the good command between sections�

Le 12 janv. 2017 � 17:54, Alessio-R <notifications@github.com> a �crit :

**Comment by maieul** [comment]
I close this issue.
