### ISSUE TITLE
Reappears the spurious space in apparatus with LuaLaTeX?

### ISSUE THREAD

**Issue by JuanManuelM** [maieul/ledmac#611]
Hello. I tried to compile recently two documents with LuaLaTeX (usually I work with XeLaTeX), and in the apparatus appears on several occasions (images below) the spurious space that was described in bug #397, which is supposed to have been fixed.

![img1](https://cloud.githubusercontent.com/assets/25255465/22167003/3bac8246-df64-11e6-84e1-10d6a5ada352.jpg)

![img2](https://cloud.githubusercontent.com/assets/25255465/22167004/3eaabfa8-df64-11e6-92ae-212ad6a47a09.jpg)

I've added some more lemmas to the sample text of that bug, and the problem also appears:

```
\documentclass{article}

\usepackage{reledmac}

\Xarrangement[A]{paragraph}

\begin{document}
\meaning\textdir
\beginnumbering
\pstart
\edtext{Subiectum}{\Afootnote{Prueba}} \edtext{igitur}{\Afootnote{Prueba}} \edtext{huius}{\Afootnote{Prueba}} \edtext{scientiae}{\Afootnote{Prueba Prueba Prueba Prueba prueba}} est animal, secundum quod in
eo est principium motus ad somnum et uigiliam, et hoc est rationale,
quia ista scientia subalternatur
\edtext{scientiae}{\Afootnote{subiectae \emph{M}}} traditae in libro
Physicorum, et ideo subiectum huius continetur sub subiecto illius.
Somnus multipliciter describitur. Philosophus enim ponit duas
descriptiones somni; una est, quod somnus est impotentia sentiendi
propter excessum uigiliae, alia est, quod somnus est immobilitatio
sensuum \edtext{exteriorum}{\Afootnote{exteriori
\emph{a. c. M}}}. Alias duas descriptiones ponit Commentator;
una est, quod somnus est sensus in potentia. Dormienti
\edtext{enim}{\Afootnote{\emph{om. L}}} uidetur, quod comedat et potet
et sentiat per omnes \edtext{quinque}{\Afootnote{\emph{s.  l. L,
om. A}}} sensus, et secundum eum uigilia est sensus in
actu, et quandoque \edtext{contingit}{\Afootnote{conuenit \emph{M}}},
quod sensus in potentia exeat in actum, ut in somniis ueris
praenuntiatiuis mirabilium, et tunc sensus, qui est in potentia, est
nobilior, quam sensus, qui est in actu. Sensus autem in potentia, cum
fuerit falsus, tunc est uilis, et sensus in actu est nobilior eo. Alio
\edtext{modo}{\Afootnote{\emph{om. A}}}
\edtext{describit}{\Afootnote{descripsit \emph{A}}} Commentator somnum
sic: Somnus est \edtext{reuocatio}{\Afootnote{reuolutio \emph{A}}}
\edtext{caloris}{\Afootnote{calorum \emph{A}}} naturalis ad interius
ab \edtext{organis}{\Afootnote{orig(.) \emph{a. c. M}}} corporeis
\edtext{exterius}{\Afootnote{\emph{An} externis \emph{scribendum?}}},
et \edtext{sic}{\Afootnote{tunc \emph{AL}}} patet, quid est somnus.
\pend
\endnumbering
\end{document}
```

![img3](https://cloud.githubusercontent.com/assets/25255465/22167017/4d2f1ace-df64-11e6-8b1f-686f88efe462.jpg)

On reledmac 2016/11/14 v2.16.6 and TeXLive 2016.

Thank you for your great work, best regards

**Comment by maieul** [comment]
it is not the same bug as #397. I am looking on.

**Comment by maieul** [comment]
please try branch issue611

**Comment by JuanManuelM** [comment]
I have tried it and all works fine! Thank you very much.

**Comment by maieul** [comment]
you'r welcome.
I will just do some test and publish it on CTAN quickly



Le 21 janv. 2017 � 00:18, JuanManuelM <notifications@github.com> a �crit :

**Comment by maieul** [comment]
do you use luaalatex to typeset Right to Left text? 
If yes, could check that the new version doesn't break feature?

**Comment by JuanManuelM** [comment]
I don't work with Right to Left texts, I'm afraid I could not do an entirely satisfactory test, sorry... Anyway, I've tried switching the direction of the main text in the sample, with a \textdir TRT\pardir TRT before \pstart and everything seems to go ok...

**Comment by maieul** [comment]
the problem could happen only in notes. I have asked to @ralessi. Maybe he could do the test
