### ISSUE TITLE
Problem with pagination using reledpar

### ISSUE THREAD

**Issue by Naufragus** [maieul/ledmac#612]
I'm preparing a bilingual edition of poetry (with texts faced in parallel page-against-page). With the MWE I add I have not quite succeeded in reproducing the problem I have, but it is more or less near to  it.

If compiled the main document, the text start at p. 6 althoug the p. 4 (verso of the title page) is empty. In fact this means I have a superfluous page in blank. In the real case of my work, I have also such empty pages (two) at he end of one of theese subdocuments. 

[DocsTex.zip](https://github.com/maieul/ledmac/files/739325/DocsTex.zip)

**Comment by maieul** [comment]
I won't solve the problem without real MWE.

You are not the only one user of reledmac/reledpar, and I can loose time to try to have an example of your problem.

**Comment by Naufragus** [comment]
The texts I added are real, truly part of my work. I can't add the whole work.

**Comment by maieul** [comment]
Do yo know that I work for nothing on reledmac/reledpar? If you don't help me, I can't help you.
You could have replace by blablab…

but indeed, I have looked on your file: that is a real true MWE. I don't understand why you told me that the problem was not fully here.

**Comment by Naufragus** [comment]
Yes I know that you work for nothing. I have said that this is a real MWE (instead of using bla, bla, bla I have repeated the texts). What I say is that this MWE, which is real, doesn't reproduce all the problem I have. In my complet document I have the pages in blank _at the beginning_ of the whole compilation result, like here, but also _at the end_ of one subdocument . I hope now I have explained better what I wanted. Excuse me if I have not bean so clear and thanks for your help.

**Comment by maieul** [comment]
at the end after a \part, or not? 

I think that is unrelated problem. I will try to get time to solve this issue with part, but that is not obvious.

**Comment by Naufragus** [comment]
Yes, after a \part.

**Comment by maieul** [comment]
so you \part
\begin{pages}
�
\end{pages}
\Pages

and you have spurious blank page between the \part and the \pages?

**Comment by Naufragus** [comment]
Yes. Moreover, at the end of one subdocuemnt. But this I can't reproduce with this MWE. I don't know why. But I suppose the two situations are related.

**Comment by maieul** [comment]
I thought the problem was after the \Pages, not before.

The problem could not be solved directly in reledpar, because it is on the \part command. (cf #463).

You can add in your preamble

```
\makeatletter
\patchcmd{\@endpart}{\null}{}{}{}
\makeatother
```

**Comment by Naufragus** [comment]
Thanks! This helped with the problem I can reproduce... but not with the second. I'll be trying to reproduce the second part of the problem -and to add here another piece of MWE-: the phantom pages at the end of one subdocument.

**Comment by maieul** [comment]
I think this second problem is linked to the cumul of multiple \pages + optional argument in \pend.  

I close this issue, please open a new one with you MWE… and use a title less generic.
