### ISSUE TITLE
Chapters and paragraphs

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#613]
In my current project, the greek chapter name (3 lines) is longer than the german one (2 lines). This leads to a problem: On the first page, the paragraphs do not start at the same height.

See MWE:
```
\documentclass{report}
\usepackage[utf8]{inputenc}
\usepackage[series={A}]{reledmac}
\usepackage{reledpar}
\usepackage{blindtext}

\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart[\chapter{This is a headline with linebreak}]
\blindtext
\pend

\pstart
\blindtext
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart[\chapter{This is a headline}]
\blindtext
\pend

\pstart
\blindtext
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages

\end{document}
```

**Comment by maieul** [comment]
yes, that is a knew problem. For now, I have no time to lookon. You could add \\\null after the short chapter name

Le 31 janv. 2017 � 09:45, Philipp <notifications@github.com> a �crit :

**Comment by baem2** [comment]
Okay, thanks for the workaround, that's all I need to know.

**Comment by maieul** [comment]
I close it (that is similar to #379)
