### ISSUE TITLE
repeatstandapenalties

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#62]
comme repeatstanza indent, mais pour \setstanzapenalties

**Comment by rrthomas** [comment]
I'm a bit puzzled that this issue is closed: I am interested in auto-repeating `\setstanzapenalties` (to avoid breaks in the middle of rhyming couplets), but I can't see that it works that way.

**Comment by maieul** [comment]
Honestly, I did never work on this problem of stanzapenalties
YOu may reopen a new issue if you want (but I cant tell you when I
would have time for this)
