### ISSUE TITLE
Saut de page nomaxlines

### ISSUE THREAD

**Issue by Circeb** [maieul/ledmac#620]
Bonjour,

J'utilise l'option nomaxlines, qui marche bien étant donné que mes textes de gauche sont plus courts que ceux de droite. Cela marche dans l'ensemble bien, mais je trouve que l'option pousse à passer à la page suivante bien plus qu'il ne paraît nécessaire (en ne remplissant qu'une moitié de page avec un "chunk", et en mettant le "chunk" suivant sur l'autre page). Y a-t-il une manière d'éviter, ou du moins de limiter cela ?

**Comment by maieul** [comment]
c'est peut être lié au goalfraction? mais il n'y a pas que le maxline qui compte, il y a aussi advancedshiftedpstarts 

cf http://geekographie.maieul.net/185

**Comment by Circeb** [comment]
je n'utilise pas advanceshiftedpstarts. J'ai essayé d'augmenter le goalfraction à 9.5, ça n'a pas eu d'effet notable. ce qui m'étonne est que sans l'option nomaxlines, le programme met bien sur une seule page deux textes qu'il sépare avec cette option.

**Comment by maieul** [comment]
c'est effectivement étonnant, mais il y a tellement de cas possible que cela ne me surprend pas tant que cela finalement.

j'imagine que tu as bien utilisé latexmk pour être sur d'avoir le bon nombre de passe?

**Comment by Circeb** [comment]
Je l'ai fait oui.

**Comment by maieul** [comment]
je ne sais pas. il faudrait decrypter le contenu des fichiers temporaires pour savoir

**Comment by Circeb** [comment]
Quels fichiers temporaires faudrait-il regarder ? Sinon, il n'y aurait pas un moyen d'empêcher localement le saut de page ?

**Comment by maieul** [comment]
les fichiers .1, .1R etc. Mais il faut savoir aussi les analyser, ce qui n'est pas évident.

Oui on peut bloquer localement le saut de page avec lednopb, mais je doute que cela suffise à résoudre le problème.

**Comment by Circeb** [comment]
lednopb n'a en effet aucun effet. Voici les fichiers .2, .2R, qui doivent correspondre à un endroit avec un saut de page inattendu entre deux textes:
.2:

\line@list@version{5}
\@par@sync@option{nomax}
\@pstart{1}{138}{0}
\@nl[138][138]
\@nl[138][138]
\@nl[138][138]
\@nl[138][138]
\@nl[138][138]
\@ref[3][
\@lemma
]
\@nl[138][138]
\@nl[138][138]
\@nl[138][138]
\@pend[8]
\@lopL{26}
\@pstart{2}{140}{0}
\@nl[140][140]
\@nl[140][140]
\@nl[140][140]
\@nl[140][140]
\@ref[3][
\@lemma
]
\@nl[140][140]
\@nl[140][140]
\@nl[140][140]
\@ref[3][
\@lemma
]
\@nl[140][140]
\@pend[8]
\@lopL{1000}

.2R:

\@pstartR{1}{139}{0}
\@nl[139][139]
\@nl[139][139]
\@nl[139][139]
\@nl[139][139]
\@nl[139][139]
\@nl[139][139]
\@nl[139][139]
\@nl[139][139]
\@nl[139][139]
\@nl[139][139]
\@pendR[10]
\@lopR{27}
\@pstartR{2}{141}{0}
\@nl[141][141]
\@nl[141][141]
\@nl[141][141]
\@nl[141][141]
\@nl[141][141]
\@nl[141][141]
\@nl[141][141]
\@nl[141][141]
\@pendR[8]
\@lopR{1000}

J'avoue que je ne vois aucune différence entre ce code et celui pour deux textes qui restent sur la même page...

**Comment by maieul** [comment]
il me faudrait l'ensemble des fichiers pour que je puisse comprendre

**Comment by Circeb** [comment]
J'ai fait un exemple minimal. Le problème n'apparaît que sur les deuxièmes pages (.2 et .2R) -- si j'enlève les premières, les textes ne mettent normalement sur une seule page au lieu de deux.

[Essai.zip](https://github.com/maieul/ledmac/files/770792/Essai.zip)

**Comment by maieul** [comment]
je regarderai tout cela dans le train mercredi si j'ai le temps

**Comment by Circeb** [comment]
Super, merci !

**Comment by maieul** [comment]
le zip ne contient pas le fichier .tex, qui est le plus important…

**Comment by Circeb** [comment]
De fait... J'ai encore simplifié pour ne pas avoir besoin des fichiers annexes.

[Essai.zip](https://github.com/maieul/ledmac/files/770818/Essai.zip)

**Comment by maieul** [comment]
j'ai juste jeter un coup d'œil pour m'assurer que tout allait bien. 


En gros pour vous le probème se situe au niveau du passage de la page iii à la page iv ? 

Si oui, c'est parfaitement normal, vu que vous utiliser des \Pages. Chaque \Pages recommence une nouvelle série de pages gauche/droite.

Si vous voulez avoir quelque chose de continue, il vous faut un seul environement pages, et une seule commande \Pages

Si ce n'est pas là, alors dites moi plus clairement où se situe le problème.

**Comment by Circeb** [comment]
Il me semble que le \pages apparaît après la page v (avant les textes T3/T4), avant il y a deux textes dans deux \pstart mais dans la même page, qui apparaissent cependant sur deux pages différentes (T1 et T2).

**Comment by Circeb** [comment]
Il me semble que T1 et T2 devraient être sur la même page, ainsi que T3 et T4, la rupture de page ne se trouvant qu'entre ces deux groupes.

**Comment by maieul** [comment]
le texte T3 commence à la page iv. 
T1 et T2 apparaissent sur la même page chez moi. (ii et iii)

**Comment by Circeb** [comment]
vraiment ? chez moi, chaque texte est sur une page différente (en général, après plusieurs compilations). C'est aussi le cas pour T3 et T4 ?

**Comment by maieul** [comment]
Dans le zip que tu m'a envoyé, il y effectivement un problème. Par contre si j'efface tous les fichiers temporaires et que je relancer un latexmk sur le fichier. 
[Mon fichier après compilation](https://github.com/maieul/ledmac/files/770885/Essai.pdf)
[Le fichier que tu as envoyé](https://github.com/maieul/ledmac/files/770887/Essai.pdf)

Peux tu reeasyer une compilation avec latexmk au propre ? quelle version de reledmac/reledpar utilise tu ?

**Comment by Circeb** [comment]
De fait, en chargeant les derniers packages, en supprimant tous les fichiers auxiliaires et en lançant latexmk, ça marche.

**Comment by maieul** [comment]
bon, ben on clot alors ;-)
