### ISSUE TITLE
\Xnumberonlyfirstintwolines et \Xsymlinenum

### ISSUE THREAD

**Issue by Circeb** [maieul/ledmac#623]
Bonjour,

Je voudrais utiliser \Xnumberonlyfirstintwolines. Mais quand j'ajoute cette option, \xsymlinenum, au lieu de remplacer mon habituel \xparafootsep entre deux lignes du même nombre, s'y additionne : j'ai donc :
 1 amet ] lorem ipsum || | amet ] lorem ipsum || 4 amet ] lorem ipsum 
au lieu de :
1 amet ] lorem ipsum | amet ] lorem ipsum || 4 amet ] lorem ipsum

Voici l'exemple :

\documentclass{book}

\usepackage{reledmac}
\Xarrangement[A]{paragraph}
\Xnumberonlyfirstinline
\Xnumberonlyfirstintwolines
\Xparafootsep{$\parallel$ }
\Xsymlinenum{$\mid$}

\begin{document}
\beginnumbering
\pstart
Lorem ipsum dolor sit \edtext{amet}{\Afootnote{lorem ipsum}}, consectetur  \edtext{amet}{\Afootnote{lorem ipsum}}adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse \edtext{amet}{\Afootnote{lorem ipsum}} cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit  \edtext{amet}{\Afootnote{lorem ipsum}} anim id est laborum.
\pend
\endnumbering

\end{document}

**Comment by maieul** [comment]
Ce bug a été introduit en 1.1.0 !

A priori, la branche issue623 résoud cela. Mais peux tu tester en texte parallèle pour que je sois sûr?

**Comment by Circeb** [comment]
Le symlinenum remplace bien le parafootsep habituel (aussi en texte parallèle), mais le parafootsep normal a disparu :
1 amet ] lorem ipsum | amet ] lorem ipsum 4 amet ] lorem ipsum

**Comment by maieul** [comment]
of course,

my fix could'nt work. I think on a real solution

**Comment by maieul** [comment]
Peux tu essayer la nouvelle version (aussi en //)

**Comment by Circeb** [comment]
Ca m'a l'air de marcher !

**Comment by maieul** [comment]
super ! je vais demander à des gens de corriger l'anglais, et on pourra publier
