### ISSUE TITLE
Separator between paragraph and line numbers

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#624]
Hi! Instead of the default separator "-", I want to use "."
I have created an .ist index style file according to the guidelines of the manual of reledmac (p. 56), but  nothing gets printed. Any ideas on how to solve this? Below follows a MWE. Thank you in advance.

**Comment by NiAgio** [comment]
\documentclass[a4paper]{book}
\usepackage{polyglossia,fontspec,xunicode}

\setmainfont{Linux Libertine O}
\setmainlanguage[variant=polytonic]{greek}

\usepackage[makeindex]{imakeidx}

\usepackage[noeledsec,series={A,B,C}]{reledmac}

\lineation{pstart}

\Xarrangement[A,B,C]{paragraph}
\Xnumberonlyfirstinline[A,B,C]
\Xinplaceofnumber[A,B,C]{0pt}
\Xinplaceoflemmaseparator[A,B,C]{2pt}

\renewcommand{\thepageline}{%
\the\value{pstart}%
\pagelinesep%
\xlineref{\edindexlab\thelabidx}%
%}

\makeindex[program=makeindex,options=-s mystyle]

\begin{document}
\beginnumbering
\numberpstarttrue
\pstart
\edindex{Ὄνομα}Νικόλαε, ἡ μακρόχρονη παραλήγουσα παίρνει περισπωμένη, ὅταν ἡ λήγουσα εἶναι βραχύχρονη.
\pend
\endnumbering
\printindex
\end{document}

**Comment by NiAgio** [comment]
In the .ist file I have inserted: 
page_compositor "."
delim_r "."

**Comment by maieul** [comment]
You must also redefine `pagelinesep`

`\renewcommand{\pagelinesep}{.}`


With that, reledmac will write a . instead of a - as separator, and with your .ist file, makeindex will be able to treat this separator.

**Comment by NiAgio** [comment]
Many thanks! It works fine!

**Comment by maieul** [comment]
Your welcome!

**Comment by NiAgio** [comment]
Oooops... there is a problem... Now every separator (both the paragraph-line separator and the separator showing the beginning and the end of the indexed text) are printed with "." See the MWE below. Sorry for the inconvenience.

**Comment by NiAgio** [comment]
\documentclass[a4paper]{book}
\usepackage{polyglossia,fontspec,xunicode}

\setmainfont{Linux Libertine O}
\setmainlanguage[variant=polytonic]{greek}

\usepackage[makeindex]{imakeidx}

\usepackage[noeledsec,series={A,B,C}]{reledmac}

\lineation{pstart}

\Xarrangement[A,B,C]{paragraph}
\Xnumberonlyfirstinline[A,B,C]
\Xinplaceofnumber[A,B,C]{0pt}
\Xinplaceoflemmaseparator[A,B,C]{2pt}


\renewcommand{\thepageline}{%
\the\value{pstart}%
\pagelinesep%
\xlineref{\edindexlab\thelabidx}%
}

\renewcommand{\pagelinesep}{:}

\makeindex[options=-s mystyle]

\begin{document}
\beginnumbering
\numberpstarttrue
\pstart
\edindex{Ὄνομα|(}Νικόλαε, ἡ μακρόχρονη παραλήγουσα παίρνει περισπωμένη, ὅταν ἡ λήγουσα εἶναι βραχύχρονη\edindex{Ὄνομα|)}.
\pend
\endnumbering
\printindex
\end{document}

**Comment by maieul** [comment]
Your delim_r was incorrect.

here a correct one

https://github.com/maieul/ledmac/blob/issue624/mystyle.ist

**Comment by maieul** [comment]
here the good link

https://github.com/maieul/ledmac/blob/4c490632c83295f5b8a07499c11c20c0030aca8e/mystyle.ist

I have corrected the handbook https://github.com/maieul/ledmac/commit/e25f90819e5bd7bf5a479312cbf13b9ac2d77874

**Comment by NiAgio** [comment]
Ok... now I feel dumm... I am apparently :)
Thanks once more! Everything works perfect!

**Comment by maieul** [comment]
my handbook was misleading
