### ISSUE TITLE
Tex4ht doesn't work with reledmac

### ISSUE THREAD

**Issue by matteofadini** [maieul/ledmac#625]
Hi, 

I'm trying to convert some .tex file with reledmac comands into .odt (or .doc) file; normally I use tex4ht, with this command: htlatex file.tex "xhtml,ooffice" "ooffice/! -cmozhtf" "-coo -cvalidate", but with reledmac file it does not seem to work (it produce the odt file, but a clear file with any text). Any ideas?
Thank you in advance, 
Matteo

**Comment by maieul** [comment]
sorry, no idea. I think you should contact tex4html author.
As reledmac/reledpar create box and unbox them, that mayb explain the loosing.

In any case, I don't think you could keep feature of reledmac as linenumbering and other thing.

**Comment by matteofadini** [comment]
Thank you: I will write to tex4ht author.
Best,
Matteo
Il 22/Feb/2017 17:35, "Maïeul Rouquette" <notifications@github.com> ha
scritto:

**Comment by maieul** [comment]
I close this issue.
