### ISSUE TITLE
Apparatus note referring to multiple verses

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#627]
Maybe it is my fault, but it seems that is impossibile to compose an apparatus note referring to two or more verses.

Here is the sample (please, look at text between START and STOP):
```tex
% !TeX encoding = UTF-8
% !TeX TS-program = pdflatex

\documentclass[a4paper,12pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[polutonikogreek,italian]{babel}
\usepackage{teubner}
\usepackage{reledmac}
\renewcommand{\baselinestretch}{1.5}

\begin{document}
\setstanzaindents{3,2,2}
\setcounter{stanzaindentsrepetition}{2}
\beginnumbering
\stanza
Ἡσυχίης τόδ’ ἄθυρμ’ ἐμὸν ἠδέ τε λέσχη μακρὰ &
ἀνδρὸς ἀκηδιόωντος ἀήματι νυσταλόεντι, &
οὐ μὰν ἄμουσον πάμπαν ὅλον τὸ πόνημα πέπαικται, &
ἀλλ’ ἐπιμὶξ \edtext{τῆς}{\Afootnote{καὶ O}} παιδιῆς ἔσθ’ ἃ \edtext{κεν}{\Afootnote{καὶ Lampros}} ἐσπούδασται. &
Οὐδέ γε αὖ ἱερῇ πολιῇ καθάπαξ ἀπεοικὸς &
%%%% START
\edtext{οὔνομα}{\Afootnote{οὔκενα O}} καὶ Θεανὼ κικλήσκεται, οὔνομα \edtext{σεμνὸν &
καί κε}{\Afootnote{blablabla A}} σὺ τοῦτο γνώσεαι, ὧ φίλος, αὐτίκ’ ἐπελθών. &
%%%% STOP
χρυσῷ καὶ τόδ’ ἐρώμενον ἔρνος ἐκόσμε’ ἐκεῖνος &
ὄφρα κατασκιάοιτο χρυσοκόμῳ ὑπὸ δένδρῳ.\&
\endnumbering
\end{document}
```

Many many thanks for all yor job!
Domenico

**Comment by maieul** [comment]
yes, that is know. a verse, in reledmac is a pstart. And en edtext can't go throug multiple \pstart.

You must use crossref mechanism and \xxref to solve this issue.

**Comment by Doc73** [comment]
Ah, ok!
I have read § 11.3.1 of manual, but I can't understand how `xxref` works. For example, why has it two arguments? Where and how to use it?

**Comment by Doc73** [comment]
There are still issues.
I used this more simplified code:
```
% !TeX encoding = UTF-8
% !TeX TS-program = pdflatex

\documentclass[a4paper,12pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[polutonikogreek,italian]{babel}
\usepackage{teubner}
\usepackage{reledmac}
\renewcommand{\baselinestretch}{1.5}

\begin{document}
\setstanzaindents{3,2,2}
\setcounter{stanzaindentsrepetition}{2}
\beginnumbering
\stanza
%%%% START
οὔνομα καὶ Θεανὼ κικλήσκεται, οὔνομα \edlabel{σεμνὸν}σεμνὸν &
\edtext{καί κε\edlabel{κε}}{\xxref{σεμνὸν}{κε}\lemma{σεμνὸν ... κε}\Afootnote{blablabla A}} σὺ τοῦτο γνώσεαι, ὧ φίλος, αὐτίκ’ ἐπελθών. &
%%%% STOP
χρυσῷ καὶ τόδ’ ἐρώμενον ἔρνος ἐκόσμε’ ἐκεῖνος &
ὄφρα κατασκιάοιτο χρυσοκόμῳ ὑπὸ δένδρῳ.\&
\endnumbering
\end{document}
```
If you comment the line with `\edtext`, the very first compilation is fine, but the other don't work!
With the line, it is not working at all.

**Comment by maieul** [comment]
a label must contain only no-accentued latin character if you work with pdflatex.

With XeLaTeX, it is possible to have all unicode character (except those whoses have special meaning like \, ~ & etc)

**Comment by Doc73** [comment]
GOOD! VERY WELL!

In short, we can say that `reledmac` works better with `Xe/Lua-LaTeX`.

Only a suggestion: why not to add the above sample from [http://tex.stackexchange.com](http://tex.stackexchange.com) into the manual?

Thank you very much!

**Comment by maieul** [comment]
In general, XeLaTeX/LuaLaTeX are better than pdflatex when working with unicode character, as they don't use catcode, but read directly unicode character… 

I have added the sample, will be published on next release of reledmac

**Comment by Doc73** [comment]
Please, correct a typo:
`Here, and example of use:` --> ` Here, an example of use:`

**Comment by maieul** [comment]
done
