### ISSUE TITLE
msdata and lualatex

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#628]
For a recent project I'm using lualatex, but reledmac throws errors, as soon as I use a msdata. Try with:

```
\documentclass{article}

\usepackage{fontspec}
\usepackage{reledmac}

\begin{document}
\beginnumbering
\pstart
\msdata{G T U V}This is a test;\stopmsdata
\pend
\endnumbering
\end{document}
```

**Comment by maieul** [comment]
please try branch issue628

**Comment by baem2** [comment]
It's working fine with the given MWE, thank you!

But in my project it's not yet working, there seems to be something else broken. I'll give you a more complex MWE later today or tomorrow.

**Comment by baem2** [comment]
And here's now the more complex one (with hyperref):

```
\documentclass{article}

\usepackage{fontspec}

\usepackage{hyperref}

\usepackage{reledmac}

\begin{document}
\beginnumbering
\pstart
\msdata{G T U V}This is a test;\stopmsdata
\pend
\endnumbering
\end{document}
```

With LaTeX it is running, with lualatex it isn't.

**Comment by maieul** [comment]
sorry, I have just tried with lualatex and the last version of the branch, and it's running

**Comment by baem2** [comment]
Sorry, on line was missing in the MWE. Is this also running for you?
```
\documentclass{article}

\usepackage{fontspec}

\usepackage{hyperref}

\usepackage{reledmac}

\begin{document}
\beginnumbering
\pstart
\msdata{G T U V}This is a test;\stopmsdata
\msdata{G T}This is a test;\stopmsdata
\pend
\endnumbering
\end{document}
```

(It's neither working in LaTeX nor in lualatex for me.)

**Comment by maieul** [comment]
I will try to look on this problem

**Comment by maieul** [comment]
now the new version of the branch should be ok

**Comment by baem2** [comment]
I can confirm it's working fine now. Thank you very much -- once more! :)

**Comment by maieul** [comment]
your welcome, it was easy.

I will publish now on CTAN.
