### ISSUE TITLE
Reledpar aver option \Columns

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#630]
Cher ami,

je vais à remettre en page ma ''ancienne'' traduction de Tonio Kroeger, que j'ai ecrit il y a dix ans avec le package parallèle, en utilisant reledpar avec \pairs. Tout est en regle, mais je pense qu'il ya des problèmes
pour la numérotation des notes et vous demander où est mon erreur possible.

Comme vous pouvez le voir sur les fichiers (source et PDF), pour la colonne de gauche la note appellèe TEST-01 fait allusion exacte à la ligne  4 de la colonne de gauche; les notes TEST-02 et TEST.03 font elles meme  exacte  référence aux nombres des la lignes  15 et 16, mais, je vous demande, si la reference de celles-ci **ne devraint pas etre plutot** aux lignes **15R e 16R**.

Merci pour l'aide, `amicalement,` Enrico

ICI source et PDF fichier

``% !TeX encoding = UTF-8 Unicode
% !TEX TS-program = pdflatex
\documentclass[10pt,b5paper,twoside]{memoir}
\usepackage[T1]{fontenc}             
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[german,italian]{babel}
%-----------------------------------------------------------------
\usepackage[series={A,B,C},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}
\setgoalfraction{.85}
\AtBeginDocument{\Xmaxhnotes{0.5\textheight}}
\setlength{\Lcolwidth}{0.47\textwidth}
\setlength{\Rcolwidth}{0.47\textwidth} 
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A}) }
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\textbf{\theBtest\ - B}) }
\newcounter{Ctest}
\def\Ctest{\stepcounter{Ctest}(\textbf{\theCtest\ - C}) }
%-----------------------------------------------------------------
\newenvironment{DE}{\begin{otherlanguage*}{german}}{\end{otherlanguage*}}
\begin{document}

\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart%
\begin{DE}Die Schule war aus. \"{U}ber den gepflasterten Hof und heraus aus der Gatterpforte str\"{o}mten die Scharen der Befreiten, \edtext{teilten sich und enteilten}{\Afootnote{\Atest\ TEST-01.}} nach rechts und links. Gro\ss e Sch\"{u}ler  hielten mit W\"{u}rde ihre B\"{u}cherp\"{a}ckchen hoch gegen die linke Schulter gedr\"{u}ckt, indem sie mit dem rechten Arm wider den Wind dem Mittagessen entgegenruderten; kleines Volk setzte sich lustig in Trab, da\ss\ der Eisbrei umherspritzte und die Siebensachen der Wissenschaft in den Seehundsr\"{a}nzeln klapperten. Aber hie und da ri\ss\ alles mit frommen\edlabel{frommen} Augen die M\"{u}tzen herunter vor dem Wotanshut und dem Jupiterbart eines gemessen hinschreitenden Oberlehrers\ldots
\end{DE}
\pend
\endnumbering
\end{Leftside}
%FINE TESTO TEDESCO
	
%INIZIO TESTO ITALIANO
\begin{Rightside}
\beginnumbering
\pstart%
La scuola era terminata. Sul selciato e fuori dal cancello sciamavano le schiere dei finalmente liberi, separandosi e sfugggendosi a destra e sinistra. I più grandi sostenevano composti, ben in alto, il fascio di libri poggiato sulla spalla sinistra mentre col braccio destro avanzavano contro vento in direzione del pranzo; i più piccoli andavano invece giocosamente al trotto, schizzando  tutt'intorno  fango gelato mentre le briciole della scienza sballottolavano nelle loro cartelle di pelle di foca. Di tanto in tanto però, tutti, \edtext{abbassando lo sguardo}{\Bfootnote{\Btest: TEST-02.}}, tiravano giù il \edtext{berretto}{\Cfootnote{\Ctest\ TEST-03.}} dinanzi al cappello di Wotan od alla barba di Giove di qualche professore che incedeva  austero\ldots 
\pend
\endnumbering
\end{Rightside}
\end{pairs} 
\end{document}
[TonioKroeger.pdf](https://github.com/maieul/ledmac/files/853371/TonioKroeger.pdf)

**Comment by maieul** [comment]
Historically, there never was the line flag in critical notes. Howvever with \Xlineflag, you can enable it.

**Comment by maieul** [comment]
(documented in reledpar handbook)

**Comment by maieul** [comment]
oups, désolé, par reflexe j'ai écrit en anglais.

Le line flag n'est pas activé par défaut dans les notes pour des raisons historiques. Mais \Xlineflag (documenté dans le manuel de reledpar) permet de l'activer.

**Comment by heinrichffleck** [comment]
OK! Tout marche!!! Tres merci, Enrico
