### ISSUE TITLE
text width in pages environment

### ISSUE THREAD

**Issue by q-miller** [maieul/ledmac#632]
In the documentation, 6.2.1, "Within the pages environment the lengths \Lcolwidth and \Rcolwidth are the widths of the left  and right pages, respectively. By default, these are set to the normal textwidth for the document, but can be changed within the environment if necessary."  But the pages environment resets these on lines 914 & 915:

\setlength{\Lcolwidth}{\textwidth}%
\setlength{\Rcolwidth}{\textwidth}%

so the user's settings are ignored.  Removing these lines makes it behave as documented.

**Comment by maieul** [comment]
All work as explained in the handbook. You must change it _WITHIN_ the pages environment.

Cf this MWE
```
\documentclass{article}
\usepackage{reledmac}
\usepackage{reledpar}

\begin{document}
\begin{pages}
  \setlength{\Lcolwidth}{5cm}%
  \setlength{\Rcolwidth}{5cm}%
\begin{Leftside}
\beginnumbering
\pstart
The Historical Part of the Pentateuch According to Philo of Alexandria: Biography, Genealogy, and the Philosophical Meaning of the Patriarchal Lives
\pend
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\pstart
The Historical Part of the Pentateuch According to Philo of Alexandria: Biography, Genealogy, and the Philosophical Meaning of the Patriarchal Lives
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
```

**Comment by q-miller** [comment]
Dear Maïeul,

Thanks for the quick reply.

But your example shows the problem I am experiencing.  The left page is set to 5cm, but when generated by \Pages the \Lcolwidth has been reset to \textwidth.  The result is a right-justified column a long way from the line numbers.

The resetting of \Lcolwidth & \Rcolwidth is on lines 2595 & 2596; sorry I had given the wrong lines before.  This is in \Pages, outside of the \pages environment; that's why the problem arises.

Run your example, then run it again with the 

    \setlength{\Lcolwidth}{\textwidth}%
    \setlength{\Rcolwidth}{\textwidth}%

near the beginning of \Pages commented out, and you'll see what I mean.

Best wishes,
Quentin

**Comment by maieul** [comment]
At, you mean that the \Pages command, and not the the page environment restore that. 

Unfortunatly, we must redefine it, because in other case we have false overfull hboxes. I will commit something to fix your issue.

**Comment by q-miller** [comment]
On 4 Apr 2017, at 17:15, Maïeul Rouquette <notifications@github.com> wrote:
> 
> At, you mean that the \Pages command, and not the the page environment restore that.

Yes.  Sorry, I misreported it initially.  (I discovered the problem last night and this morning forgot the details ...)

> Unfortunatly, we must redefine it, because in other case we have false overfull hboxes. I will commit something to fix your issue.

Thanks!

- Quentin

**Comment by maieul** [comment]
please try branch issue632.

**Comment by maieul** [comment]
hi @q-miller some feedbacks?

**Comment by q-miller** [comment]
I'm not familiar with GitHub -- what am I meant to do?

- Quentin

**Comment by maieul** [comment]
all is explained here https://github.com/maieul/ledmac#debug-and-feature-requests

**Comment by maieul** [comment]
ok, I will publish now in CTAN.
Thanks for reports and tests.
