### ISSUE TITLE
Paragraph indentation after unnumberede sections

### ISSUE THREAD

**Issue by stenskjaer** [maieul/ledmac#634]
According to the documentation, you add unnumbered headings by adding them to the optional argument of `\pstart`:

``` latex
\pstart[\section{section}]
Pstart content.
\pend
```

When I do this, I loose the indent. Take this MWE:
``` latex
\documentclass{article}
\usepackage{reledmac}

\begin{document}
\beginnumbering
\pstart[\subsection*{test}]
Fidi interpretis Aristotelis Aegidii Romani heremitarum ordinis in libros De
anima expositio
\pend

\pstart
Fidi interpretis Aristotelis Aegidii Romani heremitarum ordinis in libros De
anima expositio
\pend

\endnumbering
\end{document}
```

This results in this pdf output:
<img width="1354" alt="skaermbillede 2017-04-11 kl 09 47 16" src="https://cloud.githubusercontent.com/assets/4047523/24898087/da5d5778-1e9b-11e7-81fe-a3c32f33528c.png">

When I remove the `[\section{test}]` or just don't use a section command in there, indentation works:
<img width="1129" alt="skaermbillede 2017-04-11 kl 09 48 13" src="https://cloud.githubusercontent.com/assets/4047523/24898116/fdca96bc-1e9b-11e7-8b16-0064ab37d03d.png">
and
<img width="1189" alt="skaermbillede 2017-04-11 kl 09 48 49" src="https://cloud.githubusercontent.com/assets/4047523/24898162/2f9f2400-1e9c-11e7-874b-b4e1e425d730.png">

**Comment by maieul** [comment]
That is an imitation of the default behavior of LaTeX.

See this MWE

```
\documentclass{article}
%\usepackage{reledmac}

\begin{document}
\subsection*{test}

ss

ss
\end{document}
```

The indentation is depending of language. With french setting, there is indentation. If you want to have it with a language which have normally no indent after section, add in your preamble

```
\makeatletter
\let\@afterindentfalse\@afterindenttrue
                        \@afterindenttrue
\makeatother
```

**Comment by stenskjaer** [comment]
No, actually, it is not. I realize that in many languages the *first* paragraph is not indented, and that is also what I want.
But the reason I included two paragraphs is because the second paragraph is also not indented.
Compare your MWE:
<img width="412" alt="skaermbillede 2017-04-11 kl 17 02 54" src="https://cloud.githubusercontent.com/assets/4047523/24915885/b3d8d5d6-1ed8-11e7-9ca0-9b44dd3dc5d2.png">
With the reledmac output:
<img width="535" alt="skaermbillede 2017-04-11 kl 17 03 35" src="https://cloud.githubusercontent.com/assets/4047523/24915911/cc8633c6-1ed8-11e7-88e5-10c734cf41b2.png">

Using the snippet you supply, *both* paragraphs get indented, but I only want any *except* the first indented.

**Comment by maieul** [comment]
Oh, if you would have been more explicit, I din't make the mistake.

**Comment by maieul** [comment]
I don't like this typographic rule (but I am french). But try the branch issue634.

**Comment by stenskjaer** [comment]
This creates results identical to standard Latex. And when I change the language to French, it looks they way you like it too ;)
Thank you.

**Comment by stenskjaer** [comment]
By the way, just at short question: Can you tell me when you expect the changes to be distributed in an update?

**Comment by maieul** [comment]
I hope this week-end. I try to publish not more that on by week.
I have also to integrate one other code to this version

**Comment by maieul** [comment]
I will try to do it friday, as the 15th april, TeXLive will be frozen.

**Comment by maieul** [comment]
I have just send the new version on CTAN.

**Comment by Doc73** [comment]
Dear Maieul,
the latest zip of GitHub is the same you sent to CTAN?
Unfortunately, since two or three days TL2016 is frozen and therefore we have compile and install manually the new versions.

Thank you very much,
Domenico

**Comment by maieul** [comment]
Yes, but I didn't have time before…

**Comment by Doc73** [comment]
Perfect!
Just downloaded, compiled and installed new versions!

Many thanks!
