### ISSUE TITLE
Support for \footnoteXmark and \footnoteXtext

### ISSUE THREAD

**Issue by sieversMartin** [maieul/ledmac#636]
In standard LaTeX, using `\footnotemark` and `footnotetext` is a established way to overcome situations, where a combined `\footnote` can not be used.

Such a situation is the usage of footnotes inside underlined passages with the `ulem` package (cf. my question https://tex.stackexchange.com/questions/361441/comfortable-solution-for-using-ulem-together-with-reledmac).

With the help of the documentation I defined two macros `\footnoteAmark` and `footnoteAtext`:
``` latex
\makeatletter
\newcommand{\footnoteAmark}{%
   \begingroup%
      \prepare@prenotesX{A}%
      \stepcounter{footnoteA}%
      \protected@csxdef{@thefnmarkA}{\csuse{thefootnoteA}}%
      \csuse{@footnotemarkA}%
   \endgroup%
}%
%
\newcommand{\footnoteAtext}[1]{%
   \begingroup%
      \csuse{vfootnoteA}{A}{\expandonce{#1}}\m@mmf@prepare%
   \endgroup%
}%
\makeatother
```

However it would be great, if both were defined by `reledmac` directly and for all defined series.

**Comment by maieul** [comment]
are all your test satifasctory?

**Comment by sieversMartin** [comment]
Well, for the described situation above my solution works:
``` latex
This is \uline{a test containing\mbox{\footnoteAmark}}\footnoteAtext{A  
simple footnote.}\uline{ a simple footnote.}
```

**Comment by maieul** [comment]
ok, i will add it this week-end

**Comment by maieul** [comment]
It look like, I think now, as the 
\footnoteXnomk and  \footnoteXmk mechanism of reledpar. COuld you look on the handbook and tell me if that it the same thing?
In this case I will move the code from reledpar to reledmac…

**Comment by sieversMartin** [comment]
Yes, this looks like the exact same principle.

**Comment by maieul** [comment]
ok. so
I will:
1. Move the code to reledmac
2. Uniformize name with LaTeX name
3. Add alias for older name
4. Documente it on reledmac handbook.

**Comment by sieversMartin** [comment]
Great, thank you.

**Comment by maieul** [comment]
Hum, that is not exactly the same thing. `\footnoteXnomk` must be called before `footnoteXmk` (as the first is on left side, the other is on right side). So I will implement your code.
