### ISSUE TITLE
Support for csquotes' reset mechanism for nested quotes

### ISSUE THREAD

**Issue by sieversMartin** [maieul/ledmac#637]
The package `csquotes` resets the nesting level for the `\footnote` macro, i.e. if inside a quotation a footnote is called, a quotation inside that footnote gets double quotes (outer quotes).

Maybe this could be done for `\footnoteX`, `\Xfootnote` and `\Xendnote` as well? Please see https://tex.stackexchange.com/questions/364561/resetting-nesting-level-of-csquotes-within-reledmac-macros for more information.

**Comment by maieul** [comment]
Please try branch issue637 (and also, please answer to my last questions on #636)

**Comment by sieversMartin** [comment]
Works fine now. Inside numbered parts (your second example in issue637.tex) it already works with the current version.

**Comment by maieul** [comment]
yes, I show it. 
please answer to my question on #636, and I will publish new release this week-end
