### ISSUE TITLE
Cross referecing apparatus note

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#639]
Bonsoir cher ami.

pour cet code

% !TeX encoding = UTF-8 Unicode
% !TEX TS-program = pdflatex
`\documentclass[10pt,b5paper,twoside]{memoir}
\usepackage[T1]{fontenc}             
\usepackage[utf8]{inputenc}
\usepackage[french,german,italian]{babel}
%=========================================
\usepackage[series={A,B,C},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}
\setgoalfraction{.85}
\AtBeginDocument{\Xmaxhnotes{0.5\textheight}}
\setlength{\Lcolwidth}{0.47\textwidth}
\setlength{\Rcolwidth}{0.47\textwidth} 
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A}) }
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\textbf{\theBtest\ - B}) }
\Xlineflag 
%=========================================
\newenvironment{DE}{\begin{otherlanguage*}{german}}{\end{otherlanguage*}}

\begin{document}
\setlength{\parindent}{0cm}
\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart
%INIZIO TESTO TEDESCO
\begin{DE}
Dies ist der Brief, den \edtext{Philipp Lord Chandos}{\Afootnote{\Atest\ Testo in nota } }, j\"{u}nger Sohn des Earl of Bath....
\end{DE}
\pend
\endnumbering
\end{Leftside}%FINE TESTO TEDESCO

%INIZIO TESTO ITALIANO
\begin{Rightside}
\beginnumbering
\pstart%
Questa è la lettera che Lord Philip Chandos, il figlio più giovane dell'Earl di Bath, scrisse a Francesco Bacone,.....
\pend
\endnumbering
\end{Rightside}%FINE TESTO ITALIANO
\end{pairs} 
\Columns	
\end{document}`

qui me donne pour la notation

**1–2 Philipp Lord Chandos ] (1 - A) Testo in nota**

comment est-il possible ''acquérir'' une écriture: **Voir nota 1 - A?**

Merci, saluti, Enrico M.

**Comment by maieul** [comment]
I don't understand. You need footnote which are both by line numbering and have indivdual number?

**Comment by heinrichffleck** [comment]
Puisque la  numérotation des notes est (1-A), (2-A), etc.,  je voudrais -si possible-  ecrire

\edtext{Lord Philip Chandos}{\Bfootnote{\Btest\ Voir la note : **et  _obtenir_ ici **(1-A)****  } }.

Est-il possible? Jusqu'ici j'ai ecrit: voir la notation pour la ligne \edlineref{label en reference}.

Merci, Enrico

**Comment by maieul** [comment]
oui, vous voulez avoir des notes numérotées en plus de référence par line.
Clairement pour moi ce n'est pas un besoin générique, et je ne l'incluerait pas dans reledmac (sauf si une autre personne fait la demande).

Je peux vous proposer un code qui pourrait correspondre à vos besoins, mais j'ai besoin de précisions:
- est-ce que le renvoi à la note est systématiquement APRÈS l'appel de note
- est-ce qu'il vous faut en plus préciser la page

**Comment by maieul** [comment]
ps: désolé d'avoir répondu en anglais… mais comme le titre était en anglais, j'ai oublié la langue du message après mes tests

**Comment by heinrichffleck** [comment]
Merci pour le code:  no, la reference a la note n'est sistematique et preciser la page n'est pas nécessaire.
PS: comm'on dit en français crossreference?

Saluti e tantissimi grazie per il vostro aiuto, Affettuosamente, Enrico

**Comment by maieul** [comment]
ma question était de savoir si la référence était après l'après de note, ou s'il pouvait arriver de faire une référence avant l'appel de note.

**Comment by maieul** [comment]
ps: "crossreference">référence croisée.

**Comment by heinrichffleck** [comment]
La référence croisée est -di norma-  sur le text en italienne. la \edlabel sur le text en allemande, grecque, latin,....   text on deux columns ou sur deux pages .

Je pense -de préférence- avant l'appel de note.

de nouveau merci, Enrico

**Comment by maieul** [comment]
pas compris le "di norma". Bon, c'est compliqué tout cela. Il faut simuler une crossref en fait. Je vais regarder cela, mais pas avant demain soir.

**Comment by heinrichffleck** [comment]
Excusez moi. ''di norma'' c'est a dire en général

Saluti Enrico

**Comment by maieul** [comment]
You should definie your test commands this following way:
````
\makeatletter
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A})\protected@edef\@currentlabel{\textbf{\theAtest\ - A}}}
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\textbf{\theBtest\ - B})\protected@edef\@currentlabel{\textbf{\theAtest\ - A}}}
\makeatother
``````

then, use normal \label and \ref commands. I close this topic, as I won't add any code to reledmac.

**Comment by heinrichffleck** [comment]
Tres merci pour le code. Vous  êtes toujours très  gentil,
Saluti, Enrico
 
=======================
www.heinrichfleck.net



      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Mercoledì 19 Aprile 2017 19:36
 Oggetto: Re: [maieul/ledmac] Cross referecing apparatus note (#639)
   
You should definie your test commands this following way:\makeatletter
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A})\protected@edef\@currentlabel{\textbf{\theAtest\ - A}}}
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\textbf{\theBtest\ - B})\protected@edef\@currentlabel{\textbf{\theAtest\ - A}}}
\makeatother
then, use normal \label and \ref commands. I close this topic, as I won't add any code to reledmac.—
