### ISSUE TITLE
[RELEDPAR] Wrong numeration of fam. footnotes

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#643]
Here is a sample:

```tex
% !TeX program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\documentclass[11pt,a4paper]{book}
\usepackage{libertine}

\usepackage{reledmac,reledpar}

\begin{document}
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
\eledsection{Section title}
\pend

\pstart
Text text text text
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
\eledsection{Section title\footnoteA{Footnote 1}}
\pend

\pstart
Text text text text\footnoteA{Footnote 2}
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages

\end{document}
```

In this MWE we have these issues:

1. Footnote 1 repeated two times, the first with number 2, the second with number 1
2. The footnote 2 printed as number 3
3. In text the footnotemarks are, respectively, 2 and 3, but there isn't the nr. 1
3. Strangely, in my real text I have footnotes 1 and 2 marked, respectively, as 2 and 3 both in text and in notes

I hope I was clear.

Thank you very much in advance,
Domenico

**Comment by Doc73** [comment]
P. S.
Probably the issue depends on the fact that I wrote a footnote inside `\eledsection`

**Comment by maieul** [comment]
please try the branch issue643

**Comment by Doc73** [comment]
It isn't working.
The footnotes are right, but the footnotemark in text are in inverse order.
![mark](https://cloud.githubusercontent.com/assets/1306260/25622552/0bf69bfe-2f55-11e7-850a-4098f112c891.png)

**Comment by maieul** [comment]
It's work after three run. As I told you many time, you should use latexmk to be sur to get the correct number of run.

**Comment by maieul** [comment]
![capture d ecran 2017-05-02 a 16 40 41](https://cloud.githubusercontent.com/assets/636640/25622833/198eafbc-2f56-11e7-93c7-6599511d998d.png)

**Comment by Doc73** [comment]
Ah, yes! :+1: 
Later I'll try in my book!

**Comment by Doc73** [comment]
Ah, I forgot to mention that  in my book I was forced to leave the system of footnotes, due to the incompatibility with `titlesec` (cf. #332 )

**Comment by maieul** [comment]
yes, but as you may see, I have a long long list of thing to do…

**Comment by Doc73** [comment]
Yes, I know. Take your time. Later, I'll try this branch in my book and I'll tell you the results

**Comment by maieul** [comment]
Ok. Tell me when you will have done this test.

**Comment by Doc73** [comment]
It seems working very well. Many thanks!

When you'll publish the new version, please inform me.

**Comment by maieul** [comment]
I wait for answer on #610 and I will integrate it in new release (I hope friday)
