### ISSUE TITLE
Numbering problems in nested disambiguation?

### ISSUE THREAD

**Issue by stenskjaer** [maieul/ledmac#646]
Take this nested disambiguation challenge:

``` latex
\documentclass{article}

\usepackage{reledmac}

\begin{document}
\beginnumbering

\pstart
\sameword{sw} and 
\edtext{\sameword[1]{sw} so 
  \edtext{
    \edtext{\sameword[1,3]{sw}}{\lemma{\sameword{sw}}\Bfootnote{lvl 3 note}} 
  another thing 
    \edtext{and \sameword[1]{more}}{\lemma{and more}\Bfootnote{lvl 3 note}}
  }{\lemma{sw another thing and more}\Bfootnote{lvl 2 note}}
}{\lemma{\sameword{sw} \ldots \sameword{more}}\Afootnote{lvl 1 note}} and a \sameword{sw}
after and one \sameword{more} \edtext{flat}{\lemma{flat}\Bfootnote{lvl 1 outside nested passage}}
entry.
\pend

\endnumbering
\end{document}
```
Resulting in this line:
<img width="707" alt="skaermbillede 2017-05-21 kl 09 44 28" src="https://cloud.githubusercontent.com/assets/4047523/26282086/1debb330-3e0a-11e7-8d69-ad62b3ba8d40.png">

And this apparatus:
<img width="365" alt="skaermbillede 2017-05-21 kl 09 45 05" src="https://cloud.githubusercontent.com/assets/4047523/26282091/2d8173ca-3e0a-11e7-8f77-4a27c143597c.png">

Notice the "sw ... more" note (A series). The "more" is the first instance in line, so I would expect it to give: "sw² ... more¹" instead of "sw² ... more³".

When I remove the nesting it turns out fine:

``` latex
\documentclass{article}

\usepackage{reledmac}

\begin{document}
\beginnumbering

\pstart
\sameword{sw} and \edtext{\sameword[1]{sw} so sw another thing and 
\sameword[1]{more}}{\lemma{\sameword{sw} \ldots{} \sameword{more}}\Afootnote{sw 
critical note}} and a \sameword{sw} after and one 
\sameword{more} \edtext{flat}{\lemma{flat}\Bfootnote{note here}} entry.
\pend

\endnumbering
\end{document}
```

Giving:
<img width="300" alt="skaermbillede 2017-05-21 kl 09 51 31" src="https://cloud.githubusercontent.com/assets/4047523/26282127/12796bfe-3e0b-11e7-9954-7e9956826370.png">

Have I annotated the nested disambiguation incorrectly or is it actually a bug?

P.S. I am working on a python script that can help mark disambiguation in tex-files. This example comes out of that work.

**Comment by maieul** [comment]
I am looking on. But be careful with the end of your second argument
````
\edtext{and \sameword[1]{more}}{\lemma{and more}\Bfootnote{lvl 3 note}}
  }
````

must be

````
\edtext{and \sameword[1]{more}}{\lemma{and more}\Bfootnote{lvl 3 note}}%
  }
````

(Spurious space)

**Comment by maieul** [comment]
1. You have same content if `\lemma` which is not marked as `sameword`. The handbook tell you clearly "In the content of \lemma, use \sameword with no optional argument."
2. You have problem with some of your edtext level numbering.
   - You wrote `\sameword[1,3]{sw}` but in reality, it is associated with level 2 and 3, and not with level 1.
   - The more is associated also with level 2 and 3. 

The point~1. does not matter, as it is only for showing sameword number in footnote. But the point~2 matters, as it is for getting the correct number.

As you made a mistake with `\sameword[1,3]{sw}`, reledmac didn't use the good lemma level. 

faf43e3 show you the good way.

**Comment by stenskjaer** [comment]
You were correct that it should have been `\sameword[2,3]{sw}`. That solves the numbering. Thank you.

A note though: I do not agree that you should use `\sameword` with any word that is contained in the lemma. It is only necessary to wrap in `sameword` when the lemma content will be ambiguous. That is not the case in those places where I have not used `\sameword` in the lemmas (with multi-word phrases that are not also present in the proximate context).

I find the resulting output from when you mark *all* words in lemma as your correction suggests puts needless disambiguation numbers.

Compare
<img width="370" alt="skaermbillede 2017-05-21 kl 15 08 27" src="https://cloud.githubusercontent.com/assets/4047523/26284259/5d6468c2-3e37-11e7-8f12-88cfb972d7a3.png">

with
<img width="354" alt="skaermbillede 2017-05-21 kl 15 09 14" src="https://cloud.githubusercontent.com/assets/4047523/26284264/73b03642-3e37-11e7-9cb9-f441a9b796e6.png">


Any thoughts on that? It does not result in any problems right (as long as you make sure that the multi word phrases are not present in proximity)?

**Comment by maieul** [comment]
See my sentence "The point 1. does not matter, as it is only for showing sameword number in footnote. But the point 2 matters, as it is for getting the correct number.". You are free to use or not to use \sameword in \lemma.

**Comment by maieul** [comment]
I have just thought to something about this \sameword in lemma.

The `\sameword`s in the first argument of an `\edtext` marked with optional argument corresponding to the edtext level must have the equivalent in the `\lemma` of this edtext.

- https://github.com/maieul/ledmac/blob/36e28a223e757924e8837bc12dde7afc04cefe22/issue646.tex is ok, because the `a \sameword[1]{sw}` has is equivalence with `a \sameword{sw}`. However, the `a` is enough to leave ambiguity.
- https://github.com/maieul/ledmac/blob/a2084008be5505808dd8a1283784694efa38156f/issue646.tex is wrong. I have suppressed the  `\sameword` for `sw` in `\lemma` but not in the first argument of `\edtext` -> `more` is not well numbered.
- https://github.com/maieul/ledmac/blob/992f305aa1fb014fc40e9ebf9cf605dc6ce5c3ff/issue646.tex is ok, because there is not `\sameword` of level 1 for `sw` in the first argument of `\edtext` and no `sameword` for `sw` in the corresponding `\lemma`.

**Comment by stenskjaer** [comment]
Yes, that makes sense. So the rule is that as soon as you give an `\sameword` in an `\edtext` a optional argument indicating the level, you must also mark the `\sameword` in the `\lemma`, right.

**Comment by maieul** [comment]
yes, that is
