### ISSUE TITLE
\edtext in \section, \subection,...

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#647]
Bonjour cher ami. 

Pour ce code
...............
\usepackage[series={A,B,C},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}
\setgoalfraction{.85}
\AtBeginDocument{\Xmaxhnotes{0.5\textheight}}
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A}) }
...............

est-il-possible écrire ''en quelque sorte'':

\phantomsection\section{\edtext{Commentariolus}{\Afootnote{\Atest\ La traduzione di Commentariolus......}} Nicolai Copernici }  ?

Le système répond

! Missing \endcsname inserted.

merci, Enrico M.

**Comment by maieul** [comment]
Pour pouvoir avoir des edtext dans \section, il faut utiliser des \eledsection. Merci de lire la documentation, où j'explique clairement la différence entre \section et \eledsection. 

§ 16.1

> The standard sectioning commands (\chapter, \section etc.) can be used inside num- bered text. In this case, you must call them as an optional argument of \pstart (5.2.3 p. 18):
> …
> **The line which contains them will not be numbered, and you cannot add critical notes inside.**

16.2 Sectioning commands with line numbering and critical notes

explain you use of eledsection.

**Comment by heinrichffleck** [comment]
Pardon! Pardon! Pardon! Je l'avais oublié

Saluti, Enrico 
=======================
www.heinrichfleck.net



      Da: Maïeul Rouquette <notifications@github.com>
 A: maieul/ledmac <ledmac@noreply.github.com> 
Cc: heinrichffleck <heinrich.fleck@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Domenica 21 Maggio 2017 15:32
 Oggetto: Re: [maieul/ledmac] \edtext in \section, \subection,... (#647)
   
Pour pouvoir avoir des edtext dans \section, il faut utiliser des \eledsection. Merci de lire la documentation, où j'explique clairement la différence entre \section et \eledsection. 

§ 16.1

> The standard sectioning commands (\chapter, \section etc.) can be used inside num- bered text. In this case, you must call them as an optional argument of \pstart (5.2.3 p. 18):
> …
> **The line which contains them will not be numbered, and you cannot add critical notes inside.**

16.2 Sectioning commands with line numbering and critical notes

explain you use of eledsection.

**Comment by maieul** [comment]
pas grave, cela arrive
