### ISSUE TITLE
équivalent de Xtxtbeforenotes pour les notes classiques

### ISSUE THREAD

**Issue by Enimie** [maieul/ledmac#652]
Coucou,

Crois-tu qu'il serait possible de faire un équivalent de Xtxtbeforenotes pour les familiar footnotes (un "txtbeforenotesX') ?
\bhookgroupX marche bien, mais fonctionne pour tout le bloc de notes

Enimie

**Comment by maieul** [comment]
ca devrait pas être trop compliqué, je te fais cela dans l'heure (normalement)
-----
Maïeul Rouquette
www.maieul.net
http://geekographie.maieul.net/

**Comment by maieul** [comment]
par contre 
> txtbeforenotesX 

ca marche pour l'ensemble du group. Ca fait juste des calculs supplémentaires pour éviter des pb de débordements par rapport à \bhookgroupX

Cf copie d'écran



est-ce vraiment cela dont tu as besoin?

(ds tout les cas j'implément txtbeforenotesX

**Comment by maieul** [comment]
la copie d'écran
![capture d ecran 2017-06-08 a 16 51 14](https://user-images.githubusercontent.com/636640/26935727-ff25dfe0-4c6c-11e7-8de8-fa6292c5d1c5.png)

**Comment by maieul** [comment]
peux tu essayer la branch issue652?

**Comment by Enimie** [comment]
Avec bhookgroupx, j'ai mon texte après chaque footnoterule, donc répété à chaque page,  ce qui n'est pas le cas avec Xtextbefore: c'est cela que je souhaite.
Je teste la branche

**Comment by maieul** [comment]
Ah non., \Xtxtbefore repete aussi à chaque page.

**Comment by Enimie** [comment]
Ah, ce n'est pas ce que j'avais compris, zut.
Non, moi j'ai juste besoin de mettre un texte avant la première note, c'est tout (sans appel de note). Je peux peut être me débrouiller avec footnotetext, mais il faut que j'arrive à supprimer le numéro de la note.

**Comment by maieul** [comment]
je vais voir si je peux mettre une option pour ca

**Comment by maieul** [comment]
Voilà

\txtbeforenotesonlyonceX
\Xtxtbeforenotesonlyonce

ont été ajouté. A utiliser en complément de \Xtxtbeforenotes et \txtbeforenotesX

**Comment by Enimie** [comment]
ca marche très bien, merci beaucoup!

**Comment by maieul** [comment]
y compris en //?
(j'ai pas testé tout, normalement cela devrait être ok mais au cas où)

**Comment by Enimie** [comment]
oui, moi je n'ai testé qu'en \\ et ca marche ss pb

**Comment by maieul** [comment]
parfait. Je publie alors.
