### ISSUE TITLE
Remove xunicode from examples

### ISSUE THREAD

**Issue by adunning** [maieul/ledmac#654]
Many of the examples do not compile using LuaTeX, giving the following error:

```
(/usr/local/texlive/2017/texmf-dist/tex/xelatex/xunicode/xunicode.sty

! LaTeX Error: *** this package currently works only with XeTeX ***
 You are not using XeTeX, so we are exiting cleanly!
 Continuing may lead to 'unavailable font metrics' errors!
```

This can be fixed by simply omitting the request for `xunicode` from the header. This will have no effect, as the package is already loaded by `fontspec` when using XeTeX.

**Comment by maieul** [comment]
Done. Will be released on CTAN with the next release.

**Comment by adunning** [comment]
That was quick. Merci!

**Comment by maieul** [comment]
De rien. Ce n'étais pas non plus très difficile :). Et maintenant que je sais que xunicode fait exactement, je sais que je n'en ai pas besoin.
