### ISSUE TITLE
Page marks in verse environment

### ISSUE THREAD

**Issue by paulbroyles** [maieul/ledmac#657]
I’m working on an edition of a verse text, and I would like to use the header to help cross-reference the current edition against an earlier one, by line number. (My particular use case is multiple documentary editions of individual manuscript witnesses; I’d like to use the header to facilitate quick reference to a field-standard critical edition.) When I try to set marks within verse lines, the layout breaks, introducing extra whitespace between lines.

This is related to #112 and https://groups.google.com/forum/#!topic/comp.text.tex/BR4Rr4-KI4M, but the suggestions there do not solve my problem because they refer to solutions for dealing with paragraphed text, and I couldn't find similar commands for doing something at the start of an individual verse line.

My plan was to use \markboth to get the proper line ranges into the header, though I’m flexible on the mechanism; I'm currently formatting my header with fancyhdr, but that could also change if needed. But what is important is that I must be able to specify the line number in the standard edition for each line of verse, and have the range present on the current page show up on the header. There’s no way to reliably infer the number in the standard edition from the actual line numbers in my edition, as the witness may skip or rearrange lines that are present in the standard edition.

Here’s a sample of what I need (filling full pages, of course):
```
\documentclass{book}
\usepackage{reledmac}
\usepackage{fancyhdr}
\newcommand{\mymarks}{\rightmark--\leftmark}
\AtEveryStopStanza{\vskip 8pt}
\begin{document}
\pagestyle{fancy}
\lhead{MS A}
\chead{Text}
\rhead{\mymarks}
\beginnumbering
\setstanzaindents{1,0}
\setcounter{stanzaindentsrepetition}{1}
\stanza{}\markboth{1}{Ed 1}Lorem ipsum dolor sit amet, consectetur adipiscing elit. &
\markboth{2}{Ed 2}Maecenas nec enim vitae sapien porttitor venenatis nec nec mauris. &
\markboth{4}{Ed 4}Mauris maximus lorem in facilisis efficitur. \&
\stanza{}\markboth{5}{Ed 5}Cras rhoncus sem vel diam pulvinar, eu pharetra lectus semper. &
\markboth{6}{Ed 6}Cras placerat erat et nulla rhoncus tristique. &
\markboth{7}{Ed 7}Maecenas sagittis metus nec lorem ultricies congue. \&
\endnumbering
\end{document}
```

Can you think of a way to allow that within reledmac or to make something similar work? Thanks.

**Comment by maieul** [comment]
You can use `doinsidelinehook` to avoid this problem.

Cf this MWE
```

\documentclass{book}
\usepackage{reledmac}
\usepackage{fancyhdr}
\newcommand{\mymarks}{\rightmark--\leftmark}
\AtEveryStopStanza{\vskip 8pt}
\begin{document}
\pagestyle{fancy}
\lhead{MS A}
\chead{Text}
\rhead{\mymarks}
\beginnumbering
\setstanzaindents{1,0}
\setcounter{stanzaindentsrepetition}{1}
\stanza{}\doinsidelinehook{\markboth{1}{Ed 1}}Lorem ipsum dolor sit amet, consectetur adipiscing elit. &
\doinsidelinehook{\markboth{2}{Ed 2}}Maecenas nec enim vitae sapien porttitor venenatis nec nec mauris. &
\doinsidelinehook{\markboth{4}{Ed 4}}Mauris maximus lorem in facilisis efficitur. \&
\stanza{}\doinsidelinehook{\markboth{5}{Ed 5}}Cras rhoncus sem vel diam pulvinar, eu pharetra lectus semper. &
\doinsidelinehook{\markboth{6}{Ed 6}}Cras placerat erat et nulla rhoncus tristique. &
\doinsidelinehook{\markboth{7}{Ed 7}}Maecenas sagittis metus nec lorem ultricies congue. \&
\endnumbering
\end{document}
```

Please check on a real case use, and close the thread if ok.

**Comment by paulbroyles** [comment]
Missed that in the manual--thanks very much.

**Comment by maieul** [comment]
Your'e welcome.

**Comment by maieul** [comment]
Ps: please. when you will have done your edition, add it on https://www.zotero.org/groups/209265/critical_editions_typeset_with_edmac_ledmac_and_eledmac/items
