### ISSUE TITLE
Surround footnote with code

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [maieul/ledmac#658]
I need to shrink text of each footnote, and usually, I am using my own tweaks, surrounding text code with a `scalebox`:

```
                \scalebox{0.92}[1.0]{%
                    \parbox[t][][t]{1.08\linewidth}{%
                        TEXT
                    }\ignorespaces%
                }%
```

How can I tweak the reledmac in order to achieve the desired effect? My footnotes go in paragraph mode.

**Comment by maieul** [comment]
Sorry, but I don’t understand what you need exactly. COuld you please provides a FULL MWE of you do usually, and not only the scalebox code?

**Comment by viktor-zhuromskyy** [comment]
What I want is to wrap the footnote text of `\footnoteA{footnote text}` in `\scalebox`

**Comment by maieul** [comment]
Le 2017-06-27 01:05, Viktor Zhuromskyy a écrit :
> What I want is to wrap the footnote text of \footnoteA{footnote text}
> in \scalebox
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the
> thread [2].
> 
> 	*
\wrapcontentX[⟨s⟩]{⟨cmd⟩} should do what you need

**Comment by viktor-zhuromskyy** [comment]
No, the `\wrapcontentX[⟨s⟩]{⟨cmd⟩}` won't work because I need to execute macro
`\scalebox{0.92}[1.0]{\parbox[t][][t]{1.08\linewidth}{FOOTNOTE TEXT}\ignorespaces}`
for every footnote, where `FOOTNOTE TEXT` is actual footnote text

**Comment by maieul** [comment]
that is the ain of \wrapcontentX to wrap for every footnotes...

**Comment by maieul** [comment]
Is it ok for for you?
