### ISSUE TITLE
Multiword sameword annotation containing macros

### ISSUE THREAD

**Issue by stenskjaer** [maieul/ledmac#661]
Take this example:

```tex
sed \emph{non} \edtext{sed non}{\lemma{non}\Bfootnote{sed SV}}
```

I would still argue that annotating multiword lemmas as a single entity (the second solution in the handbook, §6.3.4, cf. #649). If we do that here, it would look like this:

```tex
\sameword{sed \emph{non}} 
\edtext{\sameword[1]{sed non}}{\lemma{\sameword{sed non}}\Bfootnote{sed SV}}
```

But just as with the nested `sameword` commands, this gives us this error:
```log
ERROR: Use of \\sameword doesn't match its definition.

--- TeX said ---
\text@command #1->\def \reserved@a {#1}\ifx \reserved@a \@empty \let \check@...l.8 
\sameword{sed \emph{non}}
                              \edtext{sed non}{\lemma{non}\Bfootnote{sed SV}}
```

I suppose the natural solution (from the perspective of someone not a TeX programmer) would be to let `\sameword` contain other macros. Is that possible? Is it a bad idea?

**Comment by maieul** [comment]
Please always provide an MWE, it is faster for me. I will look at this.

The problem happens only with some macros, those which manipulate fonts especially, and so on. It is technically not possible to allow them in a generic way, but I will add the most current ones.

**Comment by stenskjaer** [comment]
Sorry about the missing MWE. 

But sounds good.

**Comment by maieul** [comment]
done on 77df33a7
please try branch issue661, and let me know if you think about other problematic cases

**Comment by stenskjaer** [comment]
It works. I have added a PR for some typos in the documentation.

**Comment by maieul** [comment]
ok, thanks for the correction. However, I rewritten the history (that is Bad, I know, but for now, it is better) to get a better clean.
 I will publish the new version after feedback on #659

**Comment by stenskjaer** [comment]
Sounds good!
