### ISSUE TITLE
Compare samewords as lower case strings (maybe optional)

### ISSUE THREAD

**Issue by stenskjaer** [maieul/ledmac#664]
Take this MWE:

```latex
\documentclass{article}

\usepackage{reledmac}

\begin{document}

\beginnumbering
\pstart
Sed \edtext{\sameword[1]{per}}{\Afootnote{secundum O}} privationem. \sameword{Per} privationem autem ...
\pend
\endnumbering

\end{document}
```

This document will not disambiguate the two instances of "per". [edited]

I think it may be an advantage to compare sameword annotated strings case insensitively so that for example these two "per" will be disambiguated. 

It is a very difficult dilemma though, as it may also, to some, depending on tradition and school, introduce rather than remove an ambiguity. I have discussed this with myself here: https://github.com/stenskjaer/samewords/issues/3 

Any thoughts? In an edition I have been asked to disambiguated in this very situation, so I think it may be necessary to add it (maybe as an configurable option).

**Comment by maieul** [comment]
hum…I have to look for the possibility to change case in auxiliary files

**Comment by maieul** [comment]
I get an answer. I will try to integrate it on code after holidays

**Comment by maieul** [comment]
Please try branch "issue664".  The option is "swcaseinsensitive" (see the file issue664.tex)

**Comment by stenskjaer** [comment]
I works. Beautiful!

**Comment by maieul** [comment]
You'r welcome.
Published on CTAN.
