### ISSUE TITLE
ledgroup not working with paragraph notes

### ISSUE THREAD

**Issue by Conicsections** [maieul/ledmac#667]
(Follow up to our discussion on tex.stackexchange.com.)

I would like to use ledgroup with paragraph notes, but when I do the notes are sent to bottom of the page and garbled. 

In the following minimal example, if I comment out the \Xarrangement{paragraph} everything looks good, but the notes are not in paragraph form. However, when I leave it in, the notes do not behave properly. 

```
\documentclass[11pt,a4paper]{article}

\usepackage[parapparatus]{reledmac}
\lineation{pstart} 
\linenummargin{outer}

\begin{document}

\begin{ledgroup}
\beginnumbering
\Xarrangement{paragraph}%twocol, paragraph
\Xafternumber{1em}
\firstlinenum{2}\linenumincrement{2}
\pstart 
\noindent
 blah blah blah blah blurb blurb
\edtext{blurb blurb}{\Afootnote{blah blah \emph{codd.}}}
blah blah blah blah blah
\edtext{blurb}{\Afootnote{blah \textbf{A}}}
blah blah 
\edtext{blurb}{\Afootnote{blah \textbf{A}}}
blah blah blah blah
\edtext{blurb blurb}{\Afootnote{ blah \textbf{B}}}  blah blah blah blah blah.
\pend
\endnumbering
\end{ledgroup}

\end{document}
```

**Comment by maieul** [comment]
Arf, that is a bug added 5 years ago.

I am looking on

**Comment by maieul** [comment]
aee236bb8ff601cec9f2f9d9f05d649a282ca33a is the origin of the problem

**Comment by maieul** [comment]
8cee3d738d8c864cf4160938ef8d5ab25a547f0a
is also problematic

**Comment by maieul** [comment]
Ok, I see your problem.

You didn’t call the setting in the good place.

You must call them before the ledgroup, and, preferably, in the preamble.

Cf 4d1a9b7c

(I won’t add code to avoid this limit, as it could create more problem)
