### ISSUE TITLE
Unexpected line number references with \edlabelS and \edlabelE

### ISSUE THREAD

**Issue by stenskjaer** [maieul/ledmac#669]
MWE:

```tex
\documentclass{article}

\usepackage{reledmac}
\usepackage{lipsum}

\begin{document}
\SEref{ref-1}

\beginnumbering
\pstart
\lipsum[1]
\pend

\pstart
\edlabelS{ref-1}%
\lipsum[5]
\edlabelE{ref-1}%
\pend
\endnumbering

\end{document}
```

This document gives me the following line reference: 123–201. It should be 13–21. Line numbers are often (but not under all conditions, which I am unable to determine), injects a spurious number between the first and last number in the line reference.
The references in the `aux` file look like this:
```
\l@dmake@labels 1|123|0|13|2|{ref-1:start}
\l@dmake@labels 1|201|0|21|2|{ref-1:end}
```

**Comment by maieul** [comment]
Please try issue669 branch. The problem only happen at the begining of a \pstart.

Not that \lipsum add a end of paragraph after the command

(in general, please don’t use \lipsum for your MWE, because it is not optimal).

**Comment by stenskjaer** [comment]
Yes, this solves it. Thanks.

**Comment by maieul** [comment]
I close this issue and merge the branch in the release branch.
