### ISSUE TITLE
ledouternute et numberline: superposition

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#689]
Bon soir Maiuel,

quelquefois \ledouternote{ma note} se superpose à le number de line de la page de gauche ou de droite.

Est-il possible de eviter ça?

Saluti, Enrico

**Comment by maieul** [comment]
tu peux 
1) soit régler la distance entre la ligne et la note / le numéro de ligne ( 
\linenumsep, \ledlsnotesep and \ledrsnotesep)

2) soit utiliser la commande \hidenumbering à côté de la ledouternote

**Comment by heinrichffleck** [comment]
Merci, saluti, Enrico
