### ISSUE TITLE
\beginnumbering doesn't work in the right column as expected after \endnumbering

### ISSUE THREAD

**Issue by ndlecic** [maieul/ledmac#690]
A propos this discussion:
https://github.com/maieul/ledmac/issues/665#issuecomment-322487038
Here is a MWE for the case 3. Please take a look:
```latex
\documentclass[
	twoside,
	paper=B5,
]{scrartcl}

\usepackage{calc}
\usepackage{kantlipsum}
\usepackage[english]{babel}

\usepackage[
	noend,
	nofamiliar,
	noeledsec,
	auxdir=aux,
]{reledmac}

\usepackage[
	widthliketwocolumns,
	continuousnumberingwithcolumns,
]{reledpar}

\setlength{\Lcolwidth}{.5\textwidth-.75em}
\setlength{\Rcolwidth}{.5\textwidth-.75em}
\columnsposition{c}
\setlength{\beforecolumnseparator}{.75em}
\setlength{\aftercolumnseparator}{.75em}
\AtBeginPairs{\sloppy}

\begin{document}
\section{}
\beginnumbering
\pstart
	\kant*[2]
\pend
\pausenumbering

\begin{pairs}
	\begin{Leftside}
		\resumenumbering
		\pstart
			\kant*[3]
		\pend
		\pausenumbering
	\end{Leftside}
	\begin{Rightside}
		\beginnumbering
		\pstart
			\kant*[4]
		\pend
		\pausenumbering
	\end{Rightside}
\end{pairs}
\Columns

\resumenumbering
\pstart
	\kant*[6]
\pend
\endnumbering

\section{}

\beginnumbering
\pstart
	\kant*[7]
\pend
\endnumbering

\section{}

\begin{pairs}
   \begin{Leftside}
		\beginnumbering
		\pstart
			\kant*[8]
		\pend
		\pausenumbering
	\end{Leftside}
	\begin{Rightside}
		\beginnumbering % <-- doesn't work; \resumenumbering works
		\pstart
			\kant*[9]
		\pend
		\pausenumbering
	\end{Rightside}
\end{pairs}
\Columns

\resumenumbering
\pstart
	\kant*[10]
\pend
\endnumbering

\end{document}
```
Before the last section, there is `\endnumbering`. Therefore, both columns in the last section should start with `\beginnumbering`. However, it doesn't work: cf. the line with the comment "doesn't work".

**Comment by maieul** [comment]
That is perfectly normal. 

YOu have started a right \beginumbering on your first pairs, right beginnumbering which have not closed.

**Comment by ndlecic** [comment]
Hmmmm... Should I have put \endnumbering at the end of the right column of the first pairs? In this case, \beginnumbering in the second pairs will work.

**Comment by maieul** [comment]
yes, that is.

**Comment by ndlecic** [comment]
Ok, thanks, I understand. So I'm closing this issue.

**Comment by maieul** [comment]
could you produce a series of MWE for this issue as you said you would do?

**Comment by ndlecic** [comment]
> could you produce a series of MWE for this issue as you said you would do?

Sure! Now I have all answers I need, and I'm doing on it right now.

**Comment by maieul** [comment]
to solve #688, I think I need to change the syntaxis. A \beginnumbering outside of a column will be available also for right column (I need to do more test before confirming this).

**Comment by ndlecic** [comment]
> A \beginnumbering outside of a column will be available also for right column

Should I wait with writing MWE for the documentation before you sort this issue?

**Comment by maieul** [comment]
I think yes.
