### ISSUE TITLE
Center astanza environment

### ISSUE THREAD

**Issue by Naturjoghurt** [maieul/ledmac#693]
Dear Maïeul,

When trying to center all stanzas generated by the astanza environment the indentation provided by astanza breaks. The desired output should be the same indentation provided by astanza, but every stanza itself is centered on the page regarding on its line length.

I posted this as a [questin on stackoverflow](https://tex.stackexchange.com/questions/388580/center-astanza-environment-using-reledmac-reledpar-without-breaking-the-indent/388714?noredirect=1#comment964502_388714) and you asked me to create an issue for this.

Here is my MWE:
```latex
\documentclass[12pt,a4paper,twoside]{scrbook}
\usepackage[]{reledmac}
\usepackage[]{reledpar}

% Set stanza indentation
\setstanzaindents{0,0,1,0,1,0,1,0,1}

\begin{document}  
\large
\centering
\begin{pages}
    \begin{Leftside}
        \beginnumbering
            \begin{astanza}[This is the original title]
                verse verse verse 1!&  
                verse verse verse 2!&   
                verse verse verse 3! This is a long one!&
                verse verse verse 4!\&  
            \end{astanza}
        \endnumbering
    \end{Leftside}
    \begin{Rightside}
        \beginnumbering
            \begin{astanza}[This is the translated title]
                This is the long translation of the original poem. The translation is not done verse by verse synced to the original text.\&
            \end{astanza}
        \endnumbering
    \end{Rightside}
\end{pages}
\Pages
\end{document}
```

Thank you in advance. Any help appreciated!

**Comment by maieul** [comment]
I have thought, and I go to the conclusion that strictly meaning, you question does not make sense.

« every stanza itself is centered on the page » means that the middle on the line is one the middle of the page (horizontally) -> so the begining of a verse (without indentation) can’t be on a fix point
" indentation provided by astanza breaks. » start, by definition, from a fix a point.

In other time:
- with stanzaindent, the referring point is the begining of the line of verse
- with centering setting, the referring point is the middle of the line of verse

You can't have a real centering and a stanza indentation in the same time. 

What you can do, is to have a enough long indentation to make illusion of centering

7aced8f2 will show you an example of use.

Also notes:
1. The use the stanzaindentsrepetition counter
2. For right side, the use of \pstart, as we are in a prose mode

**Comment by Naturjoghurt** [comment]
Dear Maïeul,
I tested the changes to the MWE you posted and it really solves my problem. Thank you for having a look and sorry for opening up an issue as this was just caused by my faulty usage.

**Comment by maieul** [comment]
Not a problem. I will close the issue. Please validate the new answer added on SE.
