### ISSUE TITLE
conflict between reledpar and titletoc package?

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#697]
The MWE produces a paragraphed table of contents by titletoc. Behind the pagenumber of sections c) and e) which contain a reledpar columns environment a spurious space is inserted. Perhaps you see the cause of the problem at first sight. But note, it is not an urgent problem. Thank you very much!

\documentclass{book}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}
\usepackage{reledmac,reledpar}

\renewcommand{\thesection}{\alph{section})\hspace{5pt}}

\usepackage{titletoc}
\newcommand\xquad{\hspace{1em plus.4em minus.4em}}

\titlecontents{chapter}
[3pc]
{\addvspace{0.3em}\large}
{\contentslabel[\thecontentslabel]{1pc}}
{}
{\titlerule*[8pt]{.}\thecontentspage}
[]

\titlecontents*{section}
[2pc]
{\addvspace{0.2em}\small}
{\thecontentslabel\nolinebreak}
{}
{~\thecontentspage}
[]
[.\xquad---\xquad]
[.]

%%%partial ToC
\titlecontents*{p-section}
[0pc]
{\small}
{\thecontentslabel\nolinebreak}
{}
{~\thecontentspage}
[]
[.\xquad---\xquad]
[.]

\begin{document}

\tableofcontents

\chapter{Capitulum primum}

\startcontents[section]
\printcontents[section]{p-}{1}{}

\section{Sectio prima}
Some text

\section{Sectio secunda}
Some text

\section{Sectio tertia}
\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
columna sinistra
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
columna dextra
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\section{Sectio quarta}
Some text

\section{Sectio quinta}
\begin{pairs}

\begin{Leftside}
\beginnumbering
\pstart
columna sinistra
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
columna dextra
\pend
\endnumbering
\end{Rightside}

\end{pairs}
\Columns

\stopcontents[section]
\contentsfinish

\end{document}

**Comment by maieul** [comment]
reledpar insert switch language command at each line of a two columns text.

That is this switch command which make problem. The problem is, I think, in titletoc code.

You can write to the titletoc author with the following MWE : https://github.com/maieul/ledmac/blob/48d560392efbee9a39af71ed0f6e101cfeaa6455/issue697.tex

**Comment by maieul** [comment]
(as you can see in this MWE, the problem happens without reledmac/reledpar)

**Comment by sonator** [comment]
THANK YOU very much for identifying the problem! I try to contact Javier Bezos.
