### ISSUE TITLE
Xtxtbeforenotes and \endnumbering \beginnumbering

### ISSUE THREAD

**Issue by ppasedach** [maieul/ledmac#698]
Considering the following example: 

```
\documentclass{article}
\usepackage{reledmac}
\Xarrangement{paragraph}
\Xtxtbeforenotes{Testing: }
\begin{document}
\beginnumbering
\pstart
\edtext{Some}{\Afootnote{A first note.}} \edtext{text}{\Afootnote{A second note.}}.
\pend
\endnumbering

\beginnumbering
\pstart
\edtext{Some}{\Afootnote{A third note.}} \edtext{text}{\Afootnote{A fourth note.}}.
\pend
\endnumbering
\end{document}

```
I get the following apparatus:
![xtxtbeforenotes](https://user-images.githubusercontent.com/11517856/30773693-e6ba6ed2-a075-11e7-9455-8f0b716150e6.png)
You see a second "Testing: ", which I suppose got inserted because of `\endnumbering` and `\beginnumbering`. My real file is more complex, I am editing three texts, after each verse of a piece of poetry I add two commentaries on it, each of them with their own numbering. Is it possible to get rid of the second "Testing: "?

**Comment by maieul** [comment]
It could be possible to solve this issue, but I am afraid it could imply board effect. Many test should be made, and for now I have no time.

Anyway, you can use the `\resumenumbering…` way to turn around.


```
\documentclass{article}
\usepackage{reledmac}
\Xarrangement{paragraph}
\Xtxtbeforenotes{Testing: }
\firstlinenum{1}
\linenumincrement{1}
\begin{document}
\beginnumbering
\pstart
\edtext{Some}{\Afootnote{A first note.}} \edtext{text}{\Afootnote{A second note.}}.
\pend
\pausenumbering

\resumenumbering\setlinenum{0}
\pstart
\edtext{Some}{\Afootnote{A third note.}} \edtext{text}{\Afootnote{A fourth note.}}.
\pend
\endnumbering
\end{document}
```

**Comment by ppasedach** [comment]
That seems to work as a workaround, thanks. In fact it even seems I don't really need `\pausenumbering` and `resumenumbering`, `\setlinenum{0}` appears to be enough, but I still need to test that on my real files.

**Comment by maieul** [comment]
you need `\pausenumbering` to insert your commentary between poetry (as you used previously `\endnumbering`

**Comment by maieul** [comment]
I won't solve this issue.
