### ISSUE TITLE
Typo in eledmac 1.24.11

### ISSUE THREAD

**Issue by rrthomas** [maieul/ledmac#700]
I know that eledmac is now superseded, but since it's still available, it would be nice to fix this trivial but at the same time serious bug: in line 910 of `eledmac.sty`, `\n@l` should be `\@nl`.

**Comment by maieul** [comment]
it is only because it is a little bug that I will publish a correction on an unsupported version.

**Comment by rrthomas** [comment]
Thanks! I think it's a good thing to have in this case, given that it is the last version of eledmac, and hence available on CTAN.

**Comment by maieul** [comment]
yes, but the idea is also to incitate people to migrate to reledmac …

**Comment by rrthomas** [comment]
I agree, but on my current project it took me a couple of days' work just to migrate to the latest eledmac, from version 1.11, one version at a time (because I found I kept getting different errors with different versions, so going straight to the latest version was too hard). I spent another day migrating to reledmac, but yesterday I discovered that a) my document always gives an error on the first run, which makes me nervous; and b) I was able to backport the changes I had made to make it work with reledmac, to eledmac. I now have a better-structured document, and the changes to make it work with reledmac are trivial (renaming commands), and since it still doesn't work properly with reledmac, I have little reason to spend yet more time upgrading. reledmac is a rapidly-moving target; eledmac is not, so for a document which is more-or-less fixed (it's a completed book), I'd rather not worry about whether I can compile with a future version of reledmac. And, after all that, I'd rather spend my time actually making something (in this case, a high-quality PDF version of a previously-printed book), rather than the document equivalent of wrestling with library upgrades, especially as I don't see any new features or bug-fixes that I need.

The only reason I really want to upgrade is so that I can get support if I need it; but so far, upgrading has been a miserable experience, and I've been able to diagnose only that one trivial bug.

**Comment by rrthomas** [comment]
I do not mean the above as a criticism, by the way. I appreciate that reledmac is complex, I am making complex use of it (in one case, even redefining the internal `\printlines`), and also I am grateful for the detailed upgrade notes that you write. My situation is, I hope, quite rare, and most users would be better off upgrading, and find it easy to do.

**Comment by maieul** [comment]
I can understand. I would prefer to get stable version of the produce, but as you can see, there is many, many question which make I must produce new version of reledmac/reledpar. I try to avoir breaking in compatibility, but some time I must, and sometime I have not all the tool to check.

In any case, when you will have time, I would be curious to get a MWE of you problem when migrating to reledmac.

**Comment by rrthomas** [comment]
Je crois que, quand j'aurai un EFM, j'aurai aussi la solution, le problème étant comme toujours le «M» !

**Comment by maieul** [comment]
très certainement ;-) (mais il se peut qu’il y ait des bugs quand même)

**Comment by rrthomas** [comment]
By the way, the original problem I had with migrating to reledmac did indeed disappear when I tried version 2.24.1 instead of my system version (2.8.2). The remaining problem appears to be solely #704, for which I have a workaround.
