### ISSUE TITLE
Tiny typo in manual

### ISSUE THREAD

**Issue by rrthomas** [maieul/ledmac#703]
The migration section for 2.24 is entitled "Migration ro reledmac…".

**Comment by maieul** [comment]
sorry, I don’t see any section 2.24 in the migration manuel…

**Comment by rrthomas** [comment]
The migration section for version 2.24. The section "Migration to 2.24". Sorry I wasn't clear!

**Comment by maieul** [comment]
Sorry, but for me it is ok.

![capture d ecran 2017-10-03 a 10 56 25](https://user-images.githubusercontent.com/636640/31117309-a95c982e-a829-11e7-990f-20b4c3b81d5a.png)

**Comment by rrthomas** [comment]
Your screen capture shows exactly what I said: "Migration ro", not "Migration to".

**Comment by maieul** [comment]
ho, I thought the problem was with reledmac name. §
