### ISSUE TITLE
Footnotes go off the bottom of the page

### ISSUE THREAD

**Issue by rrthomas** [maieul/ledmac#704]
I apologise, the MWE in this case is not very minimal:

    \documentclass{book}
    \usepackage[a5paper]{geometry}
    \usepackage[LGR,T1]{fontenc}
    \usepackage[main=british,greek]{babel}
    \usepackage[utf8x]{inputenx}
    \usepackage{lettrine}
    \usepackage[noend]{reledmac} % for line numbering and multiple footnote series
    \usepackage{teubner}
    
    \begin{document}
    \chapter{THE YOUTH HOSTEL}
    \beginnumbering
    \pstart
    {%
      \edtext{}{\lemma{THE YOUTH HOSTEL.}\Afootnote[nonum]{%
        Perhaps the most striking incongruity of this work is its subject. One wonders what it was about staying in a rather noisome auberge during an unremarkable tour of a country which could hardly be describ’d as exotic that inspir’d such labours. It is true that the choir had a long history of tours to the Netherlands, but it was curiously irregular for them to be billeted in a youth hostel.}}}
      or \edtext{One day in Thy courts}{\lemma{foo}\Bfootnote{%
        Ps. 84:10. As we are among musicians of the establish’d Church, we use the translation of Scripture commanded by King~James, except for the Psalter, which is the Rt.~Rev.~Coverdale’s. The verse reads For one day in Thy courts is better than a thousand, and has the opposite meaning to that imply’d here.}}%
      .%
      \edtext{To those who so bravely bore that which is describ’d herein.}{\lemma{bar}\Afootnote{%
    The choir and staff on the tour were as follows\/: the Organist, Mr.~Christopher Robinson and his wife, Shirley; the tutor to the Choristers, Mr.~David Barry; the Dean, the~Rev.~Dr.~Andrew Macintosh, whose wife, Mary, assisted the Matron, Mrs.~Caroline Cooper; the coach was driven by Mr.~Rex Fishpool; the trebles were Master~Mark Williams (Head Chorister), Master~Thomas Reindorp, Master~Iestyn Davies, Master~Christopher de la Hoyde, Master~Alistair Zobel, Master~Felix Gummer, Master~Frederick Bols, Master~Thomas Dobney, Master~Jonathan Wills, Master~Alexander Choat, Master~Charles Hindley, Master~Alexander Smallwood, Master~Andrew Westwood, Master~Dominic Mander, Master~Jonathan Campbell and Master~William Brooks; the altos were Mr.~Aric Prentice, Mr.~James Burton, Mr.~Declan Costello and Mr.~Stephen Willis; the tenors were Mr.~Jacob White, Mr.~Toby Watkin, Mr.~Keith Webster, Mr.~Timothy Copsey and Mr.~David Thomson (the Academic Director of the College School, also present in a pastoral capacity); the basses were Mr.~William Clements, Mr.~Leigh-Phillips Melrose, Mr.~Simon Robson Brown, Mr.~Charles Armstrong and Mr.~Reuben Thomas; the Senior Organ Scholar was Mr.~Philip Scriven, and the Junior Organ Scholar was Mr.~James Martin.}}%
    OFT have we heard the joys of Travel told, \\
    Of wond’rous sights, reward of trav’llers bold; \\
    Of horrors too, and situations dire, \\
    Which make us glad to stay at our hearth-fire; \\
    Yet none so grim as that of which I speak, \\
    And cry to thee, o Muse! t’ inspire my \edtext{%
    meek \\
    And feeble}{\lemma{foo}\Bfootnote{%
    Not merely an echo of the first Elizabeth\,’s famous declaration, but a common misquotation of it.}}
    pen with fire from Helius\/’ height, \\
    Enlight’ning my dull wits with thine so bright. \\
    \pend
    \end{document}

When I process this document, the footnote rule for series B is right at the bottom of the page, and the B series footnotes do not appear.

If I remove the line

    \usepackage{lettrine}

then the problem goes away. (Note that in this document I do not use any commands from the lettrine package.)

However, the problem is also fixed by removing the line

    \usepackage[utf8x]{inputenx}

or indeed replacing it by

    \usepackage[utf8]{inputenc}

Also, if I remove `greek` from the list of languages passed to babel, and the line `\usepackage{teubner}` then the problem is fixed.

Finally, if I remove the `noend` option to reledmac, the problem is fixed.

I have tested using version 2.24.1 and the current git version.

**Comment by rrthomas** [comment]
Indeed, if in my original document I remove the `noend` option to the package, my page breaks are magically fixed. So this is a good workaround.

**Comment by maieul** [comment]
so there is an incompatibility with noend, that we should not have

**Comment by rrthomas** [comment]
Oh dear. It turns out that another version of the document has the same problem without `noend`. I will do more investigation.

**Comment by maieul** [comment]
Sorry, but with your first MWE, I get this pdf which look like good. 

[toto.pdf](https://github.com/maieul/ledmac/files/1399797/toto.pdf)

I see both the footnotes rules and the footnotes content.

**Comment by maieul** [comment]
(any way, for poetry, you should use stanza feature of reledmac)

**Comment by rrthomas** [comment]
But the poetry I'm setting doesn't have stanzas, unless perhaps each stanza is two lines. (I did try using them, but it makes things difficult.)

**Comment by rrthomas** [comment]
I confirm that if I copy and paste my MWE from the bug report back into a document and process it, I get the reported problem.

**Comment by maieul** [comment]
Could you upload your pdf result?

**Comment by maieul** [comment]
(Even if you have not real stanza, you can use stanza feature, but that is an other topic…)

**Comment by rrthomas** [comment]
[bar.pdf](https://github.com/maieul/ledmac/files/1399827/bar.pdf)

**Comment by maieul** [comment]
Please also send me the result of a `\listfiles`. Here is what I have. 

````
*File List*
    book.cls    2014/09/29 v1.4h Standard LaTeX document class
    bk10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
geometry.sty    2010/09/12 v5.6 Page Geometry
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
   ifpdf.sty    2017/03/15 v3.2 Provides the ifpdf switch
  ifvtex.sty    2016/05/16 v1.6 Detect VTeX and its facilities (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
 fontenc.sty
  lgrenc.def    2015/12/07 v0.13.1 LGR Greek font encoding definitions
greek-fontenc.def    2015/08/04 v0.13 Common Greek font encoding definitions
   t1enc.def    2017/04/05 v2.0i Standard LaTeX file
   babel.sty    2017/10/04 3.14 The Babel package
   greek.ldf    2016/09/07 v1.9g Greek support for the babel system
 british.ldf    2017/06/06 v3.3r English support from the babel system
inputenx.sty    2016/05/16 v1.11 Enhanced input encoding handling (HO)
ix-alias.def    2016/05/16 v1.11 Alias list (inputenx)
inputenc.sty    2015/03/17 v1.2c Input encoding file
   utf8x.def    2004/10/17 UCS: Input encoding UTF-8
     ucs.sty    2013/05/11 v2.2 UCS: Unicode input support
uni-global.def    2013/05/13 UCS: Unicode global data
lettrine.sty    2015/08/31 v1.9 (Daniel Flipo)
lettrine.cfg
reledmac.sty    2017/08/31 v2.24.1 typesetting critical editions
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
   xargs.sty    2008/03/22 v1.1  extended macro definitions  (mpg)
  xparse.sty    2017/09/18 L3 Experimental document command parser
   expl3.sty    2017/09/18 L3 programming layer (loader) 
expl3-code.tex    2017/09/18 L3 programming layer 
l3pdfmode.def    2017/03/18 v L3 Experimental driver: PDF mode
etoolbox.sty    2017/01/02 v2.4 e-TeX tools for LaTeX (JAW)
  suffix.sty    2006/07/15 1.5a Variant command support
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
ragged2e.sty    2009/05/21 v2.1 ragged2e Package (MS)
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
 teubner.sty    2016/03/31 v.4.8 Extensions for Greek philology
   iftex.sty    2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
 and LuaTeX
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
  pdftex.def    2017/06/24 v1.0g Graphics/color driver for pdftex
  ifthen.sty    2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
 exscale.sty    2014/09/29 v2.1h Standard LaTeX package exscale
   trace.sty    2014/10/28 v1.1d trace LaTeX code
  lgrcmr.fd    2017/07/29 v1.2 Greek European Computer Regular
 ucsencs.def    2011/01/21 Fixes to fontencodings LGR, T3
supp-pdf.mkii
epstopdf-base.sty    2016/05/15 v2.6 Base part for package epstopdf
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
  grfext.sty    2016/05/16 v1.2 Manage graphics extensions (HO)
kvdefinekeys.sty    2016/05/16 v1.4 Define keys (HO)
 ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
pdftexcmds.sty    2017/03/19 v0.25 Utility functions of pdfTeX for LuaTeX (HO)
epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
textalpha.sty    2016/02/05 v0.13.2 macros for Greek letters in text
    toto.1
    toto.eledsec1
  uni-32.def    2013/05/13 UCS: Unicode data U+2000..U+20FF
 ***********

 )
````^

**Comment by maieul** [comment]
I have to eat and to sleep, but I think the problem is that we don't have the same version of packages.

**Comment by rrthomas** [comment]
No problem, I'll do a diff, just as soon as I work out how `\listfiles` works :)

**Comment by rrthomas** [comment]
*File List*
        book.cls    2014/09/29 v1.4h Standard LaTeX document class
        bk10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
    geometry.sty    2010/09/12 v5.6 Page Geometry
      keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
       ifpdf.sty    2011/01/30 v2.3 Provides the ifpdf switch (HO)
      ifvtex.sty    2010/03/01 v1.5 Detect VTeX and its facilities (HO)
     ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
     fontenc.sty
      lgrenc.def    2015/12/07 v0.13.1 LGR Greek font encoding definitions
    greek-fontenc.def    2015/08/04 v0.13 Common Greek font encoding definitions
       t1enc.def    2005/09/27 v1.99g Standard LaTeX file
       babel.sty    2016/02/24 3.9q The Babel package
       greek.ldf    2016/02/04 v1.9f Greek support for the babel system
     english.ldf    2012/08/20 v3.3p English support from the babel system
    inputenx.sty    2011/05/27 v1.10 Enhanced input encoding handling (HO)
    ix-alias.def    2011/05/27 v1.10 Alias list (inputenx)
    inputenc.sty    2015/03/17 v1.2c Input encoding file
       utf8x.def    2004/10/17 UCS: Input encoding UTF-8
         ucs.sty    2013/05/11 v2.2 UCS: Unicode input support
    uni-global.def    2013/05/13 UCS: Unicode global data
    lettrine.sty    2015/08/31 v1.9 (Daniel Flipo)
    lettrine.cfg
    reledmac.sty    2017/08/31 v2.24.1 typesetting critical editions
     xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
     xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
       xargs.sty    2008/03/22 v1.1  extended macro definitions  (mpg)
      xparse.sty    2016/01/19 v6377 L3 Experimental document command parser
       expl3.sty    2016/01/19 v6377 L3 programming layer (loader) 
    expl3-code.tex    2016/01/19 v6377 L3 programming layer 
    l3pdfmode.def    2015/11/11 v6250 L3 Experimental driver: PDF mode
    etoolbox.sty    2015/08/02 v2.2a e-TeX tools for LaTeX (JAW)
      suffix.sty    2006/07/15 1.5a Variant command support
     xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
    ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
    ragged2e.sty    2009/05/21 v2.1 ragged2e Package (MS)
    everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
     teubner.sty    2015/10/25 v.4.7b Extensions for Greek philology
       iftex.sty    2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
     and LuaTeX
    graphicx.sty    2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)
    graphics.sty    2016/01/03 v1.0q Standard LaTeX Graphics (DPC,SPQR)
        trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
    graphics.cfg    2010/04/23 v1.9 graphics configuration of TeX Live
      pdftex.def    2011/05/27 v0.06d Graphics/color for pdfTeX
    infwarerr.sty    2010/04/08 v1.3 Providing info/warning/error messages (HO)
     ltxcmds.sty    2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
      ifthen.sty    2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
     exscale.sty    2014/09/29 v2.1h Standard LaTeX package exscale
       trace.sty    2014/10/28 v1.1d trace LaTeX code
      lgrcmr.fd    2013/09/01 v1.0 Greek European Computer Regular
     ucsencs.def    2011/01/21 Fixes to fontencodings LGR, T3
    supp-pdf.mkii
    pdftexcmds.sty    2011/11/29 v0.20 Utility functions of pdfTeX for LuaTeX (HO)
    epstopdf-base.sty    2010/02/09 v2.5 Base part for package epstopdf
      grfext.sty    2010/08/19 v1.1 Manage graphics extensions (HO)
    kvdefinekeys.sty    2011/04/07 v1.3 Define keys (HO)
    kvoptions.sty    2011/06/30 v3.11 Key value format for package options (HO)
    kvsetkeys.sty    2012/04/25 v1.16 Key value parser (HO)
    etexcmds.sty    2011/02/16 v1.5 Avoid name clashes with e-TeX commands (HO)
    epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
    textalpha.sty    2016/02/05 v0.13.2 macros for Greek letters in text
         bar.1
         bar.eledsec1
      uni-32.def    2013/05/13 UCS: Unicode data U+2000..U+20FF
     ***********

**Comment by rrthomas** [comment]
OK, I see several differences, I'm updating to TeXLive 2017, and I'll see whether that fixes it, and if not, what differences remain.

**Comment by maieul** [comment]
I would be curious to know which is the older package which add incompatibility …

**Comment by rrthomas** [comment]
I hope you'll forgive me, I can't see a way to bisect two TeXLive versions (given that I don't have it installed from Subversion/git). I will see if it works with TeXLive 2017, and provide a diff, at least.

**Comment by maieul** [comment]
honestly, I have no idea how to bisect two TeXLive versions ;-)

**Comment by rrthomas** [comment]
OK, updating my TeXLive fixes the MWE. Will now see if it fixes my main project.

**Comment by rrthomas** [comment]
Phew, fixes it. (After working out what I had to do with my `TEXMFVAR` directory from TeXLive 2015!)

**Comment by rrthomas** [comment]
Therefore I think we can close this bug.

**Comment by maieul** [comment]
well, I am happy to not have to look on this bug ;-)
