### ISSUE TITLE
Confusion in documentation of \Xtxtbeforenotes vs \Xbhookgroup

### ISSUE THREAD

**Issue by rrthomas** [maieul/ledmac#705]
The documentation for \Xbhookgroup says: "While \Xtxtbeforenotes is for typesetting code before notes, \Xbhookgroup and \bhookgroupX (respectively for critical and familiar) are for executing code before a
groups of notes,…"

Should the first "code" be "text", since `\Xtxtbeforenotes` is for typesetting text (section 7.13.2 "Text before notes"), not code? In other words, should the sentence read:

While \Xtxtbeforenotes is for typesetting **text** before notes, \Xbhookgroup and \bhookgroupX (respectively for critical and familiar) are for executing code before a groups of notes,

? (Bold added just to show the change.)

**Comment by rrthomas** [comment]
Also, the fact that `Xbhookgroup` can take a series as an optional argument does not appear to be documented; I had to guess this!

**Comment by maieul** [comment]
corrected. 

For the optional argument, all the « hook » defined on § 7 can contain it, as explained on the beginning.

(Note: I think §7 should have an other title, but which one?)

**Comment by rrthomas** [comment]
Thanks, better now! I think the title of section 7 is OK. Your changing the text to mention the optional argument is what I needed!

**Comment by maieul** [comment]
ok, the problem is that the section 7 
1. cover also classical footnote, and note only critical footnote
2. Does not concern only appareance (but mainly)

**Comment by rrthomas** [comment]
In that case, one option would be to make that section a subsection (literally, change `\section` to `\subsection`), and then the rest of the section is folded into section 6.

**Comment by maieul** [comment]
I think it better to have distinc section in the general plan…

**Comment by rrthomas** [comment]
How about changing the title to "Apparatus customization"? I think that users will associate "customization" with "changing how it looks", but this also deals with the fact that, as you say, it concerns other customization (the various "arbitrary code" commands).

**Comment by maieul** [comment]
Apparatus setting?

**Comment by rrthomas** [comment]
I think "Customization" is better, because it more strongly suggests changing how it looks (which is most of the section). But "settings" (has to be plural) would also work.

**Comment by maieul** [comment]
done on 4e52fbf3

Could I add you to a list of people which could help me for all problem of english spelling?

**Comment by rrthomas** [comment]
Sure.

**Comment by maieul** [comment]
thanks, that is done

**Comment by maieul** [comment]
done. Thanks you
