### ISSUE TITLE
Footnotes with \linenumannotation do not show as wished in apparatus

### ISSUE THREAD

**Issue by enjotel** [maieul/ledmac#707]
Hello,
I use a certain configuration in my critical apparatus, that uses pāda-numbers 1a-1d in each stanza. Each stanza consists of 2 hemistiches. Each hemistich consists of 2 pādas. So altogether 4 pādas in one stanza that should be marked in apparatus as 1a, 1b, 1c, 1d for the first stanza and so on.

My apparatus consists of two layers of footnotes. The lower layer is supposed to show lemma ] em. blabla Ms etc. The first layer is supposed to show quotes of lower witnesses that span over  a whole stanza. So I put the footnote around the whole stanza, which finally :) works fine.

But instead of showing 1a-d lemma footnotetext, it shows 1-d lemma footnotetext. I'd love to achieve 1a-d in an elegant way.

My current code in minimal example:

[mula.pdf](https://github.com/maieul/ledmac/files/1356479/mula.pdf)
`\documentclass[a4paper,11pt]{article}

\usepackage{lscape}

\usepackage{polyglossia}
\setmainlanguage{german}
\setotherlanguage{sanskrit}

\usepackage{fontspec}
\setmainfont{TeX Gyre Termes}
\setmonofont{TeX Gyre Termes}
\newfontfamily\devanagarifont[Script=Devanagari]{Chandas}
\newfontfamily\devnag[Script=Devanagari]{Chandas}

\newfontface\dejlight{DejaVu Sans}

\DeclareTextFontCommand{\textding}{\dejlight}

\usepackage[hang,flushmargin]{footmisc}

\usepackage[noend,noeledsec]{reledmac}
\usepackage{libertineotf}
\arrangementX[A]{paragraph}
\Xarrangement[B]{paragraph}
\Xarrangement[A]{paragraph}

\setstanzaindents{3,1}
\setcounter{stanzaindentsrepetition}{1}
\linenumincrement{1}
\firstlinenum{1}

\begin{document}

\section{Edition}
\begingroup
\beginnumbering

\stanza
\edtext{\setline{1}\linenumannotation{a}\edtext{candraḥ}{\Bfootnote{em. : \textit{candra} Ms}} sūryas tathā \edtext{vahniḥ}{\Bfootnote{em. : \textit{vahni} Ms}} \linenumannotation{b}śarīre daśa nāḍikāḥ |&
\setline{1}\linenumannotation{c}\edtext{pañca sthā}{\Bfootnote{\textit{dehasthā} Pts}} \edtext{vāyavaḥ}{\Bfootnote{em. : \textit{vāyava} Ms}} pañca \linenumannotation{d}mano bindus tathaiva ca ||1||}{\lemma{\textbf{Ci}}\Afootnote[nosep]{Vgl. Pts S.84, Z. 5102-5104: candraḥ sūryas tathā vahniḥ śarīre daśa nāḍikāḥ | dehasthā vāyavaḥ pañca mano bindus tathaiva ca |}}\& 

\endnumbering
\clearpage

\end{document}
`

**Comment by maieul** [comment]
it should be written on #602
