### ISSUE TITLE
A problem with markboth and dict style headings

### ISSUE THREAD

**Issue by JuanManuelM** [maieul/ledmac#708]
Hi,

I'm setting a critical edition containing, throughout the text, a series of  paragraph numbers, that don't correspond to the actual paragraphs. I would like to print that series in the headings, in the dictionary style, using a `markboth` inside a `doinsidelinehook`, but the sequence is not displayed correctly. Maybe I'm doing something wrong?

I have created this MWE, with two long paragraphs:

```[latex]
\documentclass[twoside]{article}
\usepackage{fancyhdr}
\usepackage{ifthen}
\usepackage{reledmac}

% marks and headings

\newcommand{\mymarks}{%
	\ifthenelse{\equal{\leftmark}{\rightmark}}
	{\rightmark} 
	{{\rightmark} – {\leftmark}}}

\fancyhead[LE,RO]{}
\fancyhead[CE,CO]{\mymarks}
\fancyhead[LO,RE]{}
\newcommand{\numpar}[1]{--\doinsidelinehook{\markboth{#1}{#1}}\textbf{#1}--}
\pagestyle{fancy}

\begin{document}
\beginnumbering 
\autopar 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nec
augue elit. Vestibulum ante ipsum primis in faucibus orci luctus et
ultrices posuere cubilia Curae; Quisque cursus eros a erat placerat,
et tempus neque volutpat. Morbi ultrices at magna et
cursus. Sed\numpar{AAA} vel purus luctus, euismod erat in, fermentum
orci. Vivamus ac rutrum sapien, id ultricies augue. Fusce sed rutrum
lorem, ut auctor urna. Proin rutrum dignissim turpis, placerat
pellentesque nulla elementum in. Nunc id tristique ipsum. Quisque
semper faucibus orci at eleifend. Proin velit velit, sagittis nec
consequat in, auctor eget tortor. Pellentesque lorem elit, scelerisque
id vulputate vel, faucibus a eros. Nunc nec orci ullamcorper,
sollicitudin magna id, maximus quam. Pellentesque nec mauris
purus. Duis suscipit nunc vitae faucibus posuere. Integer mattis
varius cursus. Proin risus diam, imperdiet sit amet sem sed, dapibus
sodales quam. Pellentesque bibendum sapien eu nisl efficitur
placerat. Aenean dignissim ante ac erat pharetra, non pellentesque
ante sodales. Nunc lorem nunc, elementum in accumsan id, blandit ac
elit. In rhoncus augue ex, quis tristique ex laoreet non. Phasellus
tincidunt, mauris nec auctor maximus,\numpar{BBB} sapien elit
elementum dolor.

Id pretium urna tortor sed purus. Donec velit leo, varius ac dui eget,
tincidunt euismod nibh. Nulla facilisis sit amet leo et
vehicula. Morbi ultrices elementum nisi, ac semper neque faucibus
non. Curabitur et justo gravida eros consequat elementum. Quisque eu
consequat eros, vitae ullamcorper risus. Nullam pellentesque id lectus
a aliquet. Cras rhoncus, arcu ut consequat ultricies, massa ante
sollicitudin massa, vehicula ullamcorper quam libero vitae eros. In
dapibus arcu sed sem vehicula, ut imperdiet odio hendrerit. Praesent
nec diam turpis. Vestibulum erat ante, maximus id pulvinar vitae,
sagittis sed odio. Pellentesque sit amet tellus aliquam, mattis purus
a, consectetur turpis. Praesent nunc magna, posuere ac faucibus eu,
ullamcorper vel sem. Aenean vel dolor eget felis malesuada molestie ac
non justo. Phasellus semper gravida mollis. Mauris fermentum eget ex
et eleifend. Morbi sit amet cursus velit. Ut efficitur, risus vel
mattis ultrices, arcu metus scelerisque dui, eget semper dolor justo
ac nisl. Fusce euismod ultrices faucibus. Vestibulum sit amet lacus
dui. Maecenas\numpar{CCC} et nisi vel ex scelerisque dictum at vel
nibh. Morbi mattis quam ut congue elementum. Etiam luctus ac metus id
faucibus. Nulla vulputate massa non tincidunt fringilla. Praesent
accumsan eget enim eu dapibus. Nunc auctor, odio nec venenatis auctor,
nibh sem efficitur sapien, ut mollis nunc nunc at massa. Morbi vitae
turpis iaculis, imperdiet quam vel, blandit purus. Suspendisse
lobortis dui et enim egestas, sed convallis dolor viverra. Etiam
mollis dolor nec laoreet facilisis. Pellentesque fringilla mauris
rhoncus pretium facilisis. Quisque vitae posuere justo. Quisque a
rutrum elit.\numpar{DDD} In at pretium magna. Morbi sed ullamcorper
lectus. Praesent ut rhoncus odio. Cras a metus nisl. Aliquam et congue
nisi, viverra ultricies metus. Duis fringilla laoreet nisi, at
suscipit ex porttitor sed. Mauris sit amet purus efficitur, euismod
sem vitae, mattis neque. Mauris pretium, turpis a suscipit pulvinar,
est nunc lacinia lacus, at pulvinar nunc lacus in erat. Lorem ipsum
dolor sit amet, consectetur adipiscing elit. Morbi nec augue
elit. Vestibulum ante ipsum primis in faucibus orci luctus et
ultrices\numpar{EEE} posuere cubilia Curae; Quisque cursus eros a erat
placerat, et tempus neque volutpat. Morbi ultrices at magna et
cursus. Sed vel purus luctus, euismod erat in, fermentum orci. Vivamus
ac rutrum sapien, id ultricies augue. Fusce sed rutrum lorem, ut
auctor urna. Proin rutrum dignissim turpis, placerat pellentesque
nulla elementum in. posuere cubilia Curae; Quisque cursus eros a erat
placerat, et tempus neque volutpat. Morbi ultrices at magna et
cursus. \numpar{FFF} Sed vel purus luctus, euismod erat in, fermentum
orci. Vivamus ac rutrum sapien, id ultricies augue. Fusce sed rutrum
lorem, ut auctor urna. Proin rutrum dignissim turpis, placerat
pellentesque nulla elementum in. Id pretium urna tortor sed
purus. Donec velit leo, varius ac dui eget, tincidunt euismod
nibh. Nulla facilisis sit amet leo et vehicula. Morbi ultrices
elementum nisi, ac semper neque faucibus non. Curabitur et justo
gravida eros consequat elementum. Quisque eu consequat eros, vitae
ullamcorper risus. Nullam pellentesque id lectus a aliquet. Cras
rhoncus, arcu ut consequat ultricies, \numpar{GGG} massa ante
sollicitudin massa, vehicula ullamcorper quam libero vitae eros. In
dapibus arcu sed sem vehicula, ut imperdiet odio hendrerit. Praesent
nec diam turpis. Vestibulum erat ante, maximus id pulvinar vitae,
sagittis sed odio.
\endnumbering 
\end{document}```

**Comment by maieul** [comment]
Your MWE provokes an error when running. Please send me a new one 
without error.
Le 2017-10-09 15:31, Juan Manuel Macías a écrit :

**Comment by JuanManuelM** [comment]
How strange. I've compiled it in sharelatex too and it works fine ...
I send you again, in normal text. In the preview my markdown is not recognized (?). Apologies

\documentclass[twoside]{article}
\usepackage{fancyhdr}
\usepackage{ifthen}
\usepackage{reledmac}

% marks and headings

\newcommand{\mymarks}{%
	\ifthenelse{\equal{\leftmark}{\rightmark}}
	{\rightmark} 
	{\rightmark – \leftmark}}

\fancyhead[LE,RO]{}
\fancyhead[CE,CO]{\mymarks}
\fancyhead[LO,RE]{}
\newcommand{\numpar}[1]{\doinsidelinehook{\markboth{#1}{#1}}\textbf{#1}}
\pagestyle{fancy}

\begin{document}
\beginnumbering 
\autopar 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nec augue elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque cursus eros a erat placerat, et tempus neque volutpat. Morbi ultrices at magna et cursus. Sed\numpar{AAA} vel purus luctus, euismod erat in, fermentum orci. Vivamus ac rutrum sapien, id ultricies augue. Fusce sed rutrum lorem, ut auctor urna. Proin rutrum dignissim turpis, placerat pellentesque nulla elementum in. Nunc id tristique ipsum. Quisque semper faucibus orci at eleifend. Proin velit velit, sagittis nec consequat in, auctor eget tortor. Pellentesque lorem elit, scelerisque id vulputate vel, faucibus a eros. Nunc nec orci ullamcorper, sollicitudin magna id, maximus quam. Pellentesque nec mauris purus. Duis suscipit nunc vitae faucibus posuere. Integer mattis varius cursus. Proin risus diam, imperdiet sit amet sem sed, dapibus sodales quam. Pellentesque bibendum sapien eu nisl efficitur placerat. Aenean dignissim ante ac erat pharetra, non pellentesque ante sodales. Nunc lorem nunc, elementum in accumsan id, blandit ac elit. In rhoncus augue ex, quis tristique ex laoreet non. Phasellus tincidunt, mauris nec auctor maximus,\numpar{BBB} sapien elit elementum dolor.

Id pretium urna tortor sed purus. Donec velit leo, varius ac dui eget, tincidunt euismod nibh. Nulla facilisis sit amet leo et vehicula. Morbi ultrices elementum nisi, ac semper neque faucibus non. Curabitur et justo gravida eros consequat elementum. Quisque eu consequat eros, vitae ullamcorper risus. Nullam pellentesque id lectus a aliquet. Cras rhoncus, arcu ut consequat ultricies, massa ante sollicitudin massa, vehicula ullamcorper quam libero vitae eros. In dapibus arcu sed sem vehicula, ut imperdiet odio hendrerit. Praesent nec diam turpis. Vestibulum erat ante, maximus id pulvinar vitae, sagittis sed odio. Pellentesque sit amet tellus aliquam, mattis purus a, consectetur turpis. Praesent nunc magna, posuere ac faucibus eu, ullamcorper vel sem. Aenean vel dolor eget felis malesuada molestie ac non justo. Phasellus semper gravida mollis. Mauris fermentum eget ex et eleifend. Morbi sit amet cursus velit. Ut efficitur, risus vel mattis ultrices, arcu metus scelerisque dui, eget semper dolor justo ac nisl. Fusce euismod ultrices faucibus. Vestibulum sit amet lacus dui. Maecenas\numpar{CCC} et nisi vel ex scelerisque dictum at vel nibh. Morbi mattis quam ut congue elementum. Etiam luctus ac metus id faucibus. Nulla vulputate massa non tincidunt fringilla. Praesent accumsan eget enim eu dapibus. Nunc auctor, odio nec venenatis auctor, nibh sem efficitur sapien, ut mollis nunc nunc at massa. Morbi vitae turpis iaculis, imperdiet quam vel, blandit purus. Suspendisse lobortis dui et enim egestas, sed convallis dolor viverra. Etiam mollis dolor nec laoreet facilisis. Pellentesque fringilla mauris rhoncus pretium facilisis. Quisque vitae posuere justo. Quisque a rutrum elit.\numpar{DDD} In at pretium magna. Morbi sed ullamcorper lectus. Praesent ut rhoncus odio. Cras a metus nisl. Aliquam et congue nisi, viverra ultricies metus. Duis fringilla laoreet nisi, at suscipit ex porttitor sed. Mauris sit amet purus efficitur, euismod sem vitae, mattis neque. Mauris pretium, turpis a suscipit pulvinar, est nunc lacinia lacus, at pulvinar nunc lacus in erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nec augue elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices\numpar{EEE} posuere cubilia Curae; Quisque cursus eros a erat placerat, et tempus neque volutpat. Morbi ultrices at magna et cursus. Sed vel purus luctus, euismod erat in, fermentum orci. Vivamus ac rutrum sapien, id ultricies augue. Fusce sed rutrum lorem, ut auctor urna. Proin rutrum dignissim turpis, placerat pellentesque nulla elementum in. posuere cubilia Curae; Quisque cursus eros a erat placerat, et tempus neque volutpat. Morbi ultrices at magna et cursus. \numpar{FFF} Sed vel purus luctus, euismod erat in, fermentum orci. Vivamus ac rutrum sapien, id ultricies augue. Fusce sed rutrum lorem, ut auctor urna. Proin rutrum dignissim turpis, placerat pellentesque nulla elementum in. Id pretium urna tortor sed purus. Donec velit leo, varius ac dui eget, tincidunt euismod nibh. Nulla facilisis sit amet leo et vehicula. Morbi ultrices elementum nisi, ac semper neque faucibus non. Curabitur et justo gravida eros consequat elementum. Quisque eu consequat eros, vitae ullamcorper risus. Nullam pellentesque id lectus a aliquet. Cras rhoncus, arcu ut consequat ultricies, \numpar{GGG} massa ante sollicitudin massa, vehicula ullamcorper quam libero vitae eros. In dapibus arcu sed sem vehicula, ut imperdiet odio hendrerit. Praesent nec diam turpis. Vestibulum erat ante, maximus id pulvinar vitae, sagittis sed odio.

\endnumbering 
\end{document}

**Comment by maieul** [comment]
now, it's working.

Your problem is normal, it is linked to the time your commands are read, 
which is before the text are typesetted.

If you mark can be done in each pstart, we could have an easy solution. 
If it is not the the case, I have to implement a feature in 
reledmac/reledpar… but for now I have no time

**Comment by JuanManuelM** [comment]
Ok, thank you for your precise explanation. I understand now...

Unfortunately, the marks in this edition would have to be located in specific places of the text, most of them within a long paragraph. So I'll stop using markboth and dict headings here...

In any case, thank you very much for your great work!

**Comment by maieul** [comment]
keep your commands in your text, maybe I would be able oneday to add the 
feature you need.

**Comment by JuanManuelM** [comment]
Great! I think it would be a very interesting feature...

**Comment by maieul** [comment]
all users thanks there feature are interesseting… and they are right

**Comment by maieul** [comment]
I found it! Will be send you some information near.

**Comment by maieul** [comment]
The branch issue708 create a \doinsidethislinehook to be called in the flow of text. Please try it and tel me (it work with your example, in two runs).

**Comment by JuanManuelM** [comment]
What a great news! Thank you so much. I just tried the example with `\doinsidethislinehook` and it works perfectly.
