### ISSUE TITLE
empty entry in endnote-apparatus using \ledsidenote + \edtabular

### ISSUE THREAD

**Issue by Latin-TeX** [maieul/ledmac#709]
I use `\doendnotesbysection{X}` and encountered a problem using an `\Xendnote` in an `\edtabular`-environment **and** a `\ledsidenote` in the same section:
There appear empty entries in the endnote-apparatus.

Here the MWE:

    \documentclass[12pt,a4paper]{scrbook}
    \usepackage[utf8]{inputenc}
    \usepackage{amsmath}
    \usepackage{amsfonts}
    \usepackage{amssymb}
    
    \usepackage{reledmac}
    \usepackage{reledpar}
    \linenummargin{inner} 
    \sidenotemargin{outer} 
    
    \let\Bfootnoterule=\relax
    \Xnotenumfont[B]{\bfseries}
    \Xendnotenumfont[B]{\bfseries}
    \Xendparagraph[B]
    \Xendbeforepagenumber[B]{}
    \Xendafterpagenumber[B]{}
    \Xendlemmaseparator[B]{\rbracket}
    \renewcommand*{\printnpnum}[1]{} % Keine Seitenzahlen in Endnotes
    \Xtwolines[B]{f.}
    \Xtwolinesbutnotmore[B]
    \Xendtwolines[B]{f.}
    \Xendtwolinesbutnotmore[B]
    
    
    \begin{document}
    
    \subsubsection{Example} % it's a subsubsection to simulate my original document.
    \beginnumbering
    \pstart\noindent
    \ledsidenote{[52r]}%
    	Figura testimoniorum planetarum in 12 domibus eorum, quantas habeant uirtutes, quilibet in qualibet.
    \pend
    \bigskip
    \pstart
    	\begin{center}
    		\begin{edtabularl}
    			Pro domo & & 52 & \\
    			Pro exaltatione & & 43 & \\
    			Pro triplicitate & & 34 & 
    			\edtext{Ptolemaei}{
    				\Bfootnote{Ptolomei}} \\
    			Pro termino & & 21 & \\
    			Pro facie & \edatright[\text{Habent testimonia}]{\}}{2.5\baselineskip} \edatleft[]{\{}{2.5\baselineskip} & 1 &
    		\end{edtabularl}
    	\end{center}
    \pend
    \endnumbering
    
    \doendnotesbysection{B}
    \end{document}

It may not be super minimal, but I tried to reconstruct the appearance that I actually use in my original document.

If you delete the `\ledsidenote`, the endnote shows up totally fine. Also, if you use `\Xfootnote`, it works, too, but I need endnotes and `\ledsidenote`.

Is there a way to get around this problem using endnotes and `\ledsidenote` anyway?

**Comment by maieul** [comment]
As explained on SE, I will look on this problem as soon I have a working 
computer.

**Comment by maieul** [comment]
Please try branch issue709.

Also notes you wrote a spurious space that made your array not well aligned. Cf 8200b397 to see how to correct it.

**Comment by Latin-TeX** [comment]
With the fix of branch issue709 it works perfectly fine now. Thanks for all the help and support!

**Comment by maieul** [comment]
I publish it on CTAN. I while post an answer on SE. Please validate it.
