### ISSUE TITLE
Prevent interline alteration

### ISSUE THREAD

**Issue by Alessio-R** [maieul/ledmac#710]
Hi Maieul,

I'm using the latest version of reledmac with Greek fonts, and everytime I write composite characters which are tallest than others it automatically enalrges the interline (see the image), while using them in normal paragraph outside reledmac doesn't alter the interline. How can I do to prevent this?

![screen](https://user-images.githubusercontent.com/6702933/31852795-9e3733a6-b67e-11e7-994e-f88afe60ef94.PNG) (here the tallest character is on line g)

Thank you.

EDIT: this not happens always

**Comment by maieul** [comment]
As always, please provide a MWE. Personnaly, I have no problem with greek fonts and composite characters.

**Comment by Alessio-R** [comment]
Maybe it depends on a new greek font that I'm using, which has some overflowing diacritics. I resolved the problem adding \lineskiplimit=-100pt\relax to the preamble.

**Comment by maieul** [comment]
Did the problem also happened in normal text (without reledmac) ?

**Comment by Alessio-R** [comment]
Yes, I noticed that it appears inside a \parcolumns environment only, with or without reledmac.

**Comment by maieul** [comment]
so the problem was not linked to reledmac, and we can close the issue.
