### ISSUE TITLE
Require hook to be executed once only before each request to print endnotes

### ISSUE THREAD

**Issue by kfeuerherm** [maieul/ledmac#714]
As outlined in https://tex.stackexchange.com/questions/399673/reledmac-endnotes-formatted-as-single-paragraph, it would be useful to have a feature similar to `\Xtxtbeforenotes` but for endnotes, i.e. one would like to execute a section of code (for example to produce a short horizontal rule like the one which typically precedes footnotes) just as each `\doendnotesbysection{<s>}` is executed.

**Comment by maieul** [comment]
Pleas try branch issue714 which and `Xendtxtbeforenotes`

**Comment by maieul** [comment]
hi @kfeuerherm  some news? I would like to release tonight or today.

**Comment by kfeuerherm** [comment]
Bonjour,

Malheureusement mon meilleur ami est décèdé soudainement hier soir et donc j’ai été occupé avec cela….

Je m’excuse. J’essaierai cela tantôt, j’espère que je suis en assez bon état pour le faire correctement. Cela sera pour moi la première fois….

K

**Comment by maieul** [comment]
Bonjour,

oh mon pauvre. Je comprends parfaitement. Il y a des choses plus iimportantes que l’édition critique dans la vie. Bon courage :-(

**Comment by kfeuerherm** [comment]
Merci mon ami. Je suis juste en train de regarder ça….

**Comment by maieul** [comment]
ne vous sentez pas non plus obligés, si vous n’avez pas la force. Cela attendra, ma foi. 
>

**Comment by kfeuerherm** [comment]
Nous avons du mauvais temps par ici et puisque je suis sur système satellite le téléchargement prend plus longtemps… enfin, nous verrons!

Si j’ai de la chance j’essaierai votre autre truc aussi avec les numéros….

**Comment by kfeuerherm** [comment]
Ça va, il me faut faire quelque chose afin de ne pas trop me morfondre….

:)

**Comment by kfeuerherm** [comment]
J’ai réussi à fabriquer les .sty mais si j’essaie “latex reledmac.dtx” on me dit:

! Use of \@icentercr doesn't match its definition.
\@ifnextchar ... \reserved@d =#1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f…

Je suppose que ce n’est pas la bonne méthode… Je voulais voir la syntaxe pour le commandement…

**Comment by maieul** [comment]
si vous avez le point sty, il suffit de le poser à côté de votre .tex

Vous pourrez alors utiliser la nouvelle fonctionnalité

\Xendtxtbeforenotes

**Comment by kfeuerherm** [comment]
Oui, d’accord, j’ai bien compris ça… Je voulais simplement vérifier si je faisais comme ceci:

\Xendtxtbeforenotes[A]{<machin chouette>}?

Je suppose que puisque nous avons "\Xtxtbeforenotes[⟨s⟩]{⟨text⟩}” selon ce que vous avez suggéré ce sera bien ça. J’essaie…

**Comment by kfeuerherm** [comment]
Applying the packages from this branch to the MWE from Stackexchange, with this code:
`\Xendtxtbeforenotes[A]{\vskip 6pt\footnoterule}` the results are exactly as desired. I am happy to try a few other examples here to ensure that they do what they are supposed to do also.

**Comment by maieul** [comment]
exactement (notez que si vous ne mettez pas [A] cela s’applique à toutes les séries… en général cela suffit.)

**Comment by kfeuerherm** [comment]
Ah! Encore mieux!

De toute façon, cela a bien marché, j’ai posté (?) au git….

**Comment by maieul** [comment]
Merci.

En fait toute notre conversation c’est retrouvé sur « l’issue » de github, puisqu’on a répondu par mail à l’adresse que github a utilisé.

Je ne pense pas qu’il faille des tests supplémentaires. Je vais publier cela ce soir (heure française). 

Toutes les commande de réglages sur les notes prennent en argument optionnel (donc entre crochet) la série de notes à laquelle elle s’applique (une liste de série, par exemple [A,B] pour appliquer à A et à B).

**Comment by kfeuerherm** [comment]
Pas de quoi, le plaisir est à moi.

Trop tard, j’ai essayé avec le MWE pour notes de fin, cela marche tout comme il faut chez moi.

**Comment by maieul** [comment]
parfait. Concernant le bug sur reledmac.dtx, c’est au moment de générer la documentation. J’avais fait une coquille. J’ai corrigé en local. Cela va être publié incessament sous peu

**Comment by kfeuerherm** [comment]
D’accord, je ne m’en soucierai plus :)

**Comment by maieul** [comment]
J'ai publié sur le CTAN, et j'ai modifié ma réponse sur stackexchange. Pouvez vous la valider (je suggère aussi de supprimer votre réponse)
