### ISSUE TITLE
Printing a colon ":" in the place of comma after the end of indexed text

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#716]
Hi! I want to print a colon ":" in the place of comma after the end of the indexed text in the "Index locorum" (NOT in the "Index nominum" and also NOT in the "Index verborum"). As you can see in the example, I have been printing the pages of the source in bold in order to differenciate it from the lines inmy edition (e.g. **392.20–28**, 15.2); I must, however, use a semicolon in order for it to look like "392.20–28: 15.2".

I tried to create an *.ist file containing
> delim_2 ": "
but it does not work.

Then I tried to add delim_2 ": " to the *ist that I already have created
> page_compositor "–"
> delim_r "."
> delim_2 ": "
It does not work either.

I would be greatfull for a solution. Here follows the MWE

\documentclass[a4paper]{book}
\usepackage{polyglossia,fontspec,xunicode}
\setmainfont{Linux Libertine O}

\setmainlanguage{english}
\setotherlanguage[variant=ancient]{greek}

\usepackage[makeindex]{imakeidx}
\usepackage[noeledsec,noend,noledgroup,series={A,B,C,D,E}]{reledmac}
\usepackage{reledpar}
\lineation{pstart}
\lineationR{pstart} 
\setlength{\ledlsnotesep}{2 \ledlsnotesep}
\Xarrangement[A]{paragraph}
\Xnumberonlyfirstinline[A]
\Xinplaceofnumber[A]{0pt}
\Xinplaceoflemmaseparator[A]{2pt}

\renewcommand{\thepageline}{%
\the\value{pstartL}%
\pagelinesep%
\xlineref{\edindexlab\thelabidx}%
}
\renewcommand{\pagelinesep}{.}

\makeindex[name=nomi,options=-s mystyle,title=Index nominum,columns=2]{}
\makeindex[name=rer,options=-s mystyle,title=Index verborum,columns=2]{}
\makeindex[name=loc,options=-s mystyle,title=Index locorum,columns=2]{}
\newcommand*{\sectionformat}{\centering\color{\sectioncolor}}

\begin{document}
\setcounter{page}{1}
\begin{pages}
\begin{greek}
\begin{Leftside}
\beginnumbering
\setcounter{pstartL}{15}
\numberpstarttrue
\pstart
Τὸ τῆς ἱστορίας χρήσιμον καὶ πρὸ ἡμῶν οἱ πολλοὶ συγγραψάμενοι διωρίσαντο
καὶ ἅπερ ἂν ἐκείνοις ἐπῆλθεν εἰπεῖν, ταῦτα ἂν καὶ ἡμεῖς ἐρεῖν ἔχωμεν·\edindex[loc]{FIRST WRITER!Work!392.20--28@\textbf{392.20--28}|(} τὶ γὰρ ἂν εὕ-
ροιμεν καινότερον νόημα τοσούτων ἱστορησάντων καὶ σύμπαν τῆς ἱστορίας ἀποφηναμένων ἐν τοῖς σφετέροις συγγράμμασι; τάχα δὲ ὃ πλέον ἐκείνων ἐν τοῖς νῦν προκειμένοις ἡμῖν λέξειν ἄξιον, τοῦτό γε ἂν τῆς ἡμετέρας συγγραφῆς\edindex[rer]{συγγραφη@συγγραφή} 
 προβαλλώμεθα. Οἱ μὲν οὖν τὰ καθ’ ἡμᾶς
ἱστορικῶς συγγραψάμενοι ἄλλην ἄλλως πεποίηνται τὴν ἀρχήν·\edindex[loc]{SECOND WRITER!Work 1!222.22@\textbf{222.22}} οἱ μὲν γὰρ αὐτῶν ἀπὸ
τῆς τοῦ κόσμου γενέσεως ἤρξαντο, οἱ δὲ ἐξ ἀξιολόγου τῆς ἀρχῆς, ἢ Περσῶν ἢ Ἑλλήνων ἢ Ῥωμαίων ἢ ἄλλου οὑτινοσοῦν ἐθνῶν, ἕκαστος πρὸς τὸν ἑαυτοῦ σκοπὸν τὸ οἰκεῖον καταρτιζόμενος σύγγραμμα. Καὶ ἡμῖν οὐχ ἥκιστα οὕτω τὰ τῆς συγγραφῆς τελεσθήσεται.\edindex[loc]{SECOND WRITER!Work 2!25.10@\textbf{25.10}}
Καὶ πρὸς ἀλλήλους οἱ πλείους οὐ συνεφώνησαν
τὰ τῶν βασιλέων συγγράφοντες, ἀλλοιώσεις τε χωρῶν καὶ πόλεων στάσεις καὶ πολέμων συῤῥήξεις.
Ἰωάννου τοῦ Παλαιολόγου\edindex[nomi]{ιωαννης-παλαιολογος@Ἰωάννης Παλαιολόγος}
 ἕνεκεν τῆς ἐν Φλωρεντίᾳ συνόδου καὶ πῶς ἡ Ἑνετῶν γερουσία ἐδέχθη αὐτόν, ὁμοίως καὶ ὁ Φεῤῥαρίας μαρκίων, ἀπελθόντος τοῦ βασιλέως εἰς
Φεῤῥαρίαν.\edindex[loc]{THIRD WRITER!Work!13-392.20--28@\textbf{392.20--28}|)}
 Εἶτα διηγησόμεθα καὶ περὶ ὧν εὐεργεσιῶν καὶ προνομίων, ἃ τὸ περιώ-
νυμον τῆς Μονεμβασίας ἄστυ εὐηργετήθη παρὰ τῶν βασιλέων, καὶ περὶ τῶν γεγονότων πολέμων ἐν τῇ Πελοποννήσῳ ἀνὰ τῶν δεσποτῶν καὶ ἀδελφῶν, λέγω κὺρ Δημητρίου\edindex[nomi]{δημητριος-παλαιολογος@Δημήτριος Παλαιολόγος} καὶ κὺρ Θωμᾶ\edindex[nomi]{θωμας-παλαιολογος@Θωμᾶς Παλαιολόγος}· καὶ περὶ τῆς τοῦ δεσπότου κὺρ Θωμᾶ μετὰ ἑτέρων ἀρχόντων ἐλεύσεως ἐν Κερκύραις, εἶτα ἐν Ῥώμῃ καὶ πῶς ἐδέχθη αὐτοὺς ὁ ἄκρος ἀρχιερεύς\edindex[rer]{αρχιερευς@ἀρχιερεύς}.
\pend
\endnumbering
\end{Leftside}
\end{greek}
\begin{Rightside}
\firstlinenum{1000000000}
\beginnumbering
\setcounter{pstartR}{15}
\numberpstarttrue
\pstart
So, at sixteen years and nine months, but looking four or five years older, and adorned with real whiskers which the scandalised Mother abolished within one hour of beholding, I found myself at Bombay where I was born, moving among sights and smells that made me deliver in the vernacular sentences whose meaning I knew not.So, at sixteen years and nine months, but looking four or five years older, and adorned with real whiskers which the scandalised Mother abolished within one hour of beholding, I found myself at Bombay where I was born, moving among sights and smells that made me deliver in the vernacular sentences whose meaning I knew not.\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\printindex[nomi]
\printindex[rer]
\printindex[loc]
\end{document}

**Comment by NiAgio** [comment]
Ok, I have solved the problem by adding delim_0 ": " and delim_1 ": " in a new .ist file.

**Comment by maieul** [comment]
perfect (that is not related to reledmac…)
