### ISSUE TITLE
Small edits suggested for the documentation of 2.26.0

### ISSUE THREAD

**Issue by kfeuerherm** [maieul/ledmac#718]
As discussed off-list, with additions:

Change to header: 9.10 Adding annotations to line numbers

Footnote 19 should read: "dealing with such patterns"

Slightly farther: "To resolve this issue, _reledmac_ allows you to annotate to a line of verse number:" --> "To resolve this issue, _reledmac_ allows you to annotate line numbers using the following command:"

Insert "n": "If two or more annotations are called before a \edtext" --> "If two or more annotations are called before an \edtext"

Insert "n": "If an annotation is called within a \edtext" --> "If an annotation is called within an \edtext"

In the section of code which follows, "\lienumannotation{B}" --> "\linenumannotation{B}"

Change to header: 9.10.1 Modifying the annotation associated with a specific note

In the next line, the subject of the second sentence is missing: "Thee \linenum (6.2.5 p. 27) macro changes the line number passed to a note. does the"

In 9.10.2, the first word "annotationposition" doesn't seem to belong there?

The third bullet note following this has an empty "⟨⟩"

The following statement is correct, but not typographically clear: "In each of these three commands, ⟨v⟩ can be **after** or **before** the line number"; maybe better "In each of these three commands, ⟨v⟩ can be **after** or **before** to indicate position with regards to the original line number" or the like.

In 9.10.3, on two occasions "(11 p. 59" is missing the right parenthesis.

**Comment by maieul** [comment]
Thanks, corrected.

**Comment by kfeuerherm** [comment]
Do you want to quickly check 2937 ("line” seems to appear twice?) To resolve this issue, \macpackage\ allows you to annotate line line numbers using the following command

and

2949 which has “na” for “an”?
