### ISSUE TITLE
\Xendtextbeforenotes appears to be broken in 2.26.0?

### ISSUE THREAD

**Issue by kfeuerherm** [maieul/ledmac#719]
The following MWE works fine... until the line with \Xendtextbeforenotes is commented out (log file checked: "Package: reledmac 2017/11/11 v2.26.0 typesetting critical editions"). Then we get undefined control sequence:

`% !TEX TS-program = xelatexmk
 \documentclass{memoir}
	
\usepackage{libertine}
\usepackage{reledmac}
	\Xarrangement[A]{paragraph}		% format all A-series critical notes into a single paragraph
	\Xlemmaseparator[A]{:}			% replace ] with : in critical notes
	\Xendlemmaseparator[A]{:}
	\setlength{\linenumsep}{0.5em}	% set space between line number and margin
	\sublinenumberstyle{alph}		% subline numbers 'a', 'b', etc.
	\renewcommand{\printnpnum}[1]{}
%	\Xendtextbeforenotes{\vskip 6pt\footnoterule}
\usepackage{reledpar} 
	\setlength{\Lcolwidth}{0.49\textwidth}
	\setlength{\Rcolwidth}{0.49\textwidth}
	\firstlinenum*{1}				% start line numbering with first line
	\linenumincrement*{1}			% number every line
	\setstanzaindents{1,0}
	\setlength{\stanzaindentbase}{1em}
	\setcounter{stanzaindentsrepetition}{1}
	\AtBeginPairs{\sloppy}

\begin{document}

\mainmatter
\chapter{Edition}

\begin{pairs}
\begin{Leftside} 
\beginnumbering
\begin{astanza}
Line one&
Line \edtext{two}{\Aendnote{This should be `three'}}\&
\end{astanza}
\endnumbering
\end{Leftside}

\begin{Rightside} 
\beginnumbering
\autopar
\noindent Translation of lines one and two\pend
\endnumbering
\end{Rightside}
\end{pairs}

\Columns

\doendnotesbysection{A}

\end{document}`

**Comment by maieul** [comment]
For historical reason, it is `\Xendtxtbeforenotes` , text is abbreviated in txt.

**Comment by maieul** [comment]
So, I have closed this issue, and I will publish your english correction right now

**Comment by kfeuerherm** [comment]
Understood.

**Comment by kfeuerherm** [comment]
Ah, ok. Apologies. I was pretty sure I’d copied it from the documentation but I must have screwed it up. Thanks.

**Comment by maieul** [comment]
Dont' worryLe mardi 14 novembre 2017 à 15:25 +0000, Karljürgen Feuerherm a écrit :
