### ISSUE TITLE
Failed biblatex lookup causes invalid critical endnote

### ISSUE THREAD

**Issue by kfeuerherm** [maieul/ledmac#720]
For some reason which is not clear to me, a biblatex \textcite command which looks for an item which does not exist in the .bib file has a strange side-effect: the command \doendnotesbysection{A} generates an endnote even though there were no \edtext commands. When I replace the \textcite with an entry which exists, the problem goes away. But it is useful to have citations like this so one can add the bibliographic items to the .bib file later.

I have provided an example below.

% !TEX TS-program = xelatexmk
 \documentclass{memoir}
	
\usepackage{libertine}

\usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @inbook{Bouzon1995,
        Author = {E. Bouzon},
        Booksubtitle = {Mélanges von Soden},
        Booktitle = {Vom alten Orient zum alten Testament},
        Editor = {Manfried Dietrich and Oswald Loretz},
        Hyphenation = {german},
        Location = {Neukirchen},
        Number = {240},
        Pages = {11--30},
        Publisher = {Neukirchener Verlag},
        Series = {Alter Orient und altes Testament},
        Shorthand = {\textsc{aoat}~240:2},
        Shorthandsort = {aoat 240:2},
        Shorttitle = {\emph{ṣimdat-šarrim}},
        Title = {Die soziale Bedeutung des \emph{ṣimdat-šarrim}-Aktes nach den Kaufverträgen der Rim--Sin-Zeit},
        Volume = {2},
        Year = {1995}}
    }
    \end{filecontents}

\usepackage[%
	notes,compresspages,% 321--328 --> 321--28
	isbn=false,			% don't need that in the body of the work; bibliography ok
	backref=true,
	block=space,		% biblatex; add space between bibliography blocks
%	refsegment=chapter,	% biblatex; start new reference segment at specified division
	autopunct=true,		% biblatex; after citations scan ahead for punctuation
%	firstinits,
	backend=biber,
	language=british,
	hyperref=true
	]{biblatex-chicago}

	\addbibresource{\jobname.bib}

\usepackage{hyperref,morewrites}

\usepackage{reledmac}
	\Xarrangement[A]{paragraph}		% format all A-series critical notes into a single paragraph
	\Xlemmaseparator[A]{:}			% replace ] with : in critical notes
	\Xendlemmaseparator[A]{:}
	\setlength{\linenumsep}{0.5em}	% set space between line number and margin
	\sublinenumberstyle{alph}		% subline numbers 'a', 'b', etc.
	\Xendbhooknote{\vskip 6pt\footnoterule}
	\renewcommand{\printnpnum}[1]{}
	\Xendparagraph[A]
%	\Xendafternote[A]{1em plus.4em minus.4em}
	\Xendtxtbeforenotes{\vskip 6pt\footnoterule}
	\newcommand{\nochange}[1]{#1}
	\Xwraplinenumannotation{\nochange}
\usepackage{reledpar} 
	\setlength{\Lcolwidth}{0.49\textwidth}
	\setlength{\Rcolwidth}{0.49\textwidth} 
	\firstlinenum*{1}
	\linenumincrement*{1}
	\setstanzaindents{1,0}
	\setlength{\stanzaindentbase}{1em}
	\setcounter{stanzaindentsrepetition}{1}
	\AtBeginPairs{\sloppy}

\newcommand{\smn}[1]{{\texorpdfstring{\sffamily\addfontfeature{LetterSpace=10.0}#1}{#1}}}	% Sumerian
\newcommand{\akk}[1]{{\texorpdfstring{\sffamily\textit{#1}}{#1}}}							% Akkadian
\newcommand{\cunchar}[1]{{\texorpdfstring{\textsc{#1}}{#1}}}
\newcommand{\D}{{\sffamily\textsuperscript{d}}}
\newcommand{\dtm}[1]{{\sffamily\textsuperscript{#1}}}

\newcommand{\qm}{\textsuperscript{?}}
\newcommand{\xm}{\textsuperscript{!}}
\newcommand{\gap}{[\dots]}

\begin{document}
\appendix
\chapter{Text Editions}\label{app:editions}

Line of text

\begin{pairs}
\begin{Leftside}
\beginnumbering
\begin{astanza}
\skipnumbering Copy A (Case) obverse\&
\end{astanza}
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\begin{astanza}
\skipnumbering Copy B (Tablet) obverse\&
\end{astanza}
\endnumbering
\end{Rightside}
\end{pairs}
\Columns

\begin{pairs}
\OnehalfSpacing
\begin{Leftside}
\beginnumbering
\begin{astanza}
\skipnumbering\&
\end{astanza}
\begin{astanza}
\skipnumbering\&
\end{astanza}
\begin{astanza}
\skipnumbering\&
\end{astanza}
\begin{astanza}
\skipnumbering[\dots]\&
\end{astanza}
\begin{astanza}
\linenumannotation{′}\smn{[ki] }\dtm{d+}\cunchar{en-zu}--\akk{iš-me-a-ni}\&
\end{astanza}
\begin{astanza}
\linenumannotation{′}\dtm{I}\akk{iš}₈+\akk{tár}--\akk{ì-lí}\&
\end{astanza}
\begin{astanza}
\linenumannotation{′}\smn{in-ši-sa₁₀}\&
\end{astanza}
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\begin{astanza}
\smn{1 sar igi-6-gál é-kislah}\&
\end{astanza}
\begin{astanza}
\smn{da é }\dtm{d+}\cunchar{en-zu}--\akk{be-el}--\akk{ì-lí}\&
\end{astanza}
\begin{astanza}
\smn{ù }\dtm{d+}\cunchar{en-zu}--\akk{še-mi}\&
\end{astanza}
\begin{astanza}
\smn{é }\dtm{d+}\cunchar{en-zu}--\akk{iš-me-a-ni}\&
\end{astanza}
\begin{astanza}
\smn{ ki }\dtm{d+}\cunchar{en-zu}--\akk{iš-me-‹a›-ni}\smn{\ dumu }\dtm{d+}\cunchar{en-zu}--\akk{a-bi}\&
\end{astanza}
\begin{astanza}
\dtm{I}\akk{iš}₈+\akk{tár}--\smn{dingir}\&
\end{astanza}
\begin{astanza}
\smn{in-ši-sa₁₀}\&
\end{astanza}
\endnumbering
\end{Rightside}
\end{pairs}
\Columns
\doendnotesbysection{A}

(\textcite{MSL:1})

\begin{pairs}
\begin{Leftside}
\beginnumbering
\begin{astanza}
\skipnumbering {VS:13} (Sippar)\&
\end{astanza}
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\begin{astanza}
\skipnumbering {VS:13} (`Larsa')\&
\end{astanza}
\endnumbering
\end{Rightside}
\end{pairs}
\Columns
\doendnotesbysection{A}

\begin{pairs}
\OnehalfSpacing
\begin{Leftside}
\beginnumbering
\setline{12}
\begin{astanza}
\smn{u₄-kúr-še tukumbi}&
\smn{é }\akk{ba-aq-ri ir-ta-ši}&
\akk{a-lum ù ši-bu-tum}&
\akk{a-lum ù ši-bu-tum}&
\akk{i-ta-na-ap-pa-lu}\&
\end{astanza}
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\begin{astanza}
\smn{[u₄-kúr]-še }\dtm{giš}\smn{kiri₆ inim-gál-la}&
\smn{ba-an-tuk}&
\smn{inim-gál-la }\dtm{giš}\smn{kiri₆-ke₄}&
\smn{ba-ni-ib-gi₄-gi₄}\&
\end{astanza}
\endnumbering
\end{Rightside}
\end{pairs}
\Columns
\doendnotesbysection{A}

\end{document}

**Comment by maieul** [comment]
I am sorry, but I did'nt get this problem with this MWE. See the enclosed result. 
[issue720.pdf](https://github.com/maieul/ledmac/files/1484875/issue720.pdf)

**Comment by kfeuerherm** [comment]
Yes you did. Look at the bottom of the page. There should be no note there.

**Comment by kfeuerherm** [comment]
I guess it is confusing. But in my bigger book the note appeared right under the text as a critical endnote where there should not be one. Only in the MWE is it at the bottom of the page

**Comment by maieul** [comment]
That is not a endnotes, (if I suppress \doendnotesbysection, I don't get it anymore).

I will look on it tomorrow.

**Comment by kfeuerherm** [comment]
Je viens d’essayer de réproduire le problème dans ma grosse fiche, mais sans succès! C’est certainement une question de détails….

Ce qui arrivait, apparament, c’est que le “footnote” de la citation a été capturée par le \doendnotesbysection, ce qui ne devrait pas arriver. Si je peux réproduire encore je vous enverrai un PDF. C’est bien difficile à montrer avec le MWE… :(

Mais puisque je sais maintenant pourquoi cela arrive, je n’ai plus besoin de m’inquieter, alors cela ne presse pas.

**Comment by maieul** [comment]
si je supprime les doendnotesbysection sur votre document, il y a tjr
le problème...Le samedi 18 novembre 2017 à 18:16 +0000, Karljürgen Feuerherm a
écrit :

**Comment by kfeuerherm** [comment]
tjr?

Mais j’en ai besoin parce-qu’il y a d’autres notes plus tard, et la les choses apparraissent dans la mauvaise section… mauvaise synchronisation. Enfin, c’est ce que je trouvais auparavant…. Je peux toujours essayer de nouveau…

**Comment by kfeuerherm** [comment]
Very strange and now I am confused. Later in my file I have:

\subsubsection{Obverse}
\begin{pairs}
\begin{Leftside}
\beginnumbering
\begin{astanza}
Stuff \edtext{TEXT}{\Aendnote{Some note}}\&
\end{astanza}
\pausenumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\autopar
\noindent\textsubscript{n--m~}TEXT\pend
\pausenumbering
\end{Rightside}
\end{pairs}
\Columns
\doendnotesbysection{A}

And I don’t get an endnote at all for “Some note”…. I must be doing something stupid….

**Comment by maieul** [comment]
désolé
tjr = toujours.

Donc le problème n'est pas lié aux notesbysection.

Je regarderai demain, promis. Le samedi 18 novembre 2017 à 18:20 +0000, Karljürgen Feuerherm a
écrit :

**Comment by kfeuerherm** [comment]
Pas de problème. Entre temps, je me suis rendu compte que peut-être est-ce parce que j’ai deux \doendnotesbysection dans une section…. Je suis en train d’étudier cela….

A demain :) Bonne nuit.

**Comment by kfeuerherm** [comment]
J’ai fait encore des essais, et je pense à la fin que vous aviez raison, il n’y pas vraiment de problème.

Ce qui paraît avoir arrivé, c’est que d’un côte, le \cite/\textcite avait crée un “footnote” (autre problème n’ayant rien à voir avec reledmac), mais en même temps, mon texte se trouvait à la fin de la page. Donc, le “footnote” avait l’apparence d’un “endnote” créé par reledmac. Je me suis trompé parce qu'en plus de cela, le numéro de footnote était identique avec un des numéros de ligne de mon texte! Donc coïncidence malheureuse, il me semble….

J’ai aussi réussi à faire apparaître mes “endnotes” plus loin. Donc, pour le moment, “I’m back in business”.

Désolé de vous avoir dérangé avec ceci.

**Comment by maieul** [comment]
donc on peut clore?

**Comment by kfeuerherm** [comment]
Oui, je pense bien. Merci
