### ISSUE TITLE
Line number annotation does not reset properly in critical notes

### ISSUE THREAD

**Issue by kfeuerherm** [maieul/ledmac#728]
Issue can be opened in English or in French (I prefer in French). Please fill this form.

Selon la documentation, "An annotation is associated with a line of verse. It is reset with each new line of verse". En effet, dans la marge on ne voie l'annotation qu'une seule fois. Mais dans les notes, the "a" de mon example se répète à chaque invocation de "edtext". Donc "13a", c'est bien correcte. Mais "15a", "16a", "17a", "20a", non.

In English: line 13 has the annotation "a", which appears correctly in the margin and the critical note associated with that line. The "a" does not reoccur in the margin after that line/astanza, but it does continue in the critical notes for other lines, even though it should not.

# Version of reledmac / reledpar: 2.26.0a/v2.21.0

# Does the problem happen recently? Precise in which version the problem didn't exist.
I do not know because this is the first time I have multiple critical notes for a document.

# Does the problem happen only when combining with some packages?
It is not caused by other packages; the only package in this MWE is `libertine` and even without it we have the problem.

# Does the problem happens both in parallel typesetting and normal typesetting?
Yes, it is not specific to reledpar.

# Minimal Working Example

Please provide a [MWE](http://minimalbeispiel.de/mini-en.html). 

```` 
 \documentclass{memoir}
	
\usepackage{libertine}
\usepackage{reledmac}
	\Xarrangement[A]{paragraph}		% format all A-series critical notes into a single paragraph
	\Xlemmaseparator[A]{:}			% replace ] with : in critical notes
	\Xendlemmaseparator[A]{:}
	\setlength{\linenumsep}{0.5em}	% set space between line number and margin
	\sublinenumberstyle{alph}		% subline numbers 'a', 'b', etc.
	\renewcommand{\printnpnum}[1]{}
	\Xendtxtbeforenotes{\vskip 6pt\footnoterule}
\usepackage{reledpar} 
	\setlength{\Lcolwidth}{0.49\textwidth}
	\setlength{\Rcolwidth}{0.49\textwidth}
	\firstlinenum*{1}				% start line numbering with first line
	\linenumincrement*{1}			% number every line
	\setstanzaindents{1,0}
	\setlength{\stanzaindentbase}{1em}
	\setcounter{stanzaindentsrepetition}{1}
	\AtBeginPairs{\sloppy}
\newcommand{\blankline}{\begin{stanza}
	\skipnumbering\quad{\footnotesize‹space›}\&
	\end{stanza}
}
\newcommand{\blankright}{\noindent\skipnumbering{}\pend}
\newcommand{\RE}{(\textsc{re}:)~}
\newcommand{\ruled}{%
\makebox{\rule[-0.3\baselineskip]{\Lcolwidth}{0.4pt}}\hspace{-\Lcolwidth}%
}
\newcommand{\smn}[1]{#1}
\newcommand{\smg}[1]{\textsc{#1}}
\newcommand{\nml}[1]{{\sffamily #1}}
\newcommand{\akk}[1]{\emph{#1}}
\newcommand{\D}{\textsuperscript{d}}
\newcommand{\dtm}[1]{\textsuperscript{#1}}
\newcommand{\tl}{/}
\newcommand{\tr}{\textbackslash}
\newcommand{\bl}{√}
\newcommand{\br}{∫}
\newcommand{\lbb}{\textbf{[}}
\newcommand{\rbb}{\textbf{]}}
\newcommand{\Bouz}{\textsc{bouz.}}
\newcommand{\Tten}{\textsc{tcl~10}}
\newcommand{\Awu}{Abu--waqar}
\newcommand{\RS}{Rim-Sîn}
\newcommand{\qm}{\textsuperscript{?}}

\begin{document}
\chapter{Appendix}	
\section{Editions}
Comments here

\subsubsection{Case reverse}
%\begin{pairs}
\OnehalfSpacing
%\begin{Leftside}
\sffamily
\beginnumbering
\begin{astanza}
\setline{13}%
\linenumannotation{a}\edtext{\smn{[igi] \tl }\akk{a-bu--wa\rbb-\tl qar}\rbb}{\Aendnote{\Bouz: l.~14, ending here}}\smn{\  \tl dumu] \tl }\akk{i\rbb-\tl din}\nml{]}\smn{--[èr-ra]}\&
\end{astanza}
\begin{astanza}
\smn{igi }\akk{u-bar}\nml{--}\D\smn{utu dumu }\akk{ì-lí}\nml{--}\akk{iš-me-a-ni}\&
\end{astanza}
\begin{astanza}
\smn{igi }\edtext{\dtm{d+}\smg{en-zu}\akk{-ma}\nml{--}dingir}{\Aendnote{\Bouz: \D\smg{en.zu}\smg{-ma-an}}}\smn{\ dumu }\akk{a-\bl ḫu-šu-nu}\&
\end{astanza}
\begin{astanza}
\smn{igi dingir-}\akk{šu}\nml{--}\akk{na-ṣir}\smn{\ dumu }\akk{u-bar}\nml{--}\edtext{\D\smn{dumu-zi}}{\Aendnote{\smn{an-i-zi}\qm}}\&
\end{astanza}
\begin{astanza}
\smn{igi }\edtext{\akk{ḫa-zi-ru-um}}{\Aendnote{\Bouz\ l.~18 ends here}}\smn{\ dumu }\akk{e-ta-am\rbb-ši}\nml{--}\smg{dingir}\&
\end{astanza}
\begin{astanza}
\smn{igi }\akk{ti-iz-qá-ru-um}\smn{\ dumu }\akk{ì-lí}\nml{--}\akk{i-din-nam}\&
\end{astanza}
\begin{astanza}
\smn{igi }\tl \akk{še}\nml{]}\akk{-ru-um}\nml{--}\akk{ì-lí}\smn{\ dumu }\dtm{d+}\smg{en-zu}\nml{--}\akk{i-ri-ba-am}\&
\end{astanza}
\begin{astanza}
\smn{igi }\edtext{\smg{an\rbb-na}\nml{--}\akk{i-mi-it-ti}}{\Aendnote{\Bouz: \D\smg{NA}\smn{-i-mi-it-ti}}}\smn{\ dumu dingir}\akk{-šu}\smn{--illat-}\akk{sú}]\&
\end{astanza}
\blankline
\begin{astanza}
\smn{kišib lú-in[i]m-ma-ab-bi- me-eš}\&
\end{astanza}
\begin{astanza}
\smn{iti gan-gan-è}\&
\end{astanza}
\begin{astanza}
\smn{mu é--}\dtm{d+}\smn{en-ki}\smn{ uri}\dtm{ki}\smn{-ma ba-dù}&
\smn{ù\rbb  \tl é nin]--é--nim-ma}&
\smn{šà é--}\D\smn{n\tl in-mar}\dtm{ki}\smn{\ mu-un-dù-a}\&
\end{astanza}
\endnumbering
%\end{Leftside}
%\begin{Rightside}
%\beginnumbering
%\autopar
%\noindent\textsubscript{13a--20~}[Before] \Awu\ s[on] of \nml{Id[din–Er]ra};\pend
%\noindent before \nml{Ubār--Šamaš} son of \nml{Ilī--išmeanni};\pend
%\noindent before \nml{Sînma--dingir} son of \nml{Aḫūšunu};\pend
%\noindent before \nml{Ilšu--nāṣir} son of \nml{Ubār--Dumuzi};\pend
%\noindent before \nml{Ḫāzirum} son of \nml{Etamši--}dingir;\pend
%\noindent before \nml{Tizqārum} son of \nml{Ilī--iddinam};\pend
%\noindent before \nml{Šērum--ilī} son of \nml{Sîn--irībam};\pend
%\noindent before anna\nml{--imittī} son of \nml{Ilšu--tillassu};\pend
%\blankright
%\noindent\textsubscript{21~}Those witnesses (have applied) seals.\pend
%\noindent\textsubscript{22~}Month ix,\pend
%\noindent\textsubscript{23--25~}year \RS~8.\pend
%\endnumbering
%\end{Rightside}
%\end{pairs}
%\Columns
\doendnotesbysection{A}\leavevmode

\end{document}
````

**Comment by maieul** [comment]
Ok, but your MWE is not MWE (as the problem happens also in not // mode, you should provide a not // example)

**Comment by kfeuerherm** [comment]
I did. I commented out the parts which were parallel. That way you can see it both ways.

**Comment by maieul** [comment]
Ok, but in this case, really, delete all thing who are not need to see the problem. 

Here  a REAL MWe

https://github.com/maieul/ledmac/blob/461c38951d0ed609ff0dfb06deee52d871c07361/issue728.tex

**Comment by kfeuerherm** [comment]
For my taste maybe just a bit too minimal, but ok, I understand for the future.

**Comment by maieul** [comment]
The Minimal is for the explanation of the problem, not for your taste
;-)

**Comment by kfeuerherm** [comment]
Yes, yes… I would just put maybe full word, easier to read, that’s all :)

**Comment by maieul** [comment]
ok, for this point ;-)

**Comment by maieul** [comment]
109a6043 make the problem... I have to found a way.

(It was a last minute change before releasing)

**Comment by kfeuerherm** [comment]
BTW Your mark-up in the github to explain to users what they should do is very good. May I suggest a change to one item?

Donc: “Does the problem happen… didn’t exist” —> “If this is a newly introduced problem, please indicate the last working version of the package(s)” ou bien “Is this a recently introduced problem? If so, please specify in which version of the package(s) the problem did not occur"

**Comment by kfeuerherm** [comment]
Faute de mieux, je pourrais toujours insérer des \linenumannotation{} je suppose? mais une bonne solution serait bien :)

**Comment by maieul** [comment]
Please try branch issue728

**Comment by kfeuerherm** [comment]
Tested on my large file, which has several instances of \linenumannotation, it works fine now.

**Comment by maieul** [comment]
Thanks, I will publish it right now. (I have added you correction in
the issues form)

**Comment by kfeuerherm** [comment]
Thanks once again
