### ISSUE TITLE
\Xgroupbyline and unwanted blank lines

### ISSUE THREAD

**Issue by gianlucapignalberi** [maieul/ledmac#731]
Issue can be opened in English or in French (I prefer in French). Please fill this form.

# Version of reledmac / reledpar
2.23.0 (but tested with 2.26.1 too)

# If this is a newly introduced problem, please indicate the last working version of the package(s)
# Does the problem happen only when combining with some packages?
No

# Does the problem happens both in parallel typesetting and normal typesetting?
Just tried normal typesetting

# Description of the problem
Gouped by line critical notes may end too tight to right margin. In this case, the document shows an unwanted blank line between these notes and the next line's.

# Minimal Working Example

Please provide a [MWE](http://minimalbeispiel.de/mini-en.html). 
In  case where the problem happens both in parallel typesetting and normal typesetting, please make your MWE in normal typesetting (because your MWE must be _Minimal_). 

```` 
\documentclass{article}
\usepackage{reledmac}
\Xgroupbyline[A]
\begin{document}

\beginnumbering
\pstart
A \edtext{Afootnote}{\Afootnote{X}} \edtext{}{\Afootnote{x}} \edtext{}{\Afootnote{Critical notes too tight to the end of line show a blank line}}
\pend
\pstart
A \edtext{Afootnote}{\Afootnote{X}} \edtext{}{\Afootnote{x}} \edtext{}{\Afootnote{Critical notes not too tight don't}}
\pend
\pstart
A \edtext{Afootnote}{\Afootnote{X}} \edtext{}{\Afootnote{x}} \edtext{}{\Afootnote{Critical notes too tight to the end of line show a blank line}}
\pend
\endnumbering

\end{document}
````

**Comment by maieul** [comment]
Please try branch issue731, which corrects tickets #731 #730 and #729

**Comment by gianlucapignalberi** [comment]
While it works on the MWEs, it hangs the compilation of the document I'm working on and doesn't issue a pdf (I'm working with XeLaTeX which perfectly compiles MWEs), while 2.26.1 does. I'll double check it tomorrow.
