### ISSUE TITLE
Reledpar edtext and endnote combination crashes when on rightside only

### ISSUE THREAD

**Issue by kfeuerherm** [maieul/ledmac#733]
<img width="515" alt="screen shot 2017-12-15 at 15 12 44" src="https://user-images.githubusercontent.com/11524091/34059261-3dea55f6-e1ac-11e7-99d9-8bfdc3eca157.png">
Issue can be opened in English or in French (I prefer in French). Please fill this form.
Please open one issue by problem, and not a global issue for multiple problems. 

# Version of reledmac / reledpar
reledmac 2017/11/26 v2.26.1
reledpar 2017/11/11 v2.21.0

# If this is a newly introduced problem, please indicate the last working version of the package(s)
Pas connu--vu pour la première fois

# Does the problem happen only when combining with some packages?
Reledpar-specific problem, unrelated to other packages

# Does the problem happens both in parallel typesetting and normal typesetting?
Can only happen in parallel (reledpar) typesetting, with "rightside" texts.

# Description of the problem

Quand on a un \ edtext {...} {\ Aendnote {...}} dans un texte dit "rightside" lorsqu'il n'y a pas de commande similaire dans le texte de gauche provoque "undefined control sequence". Quand il y a une commande similaire dans le texte de gauche, aucun problème. Le MWE fonctionne comme écrit; mais si nous supprimons le \ edtext et son deuxième argument du texte de gauche, nous obtenons le problème démontré dans le PNG.

Placing an \edtext{...}{\Aendnote{...}} in a rightside text when there is no similar command in the leftside text causes "undefined control sequence". When there is a similar command on the leftside, it compiles just fine. The MWE works as written; but if we remove the \edtext and its second argument from the leftside, we get the problem shown in the attached PNG.

# Minimal Working Example

Please provide a [MWE](http://minimalbeispiel.de/mini-en.html). 
In  case where the problem happens both in parallel typesetting and normal typesetting, please make your MWE in normal typesetting (because your MWE must be _Minimal_). 

```` 
% !TEX TS-program = xelatexmk
\documentclass{memoir}

\usepackage{reledmac}
	\Xendtxtbeforenotes{\vskip 6pt\footnoterule}

\usepackage{reledpar} 
	\setstanzaindents{1,0}
	\setcounter{stanzaindentsrepetition}{1}

\begin{document}

\begin{pairs}
    \begin{Leftside}
        \beginnumbering
            \begin{astanza}
                \edtext{Left}{\Aendnote{<left endnote>}} % remove this edtext and endnote
                paragraph\&
            \end{astanza}
        \endnumbering
    \end{Leftside}
    \begin{Rightside}
        \beginnumbe
<img width="515" alt="screen shot 2017-12-15 at 15 12 44" src="https://user-images.githubusercontent.com/11524091/34059224-1d25eefc-e1ac-11e7-94f5-207b4a6fc87b.png">
ring
        \autopar
        And \edtext{right}{\Aendnote{<right endnote>}} paragraph.\pend
        \endnumbering
    \end{Rightside}

\end{pairs} 
\Columns
\doendnotesbysection{A}

\end{document}
````

**Comment by maieul** [comment]
Please try branch issue733 or issue 732, which solve both the problem #733 and #732

**Comment by kfeuerherm** [comment]
Thank-you. I will be happy to try this tomorrow, probably in the morning.

K

**Comment by kfeuerherm** [comment]
Cela me paraît marcher comme il faut. J’ai même essayé une annotation de la colonne droite, différente de la colonne gauche, et sans problème aussi (ce que je ne pouvais pas faire auparavant, me semble-t-il).

Merci!
