### ISSUE TITLE
The second compilation hangs (\Xgroupbyline)

### ISSUE THREAD

**Issue by gianlucapignalberi** [maieul/ledmac#736]
Issue can be opened in English or in French (I prefer in French). Please fill this form.
Please open one issue by problem, and not a global issue for multiple problems. 

# Version of reledmac / reledpar
2.26.2-dev

# If this is a newly introduced problem, please indicate the last working version of the package(s)
2.26.1

# Does the problem happen only when combining with some packages?
No

# Does the problem happens both in parallel typesetting and normal typesetting?
Only tried normal

# Description of the problem
While the first compilation successfully ends, the second one hangs, apparently when in a (X-grouped-by-line) critical note the content of \edtext{} is longer than one line. Shortening the contents of the third \edtext in the mwe "overtakes" the bug.

# Minimal Working Example

Please provide a [MWE](http://minimalbeispiel.de/mini-en.html). 
In  case where the problem happens both in parallel typesetting and normal typesetting, please make your MWE in normal typesetting (because your MWE must be _Minimal_). 

```` 
\documentclass{article}
\usepackage{reledmac}
%\Xgroupbyline[A]
\Xlinerangeseparator{\textnormal{-}}
\begin{document}

\beginnumbering
\pstart
A \edtext{Afootnote}{\Afootnote{Æ}}. \edtext{Another Afootnote}{\lemma{}\Afootnote[nosep]{s}}. A third Afootnote, \edtext{this time, the lemma spans two lines of text}{\Afootnote{Where is it?}}.
\pend
\endnumbering

\end{document}
````

**Comment by maieul** [comment]
Please try branch issue736, which should solve #736, #735 and #734.

Please also, when openning a new ticker about a version in devellopement, precise it.

**Comment by gianlucapignalberi** [comment]
You're great: it works.
Sorry for nov writing "dev" after 2.26.2.

**Comment by maieul** [comment]
nice,

I will publish it on CTAN in few days
Le lundi 18 décembre 2017 à 13:19 -0800, gianlucapignalberi a écrit :

**Comment by maieul** [comment]
Please let me know when the Sermon Dolbeau will be published, are add them to https://www.zotero.org/groups/209265/critical_editions_typeset_with_edmac_ledmac_and_eledmac

**Comment by gianlucapignalberi** [comment]
I'll surely let you know along with all the related data. Thank you again for your effort. I'm sure Dolbeau will be happy about the result.
