### ISSUE TITLE
Problems after recent update

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#738]
Hey Maieul,

I did an update from reledmac 2.18.1 to 2.21.1 today. A file that was working before throws errors now. I put the reports here, maybe you see what's going wrong. I won't have the time to track the errors down now, this is just to let you know there are problems. I will be able to track them down early next year.

```
! Undefined control sequence.
\swnoexpands ...e \RenewExpandableDocumentCommand 
                                                  {\edindex }{om}{}\ifdefine...
l.993 \@sw{ᾧ}{1}{}
```

```
! Argument of \edindex has an extra }.
<inserted text> 
                \par 
l.993 \@sw{ᾧ}{1}{}
```

```
Runaway argument?
! Paragraph ended before \edindex was complete.
<to be read again> 
                   \par 
l.993 \@sw{ᾧ}{1}{}
```

```
! Extra }, or forgotten \endgroup.
<recently read> }
                 
l.993 \@sw{ᾧ}{1}{}
```

```
! Missing } inserted.
<inserted text> 
                }
l.191 \beginnumbering
```

Maybe it is all the same problem anyway (sameword and enconding)? Using pdflatex with utf8 ...

**Comment by maieul** [comment]
without mwe, it would be hard for me to see the problem.

What you can try is to do a git bisect.

But in general, it is better, when using sameword, to use native utf8
engine, as they don't use active character, which are calamity

**Comment by maieul** [comment]
Hi, could I have a MWE for this issue?

**Comment by baem2** [comment]
My congratulations for your DANTE prize!

A MWE. This file runs through fine with pdflatex + reledmac 2.18:

```
\listfiles

\documentclass{report}
\usepackage[LGR,T1]{fontenc}

\usepackage[greek]{babel}
\usepackage{reledmac}

\usepackage[utf8]{inputenc}

\begin{document}
\beginnumbering
\autopar

\sameword{ᾧ}

\endnumbering
\end{document}
```

With the recent 2.26.3 I get these errors (deleting all auxiliary files first):

****************************************************************************

! Undefined control sequence.
\swnoexpands ...e \RenewExpandableDocumentCommand 
                                                  {\edindex }{om}{}\ifdefine...
l.15 \sameword{ᾧ}
                   
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Argument of \edindex has an extra }.
<inserted text> 
                \par 
l.15 \sameword{ᾧ}
                   
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

Runaway argument?
! Paragraph ended before \edindex was complete.
<to be read again> 
                   \par 
l.15 \sameword{ᾧ}
                   
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

! Undefined control sequence.
\swnoexpands ...x \RenewExpandableDocumentCommand 
                                                  {\index }{om}{}\fi \let \s...
l.15 \sameword{ᾧ}
                   
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Argument of \@index has an extra }.
<inserted text> 
                \par 
l.15 \sameword{ᾧ}
                   
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

Runaway argument?
! Paragraph ended before \@index was complete.
<to be read again> 
                   \par 
l.15 \sameword{ᾧ}
                   
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

! Extra }, or forgotten \endgroup.
<recently read> }
                 
l.15 \sameword{ᾧ}
                   
I've deleted a group-closing symbol because it seems to be
spurious, as in `$x}$'. But perhaps the } is legitimate and
you forgot something else, as in `\hbox{$x}'. In such cases
the way to recover is to insert both the forgotten and the
deleted material, e.g., by typing `I$}'.

! Missing } inserted.
<inserted text> 
                }
l.17 \endnumbering
                  
I've inserted something that you may have forgotten.
(See the <inserted text> above.)
With luck, this will get me unwedged. But if you
really didn't forget anything, try typing `2' now; then
my insertion and my current dilemma will both disappear.

**Comment by maieul** [comment]
Thanks, I will look on.

**Comment by maieul** [comment]
I try with the latest (public) version of reledmac (v2.26.3) with four run of pdflatex -> I didn't get any error.  I think you have an older version of `xparse` package, which provokes this error.

Here are my filelist values

 ```
*File List*
  report.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
 fontenc.sty
  lgrenc.def    2015/12/07 v0.13.1 LGR Greek font encoding definitions
greek-fontenc.def    2015/08/04 v0.13 Common Greek font encoding definitions
   t1enc.def    2017/04/05 v2.0i Standard LaTeX file
   babel.sty    2018/01/04 3.16 The Babel package
   greek.ldf    2016/09/07 v1.9g Greek support for the babel system
reledmac.sty    2018/01/06 v2.26.3 typesetting critical editions
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
   xargs.sty    2008/03/22 v1.1  extended macro definitions  (mpg)
  xparse.sty    2017/12/16 L3 Experimental document command parser
   expl3.sty    2017/12/16 L3 programming layer (loader) 
expl3-code.tex    2017/12/16 L3 programming layer 
l3pdfmode.def    2017/03/18 v L3 Experimental driver: PDF mode
etoolbox.sty    2017/11/22 v2.5 e-TeX tools for LaTeX (JAW)
  suffix.sty    2006/07/15 1.5a Variant command support
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
ragged2e.sty    2009/05/21 v2.1 ragged2e Package (MS)
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
inputenc.sty    2015/03/17 v1.2c Input encoding file
    utf8.def    2017/01/28 v1.1t UTF-8 support for inputenc
   t1enc.dfu    2017/01/28 v1.1t UTF-8 support for inputenc
  ot1enc.dfu    2017/01/28 v1.1t UTF-8 support for inputenc
  omsenc.dfu    2017/01/28 v1.1t UTF-8 support for inputenc
  lgrenc.dfu    2015/08/05 1.6 UTF-8 support for Greek
  lgrcmr.fd    2017/07/29 v1.2 Greek European Computer Regular
    toto.1
    toto.eledsec1
 ***********

```

**Comment by baem2** [comment]
Yup, that's possible. Then please add a version check on loading xparse.

**Comment by maieul** [comment]
could you try with upgrading your version before? To be certain that is the problem.

**Comment by baem2** [comment]
Will do.

**Comment by maieul** [comment]
(I have also to read about how to test package version number)

**Comment by baem2** [comment]
After updating xparse and l3kernel (required by xparse), it is working fine.

Testing the package version:
```
\RequirePackage[options]{name}[version]
```

**Comment by maieul** [comment]
Its only add a warning, not an error message, and not a so much explicit message. But that does not matter, I have found a code to real make an error if using older version of package. Now, I have to found the history of xparse to know the good version to use.

**Comment by maieul** [comment]
Done on branch issue738. I won't do a special release for this feature. But I note than in the future, I should test versions number when using new feature of package.

By the way, you have a not normal TeXLive. The  `\RenewExpandableDocumentCommand`  was added in 2017/02, so in xparse version provided by TeXLive2017.

**Comment by maieul** [comment]
ps : and thanks for the message about the DANTE prize. Would you be in Passau?

**Comment by baem2** [comment]
issue738 is working fine, so you can close here.

I'm using pre-packaged TeXLive on debian stable, that's why my files tend to be outdated (but I do have my reasons for that).

No, sorry, I won't be attending the DANTE-Tagungen this year.
