### ISSUE TITLE
Noel 2017

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#739]
Cher ami, mes meilleurs voeux pour un joyeux Noël et bonne nouvelle Année;  un merci pour vos efforts pour rendre stable les packages reledmac / reledpar.

En amitié, Enrico Macchia

PS: J'ai terminé un petit travail qui utilise (pour quelques pages) le paquet reledmac. Vous pouvez le trouver à l'adresse www.heinrichfleck.net/quaderni   _sub_  ''Riferimenti ad Archimede in testi classici di lingua greca e latina'' . Ancora saluti cordiali.

**Comment by maieul** [comment]
Cherr Enrico, 

merci pour ce message. Joyeux Noël à vous aussi (avec un peu de retard). Merci aussi pour le lien.

Et bonne année par anticipation!
