### ISSUE TITLE
Reledpar: texte en colonnes, un probleme

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#740]
Cher ami, tout d'abord, bonne année.

J'ai un problème avec reledpar, texte en colonnes. Le fichier dont j'envoie la source minimale, était filable sans erreur jusqu'en juin dernier. À la fin de l'année, comme d'habitude, j'ai recompilé tous mes fichiers, et dans ce cas j'ai trouvé des erreurs et la compilation n'est pas bonne.

`\documentclass[10pt,b5paper,twoside]{memoir}
\usepackage[T1]{fontenc}             
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[french,greek,german,italian]{babel}
%-------------------------------------------------------------------
\usepackage[series={A,B},noend,noeledsec,noledgroup]{reledmac}
\usepackage{reledpar} \setgoalfraction{.85}
\AtBeginDocument{\Xmaxhnotes{0.5\textheight}}
\setlength{\Lcolwidth}{0.47\textwidth}
\setlength{\Rcolwidth}{0.47\textwidth} 
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\textbf{\theAtest\ - A}) }
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\textbf{\theBtest\ - B}) }
\lineation*{page} \Xlineflag 

\newenvironment{DE}{\begin{otherlanguage*}{german}}{\end{otherlanguage*}}
\usepackage{hyperref}\hypersetup{colorlinks,linkcolor=black,citecolor=black,urlcolor=black}%

\begin{document}
\begin{center} 	{\Huge\bfseries{Titolo}} \end{center}	\setlength{\parindent}{0mm}

\begin{pairs}\begin{Leftside}\beginnumbering
\vspace{10mm} 
		
\pstart
%INIZIO TESTO TEDESCO
\begin{DE}
\edtext{Dies ist der Brief}{\Afootnote{\Atest\ Testo in nota}}, den Philipp Lord Chandos, j\"{u}nger Sohn des Earl of Bath, an Francis Bacon, sp\"{a}ter Lord Verulam und Viscount St. Albans, schrieb, um sich bei diesem Freunde wegen des g\"{a}nzlichen Verzichtes auf literarische Bet\"{a}tigung zu entschuldigen.
\end{DE}
\pend
		
\pstart
\begin{DE}
Die Wintersonne\edlabel{Menschen} stand nur als armer Schein, milchig und matt hinter Wolkenschichten \"{u}ber der engen Stadt...
\end{DE}
\pend
\endnumbering
\end{Leftside}%FINE TESTO TEDESCO
	
%INIZIO TESTO ITALIANO
\begin{Rightside}
\beginnumbering
\pstart%
Questa è la lettera che Lord Philip Chandos, il rampollo pù giovane dell'Earl di Bath, scrisse a Francesco Bacone, in seguito Lord Verulan e visconte di Sant'Alban, per spiegare all'amico la definitiva rinuncia all'attività letteraria.
\pend
		
\pstart
Il sole d'inverno stava solo come pallido chiarore bianco e latteo dietro uno strato di nubi\edtext{degli uomini non comuni, di quelli}{\Afootnote{\Atest\ \begin{DE}\textit{den nur gro\ss e Menschen},\end{DE} ln. \edlineref{Menschen}: <<quale [è] soltanto dei grandi uomini>>.}} sopra l'angusta città.....%
\pend%
\endnumbering
\end{Rightside}%FINE TESTO ITALIANO
\end{pairs} 
\Columns
\end{document}`
%============================================

Le problème est le suivant: si j'écris  (texte en allemand, colonne de gauche):
**\edtext {Dies ist der Brief} {\ Afootnote {\ Atest \ Testo in nota}}**, den Philipp Lord Chandos, jj\"{u}nger Sohn des Earl of Bath,.......  la compilation est réussie sans erreurs; 

MAIS SI J'ECRIS

**Dies ist der Brief** den Philipp Lord Chandos, j\"{u}nger Sohn des Earl of Bath, an Francis Bacon, sp\"{a}ter Lord Verulam und Viscount St. Albans, schrieb,.... "le fichier apparaît comme dans l'image ci-jointe: 
![schermata](https://user-images.githubusercontent.com/13473498/34469206-f7a938c0-ef19-11e7-9404-66d59d80ae88.JPG)
 et pendant la compilation, le systeme me donne: beaucoup d'erreurs.

J'ai essayé pendant deux jours pour comprendre le problème mais en vain. Pouvez-vous m'aider? 
La compilation est avec pdflatex, LaTeX est mis à jour, reledpar est la version v2.21.1, dernière révision 2017/12/22.

Saluti, Enrico

**Comment by maieul** [comment]
Pouvez vous tester la branche issue740?

La prochaine fois, pouvez vous utiliser le formulaire pré-rempli lors de la création  d'une issue?

**Comment by heinrichffleck** [comment]
Excusez moi mais je n'ai pas bien compris. La branche issue 740  est la même que j'ai envoyé. J'ai toujours  beaucoup erreurs de compilation; pour example

- Extra }, or forgotten \endgroup, (pas vrai)
- Undefined control sequence,  (ou ??)
e la complation n'est pas bonne. 

Il est (pour moi)  inexplicable que si sur la premiere ligne du texte en allemand j'écris
\edtext{ist}{\Afootnote{\Atest\ TEST-NOTA} } la compiulation est perfait!

Quand vous avez du temps, ça n'est pas urgent, saluti, Enrico

**Comment by maieul** [comment]
Êtes vous sûr d'avoir pris la bonne branche? Votre MWE qui ne marchait pas marche désormais avec cette branche.

**Comment by heinrichffleck** [comment]
Cher Maieul, je ne suis pas un informatique comme vous êtes: je n'ai pas encore résolu mon problème. S'il vous plaît,  si vous avez un peu de temps,  conduisez-moi à trouver l'erreur ou, malheureusement, je  je devrai chercher une autre  fichier  parmi vos exemples.
Saluti, Enrico

**Comment by maieul** [comment]
Tous ce que vous devez faire, c'est de suivre la procédure habituelle pour tester la branch, procédure décrite ici

https://github.com/maieul/ledmac#debug-and-feature-requests

**Comment by maieul** [comment]
Avez vous pu tester cette branche?

**Comment by heinrichffleck** [comment]
D'accord, ça marche, merci. 
Mais je serais extrêmement vous reconnaissant si vous me montriez où se trouve le bogue dans mon fichier source
Saluti, Enrico

**Comment by maieul** [comment]
Il n'y avait aucun bug dans votre fichier source, c'était reledmac/reledpar qui était bugé.

**Comment by maieul** [comment]
Je publie sur le CTAN le correctif. Merci pour le rapport de bug et les tests.

**Comment by heinrichffleck** [comment]
merci à vous pour l'aide et la patience, comme toujours. Saluti, Enrico
