### ISSUE TITLE
\resumenumbering doesn't work in Leftside right after \eledsection

### ISSUE THREAD

**Issue by ndlecic** [maieul/ledmac#744]
If I start \beginnumbering before \eledsection, I can't do \resumenumbering inside \begin{Leftside}, if this is the first thing that happens after section title (cf. MWE). No such problem with \section.

````latex
\documentclass{article}
\usepackage[noend,nofamiliar,series={A}]{reledmac}
\usepackage{polyglossia}
\setmainlanguage{latin}
\setotherlanguage{english}
\usepackage{libertineotf}
\usepackage[widthliketwocolumns,continuousnumberingwithcolumns]{reledpar}
\setlength{\Lcolwidth}{0.47\textwidth}
\setlength{\Rcolwidth}{0.47\textwidth}
\columnsposition{c}
\setlength{\beforecolumnseparator}{0.03\textwidth}
\setlength{\aftercolumnseparator}{0.03\textwidth}
\AtBeginPairs{\sloppy}
\usepackage{lipsum}
\firstlinenum*{1}
\linenumincrement*{1}

\begin{document}

\beginnumbering
\pstart
\eledsection{Section Title}
\pend

\begin{pairs}  
\begin{Leftside} 
    \resumenumbering  
    \pstart  
        Left Lorem ipsum.
    \pend  
    \pausenumbering
\end{Leftside} 
\begin{Rightside}   
    \beginnumbering  
    \pstart  
        Right Lorem ipsum.
    \pend  
    \pausenumbering
\end{Rightside}  
\end{pairs}  
\Columns

\resumenumbering
\pstart  
    Lorem \edtext{ipsum}{\Afootnote{ipsam}} dolor.
\pend  
\pausenumbering

\end{document}
````

**Comment by maieul** [comment]
Please, when opening an issu, respect the form structuration,

![screenshot-2018-1-21 maieul ledmac](https://user-images.githubusercontent.com/636640/35195745-491286ea-fec8-11e7-868d-a82e86d15ab0.png)

**Comment by maieul** [comment]
You didn't respect the structure for the alternance between // and not // texts.

Cf 
36977cc 

which work perfectly.

**Comment by ndlecic** [comment]
Sorry, I missed the version: tested with ledmac-issue743. And sorry for the missing \pausenumbering. Actually, for me it doesn't work correctly; please take a look at the number at the right side: it should be 2R, but 1R appears. That's the problem.

**Comment by maieul** [comment]
Please try the branch issue744

**Comment by ndlecic** [comment]
Thanks again! It works as expected with issue744 branch. However, now I see that there is a similar problem with right numbering with \section as well. Should I open a new issue, or do you prefer a new MWE here?

**Comment by maieul** [comment]
One issue by problem.

**Comment by ndlecic** [comment]
Done. Sorry for the lack of clarity in this issue once again. We're all too busy and trying (in vain in my case) to do several things at the time...

**Comment by maieul** [comment]
I have published on CTAN the new version.

**Comment by ndlecic** [comment]
Great, thanks much for the info!
