### ISSUE TITLE
\textit prints bold-italics, instead of italics in Xelatex

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#751]
Hi!
My reledmac-version is "2.26.6"; unfortunately, I cannot remember which was the version I was using before that. After the last update of my Latex distribution, the problem is that whenever I use \textit the respective text gets printed in bold-italics, instead of italics. The problem occurs anyway, i.e. not only when combined with other packages. The problem happens both in parallel and normal typesetting.

```` 
\documentclass[a4paper]{book}
\usepackage{polyglossia,fontspec,xunicode}
\setmainfont{Linux Libertine O}
\setmainlanguage[variant=ancient]{greek}
\begin{document}
Ἄνδρα μοι ἔννεπε, \textit{Μοῦσα}, πολύτροπον, ὃς μάλα πολλὰ πλάγχθη.
\end{document}
````

**Comment by Doc73** [comment]
Sorry, but I just tested your MWE and I can't confirm your issue. :-(

**Comment by maieul** [comment]
In any case, your issue, as far I understand it, is not related to reldmac, as I can see in your MWE.

**Comment by RichyZ99** [comment]
I suggest to add a specification right after `\setmainfont{Linux Libertine O}` so that the package is forced to use the right variant of the font:
`\setmainfont{Linux Libertine O}[ItalicFont = Linux Libertine O Italic, BoldFont = Linux Libertine O Bold]`

**Comment by NiAgio** [comment]
RichyZ99, you have just saved my life. Thanks a lot!

**Comment by RichyZ99** [comment]
You're welcome, @NiAgio; I had the same problem with the same font, but I had a look at `fontspec` documentation and they focused on this issue too.

**Comment by maieul** [comment]
That is not normal to get this resultat. In any case, Linux Libertine font is not maintened anymore, but its forks Libertinus is.

**Comment by sieversMartin** [comment]
Am 04.03.2018 um 15:57 schrieb RichyZ99:
> I suggest to add a specification right after |\setmainfont{Linux
> Libertine O}| so that the package is forced to use the right variant of
> the font:
> |\setmainfont{Linux Libertine O}[ItalicFont = Linux Libertine O Italic,
> BoldFont = Linux Libertine O Bold]|

For Libertine, there is also a ready-to-use package.

Best wishes
Martin

**Comment by maieul** [comment]
I am quite surprised by the number of people who follow the issues on
reledmac !

**Comment by RichyZ99** [comment]
I study Humanities at Lycée in Italy: `reledmac` is the antidote to awful unedited Microsoft(R) Word documents @maieul

**Comment by Doc73** [comment]
@RichyZ99 I am a high school teacher in Pisa. Now I'll do an interrogation to you! :-D

**Comment by RichyZ99** [comment]
@Doc73 may I remind you that only the police do an _interrogation_; maybe you meant _oral test_.

**Comment by Doc73** [comment]
@RichyZ99 No, no! I usually do "interrogations"! Ahahah!

**Comment by maieul** [comment]
@RichyZ99 what is surprising me is not that people use reledmac, but that they follow the new issues on reledmac repository.

**Comment by RichyZ99** [comment]
My presence here is just a case: I saw the email and I replied since I could give an answer, even if Martin showed mine answer wasn't the best possible one. I enabled the _Watch_ feature as I may find something useful for me @maieul
