### ISSUE TITLE
Using \section in place of \eledsection

### ISSUE THREAD

**Issue by adunning** [maieul/ledmac#752]
Would it be possible to use the standard `\section`, `\subsection`, etc. commands in place of `\eledsection`, `\eledsubsection` when using `\autopar`?

I ask in part because it would make it much easier for newcomers to learn the system, but also because it would improve the functionality: the `hyperref` package does not recognize `\eledsection` for building a table of contents, and classes do not control their formatting. I realize, however, that there is probably a very good reason for the design as it stands.

As an example, I am thinking of something like:

```latex
\beginnumbering 

\autopar

\section{\edtext{Sermo}{\lemma{sermo} \Afootnote{exhortatio \emph{P3}}} ad leprosos}

Lorem ipsum …

\endnumbering
```

(Under Reledmac 2.26.6, this returns an error.)

**Comment by maieul** [comment]
No. It is not possible. Formally, \section can't be between \pstart and
\pend. It can only be in the optional argument of a \pstart.

And also, \eledsection is counted in the list of lines, but \section is
not in the list of line.


And \eledsection is recognized in a table of content (or if not, please open an issue with a MWE)

And yes, it is know that \eledsection can't be controlled by
class/package. That is a major problem, with many openend isssue, but I
have no time to solve this. 


So I close this issue.

**Comment by adunning** [comment]
One can always hope. Thanks for the explanation!
