### ISSUE TITLE
\numberlinefalse et numéro de note critiques

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#761]
Issue can be opened in English or in French (I prefer in French). Please fill this form.
Please open one issue by problem, and not a global issue for multiple problems. 

# Version of reledmac / reledpar (if that is a devellopement version, please precise the branch)
Current (2.26.8)
# If this is a newly introduced problem, please indicate the last working version of the package(s)
# Does the problem happen only when combining with some packages?

# Does the problem happens both in parallel typesetting and normal typesetting?
Yes

# Description of the problem
vu en #760 : après un \numberlinefalse, les numéros de lignes en note de bas de page sont erronnées. 
# Minimal Working Example

Please provide a [MWE](http://minimalbeispiel.de/mini-en.html). 
In  case where the problem happens both in parallel typesetting and normal typesetting, please make your MWE in normal typesetting (because your MWE must be _Minimal_). 

```` 
\documentclass{book}


\usepackage[series={A},noeledsec,nofamiliar,noledgroup,draft]{reledmac}
\usepackage{reledpar}


\begin{document}

\lineation{page}
\firstlinenum*{1}
\linenumincrement*{1}

\beginnumbering
	       \pstart
                Left side %
\edtext{paragraph}{%
	\Afootnote{test}}%
. Left side paragraph. Left side paragraph. Left side paragraph. Left side paragraph. Left side paragraph. Left side paragraph. Left side paragraph.
            \pend
            \numberlinefalse
            \pstart
\textit{Add some text here that expplains something about the following passage, e.g. that it is only available in another ms because\footnote{regular footnote} of a lacuna in the main witness:            
}           \pend
			\numberlinetrue
            \pstart
                Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  %
\edtext{Other}{%
	\Afootnote{test}}
 left side paragraph.  Other left side paragraph.
            \pend
\endnumbering



\begin{pages}
    \begin{Leftside}
        \beginnumbering
            \pstart
                Left side %
\edtext{paragraph}{%
	\Afootnote{test}}%
. Left side paragraph. Left side paragraph. Left side paragraph. Left side paragraph. Left side paragraph. Left side paragraph. Left side paragraph.
            \pend
            \numberlinefalse
            \pstart
\textit{Add some text here that expplains something about the following passage, e.g. that it is only available in another ms because\footnote{regular footnote} of a lacuna in the main witness:            
}           \pend
			\numberlinetrue
            \pstart
                Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  Other left side paragraph.  %
\edtext{Other}{%
	\Afootnote{test}}
 left side paragraph.  Other left side paragraph.
            \pend
        \endnumbering
    \end{Leftside}
    \begin{Rightside}
        \beginnumbering
            \pstart
                Right side paragraph. Right side %
\edtext{paragraph}{%
	\Afootnote{test}}.
. Right side paragraph. Right side paragraph.
            \pend
            \numberlinefalse
            \pstart
            \pend
            \numberlinetrue
            \pstart
                Other right side paragraph. Other right %
\edtext{side}{%
	\Afootnote{test2}}
 paragraph. Other right side paragraph. Other right side paragraph. Other right side paragraph. Other right side paragraph. Other right side paragraph.
            \pend
        \endnumbering
    \end{Rightside}

\end{pages} 
\Pages

\end{document}

````

**Comment by maieul** [comment]
@floriandk   

please test the branch issue761. It solve both #760 and a problem with footnote line numbering.

Notes : the  \numberlinefalse was introduced for people who need multiple layer of standard footnote, but no line number, and also for people who needs parallele typesetting without line numbering. It was not tested for your usecase.

**Comment by floriandk** [comment]
Looking good here: the break is added correctly in the parallel text, too, and the wrong numbers seem to be ok now.

Thanks you!

(You might want to change your README.md, it still says "- run: `latex reledmac.ins`" etc. instead of - run: `xelatex reledmac.ins`)

**Comment by maieul** [comment]
is pdflatex problematic with texlive2018? because with texlive 2017, I
can use pdflatex on .ins file.

**Comment by floriandk** [comment]
indeed, it also works for me with TL17, but in new TL18 running pdflatex on the .ins file breaks off with 

```
********************************************************
* No Configuration file found, using default settings. *
********************************************************

(./reledmac.ins
! Undefined control sequence.
\UseTextAccent ...up \@firstofone \let \@curr@enc 
                                                  \cf@encoding \@use@text@en...
l.45 \endpreamble
                 
```

`xelatex` compilation works on TL18

**Comment by maieul** [comment]
well,
David Carlisle confirms me that is a bug in LaTeX.

You can workaround by modifing the .ins file 
\input docstrip.tex
\csname UseRawInputEncoding\endcsname

They will release a new version of LaTeX without this bug
