### ISSUE TITLE
Chapter ending with parallel columns

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#772]
# Version of reledmac / reledpar (if that is a devellopement version, please precise the branch)
2.26.11/2.21.8

# If this is a newly introduced problem, please indicate the last working version of the package(s)
//

# Does the problem happen only when combining with some packages?
//

# Does the problem happens both in parallel typesetting and normal typesetting?
Parallel and normal

# Description of the problem
When a chapter ends with parallel columns, I get some errors in compilation.
I read the manual carefully (§ 4.2.6), and especially this sentence:

> The important thing to remember is that you have to use `\endnumbering` in a right column before every `\endnumbering` in single-column text or in parallel with `\endnumbering` in a left-column text (the latter is the case when a document or a section ends in a two-columns mode).

but changing the last `\pausenumbering` to `\endnumbering` doesn't solve the issue. Maybe it's my fault that I do not understand the manual well...

When, after latest parallel text, there is a new `pstart`, the compilation is fine.

# Minimal Working Example
Please provide a [MWE](http://minimalbeispiel.de/mini-en.html). 
In  case where the problem happens both in parallel typesetting and normal typesetting, please make your MWE in normal typesetting (because your MWE must be _Minimal_). 

```tex
% !TeX program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\documentclass{book}

\usepackage{libertinus-otf}
\usepackage{polyglossia}

\usepackage[noeledsec,noledgroup,series={A,B,C}]{reledmac}
\usepackage[continuousnumberingwithcolumns]{reledpar}

\usepackage{lipsum}

\begin{document}

\chapter{chapter 1}
\beginnumbering
\numberpstarttrue

\pstart
\lipsum[1]
\pend

\pausenumbering
\begin{pairs}
\begin{Leftside}
\resumenumbering
\numberpstartfalse
	\pstart
	\lipsum[1] 
	\pend
\pausenumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\numberpstartfalse
	\pstart
	\lipsum[1]
	\pend
\pausenumbering
\end{Rightside}
\end{pairs}
\Columns

\numberpstarttrue
\resumenumbering

% Adding a new pstart solves the issue
%\pstart
%\lipsum[1]
%\pend

\numberpstartfalse
\endnumbering

\chapter{chapter 2}
\beginnumbering
\numberpstarttrue

\pstart
\lipsum[1]
\pend

\pausenumbering
\begin{pairs}
\begin{Leftside}
\resumenumbering
\numberpstartfalse
	\pstart
	\lipsum[1] 
	\pend
\pausenumbering
\end{Leftside}

\begin{Rightside}
\resumenumbering
\numberpstartfalse
	\pstart
	\lipsum[1]
	\pend
\pausenumbering
\end{Rightside}
\end{pairs}
\Columns
\numberpstarttrue
\resumenumbering

\pstart
\lipsum[1]
\pend

\numberpstartfalse
\endnumbering

\end{document}
```

**Comment by maieul** [comment]
826c1b73 solve this issue.

the solution is explained in the citation your quotes **or in parallel with \endnumbering in a left-column text**

**Comment by Doc73** [comment]
Many thanks! 
Could you add such a scheme in the manual? I think it could be clearer for the reader.

```tex
\section{}
\beginnumbering
\pstart ... \pend
\pausenumbering
\begin{pairs}
\begin{Leftside}
\resumenumbering
	\pstart ... \pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
	\pstart ... \pend
\endnumbering
\end{Rightside}
\end{pairs}
\Columns

\section{}
\beginnumbering
\pstart ... \pend
\pausenumbering
\begin{pairs}
\begin{Leftside}
\resumenumbering
	\pstart ... \pend
\pausenumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
	\pstart ... \pend
\pausenumbering
\end{Rightside}
\end{pairs}
\Columns
\numberpstarttrue
\resumenumbering
...
```

**Comment by Doc73** [comment]
Alternatively, you could consider to modify the sentence

> The important thing to remember is that you have to use `\endnumbering` in a right column before every `\endnumbering` in single-column text or in parallel with `\endnumbering` in a left-column text (the latter is the case when a document or a section ends in a two-columns mode).

to

> The important thing to remember is that you have to use `\endnumbering` in the latest right column of chapter or section. In particular, when document or section ends in a two-columns mode, remember to use `\endnumbering` also in the left-column text.

**Comment by maieul** [comment]
no, 
it is not related at all with chapter or section. 

I won't add example directly in the handbook, as it is already in
example file.

I suggest: you must 
use \endnumbering in a right column in the following cases:
- there is also a \endnumbering in the left column, because the line
numbering is finishing with a two columns mode
- there will be a \endnumbering in a text after the columns, in a single
column mode, because the ligne numbering finish with single column modetext.

**Comment by Doc73** [comment]
Ok. Another small suggestion:
> You must use \endnumbering in a right column in the following cases:
>- there is also a \endnumbering in the left column, because the line numbering ends with a two columns mode **(for ex. at the end of a document or column)**
>- there will be a \endnumbering in a text after the columns, in a single column mode, because the ligne numbering finish with single column mode text.

**Comment by maieul** [comment]
done on 4332cad8, I have deleted "or column", because it is not clear at all

**Comment by Doc73** [comment]
Ah, right! My fault! I wanted to write "section", bot I wrote "column"!

**Comment by maieul** [comment]
I any case, I won't use section notion, in anyway.

**Comment by maieul** [comment]
We should not presume the way people split there text. And, in anycase, it could be possible to overlap section and to continoue with  same line numbering.
