### ISSUE TITLE
reledpar + calc = overfull boxes

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#773]
If you load reledpar and calc every line is a overfull box (in the MWE: a black box). This issues seems to be introduced at (or shortly before) reledpar 1.17. As soon as you remove calc, it's fine.

PS Sorry, I did not test it with the most recent version, as it requires the latest latex3 (with the command \NewExpandableDocumentCommand), which I do not yet use (you should add a fitting "required version" command).

MWE:

```
\listfiles
\documentclass[paper=a4,10pt,DIV=classic]{scrbook}
\usepackage[latin,german]{babel} 
\usepackage[T1]{fontenc}
\usepackage{textcomp}
\usepackage{calc}
\usepackage{blindtext}
\usepackage[series={A},noeledsec,noledgroup]{reledmac}
\usepackage{reledpar}

\setlength{\overfullrule}{.45em}

\begin{document}
\chapter{Das Beispiel}

\section{Einleitung}

\blindtext[2]

\begin{pages}
\begin{Leftside}
\beginnumbering

\pstart[\section{Der linke Text}]
\begin{otherlanguage}{latin}
  \noindent\blindtext[2]
\end{otherlanguage}
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering

\pstart[\section{Der rechte Text}]
\noindent\blindtext[2]
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}
```

**Comment by maieul** [comment]
That is a BIG bug of calc, which doesnot allow global assignment with \setlength.

``` 
\documentclass{article}
\usepackage{calc}
\begin{document}
\newlength{\toto}
\begingroup
\global\setlength{\toto}{2pt}
\endgroup
\the\toto
\end{document}
``` 

For the problem of minimal version of xparse, please open an issue.

**Comment by maieul** [comment]
cf https://github.com/latex3/latex2e/issues/58

**Comment by maieul** [comment]
ok, calc won't change for this problem (it is not possible). Please try  branch issue773 which solve this issue.

**Comment by baem2** [comment]
Thanks for fixing it -- but sorry, I can't test, as I do have a too old TeX system (see #774).

**Comment by maieul** [comment]
Sorry, but it is not my problem. You should update your tex system to get new version of reledmac/reledpar.

In any case, I could publish without your test because the bug is very easy. But if you want to have it in a solved version, you should update, in any case, your tex distribution...

**Comment by baem2** [comment]
I'm happy when it is fixed in the most recent version, I do not need the fix backported. I just wanted to tell that I'm not able to test it. I do not need the fix for my older verison, it's all fine. Thank you for your work! If it is an easy fix, just publish it as it is now.
