### ISSUE TITLE
Use of \NewExpandableDocumentCommand

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#774]
In some version of reledpar after version 1.17.4 the use of the command \NewExpandableDocumentCommand was added. This command is defined in a rather recent version of xparse (latex3).

Please add the respective required-version-command for xparse.

**Comment by maieul** [comment]
2017/03/07

**Comment by maieul** [comment]
I have two options
1. Juste single warning
2. Real error message.

I would prefer 1 (easiest to implement, the error message will comme latex), What do you think?

**Comment by baem2** [comment]
1 is fine.
