### ISSUE TITLE
Support for three or four columns on a double page

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#776]
This is not a bug, rather a question or probably a feature request.

As you know, texts are often transmitted in several languages. Sometimes it makes sense to have two languages printed parallely. For a current project we're trying to have Latin and Greek in two columns on the left pages, and German on the right pages. The left/right pages including apparatus are currently done with reledmac/-par, the columns on the left pages are done with parallel.sty (as an environment inside a \pstart/\pend) -- and it actually works! But most likely we will stumble upon weird problems sooner or later with this solution.

That's why I'm asking: Is there any chance to have something like that as an official feature of reledmac/-par? Or is it a change too complex?

**Comment by maieul** [comment]
that is a big point, asked many time.

The answer is : no chance, untily I get six month to refactoring all the
code.

**Comment by baem2** [comment]
Yap, I feared that would be the answer -- thank you anyway for your work on this package! :)
