### ISSUE TITLE
\hidenumbering adds a space

### ISSUE THREAD

**Issue by adunning** [maieul/ledmac#780]
# Version of reledmac / reledpar (if that is a devellopement version, please precise the branch)

2018/09/13 v2.27.0

# Description of the problem

Adding the \hidenumbering command within a word unexpectedly adds a space. (I am doing this in combination with sidenotes to ensure they do not clash with line numbers.)

<img width="253" alt="screen shot 2018-10-06 at 01 03 31" src="https://user-images.githubusercontent.com/1084407/46563770-a7142400-c903-11e8-8457-054cf9ec2803.png">

# Minimal Working Example

```latex
\documentclass{article}
\usepackage[series={},nocritical,noend,noeledsec,nofamiliar,noledgroup]{reledmac}

\begin{document}
\beginnumbering
\autopar

\noindent quo\ledinnernote{375ra}\hidenumbering\textbar{}dam \\
quo\ledinnernote{375ra}\textbar{}dam \\
quo\hidenumbering{}dam

\endnumbering
\end{document}
```

**Comment by maieul** [comment]
branch  issue780 solve this issue

**Comment by adunning** [comment]
Merci beaucoup!
