### ISSUE TITLE
A package for Emacs to work with reledmac

### ISSUE THREAD

**Issue by JuanManuelM** [maieul/ledmac#783]
Hi, I've wrote a small and very simple package for Emacs / AUCTeX, with a series of shortcuts that I think might be useful for working in Emacs with reledmac (the repo is on GitLab, sorry): https://gitlab.com/maciaschain/critical-keys

Best regards

**Comment by Doc73** [comment]
Many thanks! I'm an Emacs/AUCTeX user, but I use a simple abbrev-table.
The only thing that scares me is the idea of having to memorize these shortcuts :-D

**Comment by JuanManuelM** [comment]
@Doc73 you're welcome. The "edtext" shortcuts can be memorozed as: M - (QW ER TY); and the others, with the three letters below: M - (A S D). And, of course, the key binds can be modified in each function:
```elisp
...
'(define-key LaTeX-mode-map
     (kbd "<new-key-bind>")
...
```

**Comment by Doc73** [comment]
@JuanManuelM 
I would suggest to change the commands in the following manner:
```tex
\edtext{<REGION>}{\Afootnote[]{}}
```
etc., in order to have square brackets for options.

**Comment by JuanManuelM** [comment]
@Doc73 good suggestion, many thanks. I've just made a commit. Now, the prefix `C-u` inserts the command with brackets, *i.e*., `C-u M-Q` = `\edtext{<REGION>}{\Afootnote[]{}}`

**Comment by Doc73** [comment]
@JuanManuelM 
I think it is not necessary to add anoter shortcut. It is better one command which insert square brackets: even if not used, they do not give issues.
