### ISSUE TITLE
No separation between multiple line number annotations on the same line

### ISSUE THREAD

**Issue by fps-vogel** [maieul/ledmac#791]
# Version of reledmac
2.29.0

# Description of the problem
Multiple line number annotations on the same line are displayed without any separation between them. In the example below, where a biblical text is typeset with verse numbers in the margins, the first two verses both begin on the first line, so "12" appears in the margin. Is it possible to copy the behavior of sidenotes here, so that a comma and space appear between every annotation ("1, 2")?

# Minimal Working Example
```` 
\documentclass{article}
\usepackage[total={3in, 4in}]{geometry}
\usepackage[noresetlinenumannotation]{reledmac}
\newcommand{\bv}[1]{\linenumannotation{#1}}
\makeatletter
\Xwraplinenumannotation{\@firstofone}
\renewcommand{\linenumrep}[1]{}
\makeatother
\firstlinenum{1}
\linenumincrement{1}

\begin{document}
  \beginnumbering
  \pstart
    \bv{1}Initium evangelii Iesu Christi, Dei filii.\bv{2} Ut scriptum in vatibus est: “Ego tibi meum praemittam nuntium, qui tibi viam praeparet.\bv{3} Vox clamantis in solitudine: ‘Parate viam Domini! Dirigite semitas eius!’”
  \pend
  \endnumbering
\end{document}
````

**Comment by maieul** [comment]
I will try to look on it this week-end, but without certainty

**Comment by maieul** [comment]
Branch issue791 (which DOES NOT include feature of branche issue790 and issue792) add a comma between annotation.

You can change this separator using `\setlinenumannotationsep`

**Comment by fps-vogel** [comment]
This solves the problem. Thank you!
