### ISSUE TITLE
Trop d'espace avant \Xsymlinenum et \Xparafootsep

### ISSUE THREAD

**Issue by adunning** [maieul/ledmac#795]
# Version

2019/01/22 v2.30.0

# Description

Les symboles utilisés pour `\Xsymlinenum` et `\Xparafootsep` ne sont pas centrés entre les deux notes environnantes.

![screen shot 2019-02-11 at 00 30 17](https://user-images.githubusercontent.com/1084407/52547232-3f2f8780-2d94-11e9-8c06-c3deadacdb75.png)

```latex
\documentclass{book}

\usepackage{reledmac}
\Xarrangement[A]{paragraph}
\Xnumberonlyfirstinline
\Xnumberonlyfirstintwolines
\Xparafootsep{$\parallel$}
\Xsymlinenum{$\mid$}

\begin{document}
\beginnumbering
\autopar

Lorem ipsum dolor sit \edtext{amet}{\Afootnote{lorem ipsum}}, consectetur \edtext{amet}{\Afootnote{lorem ipsum}}adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna \edtext{amet}{\Afootnote{lorem ipsum}} aliqua.

\endnumbering

\end{document}
```

**Comment by maieul** [comment]
Une espace de 1em minus 0.4 em plus 0.4em est ajouté après chaque note paragraphé. C'est réglable via `\Xafternote`. Ca c'est pour le séparateur de note. 

Après un symbole de ligne, le même espace qu'après un numéro de ligne est inséré. C'est réglable avec `\Xaftersymlinenum` (et on a aussi `\Xbeforesymlinenum).

Avec ceci,  tu devrait pouvoir centrer tes symboles.

**Comment by adunning** [comment]
Merci beaucoup! Oui, il marche avec `\Xaftersymlinenum`:

![screen shot 2019-02-11 at 10 50 06](https://user-images.githubusercontent.com/1084407/52574670-cdcef380-2dea-11e9-9aba-8dac54a0681c.png)

```latex
\documentclass{book}

\usepackage{reledmac}
\Xarrangement{paragraph}
\Xnumberonlyfirstinline
\Xnumberonlyfirstintwolines
\Xafternote{1em plus.4em minus.4em}
\Xaftersymlinenum{1em plus.4em minus.4em}
\Xsymlinenum{\textbar{}}
\Xparafootsep{$\parallel$\hspace{1em plus.4em minus.4em}}

\begin{document}
\beginnumbering
\autopar

Lorem ipsum dolor sit \edtext{amet}{\Afootnote{lorem ipsum}}, consectetur \edtext{adipiscing}{\Afootnote{lorem ipsum}} elit, sed do eiusmod tempor incididunt ut labore et dolore magna \edtext{amet}{\Afootnote{lorem ipsum}} aliqua.

\endnumbering

\end{document}
```
