### ISSUE TITLE
Masquer un préfixe pour un renvoi individuelle

### ISSUE THREAD

**Issue by adunning** [maieul/ledmac#796]
# Version

2019/01/22 v2.30.0

# Description

Si je donne plusieurs renvois à la suite, normalement je ne répéterais pas le préfixe.  L'exemple ci-dessous donne « ligne 1, ligne 2 » au lieu de « ligne 1, 2 ». Serait-il possible d'ajouter un argument optionnel pour désactiver le préfixe d'un renvoi individuel, par exemple `\SEref[noprefix]{test}`?

(Je m'excuse par avance si c'est encore un problème dont la solution me regarde en face.)

```latex
\documentclass{book}

\usepackage{reledmac}
\setapprefprefixsingle{ligne~}
\setapprefprefixmore{lignes~}
\setSErefonlypageprefixsingle{p.~}
\setSErefonlypageprefixmore{pp.~}

\begin{document}

\SEref{test}, \SEref{test2}

\beginnumbering
\autopar

\edlabelSE{test}Lorem ipsum dolor sit amet, consectetur sed do eiusmod tempor incididunt ut \edlabelSE{test2}labore et dolore magna amet aliqua.

\endnumbering

\end{document}
```

**Comment by maieul** [comment]
It should be possible, I just need to find few hour. Maybe next week,
but not this one.

**Comment by adunning** [comment]
Glad that I wasn't missing it, at least, thank you very much indeed!

**Comment by adunning** [comment]
I suppose there should be two arguments: one to override the prefix to use the plural `\setapprefprefixmore` (for the first cross reference) and another to hide the prefix (for the second).

**Comment by maieul** [comment]
Il faut que cela s'applique aussi aux notes de fin (puisque le code est mutualisé).
 \newhooktoggle@specific > c'est ca que je dois utiliser,

**Comment by maieul** [comment]
a non dans ce cas, il y a pas besoin d'appel aux notes de fin.

Bon, sur la branch issue796, j'ai ajouté l'option [noprefix]

@adunning pour l'autre option, j'aurais besoin d'un nom cohérent ;-)

**Comment by adunning** [comment]
Merci beaucoup ! Je pense que une option intitulée  `prefixmore` est cohérent avec le nom `\setapprefprefixmore`.

**Comment by maieul** [comment]
J'ai ajouté donc l'option `prefixmore`. Par contre dans votre cas, c'est `\setSE....` cf f94c9c3c

merci de tester et de me faire des retours. Je documentair plus tard.

**Comment by adunning** [comment]
Merci beaucoup! Il semble que la branch `issue796` n'est pas publiée sur GitHub?

**Comment by maieul** [comment]
corrigé!

**Comment by maieul** [comment]
J'avais fait une erreur dans mes commits. J'ai du coup forcé un push de issue796 (normalement j'évite, mais là...). Le dernier commit d'issue796 est  9fc4dda7

**Comment by adunning** [comment]
C'est fantastique. J'ai ajouté la documentation dans #806. Merci beaucoup !

**Comment by maieul** [comment]
voilà, je publie sur le CTAN

**Comment by adunning** [comment]
Très bien; merci encore !
