### ISSUE TITLE
Line break in verse like poemscol's \brokenline/\versephantom

### ISSUE THREAD

**Issue by rrthomas** [maieul/ledmac#797]
How can I achieve the same effect with reledmac as poemscol's \brokenline/\versephantom:

![image](https://user-images.githubusercontent.com/17382/52640854-6474e080-2ecf-11e9-95e9-c01dcab5cc35.png)

**Comment by maieul** [comment]
sorry, I don't know what \brokenline/\versephantom... 
please provide a MWE...

**Comment by rrthomas** [comment]
See the excerpt from the poemscol manual which I attached above.

**Comment by martinantonmueller** [comment]
Not sure if this is the same but in plays there exists the Antilabe https://en.wikipedia.org/wiki/Antilabe where one has to work with \textlength to make the exact whitespace so that the next line continues at the same spot the previous verse ended

**Comment by rrthomas** [comment]
@martinantonmueller, as far as the typesetting goes, yes, it's the same.

As a workaround, I did the equivalent of the following:

    \startsub
    And Agamemnon dead. &
    \endsub\makebox[\widthof{And Agamemnon dead.}]{} Being so caught up, &

**Comment by maieul** [comment]
I think a better workaround would be  
``` 
And Agamemnon dead.\\
\hphantom{And Agamemnon dead.} Being so caught up,
```` 

(to be tested)

**Comment by maieul** [comment]
not that if this typography is required because the verse is too long,
reledmac does it automatically

**Comment by rrthomas** [comment]
Thanks, I wasn't aware of `\hphantom`. I tried it and it didn't work, I guess because the space is at the start of a (TeX) line?

Also, I tried using `\\` before instead of sublineation. That would work fine in some situations, but in mine it did not because I needed a page break between the two sublines, and the use of `\\` instead of sublines seemed to prevent that. (Conversely, if you specifically didn't want a page break there, it would be a good solution!)

In this case the line is not too long; rather, the break is required for reasons of sense (my case is very similar to antilabe, as mentioned above).

**Comment by maieul** [comment]
which syntax would you like? is it ok for you with the workaround?

**Comment by rrthomas** [comment]
Maybe it is OK with the workaround, but it would be good to document the workaround. Also, which solution should be documented? We've already discussed several possibilities (`\makebox` vs `\hphantom`, and `\\` versus sublineation. It would be good to document a technique that is likely to work in most circumstances, if possible.
