### ISSUE TITLE
\Xgroupbyline produit des lignes en surplus

### ISSUE THREAD

**Issue by adunning** [maieul/ledmac#802]
# Version of reledmac

2019/01/22 v2.30.0

# If this is a newly introduced problem, please indicate the last working version of the package(s)

Vous avez corrigé ce problème dans #731.

# Description

Quand le texte atteint la fin d'une ligne,`\Xgroupbyline` ajoute une ligne blanche en surplus.

# Minimal Working Example

```latex
\documentclass{article}
\usepackage{reledmac}
\Xgroupbyline
\begin{document}

\beginnumbering
\autopar

A \edtext{Afootnote}{\Afootnote{X}} \edtext{}{\Afootnote{x}} \edtext{}{\Afootnote{Critical notes too tight to the end of line show a blank line}}

A \edtext{Afootnote}{\Afootnote{X}} \edtext{}{\Afootnote{x}} \edtext{}{\Afootnote{Critical notes not too tight don't}}

\endnumbering

\end{document}
```

**Comment by maieul** [comment]
merci d'essayer la branche "issue802"

**Comment by adunning** [comment]
J'ai le même résultat avec issue802, utilisant le MWE ci-dessus.

**Comment by adunning** [comment]
Désolé, j'ai négligé de déplacer le fichier dans le bon dossier ! Ça fonctionne parfaitement !

**Comment by maieul** [comment]
ok, par contre j'ai du modifié encore le code pour pouvoir débuguer issue #801. Du coup il faudrai tester à partir de la branche issue801 aussi

**Comment by adunning** [comment]
Hm, la branche `issue801` ne fonctionne pas du tout.

**Comment by maieul** [comment]
peut être qu'avec ma connexion internet pourri, j'avais pas envoyé les bonnes choses. peux tu retester? le dernier commit de issue801 est cf4c0a18

**Comment by adunning** [comment]
Il fournit le même résultat. C'est plus évident avec le paquet setspace:

![screen shot 2019-02-25 at 11 36 10](https://user-images.githubusercontent.com/1084407/53352839-8ddf3480-38f1-11e9-8f0f-b09a2e9d2df1.png)

```latex
\documentclass{article}

\usepackage{setspace}
\setstretch{1.5}

\usepackage[series={A}]{reledmac}
\Xgroupbyline

\usepackage{mwe}

\begin{document}

\beginnumbering
\autopar

\edtext{test}{\Afootnote{\blindtext}} \blindtext\edtext{test}{\Afootnote{\blindtext}} \blindtext\edtext{test}{\Afootnote{\blindtext}}

\endnumbering

\end{document}
```

**Comment by adunning** [comment]
Sans `\Xgroupbyline`:

![screen shot 2019-02-25 at 11 37 38](https://user-images.githubusercontent.com/1084407/53352942-c1ba5a00-38f1-11e9-8a36-f05da40a4f94.png)

**Comment by adunning** [comment]
Je ne comprends pas le problème: la branche issue801 fonctionne bien avec mes MWEs, mais avec mon fichier plus volumineux, elle semble être bloquée dans une boucle infinie au cours de la création du fichier de notes.

**Comment by maieul** [comment]
arf !
cette fonction est vraiment casse-geule... on arrivera sans doute à la
faire fonctionner, mais il y a plein de piège...

**Comment by adunning** [comment]
Vraiment ; merci pour ta persévérance ! Devrais-je développer un MWE avec la boucle ?

**Comment by maieul** [comment]
oui,
car sans j'aurais du mal...

**Comment by adunning** [comment]
Je pense que cela se produit avec un long texte dans `\edtext`:

```latex
\documentclass{article}
\usepackage[series={A}]{reledmac}
\Xgroupbyline
  
\usepackage{mwe}
\begin{document}

\beginnumbering
\autopar

\edtext{\blindtext}{\Afootnote{test}}

\endnumbering

\end{document}
```

**Comment by adunning** [comment]
Cet exemple fonctionne si je supprime `\Xgroupbyline` ou utilise un texte de un or deux mots dans `\edtext`.

**Comment by maieul** [comment]
hum
est-ce que ce serai une saturation mémoire? je vais regharder tout cela.

Merci pour l'envoi

**Comment by adunning** [comment]
Merci beaucoup !

**Comment by adunning** [comment]
J'ai créé #807 pour le problème de la boucle infinie.

**Comment by maieul** [comment]
le problème se posait en multiple line, car l'intégration de l'option
linerangesep buguait... c'est corrigé normalement dans la dernière
version

**Comment by maieul** [comment]
@adunning des nouvelles?

**Comment by adunning** [comment]
Oui, ça marche bien avec la branche `issue802` !

**Comment by adunning** [comment]
(Ça marche aussi avec `issue801`.)

**Comment by maieul** [comment]
oui, mais issue801 n'allait pas avec issue la correction sur 802. Donc on garde issue802 comme branche.
