### ISSUE TITLE
L’espacement des lignes est incohérent avec \Xgroupbyline

### ISSUE THREAD

**Issue by adunning** [maieul/ledmac#803]
# Version of reledmac

2019/01/22 v2.30.0

# Description of the problem

L’espacement des lignes entre les paragraphes est incohérent quand j'utilise `\Xgroupbyline`. Je suppose que ce problème est lié à #802. Est-ce qu'il manque un `\par`?

# Minimal Working Example

![screen shot 2019-02-14 at 18 23 10](https://user-images.githubusercontent.com/1084407/52824165-9760d500-3085-11e9-8f94-6f775c1171fa.png)

```latex
\documentclass{article}

\usepackage[series={A}]{reledmac}
\Xgroupbyline

\usepackage{mwe}

\begin{document}

\beginnumbering
\autopar

\edtext{test}{\Afootnote{\blindtext}} \blindtext\edtext{test}{\Afootnote{\blindtext}} \blindtext\edtext{test}{\Afootnote{\blindtext}}

\endnumbering

\end{document}
```

**Comment by maieul** [comment]
je ne vois pas le problème. Il s'agirait entre semper et 11? ou bien c'est ailleurs? parce que là, tout est bon normalement dans reledmac

**Comment by adunning** [comment]
Oui, la ligne qui suit « semper » a moins d'espace après la ligne que la ligne précédente.

**Comment by adunning** [comment]
C'est plus évident avec le paquet setspace:

![screen shot 2019-02-25 at 11 36 10](https://user-images.githubusercontent.com/1084407/53352839-8ddf3480-38f1-11e9-8f0f-b09a2e9d2df1.png)

```latex
\documentclass{article}

\usepackage{setspace}
\setstretch{1.5}

\usepackage[series={A}]{reledmac}
\Xgroupbyline

\usepackage{mwe}

\begin{document}

\beginnumbering
\autopar

\edtext{test}{\Afootnote{\blindtext}} \blindtext\edtext{test}{\Afootnote{\blindtext}} \blindtext\edtext{test}{\Afootnote{\blindtext}}

\endnumbering

\end{document}
```

Sans `\Xgroupbyline`:

![screen shot 2019-02-25 at 11 37 38](https://user-images.githubusercontent.com/1084407/53352942-c1ba5a00-38f1-11e9-8a36-f05da40a4f94.png)

**Comment by maieul** [comment]
A tester avec la nouvelle version, mais j'ai pas d'outil de mesure précise dans le train

**Comment by maieul** [comment]
@adunning des nouvelles?

**Comment by adunning** [comment]
Merci - j'ai le même problème avec la branche issue803, <https://github.com/maieul/ledmac/commit/e5749a72c4fe60a38d5fbee350a23cdb4b302854>.

**Comment by maieul** [comment]
forcément, si je teste sur des versions sans Xgroupbyline, je ne peux pas voir le problème...

**Comment by adunning** [comment]
Oui, c'est seulement un problème avec `\Xgroupbyline`.

**Comment by maieul** [comment]
Peux tu tester la nouvelle version?

J'ai également corrigé le fait qu'il y avait une indentation, ce qui n'est pas le cas normalement pour les notes de reldmac (sauf avec Xparindent)

**Comment by adunning** [comment]
Oui, ça marche ! Mais elle a encore le problème #807.

**Comment by maieul** [comment]
J'ai rouvert #807, pour régler le problème la bas.
