### ISSUE TITLE
Boucle infinie avec \Xgroupbyline et un long texte dans \edtext

### ISSUE THREAD

**Issue by adunning** [maieul/ledmac#807]
# Version

branch `issue802`, https://github.com/maieul/ledmac/commit/cf4c0a186d6861a9a29027e0dbcc42aa0cbdee9f

# Regression

Ce problème ne se produit pas dans la version publiée.

# Description

Quand j'utilise `\Xgroupbyline` avec un long texte dans `\edtext`, reledmac ne marche pas: une boucle infinie se produit. Cet MWE fonctionne si je supprime `\Xgroupbyline` ou utilise un texte de un or deux mots dans `\edtext`.

Avec l'interruption du processus, la fin du carnet:

```
Section 1 (./test.1)
\openout3 = `test.1'.

\openout4 = `test.Aend'.

 (./test.eledsec1)
\openout5 = `test.eledsec1'.


! Interruption.
\printlines ...ined \linerangesep@ \linerangesep@ 
                                                  \else \csuse {Xlinerangese...
l.13 \endnumbering
```

# Minimal Working Example

```latex
\documentclass{article}
\usepackage[series={A}]{reledmac}
\Xgroupbyline
  
\usepackage{mwe}
\begin{document}

\beginnumbering
\autopar

\edtext{\blindtext}{\Afootnote{test}}

\endnumbering

\end{document}
```

**Comment by maieul** [comment]
je ferme, dans la mesure où il s'agit d'un problème dans le dev courant de #801

**Comment by maieul** [comment]
On rouvre, je croyais avoir résolu, mais j'ai du remettre un problème.

**Comment by maieul** [comment]
@adunning merci de tester la branch issue807. Je pense que j'ai du avoir un bug dans un report depuis le .sty vers le .dtx.

**Comment by adunning** [comment]
C'est absolument fantastique. La branche `issue807` corrige tous les problèmes avec `\Xgroupbyline`. Merci beaucoup pour votre persévérance !

**Comment by maieul** [comment]
de rien! du coup je vais pouvoir releaser le 3 mars avant minuit, ce que j'esperais (sinon fallait que je change tout)

**Comment by adunning** [comment]
Je l'ai testé avec le livre sur lequel je travaille ainsi qu'avec mes MWEs. C'est parfait. Merci encore !
