### ISSUE TITLE
Reledmac compiling with empty notes

### ISSUE THREAD

**Issue by apollo77x** [maieul/ledmac#810]
# Version

2019/01/22 v2.30.0

# Regression

I believe the last working version of reledmac/reledpar I used was 2 years ago.

# Description

I have been working on this project for at least 4 years; I left it alone for maybe the past 2 years, and when I tried to compile it again after updating all my latex packages, the footnotes in Devanagari (Indian) script do not appear, there is only blank space.  The roman text does appear, there is only empty space where the Devanagari should be.  Also they appear as endnotes at the end of the section, not as footnotes at the bottom of each page.  I am also using Tibetan script, which does not appear, but I only put in Devanagari in the MWE.   

I believe it is something to do with the updated packages, as it was working maybe 2 years ago, and I haven't changed anything else since then.

# Minimal Working Example

\documentclass{article}

\usepackage{reledmac}
   
\usepackage{reledpar}

\usepackage{fontspec}

\usepackage{polyglossia}
    \setmainlanguage{english}
    \setotherlanguage{sanskrit}
    \setotherlanguage[numerals=false]{tibetan}
    \newfontfamily\devanagarifont{Nakula}
    \newfontfamily\tibetanfont{Jomolhari}

\begin{document}

\numberlinefalse

\begin{pairs}

\begin{Leftside} 

\setstanzaindents{0,0,0}

\beginnumbering
\autopar

\devanagarifont
\begin{sanskrit}

\stanza
\edtext{महा}{\Afootnote{माद्}}भिज्ञापरीकर्म अविवादेन देशितम्।&
विवादे यस्तु चरति नोद्गृह्णन् स विमुच्यते॥१॥\&

\stanza
अभिज्ञा तस्य \edtext{सा}{\Afootnote{स}} प्रज्ञा बोद्धं ज्ञानमचिन्तियम्।&
उद्ग्रहे यः स्थितो भोति ज्ञानं तस्य न विद्यते॥२॥\&

\stanza	
बहवो ऽचिन्तिया धर्मा ये शब्देन प्रकाशिताः।&
यस्तत्र निविशेच्छब्दे सन्धाभाष्यं न जानति॥३॥\&

\end{sanskrit}

\endnumbering

\end{Leftside}

\begin{Rightside} 

\setstanzaindents{0,0,0}
 
\beginnumbering
    \autopar

\tibetanfont
\begin{tibetan}

\stanza
།མངོན་ཤེས་ཆེན་པོ་ཡོངས་སྦྱངས་པ། །\edtext{རྩོད་}{\Bfootnote{ཙོད་}}པ་མེད་པར་བསྟན་པ་སྟེ།&
།རྩོད་པ་དག་ལ་གང་སྤྱོད་ཅིང་། །འཛིན་པར་བྱེད་པ་དེ་མི་ཐར། ༡\&

\stanza
།མངོན་ཤེས་དེ་ཡི་ཤེས་རབ་སྟེ། \edtext{།སངས་}{\Bfootnote{སང་}}རྒྱས་ཡེ་ཤེས་བསམ་མི་ཁྱབ།&
།འཛིན་པ་ལ་ནི་གང་གནས་པ། །དེ་ལ་ཡེ་ཤེས་ཡོད་མི་འགྱུར། ༢\&

\stanza
།གང་དག་སྒྲ་ཡིས་བསྟན་པ་ཡི། །ཆོས་རྣམས་མང་པོ་བསམ་མི་ཁྱབ།&
།སྒྲ་དེ་ལ་ཡང་གང་ཆགས་པ། །དགོངས་པའི་བཤད་པ་མི་ཤེས་སོ། ༣\&

\end{tibetan}

\endnumbering

\end{Rightside}

\end{pairs}

\Columns

\end{document}

[big MWE.pdf](https://github.com/maieul/ledmac/files/3005660/big.MWE.pdf)

**Comment by maieul** [comment]
thanks. I will try to look on it this week-end

**Comment by maieul** [comment]
I don't understand why you told that produce endnote. I get footnote. For the blank, I will look on.

**Comment by maieul** [comment]
also, \footnoteA should not be the second argument of an `edtext`, it should be `Afootnote`

**Comment by maieul** [comment]
4932e788b9f658f05ad95dc06585f462855a2bde created the bug with the font

**Comment by apollo77x** [comment]
Ah, thank you.  In my longer edition, all of the footnotes come out at the end of the document.  Maybe they are still formatted as footnotes, but they come out at the end rather than at the bottom of each page.

**Comment by apollo77x** [comment]
So the problem is related to 4932e78.  Not sure what I should do to fix it.  Thanks for your time.

**Comment by maieul** [comment]
Hum,

I can't understand why it does that.

I will debug the bug with the font tomorrow.

Please open an other issue for this bug of endnote, with a example that
reproduce it. 

More globally, if you have two problem, open two issues

**Comment by maieul** [comment]
the link was for myself. I will do the fix tomorrow. It is not complex,
but I have no time yet.

**Comment by apollo77x** [comment]
OK, thanks.  I appreciate it.

**Comment by apollo77x** [comment]
Sorry my MWE was all wrong, when I put in \Afootnote instead of \footnoteA it worked (I haven't used latex in a while!).  But the problem is persisting in my edition.  I will have to make a new MWE.  thanks for your patience.

**Comment by apollo77x** [comment]
OK, I have been able to reproduce my problem with a larger MWE.  I am using many custom commands, and the problem seems to be with either the commands, or the formatting.  There are many "overfull hbox" errors, and it may something to do with that.  I will edit the MWE in the original post.

**Comment by apollo77x** [comment]
Also in my edition I have both a prose section and a verse section; the problem is only happening with the verse section, so I have only included verses in my MWE.

**Comment by apollo77x** [comment]
Hold on I will try to simplify it for you.

**Comment by apollo77x** [comment]
OK I have simplified the MWE.  The problem is something to do with the verse formatting.

**Comment by apollo77x** [comment]
I have figured out what the problem is.  For the verse section of my edition (I have a prose and verse section),  I have turned the line numbering off with \numberlinefalse, because I am using verse number, and not line number, in the apparatus to refer to the body of the text.  It is this command that is causing the variants (but not the lemmas!) in the apparatus to not appear.  When I do not have the command \numberlinefalse, everything appears normally in the apparatus, but this is also a small problem because I don't need line numbers in the verse portion of my edition.   I have updated the MWE accordingly.

**Comment by maieul** [comment]
in any case, please open a new issue.

**Comment by maieul** [comment]
please try issue810 branch, for the problem with the font.

**Comment by maieul** [comment]
@apollo77x I wait for your test

**Comment by maieul** [comment]
I publish now on CTAN.
