### ISSUE TITLE
reledpar compiling with empty notes due to \numberlinefalse command

### ISSUE THREAD

**Issue by apollo77x** [maieul/ledmac#816]
# Version

2019/01/22 v2.30.0

# Regression

I believe the last working version of reledmac/reledpar I used was 2 years ago.

# Description

I have been working on this project for at least 4 years; I left it alone for maybe the past 2 years, and when I tried to compile it again after updating all my latex packages, the footnotes in Devanagari (Indian) and Tibetan script do not appear.  All of the English text does appear, and the Tibetan/Devanagari text in the lemma does appear; it is only the Asian scripts within the body of the footnote text that do not appear.  

This bug is triggered by using the \numberlinefalse command.  If this command is left out, everything works normally.  

The bug also only happens if the file uses reledpar to create a dual-text edition (in my case, with left and right columns). 

This wasn't happening the last time I compiled the project using an older version of latex.

# Minimal Working Example

```
\documentclass{article}

\usepackage{reledmac}
   
\usepackage{reledpar}

\usepackage{fontspec}

\usepackage{polyglossia}
    \setmainlanguage{english}
    \setotherlanguage{sanskrit}
    \setotherlanguage[numerals=false]{tibetan}
    \newfontfamily\devanagarifont{Nakula}
    \newfontfamily\tibetanfont{Jomolhari}

\begin{document}

\numberlinefalse

\begin{pairs}

\begin{Leftside} 

\setstanzaindents{0,0,0}

\beginnumbering
\autopar

\devanagarifont
\begin{sanskrit}

\stanza
\edtext{महा}{\Afootnote{माद्; \textenglish{A}}}भिज्ञापरीकर्म अविवादेन देशितम्।&
विवादे यस्तु चरति नोद्गृह्णन् स विमुच्यते॥१॥\&

\stanza
अभिज्ञा तस्य \edtext{सा}{\Afootnote{स; \textenglish{A}}} प्रज्ञा बोद्धं ज्ञानमचिन्तियम्।&
उद्ग्रहे यः स्थितो भोति ज्ञानं तस्य न विद्यते॥२॥\&

\stanza	
बहवो ऽचिन्तिया धर्मा ये शब्देन प्रकाशिताः।&
यस्तत्र निविशेच्छब्दे सन्धाभाष्यं न जानति॥३॥\&

\end{sanskrit}

\endnumbering

\end{Leftside}

\begin{Rightside} 

\setstanzaindents{0,0,0}
 
\beginnumbering
    \autopar

\tibetanfont
\begin{tibetan}

\stanza
།མངོན་ཤེས་ཆེན་པོ་ཡོངས་སྦྱངས་པ། །\edtext{རྩོད་}{\Bfootnote{ཙོད་; \textenglish{B}}}པ་མེད་པར་བསྟན་པ་སྟེ།&
།རྩོད་པ་དག་ལ་གང་སྤྱོད་ཅིང་། །འཛིན་པར་བྱེད་པ་དེ་མི་ཐར། ༡\&

\stanza
།མངོན་ཤེས་དེ་ཡི་ཤེས་རབ་སྟེ། \edtext{།སངས་}{\Bfootnote{སང་; \textenglish{B}}}རྒྱས་ཡེ་ཤེས་བསམ་མི་ཁྱབ།&
།འཛིན་པ་ལ་ནི་གང་གནས་པ། །དེ་ལ་ཡེ་ཤེས་ཡོད་མི་འགྱུར། ༢\&

\stanza
།གང་དག་སྒྲ་ཡིས་བསྟན་པ་ཡི། །ཆོས་རྣམས་མང་པོ་བསམ་མི་ཁྱབ།&
།སྒྲ་དེ་ལ་ཡང་གང་ཆགས་པ། །དགོངས་པའི་བཤད་པ་མི་ཤེས་སོ། ༣\&

\end{tibetan}

\endnumbering

\end{Rightside}

\end{pairs}

\Columns

\end{document}
```
[big MWE.pdf](https://github.com/maieul/ledmac/files/3009545/big.MWE.pdf)

**Comment by maieul** [comment]
c2c2f9cfd0a770d4d11183278d835b5360412a1d make the problem. But coming back to the previous code will add a more important bug. I won't fix #816, but juste add some information into the handbook.
