### ISSUE TITLE
stanza's sethangingsymbol ignored with numberlinefalse

### ISSUE THREAD

**Issue by urrameu** [maieul/ledmac#822]
# Version

Verified in both version 2019/02/22 v2.31.0 and version 2017/01/22 v2.17.1 .

# Regression

I do not know if this ever worked before.

# Description

When typesetting a ``\stanza`` with ``\numberlinefalse``, ``\sethanginsymbol`` has no effect; the continuation line is indented, which is the default, but that behaviour cannot be customized.

From what I can tell, ``\do@line`` does this:

```latex
\ifnum\@lock>\@ne
    \inserthangingsymboltrue
  \else
    \inserthangingsymbolfalse
```

But ``\@lock`` is calculated by ``\getline@num``, which does not go all the way with ``\numberlinefalse``, so ``\@lock`` is always zero (I think). How to solve this, however, is beyond my LaTeX expertise. This happens both with reledmac and reledpar.

# Minimal Working Example

```latex
\documentclass{article}
\usepackage{mwe}
\usepackage{reledmac}

\sethangingsymbol{\protect\hfill[\,}

\begin{document}

\numberlinefalse
\setstanzaindents{1,0}
\firstlinenum{1}

\beginnumbering
  \stanza
    This is a very, very long line that takes so
    much space that it definitely causes a line break\&
\endnumbering

\end{document}
```

If someone ends up here before this gets addressed, there are two simple workarounds: either ``\firstlinenum{999999}`` or ``\AtEveryPstart{\hidenumbering}`` can "solve" the problem.

Thanks!

**Comment by maieul** [comment]
\numberlinefalse was not a good idea. It is a feature which create more
problem than it solve. In the future, I will delete this feature.

You can just set a big firstlinenum

for example 


\firstlinenum{99999999}
