### ISSUE TITLE
A filter to export from Org Mode to reledmac

### ISSUE THREAD

**Issue by JuanManuelM** [maieul/ledmac#823]
Hi,

I\'ve made [a very simple filter](https://gitlab.com/maciaschain/critical-marks) (based on regexp) to export from the Emacs Org mode to a LaTeX document for `reledmac`. It consists of a set of functions for Gnu Emacs that run in the export post-process from Org Mode to LaTeX. Its aim is to replace a series of simple textual marks with the basic macros of reledmac. The critical and familiar notes can be added to the `*.org` file as simple native footnotes. The reason for writing this is because I use Org Mode very much for my notes and my writings. I don\'t know if it will be useful to someone else :-)

**Comment by maieul** [comment]
I don't know anything to emacs. What is the relationship with your previous contribution #823?

**Comment by Doc73** [comment]
Many thanks!
A great reason to restart using org-mode after so many years.

@maieul 
I'd suggest to switch to emacs: it is the best editor for LaTeX etc. etc.

**Comment by maieul** [comment]
@dominco : I use vim, and I don't want to learn any new thing.

**Comment by JuanManuelM** [comment]
Anyway, this filter only exports the most basic reledmac macros. The idea is to be able to start working on a critical edition from a lightweight markup format like Org Mode, which is very similar to Markdown.

**Comment by maieul** [comment]
I see,

well,
please open a pull request on reledmac.dtx handbook in which you rewrite
the presentation I made of your tools for emacs...

**Comment by JuanManuelM** [comment]
OK, thank you very much!

(Another reason to write that filter, by the way, is that many
colleagues only use word for their critical editions, and and they 
end
up messing around in a pile of documents: one for the edited text, 
one for
critical apparatus, etc. I thought that if they write those simple 
marks
in their document and add the critical notes as simple (word) 
footnotes, it
would be less laborious to export all that stuff to a tex file to 
be
able to work with reledmac: word --> pandoc --> org --> LaTeX)

Best regards

Maïeul Rouquette <notifications@github.com> writes:

> I see,
>
> well,
> please open a pull request on reledmac.dtx handbook in which you 
> rewrite
> the presentation I made of your tools for emacs...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the 
> thread.
>

-- 
----------------------------------------------------------------
Juan Manuel Macías --

**Comment by adunning** [comment]
This is a great idea. Have you thought of making it into a Pandoc filter? One could notionally use this to create an edition not only for Reledmac/PDF but also HTML, EPUB, TEI, etc.

**Comment by JuanManuelM** [comment]
@adunning Thank you for your feedback.

I have thought about all these options, but the problem is the lack of time ;-) ... However, in this package for Emacs the main goal is to export to LaTeX / reledmac from a basic text in Org. In my opinion, other formats such as HTML or Epub are inferior and cannot represent the (say) "three-dimensionality" of a critical edition. The typography of the book and its "old school" is the best option here.

As for TEI, although it is useful for certain contexts, I think that it is still quite inefficient to store the data of a critical edition. And it is very abstruse and complex for most of the philologists who work in this type of books.

Regards

**Comment by adunning** [comment]
The problem is that PDFs generated by LaTeX are not accessible, and one needs other output formats. There's a great deal of potential in TEI (see e.g. <http://teicat.huma-num.fr>), but indeed it is not very easy to learn.

**Comment by JuanManuelM** [comment]
> I see, well, please open a pull request on reledmac.dtx handbook in which you rewrite the presentation I made of your tools for emacs...

Hi, @maieul . After a while, I have improved and fixed this filter to export from Emacs Org Mode to reledmac. Regarding the pull request, since I don't use Github I can't do it. Could you please add these lines to reledmac.dtx, if you find them appropriate, of course :-) ? Thank you!

``` latex
% \subsection{critical-marks for \emph{Emacs}}
% A set of functions for \emph{Emacs} that run in the export process from Org Mode to
% LaTeX and replace a series of simple textual marks with the basic \macpackage's commands (Juan Manuel Macías Chaín)
% \url{https://gitlab.com/maciaschain/critical-marks}
```

**Comment by maieul** [comment]
will be done on the next release, thansk.
