### ISSUE TITLE
Multiple lemmas referring to the same verse

### ISSUE THREAD

**Issue by piagentina** [maieul/ledmac#824]
# Version
2.31.3

# Description
I'm working on a text that employs biblical verses. I would like to avoid displaying multiple lemmas referring to the same verse and use a separator instead (as if the lemmas were from the same line)

# Minimal Working Example

```latex
\documentclass[12pt]{article}
\usepackage[total={3in, 4in}]{geometry}
\usepackage[series={A},noresetlinenumannotation]{reledmac}
\Xarrangement[A]{paragraph}
\Xnoidenticallinenumannotation
\newcommand{\bv}[1]{\linenumannotation{#1}}
\makeatletter
\Xwraplinenumannotation{\@firstofone}
\renewcommand{\linenumrep}[1]{}
\makeatother
\firstlinenum{1}
\linenumincrement{1}

\begin{document}
	\beginnumbering
	\pstart
		\bv{6} Erat autem Ioannes indutus camelinis pilis, lateribus pelliceo cingulo cinctis, vescebaturque locustis et \edtext{melle silvestri}{\Afootnote{melle}}, \edtext{atque}{\Afootnote{et}} huiusmodi verbis publice docebat:\bv{7} “Venit quidam post me, adeo me praestantior, ut ego non sim dignus qui eius calceorum corrigiam pronus solvam.”
	\pend
	\endnumbering
\end{document}
```

**Comment by maieul** [comment]
I am not sur to undsertand what you would like to get as final output. Please show me an example

**Comment by Doc73** [comment]
@piagentina 
I think all you need is `\Xnumberonlyfirstinline[A]`:

```tex
\documentclass[12pt]{article}
\usepackage[total={3in, 4in}]{geometry}
\usepackage[series={A},noresetlinenumannotation]{reledmac}
\Xarrangement[A]{paragraph}
\Xnoidenticallinenumannotation
\Xnumberonlyfirstinline[A]
\newcommand{\bv}[1]{\linenumannotation{#1}}
\makeatletter
\Xwraplinenumannotation{\@firstofone}
\renewcommand{\linenumrep}[1]{}
\makeatother
\firstlinenum{1}
\linenumincrement{1}

\begin{document}
	\beginnumbering
	\pstart
		\bv{6} Erat autem Ioannes indutus camelinis pilis, lateribus pelliceo cingulo cinctis, vescebaturque locustis et \edtext{melle silvestri}{\Afootnote{melle}}, \edtext{atque}{\Afootnote{et}} huiusmodi verbis publice docebat:\bv{7} “Venit quidam post me, adeo me praestantior, ut ego non sim dignus qui eius calceorum corrigiam pronus solvam.”
	\pend
	\endnumbering
\end{document}
```

**Comment by piagentina** [comment]
Grazie Domenico, you nailed it! One last question: what if I want to use a separator between the two lemmas (I was thinking of a vertical slash: | ). Thank you in advance.

**Comment by Doc73** [comment]
I think there is a way to customize the separators between notes in different lines and those in the same line, but try searching the word `separator` inside doc.

**Comment by maieul** [comment]
I am not at all convinced by  using `Xnumberonlyfirstinline` regarding the question asked by @piagentina. It work only because the two edtext, in this example, are in the same physical line. But, try, for example, with that

```
\documentclass[12pt]{article}
\usepackage[total={3in, 4in}]{geometry}
\usepackage[series={A},noresetlinenumannotation]{reledmac}
\Xarrangement[A]{paragraph}
\Xnoidenticallinenumannotation
\Xnumberonlyfirstinline[A]
\newcommand{\bv}[1]{\linenumannotation{#1}}
\makeatletter
\Xwraplinenumannotation{\@firstofone}
\renewcommand{\linenumrep}[1]{}
\makeatother
\firstlinenum{1}
\linenumincrement{1}

\begin{document}
	\beginnumbering
	\pstart
  \bv{6} \edtext{Erat}{\Afootnote{A}} autem Ioannes indutus camelinis pilis, lateribus pelliceo cingulo cinctis, vescebaturque locustis et \edtext{melle silvestri}{\Afootnote{melle}}, \edtext{atque}{\Afootnote{et}} huiusmodi verbis publice docebat:\bv{7} “Venit quidam post me, adeo me praestantior, ut ego non sim dignus qui eius calceorum corrigiam pronus solvam.”
	\pend
	\endnumbering
\end{document}
```

It does not work. I should add something like `Xnumberonlyfirstinlineannotation`. SHould not be complicated. Maybe i would have time tomorrow.

**Comment by piagentina** [comment]
Thank you, Maïeul.

**Comment by maieul** [comment]
I have pushed on branch issue824 an implementation of 
`\Xlinenumannotationonlyfirst`
`\Xlinenumannotationonlyfirstintwo`
`\Xsymlinenumannotation` which are the equivalent of `Xnumberonlyfirstinline` and so one, but for line number annotation.  See the file issue824.tex for an example. Please, test in a real use case, and make feedback. 

I have also to implement for end critical note, but I am waiting your feedback.

**Comment by piagentina** [comment]
Can't find the file issue824.tex. Sorry, I am quite inexperienced.

**Comment by maieul** [comment]
to test new branch, please read 
https://github.com/maieul/ledmac#debug-and-feature-requests

the file issue824.tex is included in the branch

**Comment by piagentina** [comment]
First of all, a big thank you for your time. I've managed to test-drive the new commands and they work just fine with the exception of a couple of glitches:
a) `\Xsymlinenumannotation{|}` produces an em-dash (—) in the output, while I wanted it to be a vertical bar (I've tried to input `\lvert` or `\mid` but to no avail.
b) The separator looks closer to the right side than exactly between the two lemmas. You can see this by yourself if you replace `\Xsymlinenumannotation{|}` with `\Xsymlinenumannotation{;}`

**Comment by maieul** [comment]
1) that is because you use pdflatex Ot1 font encoding. As i always use xelatex, i didn't see that. Use `\textbar` instead of directly call `|`, or use `$|$`. See 
2) between each paragraphed note, reledmac add a space which can be set with `\Xafternote`. And after line number + line number annotation, reledmac add a space which can be set with `\Xafternumber`. But the default value of these to space are not the same, because. So just add `\Xafternote{1em}` and `\Xafternumber{1em}` in your preamble at the will be set (1em, or what size you want).

**Comment by piagentina** [comment]
It works very well now. Thank you.

**Comment by maieul** [comment]
I will add today the feature for endnote, then publish on CTAN. You
should update your texlive/miktex installation in few day, and delete
your local .sty file.

**Comment by maieul** [comment]
I have just pushed the new version into the ctan.
