### ISSUE TITLE
The symbol of \Xendsymlinenum and that of \Xendsep appear together in the end notes

### ISSUE THREAD

**Issue by JuanManuelM** [maieul/ledmac#827]
Hi, sorry if the title seems a bit confusing ...

(reledmac version 2019/04/03 v2.31.2).

When I compiled the following MWE, I found a strange behavior in the end notes, when they are in paragraph format. In the footnotes, the symbol defined in `\Xsymlinenum` is inserted between notes that refer to the same line; and the symbol of `\Xparafootsep` is printed when the notes refer to different lines. All that seems right to me (img1). However, in the end notes, the symbol of `\Xendsymlinenum` appears followed by the symbol of `\Xendsep` (img2), when only the first one should appear in that context (same line) . I am doing something wrong?

(Anyway, I do not need the end notes right now. I was just testing this feature, for future work... ☺)

``` {.latex}
\documentclass{article}
\usepackage{reledmac}

%% footnotes
\Xarrangement[A]{paragraph}
\Xnumberonlyfirstinline
\Xnumberonlyfirstintwolines
\Xsymlinenum{|}
\Xafternote{0.4em plus.1em minus.1em}
\Xparafootsep{‖\hspace{0.4em plus.1em minus.1em}}

%% endnotes
\Xendparagraph[A]
\Xendnumberonlyfirstinline
\Xendnumberonlyfirstintwolines
\Xendsymlinenum{|}
\Xendafternote{0.4em plus.1em minus.1em}
\Xendsep{‖\hspace{0.4em plus.1em minus.1em}}

\begin{document}
\beginnumbering\pstart

\edtext{Lorem ipsum}{\Afootnote{same line}\Aendnote{same line}} \edtext{dolor sit
  amet}{\Afootnote{same line}\Aendnote{same line}}, consectetuer adipiscing elit. Donec
hendrerit tempor tellus. Donec pretium posuere tellus. Proin quam nisl, tincidunt et,
mattis eget, convallis nec, purus. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Nulla posuere. Donec vitae dolor. Nullam tristique diam
non turpis. Cras placerat accumsan nulla. Nullam rutrum. Nam vestibulum accumsan
\edtext{nisl}{\Afootnote{other line}\Aendnote{other line}}.

\pend\endnumbering

\bigskip

\doendnotes{A}

\end{document}
```

![endnotes2](https://user-images.githubusercontent.com/25255465/61547904-a391f980-aa4c-11e9-9df8-923ac930fe69.png)

![endnotes1](https://user-images.githubusercontent.com/25255465/61547919-aab90780-aa4c-11e9-8e9b-1eb7681ed0eb.png)

**Comment by maieul** [comment]
please try branch issue827.

**Comment by JuanManuelM** [comment]
Thank you! I just tried it, and the behavior is now the expected one. An "ss" appears before the | symbol. I have seen that it is on line 13849: ```{\ifcsempty{Xendsymlinenum@#4}{\csuse{Xendsep@#4}}{ss}}%``` Is it for testing purposes? Anyway, when I remove the "ss" everything seems ok.
