### ISSUE TITLE
Question: What does control familiar footnote vertical spacing?

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#830]
I just noticed that in my edition there is too much vertical space between the familiar footnotes in the part which uses reledpar (the extra space is not there on "normal" pages or between the critical notes). Could you tell me which commands are controlling this? A MWE probably won't help much here: The problem is most likely rooted the publishers style file that I am not allowed to share ...

**Comment by baem2** [comment]
Here's an example of how it looks:
![spacing](https://user-images.githubusercontent.com/5675156/69818945-264a7280-11fe-11ea-91c1-4360da67f277.jpg)

The normal footnotes outside of the parts made with reledmac do not do that ...

Any ideas?

**Comment by maieul** [comment]
hum, I don't see what could provokes such behavior, especillay with the distinction between the reledmac and reledpar parts. Are your you didn'nt introduce any special characters at the end of your footnotes? Do you have tried with default styles? If you have the same problem, that is a bug in reledmac/reledpar, and I need a MWE. If not, it is a bug in your styles, and you should try by dychotomie what line in your code could provoke that.

**Comment by baem2** [comment]
I now tried it with a rather basic MWE, and it does not look as bad as posted above, but it is still clearly visible that there is more vertical space between reledmac familiar footnotes than between normal ones. I'm running reledmac v2.32.1.

```

\listfiles
\documentclass{book}

\usepackage[english]{babel}

\usepackage[utf8]{luainputenc}

\usepackage[series={A,B,C},noledgroup]{reledmac}


\begin{document}

Lorem\footnote{A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long.} ipsum\footnote{A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long.} dolor sit amet, consectetur adipiscing elit. Fusce sed dolor libero. Aenean rutrum vestibulum lacus ut pretium. Fusce et auctor lectus. Ut et commodo quam, quis gravida orci. Nullam at risus elementum, suscipit enim a, pellentesque mi.
Morbi commodo, ligula vel consectetur accumsan,\footnote{A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long.} massa metus egestas velit, eu fringilla leo ante in turpis. Vivamus ut tellus sollicitudin, facilisis ipsum sit amet, tincidunt odio. Maecenas tincidunt dolor sed ante blandit tincidunt. Etiam vulputate ultricies facilisis.



\newpage

\beginnumbering
\pstart
Lorem\footnoteA{A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long.} ipsum\footnoteA{A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long.} dolor sit amet, consectetur adipiscing elit. Fusce sed dolor libero. Aenean rutrum vestibulum lacus ut pretium. Fusce et auctor lectus. Ut et commodo quam, quis gravida orci. Nullam at risus elementum, suscipit enim a, pellentesque mi.
Morbi commodo, ligula vel consectetur accumsan,\footnoteA{A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long. A familiar note, very long.} massa metus egestas velit, eu fringilla leo ante in turpis. Vivamus ut tellus sollicitudin, facilisis ipsum sit amet, tincidunt odio. Maecenas tincidunt dolor sed ante blandit tincidunt. Etiam vulputate ultricies facilisis.
\pend
\endnumbering

\end{document}


```
See [test.pdf](https://github.com/maieul/ledmac/files/3902624/test.pdf)

**Comment by maieul** [comment]
ok
so 
1) the problem happens also with reledmac :), not only reledpa
2) it is related to lualatex.

I am looking on it.

**Comment by maieul** [comment]
please try branch issue #830

**Comment by baem2** [comment]
Yup, right, creating a MWE once more narrowed down the issue ...

Your fix solves the problem – thank you very much!

The book will be published early next year. If you are interested in a paper copy, let me know where I can send it to! :)

**Comment by maieul** [comment]
Nice, I will publish soon on CTAN.
