### ISSUE TITLE
Issue with \Xgroupbyline and twocol 

### ISSUE THREAD

**Issue by lazzalazza** [maieul/ledmac#836]
# Version

2019/12/09 v2.32.3
LuaLaTeX 1.10.0 (TeX Live 2019)
[macOSX Catalina]

# Regression

# Description

I am working on a critical edition and I would like to produce a two-column footnote that is grouped by lines. The *Xgroupbyline* command causes a problem with the *twocol* option (the columns become weird and thin): see attached file.

Would there be a way to fix this issue? Thanks in advance for all your great work.

# Minimal Working Example

```latex

\documentclass{article}
\usepackage{lipsum}
\usepackage[latin]{babel}

\usepackage{reledmac}

\Xgroupbyline
\Xarrangement[A]{twocol}

\begin{document}
\beginnumbering
\pstart
Arma \edtext{virumque} {
	\Afootnote{\lipsum[1]}
} \edtext{cano}{
	\Afootnote{\lipsum[1]}
}.
\pend
\endnumbering
\end{document}

```
[problem.pdf](https://github.com/maieul/ledmac/files/4140658/problem.pdf)

**Comment by maieul** [comment]
please try branch issue836

**Comment by lazzalazza** [comment]
Je ne sais pas vraiment comment te remercier: ça marche splendidement! ;)

**Comment by maieul** [comment]
super,

je publierai cela prochainement dans une future release

**Comment by lazzalazza** [comment]
Merci encore!

**Comment by maieul** [comment]
je vais publier cela aujourd'hui.
