### ISSUE TITLE
Footnotes in two columns are spread out when using bidi package.

### ISSUE THREAD

**Issue by Alatius** [maieul/ledmac#837]
# Version
Tested with both reledmac 2018/02/28 v2.26.6 and 2019/12/09 v2.32.3.

# Description
When using the bidi-package in XeLaTeX, it has the side effect that reledmac's footnotes in two columns will be spread out vertically. Note that there is more space above each footnote, and how footnote 3 is not aligned with footnote 1. If you remove \usepackage{bidi}, the footnotes will look correct.

# Minimal Working Example
```latex
\documentclass[12pt]{article}

\usepackage[series={A},nocritical,noend]{reledmac}
\arrangementX[A]{twocol}

\usepackage{bidi} % Removing this line fixes the spaced out footnotes.

\begin{document}

Text.\footnoteA{Footnote 1.}\footnoteA{Footnote 2.}\footnoteA{Footnote 3.}

\end{document}
```

**Comment by maieul** [comment]
Hum,

the problem is that both reledmac and bidi redefine footnote layout. I wrote to the bidi author, but it does not seem to want to collaborate in order to prevent such conflict. So....

**Comment by maieul** [comment]
I think I found a workaround. Please try issue837 branch, also with real use case of rtl footnote in two/three column,

**Comment by Alatius** [comment]
Thank you very much! It looks great now for me, with Latin characters in the footnote. I don't actually work with RTL text, so I don't have a good real use case to test with. I only found this issue because I had to include a short quote in Hebrew in the main text.
