### ISSUE TITLE
Lineation problématique de deux lignes consécutives avec Reledmac, arabe et LuaLaTeX 

### ISSUE THREAD

**Issue by yadaddi** [maieul/ledmac#839]
# Version

Package: reledmac 2019/07/21 v2.32.1 typesetting critical editions

# Regression

# Description

Les numéros de lignes (quand il y a un intervalle) sont inversés dans les notes critiques. En arabe, le 1er nombre est à droite, suivi d'un tiret, puis du 2e nombre. La combinaison Reledmac+LuaLaTeX ignore l'ordre en RTL.

# Minimal Working Example

```latex
```
\documentclass{article}
\usepackage[english,french, bidi=basic]{babel}
\babeltags{ar = arabic}
\babelfont{rm}{Crimson}
\babelfont[*arabic]{rm}{Amiri}
\usepackage{arabluatex}
\usepackage[series={A,B}]{reledmac}
\Xarrangement{paragraph}
\Xbhookgroup[A]{\pardir TRT\textdir TRT}
\Xlemmaseparator[A]{[} 
\Xafterlemmaseparator[A]{0.5em}
\Xbeforelemmaseparator[A]{0.25em}
\Xwrapcontent[A]{\txarb}
% I think the following is needed to print subsequent line numbers in
% LTR:
\Xbhooknote[A]{\textdir TRT}
\firstlinenum{1} \linenumincrement{1} \lineation{page}

\renewcommand{\Afootnoterule}{%
  \hfill\noindent\rule[1mm]{.4\textwidth}{.15mm}}

\begin{document}
  \beginnumbering
  \pstart[\setRL\arabicfont] %
  انطلقت الثورة الليبية منذ أكثر من سنة
  متوازية مع ثورات الربيع العربي الأخرى التي أطاحت ببعض حكام البلدان
  العربية، وما إن وافقت الجامعة العربية وأمريكا وأوروبا على ضرورة تدخل
  \edtext{\txarb{منظمة حلف شمال الأطلسي}}{\Afootnote{الأمم المتحدة}}
  في المسألة حتى دخلت تركيا على الخط وقامت بإيصال مواد إغاثية وعسكرية
  دعما للثوار الليبيين. وهذا التدخل التركي يعكس الواقع الجديد في ملف
  العلاقات الخارجية بين تركيا والشرق الأوسط، ألا وهو  \edtext{ تعاظم دور تركيا}{\Afootnote{ تزايد الدور التركي}}    في العالم الناطق بلغة الضاد، حيث باتت تركيا تنتهج سياسة خارجية نشطة  في القضايا الشائكة والعالقة في \edtext{\txarb{الشرق
      الأوسط}}{\Afootnote{الشرق عموما}} ومع هذا الاتجاه الجديد في
  سياسات تركيا، ينبغي تحديد معالم دور تركيا الجديد، ومحددات هذا الدور
  في ضوء التغيرات الأخيرة في المنطقة، وكذلك تحديد آراء العرب حيال
  الموقف التركي في الشرق الأوسط.
  \pend
  \endnumbering
\end{document}
```
```

**Comment by maieul** [comment]
il faut que je penche du coté de la résolution de #397

**Comment by maieul** [comment]
Il y  avait un bug dans LuaTeX, qui était contourné en #397, mais cela provoquait #389. Le bug est visiblement fini. merci de tester la branch issue397.

**Comment by yadaddi** [comment]
Maintenant tous les numméros composant les chiffres sont inversés. On a 21 au lieu de 12, etc.

**Comment by maieul** [comment]
arf ! 

Donc le chiffres les nombres se lisent de gauche à droite, mais les séquences de droite à gauche ?

**Comment by maieul** [comment]
Hum,

est-ce que le résultat en patchant selon 8a1649df est correct ?

Si oui, cela veut dire qu'il faut modifier localement la direction. Mais je ne peux pas l'appliquer par défaut, car j'imagine que dans certaines langues, si on n'écrit pas en chiffre arabe, alors il faut que ce soit en RTL. 

Je pourrais proposer un hook de début de \linenumrep, mais je ne suis pas convaincu, d'autant que ce hook serait surchargé si une personne redefini lui-même \linenumrep. Est-ce que cela vaut la peine d'avoir des réglages différnets selon les series? Si oui, un hook a du sens.

Dans tous les cas, je pense qu'il est plus qu'urgent de publier enfin ce tutoriel sur RTL et reledmac, parce qu'il y a plein de question/réponse partout, et moi même je suis perdu.

**Comment by yadaddi** [comment]
Oui! Ca marche très bien sans la commande \setlinenum{123}
Ca me donne l'erreur de compilation suivante, alors que j'ai la version 1.10.0 de LuaTeX
(/TeXlive/2019/texmf-dist/tex/generic/iftex/ifxetex.sty)
! Undefined control sequence.
l.144     \reledmac@error
                       {You need to use LuaTeX 1.1.0 or higher}{\@ehc}%
Mais en tapant sur Entrée, ça compile sans problème.

**Comment by maieul** [comment]
oui, j'avais aussi corrigé ce problème dans la toute dernière version 

la commande \setlinenum était juste là pour me permettre d'avoir des
nombres a plus d'un chiffre.

En tout cas la publication ne se fera pas avant 10 jours. Est-ce que tu
pense pouvoir d'ici là faire un petit document synthétique sur lualatex
/ rtl + reledmac.

Je vois les choses suivantes :
- sens du texte
- sens des notes
- sens des chiffres dans les notes
- etc

**Comment by yadaddi** [comment]
Je vais essayer... Avec ton assistance et celle de @ralessi !
J'ai commencé hier à voir LuaTeX de près ainsi que Babel.
Je vais préparer un texte modèle... et l'on démarre à partir de là.

**Comment by maieul** [comment]
ce qui serait bien, je pense, serait de lister d'abord
1) les commandes de direction en Luatex
2) les lieux où l'on peut les insérer dans reledmac

**Comment by yadaddi** [comment]
Ah! Je vois ce que tu veux! Je crois que Robert Alessi @ralessi est le spécialiste, puisqu'il a écrit ArabLuaTeX. Ça serait incongru de m'y mettre.

**Comment by yadaddi** [comment]
Je viens de remarquer que les notes normales sont toutes en TLT.

**Comment by ralessi** [comment]
> Ah! Je vois ce que tu veux! Je crois que Robert Alessi @ralessi est le spécialiste, puisqu'il a écrit ArabLuaTeX. Ça serait incongru de m'y mettre.

`arabluatex` n'utilise cependant ni `babel` ni `polyglossia`, mais seulement les primitives de `luatex`. À noter aussi qu'il existe un package `luabidi` qui a été mis à jour cette année et qui devrait fonctionner.

**Comment by yadaddi** [comment]
> `arabluatex` n'utilise cependant ni `babel` ni `polyglossia`, mais seulement les primitives de `luatex`. À noter aussi qu'il existe un package `luabidi` qui a été mis à jour cette année et qui devrait fonctionner.

N'est-ce pas l'idée de Maieul? https://geekographie.maieul.net/199
De mon côté j'explore Luatex et je constate que les commandes \pagedir et \bodydir sont très instables. Y'a-t-il moyen de les contourner? J'ai fait des essais et ça marche pas mal avec ArabLuaTeX et Luabidi. Mais j'ai encore des soucis.

**Comment by ralessi** [comment]
> N'est-ce pas l'idée de Maieul? https://geekographie.maieul.net/199

Le document en ligne date de 2016. Question: est-ce que les conseils qui y sont donnés fonctionnent toujours avec le reledmac d'aujourd'hui? Une idée serait de le mettre à jour.

> De mon côté j'explore Luatex et je constate que les commandes \pagedir et \bodydir sont très instables. Y'a-t-il moyen de les contourner? J'ai fait des essais et ça marche pas mal avec ArabLuaTeX et Luabidi. Mais j'ai encore des soucis.

En ce qui concerne arabluatex, si l'on souhaite insérer du texte arabe unicode, il faut penser à utiliser \txarb{} plutôt que \arb{} qui est fait pour interpréter des séquences ASCII. Même chose pour les paragraphes en arabe unicode: la commande est \begin{txarab} ... \end{txarab}, et non pas \begin{arab} ... \end{arab}.

Pour les primitives de direction luatex, le mieux est de consulter la documentation de luatex (texdoc luatex): "3.3 Directions", p. 51, et pour le moment de s'appuyer sur \textdir, \linedir et \pardir.

**Comment by yadaddi** [comment]
> Le document en ligne date de 2016. Question: est-ce que les conseils qui y sont donnés fonctionnent toujours avec le reledmac d'aujourd'hui? Une idée serait de le mettre à jour.

Avis au spécialistes! Je ne puis rien dire sur ce point.


> En ce qui concerne arabluatex, si l'on souhaite insérer du texte arabe unicode, il faut penser à utiliser \txarb{} plutôt que \arb{} qui est fait pour interpréter des séquences ASCII. Même chose pour les paragraphes en arabe unicode: la commande est \begin{txarab} ... \end{txarab}, et non pas \begin{arab} ... \end{arab}.

J'ai consulté votre excellent ArabLuaTeX et j'ai effectivement noté les différences que vous soulignez. J'ai également des textes en ASCII.


> Pour les primitives de direction luatex, le mieux est de consulter la documentation de luatex (texdoc luatex): "3.3 Directions", p. 51, et pour le moment de s'appuyer sur \textdir, \linedir et \pardir.

Est-ce que cela signifie que la commande \bodydir, notamment, qui figure dans Reledpar doit être éliminée, même temporairement? 
J'ai consulté la documentation LuaTeX, j'ai fait toutes les combinaisons possibles sans parvenir à un résultat final satisfaisant pour Reledpar. Il y a toujours quelque chose qui ne fonctionnne pas comme il se doit. 

J'ai ouvert un nouveau ticket et y ai posté un exemple dans le lien suivant: https://github.com/maieul/ledmac/issues/843

Du reste, ArabLuaLaTeX et Luabidi semblent bien fonctionner avec Reledmac, sans problème majeurs..., à part le problème des numéros de lignes consécutives, mentionnné dans ce lien https://github.com/maieul/ledmac/issues/839 et qui revient, mlagré l'insertion de la commande sugérée par Maïeul. Il  y'a aussi la macro \variant qui ne fonctionne pas bien...

Voici un exemple en ASCII:

```
\documentclass[12pt]{book}
\usepackage[paper=16cm:24cm]{typearea}
\usepackage[top=2.5cm,bottom=2.5cm,left=2.2cm,right=2.2cm]{geometry}
\usepackage[series={A,B},noend,noledgroup,nopenalties]{reledmac}
\usepackage[no-math]{fontspec}
\usepackage{perpage}
\setmainfont{Amiri}
\newfontfamily\arabicfont{Amiri}[Script=Arabic, Mapping = arabicdigits]
\usepackage{newunicodechar}
\usepackage{xcolor}
\usepackage{setspace}
\onehalfspacing
\usepackage[novoc]{arabluatex}
\usepackage{luabidi}
\Xarrangement{paragraph}
\Xbhookgroup[A]{\pardir TRT\textdir TRT} %
\newcommand{\n}         [1]     % for digits inside Arabic text
    {\bgroup\textdir TLT #1\egroup}
\bhooknoteX[A]{\pardir TRT \textdir TRT} %Adds nothing
\firstlinenum{1} \linenumincrement{1} \lineation{page}
\NewDocumentCommand{\arnote}{m}{\footnoteA{\txarb{#1}}}
\NewDocumentCommand{\ennote}{m}{\footnoteB{#1}}
\NewDocumentCommand{\commentaire}{m}{\footnoteB{\txarb{#1}}}
%Critical Notes
\newcommand{\variant}[3]{\edtext{\arb{#1}}{\Afootnote{\arb{#2} : \arb{#3}}}}
\newcommandx{\om}[2]{\variant{\arb{#1}}{\txarb{محذوفة من}}{\arb{#2}}}
\newcommandx{\add}[3]{\variant{\arb{#1}}{\txarb{#3}}{\arb{{زائدة في}} #2}}
\MakePerPage{footnoteA}
\MakePerPage{footnoteB}
\MakePerPage{Afootnote}
\newenvironment{en}     % Arabic paragraph
    {\textdir TLT \pardir TLT \enfont}{}
\sidenotemargin{right}
\rightfootnoterule
\newcommand{\transw}[1]{\arb[trans]{#1}}
\SetArbEasy
\pretocmd\linenumrep{%
 \textdir TLT%
}{}{}

\Xsymlinenum{$||$}

\begin{document}

\linenummargin{left}
\beginnumbering
\pstart[\setRTLmain] 
\parindent=0pt
\begin{arab}
 
% Doc 1
 al-.hamdu li-lahi .ha.dara 
 ladY ^sahIdayhi wa-bi-al-ma.hkamaTi \edtext{\arb{al-.hanafiyaTi}}{\Afootnote{\arb{al-mAlikiyaT}}} min baladi al-^gazAyiri al-ma.hmiyaTi 
 bi-ala-lahi ta`AlY amAma \edtext{\arb{al-^say_hi al-qA.dI }}{\Afootnote{\arb{al-qA.dI al-^say_h}}} .fI  al-tArI_hi ayadahu ala-lahu al-wA.di`i .tAbi`ahu

 al-rafI`i a`lAhu dAma `izahu wa `alAhu al-`Alim al-`alAmah al-ba.hr al-fahAmah al-mu.haqiq

 al-muwafaqi al-sayid mu.hamad muftI al-sAdAti al-mAlikiyaTi al-.hnafiyaT kAna ibn al-mar.hUmi bi-karami al-.hayi

 al-qayUmi al-sayid al-.hA^g ibrAhIm bin mUsY bihi ^sahida wa-a^shadahumA\footnoteA{.hwl ^sahida wa-a^shada, un.zr: \LR{Beaussier,  \textit{dictionnaire}, p. 348}} `alY nafsihi

 anahu a`taqa ^gamI`a al-^gU^gAn al-.sa.gIri al-_dI [\om{yaq.suru}{b}] al-wa.sfu `anhu li-.si.garihi al-musamY

 bi-al-_hayri `arabI al-lisAni `itqaN ^gAyizaN nA^gizaN a.tlaqahu min .habli al-riqi wa al-`ub--

 al-`ubUdiyaTi wa-al.haqahu bi-.harAyiri al-muslimIna fImA lahum wa-`alayhim ya_dhabu .hay_tu ^sA'a

 lA sabIla li-a.hadiN min _halqi ala-lahi `alayhi `adY sabIla al-walA'i liman .hakamat bihi al-^sarI`aTi

 al-mu.hamadiyaTi `alY .sA.hibihA af.dala al-.salATi wa-azkY al-ta.hiyaTi qa.sada bi-_dalika wa^gha ala-lahi

 al-`a.zImi wa-ra^gA'a _tawAbihi al-^gasImi ina ala-laha yu^gzI al-muta.sadiqIna wa-lA yu.dI`u a^gra

 al-mu.hsinIna wa-_dAlika min _tulu_ti mu_halafAti al-waliyah 'Aminah bint bU^samAyim [.hasbamA ]

 _dAlika bi-rasmi bi-yad .sA.hibi al-_tulu_ti al-mu`t"aqi al-ma_dkUri ra^gA'a an yu`tiqa ala-lahu

 bi-kuli `u.dwiN minhu `u.dwaN min mu`tiqatihi mina al-nAri kamA ^gA'a fI .sa.hI.hi al-a_hbAri

 `ani al-nabI al-mu_htAri .salY ala-lahu `alayhi wa salama 'AnA' al-layli wa a.trAfa al-nahAri `alayhi

 bi-_dAlika wa-huwa bi-al-.hAlaTi al-^gAyizaTi ^sar`aN wa-`arafahu bi-tArI_hi awAyili [_dI] al-.h^gaTi al-.harAmi `aAma

 i_tnayni wa-arba`Ina wa mA'yatayni wa alfiN\footnoteA{\LR{26} جوان \LR{1827}}

 `abd al-ra.hman... 
 
 %\hspace{5cm} 
 
  mu.hamad...

 `aqd al-`itq mtA` bi-al-_hayr
 \end{arab}
\pend
\endnumbering




%Doc 2
\beginnumbering
\pstart[\setRTLmain] 
\parindent=0pt
\begin{arab}

 al-.hamd li-ll"ahi bayn yaday al-^say_h al-imAm al-`Alm al-`alAmaT al-humAm al-qudwT al-fahAmaT qA.dI al-mAlikiyaT

 bi-al-^gazAyir fI al-tArI_h ayadahu al-l"ah ta`AlY wa huw al-sayid qadUr ['im.d--------A']

 wa saradahu a^shad"a al-mukaram al-sayid al-.hA^g mu.hamad al-mad`U al-a`ra^g bin `abd al-qAdir al-milyAnI nasabaN

 ^sahIdayhi `alY nafsihi anahu b------------A`a min al-sayid qadUr al-.hanafI bin al-sayid mu.s.tafY bin al-_haznA^gI

 bihi ^sahar ^gamI` ^sU^sAnah al-musam"aY fAti.h wa-na`tuh kabdI ala-lwn `arabI ala-lisAn wa bi_dirA`yh

 a_tar kay [ <?>]barI bay`aN tAmaN ^gAyizaN nA^gizaN bataN batalaN bimA qadruh _hamsaT wa-arba`Una riyAlaN dUrUA

 kuluhA sikaT .sbAniyA qaba.d al-bAyi` al-ma_dkUr min al-mubtA` al-mas.tUr ^gamI`  al-`adad al-mazbUr

 mu`AyanaT li-_dlik al-qab.d al-tAm wa-abrAhu min ^gamI` mA _dkr bi-al-ibrA' al-`Am al-barA'aT al-tt"AmaT

 mu^sh--i----daN ma` _dAlik al-mubtA` al-ma_dkUr an ibtiyA`ahu limA _dukr inamA hw li-.hafIdatih al-waliyaT

 rUzaT bint al-sayid mu.hamad bin al-_haznA^gI wa min mAlihA al-_hA.s bihA dafa`a `nhA ^gamI` mA _dukir wa-yaduhu

 nAyibaT `anhA wa `AriyaT fa-b--a----`da kawn mA _dukir kamA su.t.t"ir .ha.dar al-An ladY ^sahIdayhi

 amAm man _dukir al-mukaram al-qAyid mubArak mu`taq al-waliyaT rUzaT al-ma_dkUraT ma^shUdaN lahA bimA

 _dukir wa a^sh--a--dahumA `alY nafsih anah `--a--taq fI .haq sayidatih rUzaT al-ma_dkUraT [bi-tArI_h <?>]

al-wakAlaT minhA lh birasmiN bi-yadih bi-al-`adAlaT al-mar.diyaT ^gam--I` ^sU^sAnahA al-maw.sUf al-ma_dkUr

 `--i----tqaN ^gAyizaN nA^gizaN a.tlaqahu min .habl al-riq  wa-al-`ubUdiyaT wa-al-.haqahu bi-.harAyir al-muslimIn

 fImA lahum wa-`alayhim ya_dhab .hay_t ^sA' lA sabIl lA.had min _halq ala-ll"ah `alayhi `adY

 sabIl al-walA' liman .hakamat bihi al-^sarI`aT al-mu.hamadiyaT `alY .sA.hbihA af.dal al-.salAT wa-azkY

al-ta.hiyaT wa ^ga`ala _tawAbahu lisayidatihi al-ma_dkUraT qa.sada bi-_dlk wa^gh ala-ll"ah al-`a.zIm wa-ra^gA'

 _tawAbihi al-^gasIm ina ala-ll"aha yu^gzI al-muta.sadiqIna wa-lA yu.dI`u a^gra al-mu.hsinIna wa ^s--a----hida

 `alY mA _dukr bimA _dukr `alY na.hwi mA bayan fIh wa su.tir fI a.hwAlihi al-^gAyizaT ^sar`aN wa `arafah

bi-tArI_h al-yawm al-_tAli_t min ^gumAdY al-uwlY `Am _hamsaT wa-_hamsIn wa-mAyatyn wa-alf

mu.hama--[d] wafaqah ala-lah bimanih 
%\hspace{2cm} 
wa-`abId rabih sub.hAnah `abd al-qA[dir] wafaqah ala-lah bimanih
\end{arab}

\pend
\endnumbering

\end{document}


```

**Comment by maieul** [comment]
<code>
à part le problème des numéros de lignes consécutives, mentionnné dans ce lien #839 et qui revient, mlagré l'insertion de la commande sugérée par Maïeul
</code>

merci de me faire un exemple minimum pour ce cas....

**Comment by yadaddi** [comment]
Le voici:
```
\documentclass[12pt]{book}
\usepackage[paper=16cm:24cm]{typearea}
\usepackage[top=2.5cm,bottom=2.5cm,left=2.2cm,right=2.2cm]{geometry}
\usepackage[series={A,B},noend,noledgroup,nopenalties]{reledmac}
\usepackage[no-math]{fontspec}
\usepackage{perpage}
\setmainfont{Amiri}
\newfontfamily\arabicfont{Amiri}[Script=Arabic, Mapping = arabicdigits]
\usepackage{newunicodechar}
\usepackage{xcolor}
\usepackage{setspace}
\onehalfspacing
\usepackage[novoc]{arabluatex}
\usepackage{luabidi}
\Xarrangement{paragraph}
\Xbhookgroup[A]{\pardir TRT\textdir TRT} %
\firstlinenum{1} \linenumincrement{1} \lineation{page}
\NewDocumentCommand{\arnote}{m}{\footnoteA{\txarb{#1}}}
\NewDocumentCommand{\ennote}{m}{\footnoteB{#1}}
\NewDocumentCommand{\commentaire}{m}{\footnoteB{\txarb{#1}}}
\newcommand{\variant}[3]{\edtext{\arb{#1}}{\Afootnote{\arb{#2} : \arb{#3}}}}
\newcommandx{\om}[2]{\variant{\arb{#1}}{\txarb{محذوفة من}}{\arb{#2}}}
\newcommandx{\add}[3]{\variant{\arb{#1}}{\txarb{#3}}{\arb{{زائدة في}} #2}}
\MakePerPage{footnoteA}
\MakePerPage{footnoteB}
\MakePerPage{Afootnote}
\sidenotemargin{right}
\rightfootnoterule
\newcommand{\transw}[1]{\arb[trans]{#1}}
\SetArbEasy
\pretocmd\linenumrep{%
 \textdir TLT%
}{}{}
\Xsymlinenum{$||$}
\begin{document}
\linenummargin{left}
\beginnumbering
\pstart[\setRTLmain] 
\parindent=0pt
\begin{arab}
 al-.hamdu li-lahi .ha.dara 
 ladY ^sahIdayhi wa-bi-al-ma.hkamaTi \edtext{\arb{al-.hanafiyaTi}}{\Afootnote{\arb{al-mAlikiyaT}}} min baladi al-^gazAyiri al-ma.hmiyaTi 
 bi-ala-lahi ta`AlY amAma \edtext{\arb{al-^say_hi al-qA.dI }}{\Afootnote{\arb{al-qA.dI al-^say_h}}} .fI  al-tArI_hi ayadahu ala-lahu al-wA.di`i .tAbi`ahu

 al-rafI`i a`lAhu dAma `izahu wa `alAhu al-`Alim al-`alAmah al-ba.hr al-fahAmah al-mu.haqiq

 al-muwafaqi al-sayid mu.hamad muftI al-sAdAti al-mAlikiyaTi al-.hnafiyaT kAna ibn al-mar.hUmi bi-karami al-.hayi

 al-qayUmi al-sayid al-.hA^g ibrAhIm bin mUsY bihi ^sahida wa-a^shadahumA\footnoteA{.hwl ^sahida wa-a^shada, un.zr: \LR{Beaussier,  \textit{dictionnaire}, p. 348}} `alY nafsihi

 anahu a`taqa ^gamI`a al-^gU^gAn al-.sa.gIri al-_dI [\om{yaq.suru}{b}] al-wa.sfu `anhu li-.si.garihi al-musamY
\end{arab}
\pend
\endnumbering
\end{document}
```

**Comment by maieul** [comment]
Désolé, mais impossible de compiler cet exemple.

J'obtiens

`\arabicfont{}\ربcفْنت`

Merci de me fournir un exemple compilable...

**Comment by maieul** [comment]
J'obtiens

```
! Undefined control sequence.
l.1 \arabicfont{}\ربcفْنت

```

**Comment by yadaddi** [comment]
Ce sont les macros que j'ai créé qui étaient problématiques. Je m'en excuse.
Voici donc un MWE:
```
\documentclass[12pt]{book}
\usepackage[paper=16cm:24cm]{typearea}
\usepackage[top=2.5cm,bottom=2.5cm,left=2.2cm,right=2.2cm]{geometry}
\usepackage[series={A,B},noend,noledgroup,nopenalties]{reledmac}
\usepackage{perpage}
\usepackage[no-math]{fontspec}
\setmainfont{Junicode}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}
\usepackage[novoc]{arabluatex}
\usepackage{luabidi}
\Xarrangement{paragraph}
\Xbhookgroup[A]{\pardir TRT\textdir TRT} %
\firstlinenum{1} \linenumincrement{1} \lineation{page}
\MakePerPage{footnoteA}
\MakePerPage{footnoteB}
\MakePerPage{Afootnote}
\sidenotemargin{right}
\rightfootnoterule
\newcommand{\transw}[1]{\arb[trans]{#1}}
\SetArbEasy
\pretocmd\linenumrep{%
 \textdir TLT%
}{}{}
\Xsymlinenum{$||$}

\begin{document}
\parindent=0pt
\linenummargin{left}
\beginnumbering
\pstart[\setRTLmain] 

\begin{arab}
 al-.hamdu li-lahi .ha.dara 
 ladY ^sahIdayhi wa-bi-al-ma.hkamaTi \edtext{\arb{al-.hanafiyaTi}}{\Afootnote{\arb{al-mAlikiyaT}}} min baladi al-^gazAyiri al-ma.hmiyaTi 
 bi-ala-lahi ta`AlY amAma \edtext{\arb{al-^say_hi al-qA.dI }}{\Afootnote{\arb{al-qA.dI al-^say_h}}} .fI  al-tArI_hi ayadahu ala-lahu al-wA.di`i .tAbi`ahu

 al-rafI`i a`lAhu dAma `izahu wa `alAhu al-`Alim al-`alAmah al-ba.hr al-fahAmah al-mu.haqiq

 al-muwafaqi al-sayid mu.hamad muftI al-sAdAti al-mAlikiyaTi al-.hnafiyaT kAna ibn al-mar.hUmi bi-karami al-.hayi

 al-qayUmi al-sayid al-.hA^g ibrAhIm bin mUsY bihi ^sahida wa-a^shadahumA\footnoteA{.hwl ^sahida wa-a^shada, un.zr: \LR{Beaussier,  \textit{dictionnaire}, p. 348}} `alY nafsihi

 anahu a`taqa ^gamI`a al-^gU^gAn al-.sa.gIri al-_dI [\footnoteA{yaq.suru}{b}] al-wa.sfu `anhu li-.si.garihi al-musamY
\end{arab}
\pend
\endnumbering
\end{document}

```

**Comment by maieul** [comment]
bah heu, je ne vois aucun souci.

on a bien `2-1`, dans le bon ordre.... (le 1 à droite, le 2 à gauche)

**Comment by maieul** [comment]
[issue839-bis.pdf](https://github.com/maieul/ledmac/files/4183382/issue839-bis.pdf)

**Comment by yadaddi** [comment]
Merci infiniment! Effectivement, le problème est résolu.

**Comment by yadaddi** [comment]
> En tout cas la publication ne se fera pas avant 10 jours. Est-ce que tu pense pouvoir d'ici là faire un petit document synthétique sur lualatex / rtl + reledmac. Je vois les choses suivantes : - sens du texte - sens des notes - sens des chiffres dans les notes

@maieul et @ralessi 
J'ai passé du temps à faire les essais et voici le résumé des résultats que j'ai trouvé: 
Reledmac/Réledpar fonctionnent parfaitement avec Babel sous LuaLaTeX et avec la combinaison d'ArabLuaTeX et Luabidi sous LuaLaTeX également. Je n'ai pas réussi cependant à les combiner avec polyglossia sous LuaLaTeX. 
Les commandes LuaLaTex concernées:
```
	\pardit TRT
	\textdir TRT
```

A) Les plcement de ces commandes dans Reledmac:

1- un groupe de notes critiques et un de notes normales en arabe.
```
\Xbhookgroup[A]{\pardir TRT\textdir TRT}
\beforeinsertingX[A]{\pardir TRT}

```
2- un groupe de notes critiques et un de notes normales en langues latines: (reledpar)
```
\Xbhookgroup[B]{\pardir TLT\textdir TLT}
\beforeinsertingX[B]{\pardir TLT}

```
Pour la règle des notes de bas de page:
Changer la lettre de la footnoterule selon le cas:
```
	 \renewcommand{\Afootnoterule}{%
	 \noindent\rule[1mm]{\textwidth}{.15mm}}		
```

Les numéros et les tirets ne requièrent aucun traitement spécial.
	 
Pour éviter que les chiffres dans les numéros de notes ne s'inversent quand il sont 10 et plus
```
\pretocmd\linenumrep{%
 \textdir TLT%
}{}{}
```

Pour Reledpar il convient de mettre cette commande:
La page en langue arabe:	
```
\renewcommand{\Leftpagehook}{%
\pardir TRT \textdir TRT
}
La page en langues latines:
\renewcommand{\Rightpagehook}{%
\pardir TLT \textdir TLT
}
```

En ce qui concerne l'introduction de l'arabe dans les notes, il convient de le faire dans l'environnement du paquet utilisé: 
Pour Babel, il faut déclarer dans le prémbule:
```
\usepackage[main=english,french,bidi=basic-r]{babel}
\babelprovide[import,main]{arabic}
\babelfont{rm}{Amiri}
\babelfont[english,french]{rm}{Junicode}
\babeltags{ar = arabic}
\babeltags{en = english}
```
Cela permet d'introduire l'envirommenent
\begin{ar}...\end{ar}
et la commande \ar{}
Après le préambule, il convient de mettre la commande:
```
\selectlanguage{arabic}
\beginnumbering
\pstart
\begin{ar}...
```

Pour ArabLuaTeX
```
\usepackage{arabluatex}
\usepackage{luabidi}
```
Après le préambule, utiliser les commandes:
 \setRTLmain (de luabidi)
et les commande ArabLuaTeX:
```
\begin{txarab}
\beginnumbering
\pstart
...
\end{txarb} 
```
dans l'ordre suggéré dans la documentation.
Dans les notes, il faut utiliser \arb et non pas \txarb pour insérer les mots arabes même en utilisant l'Unicode!... ce qui n'est pas recommandé dans la doc. la commande \txarb ne fonctionne pas dans ce cas de figure.
Merci @maieul et @ralessi pour votre assistance. Si y'a besoin d'exemple je serais plus que ravis de vous les communiquer.

**Comment by ralessi** [comment]
Je vois qu'une solution a été trouvée à chaque problème posé. Juste une remarque sur `arabluatex`. En fait, je pense que la commande `\txarb{}` fonctionne, mais il faut la répéter dans le premier argument de `\edtext{}{}`, comme ceci:
````
\begin{txarab}
\beginnumbering
\pstart
... \edtext{\txarb{...}}{\Afootnote{...}}
\end{txarab} 
````

Et si l'on choisit de saisir l'arabe en unicode, il est préférable de procéder ainsi car la compilation s'en trouve considérablement accélérée.

**Comment by yadaddi** [comment]
Effectivement. Je ne sais plus ce que j'ai fait pour que ça foire! Chez-moi, le deuxième argument prend la commande \txarb{...} également, sinon j'ai des points d'interrogation à la place des lettres arabes.

**Comment by ralessi** [comment]
> Effectivement. Je ne sais plus ce que j'ai fait pour que ça foire! Chez-moi, le deuxième argument prend la commande \txarb{...} également, sinon j'ai des points d'interrogation à la place des lettres arabes.

En effet, le 2e argument aussi, car la commande doit réinitialiser la police de caractères.

**Comment by maieul** [comment]
Je vais fermer ce ticket et publier les corrections. Si vous voulez continuer la conversation, faite là en privé. Et si un jour vous faite une doc sur RTL et reledmac, je prend volontier.
