### ISSUE TITLE
Wrong Index Output with \edindex within eledsection commands

### ISSUE THREAD

**Issue by mxordn** [maieul/ledmac#840]
# Version
reledmac 2019/02/22 v2.31.0
relepar 2019/01/22 v2.22.2.

# Regression

--

# Description

I get a wrong index output, if an \edindex command is put into the \eledsection{} argument. It seems that imakeindex gets confused with the linenumbers of all index items on the same page.

# Minimal Working Example

```latex
\documentclass[fontsize=11pt, pagesize=false]{scrbook}
\usepackage{fontspec}

\usepackage{blindtext}
\usepackage[splitindex]{imakeidx}
\usepackage[series={A,B,C}]{reledmac}
\usepackage{reledpar}
\Xarrangement[A]{paragraph}

\makeindex[name=persona, title={Index der Personen}]


%%BEGIN DOCUMENT \begin{document} \lineation{page} \lineationR{page}

\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart
\eledsection*{\textsc{C.}\edindex[persona]{C., S.} in Epistola ad \textsc{H. B.} M.DC.VI}
\pend\pstart
Placuit mihi tuum\edindex[persona]{B., H.} tricinium, et video te non tironem, sed exercitatum esse in hujusmodi harmoniis condendis. Ego sic statuo neminem futurum bonum melopoëtam\edindex[persona]{Melopoëta}, nisi.
\pend
\endnumbering
\end{Leftside}


\begin{Rightside}
\beginnumberingR
\pstart
\eledsection*{C. in einem Brief an H. B.}
\pend\pstart
\blindtext
\pend
\endnumberingR
\end{Rightside}
\end{pages}
\Pages

\printindex[persona]

\end{document}
```

**Comment by maieul** [comment]
Please try branch issue#840

**Comment by mxordn** [comment]
Merci Maieul, j'ai vu le MWE issue840.tex est le output est mieux. Mais je comprend pas, pourquoi il y'a 4 entrée dans le index mais seulment trois commandes de \edindex dans la source. L'entrée "C., S., 1-0" n'existe pas, "C., S., 1-1" est correcte.

**Comment by maieul** [comment]
heu, je n'ai pas de 1-0 avec cette branche :)
[issue840.pdf](https://github.com/maieul/ledmac/files/4183321/issue840.pdf)

**Comment by mxordn** [comment]
Pardon :) J'ai pas fait le test avec la nouvelle version. C'est trop tard… Tout fonctionne parfait avec la nouvelle version. Merci beaucoup!

**Comment by mxordn** [comment]
The problem in issue 841 with the line `\xpg@set@group@aux` also occured in my larger project. deleting the line helped. Is anything else affected when I delete this line?

**Comment by maieul** [comment]
It just will be incompatible with the next version of polyglossia.

I will publish quickly new version correcting this trouble.
