### ISSUE TITLE
Italics arguments within \sameword

### ISSUE THREAD

**Issue by federico9996** [maieul/ledmac#846]
Reledmac version: 2020/02/4 v2.32.4

For my critical edition I usually use italics characters to distinguish between letters still present in the manuscript readings and letters which are integrated. They appear in the text in a partially different shape, yet represent of course always the same word. However, the command \sameword does not regard the normal-font word and the italics one as the same, and the corresponding exponents do not therefore appear in the apparatus. Hereafter a MWE:

`\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\usepackage[noend,noledgroup,noeledsec,series={A}]{reledmac}

\begin{document}

\beginnumbering
\autopar

per \sameword{causam} tamen scire \edtext{\sameword{causam}}{\Afootnote{fn}} est per \edtext{\sameword{causam}}{\Afootnote{fnn}} cognoscere \edtext{\sameword{ca\textit{u}sam}}{\Afootnote{fnnn}}

\endnumbering

\end{document}` 

Can this issue be solved? Thank you in advance!

[mwe_1.pdf](https://github.com/maieul/ledmac/files/4287857/mwe_1.pdf)

**Comment by maieul** [comment]
please, next time, respect the guideline when creatin a new issue.

**Comment by maieul** [comment]
the first way to deal with it is to use xetex instead of pdflatex. I am looking for another fix.

**Comment by federico9996** [comment]
I’m sorry, in what respect didn’t I follow them? I indicated the reledmac version, I described the problem and included a MWE together with pdf. Did I have to do anything else? I’m sorry, I thought it was enough! 

Thank you for your help anyway

Inviato da iPhone

**Comment by maieul** [comment]
yeah, but you deleted the header (the line starting with #)

**Comment by maieul** [comment]
Hum, it is more complex than expected. I have asked to latex neerd some help. But the faster way would be to switch to xelatex instead of pdflatex.

**Comment by maieul** [comment]
Hum, it is more complex than expected. I have asked to latex neerd some help. But the faster way would be to switch to xelatex instead of pdflatex.

**Comment by maieul** [comment]
Oki, with the help of other tex user, I get the solution. Please try branch issue846 and do feedback.

**Comment by federico9996** [comment]
I'm sorry, I can't download the reledmac.dxt file... How can I do?

**Comment by maieul** [comment]
All is explained here

https://github.com/maieul/ledmac#debug-and-feature-requests

**Comment by federico9996** [comment]
Ok, it works in my MWE, but it gives compiling error in the file of my thesis. I'm not sure I'm now able to isolate the exact problem... The error message is the following:

Missing \endcsname inserted. <to be read again> xparse function is not expandable

I do use an xparse function in my document, but it gives no problem without the .sty files in the folder...

**Comment by maieul** [comment]
reledmac use xparse internally,

Please try to extract the lines.

**Comment by maieul** [comment]
in order to extract the line, you can proceed by dichotmy

**Comment by federico9996** [comment]
I think it was my fault this time: there was a mistake in my document, for I had put two \sameword commands with slightly different content. Everything seems alright now, but I don't understand why no error message was given before... Thank you very much!

**Comment by maieul** [comment]
because, before, commands inside sameword was transformer in simple
text. 

I will publish the release this week-end

**Comment by Irgend-Wer** [comment]
Please find enclosed the LOG and the PDF file. There was no error (only a normal one in the first run).
 

Gesendet: Donnerstag, 05. März 2020 um 16:26 Uhr
Von: "Maïeul Rouquette" <notifications@github.com>
An: maieul/ledmac <ledmac@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [maieul/ledmac] Italics arguments within \sameword (#846)


Oki, with the help of other tex user, I get the solution. Please try branch issue846 and do feedback.
