### ISSUE TITLE
Problem with \sethangingsymbol and astanza

### ISSUE THREAD

**Issue by Irgend-Wer** [maieul/ledmac#847]
I am sorry I am not able speak or write in French and only poorly in English...

# Version 

Package: reledmac 2020/02/04 v2.32.4 typesetting critical editions
Package: reledpar 2019/11/04 v2.22.4 reledmac extension for parallel texts

# TeX Engine

LuaLaTeX
This is LuaTeX, Version 1.10.0 (TeX Live 2019)  (format=lualatex 2020.3.2)

# Regression

none

# Description

\sethangingsymbol{\protect\hfill} (see documentation "Parallel typesetting for critical editions: the reledpar package" on page 22) does not workin combination with the astanza environment
 
# Minimal Working Example

```lualatex
\documentclass{scrbook}
\usepackage{fontspec}
\usepackage{polyglossia}
\setdefaultlanguage[spelling=new, latesthyphen=true, babelshorthands=true]{german}
\setmainfont{EB Garamond}
\setsansfont{EB Garamond}
\usepackage[series={A,B},noend,noeledsec]{reledmac}
\usepackage{reledpar}
\setstanzaindents{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
\sethangingsymbol{\protect\hfill}
\parindent=0pt

\begin{document}
\subsection{Text and Translastion}
Bla bla bla and \dots
\begin{pages}
\beginnumbering
\begin{Leftside}
\begin{itshape}
\begin{astanza}\subsubsection*{Text} XXX XXX XXX\dots  XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX \dots XXX XXX XXX XXX XXXXXX. &
XXX \& \end{astanza}
\end{itshape}
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\begin{astanza}\subsubsection*{Translation} XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX \dots XXX XXX XXX XXX XXXXXXXXX XXXXXXXXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXX \dots XXX XXX XXX XXX XXXXXX. &
XXX \& \end{astanza}
\endnumbering
\end{Rightside}
\end{pages}
\Pages

\end{document}
```
# Workaround
I got an helping information from the maintainer (Maïeul Rouquette) via eledmac@lists.tuxfamily.org:
This feature (\sethangingsymbol) does not work yet with astanza, but you can use \stanza instead.

From my point of view it would be great when there would be a short sentence in the documentation that would name this "incompatibility" and the above written workaround (until maybe someone will have coded/implemented a solution that makes it compatible to each other).

# Thanks
Thanks to all of you coding and maintaining this packages. This is really a great work!

[minimalBsp3.log](https://github.com/maieul/ledmac/files/4289355/minimalBsp3.log)
[minimalBsp3.pdf](https://github.com/maieul/ledmac/files/4289356/minimalBsp3.pdf)

**Comment by maieul** [comment]
Not directly related remarks : 
- instead of using multiple 0 in `setstanzaindents`, you should set `stanzaindentsrepetition` counter (§ 9.3 of reledmac handbook)
- YOU MUST not add any section or related directly in pstart (you will get wrtong result), but inside the optional argument of pstart

I will not change the handbook,  but instead solve this issue. Please wait few time.

**Comment by maieul** [comment]
Please try branch issue847, which should add hnagingsymbole in astanza

**Comment by Irgend-Wer** [comment]
Thanks a lot for fixing this within only a few hours! That is great.
I am going to be back at my computer tonight and I am going to test it as soon as possible.
Yours sincerly

**Comment by Irgend-Wer** [comment]
Dear Maintainer,

I did try but I was not running it correctly.

I am not sure if I installed it in the right and proper way, because this is the first time I used files I did not install via tlmgr.

I cloned the repo to a folder on my computer and merged the branches master and issue 847 locally.
Then I ran the following commands:
```
latex reledmac.ins
latex reledpar.ins
```
That worked fine.

And then I copied reledmac.sty and reladpar.sty to the folder /usr/local/texlive/2019/texmf-dist/tex/latex/reledmac but the compiling of the MWE had the same result as before.

So I am not sure if I made a mistake installing reledmac/-par from branch issue847 or if the changes in these files does not fix my problem.
Is there a way to see (e.g. in the log) if it used the files from branch issue847 or if I fail installing it correctly?

Yours sincerly
Irgend-Wer

**Comment by maieul** [comment]
All the process to make test is explained here.

https://github.com/maieul/ledmac#debug-and-feature-requests

You should not have to merge/clone/do anything, just download the branch

**Comment by Irgend-Wer** [comment]
Sorry for bothering with the wrong installation. I did as written in the link (and this time I found the link to download the zip and it worked fine!
Thanks a lot.
Is there anything else needed for the report? (log or something like that) Or is it just fine when it works?
Thanks a lot for your patience and for the help!!!
