### ISSUE TITLE
Critical notes with footnote marker?

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#855]
For a new edition project, I probably need to follow new/other rules.

Most importantly, in the text they want a footnote mark after the lemma; in the apparatus, they want the footnote mark instead of the line number. It is possible to do this with a workaround (not using \edtext and \Afootnote, but a regular footnote), but it means loosing a lot of other functionality. Would it be possible to add this as a regular feature? (Or is it possible already and I didn't see that?)

Here's a MWE that produces the required output:
```
\documentclass{book}

\usepackage[latin]{babel}

\usepackage[utf8]{inputenc}

\usepackage[series={A},noledgroup]{reledmac}

\begin{document}


\makeatletter
\renewcommand*{\thefootnoteA}{\alph{footnoteA}}
\renewcommand*{\footfootmarkA}{\textbf{\@nameuse{@thefnmarkA}}}
\makeatother

\newcommand{\app}[2]{#1\footnoteA{ #1] #2}}

\beginnumbering
\pstart
Non est nobis animus de dignitate atque utilitate \emph{\app{studii}{studij X} Theologici} praefationis loco multis disserere, sed methodum rectè illud instituendi ac pertexendi illis, qui se huic studio consecratos volunt, praescribere.
\pend
\endnumbering

```

PS If you are interested in my last edition project, please send me your address (if the pdf fits your needs, it will be available freely soon).

**Comment by maieul** [comment]
well,

i have no so much time now for reledmac, and, as you explained, you can
similate such feature by creating your own commands which call the
familial foonote + add the lemma.

I don't know exactly which other features you will lost using familiar
footnotes...

**Comment by baem2** [comment]
A feature missing is for example that \edtext takes over the correct settings of the font (in the MWE: \emph), while my solution doesn't. But it's fine, I just wanted to know if I overlooked some existing way to do it.

**Comment by maieul** [comment]
well,
in this case, I think you could create you own feature, based on edtext.

1. Having a counter increased at each edtext (indeed, we have already
it, it is an internal counter, that you may use)
2. Create you command which :
- call edtext 
- use \lemma to add the counter in the footnote
- add the counter after the lemma
3. Setting to not playing line number (there is a hook for that)

**Comment by baem2** [comment]
Thanks. But as far as I see, normal text in the second argument of edtext is placed before the lemma  in the main text. So the counter given in 2., third "-", will be placed before the lemma in the main text if I see it correctly.

**Comment by maieul** [comment]
sorry ? only the first argument of edtext is typeset in the main text

**Comment by baem2** [comment]
Ah, now I see how you want to do it. This seems to work, thanks!

(The second argument of edtext is also typeset in the main text, but in front of the lemma. At least in reledmac 2.26.2.)

**Comment by maieul** [comment]
sorry??????
please provide a MWE....

**Comment by maieul** [comment]
`\edtext{toto}{\Afootnote{something}}`

the second argument is not typeset... if it is typeset it is because you use it wrong :)

**Comment by baem2** [comment]
If you do something like this ´´\edtext{toto}{\Afootnote{something}42}´´ the 42 will be typeset in the main text, before the lemma. But this might be "doing something wrong" ;)

**Comment by maieul** [comment]
indeed. why adding this 42 in the second argumment? 

you should use the `\lemma` command

**Comment by baem2** [comment]
Yap, right, I was just trying to put the footnote marker to the correct position. But that works now.

I tried to implement the solution you suggested. One problem I wasn't able to fix: In the apparatus, the footnote mark does not fit (it's always the last status of the counter [even if I use a new counter, not the internal one]). See MWE.

The internal counter from your "1." is called "edtext"; the hook to prevent the line number is \Xnonumber.

MWE:
```
\documentclass{book}

\usepackage[latin]{babel}

\usepackage[utf8]{inputenc}

\usepackage[series={A},noledgroup]{reledmac}

\begin{document}

\newcommand{\app}[2]{\edtext{#1\textsuperscript{\alph{edtext}}}{\lemma{{\normalfont\textbf{\alph{edtext}}} #1}\Afootnote{#2}}}

\Xnonumber[A]

\Xinplaceofnumber[A]{0mm}

\beginnumbering
\pstart
Non est nobis animus de dignitate atque utilitate \emph{\app{studii}{studij X} Theologici} \app{praefationis}{prafationis X} loco multis disserere, sed methodum rectè illud instituendi ac pertexendi illis, qui se huic studio consecratos volunt, praescribere.
\pend
\endnumbering
\end{document}
```

**Comment by maieul** [comment]
Ha, yes, it is a classical problem of expansion.

Basically, `\lemma` macro just defines an internal reledmac macros, used later, when the footnote are send to to the output routine.

With you code, you say that this internal macro must contain `\alph{edtext}`, which mean "get the current value of the edtext counter". As it is called after all the main text is parsed, of course it will get the last version of the counter.

reledmac/latex classical footnote have internal "hack" to deal with that,

Basically, what you need is to expand the the result of `\alph{edtext}` before sending it to `\lemma`. So you need to deal with `\expandafter`.

In order to avoir `expandafter` long string, we could store the result of `\alph{edtext}` in a temporary macro.

That will do :
```

\newcommand{\app}[2]{%
  \edtext{%
    #1\textsuperscript{\alph{edtext}}
  }%
  {%
    \edef\thisedtext{\unexpanded{\normalfont\textbf}{\alph{edtext}}}%
  \expandafter\lemma\expandafter{\thisedtext\ #1}%
  \Afootnote{#2}}%
}
```

I am tired and I have no time now for a learning about expansion problem with TeX, but you will get many ressource on the internet.

**Comment by baem2** [comment]
Yap, I already thought it might be about exapnsion (I know what it is!), I just did not know how to work around that. Thank you very much! Your support is great as always. (I even mentioned that in my recent preface!)

**Comment by maieul** [comment]
your welcome. Please don't forget to add your book on the collaborative bibliography, if not done. (I have no place at home for a physical volume)
