### ISSUE TITLE
edtabular indentation (reledmac.sty)

### ISSUE THREAD

**Issue by ferenczizsani** [maieul/ledmac#856]
# Version

reledmac.sty 2020/04/19 v2.32.6

# Regression

There is no problem with previous version of reledmac.sty (2015/11/29 v2.7.0).

# Description

The very first rows of text of the edtabular tables gets indented in every cell, which is not wanted. As an example, see the `examples/1-tabular.tex` file.

**Comment by maieul** [comment]
ba6693dd5f676ddbd0e62df1dc3b5e0d5a414dcb is the origin of the problem.

**Comment by maieul** [comment]
Please try branch issue857

**Comment by maieul** [comment]
@ferenczizsani could you try it before sunday? I would like to publish a release this week end.

**Comment by maieul** [comment]
well, no answer.

So I will publish on CTAN today.
