### ISSUE TITLE
Mauvaise numérotation de la ligne 1 dans l'apparat avec \lineation{pstart}

### ISSUE THREAD

**Issue by badumont** [maieul/ledmac#857]
# Version

reledmac 2019/07/21 v2.32.1

# TeX Engine

xelatex (même résultat avec lualatex et pdflatex)

# Regression

Je n'ai pas utilisé reledmac auparavant...

# Description

En donnant l'argument `pstart` à `\lineation{}`, les numéros de ligne affichés en marge sont exacts, mais l'apparat critique présente un problème : le numéro renvoyant à la première ligne du second paragraphe correspond au numéro de la dernière ligne du paragraphe précédent + 1. Tous les autres numéros de ligne dans l'apparat critique sont exacts.

L'ajout de contenu non numéroté entre les paragraphes numérotés n'a aucune incidence.

# Minimal Working Example

```latex
\documentclass{article}
\usepackage{reledmac}
\lineation{pstart}

\begin{document}
\beginnumbering

\pstart Falso \edtext{queritur}{\lemma{queritur} \Afootnote{on se plaint}} de natura sua genus humanum, quod inbecilla atque aevi brevis forte potius quam virtute regatur. nam contra reputando neque maius aliud neque praestabilius invenias magisque naturae industriam hominum quam vim aut tempus deesse. sed dux atque imperator vitae mortalium animus est. qui \edtext{ubi}{\lemma{ubi} \Afootnote{là où}} ad gloriam virtutis via grassatur, abunde pollens potensque et clarus est neque fortuna eget, quippe quae probitatem, industriam aliasque artis bonas neque dare neque eripere quoiquam potest. \pend

\pstart sin captus \edtext{pravis}{\lemma{pravis} \Afootnote{honteux}} cupidinibus ad inertiam et voluptates corporis pessum datus est, perniciosa lubidine paulisper usus, ubi per socordiam vires tempus ingenium diffluxere, naturae infirmitas accusatur: suam quisque culpam auctores ad negotia transferunt. quod si hominibus bonarum rerum tanta cura esset, quanto studio aliena ac nihil profutura multaque etiam periculosa <ac perniciosa> \edtext{petunt}{\lemma{petunt} \Afootnote{requièrent}}, neque regerentur magis quam regerent casus et eo magnitudinis procederent, ubi pro mortalibus gloria aeterni fierent.  \pend 

\endnumbering
\end{document}

```

# Workaround

Ajouter `\setlinenum{0}` après le deuxième `\pstart` pallie le problème.

(Au cas où cette indication puisse aider : `\setlinenum{1}` fait que la première ligne est numérotée "2" dans l'apparat. Dans les deux cas, la linéation en marge ne change pas.)

**Comment by maieul** [comment]
Bon en mettant tout les numeros de ligne, on voit que la numerotation n'est pas bonne pour la première ligne du deuxième paragraphe !!!!

Je regarde ce qu'il en est.

**Comment by maieul** [comment]
"% We check if lineation is by pstart: in this case, we reset the line number, but only in the second line of the pstart.
% We can't reset line number at the beginning of  \protect\cs{pstart}, as \protect\cs{setline} is parsed at the end of previous \protect\cs{pend}, and so, we must do it at the end of first line of pstart.
"

comment ai je pu penser une seul seconde qui cela n'aurait pas des effets indirects.

**Comment by maieul** [comment]
merci d'essayer la branche issue857

**Comment by badumont** [comment]
J'ai vérifié sur le fichier de test et sur mon édition : ça marche parfaitement, merci (et merci beaucoup au passage pour tout le travail que vous fournissez) !

**Comment by maieul** [comment]
Bien, j'attend dds tests d'autres personnes, et si c'est pas le cas je publierai ce week-ed.

**Comment by maieul** [comment]
Je vais publier sur le CTAN aujourd'hui.
