### ISSUE TITLE
\parafootsepX n'es pas pris en compte

### ISSUE THREAD

**Issue by badumont** [maieul/ledmac#858]
# Version

reledmac 2020/04/19 v2.32.6

# TeX Engine

Testé sur les trois.

# Regression

Probablement, car le bug a déjà été repéré et réglé par le passé (#528), mais je ne peux pas dire dans quelle version il est réapparu.

# Description

Avec `\arrangementX{paragraph}`, `\parafootsepX` n'est pas pris en compte. La valeur de `\Xparafootsep` est utilisée à la place. Ce bug n'est pas généralisé à toutes les commandes pour les notes familières : `\afternoteX` fonctionne, par exemple.

# Minimal Working Example

```latex
\documentclass{article}
\usepackage[series=A]{reledmac}
\Xarrangement{paragraph}
\arrangementX{paragraph}
    \parafootsepX[]{;}
    \Xparafootsep[]{$\parallel$}
    \Xafternote[]{0.2em}
    \afternoteX[]{2em}
\lineation{pstart}
\linenumincrement{1}

\begin{document}
\beginnumbering

\pstart Falso \edtext{queritur}{\lemma{queritur} \Afootnote{on se plaint}} de \edtext{natura}{\lemma{natura} \Afootnote{nature}} sua genus humanum, quod inbecilla\footnoteA{faible} atque aevi brevis\footnoteA{court} \pend

\endnumbering
\end{document}
```

**Comment by maieul** [comment]
Le bug pointé n'était pas tout à fait le même, et je pense que le bug que vous avez soulevé est nouveau.

Pour autant il était simple à résoudre.

Pouvez vous tester la branche issue858 ?

J'aimerais faire une release demain.

**Comment by badumont** [comment]
Ça marche ! Au passage, je m'en suis rendu compte parce que j'ai voulu utiliser \parafootsepX pour ajouter un peu d'espace entre le séparateur et la marque de note suivante. N'y a-t-il pas moyen de faire autrement (un équivalent de \Xbeforenumber pour les notes familières) ? J'ai parcouru mainte fois le manuel sans trouver, j'espère que je ne suis pas passé à côté d'un truc évident...

**Comment by maieul** [comment]
Xbeforenum n'est pas équivalent, puisque cela affiche l'espace avant le
numero qu'il y ait une note ou pas avant.

Ce dont vous avez besoin est `afternoteX` qui ajoute une espace après le
séparateur de note.

**Comment by badumont** [comment]
Mh, je viens de tester \afternoteX et ça augmente l'espace avant le séparateur... 

Je suppose que c'est possible de le faire en insérant un \hskip après le séparateur de notes proprement dit dans \parafootsepX ? Ça marche avec \Xparafootsep... Merci beaucoup en tout cas pour l'indication sur \Xbeforenumber, je ne m'étais pas rendu compte que ça affichait l'espace au début de paragraphe de notes !

**Comment by maieul** [comment]
ah oui c'est moi qui suis fatigué. Oui donc \hskip aura plus de sens.


Je pourrais ajouter une option \beforenoteX, mais elle serait pas
symétrique de l'autre. Ca n'aurait pas de sens de l'inserer partout.

**Comment by badumont** [comment]
Cela étant, comme il y aurait d'un côté "beforenumber", et de l'autre "beforenote", ça ne suggérerait pas trop de symétrie... Après, je ne sais pas si ça concernerait suffisamment de monde pour qu'il soit intéressant de l'ajouter, vu qu'il y a une espace insérée par défaut après le séparateur. Pour être honnête, si j'en ai eu besoin, c'est parce que j'ai ajoutée un \unskip à la commande \thefootnoteA pour supprimer l'espace introduite entre le texte grec et la marque de note latine dans mon texte... Je cherche les problèmes.

**Comment by maieul** [comment]
oui alors il faudrait résoudre en effet.

beforenote ferait pendant à afternote, sauf qu'en fait non. c'est bien
là le problème

**Comment by maieul** [comment]
Je vais publier sur le CTAN aujourd'hui.
