### ISSUE TITLE
stanza: fixing an automatic \hspace to horizontally align "split" lines

### ISSUE THREAD

**Issue by henryflower** [maieul/ledmac#861]
See [https://tex.stackexchange.com/questions/546309/reledmac-using-stanza-environment-for-dramatic-verse](url)
There is also some similarity to  #797

# Version

reledmac 2020/05/03 v2.32.7

# TeX Engine

pdfLaTeX

# Regression

none

# Description

When using \stanza for verse lines of a dramatic text, lines that are "split" between speakers (an antilabe) should include a white space between the name of the speaker and their utterance to signify the continuation of the "split" line. The difference to issue 797 is that in dramatic verse the length of the white space has to take the length of the speaker's name into account.
![a](https://user-images.githubusercontent.com/66003703/82996173-e295c180-a004-11ea-8a60-a700121a6993.png)

# Minimal Working Example

```latex
\documentclass [12pt, a4paper, pagesize] {scrbook}
\usepackage [UKenglish] {babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{microtype}

\usepackage[characterstyle=imprimerie-prose]{thalie}

\usepackage{reledmac}


%%retained from the thalie package, modifies the way a character's name is given in the first line of speech
\renewcommand*{\speakswithoutdirection}[1]{%
   \noindent\textsc{#1}\xspace.%
    }



\begin{document}

%%part of thalie's management of characters
\begin{dramatis}[hidden]
	\character[cmd={Buckingham}]{Buckingham}
	\character[cmd={Norfolk}]{Norfolk}
\end{dramatis}

%sets indent for stanza at 2\parindent for all lines following the first in a stanza
\setlength\stanzaindentbase{2\parindent}
\setstanzaindents{0,1}
\setcounter{stanzaindentsrepetition}{1}

	\linenummargin{right}
	\beginnumbering
		\selectlanguage{UKenglish}
		\stanza\Buckingham Good morrow and well met. How have ye done&\skipnumbering Since last we saw in France?\&
		
	 	\stanza\Norfolk I thank your grace,&Healthful, and ever since a fresh admirer&\skipnumbering Of what I saw there.\&

		\stanza\Buckingham An untimely ague&Stayed me a prisoner in my chamber when\&
	\endnumbering


\end{document}
```

# Workaround

A manual workaround would be something like:
```latex
\stanza\Buckingham Good morrow and well met. How have ye done&\skipnumbering Since last we saw in France?\&

\stanza\Norfolk \hphantom{ast we saw in France?}I thank your grace,&Healthful, and ever since a fresh admirer&\skipnumbering Of what I saw there.\&
```
Of course inserting \hphantom manually throughout a complete five-act play would become very tiresome. A function for this or something similar with a determination of the correct length of white space needed would be much appreciated.

**Comment by maieul** [comment]
I will try something. By the way, you should put all your setting in the preamble. It "cleaner"

**Comment by maieul** [comment]
@henryflower could you confirme the enclosed pdf is as you wanted.

[issue861.pdf](https://github.com/maieul/ledmac/files/4688487/issue861.pdf)

I have two question to get more in this topic

1. What about in the second "false verse" is too long? Where should the hanging start ?
2. Which syntaxis would you prefer to mark such verse ?


(enclose : a copy for my self of my first test, please dont use it, I will ask to you when you could make test
[reledmac.sty.zip](https://github.com/maieul/ledmac/files/4688491/reledmac.sty.zip)

**Comment by henryflower** [comment]
About the pdf: I'm afraid that is not what I had in mind. 
I'm uploading a .png here in the comment with an example of correct empty spaces.
![d](https://user-images.githubusercontent.com/66003703/83042013-6cfc1680-a041-11ea-9e3b-0c5fc62dd73c.png)


Your questions:
1. At least with the Shakespeare text that I am dealing with, this case will not happen; a line consisting of a pentameter or hexameter should never exceed the possible linewidth. On a more general level, even without considering the number of metrical feet in a line, these antilabe splits are usually used for quick back-and-forth exchanges between speaking characters, so antilabe lines are very unlikely to become too long.

2. I don't have much experience with naming conventions etc. I assume that the line where the split begins will need a command to signify that beginning, maybe \splitline or \splitverse (very close to the dreaded \pauseverse \resumeverse from the thalie package though), or even \antilabe; and I guess that the next line, where the split continues with the correct amount of white space between character name and words will also need a command to set that space, maybe \resumeline or \antilabectd?

Again, many thanks for looking into this. Please let me know if I can be of further assistance.

Oliver

**Comment by maieul** [comment]
Sorry, I misplaced the command in my test file, as I was focused on the "getting the width of the previous line" that I put my code in the wrong place.
Enclosed, a corrected example. Please tell me if it is ok. 

[issue861.pdf](https://github.com/maieul/ledmac/files/4690269/issue861.pdf)

1. Oki, that nice, I won't take care of this problem.
2. We don't need to mark the starting line (except for \skipnumbering), only the finishing one. So it would be something like this `\antilabe\Norfolk`. For #797, it will be `\antilabe{}` or something like this.

Also, as this feature is quite ressource consuming, it will be required to pass explicitly an option when loading the package to enable it, in order to avoid penalty for other users.
 
[reledmac.sty.zip](https://github.com/maieul/ledmac/files/4690247/reledmac.sty.zip)

Another point :  I think your   setting of indentation is wrong. 

`\setstanzaindents{1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1}` would be better : first verse of a stanza no indented, other verse indentend


I ask the opinion of @rrthomas about the naming convention.

**Comment by rrthomas** [comment]
@maieul, if you're asking about the name of the proposed `\antilabe`, that seems fine to me. Also, good to see explicit support. Funnily enough it took me a good few minutes to work out which project I was working on when I filed #797!

**Comment by henryflower** [comment]
@maieul, yes, now the .pdf shows the lines in the way they are supposed to be. Bravo!

about `\setstanzaindents`... maybe I misunderstood how it is supposed to work. How could `\setstanzaindents{1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1}` be translated into a repetition pattern "first line not indented, all other lines indented" with `\setcounter{stanzaindentsrepetition}{}`?

**Comment by maieul** [comment]
@rrthomas oki, nice. I will do that
@henryflower Nice, so I will code it "definitivly" this week-end and I will ask you for test.

Note that with astanza, it could work only with the last line of an astanza environnement, not inisde a astanza environnement, contrary to normal stanza. I hope that is the case for you. but If I understand well the use of antliabe, it is only between two replies of two characters, so it should work nice. 

COncerning setsanzaindents, actually it can't be translated into you repetition pattern you asked, The repetition start from the first verse. It is used when the indentation alternate between in a regular pattern, for example for latin classical poetry (I don't remember exactly why, but @Enimie could answer). 
```
Verse 1 
   Verse 2
Verse 3
    Verse 4 
Verse 5
    Verse 6
etc
```

What we could do for your case, is to a new counter {startstanzaindentrepetitions}. But please open a new issue for that.

**Comment by henryflower** [comment]
Great, I look forward to testing it then. You are right, in my case the antilabe always occurs at the transition from the last line of a stanza or astanza environment to the first line of a new environment.

About the stanzaindents: I see. I will open a new issue for that.

**Comment by maieul** [comment]
ping @gabays who may be interessed by the antilabe feature and have an opinion about it.

**Comment by maieul** [comment]
please try branch issue861.

Note that the feature of #863 are not yet inside the branch. I will create a release branch with both feature.

Please also made feedback about the handbook, on e28d0687

**Comment by rrthomas** [comment]
Looks fine to me. A little confusing to read since the same commit changes other unrelated but adjacent material.

**Comment by maieul** [comment]
thanks @rrthomas. Indeed, I did not a good work for this commit, which should have been split...

**Comment by henryflower** [comment]
Many thanks. I tested it and it works exactly as intended. It may be more typographically correct and aesthetically pleasing to add a "normal" whitespace to the length that `\antilabe` leaves empty before continuing with the split line? I am very sorry I did not think about this sooner, I just realised this now when I saw the result on the page. However, if that is not possible to implement, then I think `\antilabe` is good as it is now.
The explanation of the function in the documentation reads fine to me.

**Comment by maieul** [comment]
Please try new version of the branch, which allow to insert automatically arbitrary content after/before `\antilabe` (cf 59320c63 for the handbook)

**Comment by henryflower** [comment]
I tested several insertions, they all work as expected. Many thanks for adding this useful function. Documentation appears clear und understandable to me.

**Comment by maieul** [comment]
Nice. I have deleted the branch issue861, and merge all in the branch
mac2.33.0-par2.24.0.

It include feature of #861 and #863.

I have some things to do with #862, and after that I should be
published (but I will ask for spell checking to a voluntary team).



In any case, I have answered to you on SE. Please validate and vote up
to the answer.

https://tex.stackexchange.com/a/547213/7712
