### ISSUE TITLE
Customize \ledinnotemark by footnote series

### ISSUE THREAD

**Issue by davidesimo** [maieul/ledmac#862]
# Version
reledmac 2020/02/04 v2.32.4

# TeX Engine
LuaLaTeX

# Description
I need to index words that appear in different apparatuses and would like to define a new suffix for each footnote series: for example, the default suffix (n) would refer to an apparatus of variants and a new suffix (like +) would refer to an apparatus of interpolations.

# Minimal Working Example
```latex
% !TEX encoding = utf8
% !TEX TS-program = lualatex

\documentclass{book}

\usepackage{polyglossia}
\setmainlanguage{latin}

\usepackage{imakeidx}

\usepackage[series={A,B},noend,nofamiliar,noledgroup,nopbinverse]{reledmac}

\makeindex[name=nom,title=Index nominum]

\begin{document}
	
	\beginnumbering
	\setstanzaindents{0,0}
	\setcounter{stanzaindentsrepetition}{1}
	
	\stanza
	\edtext{}{\Afootnote[nosep]{… Gratum opus agricolis, at nunc horrentia Martis\edindex[nom]{Mars} — ante v.~1}}%
	Arma uirumque cano, Troiae\edindex[nom]{Troia} qui primus ab oris&
	Italiam\edindex[nom]{Italia} fato profugus \edtext{Lauiniaque\edindex[nom]{Lauinium}}{\Bfootnote{Lauinaque\edindex[nom]{Lauinium}}} ueni…\&
	
	\endnumbering
	
	\printindex[nom]
	
\end{document}
```

**Comment by maieul** [comment]
But please, provide a MWE which is simpler. No any custom command, just
"vanilla" reledmac.

**Comment by maieul** [comment]
I will try to get time for it this week-end

**Comment by davidesimo** [comment]
Sorry, I edited the MWE. Hope it’s ok.

**Comment by maieul** [comment]
yes, thank you !

**Comment by maieul** [comment]
Please try the branch issue862, which provide two command `\Xinnotemark and \innotemarkX`. For use, please read 339be77f and make feedback on the handbook.

**Comment by davidesimo** [comment]
I tried it and it works in the test file, but if I add `\Xnonumber` or the `nonum` option in `\Xfootnote` it gives an error.

**Comment by maieul** [comment]
Please try the new version of the branch. It should fix it.

**Comment by davidesimo** [comment]
Now I get no error, but it seems that `\Xinplaceoflemmaseparator{0pt}` and `\Xinplaceofnumber{0pt}` don’t have any effect now (there is white space before the text of the footnote).

**Comment by maieul** [comment]
oups, sorry, I added a trick to check if the series asked in a hook was good, but... I did a big typo, and no hook work any more). Please try again.

**Comment by davidesimo** [comment]
Thanks, it’s ok now!

**Comment by davidesimo** [comment]
If I try with reledpar though, I get this error:

> ! Package reledpar Error: You use the polyglosia package.
> (reledpar)                However, reledpar requires version 2020/04/08 v1.49 o
> r later of the polyglossia package.
> (reledpar)                Please update your reledpar version.

So it can’t work with reledpar unless I update both right?

**Comment by maieul** [comment]
Yes, there was many change in polyglossia in the past, which broke the compatibility. I won't support all the version of polyglossia, so I ask for the last version.

**Comment by maieul** [comment]
(I have just corrected the typo in the error message)

**Comment by davidesimo** [comment]
Ok, I’ll upgrade then, thank you.

**Comment by maieul** [comment]
I will publish the new version ASAP on CTAN. I just wait for spell checking.

I have answered to you on SE. Please validate and vote up the answer.

**Comment by davidesimo** [comment]
I read [339be77](https://github.com/maieul/ledmac/commit/339be77f9a27e2e9f41631fd5ac32d1889913ed5).
