### ISSUE TITLE
stanza: set a fixed indent for all lines after the first

### ISSUE THREAD

**Issue by henryflower** [maieul/ledmac#863]
# Version

reledmac 2020/05/03 v2.32.7

# TeX Engine

pdfLaTeX

# Regression

none

# Description

When using the `stanza`or `astanza` environment to set dramatic verse, it is useful to set an indent for all verse lines after the first to set off the speaker's name for easier distinction of speech parts. At present, this has to be done with `\setstanzaindents{1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1}` and a number of 1,1,1,1etc repetitions that covers even the longest cases of all characters' speeches in a play. This can become tedious and fault-prone. Hamlet's famous "To be, or not to be" monologue for example consists of 34 lines.

# Minimal Working Example

```latex
\documentclass [12pt, a4paper, pagesize] {scrbook}
\usepackage [UKenglish] {babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{microtype}

\usepackage[characterstyle=imprimerie-prose]{thalie}

\usepackage{reledmac}


%%retained from the thalie package, modifies the way a character's name is given in the first line of speech
\renewcommand*{\speakswithoutdirection}[1]{%
   \noindent\textsc{#1}\xspace.%
    }

%sets indent for stanza at 2\parindent for all lines following the first in a stanza
\setlength\stanzaindentbase{2\parindent}
\setstanzaindents{1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1}

\linenummargin{right}

\begin{document}

%%part of thalie's management of characters
\begin{dramatis}[hidden]
	\character[cmd={Buckingham}]{Buckingham}
	\character[cmd={Norfolk}]{Norfolk}
\end{dramatis}

\beginnumbering
\selectlanguage{UKenglish}
\stanza\Buckingham  Pray give me favour, sir. This cunning Cardinal&
The articles o' th' combination drew&
As himself pleased; and they were ratified&
As he cried, `Thus let be,' to as much end&
As give a crutch to th' dead. But our Count-Cardinal&
Has done this, and 'tis well, for worthy Wolsey,&
Who cannot err, he did it. Now this follows,&
Which, as I take it, is a kind of puppy&
To th' old dam treason, Charles the Emperor,&
Under pretence to see the Queen his aunt,&
For 'twas indeed his colour, but he came&
To whisper Wolsey, here makes visitation.&
His fears were that the interview betwixt&
England and France might through their amity&
Breed him some prejudice, for from this league&
Peeped harms that menaced him. He privily&
Deals with our cardinal, and, as I trow,&
Which I do well, for I am sure the Emperor&
Paid ere he promised, whereby his suit was granted&
Ere it was asked, but when the way was made&
And paved with gold, the Emperor thus desired&
That he would please to alter the King's course&
And break the foresaid peace. Let the King know,&
As soon he shall by me, that thus the Cardinal&
Does buy and sell his honour as he pleases,&
And for his own advantage.\&
\endnumbering

\end{document}
```
Discussion in #861 has suggested that a new counter {startstanzaindentrepetitions} might help with that.

**Comment by maieul** [comment]
Ok, please try branch issue863. You have a new counter `startstanzaindentsrepetition`. You must set it to 2 (default value is 1) to say "hey, I want you to repeat the indents after the line 2, included".

You can see an example in the file issue863.tex (I put other setting, only for test). 


Please also have a look on the handbook change in 828107b3.

**Comment by henryflower** [comment]
Many thanks, this does exactly what is needed. I think there is a small mistake in the documentation, and I made a comment in [https://github.com/maieul/ledmac/commit/828107b3157942b2a143229c8eb26f5d7dbdb39e](url)

**Comment by maieul** [comment]
nice! thanks you for the test
