### ISSUE TITLE
Spurious empty lines using \marks command

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#864]
# Version

reledmac 2020/05/24 v2.32.8

# TeX Engine

pdflatex

# Description

In an edition project, I am trying to add the original pagination to the margin and running title. The command used for this seems to lead to empty lines in reledmac: ``\marks\origmark{#1}``. As soon as I remove it, there is no problem at all.

I do not know if this is an error on reledmac's side, please have a look yourself ...

# Minimal Working Example

```latex
\listfiles

\documentclass{report}
\usepackage[T1]{fontenc}

\usepackage[english]{babel}
\usepackage{reledmac}
\usepackage{blindtext}

\usepackage{ifthen}

\usepackage[headsepline]{scrlayer-scrpage}

\newmarks\origmark

\newcommand{\origpage}[1]{%
|\ledouternote{p.~#1}% 
\marks\origmark{#1}%
}

\newcommand{\origpagemark}{\ifthenelse{\equal{\botmarks\origmark}{\topmarks\origmark}}%
{[\botmarks\origmark]}%
{\ifthenelse{\equal{\botmarks\origmark}{\firstmarks\origmark}}%
{[\topmarks\origmark{/}\botmarks\origmark]}%
{[\topmarks\origmark--\botmarks\origmark]}%
}%
}

\ihead{\origpagemark}

\begin{document}
\beginnumbering
\marks\origmark{36}
\pstart
\blindtext[2] \origpage{37} \blindtext[2] \origpage{38} \blindtext[2] \origpage{39}
\pend
\endnumbering
\end{document}
```

# Workaround

I am not aware of any (yet).

**Comment by maieul** [comment]
Please, do MWE simpler :).

But the problem of the mark commands is aborder on reledmac handbook with a solution (§ 5.7)
