### ISSUE TITLE
[SUGGESTION] Add \Xpstartseparator

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#865]
# Version

Package: reledmac 2020/06/06 v2.33.1

# TeX Engine
All

# Regression
No

# Description

Dear Maieul,
helping a friend of mine I discovered some commands that I didn't know: `\Xstanza`, `\Xstanzaseparator` and `\Xpstart`.

Can a new command `\Xpstartseparator` also be added?

Second idea: is it possible to print only the first pstart/stanza number of each series?

Please, take all the time you need: I'm in no hurry! :-)

Many thanks in advance,
Domenico

# Minimal Working Example

```latex
% !TeX encoding = UTF-8
% !TeX TS-program = xelatex
% !TeX spellcheck = it_IT
% !TeX root = Problemi.tex
% !BIB TS-program = biber

\documentclass{book}

\usepackage[osf]{libertinus-otf}

%Edizione Critica
\usepackage[noeledsec,noledgroup,series={A,B,C}]{reledmac}
\labelpstarttrue
\lineation{page}
\linenummargin{inner}
\Xarrangement[A,B,C]{paragraph}
\Xnumberonlyfirstinline[C]
\Xnumberonlyfirstintwolines[C]
\Xnonbreakableafternumber[C]
\Xnotefontsize[A,B,C]{\footnotesize}
\Xpstart[A,B,C]

\makeatletter
\renewcommand{\thepstart}%
	{{\hspace{3mm}\makebox[0pt][r]%
		{\bf\@arabic\c@pstart}}\hspace{3mm}%
	}
\makeatother

\usepackage{hyperref}

\begin{document}
\beginnumbering
\numberpstarttrue

\pstart%
Quel ramo del lago di Como che volge a mezzogiorno
\pend

\pstart
e il \edtext{ponte}{\Cfootnote{via}}, che ivi congiunge le due rive, par che renda ancor più sensibile all'occhio questa trasformazione, e segni il punto in cui il lago cessa, e l'Adda rincomincia, per ripigliar poi nome di \edtext{lago}{\Cfootnote{fiume}} dove le rive, allontanandosi di nuovo, lascian l'acqua distendersi e rallentarsi in nuovi golfi e in nuovi seni
\pend

\pstart
tra due catene non interrotte di monti, tutto a seni e a golfi
\pend

\pstart
a seconda dello sporgere e del \edtext{rientrare}{\Bfootnote{kjhkjkjh}} di quelli, vien, quasi a un tratto
\pend

\pstart
a ristringersi, e a prender corso e figura di fiume, tra un promontorio a destra, e un'ampia costiera dall'altra parte
\pend

\numberpstartfalse
\endnumbering
\end{document}
```

# Workaround

//

**Comment by maieul** [comment]
Should not be very difficult, for both problem, but please open a
distinct issue for the second one.

**Comment by maieul** [comment]
Please try branch issue865

**Comment by Doc73** [comment]
I add to preamble `\Xpstartseparator[A,B,C]{.}` and it produces the expected dot, but, at least in my MWE, a space between pstart number and line number still persists.

**Comment by maieul** [comment]
well, that is normal, in you MWE you explicilty add a 3mm hspace at the end of `\thepstart` definition.

What I can see for your are either:
- using `\sidepstartnumtrue` to put the pstart number in the side
- keeping your definition of thepstart, but add \unskip at the beginingof `\Xpstartseparator` to delete this space in the footnote, before the dot.

I will publish both #865 and #866 this afternoon

**Comment by Doc73** [comment]
Ah! I forgot my definition!
Many thanks!
