### ISSUE TITLE
Apparatus notes on wrong page

### ISSUE THREAD

**Issue by zvtoth** [maieul/ledmac#868]
# Version

Reledmac 2.34.0

# TeX Engine

LuaLatex 1.12
# Description

We are typesetting a critical edition with long footnotes and numerous apparatus notes (just two sets of notes total). The problem is that sometimes, especially when the footnotes are long, the apparatus notes show up on the wrong page.
I have tried to isolate the problem, and it seems to be mostly in cases where the footnote and the apparatus notes together would not fit on the page. But instead of breaking the footnotes earlier, we have the apparatus notes (as well as the footnotes) showing up on the next page. While we don't care that much about where the regular footnotes show up, the apparatus notes *must* be on the page where they belong. Is there a way to force that?

There is a lot of formatting set-up in our document, and I don't have a MWE at the moment. But if it helped, will try to create one.

Thank you!

(What we have tried so far: minimizing \interfootnotelinepenalty; trying \enlargethispage. But neither of them gave full success, and they are very cumbersome.)

**Comment by zvtoth** [comment]
What we found out so far is that it only happens when we also use the titlesec package. Maybe reledmac does not play well with that? I could not find it in the documentation.

**Comment by maieul** [comment]
is it only happen when you insert title? in which way do you insert
them ?

**Comment by zvtoth** [comment]
It only happens if we configure the title formats with the titlesec package.
Right now, we use both
\pstart
\section{}
\pend
(we tried \eledsection but it did not make a difference)

AND, we have running subsection titles (which did not work with \eledsubsection as configured so we reverted to regular \subsection)
\pstart
\subsection{}~and then here is some text.
\pend

The subsections are needed because we have their number in the running header.
They are configured as follows:
\titleformat{\subsection}[runin]{\normalfont}{\thesubsection}{1em}{}
\titlespacing{\subsection}{0pt}{3.5ex plus 1ex minus .2ex}{0pt}
\renewcommand{\thesubsection}{}
\renewcommand{\subsectionmark}[1]{%
	\markright{\MakeUppercase{\thesubsection\ #1}}%
}

The behavior is inconsistent, and there is more of it when we have longer footnotes. 

Thank you for looking at it!

**Comment by maieul** [comment]
as explained in the handbook, you CAN'T use section directly inside a \pstart\pend structure. You must use it inside the optional argument of pstart

**Comment by zvtoth** [comment]
Yes, we are aware and we tried.
But we need a subsection that is on a numbered line, and is run-in: we do not want a line break after the subsection title.
So there is no way to do that consistently?

**Comment by maieul** [comment]
so you need eledsectiom,  but actually it is not compatible with titlesec.

**Comment by zvtoth** [comment]
But I cannot configure \eledsection so that it is on a numbered line with footnotes/apparatus, and has no line break after it.
I realize that eledsection is recommended in the manual, but it would be helpful to mention the incompatibility with titlesec.

**Comment by maieul** [comment]
sorry, I jave no time ti improve compatibility with titlesec... I it as big, big work.

**Comment by zvtoth** [comment]
I understand. Thank you for responding.
