### ISSUE TITLE
[BUG] Spurious void line after edtabular

### ISSUE THREAD

**Issue by Doc73** [maieul/ledmac#869]
# Version

reledmac 2020/06/24 v2.34.0

# TeX Engine

XeLaTeX (but other engines wasn't tested)

# Regression

reledmac 2020/03/08 v2.32.5

# Description

As in subject, after every `edtabular` is now inserted a spurious numbered line.

# Minimal Working Example

```latex

% !TeX program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\documentclass[11pt,a4paper]{book}
\usepackage{libertine}
\usepackage{polyglossia}

\usepackage[noeledsec,noledgroup,series={A,B,C}]{reledmac}

\begin{document}
\beginnumbering
\numberpstarttrue

\pstart%
First pstart
\pend

\pstart
Second pstart
\pend

\pstart Third pstart
\begin{edtabularl}
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX
\end{edtabularl}
\pend

\pstart%
Forth pstart
\pend

\numberpstartfalse
\endnumbering

\end{document}
```

# Workaround

//

**Comment by maieul** [comment]
It was already here in v2.32.5, but you didn't see it because the tabular starting, wrongly, one line earlier.

But that is indeed a bug. I am looking on it.

**Comment by maieul** [comment]
it is provoqued by numberpstart, I am looking on it.

**Comment by maieul** [comment]
Oki,

while it is not explicitly mentionned in the handbook, it seems that tabular must be alone inside it pstart. The numberpstart option automatically add a content at the beginining of the pstart. 

I won't try to fix this,  as edtabular system is very complex. 

Looking on you MWE, cd924c24 should produce the expected output.

**Comment by Doc73** [comment]
No, I'm sorry! 
The modified MWE
```tex
% !TeX program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\documentclass[11pt,a4paper]{book}
\usepackage{libertine}
\usepackage{polyglossia}

\usepackage[noeledsec,noledgroup,series={A,B,C}]{reledmac}

\begin{document}
\beginnumbering
\numberpstarttrue

\pstart%
First pstart
\pend

\pstart
Second pstart
\pend

\pstart
Third pstart
\pend

\numberpstartfalse
\pstart
\begin{edtabularl}
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX
\end{edtabularl}%
\pend
\numberpstarttrue
\addtocounter{pstart}{-1}

\pstart%
Forth pstart
\pend

\numberpstartfalse
\endnumbering

\end{document}
```
isn't working. :-(

**Comment by maieul** [comment]
sorry, I forget to to tell you that I have correct a little relate bug, you should use the branch issue869

**Comment by Doc73** [comment]
Yes, now it works, but, please, consider my necessity to correct several instances of `edtabular` in my book.
I'm also afraid that there may be problems with the pstart cross-reference systems.
In short, how is it possible that for so many years there have been no problems and that, at least until v. 2.32.5, did everything work out well?
Is it not possible to revert the change that caused the problem?

**Comment by maieul** [comment]
as explained, the problem already happen before v2.32.5, as you can see
with this MWE 
https://github.com/maieul/ledmac/blob/90ffdaa5c2704c3ac4533ce90632107a3182d313/issue869.tex

you may see that there already was a spurious line after the
edtabular...

**Comment by Doc73** [comment]
I don't question what you tell me, however I have a PDF generated with that version of reledmac that doesn't have that empty line.
BTW, the important thing is that now it works, so I'll work hard to adapt all my many tables.
Thank you!

**Comment by maieul** [comment]
well, please send my this pdf, the .tex and the .sty file. What I get with the linked file is this

[toto.pdf](https://github.com/maieul/ledmac/files/4878624/toto.pdf)

and with your original MWE

[issue869-original-MWE.pdf](https://github.com/maieul/ledmac/files/4878634/issue869-original-MWE.pdf)

we have the emptyline

So if you tell me that in v2.32.5 you didn't get this output, that is problematic, and we need to find the reason.

**Comment by Doc73** [comment]
I can confirm that edtabular was working very well also with v2.32.6, as you can see in this page of my book, with corresponding log file.

![scholia](https://user-images.githubusercontent.com/1306260/86590621-45796180-bf90-11ea-82c7-8a82426b68c2.png)

**Comment by maieul** [comment]
Well.

But I also tried your MWE with ths version, and I get the ouput I show you. So your MWE was in some way wrong. So the problem is not solved. So please try to provide a MWE showing the problem.

**Comment by maieul** [comment]
You can get older version of reledmac through this page  https://github.com/maieul/ledmac/releases/

**Comment by Doc73** [comment]
Dear @maieul , please, test this MWE (with the very same options of my book):
```tex
% !TeX TS-program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT
% !TeX root = Root.tex

\documentclass[11pt,b5paper]{book}
\usepackage{libertinus}
\usepackage{polyglossia}

\usepackage[noledgroup,noeledsec,series={A,B,C}]{reledmac}
\usepackage{reledpar}
\lineation{page}
\linenummargin{inner}
\sidenotemargin{outer}
\Xnotefontsize[A,B,C]{\footnotesize}
\renewcommand*{\ledlsnotefontsetup}{\raggedleft\it\footnotesize}
\renewcommand*{\ledrsnotefontsetup}{\raggedright\it\footnotesize}
\setsidenotesep{\bgroup\normalfont\ | \egroup}
\Xnonumber[A,B]
\Xnumberonlyfirstinline[C]
\Xnumberonlyfirstintwolines[C]
\Xinplaceofnumber[A,B,C]{0em}
\Xnolemmaseparator[A,B]
\Xnonbreakableafternumber[C]
\Xinplaceoflemmaseparator[A,B]{0em}
\Xinplaceoflemmaseparator[C]{.5em}
\addtolength{\skip\Afootins}{2em plus.4em minus.4em}
\Xbeforenotes[A]{2em plus.4em minus.4em}
\Xafternote[A,B,C]{2em plus.4em minus.4em}
\Xarrangement[A,C]{paragraph}
\Xarrangement[B]{normal}
\labelpstarttrue
\setlength{\Lcolwidth}{0.47\textwidth}
\setlength{\Rcolwidth}{0.47\textwidth}
\setlength{\beforecolumnseparator}{0.06\textwidth}
\columnsposition{C}
\AtBeginPairs{\sloppy}

\makeatletter
\renewcommand{\thepstart}%
	{{\hspace{3mm}\makebox[0pt][r]%
		{\bf\@arabic\c@pstart}}\hspace{3mm}%
	}
\makeatother

\begin{document}
\beginnumbering
\numberpstarttrue

\pstart%
First pstart
\pend

\pstart
Second pstart
\pend

\pstart Third pstart

\begin{edtabularl}
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX
\end{edtabularl}
\pend

\pstart%
Forth pstart

\begin{edtabularl}
	XXXX & XXXXX \\
	XXXX & XXXXX \\
	XXXX & XXXXX
\end{edtabularl}
\pend

\pstart
Fifth pstart
\pend

\numberpstartfalse
\endnumbering

\end{document}
```

With v2.32.6 works fine, very fine.
With v2.34.0, we receive this error: `! LaTeX Error: There's no line here to end`; in order not to have errors, we have to remove the white line before `\begin{edtabularl}`, but, in this case, we have the the empty lines.

**Comment by maieul** [comment]
OK, please next time, go directly to the point.

1. Your problem was not the empty line, but the message `! LaTeX Error: There's no line here to end;`
2. Your empty line was created because you remove the white line before.

So next time, ask directly for the problem, which is the ``! LaTeX Error: There's no line here to end;``, which is solved by the branch. It will be simpler.

I will release tomorrow the fix.

**Comment by Doc73** [comment]
Dear Maieul, yesterday I had no errors, but only the empty line! :smile: 
Also now, with latest `reledmac` version, I had no errors at all during compilation, but with the empty line.
I found this error only after some tests and further investigations :smiley:

**Comment by maieul** [comment]
so all is ok for you, now?, with the branch issue869?

**Comment by Doc73** [comment]
BTW, with branch issue869, I confirm that the issue is solved: no errors, no empty lines in PDF, but... with empty lines in `tex` file.

Thank you very much again! :smile:
