### ISSUE TITLE
Package reledpar Error: The left page has ended on a right page

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#870]
# Version
reledmac 2020/07/06 v2.34.2
reledpar 2020/05/31 v2.24.0

# TeX Engine
XeLateX (MiKTeX 20.6.29)

# Description
My edition includes ancient Greek text and English translation. I receive  the message "Package reledpar Error: The left page has ended on a right page" whenever I compile a certain section of my edition (needless to say that the same message is there when I compile the whole book). I have tried to divide the text of the problematic section to smaller chunks in order to exactly spot the passage which leads to the mistake. I simply cannot find it! Reledpar works just fine with Reledmac whenever I compile single paragraphs of the text. This is the reason why I do not think that any MWE would help - it would work just fine. The message occurs only when I compile the whole of the section. I would be greatful for any advice!

**Comment by maieul** [comment]
well, that may happend for many reason, because reledpar is not able to
synchronize the two pages.

You should look of pagegoalfraction and on package options for
synchronizing.

**Comment by NiAgio** [comment]
Thank you! I tried to change the goalfraction by inserting \renewcommand*{\goalfraction}{0.8} in the preamble. However I receive the error message "Command \goalfraction undefined"... What am I doing wrong?

**Comment by maieul** [comment]
please read the handbook, you must use \setgoalfraction since reledpar

**Comment by maieul** [comment]
please read the handbook, since reledmac you must use
\setgoalfraction....

**Comment by NiAgio** [comment]
Ok, it has worked! Many thanks!
