### ISSUE TITLE
Problems with \hidenumbering, stanza numeration, and layout (reledmac, reledpar)

### ISSUE THREAD

**Issue by andreaacri** [maieul/ledmac#871]
# Version

XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex)
 restricted \write18 enabled.
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-07-17>

 reledmac 2020/07/06 v2.34.2 

reledpar 2020/05/31 v2.24.0

XeLaTex (Error repeating itself in LaTex)

# Regression

no

# Description

I'm using reledmac and reledpar to typeset in parallel an edition of a text arranged in the form of verses/stanzas + prose passages. Ideally, I want to automatically number stanzas (but the numeration might be hidden), and have A/C/Dfootnotes numbers in the apparatus (before the lemma) as follows: e.g. (no chapter number) stanza 1a, 1b, 1c, 1d, 1e etc. , and Bfootnotes numbers as (no chapter) stanza/paragraph (see second paragraph in my example) + line number. Ideally, I would want the line numbers to restart at every paragraph, not page.

In both parallel and normal typesetting, the problems are:

1) \hidenumbering does not seem to work
2) an odd layout is produced, whereby a (numbered) white space appears between two stanza lines
3) The last line of the stanza is numbered (following the page lineation)
4) in parallel typesetting, the first value of the lemma number is 0

Parallel and normal give slightly different layout results (in normal, the stanza is numbered) 

# Minimal Working Example

[containing instances of both customised and "default" numbering in the apparatus]

1) xelatex, normal

\documentclass[11pt,twoside]{book}
\usepackage{fontspec}
\usepackage{xunicode}
\setmainfont[]{Palatino}
\usepackage[parapparatus]{reledmac}

\AtEveryPend{\vspace{\parskip}}

\Xarrangement[A]{paragraph}
\Xarrangement[B]{paragraph}
\Xarrangement[C]{paragraph}
\Xarrangement[D]{paragraph}

\newcommand{\choiceline}[2]{\linenum{|#1|#2||#1|#2}}
\sublinenumberstyle{alph}
\let\fullstop\relax

\setlength{\parindent}{0pt}

\setstanzaindents{0,0,0,0}
\setcounter{stanzaindentsrepetition}{0}
\numberstanzatrue

\Xstanza
\Xstanzaseparator{.}

\lineation{page}
\firstlinenum{1} 
\linenumincrement{1}
\firstsublinenum{1} 
\sublinenumincrement{1}

\begin{document}

\beginnumbering
\skipnumbering
\pstart
\centering{||} O{||} \textit{avighnam astu}{||} O{||}\pend

\pstart\noindent{}\edtext{saṅ}{\Bfootnote{em.; sa LOr}} saṅgrahakāri sira movus{|} liṅnira{|} \pend

\stanza
 \setlength{\leftskip}{15mm}\setlength{\rightskip}{15mm}\itshape\hidenumbering \edtext{śūnyaś}{\choiceline{1}{1}\Afootnote{em.; śūnya A}}  ca \edtext{nirbbāṇādhikaḥ{|} śivāṅgatve}{\linenum{|2|1||2|2|}\Afootnote{em; nirbbhāṇādhika{|} śśivaṅgatve A, B}} nirīkṣyate{|}&
\setlength{\leftskip}{15mm}\setlength{\rightskip}{15mm}\itshape\hidenumbering kutaḥ tadvākyam atulaṁ{|} śrutvā devo \edtext{’vatiṣṭhati}{\Afootnote{em; vatiṣṭha{|} ca A, B}} {||} \normalshape 1.2\&[ ]

\pstart nāhan takvanaknaniṅ hulun ri bhaṭāra{|} hana ya pada śūnya{|} ya sinaṅguh ka\-mo\-kṣan{|} ṅa{|} viśeṣa ya{|} ya śiva ṅaranya{|} \textit{nirīkṣyate}{|} katon pva ya de saṅ \edtext{yogīśvara}{\lemma{\ldots{}gīśvara}\Cfootnote{B om.}}{|} sājñā bhaṭāra{|} an maṅkana kottamaniṅ vuvus saṅ ṛṣi{|} ya ta kaṛṅĕ de bhaṭāra{||} 1.2\pend

\pstart\textit{\edtext{kenopāyena bhagavan}{\choiceline{25}{1}\Afootnote{em.; meyopāyena bhagavān A}\Dfootnote{unmetrical}}}{|}\textit{sukhayogasya lakṣaṇaṁ}{|} \edtext{nihan}{\Bfootnote{conj.; nāhan A}} takvananiṅ hulun ri kita bha\-ṭā\-ra{|} ndya kunaṅ upāyanikā saṅ paṇḍita{|} mataṅyan kapaṅguhāvaknikaṅ sukhādhyātmika{||} 10.25\pend

\endnumbering
\end{document}

2) xelatex, parallel

\documentclass[11pt,twoside]{book}

\usepackage{fontspec}
\usepackage{xunicode}
\setmainfont[]{Palatino}
\usepackage[parapparatus]{reledmac}
\usepackage[shiftedpstarts]{reledpar}

\setlength{\columnrulewidth}{0.4pt}
\AtEveryPend{\vspace{\parskip}}

\Xarrangement[A]{paragraph}
\Xarrangement[B]{paragraph}
\Xarrangement[C]{paragraph}
\Xarrangement[D]{paragraph}

\newcommand{\choiceline}[2]{\linenum{|#1|#2||#1|#2}}
\sublinenumberstyle{alph}
\let\fullstop\relax

\setlength{\parindent}{0pt}
\setstanzaindents{0,0,0,0}
\setcounter{stanzaindentsrepetition}{0}
\numberstanzatrue

\Xstanza
\Xstanzaseparator{.}
\setRlineflag{}

\hidenumberingonrightpage
\firstlinenumR{100000}
\lineation{page}
\firstlinenum{1} 
\linenumincrement{1}
\firstsublinenum{1} 
\sublinenumincrement{1}

\begin{document}

\begin{pages}
\begin{Leftside}
\beginnumbering
  \autopar

\skipnumbering
\centering{||} O{||} \textit{avighnam astu}{||} O{||}

\noindent{}\edtext{saṅ}{\Bfootnote{em.; sa LOr}} saṅgrahakāri sira movus{|} liṅnira{|} 

\begin{astanza}
 \setlength{\leftskip}{15mm}\setlength{\rightskip}{15mm}\itshape\hidenumbering \edtext{śūnyaś}{\choiceline{1}{1}\Afootnote{em.; śūnya A}}  ca \edtext{nirbbāṇādhikaḥ{|} śivāṅgatve}{\linenum{|2|1||2|2|}\Afootnote{em; nirbbhāṇādhika{|} śśivaṅgatve A, B}} nirīkṣyate{|}&
\setlength{\leftskip}{15mm}\setlength{\rightskip}{15mm}\itshape\hidenumbering kutaḥ tadvākyam atulaṁ{|} śrutvā devo \edtext{’vatiṣṭhati}{\Afootnote{em; vatiṣṭha{|} ca A, B}} {||} \normalshape 1.2\&[ ]
\end{astanza}

nāhan takvanaknaniṅ hulun ri bhaṭāra{|} hana ya pada śūnya{|} ya sinaṅguh ka\-mo\-kṣan{|} ṅa{|} viśeṣa ya{|} ya śiva ṅaranya{|} \textit{nirīkṣyate}{|} katon pva ya de saṅ \edtext{yogīśvara}{\lemma{\ldots{}gīśvara}\Cfootnote{B om.}}{|} sājñā bhaṭāra{|} an maṅkana kottamaniṅ vuvus saṅ ṛṣi{|} ya ta kaṛṅĕ de bhaṭāra{||} 1.2

\textit{\edtext{kenopāyena bhagavan}{\choiceline{25}{1}\Afootnote{em.; meyopāyena bhagavān LOr}\Dfootnote{unmetrical (\textit{bha-vipulā} with short second syllable)}}}{|}\textit{sukhayogasya lakṣaṇaṁ}{|} \edtext{nihan}{\Bfootnote{conj.; nāhan A}} takvananiṅ hulun ri kita bha\-ṭā\-ra{|} ndya kunaṅ \edtext{upāyanikā}{\Bfootnote{corr.; opāyanikā A}} saṅ paṇḍita{|} mataṅyan kapaṅguhāvaknikaṅ sukhādhyātmika{||} 10.25

\endnumbering

\end{Leftside}

    \begin{Rightside}
    \beginnumbering
    
{\centering\pstart Everything works here \pend}

\autopar

Everything works here:

\begin{astanza}
\setlength{\leftskip}{15mm}\setlength{\rightskip}{15mm}\itshape Everything works here. Everything works here. Everything works here. Everything works here. Everything works here.\&[ ]
\end{astanza}

Everything works here. Everything works here. Everything works here. Everything works here. Everything works here. Everything works here. Everything works here. Everything works here. Everything works here. Everything works here. (1.2)

Everything works here. Everything works here. Everything works here. Everything works here. Everything works here. Everything works here. Everything works here 10.10
    
    \endnumbering
        \end{Rightside}

\end{pages}
\Pages

\end{document}

# Workaround

The only workaround I have found for this is to substitute \hidenumbering  with \skipnumbering, and omit \numberstanzatrue. However, line numbering is by page, and I have to manually change all the A/C/D footnotes numbers before lemmas by the command \linenum{|1|1||1|2|} etc. (Or \choiceline: https://tex.stackexchange.com/questions/263724/custom-line-numbering-and-using-letters-in-the-linenum-argument?noredirect=1)

**Comment by maieul** [comment]
Please, next time, open one issue for each problem. here you have 4  problem, which means you should open 4 issues,  each of them with it own MWE. 

I will try to answer to your question.

## \hidenumbering does not seem to work

That is because there is an historical inconsistency when the first argument of `setstanzaindents` is equal to zero, all the macro which require the verse has already started, including `hidennumbering` do not consider the verse start, and so does not work. I have correct it in branch issue871. I hope i won't break anything.

## an odd layout is produced, whereby a (numbered) white space appears between two stanza lines

That is because you did 

`\AtEveryPend{\vspace{\parskip}}`

You must know that verse in stanza are just specific `\ptsart...\pend` structure.

You may use 

`\AtEveryPend{\ifinstanza\else\vspace{\parskip}\fi}`

However, there was a bug if you used `lineation{pstart}`(which is required to restart lineation at each paragraph. I have corrected it the branch.

### The last line of the stanza is numbered (following the page lineation)

Well, what is the difference with the bug one ? I don't understand your point. 

### in parallel typesetting, the first value of the lemma number is 0

That is becase numberstanza does not work with astanza. I am looking on it.

**Comment by maieul** [comment]
## in parallel typesetting, the first value of the lemma number is 0

it is now corrected

**Comment by maieul** [comment]
so please try the branch, and do feedback

**Comment by andreaacri** [comment]
The layout problem is fixed in both normal and parallel files (in the latter, only after using  \AtEveryPend{\ifinstanza\else\vspace{\parskip}\fi . Also, the stanza line numbers are now hidden.

I will post somewhere else what I want to achieve in the apparatus visualisation.

Thanks!

**Comment by maieul** [comment]
nice, but please dont close the issue. i will close it when it will be released.
