### ISSUE TITLE
\parafootsepX problem

### ISSUE THREAD

**Issue by frpatte2** [maieul/ledmac#873]
# Version
reledmac 2020/07/06 v2.34.2

# TeX Engine
Même problème en utilisant pdflatex ou xelatex

# Description

J'ai supprimé tous les packages que j'utilise et le problème persiste..

Merci pour ces réactions rapides...

# Minimal Working Example

```latex

```
\documentclass{report}
\usepackage{reledmac}
\arrangementX[A]{paragraph}
\arrangementX[B]{paragraph}

\parafootsepX[A]{$\parallel$}

\begin{document}

Text\footnoteA{note1} Text\footnoteA{note2}

\end{document} 
```
```

# Workaround

**Comment by maieul** [comment]
Oki, ca se posait parce que tu étais en dehors de `\beginnumbering...\endnumbering`. La branche issue873 résoud cela. Peux tu tester ? Merci

**Comment by maieul** [comment]
bonjour, 
des retours?

**Comment by frpatte2** [comment]
La nouvelle version fonctionne correctement sauf quand une note apparaît dans un paragraphe à cheval sur deux pages, auquel cas une note apparaissant sur la deuxième page débute avec le séparateur et la note suivant sans le séparateur.

MCE

\documentclass{report}

\usepackage{reledmac}
\arrangementX[A]{paragraph}
\arrangementX[B]{paragraph}

\parafootsepX[A]{$\parallel$}

\usepackage{lipsum}
\begin{document}

\lipsum[1-3]\footnoteA{note1} \lipsum[4-6]\footnoteA{note2}

Text\footnoteA{note1} Text\footnoteA{note2}

\end{document}

**Comment by maieul** [comment]
hum, ca fait 1 mois que j'ai demadné des retours. Depuis le ticket a été clos et le code envoyé sur le CTAN. 
Donc merci de rouvrir un nouveau ticket en bonne et du forme
