### ISSUE TITLE
Lineation problem

### ISSUE THREAD

**Issue by PaoloMas** [maieul/ledmac#876]
The problem arises when the conditions of the fifth block of the MWE are met, that is, when it begins with the page. In that case and only in that case, the numbering does not start over from one. I tried to change the font but the problem remains. in order to show the problem, I used lipsum but with my file, the behavior is the same.

```
\documentclass[a4paper,
               twoside,
               openright,
               8pt,
               final]
               {memoir}

\usepackage[utf8]{inputenc}
\AtBeginDocument{\linespread{1}}
\usepackage[]{polyglossia}

\usepackage[series={A,B,C,D,E},noledgroup,noend,noquotation,noeledsec]{reledmac}
\usepackage[]{reledpar}
\setgoalfraction{.95}
\numberlinetrue
\linenumincrement*{1}

\setlength{\linenumsep}{1.5mm}
                
\firstlinenum*{0}
\setRlineflag{d}
\setlength{\Lcolwidth}{75mm} 
\setlength{\Rcolwidth}{70mm} 
\AtBeginPairs{\sloppy}

\Xlemmaseparator[A]{$\ulrcorner$}
\Xlemmaseparator[B]{$\ulrcorner$}
\Xlemmaseparator[C]{$\ulrcorner$}
\Xlemmaseparator[D]{$\ulrcorner$}
\Xlemmaseparator[E]{$\ulrcorner$}

\Xarrangement[A]{paragraph}
\Xarrangement[B]{paragraph}
\Xarrangement[C]{paragraph}
\Xarrangement[D]{paragraph}
\Xarrangement[E]{paragraph}

\Xnotefontsize[A]{\footnotesize}
\Xnotefontsize[B]{\footnotesize}
\Xnotefontsize[C]{\footnotesize}
\Xnotefontsize[D]{\footnotesize}
\Xnotefontsize[E]{\footnotesize}

\Xlemmadisablefontselection[A]
\Xlemmadisablefontselection[B]
\Xlemmadisablefontselection[C]
\Xlemmadisablefontselection[D]
\Xlemmadisablefontselection[E]
    


    \Xlemmafont[A]{\itshape\normalsize}
    \Xlemmafont[B]{\itshape\normalsize}
    \Xlemmafont[C]{\itshape\normalsize}
    \Xlemmafont[D]{\itshape\normalsize}
    \Xlemmafont[E]{\itshape\normalsize}
    
\setlength{\ledrsnotesep}{6mm}
\setlength{\ledlsnotesep}{6mm}

\setlength{\ledlsnotewidth}{70pt}
\setlength{\ledrsnotewidth}{70pt}

\fnpos{%
{A}{critical},%
{B}{critical},%
{C}{critical},%
{D}{critical},%
{E}{critical},%
{A}{familiar},%
{B}{familiar},%
{C}{familiar},%
{D}{familiar},%
{E}{familiar}%
}

\Xtxtbeforenotes[A]{M $\cdot$ }  %%%% note del manoscritto
\Xtxtbeforenotes[B]{T $\cdot$ }  %%%% note della traduzione
\Xtxtbeforenotes[C]{V $\cdot$ }  %%%% varianti del manoscritto
\Xtxtbeforenotes[D]{D $\cdot$ }  %%%% definizioni
\Xtxtbeforenotes[E]{C $\cdot$ }  %%%% concetti principali
\usepackage{microtype}
\usepackage{fontspec}
\usepackage{lipsum}
\setmainlanguage{italian}
\setotherlanguages{french}
\setotherlanguages{hebrew}
\setstocksize{297mm}{210mm}
\setlrmarginsandblock{27mm}{33mm}{*}
\setulmarginsandblock{27mm}{38mm}{*}
\setheaderspaces{*}{8pt}{*}
\setheadfoot{25pt}{25pt}
\checkandfixthelayout

%       \setmainfont{Brill Roman}[Scale=1,Ligatures = {Rare,Common}]    
%       \renewcommand{\numlabfont}{\fontspec{Brill Roman}\tiny}
        \setmainfont{TeX Gyre Bonum}[Scale=.79]
        \lineation*{page}
\begin{document}

    \begin{pairs}%
        \begin{Leftside}%
            \beginnumbering%
                \pstart%
\lipsum[1]
                \pend%
            \pausenumbering%
        \end{Leftside}%
        %%%%%%%%%%%%% 1st block 
        \begin{Rightside}%
            \beginnumbering%
                \pstart%
\lipsum[2]
                \pend%
            \pausenumbering%
        \end{Rightside}%
    \end{pairs}%
\Columns%

    \begin{pairs}%
        \begin{Leftside}%
            \resumenumbering%
                \pstart%
\lipsum[3]
                \pend%
            \pausenumbering%
        \end{Leftside}%
        %%%%%%%%%%%%% 2nd block
        \begin{Rightside}%
            \resumenumbering%
                \pstart%
\lipsum[4]
                \pend%
            \pausenumbering%
        \end{Rightside}%
    \end{pairs}%
\Columns%
    \begin{pairs}%
        \begin{Leftside}%
            \resumenumbering%
                \pstart%
\lipsum[5]
                \pend%
            \pausenumbering%
        \end{Leftside}%
        %%%%%%%%%%%%% 3rd block 
        \begin{Rightside}%
            \resumenumbering%
                \pstart%
\lipsum[6]
                \pend%
            \pausenumbering%
        \end{Rightside}%
    \end{pairs}%
\Columns%
    \begin{pairs}%
        \begin{Leftside}%
            \resumenumbering%
                \pstart%
\lipsum[7]
                \pend%
            \pausenumbering%
        \end{Leftside}%
        %%%%%%%%%%%%% 4th block     
        \begin{Rightside}%
            \resumenumbering%
                \pstart%
\lipsum[8]
                \pend%
            \pausenumbering%
        \end{Rightside}%
    \end{pairs}%
\Columns%
    \begin{pairs}%
        \begin{Leftside}%
            \resumenumbering%
                \pstart%
\lipsum[9]
                \pend%
            \pausenumbering%
        \end{Leftside}%
        %%%%%%%%%%%%% 5th block     
        \begin{Rightside}%
            \resumenumbering%
                \pstart%
\lipsum[10]
                \pend%
            \pausenumbering%
        \end{Rightside}%
    \end{pairs}%
\Columns%
\end{document}
```

**Comment by maieul** [comment]
not direclty related, by you can use hookcommand without optional argument if you want to apply to each series.
Instead of 
```
\Xlemmaseparator[A]{$\ulrcorner$}
\Xlemmaseparator[B]{$\ulrcorner$}
\Xlemmaseparator[C]{$\ulrcorner$}
\Xlemmaseparator[D]{$\ulrcorner$}
\Xlemmaseparator[E]{$\ulrcorner$}

```

just do
`
\Xlemmaseparator{$\ulrcorner$}`

**Comment by maieul** [comment]
Well, looking for you MWE, I get with several run (with latexmk) the enclosed output, which seems to be good, that is with line number restarting to 1 at each page.
[issue876.pdf](https://github.com/maieul/ledmac/files/5136117/issue876.pdf)

I think you did only one rune, while it explained in the handbook that you must run several time in order to make reledmac feature working.

**Comment by PaoloMas** [comment]
Please, find the attached pdf as result from ten (10) typeset run.

Let me explain how I have organized my work: I have hundreds of chapters in
french to translate in italian and is
more easy for the work to have only one chunk for each chapter.
It means: chapter 1 french (leftside), chapter 1 italian (rightside), and
the command \Columns.
When there is a page break between chapter n and chapter n+1, the lineation
doesn't reset.
In more than 200 hundred pages it happens 3 or 4 times.
The wrap around I did is obvious: when it happens, I make chapter n and
chapter n+1 in the same reledmac section, I mean within the same \Column
command.
In this way the lineation reset and it is ok.

One thing more but for another little problem: when the last line of the
french section of the chapter (which is between \begin{french} -
\end{french})
occupies the total length of the last print line, one more spurious and
blank numbered line is added.
Also in this case the wrap around is obvious: I move the \end{french}
command from after the last word to before the last word and it is ok.

Best regards.

P. Mascetti


Il giorno gio 27 ago 2020 alle ore 13:50 Maïeul Rouquette <
notifications@github.com> ha scritto:

**Comment by maieul** [comment]
Je ne vois pas le document joint (il faut utiliser l'interface de github pour l'envoyer, répondre par email ne suffit pas).

Je m'appuie sur l'exemple complet minimum que vous m'avez envoyé, pour lequel je ne reproduis pas le problème. Si vous avez un problème ailleur (ce que je veux bien croire), merci de me fournir un exemple complet minimum. Sans quoi je ne peux pas travailler.

**Comment by PaoloMas** [comment]
En regardant le fichier pdf que vous m'avez envoyé, on voit clairement
qu'il ne reproduit pas
les mêmes conditions car la page change au milieu d'un chapitre et non au
début.
Quoi qu'il en soit, merci pour votre soutien.
PM

Il giorno gio 27 ago 2020 alle ore 14:45 Maïeul Rouquette <
notifications@github.com> ha scritto:

**Comment by PaoloMas** [comment]
[mwe.pdf](https://github.com/maieul/ledmac/files/5136537/mwe.pdf)

**Comment by maieul** [comment]
Dans ce cas là, envoyez moi un MWE permettant de reproduire le problème...

**Comment by PaoloMas** [comment]
`\documentclass[a4paper,
	               twoside,
	               openright,
	               8pt,
	               final]
	               {memoir}

\usepackage[utf8]{inputenc}
\AtBeginDocument{\linespread{1}}
\usepackage[]{polyglossia}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  BIBLIOGRAFIA
\usepackage[bibstyle=alphabetic,
		%bibstyle=debug,
		citestyle=alphabetic,
		backref,
		backrefstyle=none,
		backend=bibtex8,
		]
                     {biblatex}

\addbibresource{bib4.bib}

\usepackage[series={A,B,C,D,E},noledgroup,noend,noquotation,noeledsec]{reledmac}
\usepackage[]{reledpar}
\setgoalfraction{.95}
\numberlinetrue
\linenumincrement*{1}

\setlength{\linenumsep}{1.5mm}
				
\firstlinenum*{0}
\setRlineflag{d}
\setlength{\Lcolwidth}{75mm} 
\setlength{\Rcolwidth}{70mm} 
\AtBeginPairs{\sloppy}

\Xlemmaseparator{$\ulrcorner$}

\Xarrangement[A]{paragraph}
\Xarrangement[B]{paragraph}
\Xarrangement[C]{paragraph}
\Xarrangement[D]{paragraph}
\Xarrangement[E]{paragraph}

\Xnotefontsize[A]{\footnotesize}
\Xnotefontsize[B]{\footnotesize}
\Xnotefontsize[C]{\footnotesize}
\Xnotefontsize[D]{\footnotesize}
\Xnotefontsize[E]{\footnotesize}

\Xlemmadisablefontselection[A]
\Xlemmadisablefontselection[B]
\Xlemmadisablefontselection[C]
\Xlemmadisablefontselection[D]
\Xlemmadisablefontselection[E]
		
		\Xlemmafont[A]{\itshape\normalsize}
		\Xlemmafont[B]{\itshape\normalsize}
		\Xlemmafont[C]{\itshape\normalsize}
		\Xlemmafont[D]{\itshape\normalsize}
		\Xlemmafont[E]{\itshape\normalsize}
		
\setlength{\ledrsnotesep}{6mm}
\setlength{\ledlsnotesep}{6mm}

\setlength{\ledlsnotewidth}{70pt}
\setlength{\ledrsnotewidth}{70pt}

\fnpos{%
{A}{critical},%
{B}{critical},%
{C}{critical},%
{D}{critical},%
{E}{critical},%
{A}{familiar},%
{B}{familiar},%
{C}{familiar},%
{D}{familiar},%
{E}{familiar}%
}

\Xtxtbeforenotes[A]{M $\cdot$ }  %%%% note del manoscritto
\Xtxtbeforenotes[B]{T $\cdot$ }  %%%% note della traduzione
\Xtxtbeforenotes[C]{V $\cdot$ }  %%%% varianti del manoscritto
\Xtxtbeforenotes[D]{D $\cdot$ }  %%%% definizioni
\Xtxtbeforenotes[E]{C $\cdot$ }  %%%% concetti principali
\usepackage{microtype}
\usepackage{fontspec}
\usepackage{lipsum}
\setmainlanguage{italian}
\setotherlanguages{french}
\setotherlanguages{hebrew}
\setstocksize{297mm}{210mm}
\setlrmarginsandblock{27mm}{33mm}{*}
\setulmarginsandblock{27mm}{38mm}{*}
\setheaderspaces{*}{8pt}{*}
\setheadfoot{25pt}{25pt}
\checkandfixthelayout

		\setmainfont{TeX Gyre Bonum}[Scale=.79]
		\lineation*{page}
		\ledpbsetting{after}
\begin{document}

	\begin{pairs}%
		\begin{Leftside}%
			\beginnumbering%
				\pstart%
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et
justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
ipsum dolor sit amet.
				\pend%
			\pausenumbering%
		\end{Leftside}%
		%%%%%%%%%%%%% 1st block	
		\begin{Rightside}%
			\beginnumbering%
				\pstart%
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum
dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit
amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna
aliquam erat volutpat.
				\pend%
			\pausenumbering%
		\end{Rightside}%
	\end{pairs}%
\Columns%

	\begin{pairs}%
		\begin{Leftside}%
			\resumenumbering%
				\pstart%
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et
justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
ipsum dolor sit amet.
				\pend%
			\pausenumbering%
		\end{Leftside}%
		%%%%%%%%%%%%% 2nd block
		\begin{Rightside}%
			\resumenumbering%
				\pstart%
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum
dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit
amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna
aliquam erat volutpat.
				\pend%
			\pausenumbering%
		\end{Rightside}%
	\end{pairs}%
\Columns%
	\begin{pairs}%
		\begin{Leftside}%
			\resumenumbering%
				\pstart%
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et
justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
ipsum dolor sit amet.
				\pend%
			\pausenumbering%
		\end{Leftside}%
		%%%%%%%%%%%%% 3rd block	
		\begin{Rightside}%
			\resumenumbering%
				\pstart%
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum
dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit
amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna
aliquam erat volutpat.
				\pend%
			\pausenumbering%
		\end{Rightside}%
	\end{pairs}%
\Columns%
\ledpb
	\begin{pairs}%
		\begin{Leftside}%
			\resumenumbering%
				\pstart%
 Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et
justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
ipsum dolor sit amet.
				\pend%
			\pausenumbering%
		\end{Leftside}%
		%%%%%%%%%%%%% 4th block		
		\begin{Rightside}%
			\resumenumbering%
				\pstart%
 Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum
dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit
amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna
aliquam erat volutpat.
				\pend%
			\pausenumbering%
		\end{Rightside}%
	\end{pairs}%
\Columns%

	\begin{pairs}%
		\begin{Leftside}%
			\resumenumbering%
				\pstart%
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et
justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
ipsum dolor sit amet.
				\pend%
			\pausenumbering%
		\end{Leftside}%
		%%%%%%%%%%%%% 5th block		
		\begin{Rightside}%
			\resumenumbering%
				\pstart%
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum
dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit
amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna
aliquam erat volutpat.
				\pend%
			\pausenumbering%
		\end{Rightside}%
	\end{pairs}%
\Columns%
\end{document}

[mwe.pdf](https://github.com/maieul/ledmac/files/5136839/mwe.pdf)
`

**Comment by maieul** [comment]
Merci de tester la branche issue876.

Pour le problème d'espace indésirable avec les changements de langue, merci d'ouvrir un nouveau ticket (en respectant la structuration proposée lors de la création du ticket)

**Comment by maieul** [comment]
@PaoloMas des retour ?

**Comment by PaoloMas** [comment]
pour le problème de "lineation" toujours le meme. 
j'essaye de recréer l'autre problème mais ce n'est pas facile

**Comment by maieul** [comment]
Arf oui, j'avais résolu à gauche, mais pas à droite. En fait il y avait deux bugs superposés. Bref, pouvez vous tester la nouvelle version de la branche ?

**Comment by PaoloMas** [comment]
j'ai telechargé le zip du dernier branche issue876 et il me semble que le bug est encore là.


[issue876-1.pdf](https://github.com/maieul/ledmac/files/5162289/issue876-1.pdf)
[issue876-2(arial).pdf](https://github.com/maieul/ledmac/files/5162290/issue876-2.arial.pdf)
[issue876-3(arial).pdf](https://github.com/maieul/ledmac/files/5162291/issue876-3.arial.pdf)

**Comment by maieul** [comment]
Avez vous bien généré les fichiers .sty ? Cf le fichier-ci joint, qui sauf erreur de ma part, n'a pas de problème de lineation. 

[issue876.pdf](https://github.com/maieul/ledmac/files/5162487/issue876.pdf)

**Comment by PaoloMas** [comment]
votre pdf n'affiche pas de bloc commençant en haut de la page (comme mon troisième exemple). C'est la seule situation d'erreur.
J'ai téléchargé le fichier zip avec le bouton "code". Si je me suis trompé, je vous demande, si possible, de m'envoyer directement le fichier tex.

**Comment by maieul** [comment]
Comme expliqué dans le tutoriel, il faut que vous generiez les fichiers
.sty, puis que vous les placiez à côté de vos fichiers .tex

(je viens de ressayer en supprimant la première ligne de la page 3 de
mon fichiers, et je confirme que le bug n'est plus présent...)

**Comment by PaoloMas** [comment]
ça marche!

**Comment by maieul** [comment]
parfait !

ca sera publié très prochainement sur la version officielle

**Comment by maieul** [comment]
j'attend par contre le ticket sur le problème d'esapce/de langue

**Comment by PaoloMas** [comment]
envoyé sur github

Il giorno ven 11 set 2020 alle ore 20:15 Maïeul Rouquette <
notifications@github.com> ha scritto:

**Comment by maieul** [comment]
Je vais publier surle CTAN la nouvelle version. J'ai posté une réponse sur github. Merci de la valider.
