### ISSUE TITLE
\parafootsepX new problem

### ISSUE THREAD

**Issue by frpatte2** [maieul/ledmac#877]
# Version

reledmac.sty    2020/08/19 v2.34.3

# TeX Engine

pdflatex et xelatex

# Regression

# Description

La nouvelle version fonctionne correctement sauf quand une note apparaît dans un paragraphe à cheval sur deux pages, auquel cas une note apparaissant sur la deuxième page débute avec le séparateur et la note suivant sans le séparateur.

# Minimal Working Example

```latex
Type your MWE here
```
\documentclass{report}

\usepackage{reledmac}
\arrangementX[A]{paragraph}
\arrangementX[B]{paragraph}

\parafootsepX[A]{$\parallel$}

\usepackage{lipsum}
\begin{document}

\lipsum[1-3]\footnoteA{note1} \lipsum[4-6]\footnoteA{note2}

Text\footnoteA{note1} Text\footnoteA{note2}

\end{document}
# Workaround

**Comment by maieul** [comment]
Bien sûr ! C'était un bug basique  de dev en latex, que j'avais oublié. bref, pouvez vous tester la branche issue877 ? Attention cela nécessite de passer par 2 compilations au moins (de toute facon, en general il vaut mieux utiliser un outils comme latexmk quand on fait du latex, et plus spécialement du reledmac)

**Comment by frpatte2** [comment]
Merci pour cette réaction rapide! Je veux bien tester mais il me manque
quelque chose: je suis les instructions sur cette page:
https://github.com/maieul/ledmac

et je vais sur la page:

https://github.com/maieul/ledmac/tree/issue877

Et là aucun menu "Clone" ou "Download" en vue pour télécharger le
fichier "zip"....

Où me suis-je trompé?

Merci.

**Comment by maieul** [comment]
L'interface  a changé depuis que j'ai écrit ce truc (et visiblement cet été). Il s'agit du menu "code" en vert. Jecorrige le tutoriel.

**Comment by maieul** [comment]
Hum, à l'avenir merci de bien séparer tout les problèmes. 
1. C'est corrigé dans la nouvelle version de la branche. 
2. 
a. Pour l'espace entre le séparateur et le numéro de note, à vous de modifier le séparateur avec `\parafootsepX` en incluant l'espacement que vous voulez à la fin...
b. A cause du mecanisme de cosntruction des notes paragraphés, c'est plus complexe, mais j'essaie de trouver une solution
3. Disons que c'est historique, et que casser cela serait très problèmatique. Mais il vous suffit d'utiliser `\makeatletter\@addtoreset{footnoteA}{chapter}\makeatother` pour obtenir ce résultat.

**Comment by maieul** [comment]
Concernant le point 2b, il n'est pas possible de dire que ne peut pas couper avant le symbole de séparation (en raison de la manière dont fonctionne les notes paragraphés). Par contre on peut pousser à couper plutôt après, en utilisant une penalité négative.

Un code qui devrait correspondre à vos besoin serait :

`\parafootsepX[A]{$\parallel$\hspace{1em plus .4em minus .4em}\penalty -100}`

Ce qui veut dire : "pour la série A, le séparateur est le symbol parallel, suivi d'une espace de 1em  à plus ou moins 0.4 em, et l'on pousse à couper juste après".

**Comment by frpatte2** [comment]
Merci pour toutes ces précisions. 
Il y a encore des pb: parfois le séparateur n'apparaît pas entre deux notes, parfois il apparaît avant la première note d'une page. Je n'ai pas encore trouvé de raisons et je cherche à produire un ECM qui reproduise le phénomène (mais comme il me paraît encore "aléatoire", je ne sais pas encore quoi faire).

**Comment by maieul** [comment]
Est-ce que ce serait pas un problème du nombre de passe latex ? Normalement il vaut mieux utiliser latexmk, pour s'assurer d'avoir pile le bon nombre de passe.

**Comment by frpatte2** [comment]
Non, même en utilisant latexmk, le phénomène se reproduit: sur une page le séparateur entre deux notes n'apparaît pas et sur une autre il manque entre deux notes. Plus précisément: sur une page pas de séparateur entre les notes 17 et 18 et, quelques pages plus loin, la note 19 (première de la page) est précédée du séparateur. Puis, les notes suivantes se comportent normalement.

Le problème: je n'arrive pas à construire un ECM qui reproduise le phénomène...

**Comment by maieul** [comment]
hum. Pas de modification d'une manière où d'une autre de la pagination
? peux tu m'envoyer le fichier .aux ?

**Comment by frpatte2** [comment]
Bon, j'ai l'impression que répondre via l'adresse mail ne fonctionne pas. Comme github n'accepte pas le format "texte", je copie-colle ce fichier:

\relax 
\providecommand\babel@aux[2]{}
\@nameuse{bbl@beforestart}
\babel@aux{french}{}
\babel@aux{french}{}
\pp@pagectr{footnoteA}{1}{2}{2}
\pp@pagectr{footnoteA}{2}{2}{2}
\l@dmake@labels 2|000|000|000|000|0|{parafootsepX@A@1}
\l@dmake@labels 2|000|000|000|000|0|{parafootsepX@A@2}
\l@dmake@labels 2|000|000|000|000|0|{parafootsepX@B@0}
\l@dmake@labels 2|000|000|000|000|0|{parafootsepX@B@1}
\pp@pagectr{footnoteA}{3}{3}{3}
\pp@pagectr{footnoteA}{4}{3}{3}
\l@dmake@labels 3|000|000|000|000|0|{parafootsepX@A@3}
\l@dmake@labels 3|000|000|000|000|0|{parafootsepX@A@4}
\l@dmake@labels 3|000|000|000|000|0|{parafootsepX@B@2}
\l@dmake@labels 3|000|000|000|000|0|{parafootsepX@B@3}
\l@dmake@labels 3|000|000|000|000|0|{parafootsepX@B@3}
\l@dmake@labels 3|000|000|000|000|0|{parafootsepX@B@3}
\l@dmake@labels 5|000|000|000|000|0|{parafootsepX@B@4}
\l@dmake@labels 5|000|000|000|000|0|{parafootsepX@B@5}
\l@dmake@labels 5|000|000|000|000|0|{parafootsepX@B@6}
\l@dmake@labels 5|000|000|000|000|0|{parafootsepX@B@7}
\l@dmake@labels 6|000|000|000|000|0|{parafootsepX@B@8}
\l@dmake@labels 6|000|000|000|000|0|{parafootsepX@B@9}
\l@dmake@labels 6|000|000|000|000|0|{parafootsepX@B@10}
\l@dmake@labels 6|000|000|000|000|0|{parafootsepX@B@11}
\l@dmake@labels 6|000|000|000|000|0|{parafootsepX@B@12}
\pp@pagectr{footnoteA}{5}{7}{7}
\l@dmake@labels 7|000|000|000|000|0|{parafootsepX@A@5}
\l@dmake@labels 7|000|000|000|000|0|{parafootsepX@B@13}
\pp@pagectr{footnoteA}{6}{8}{8}
\l@dmake@labels 8|000|000|000|000|0|{parafootsepX@A@6}
\l@dmake@labels 8|000|000|000|000|0|{parafootsepX@B@14}
\l@dmake@labels 8|000|000|000|000|0|{parafootsepX@B@15}
\gdef \LT@i {\LT@entry 
    {2}{104.1711pt}\LT@entry 
    {3}{147.59384pt}\LT@entry 
    {3}{93.29358pt}\LT@entry 
    {2}{79.89pt}\LT@entry 
    {2}{230.20067pt}}
\newlabel{maridas.ch1.noms.nakshatra}{{}{10}}
\newlabel{maridas.ch1.nakshatra}{{}{12}}
\pp@pagectr{footnoteA}{7}{13}{13}
\l@dmake@labels 13|000|000|000|000|0|{parafootsepX@A@7}
\l@dmake@labels 13|000|000|000|000|0|{parafootsepX@B@15}
\l@dmake@labels 13|000|000|000|000|0|{parafootsepX@B@16}
\l@dmake@labels 14|000|000|000|000|0|{parafootsepX@B@17}
\l@dmake@labels 15|000|000|000|000|0|{parafootsepX@B@18}
\l@dmake@labels 15|000|000|000|000|0|{parafootsepX@B@19}
\l@dmake@labels 15|000|000|000|000|0|{parafootsepX@B@20}
\l@dmake@labels 16|000|000|000|000|0|{parafootsepX@B@21}
\l@dmake@labels 16|000|000|000|000|0|{parafootsepX@B@22}
\@writefile{lof}{\contentsline {figure}{\numberline {1}{\ignorespaces Les \textit  {nakṣatra}\relax }}{17}\protect
ed@file@percent }
\gdef \LT@ii {\LT@entry 
    {1}{79.85551pt}\LT@entry 
    {1}{127.90573pt}\LT@entry 
    {1}{146.71652pt}}
\l@dmake@labels 18|000|000|000|000|0|{parafootsepX@B@23}
\gdef \LT@iii {\LT@entry 
    {1}{25.68752pt}\LT@entry 
    {1}{73.68123pt}\LT@entry 
    {1}{126.36179pt}}
\gdef \LT@iv {\LT@entry 
    {1}{25.68752pt}\LT@entry 
    {1}{58.49086pt}\LT@entry 
    {1}{107.98769pt}\LT@entry 
    {1}{56.30371pt}}
\l@dmake@labels 24|000|000|000|000|0|{parafootsepX@B@24}
\l@dmake@labels 24|000|000|000|000|0|{parafootsepX@B@25}
\l@dmake@labels 24|000|000|000|000|0|{parafootsepX@B@26}
\l@dmake@labels 25|000|000|000|000|0|{parafootsepX@B@27}
\gdef \LT@v {\LT@entry 
    {2}{158.12775pt}\LT@entry 
    {3}{61.09981pt}\LT@entry 
    {1}{55.0992pt}}
\gdef \LT@vi {\LT@entry 
    {2}{99.23866pt}\LT@entry 
    {1}{47.41231pt}\LT@entry 
    {1}{55.0992pt}}
\newlabel{ramayana.r}{{}{28}}

**Comment by maieul** [comment]
Bon,

la bonne nouvelle est que le problème se situe bien au niveau de la production de ce fichier (on ne devrait pas avoir  `\l@dmake@labels 2|000|000|000|000|0|{parafootsepX@B@0}`, ni `\l@dmake@labels 3|000|000|000|000|0|{parafootsepX@B@3}` en trois exemplaire. 

La mauvaise nouvelle est que n'ayant pas le fichier source, il m'est difficile d'investiger.

Toute même, pouvez vous tester avec la nouvelle version de la branche ? et si cela ne marche toujours pas, m'envoyer le fichier .tex qui produit cela ?

**Comment by frpatte2** [comment]
Ça ne marche toujours pas. Je joins (si je peux) le fichier tex en espérant qu'il n'y aura pas de problème de fontes (en général les fontes manquantes s'affichent comme des petits rectangles vides sans incidence sur la compilation).
Github ne veut pas de mon attachement (zip).

**Comment by maieul** [comment]
vous pouvez simplement copier-coller le .tex. Sinon mon adresse mail se trouve facilement...

**Comment by maieul** [comment]
OKi, cela venait, je pense, du fait que vous utiliser `\footnoteBtext`, ce qui fait que les compteurs utilisé pour le crossreferencing n'étaient pas incrémenté au bon moment, et du coup la detection de la page n'était pas bonne.

je vous invite à tester la nouvelle version de la branche.

**Comment by frpatte2** [comment]
Ça marche... Du moins sur la totalité du fichier que j'ai actuellement tapé. 

Merci beaucoup.
