### ISSUE TITLE
Problème avec \Xendlinenumannotationonlyfirst

### ISSUE THREAD

**Issue by PierreChaProt** [maieul/ledmac#879]
# Version
2018/02/28 v2.26.6

# TeX Engine
XeLateX

# Description
Je voudrais utiliser les commandes \SErefwithpage et \apprefwithpage pour renvoyer, en introduction, à des endroits précis de l'édition. Mais XeLaTeX renvoie pour chaque commande \...withpage une erreur "Undefined control sequence. <argument> \annot@start" et/ou "Undefined control sequence. <argument> \annot@start".

J'ai essayé de définir \Xendlinenumannotationonlyfirst, dans le préambule et après \begin{document}, avec et sans argument optionnel, sans succès. Essayer de définir \Xendlinenumannotationonlyfirst dans le préambule renvoie une erreur "Undefined control sequence" ou "Missing \begin{document}", donc visiblement le compilateur ne s'attend pas à rencontrer ça là…

# Minimal Working Example

```latex
\documentclass[a4paper,12pt]{article}

\usepackage{xltxtra}

\setromanfont[Mapping=tex-text]{Linux Libertine O}

\usepackage{reledmac}
\lineation{page}

% \Xendlinenumannotationonlyfirst

\title{MWE}
\author{}
\date{}

\usepackage{hyperref}

\begin{document}
\maketitle

\section{Introduction}

Exemples:
\begin{itemize}
    \item\SErefwithpage{donec} donec
    \item\SErefwithpage{scelerisque} scelerisque
    \item\apprefwithpage{sollicitudin}  sollicitudine
    \item\apprefwithpage{aliquamnisi} aliquam -- nisi 
\end{itemize}



\section{Texte}
\beginnumbering
\pstart
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu ligula et odio mattis commodo. Donec metus urna, tincidunt id efficitur at, porttitor non nisi. Aenean interdum turpis at leo pharetra mattis. \edlabelSE{donec}Donec placerat justo a nisl pulvinar, sit amet interdum arcu \edtext{sollicitudin}{\applabel{sollicitudin}\Afootnote{sollicitudine}}. Proin vitae volutpat ligula. Sed a congue ligula. Donec non magna ex. Sed elit nisl, malesuada quis pretium vitae, lacinia at nulla. Phasellus ultrices odio vitae neque dignissim, sit amet sagittis orci hendrerit. In viverra arcu nisl, ac placerat purus porta eu. Vestibulum tortor ante, fermentum eu quam quis, mattis venenatis leo. Pellentesque eget dictum ante. Etiam in ipsum vel nisi varius lacinia malesuada non tortor.
\pend\pstart
Nulla facilisi. Vestibulum \edlabelS{scelerisque}scelerisque justo vel pretium vestibulum. Suspendisse fringilla sem sed erat imperdiet, sed eleifend augue venenatis. Fusce at egestas sapien, a sodales ex. Nullam nibh mauris, placerat eu metus non, suscipit pulvinar sem. Proin cursus lacinia ex at fringilla. Praesent varius augue at ex commodo pulvinar.
\pend\pstart
Vivamus ac libero quis urna vulputate lobortis. \edtext{Aliquam sit amet ex posuere, pellentesque ante nec, venenatis leo. Pellentesque a odio ante. Integer porta eleifend urna, quis facilisis sapien tempor in. Phasellus nisi lacus, pharetra vel blandit nec, porttitor quis velit. Duis a metus felis. In at semper augue. Praesent id tortor nec erat maximus aliquet. Quisque at ipsum mauris. Nulla congue dictum quam, in elementum tortor laoreet eu. Sed sed lobortis ante, finibus fringilla libero. Ut elementum ipsum sed felis volutpat malesuada. Quisque massa elit, interdum sed egestas ut, dapibus vitae diam. In id placerat turpis.
Aenean aliquam elementum magna, eu finibus leo scelerisque in. Integer eu nisl pretium, posuere augue nec, aliquam lorem. In ultrices non libero vitae gravida. Morbi vitae nisi tempus, tristique lacus non, suscipit purus. Morbi placerat a dolor sed ullamcorper. Pellentesque ornare quis justo at congue. Phasellus odio elit, placerat vel feugiat ac, lobortis non sem. Sed malesuada vestibulum finibus. Etiam justo arcu, rutrum consequat pretium non, sodales ut nisi.}{\applabel{aliquamnisi}\lemma{aliquam -- nisi}\Bfootnote{omisit}} Cras id iaculis neque. Sed fringilla, nunc vitae aliquam molestie, nisl ante eleifend tellus, iaculis maximus sapien dolor et eros.
\pend\pstart
In hac habitasse platea dictumst. Maecenas venenatis faucibus malesuada. Fusce urna dui, feugiat eget erat quis, auctor varius libero. Vestibulum blandit tristique odio ac efficitur. Nam sed ultrices nisl. Morbi vitae libero urna. Suspendisse malesuada vestibulum convallis. Aenean at elit ac neque lacinia fermentum. Suspendisse condimentum odio scelerisque\edlabelE{scelerisque}, sagittis libero eu, lobortis arcu.
\pend
\endnumbering

\end{document}
```

**Comment by maieul** [comment]
peux tu tester la branche issue879 ? Cela devrait résoudre tes problèmes (et permettre aussi d'avoir les annotations de ligne en cross-referencing !)

**Comment by PierreChaProt** [comment]
Non, désolé, j'ai toujours les mêmes erreurs "Undefined control sequence"... et, dans Overleaf, les mêmes indications d'un problème avec etoolbox : 
`Package etoolbox Error: Toggle 'Xendlinenumannotationonlyfirst@SErefwithpage' undefined.`
et 
`Package etoolbox Error: Toggle 'Xendlinenumannotationonlyfirst@apprefwithpage' undefined.`

**Comment by maieul** [comment]
Hum, je pense que tu teste mal :). 
Je t'invite à relire la procédure ici https://github.com/maieul/ledmac#debug-and-feature-requests

**Comment by PierreChaProt** [comment]
Ah oui, désolé. En effet, ça marche très bien. Ça marche aussi si j'enlève les paramètres spécifiques que tu as ajoutés, \firstlinenum, \linenumincrement, la \linenumannotation, la \Aendnote, et le \doendnotes{A}. Et ça marche aussi si je remets les paquets `fontspec`, `xltxtra`, `xunicode` et compile avec `xelatex` : j'obtiens un résultat tout à fait conforme à ce que je souhaitais \o/

**Comment by maieul** [comment]
parfait alors. Je publierai ce week-end. 

Oui j'ai ajouté du code pour vérifier certains petits points, et
enlevait ce qui était pas indispensable, notamment pour pouvoir ensuite
produire un fichier de test de regression qui fonctionne avec pdflatex
(plus rapide que xelatex, et vu le nombre de fichiers de tests de
regression que j'ai, ca compte)
