### ISSUE TITLE
reledmac and pdfpages compatibility

### ISSUE THREAD

**Issue by kascana** [maieul/ledmac#881]
The latest version of reledmac (2020/09/23 v2.34.5) run with pdfTeX (MiKTeX 20.7) appears to have difficulties when one uses simultaneously the pdfpages package. With the latter package activated, the settings \lineation{page} and  \linenummargin{inner} do not work, and the file compiles with continuous line numbers forced on the outer side of the page. This issue was not present in the previous version of reledmac. It would be nice to resolve this. Thank you.

**Comment by maieul** [comment]
please add am MWE.

**Comment by maieul** [comment]
which previous version of the package worked?

**Comment by kascana** [comment]
I don't know the exact version number, but it was the one available via MiKTeX about a month ago. As for an MWE, you may observe the issue if you simply test with one of your own sample files (4-reledpar_pages_long_notes.tex) with \usepackage{pdfpages}, \lineation{page}, and \linenummargin{inner} added in the preamble. As long as the pdfpages package is there, the problem persists, at least on my computer. Without pdfpages the line numbers appear correctly.

**Comment by maieul** [comment]
6c37fcdcbc8a1f3a1ba77994fcdec9845244bfbd is the origin.

**Comment by kascana** [comment]
Alas, I don't understand anything of this, but am very glad that you have been able to localize the culprit so quickly. Hopefully, in the next release of reledmac the issue will be resolved. Thanks much.

**Comment by maieul** [comment]
Well, it is very easy to found the commit which creates the problem. It is more difficulte to solve it.

It seems there is some incompatibility with calc package (loaded by pdfpage), but I don't know exactly why. I asked a question on 

https://tex.stackexchange.com/q/566118/7712

In any case, I could revert this commit, which was only for optinisation.

**Comment by maieul** [comment]
it is fixed in the dev branch. I will release it this week-end.

**Comment by kascana** [comment]
This is wonderful! Thanks much for your efforts and amazing speed!
