### ISSUE TITLE
Disparition de notes dans une sous-section précédée d'un titre de section (Notes disappearing when preceded with section title)

### ISSUE THREAD

**Issue by KumakoHachiko** [maieul/ledmac#883]
# Version

Reledmac 2020/03/08 v2.32.5
Reledpar 2020/03/08 v2.23.0

# TeX Engine

XeLaTeX

# Description

(English follows below)

Je fais un livre de poèmes avec traduction en vis-à-vis. Le livre est divisé en plusieurs sections et chaque poème est une sous-section (de façon à être inclus dans le sommaire). J'ai remarqué que, lorsque la sous-section est précédée d'un titre de section, la première note (et parfois jusqu'aux trois premières notes) de bas de page du poème (de la sous-section, donc) était effacée en bas (alors même que l'appel de note figure dans le texte traduit à droite). On a donc un texte où figurent des appels de note 1,2,3..., mais les notes elles-mêmes commencent avec la note 2 ou la note 3. Il suffit d'effacer le titre de la section pour retrouver la ou les notes disparues.

Y aurait-il une solution à ce problème étrange ? Merci par avance.

................................................................................................................................................................................................................................................................

I am editing a bilingual poetry book, with facing translations. The book is divided into sections and each poem constitutes a sub-section (so as to be included in the table of content). I have noticed that, when a sub-section title is preceded by the title of a section, one or several footnotes of the poem (in the sub-section) are simply not printed underneath the poem in the final pdf, even if the references to these footnotes (the numbers) are displayed within the body of text (on the right, in the translation). As a result, the main body of text has the numbers 1, 2, 3... but the footnotes under the text start with note 2 or 3.  If the section title is deleted, then, the notes reappear automatically under the text.

Is there a workaround for this problem ? Thank you in advance.

# Minimal Working Example

```latex
\documentclass{book}
\listfiles
\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage{french}
\usepackage[]{setspace}
\usepackage[series={A},nocritical,noend,noeledsec,noledgroup]{reledmac}
\usepackage[shiftedpstarts]{reledpar}
\maxhnotesX{0.5\textheight}

\usepackage{lipsum}


\begin{document}

\begin{pages}
\begin{Leftside}


\beginnumbering

\pstart[\section*{Gedichte}]
\pend

\setstanzaindents{5,5,5,5,5,5,5,5}
\stanza[\subsection*{Röslein auf der Heiden}]
Sah' ein Knab ein Röslein stehn\footnoteAnomk{\lipsum[1]}&
Röslein auf der Heiden\footnoteAnomk{\lipsum[1]},&
War so jung und morgenschön\footnoteAnomk{\lipsum[1]},&
Lief er schnell, es nah zu sehn\footnoteAnomk{\lipsum[1]},&
Sah's mit vielen Freuden\footnoteAnomk{\lipsum[1]}.&
Röslein, Röslein, Röslein rot\footnoteAnomk{\lipsum[1]},&
Röslein auf der Heiden\footnoteAnomk{\lipsum[1]}\&

\endnumbering

\end{Leftside}

\begin{Rightside}

\beginnumbering

\pstart[\section*{Poèmes}]
\pend

\setstanzaindents{5,5,5,5,5,5,5,5}
\stanza[\subsection*{Petite rose sur la lande}]
Un enfant vit une petite rose\footnoteAmk &
Petite rose sur la lande\footnoteAmk &
Si jeune et belle en ce matin\footnoteAmk &
Qu'il accourut pour la voir de près \footnoteAmk
&
Il la vit avec joie\footnoteAmk&
Rose, rose, rose rouge\footnoteAmk
&
Petite rose sur la lande\footnoteAmk\&

\endnumbering
\end{Rightside}
\end{pages}
\Pages





\end{document}
```

**Comment by maieul** [comment]
Le problème est votre \pstart...\pend vide, qui perturbe tout, et qui n'est pas nécessaire pour avoir à la fois les sections et les sous sections.

Cf e17b149d
