### ISSUE TITLE
conflict between ledgroup and \arrangementX[<s>]{paragraph}?

### ISSUE THREAD

**Issue by sonator** [maieul/ledmac#886]
# Version
I use the current release

# TeX Engine
  pdflatex

# Regression
The problem appeared later than october 16. 

# Description

Compiling the MWE with familiar notes in the following order, I get error messages. But, compiling it vice versa, id est, the ledgroup before the columns, the MWE runs without problems.

# Minimal Working Example

```latex
Type your MWE here
```

\documentclass{scrbook}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german]{babel}

\usepackage[series={A,B},noeledsec,noend]{reledmac}
\usepackage{reledpar}

\arrangementX[A]{paragraph}
\renewcommand*{\thefootnoteA}{\alph{footnoteA}}
\arrangementX[B]{paragraph}
\renewcommand*{\thefootnoteB}{\arabic{footnoteB}}

\begin{document}

\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart
Columna sinistra. Columna sinistra\footnoteA{Nota A in pede paginae.}. Columna sinistra\footnoteB{Nota B in pede paginae.}.
\pend
\endnumbering
\end{Leftside}

\begin{Rightside}
\beginnumbering
\pstart
Columna dextra. Columna dextra. Columna dextra.
\pend
\endnumbering
\end{Rightside}
\end{pairs}
\Columns

\begin{ledgroup}
\beginnumbering
\pstart
Quod non est in actis non est in mundo. Quod non est in actis non est in mundo. 
\pend
\endnumbering
\end{ledgroup}

\end{document}

# Workaround

**Comment by maieul** [comment]
deda81644d55c35aa37fc8940004bb6230656554 is the origin. I will look to solve it.

**Comment by sonator** [comment]
Thank you! This is not an urgent problem.

**Comment by maieul** [comment]
it is also not a difficult one. Please try the branch issue886

**Comment by sonator** [comment]
Problema solutum est! The MWE and a greater file are running without error. Thank you very much and good evening.

**Comment by maieul** [comment]
nice, I will publish it either tomorrow, either this week-end.
