### ISSUE TITLE
xxref behaving oddly (reledmac 2020/10/10 v2.34.6 and xetex)

### ISSUE THREAD

**Issue by lazzalazza** [maieul/ledmac#890]
# Version
reledmac 2020/10/10 v2.34.

# TeX Engine
xelatex

# Regression

# Description

xxref doesn't seem to work and always produces a 0, as in the attached example.
[Libro.pdf](https://github.com/maieul/ledmac/files/5629242/Libro.pdf)

# Minimal Working Example

```latex
\documentclass[11pt,twoside,openright,showtrims,final]{memoir}
\usepackage[series={A, B, C}]{reledmac}

\begin{document}
\beginnumbering
\pstart

\edlabel{sapien}\edtext{sapien}{%
  \xxref{sapien}{tellus}%
  \lemma{sapien \ldots{} tellus}%
  \Afootnote{not working!}} Nullam eu ante vel est convallis \edtext{dignissim.}{%
  \Afootnote{working!}
} Fusce suscipit,
wisi nec facilisis facilisis, est dui fermentum leo, quis tempor ligula erat
quis odio. Nunc porta vulputate tellus.\edlabel{tellus}
\pend
\endnumbering
\end{document}
```

# Workaround

**Comment by lazzalazza** [comment]
Also tried with reledmac 2020/11/29 v2.35.0 and same results.

**Comment by maieul** [comment]
Hum, you should check your installation, because I get the correct resul after three runs with reledmac


[issue890.pdf](https://github.com/maieul/ledmac/files/5629932/issue890.pdf)

**Comment by maieul** [comment]
some news ?

**Comment by lazzalazza** [comment]
Hi! I'm sorry if I forgot write a follow up! I reinstalled the package and everything seems to work now. Again, sorry for my late reply and thanks for the great work!

**Comment by maieul** [comment]
nice, I close.
