### ISSUE TITLE
Changement de police de caractère ne touchent pas les notes (footnoteX)

### ISSUE THREAD

**Issue by martextins** [maieul/ledmac#891]
J'utlise Xelatex et j'ai essayé de changer la police de caractères pour Source Sans Pro.
D'abord j'ai utilisé la police de mons système avec

\usepackage{fontspec} 
\setmainfont{Source Sans Pro}

Le résultat c'est que le corps du text changes aussi bien que les Afootnote, mais pas les notes familières (familiar notes, pardon, mais je sais pas le terme français). Après j'ai fait une autre tentative avec ce preambule du MWE que je remets. Le résultat c'est le même: le corps du texto change, les notes A aussi, mais pas les notes familières ni les eledsection, eledsubsection, elechapter (pas mêmes les \part du livre).
Merci
Armando Martins

Version du Xelatex:

This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Debian) (preloaded format=xelatex 2020.5.23)  6 DEC 2020 00:12
entering extended mode
 restricted \write18 enabled.

\documentclass[12pt,a4paper]{book}
\usepackage[polutonikogreek,latin,portuges,]{babel}
\usepackage{sourcesanspro}
\renewcommand*\familydefault{\sfdefault}
\let\oldfootnote\footnote
\renewcommand{\footnote}[1]{\oldfootnote{\sffamily#1}}
\usepackage{lettrine}
\usepackage[utf8x]{inputenc}
\usepackage[series={A,B}]{reledmac}
\Xarrangement[A]{paragraph}
\Xarrangement[B]{paragraph}
\arrangementX[A]{paragraph}
\arrangementX[B]{paragraph}
\usepackage[T1]{fontenc}
\newcommand{\cmmnt}[1]{\ignorespaces}

\begin{document}
\part{Introdução}
\part{Edição}
\selectlanguage{latin}

\lineation{page}

\fnpos{familiar-critical}
\beginnumbering

\pstart
\eledsection*{De Baetica Hispania
	Caput decimum nonum}
\pend

\pstart
Ab oriente terminatur linea ducta a \edtext{Charidemi}{\Afootnote{Caridani \textit{C}}} promontorio ad Anam usque per Castulonem quae urbs Baeticae est ad Anam fluuium, nunc \textit{Caslona} Carolo Clusio, uel \textit{Caslona la}\edtext{\textit{Vieja}}{\Afootnote{Vieia \textit{post corr. C}}} aliis. 
\pend

\pstart
A Baeti flumine eam interfluente nomen sortita est. Eiusdem longitudinem constituit Plinius a Castulone \edtext{250 000}{\Afootnote{1250 \textit{C}}} passus, latitudinem uero qua maxima est a Carteia (nunc \textit{Tarifa} Augusto \edtext{Curione}{\Afootnote{Curioni \textit{C}}}\footnoteA{CSar: I, 42} teste) uel Carthagena quae ad fretum Gaditanorum Carolo Clusio \edtext{236 000}{\Afootnote{236 \textit{A}}}. In ea quattuor [Plinius] statuit conuentus: Gaditanum, quare in \edtext{Gadibus}{\Afootnote{G<.>dibus \textit{A}}}  insula olim /74v/ \edtext{Cotynusa}{\Afootnote{Catynusa \textit{post. corr.} Catyniua \textit{ante corr. A}}} (Dionysio poetae), \edtext{Gades}{\Afootnote{Cales \textit{A}}}, \edtext{Graece}{\Afootnote{post corr. \textit{A}}} \edtext{Gadeira}{\Afootnote{Garura \textit{A}}}, (Volaterrano\footnoteA{VCom, II, 9} uero  \edtext{Erythrea}{\Afootnote{Erystreia \textit{A}}}); secundum Cordubensem, quia in Corduba  \edtext{Senecae}{\Afootnote{Seni- \textit{A}}} <et> Lucani patria; tertium Astigitanum, quare in \edtext{Turdetanorum}{\Afootnote{Turdetenorum \textit{A}}} oppido olim Astigi, alias Astid, uel Astygis et Augusta \edtext{Firma}{\Afootnote{Prima \textit{A}}}, atque etiam Astygitana colonia Tarapha\footnoteA{TOr: 55} teste, nunc  \edtext{\textit{Écija}}{\Afootnote{Esige \textit{A}}} uulgo  \edtext{si}{\Afootnote{\textit{scripsi} Socal \textit{pro} si Carolo \textit{A}}} Carolo Clusio\footnoteA{OrtSyn: 55}, Taraphae\footnoteA{TOr: 35} et Moletio\footnoteA{MolG: 15} credimus; quartum demum Hispalensem quare in Hispali, quae olim Iulia \edtext{Romulia}{\Afootnote{Rumulia \textit{A}}}, episcopo \edtext{Gerundense}{\Afootnote{Gerundensi \textit{A}}}\footnoteA{MyP: I, f. XXII} teste, nunc \textit{Sevilha}, Tarapha\footnoteA{Cf. TOr: 20, 124, 167 (\textit{nihil tamen de Iulia Romulia}).} et Clusio\footnoteA{Sevilla hodie dicitur. Episcopus Gerundensis scribet eam a Strabone Iulia Romulia appellari}.
\pend

\endnumbering
\end{document}

**Comment by maieul** [comment]
Dans tous les cas, je vous conseillerai d'utiliser la police système, car je n'y connais pas grand chose aux fontes tex. Je regarde pour le reste du problème.

**Comment by maieul** [comment]
Donc comme je disais, si j'utilise la police système, cela marche très bien.

Voici comment j'ai fait

```
\documentclass[12pt,a4paper]{book}
\usepackage[polutonikogreek,latin,portuges,]{babel}
\usepackage[series={A,B}]{reledmac}
\usepackage{fontspec}
\setmainfont{Source Sans Pro}
\Xarrangement[A]{paragraph}
\Xarrangement[B]{paragraph}
\arrangementX[A]{paragraph}
\arrangementX[B]{paragraph}
\lineation{page}
\fnpos{familiar-critical}
\newcommand{\cmmnt}[1]{\ignorespaces}
\begin{document}
\part{Introdução}
\part{Edição}
\selectlanguage{latin}

\beginnumbering

\pstart
\eledsection*{De Baetica Hispania
Caput decimum nonum}
\pend

\pstart
Ab oriente terminatur linea ducta a \edtext{Charidemi}{\Afootnote{Caridani \textit{C}}} promontorio ad Anam usque per Castulonem quae urbs Baeticae est ad Anam fluuium, nunc \textit{Caslona} Carolo Clusio, uel \textit{Caslona la}\edtext{\textit{Vieja}}{\Afootnote{Vieia \textit{post corr. C}}} aliis.
\pend

\pstart
A Baeti flumine eam interfluente nomen sortita est. Eiusdem longitudinem constituit Plinius a Castulone \edtext{250 000}{\Afootnote{1250 \textit{C}}} passus, latitudinem uero qua maxima est a Carteia (nunc \textit{Tarifa} Augusto \edtext{Curione}{\Afootnote{Curioni \textit{C}}}\footnoteA{CSar: I, 42} teste) uel Carthagena quae ad fretum Gaditanorum Carolo Clusio \edtext{236 000}{\Afootnote{236 \textit{A}}}. In ea quattuor [Plinius] statuit conuentus: Gaditanum, quare in \edtext{Gadibus}{\Afootnote{G<.>dibus \textit{A}}} insula olim /74v/ \edtext{Cotynusa}{\Afootnote{Catynusa \textit{post. corr.} Catyniua \textit{ante corr. A}}} (Dionysio poetae), \edtext{Gades}{\Afootnote{Cales \textit{A}}}, \edtext{Graece}{\Afootnote{post corr. \textit{A}}} \edtext{Gadeira}{\Afootnote{Garura \textit{A}}}, (Volaterrano\footnoteA{VCom, II, 9} uero \edtext{Erythrea}{\Afootnote{Erystreia \textit{A}}}); secundum Cordubensem, quia in Corduba \edtext{Senecae}{\Afootnote{Seni- \textit{A}}} Lucani patria; tertium Astigitanum, quare in \edtext{Turdetanorum}{\Afootnote{Turdetenorum \textit{A}}} oppido olim Astigi, alias Astid, uel Astygis et Augusta \edtext{Firma}{\Afootnote{Prima \textit{A}}}, atque etiam Astygitana colonia Tarapha\footnoteA{TOr: 55} teste, nunc \edtext{\textit{Écija}}{\Afootnote{Esige \textit{A}}} uulgo \edtext{si}{\Afootnote{\textit{scripsi} Socal \textit{pro} si Carolo \textit{A}}} Carolo Clusio\footnoteA{OrtSyn: 55}, Taraphae\footnoteA{TOr: 35} et Moletio\footnoteA{MolG: 15} credimus; quartum demum Hispalensem quare in Hispali, quae olim Iulia \edtext{Romulia}{\Afootnote{Rumulia \textit{A}}}, episcopo \edtext{Gerundense}{\Afootnote{Gerundensi \textit{A}}}\footnoteA{MyP: I, f. XXII} teste, nunc \textit{Sevilha}, Tarapha\footnoteA{Cf. TOr: 20, 124, 167 (\textit{nihil tamen de Iulia Romulia}).} et Clusio\footnoteA{Sevilla hodie dicitur. Episcopus Gerundensis scribet eam a Strabone Iulia Romulia appellari}.
\pend

\endnumbering
\end{document}
```

Quelques commentaires:
- avec XeLateX, inutile d'utiliser inputenc et fontenc
- il faut en revanche utiliser fontspec
- là ca bascule la police principale en Soruce Pro. J'imagine que c'était bien votre souhait, même si le message n'était pas hyper clair
- j'ai déplacé tout les réglages reledmac dans le préambule
- reledmac et lettrine ne fonctionne pas bien, de mémoire, pour l'heure (et je n'ai pas le temps de m'occuper de cela)

**Comment by martextins** [comment]
Merci beaucoup. Ça a marché três bien.
Armando Martins

**Comment by maieul** [comment]
je ferme donc
