### ISSUE TITLE
subline alpha style incompatibility with polyglossia

### ISSUE THREAD

**Issue by michael2457** [maieul/ledmac#896]
# Version
2020/12/20 v2.35.1

# TeX Engine
XeLateX

# Description
Using polyglossia with a Greek font in a verse stanza, subline lineation works well.  But if I set \sublinenumberstyle{alph}, polyglossia issues an error.  I have not tried parallel typesetting.

# Minimal Working Example

```latex
\documentclass{article}
\usepackage{reledmac}
 \setstanzaindents{0,0}
 \setcounter{stanzaindentsrepetition}{1} 
 \firstlinenum{1}
 \linenumincrement{1}
 \sublinenumberstyle{alph}
 
\usepackage{fontspec}
\usepackage{polyglossia}
 \setdefaultlanguage{english}
 \setotherlanguage{greek}
 \setmainfont[Numbers=OldStyle]{STEP}
 \newfontfamily\greekfont{Tempora-Regular}

\begin{document}

\begin{greek}
\beginnumbering
\stanza%
    θεμιστεῖον ὃς ἀμφέπει σκᾶπτον ἐν πολυμήλῳ&
\startsub    Σικελίᾳ δρέπων μὲν κορυφὰς ἀρετᾶν ἄπο πασᾶν,&
    ἀγλαΐζεται δὲ καί&
    μουσικᾶς \edtext{ἐν}{\Afootnote{ὑπό}} ἀώτῳ,& % (15)
\endsub     οἷα παίζομεν φίλαν &
    ἄνδρες ἀμφὶ θαμὰ τράπεζαν. ἀλλὰ Δωρίαν ἀπὸ φόρμιγγα πασσάλου\& % (17)
\endnumbering
  \end{greek}

\end{document}
```

# Workaround

**Comment by maieul** [comment]
please, provide link to the font, in order to allow me to test.

**Comment by michael2457** [comment]
Unrelated to this issue, I wonder how (if possible) to get a subline number (e.g. 2.1) included in the marginal text lineation?  And how to get the subline number printed in the margin when it would not get printed in the normal linenumincrement?

**Comment by michael2457** [comment]
I believe this is the font: http://mirrors.ctan.org/fonts/tempora.zip
but any Greek polytonic font should work.

**Comment by michael2457** [comment]
> > Unrelated to this issue, I wonder how (if possible) to get a subline number (e.g. 2.1) included in the marginal text lineation? And how to get the subline number printed in the margin when it would not get printed in the normal linenumincrement?
> 
> I think you should read § 5.4.1 of the handbook, which title is "sublineation".

Thanks.  Actually I just now found the answer in § 5.3.2 and § 5.4.3.

**Comment by maieul** [comment]
> Thanks. Actually I just now found the answer in § 5.3.2 and § 5.4.3.

Nice. Maybe I should add crossreferencng.

**Comment by maieul** [comment]
To come back to your main problem, that is because polyglossia do some hack in order to print number in greek lineation, and it is not fully implemented, I guess.

But i suppose you want latin character numbering, and not greek numbering, so you can simply use `numberals` option when loading greek.

`\setotherlanguage[numerals=arabic]{greek}`

**Comment by michael2457** [comment]
> To come back to your main problem, that is because polyglossia do some hack in order to print number in greek lineation, and it is not fully implemented, I guess.
> 
> But i suppose you want latin character numbering, and not greek numbering, so you can simply use `numberals` option when loading greek.
> 
> `\setotherlanguage[numerals=arabic]{greek}`

Thanks!  That takes care of the problem.  And thanks also for reporting the issue to the polyglossia author.
