### ISSUE TITLE
suppress or disable printing of a series of critical footnotes

### ISSUE THREAD

**Issue by michael2457** [maieul/ledmac#897]
# Version
2020/12/20 v2.35.1

# TeX Engine
XeTeX

# Regression

# Description
I'm requesting adding a feature to allow selective printing of a series of critical notes -- e.g., to print only Afootnotes even if both A and other series are included in the source.  I have not tried parallel typesetting.

# Minimal Working Example
I think this does not apply.

```latex
Type your MWE here
```

Thank you!

**Comment by maieul** [comment]
Well, A MWE always applies.

Anyway, could you test the branch issue897, which provide `\Xseries` and `\seriesX`, which optional argument is for the series. 

To know how to test, please read https://github.com/maieul/ledmac#debug-and-feature-requests

**Comment by maieul** [comment]
hi @michael2457 some feedbacks ?

**Comment by michael2457** [comment]
I have now tested the new version pretty thoroughly and find no problems.  (The "trivial" problem I mentioned in an email is resolved; it had nothing to do with the new version.)

Amazingly impressive work!  Thanks again.

**Comment by maieul** [comment]
Nice. I will publish it friday, then post an answer on SE. At this time, please validate it.
