### ISSUE TITLE
endsub not working on right side (reledpar reledmac)

### ISSUE THREAD

**Issue by DarkBlueMaster** [maieul/ledmac#898]
# Version
reledmac   2020/12/20 v2.35.1
reledpar    2020/11/29 v2.25.0

# TeX Engine
Tried with pdfLaTeX, XeLateX and LuaLaTeX. No difference.

# Regression
unknown

# Description
If a sub enviroment is opend on the right side with \startsub, the closing command \endsub is not working correctly. On the left side everything is working fine. You can see the bug in the footnotes in the minimal example below.

# Minimal Working Example
```latex
\documentclass[twoside]{scrbook}
\usepackage[]{reledmac}
\usepackage{reledpar}
\setlength{\parindent}{0pt}

\begin{document}

\title{Edition}
\begin{pairs}
    \begin{Leftside}
        \beginnumbering
        \pstart\startsub
         {\edtext{Test}{\Afootnote{Test}}}
        \endsub\pend
        \pstart
       Lorem ipsum {\edtext{dolor}{\Afootnote{Test}}} sit amet\\ 
       consetetur sadipscing elitr
       \pend
       \endnumbering
    \end{Leftside}
    \begin{Rightside}
        \beginnumbering
        \pstart\startsub
         {\edtext{Test}{\Bfootnote{Test}}}
        \endsub\pend
        \pstart
       Lorem ipsum  {\edtext{dolor}{\Bfootnote{Test}}} sit amet\\ 
       consetetur sadipscing elitr
       \pend
        \endnumbering
    \end{Rightside}
\end{pairs} 
\Columns

\end{document}
```

# Workaround

No workaround known (would be happy if there is one)

**Comment by maieul** [comment]
Please try branch issue898.
To know how to dit, read
https://github.com/maieul/ledmac#debug-and-feature-requests

**Comment by DarkBlueMaster** [comment]
That looks perfect, thanks so much for the quick help. I tried some different scenarios and everything worked fine.

**Comment by maieul** [comment]
Please don't close issue. I will close myself when I will publish it on CTAN (I hope Friday)

At this time
1. Remove your .sty file, and upgrade your installation
2. I will publish and answer on SE, please validate it.
