### ISSUE TITLE
Hyperref breaks linenumbers and sidenotes for \eledsection etc

### ISSUE THREAD

**Issue by floriandk** [maieul/ledmac#899]
# Version

reledmac v2.36.0
up-to-date TL2020

# TeX Engine

all

# Regression

The closest I can get is that I have an older version of the example file "2-titles_in_line_numbering_with_notes.pdf" compiled on 23 February 2019 that behaves correctly

# Description

Some change broke the printing of linenumbers for `\eledsection` etc. The sidenotes have disappeared for all unstarred versions.
`\eledchapter` seems unaffected.

It seems that calling hyperref in the file is the culprit. The result looks ok when I remove it.

I am wondering whether this is related to the [problems I reported earlier](https://github.com/maieul/ledmac/issues/746) with disappearing linenumbers for KOMA-script. 

# Minimal Working Example

2-titles_in_line_numbering_with_notes.tex

```latex
Type your MWE here
```

# Workaround

**Comment by maieul** [comment]
The problem happend only with scrbook... so same pb as #899

**Comment by maieul** [comment]
sorry, misreading

**Comment by maieul** [comment]
But tried with v2.0.0 I have already the problem,...

**Comment by maieul** [comment]
Problem solved. Hypeeref break something in its code

But that does not solve #746. Someday, maybe...
