### ISSUE TITLE
Recommencer le numérotage des notes familières

### ISSUE THREAD

**Issue by martextins** [maieul/ledmac#900]
J'ai utilisé beaucoup de notes familières dans une partie d'une édition. À la fin j'ai des notes avec un nombre de trois chiffres. Ça rendrait le text plus leger si j'avais des nombres de notes dans le texte soit soit un plus petits soit avec une numérotation qui recommence disons à chaque chapitre.

Le meilleur moyen pour le faire serait-il de mettre plusieurs \beginnumbering \endnumbering ou est-ce qu'il y a un autre moyen?
Merci.

Version de reledmac:
Package: reledmac 2020/02/04 v2.32.4 typesetting critical editions
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Debian) (preloaded format=xelatex 2020.5.23)  6 FEB 2021 00:22

**Comment by maieul** [comment]
Les numéros de notes ne sont pas liés aux \beginnumbering/endnumbering.
Il y a un compteur par série (footnoteA, footnoteB, etc).

Le mieux est de programmer pour que les compteurs soient réinitialisé à chaque chapitre, via `\@addtoreset` :

``` 
\makeatletter
\@addtoreset{footnoteA}{chapter}
\makeatother
``` 


Sur les compteurs et leur réinitialisation, voir le chapitre que j'y consacre dans mon livre sur LaTeX appliqué aux SHS.
