### ISSUE TITLE
Multiple input files break the variant line numbers

### ISSUE THREAD

**Issue by zvtoth** [maieul/ledmac#901]
# Version

the latest

# TeX Engine

LuaLatex, via latexmk

# Description

We are typesetting a whole book of critical edition with different chapters. Due to the complexity and length of the text, each chapter is in a separate file, and we compile them "centrally" by using a root file and the \input{} command.
When the files are compiled separately (having only a single \input in the root), everything is fine. However, when we try to compile multiple files at once (\input{chapter1} \input{chapter2} etc.), then the line numbers of some of the variants break. This seems to be especially a problem in overlapping variants. 

# Minimal Working Example

Here is an example, where the line numbers printed fine when only this file was compiled, but got messed up if we compiled with it the subsequent chapter. 

```latex
\edtext{\sameword[1,2]{sciri}}{\linenum{||||\xlineref{overlap-1}}\lemma{\sameword{sciri} \sameword{desideratur}]}\Afootnote[nosep]{scire desiderant~EN, \textit{om.}~P}}}{\lemma{desiderant -- \sameword{sciri}}\Afootnote[nosep]{\textit{rep. sed corr.}~V}} \sameword{desideratur}\edlabel{overlap-1}
\sameword{est} unum scibile.```

# Workaround

Compile everything on its own.... was trying to avoid that.

**Comment by maieul** [comment]
SOrry, but I really need a MWE to work. What your provide is not a MWE.

**Comment by zvtoth** [comment]
Yes, I'm aware it's not a MWE. 
We figured it out. THe problem was that the overlap became ambiguous across multiple files when they were stitched together.

**Comment by maieul** [comment]
There is no reason that input change things, except if you use multipe \beginnumbering, but in this case te problem is with multle begininumbering, and you could provide a MWE.

In any case, I won't lost time to try to reproduce your error.

**Comment by maieul** [comment]
are you sure you dont have duplicate label ?

**Comment by zvtoth** [comment]
We have new \beginnumbering in each file. We had to disambiguate the \overlap's between the different files, somehow latex got confused about which one belonged where.

Sorry I could not give a MWE, but our files are so complicated at this point that I didn't know how to strip them. Feel free to close this.

**Comment by maieul** [comment]
So I close, and one you will have a MWE, I could analyse your problem.

**Comment by maieul** [comment]
I think, however, that it is possible your problem is caused by crossef between different beginnumbering.. YOu could try to produce a MWE from this pist.

**Comment by zvtoth** [comment]
OK. I'll that if I have time. Thanks.

**Comment by maieul** [comment]
I have send a new version on CTAN which correct some crossreferencing bug.

Maybe it correct yours.
