### ISSUE TITLE
Error with option 'parapparatus' when nesting footnote

### ISSUE THREAD

**Issue by marquinho78** [maieul/ledmac#910]
# Version

reledmac 2021/01/21 v2.36.0

# TeX Engine

pdfLaTeX

# Description

Option `parapparatus` of reledmac allows paragraphing within footnotes (unless their arrangement is set to "paragraph").

However, if the footnote is nested within (the `\edtext{}` macro of) any other footnote, a paragraph break cannot be introduced. File doesn't compile and gives the error `Paragraph ended before \showlemma was complete.`

The problem occurs with plain reledmac, without other packages loaded, in normal typesetting.

# Minimal Working Example

```
\documentclass{article}
\usepackage[parapparatus]{reledmac}

\begin{document}
\beginnumbering

\pstart
\edtext{Lemma Bigger FN...
%
  \edtext{Lemma Nested FN}{%
  \Afootnote{First paragraph.
  \par                                           % the "forbidden" paragraph break
  Second paragraph.}}
%
...end of lemma.}{%
\Afootnote{Text Bigger FN.}}
\pend

\endnumbering
\end{document}
```

# Workaround

Instead of using \par or a blank line, one can force a line break within the footnote with `\newline` or `\\` or `\\[<vertical space>]`. These do not count as paragraph breaks and do not cause the error.

**Comment by maieul** [comment]
please try branch issue910

**Comment by marquinho78** [comment]
Thanks, one part of the problem is solved: Now there's no error when nesting within a "normal" footnote.

But unfortunately the problem persists when nesting a "normal" footnote within a "paragraph" footnote, like this:

```
\documentclass{article}
\usepackage[parapparatus]{reledmac}
\Xarrangement[B]{paragraph}

\begin{document}
\beginnumbering

\pstart
\edtext{Lemma Bigger FN (paragraphed)...
%
  \edtext{Lemma Nested FN (normal)}{%
  \Afootnote{First paragraph.
  \par                                           % the "forbidden" paragraph break
  Second paragraph.}}
%
...end of lemma.}{%
\Bfootnote{Text Bigger FN (paragraphed).}}
\pend

\endnumbering
\end{document}
```

Should I open a new issue?

**Comment by maieul** [comment]
No, it it the same problem (but the solution is more complex !)

**Comment by maieul** [comment]
Please try new version.

**Comment by marquinho78** [comment]
Yes, it works great!
Both the MWE and the real-life text that made me aware of the issue.

Thanks a lot for this and – it goes without saying – for all your great work on (r)(e)ledmac!

**Comment by maieul** [comment]
nice, I think a will be a maintenance release this week-end.

**Comment by maieul** [comment]
The release is currently running. Please validate my answer on SE.
