### ISSUE TITLE
Master Document pour de nombreux poèmes: erreur reledpar compilateur  

### ISSUE THREAD

**Issue by menarinis** [maieul/ledmac#911]
**# Version**: 2.36.0
**# TeX Engine**: XeLatex 

**# Description**:
Salut, comment ça va? Je vous demande votre aide sur la structure d'un livre qui contient le "file Master" et de nombreux poèmes. Je attaque un exemple. Mon problème est qu'avec cette structure, j'obtiens des erreurs. Mais je dois nécessairement utiliser ces commandes dans chaque poème et non dans le "file Master". Comment puis-je faire? Merci d'avance pour les conseils! 
J'ai également fait 3 autres tests en utilisant: le package Standalone, le package Subfiles et un modèle propre téléchargé à partir de https://www.latextemplates.com/cat/books, mais rien à faire, j'obtiens le même genre d'erreurs. J'ai probablement tort de structurer le fichier mainfile.tex ou les fichiers enfants. Si vous pouviez m'aider, je vous serais très reconnaissant.
Donato

**MWE:**

Master Document:
\documentclass[a5paper,openany]{book}

\usepackage{verse}
\PassOptionsToPackage{bookmarks, colorlinks=false, hidelinks}{hyperref}
% Use PoetryTeX; http://www.ctan.org/pkg/poetrytex
\usepackage[numberpoems, clearpageafterpoem, useincipits]{poetrytex}

\usepackage{polyglossia}
\setmainlanguage{italian}
\setotherlanguages{latin,spanish,german,french,english}
\setotherlanguage[variant=polytonic]{greek}

\usepackage{verse}                  
\usepackage[series={A,B,D}]{reledmac}
\usepackage[]{reledpar}

% Use the PA5 paper size
\usepackage[paperwidth=140mm,paperheight=210mm]{geometry}

\renewcommand{\pttitle}{A Collection of Poetry}
\renewcommand{\ptsubtitle}{Mostly by people.}
\renewcommand{\ptauthor}{Someone}
\renewcommand{\ptdate}{2014/12/10}
\renewcommand{\ptdedication}{Frontmatter haiku:\\*This is dedicated to,\\*Someone else, not you.}

\includeonly{
	poes11,
	poes12,
	poes13,
	poes21,
	poes22,
	poes23,
		}
\begin{document}
\maketitle
\makededication

\frontmatter
\maketoc
\renewcommand*{\topname}{Poems} % Name for the table of poems
\maketop

\section{Preface}
This is a prose preface.

\newpage
\thispagestyle{empty}

\mainmatter
\chapter{Introduzione}
Scrivere una semplice raccolta di poesie 

\chapter{Poesie satiriche}
\include{poes11}
\include{poes12}
\include{poes13}
\chapter{Maitunate}
\include{poes11}
\backmatter
\end{document}

_________________
poes11.tex
\addcontentsline{toc}{subsection}{Tsus eda mep niter}
\section*{I lax settur sumpi}
\begin{pages}
\begin{Leftside}
\beginnumbering
\gdef\linenumberlist{1,2,6,8}
\begin{astanza}[{\textbf{Ud giuia inele}}]
\setline{1}
\newverse
Unitor semper quisque labi atter cumdaà!&
Unitor semper quisque labi atter cumdaà!&
Unitor semper quisque labi atter cumdaà!&
Unitor semper quisque labi atter cumdaà!&
\end{astanza}
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\gdef\linenumberlist{2,4,6,8}
\begin{astanza}[{\textbf{II lax settur sumpi}}]
\setline{1}
\newverse
Unitor semper quisque labi atter cumdaà!&
Unitor semper quisque labi atter cumdaà!&
Unitor semper quisque labi atter cumdaà!&
Unitor semper quisque labi atter cumdaà!&
\end{astanza}
\endnumbering
\end{Rightside}
\end{pages}
\Pages
__________________

Erreur du compilateur (utilisez Xelatex dans texlive)
Missing number, treated as zero. \setline
Missing = inserted for \ifnum. \setline
Package reledmac Error: You have not defined the indentation for the line 1. \setline
etc.etc

**Comment by maieul** [comment]
Je ne suis pas sur de comprendre votre problème, surtout que

1. Vous n'avez pas rempli les champs où je demandais des précisions importantes ....
2. Votre MWE n'est pas complet


Mais visiblement vos erreurs ont lieu au moment de l'interprétation du preambule. Il semblerait que bidi (le package qui permet de gerer l'écriture de droite à gauche, appelé lorsque vous charger l'arabe) ait encore changé des choses dans son fonctionnement, qui fait que l'ordre de chargement est important.

Bref, la solution est simple : charger vos langues avant reledmac.

**Comment by menarinis** [comment]
Salut et merci pour la pointe, j'ai chargé, comme vous l'avez suggéré et j'ai supprimé l'arabe de la liste. Maintenant l'erreur "bidi"a disparu mais les autres restent:
Missing number, treated as zero. \setline
Missing = inserted for \ifnum. \setline
Illegal unit of measure (pt inserted). \setline
Package reledmac Error: You have not defined the indentation for the line 1. \setline
....

**Comment by maieul** [comment]
Ce problème n'est aussi pas lié aux inputs. Il y a un message clair " You have not defined the indentation for the line".

Vous deveu utiliser la commande `setstanzaindents` (see §9.2 and 9.3 of the handbook). 

Par ailleur, il est inutile d'utiliser `\newverse` pour le tout premier vers.

**Comment by menarinis** [comment]
Merci, j'ai également apporté les modifications à votre dernier e-mail et maintenant cela fonctionne. J'étais coincé sur une erreur imprudente. Merci beaucoup.
