### ISSUE TITLE
\stanza centers Hebrew text

### ISSUE THREAD

**Issue by kmein** [maieul/ledmac#915]
# Version
2020/02/04 v2.32.4 

# TeX Engine
XeLaTeX

# Description

When `reledmac` is used together with `polyglossia` 's `\texthebrew` or `\begin{hebrew}` to support hebrew text, the `\stanza` command stops working as documented: With text in Latin script (e. g. the english stanza in the example), `\setstanzaindents{1,0}` keeps the text left-aligned and indents verses which are too long. If you use an RTL script such as Hebrew, setting the stanza indents to anything but `0,0` centers each line horizontally.

This seems like it might not be intended. If it is, I would be very happy to know how to achieve correctly aligned Hebrew verse.

![falsely centered stanza](https://user-images.githubusercontent.com/10352507/119239781-96b02680-bb4b-11eb-9ead-983554d9f0b9.png)

# Minimal Working Example

```latex
\documentclass{scrbook}
\usepackage{fontspec}
\usepackage{polyglossia}
\usepackage{reledmac}

\setdefaultlanguage{english}
\setotherlanguages{hebrew}
\setmainfont{Linux Libertine O} % substitute for any font that supports Hebrew

\begin{document}

\setstanzaindents{1,0}
\setcounter{stanzaindentsrepetition}{1}

\beginnumbering
  \stanza
    This is some text, it should be left-aligned. &
    It works with stanza-indents set to one. &
    But use some Hebrew text and you will find &
    The verses to the page's centre gone.
  \&
\endnumbering

\begin{hebrew}
  \beginnumbering
  \stanza
    פֿון איין ריטר אויז פֿראוונציאן לנד&
    זיגמנד איז זיין נאמן גיננט&
    אונ׳ פֿונ קינגשטאכֿטר מגלינה פֿונ פֿרנקרייך&
    איר שונהייט גפֿינט מן ניט איר גלייך&
    וויא זיא זיך אננדר האבן גינומן&
    אונ׳ וויא זיא זענן ווידר פֿון אננדר גיקומן&
    אונ׳ וויא זיא האט טאן איין קלוסטר בויאן&
    אונ׳ וויא ער האט טאן זיא מיט גרושן רייכֿטום ווידר בישויאן
  \&
\endnumbering
\end{hebrew}

\end{document}
```

**Comment by maieul** [comment]
please try branch issue915

**Comment by kmein** [comment]
It works. Thank you so much!

**Comment by maieul** [comment]
I will release it next week-end.

**Comment by almediaeval** [comment]
I'm at branch issue915 and having two related problems: (1) the hebrew stanza is right-aligned, but with the stanza intents at 1,0 there is no visible indent, while the english text is indented. And (2), if I have critical footnotes with a hebrew lemma and I use \Xarrangement[]{paragraph} , the footnotes get centered (they are left-aligned without it).

(1) (the third line should be indented)
![grafik](https://user-images.githubusercontent.com/61889943/119883812-414f8d00-bf30-11eb-8530-c9c0694efdaf.png)
`\documentclass{scrbook}
\usepackage{fontspec}
\usepackage{polyglossia}
\usepackage{reledmac}

\setdefaultlanguage{english}
\setotherlanguages{hebrew}
\setmainfont{Linux Libertine O} % substitute for any font that supports Hebrew

\begin{document}

\setstanzaindents{1,0}
\setcounter{stanzaindentsrepetition}{1}

\beginnumbering
\stanza
this is a stanza in latin alphabet&
and if a verse is very looooooooooooooooooooooooooooooooooooooooooooong the indent is just done properly&
right?\&
\endnumbering

\begin{hebrew}
  \beginnumbering
  \stanza
    פֿון איין ריטר אויז פֿראוונציאן לנד&
    זיגמנד איז זיין נאמן גיננט אונ׳ פֿונ קינגשטאכֿטר מגלינה פֿונ פֿרנקרייך איר שונהייט גפֿינט מן ניט איר גלייך וויא זיא זיך אננדר האבן גינומן אונ׳ וויא זיא זענן ווידר פֿון אננדר גיקומן&
    אונ׳ וויא זיא האט טאן איין קלוסטר בויאן&
    אונ׳ וויא ער האט טאן זיא מיט גרושן רייכֿטום ווידר בישויאן
  \&
\endnumbering
\end{hebrew}

\end{document}
`
(2)
![grafik](https://user-images.githubusercontent.com/61889943/119884156-9be8e900-bf30-11eb-8271-853fe1cf894a.png)
`\documentclass{scrbook}
\usepackage{fontspec}
\usepackage{polyglossia}
\usepackage{reledmac}

\setdefaultlanguage{english}
\setotherlanguages{hebrew}
\setmainfont{Linux Libertine O} % substitute for any font that supports Hebrew
\Xarrangement[]{paragraph}
\Xwrapcontent{\textenglish}

\begin{document}

\setstanzaindents{1,0}
\setcounter{stanzaindentsrepetition}{1}

\begin{hebrew}
  \beginnumbering
  \stanza
    פֿון איין ריטר אויז\edtext{פֿראוונציאן}{\Afootnote{footnotes with a hebrew lemma get centered}} לנד &
    זיגמנד איז זיין נאמן גיננט&
    אונ׳ פֿונ קינגשטאכֿטר מגלינה פֿונ פֿרנקרייך&
    איר שונהייט גפֿינט מן ניט איר גלייך&
    וויא זיא זיך אננדר האבן גינומן&
    אונ׳ וויא זיא זענן ווידר פֿון אננדר גיקומן&
    אונ׳ וויא זיא האט טאן איין קלוסטר בויאן&
    אונ׳ וויא ער האט טאן זיא מיט גרושן רייכֿטום ווידר בישויאן
  \&
\endnumbering
\end{hebrew}

\end{document}
`

**Comment by maieul** [comment]
for the first problem, please try the new version of the branch.

For the second problem, that is because, one the footnote are typeset, you have left the RTL mode (as we are in the end of a page which is mainly LTR). You can add `\Xbhookgroup{\RTL}` to deal with this problem.

**Comment by maieul** [comment]
@almediaeval any feedback ? I would like to release it soon.

**Comment by almediaeval** [comment]
@maieul it works perfectly with the indents now, thank you so much!!
with the footnotes it still doesn't work for me, but maybe that's because of something else, I'll try again next week.

**Comment by maieul** [comment]
oki, in case you didn't find, open a new issue.
