### ISSUE TITLE
Problem with reledmac and lemma substitution, error '\iflemmacommand@0' undefined

### ISSUE THREAD

**Issue by GiliGitSF** [maieul/ledmac#916]
It seems that a \edtext{} content longer than one line give rise to this "\iflemmacommand@0" undefined error.

Compiled in overleaf

# Version

Package: reledmac 2020/07/06 v2.34.2 typesetting critical editions

# TeX Engine

This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex 2020.9.10)  26 MAY 2021 20:14
entering extended mode

# Description

The MWE below triggers the error.
If you reduce the content of \edtex to occupy one single line, the error is not triggered.
BUT, you must clear the cache, otherwise you get three errors!
- \iflemmacommand@0
- extra }, or forgotten \endgroup.
- Runaway argument?

Let me repeat the situation:
- start with a short content (less than one line) in \edtext => no error;
- increase le length to more than a single line => \iflemmacommand error;
- reduce \edtext to starting length (but do no clear the cache) => three errors!

By "single line", I mean the length of the Arabic text in the final compiled pdf

Please do note that, despite the \iflemmacommand error, the final result is correct, i.e. the content of the critical note is correct in the pdf.

# Minimal Working Example

\documentclass[a4paper, 12pt, twoside, openright]{book}

%\usepackage{polyglossia}
%\setdefaultlanguage{italian}
\usepackage{fontspec}
\newfontfamily\arabicfont[Script=Arabic, Scale=1.5]{Scheherazade}
%%%%%%%%%%%%%%%%%%%%%%%%%%
% If you do not use fontspec and  Scheherazade, please make sure the that the content of \edtex was shorter or longer
% than a single line, in order to trigger the error
%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage[series={A}, noend, nopenalties, nofamiliar, noeledsec, noledgroup ]{reledmac}
\Xlinerangeseparator{\null-\null}

\usepackage{arabxetex}

\begin{document}

\begin{arab}
\beginnumbering
\pstart

	\edtext{al-^guz'_u al-'wwalu min kitAbi kAmili al-.sinA`Ti  al-.tibbyaTi al-ma`rUfi kAmili al-.sinA`Ti al-.sinA`Ti al-.sinA`Ti al-'wwalu min kitAbi}{
	\lemma{al-^guz'_u \dots\ bAbAN}
	\Afootnote{al-^guz|"'u bAbAN}}

\pend
\endnumbering
\end{arab}

\end{document}

**Comment by maieul** [comment]
hum, that is a bug because xetex support of rtl is not optimal.

**Comment by maieul** [comment]
please try brancj issue916

**Comment by GiliGitSF** [comment]
Dear Maieul,

first I had to understand how to use this issue916 in Mac TeXShop, but finally I got it ...
It works ! No more \iflemmacommand error !!!

Thank you very much for your kind help!

Best regards
Gili

**Comment by maieul** [comment]
I see that you comment on SE that you opend an issue and it was be solved. 

Could you please

1. Delete your message
2. Valide my answer (it is for my rank reputation).
Thanks

**Comment by GiliGitSF** [comment]
I do beg your pardon, I just wanted to let the community know that you solved the issue.
It is the first time I post in Stackexchange (really the first time on a website), I have to improve my netiquette...

Thank you
BR
Gili

**Comment by maieul** [comment]
It is not a problem, you couldn't know :)
