### ISSUE TITLE
Feature request: Line abbreviations as a cross reference

### ISSUE THREAD

**Issue by marquinho78** [maieul/ledmac#917]
# Version

reledmac 2.37.2 April 2021

# TeX Engine

only pdfLaTeX tested

# Description

In critical footnotes with an abbreviated line range (specified via `\Xtwolines{f.}` and `\Xmorethantwolines{ff.}`), only the explicitely stated number gets a cross reference. The abbreviation text ("f.") does not.
This becomes evident when using hyperref, but it appears to depend from the code of reledmac itself.

# Minimal Working Example

```latex
\documentclass{article}

\usepackage[series={A},noend,nofamiliar,noeledsec]{reledmac}

\Xtwolines{f\fullstop}
\Xmorethantwolines{ff\fullstop}

\usepackage[colorlinks]{hyperref}       

\begin{document}
\beginnumbering
%
\pstart
%
\edtext{Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.}{%
\lemma{Lorem \lbrack...\rbrack\ consequat.}
\Afootnote{A critical note that spans two or more lines.}}
%
\pend
\endnumbering
\end{document}

```

# Workaround

No known workarounds, other than editing the definition of `\printlines` in `reledmac.sty.

**Comment by maieul** [comment]
so, please try branch issue917. I have a made an hyperlink to the endline, while it is not so obvious to chooce between end and start line.

**Comment by marquinho78** [comment]
Great! It works perfectly. Yes, it's good that the abbreviation links to the endline.
Thanks a lot!

**Comment by marquinho78** [comment]
(Sorry, I think closing is your prerogative :-) )

**Comment by maieul** [comment]
indeed, it is my prerogative. I close only when the changelog is done, and merged in master.
