### ISSUE TITLE
Flexible customization of page-line-numbers for footnotes that span page break

### ISSUE THREAD

**Issue by marquinho78** [maieul/ledmac#918]
# Version

2.37.2. April 2021

# TeX Engine

Only tested on pdfLaTeX

# Description

This is a request for more flexible customization options for critical `\Xfootnote`s when they span a page break.
The current standard format of the page-line-numbers, if a footnote spans several pages, is: "SP.SL–EP.EL" (abbreviations stand for: start page, start line, end page, end line).
I would like to request
1. the ability to insert a *prefix* of choice before EP (f.i. "p.~" for "page");
2. the ability to silence the SP number, *if* it is identical with the number of the current page (and therefore redundant)
so as to get the style: "SL–p.~EP.EL"

# Minimal Working Example

```latex
\documentclass{article}

\usepackage[series={A},noend,nofamiliar,noeledsec]{reledmac}

\lineation{page}    
\firstlinenum{1}
\linenumincrement{1}    

\begin{document}
\beginnumbering
%
\pstart
\setline{10}
%
\edtext{Lorem}{%
\Afootnote{A critical note that is all contained in one page.}}
%
ipsum dolor sit amet, consectetur adipiscing elit, sed do 
%
\edtext{eiusmod 
\ledpb
tempor incididunt.}{%
\Afootnote{A critical note that spans a page break.}}
%
\pend
\endnumbering
\end{document}
```

# Workaround

No workarounds known, other than editing the definition of `\printlines` in reledmac.sty.

**Comment by maieul** [comment]
Ok, 

please try branch issue918.

It provides two more settings

- `\Xbeforepagenumber` to print arbitrary text before page number
- `Xnopagenumberifcurrent` to avoid printing page number if it is the current one. 

Not that, because of the complexity to get the current page number (https://tex.stackexchange.com/a/239457/7712), we need more one run. But in general, you should use latexmk or such programm when dealing with reledmac.

**Comment by marquinho78** [comment]
Thanks a lot!
(1)
`\Xbeforepagenumber` works as expected.
For the documentation, l. 2397 I would suggest: "when a note spans across **two or more pages** and the lineation is by page."
As it is now, if used together with hyperref, you get a hyperlink that includes the prefix: **S. 1** is all a (colored/boxed) hyperlink. I would like it more if the prefix was just plain text and the hyperlink started with the page number S. **1** . What do you think? This might just be me and purely a matter of taste :-)

**Comment by marquinho78** [comment]
(2)
With `\Xnopagenumberifcurrent` unfortunately there seems to be a bug. It works fine in most contexts, but there is a bug whenever *one paragraph* (\pstart to \pend) is so long that it spans two or more page breaks, *and* there is a critical footnote spanning *each* of these page breaks. This is quite infrequent, but possible.
I have tested it extensively in several settings (with `\lipsum`; with pages of real text; and with forced page breaks `\ledpb`) and I could reproduce the following bug.
In this situation, only the very last footnote of the paragraph has the correct numbers (SL-EP.EL). The second-to-last has it completely backward (SP.SL-EL !) and any footnotes before these have the whole range (SP.SL-EP.EL).
I give you two examples (where I have formated the \notenumfont bold for clarity):

**Comment by marquinho78** [comment]
\documentclass{article}

\usepackage[series={A},noend,nofamiliar,noeledsec]{reledmac}

\lineation{page}    
\firstlinenum{1}
\linenumincrement{1}
\Xnotenumfont{\bfseries\footnotesize}


\Xnopagenumberifcurrent[A]


\usepackage{lipsum}
\newcommand{\sevenlinesoftext}{Text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text
text text text text text text text text text text text text text text text text text text}


\begin{document}
\setcounter{page}{101}
\beginnumbering
%
\pstart
%
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
%
\edtext{{\itshape \sevenlinesoftext}}{%  	% note starts on 101.35, ends on 102.3
\Afootnote{A-footnote. Expected output: \textbf{35-102.3}}}
%
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
%
\edtext{{\itshape \sevenlinesoftext}}{%  	% note starts on 102.38, ends on 103.5
\Afootnote{A-footnote. Expected output: \textbf{38-103.5}}}
%
\sevenlinesoftext\
\sevenlinesoftext\
%\pend \pstart							% test: break the long paragraph in the middle
\sevenlinesoftext\
\sevenlinesoftext\
%
\edtext{{\itshape \sevenlinesoftext}}{%  	% note starts on 103.33, ends on 104.1
\Afootnote{A-footnote. Expected output: \textbf{33-104.1}}}
%
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
\sevenlinesoftext\
%
\edtext{{\itshape \sevenlinesoftext}}{%  	% note starts on 104.35, ends on 105.3
\Afootnote{A-footnote. Expected output: \textbf{35-105.3}}}
%
\sevenlinesoftext\
%
\pend
\endnumbering
\end{document}

**Comment by maieul** [comment]
I will look. I prefere having example without lipsum. Is there any reason to provide two examples ?

**Comment by marquinho78** [comment]
These are both paragraphs that are several pages long and have 4 footnotes, one for each page break.
Only footnote 4 is correct; footnote 3 is strange; no. 1 and 2 have the "normal" format.
See what happens if you break the long paragraph in the middle with a \pend.

(I'm sorry for posting so much and making so much trouble!
And do take all the time you need, I do understand that the matter of page breaks and page numbers is quite complicated. I know that LaTeX doesn't update the page number at page shipout, but only after the end of a paragraph...)

**Comment by marquinho78** [comment]
No, there's no specific reason, so you can ignore the example with lipsum. The other one gives the problem too.

**Comment by maieul** [comment]
So the new version of the branch

1. Add the page prefix outside of the crossref (it is a matter of gust, but I think outside is maybe more common)
2. Correct the handbook
3. Correct your problem with `Xnopagenumberifcurrent` (which was just related to the fact that I used a wrong counter...)

**Comment by marquinho78** [comment]
Yes, it's perfect now!

Regarding the handbook l. 2462: I find it very clear, just a couple of pedantic corrections:

% When we use a lineation by page, \macpackage *checks* if a lemma spans across two page. In this case, it *prints* the starting *and* ending page number.
%
% Many *times*, one of these two page *numbers* is also the current page number.
%
% In this case, it is possible to disable page number printing, using \cs{Xnopagenumberifcurrent}\oarg{s}.

Thanks a lot!

**Comment by maieul** [comment]
Nice. Thanks for the typos. 

I will publish it this week-end (I am waiting answer for other issues)
