### ISSUE TITLE
Text and diagrams in parallel environment

### ISSUE THREAD

**Issue by NiAgio** [maieul/ledmac#923]
# Version

reledmac 2021/05/30 v2.38.0

# TeX Engine

XeLaTeX

# Description

Hi, this issue is about a request, not a problem. Is it possible to print in a parallel environment a paragraph of text (to the left) and a diagram (to the right) in such a way that both items "stand" on the same "level"? I have tried to do it by means of reledmac/reledpar, but the diagram is printed always parallel next to the first line of the text. See both the picture and the mwe. Thank you very much in advance!

<img width="560" alt="pic" src="https://user-images.githubusercontent.com/10960975/122690277-d93b5080-d228-11eb-840f-d0b3e5a426c9.png">

# Minimal Working Example

\documentclass[twoside,12pt]{article}
\usepackage{polyglossia,fontspec,xunicode}

\setmainfont{Times New Roman}

\setmainlanguage{latin}
%\setotherlanguage[variant=ancient]{greek}

\usepackage[a4paper,right=4.25cm,left=4.25cm,top=5.25cm,bottom=5.25cm]{geometry}

\usepackage[noeledsec,noledgroup,series={A}]{reledmac}

\usepackage[widthliketwocolumns,continuousnumberingwithcolumns]{reledpar}
\setlength{\Lcolwidth}{0.47\textwidth}
\setlength{\Rcolwidth}{0.47\textwidth}
\columnsposition{c}
\setlength{\beforecolumnseparator}{0.03\textwidth}
\setlength{\aftercolumnseparator}{0.03\textwidth}

\AtBeginPairs{\sloppy}

\lineation{section}

\usepackage{calc}
\usepackage{graphicx}
\usepackage{tikz}

\usepackage{pgfplots}
\pgfplotsset{compat=1.15}
\usepackage{mathrsfs}
\usetikzlibrary{arrows}

\Xarrangement[A]{paragraph}
\Xnumberonlyfirstinline[A]
\Xnumberonlyfirstintwolines[A]
\Xinplaceofnumber[A]{0em}

\begin{document}
\beginnumbering  
\pstart  
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum feugiat dolor vitae urna laoreet dapibus. Ut pulvinar nisl ultrices ex viverra, ac imperdiet sem gravida. Pellentesque malesuada augue a interdum placerat. Aenean tincidunt euismod viverra. Maecenas consectetur ligula nisi, in dignissim nulla tempus et. Aenean non scelerisque odio. Phasellus cursus bibendum turpis quis finibus.
\pend  
\pausenumbering

\begin{pairs}
\begin{Leftside} 
\resumenumbering  
\pstart  
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum feugiat dolor vitae urna laoreet dapibus. Ut pulvinar nisl ultrices ex viverra, ac imperdiet sem gravida. Pellentesque malesuada augue a interdum placerat. Aenean tincidunt euismod viverra. Maecenas consectetur ligula nisi, in dignissim nulla tempus et. Aenean non scelerisque odio.
\pend  
\pausenumbering 
\end{Leftside}

\begin{Rightside}   
\beginnumbering 
{\centering
\pstart  
\begin{tikzpicture}[line cap=round,line join=round,>=triangle 45,scale=1.5]
\scriptsize
\draw [line width=0.5pt] (0,1.1547005383792515)-- (-1,-0.5);
\draw [line width=0.5pt] (-1,-0.5)-- (1,-0.5);
\draw [line width=0.5pt] (0,1.1547005383792515)-- (1,-0.5);
\end{tikzpicture}
\pend  
}
\endnumbering
\end{Rightside}  
\end{pairs}  
\Columns

\resumenumbering  
\pstart  
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum feugiat dolor vitae urna laoreet dapibus. Ut pulvinar nisl ultrices ex viverra, ac imperdiet sem gravida. Pellentesque malesuada augue a interdum placerat. Aenean tincidunt euismod viverra. Maecenas consectetur ligula nisi, in dignissim nulla tempus et. Aenean non scelerisque odio. Phasellus cursus bibendum turpis quis finibus.
\pend  
\endnumbering
\end{document}

**Comment by maieul** [comment]
now, there is no direct way for that in reledmc/reledpar

**Comment by NiAgio** [comment]
Ok! Thanks!
