### ISSUE TITLE
Problème avec l'indentation des vers en latin

### ISSUE THREAD

**Issue by Outis27** [maieul/ledmac#930]
# Version

2021/09/27 v2.38.1

# TeX Engine

LuaLaTeX

# Description

Je suis en train de faire une édition critique avec du latin et du grec ancien et des vers. Quand j'écris des vers numérés en latin avec une indentation alternante, il semble que le premier vers n'est pas indenté, alors que le même code marche très bien avec indentation pour le grec ancien.
Dans mon exemple, vous devrez bien voir que le "verse 1" du texte en latin a la même indentation que texte normal et seulement "verse 3" a la bonne indentation, alors que le "βερς 1" en grec a la même indentation que "βερς 3". Le code pour les deux parties est le même, je l'ai copié et collé en changeant seulement la langue. Donc je n'ai plus d'autre explication que celle-ci. 
A part de reledmac je n'utilise que les packages qu'on m'a proposé comme indispensable avec lualatex, que j'utilise parce que c'est plus facile de changer beaucoup entre mes trois langues latin, grec et allemand. Voilà aussi pourquoi j'utilise Times New Roman, puisque autrement, le programme me dit qu'il ne trouve pas les charactères grecs.
(En général je suis encore débutant en latex, donc s'il y a quelque chose d'inutile ou superflu ou ce que n'a pas de sens dans le code, je vous en prie de ne pas me tuer! ;) )

# Minimal Working Example

```latex
\documentclass[12pt, oneside]{book}
\usepackage{polyglossia} 
	\setdefaultlanguage[spelling=new, babelshorthands=true]{german}
	\setotherlanguage[variant=ancient]{greek}
	\setotherlanguage{latin}
\usepackage{fontspec} 
\usepackage{unicode-math}
\usepackage{luacode}
\usepackage[series={A,B}]{reledmac}
\setmainfont{Times New Roman} 

\begin{document}

\beginnumbering 
\pstart
\begin{latin} 
text. \\ 
\end{latin} 
\pend
\begin{latin}
\setstanzaindents{5,3,4}
\setcounter{stanzaindentsrepetition}{2}
\stanza 
verse 1 & %sans indentation bien qu'il devrait y en avoir
verse 2 &
verse 3 &
verse 4 \&
\end{latin}
\pstart
\begin{latin}
text
\end{latin}
\pend
\endnumbering

\beginnumbering 
\pstart
\begin{latin} 
text. \\ 
\end{latin} 
\pend
\begin{greek}
\setstanzaindents{5,3,4}
\setcounter{stanzaindentsrepetition}{2}
\stanza 
βερς 1 & %avec indentation comme cela devrait être
βερς 2 &
βερς 3 &
βερς 4 \&
\end{greek}
\pstart
\begin{latin}
text
\end{latin}
\pend
\endnumbering

\end{document}
```

# Workaround

La seule solution que j'au trouvé jusqu'ici est d'écrire le texte latin dans un environnement grec. Il semble que le programme n'a pas de proplème avec cela, mais bien sûr que ce n'est pas ainsi que cela devrait marcher.

**Comment by maieul** [comment]
Là, comme cela en premier abord, je dirais deja de mettre vos commande 
de gestion des indententations **en dehors** des environnements concernés.

Si ce n'est pas ca le problème, j'essaierai de trouver prochainement du 
temps pour regarder plus en détails.

**Comment by Outis27** [comment]
Bonsoir! 
Merci pour votre reponse. J'ai encore une fois essayé trois choses avec le

\setstanzaindents{5,3,4}
\setcounter{stanzaindentsrepetition}{2}

- Je l'ai mis dans la préambule, juste avant \begin{document}.
- je l'ai mis juste après le \begin{document}
- et je l'ai mis entre le \pend et le \begin{latin/greek} \stanza respectivement. Dans ce scénario il faut en effet le mettre les deux fois, autrement il y a un message d'erreur.

Aucune des trois variantes n'a changé rien dans le résultat.
À part de cela, de toute manière les deux environnements sont complètements identiques dans le code, donc je dirais intuitivement que les resultats devraient être les mêmes et pour la partie latine et pour celle en grec. De l'autre côté l'intuition ne marche pas toujours avec ces choses-là.

Je vous remercie beaucoup pour votre effort! A part ce minuscule problème j'adore le résultat que me donne le package.

**Comment by maieul** [comment]
Hum, je viens de tester, si on met le `\begin{latin}` avant le `\beginnumbering`, cela marche.

**Comment by maieul** [comment]
Pouvez vous essayer la branche issue930 ?

**Comment by Outis27** [comment]
J'ai essayé le code dont vous avez posté le link. Voici le resultat en format pdf:
[reledmac4.pdf](https://github.com/maieul/ledmac/files/7456586/reledmac4.pdf)
Rien n'a changé pour moi, "verse 1" est toujours loin de la position de "verse 3" qu'il devrait partager. Je ne sais pas ce qui peut être différent pour moi, j'ai copié et collé votre code et n'y ai mis rien de plus, en utilisant lualatex. J'ai aussi encore une fois verifié le fichier .log pour la version de reledmac, mais tout est correct (Package: reledmac 2021/09/27 v2.38.1 typesetting critical editions). Le problème pourrait-il être dans mon programme TeXworks lui-même? Mais je suppose que c'est plutôt improbable.

A part de cela, mettre la langue hors de la numérotation ne serait pas pratique pour moi, puisque je travaille avec des textes du XVI siècle avec des poèmes mélangeants des vers en grec et en latin, donc changer de langue au cours de vers d'une manière ou d'autre est indispensable.

**Comment by maieul** [comment]
hum, non vous n'avez pas compris la procédure pour tester, c'est pour cela j'imagine que cela ne marche pas pour vous.

Je vous invite à lire ici la procédure pour comprendre comment tester les branches de devellopement. https://github.com/maieul/ledmac#debug-and-feature-requests

**Comment by Outis27** [comment]
Ah, je suis désolé! 

Oui, comme cela, cela marche tout à fait. Seulement si je mets le fichier dans le dossier que j'ai téléchargé chez vous et non pas d'autre part, mais je suppose que cela doit encore être ainsi.

**Comment by maieul** [comment]
le fichier .sty doit être à côté du fichier .tex, oui.

Lorsque je sortirai la nouvelle version du package, il vous faudra 
ensuite mettre à jour le plugin, et ainsi vous pourrez supprimer le 
fichier .sty
