### ISSUE TITLE
One footnote ruler for 2 or more series 

### ISSUE THREAD

**Issue by shoshia** [maieul/ledmac#933]
Not Issue. Just useful feature

# Description

When I have two ruler one for each footnote I have ruler, when i have only one series footnote on page. Question is is it possible to have just one ruler for A,B footnotes? No matter wat footnote i have A,B, or both only one ruler is drawn. Here is a MnotWE :)

# Minimal not Working Example

```latex
        \documentclass[]{article}
        \usepackage[series={A,B},noeledsec]{reledmac}
        \usepackage{perpage}
        \arrangementX{paragraph}
        \MakePerPage{footnoteA}
        \MakePerPage{footnoteB}
        \renewcommand\footnoteruleA{ %
        \kern-3pt \hrule width 5.0cm \kern 2.6pt \par \hspace{2em}}
        \renewcommand\footnoteruleB{ }
        \renewcommand*{\thefootnoteB}{\roman{footnoteB}}
        \begin{document}
        \beginnumbering
        \pstart
        An footnote\footnoteA{footnoteA text}\footnoteB{footnoteB text} 
         and I don't need two rulers
        \pend
        \newpage
        \pstart
         Some text with A footnote\footnoteA{This is ok}
          \pend
        \newpage
            \pstart
         Some text with B footnote\footnoteB{I need ruler here}
          \pend
        \endnumbering
        \end{document}
```

# Workaround

**Comment by maieul** [comment]
I have to deal with a current moving house, but ask me again in middle march

**Comment by lenoch** [comment]
Dear @maieul, first of all, thank you for taking care of reledmac! I’ve been building a tool in Python to render critical editions from custom markup in DOCX through TEI to PDF and I am very fond of reledmac being able to typeset them beautifully.

Finally, I have reached a point when I have two series of footnotes (A = corrections of errors in manuscripts & B = other notes such as textual variants) and like @shoshia, I need a single horizontal rule above them, as I’ve been seeing in my local (Czech) tradition.

I wouldn’t dare try to use reledmac hooks for this as I am a rather casual LaTeX user and frankly, the code still scares me. Do you think you could add an option to reledmac to only render a single rule above several series of footnotes, please?

Merci beaucoup ! 🙂

**Comment by maieul** [comment]
> I wouldn’t dare try to use reledmac hooks for this as I am a rather casual LaTeX user and frankly, the code still scares me. Do you think you could add an option to reledmac to only render a single rule above several series of footnotes, please?

well, in any case, an option would be an hook. But yes, actually we have no hook for that. I will try to look on, but I have not a lot of time for reledmac.

**Comment by maieul** [comment]
So, you are lucky, I had some time. So please try branch  `issue933_footnoteruler`. You may find the documentation change on  2bd3607bf446a5ae8f4b0524a9a1a4df5606a45b. Please also tell me if the handbook is clear on this point.

**Comment by maieul** [comment]
Thanks for the test and the PR. I will let one week to find bug (I hope there are not) and well, releasing to CTAN sunday afternoon.

**Comment by lenoch** [comment]
Sweet! Thank you @maieul for such convenience 🙂

My colleague is already enjoying your code change and I hope to publish my project once it matures enough.

**Comment by maieul** [comment]
Finally, I will release today.

**Comment by maieul** [comment]
So, that is now on CTAN, available normally tomorrow via tlmgr.

**Comment by lenoch** [comment]
Thanks for the release! As a tectonic user I might be stuck to a TeXLive 2022 version but luckily I have the most recent build 🙂
