### ISSUE TITLE
I have a simple question, which I think, does not need any code: Is it possible to assign discontinuous line numbers in reledmac?

### ISSUE THREAD

**Issue by wkittler** [maieul/ledmac#939]
# Version

# TeX Engine

# Regression

# Description

# Minimal Working Example

```latex
Type your MWE here
```

# Workaround

**Comment by maieul** [comment]
You may use `\setlinenum` and / or `\setline`.

See the handbook.

**Comment by wkittler** [comment]
Dear Maïeul Rouquette,

I am sorry, this was a stupid question. I found, too late, that I could
solve the problem with \advancenumber and \gdef\linenumberlist.

This is a great program, and I am grateful to those who created it.

Thank you,

Wolf Kittler
