### ISSUE TITLE
[Feature] Display several footnotes in the middle of page

### ISSUE THREAD

**Issue by martensas** [maieul/ledmac#942]
I'm writing a translation of a poem where each stanza should be followed immediately by its footnotes. The only way I have found to solve this is with a minipage, but that gives the problem that there is often huge blank space between the stanzas. The screenshot should illustrate well.
<img width="506" alt="Skärmavbild 2022-10-04 kl  13 48 52" src="https://user-images.githubusercontent.com/99649940/193812097-cbddeaeb-6d61-424f-9da5-96033378bb95.png">

**Comment by maieul** [comment]
You should use ledgroup.
