### ISSUE TITLE
Incompatibilité entre reledmac, glossaries-extra et leipzig

### ISSUE THREAD

**Issue by JPapir** [maieul/ledmac#945]
# Version
Package: reledmac 2022/02/04 v2.39.1 typesetting critical editions

# TeX Engine

XeLateX, PDFLaTex = même problème

# Description
Le package Leipzig pour réaliser des gloses linguistiques s'appuie sur glossaries. Mais reledmac exige que glossaries soit chargé avec glossaries-extra et soulève une erreur dès que l'on charge le paquet leipzig, parce que ce dernier n'utilise pas glossaries-extra.  Or, glossaries-extra est incompatible avec leipzig.
Personnellement, je n'ai pas besoin d'utiliser glossaries dans reledmac même, je veux juste que mon document soit autorisé à contenir un index des gloses gérées par Leipzig. Est-ce possible ? En gros il s'agirait d'autoriser reledmac à fonctionner sans glossaries-extra si l'utilisateur sait ne pas avoir besoin de glossaries dans reledmac. (par exemple avec une option au chargement du package without-glossaries ?)

# Minimal Working Example

```latex
\documentclass{scrbook}

\usepackage{reledmac}
\usepackage{leipzig}

\begin{document}
 Test
\end{document}
```
L'erreur soulevée est la suivante :
```! Package reledmac Error: When using both reledmac and glossaries, you must also use glossaries-extra.```

# Workaround

Ne charger que l'un des deux packages est la seule solution que j'aie trouvée.

**Comment by maieul** [comment]
Dans la mesure où c'est Leipzig qui décide d'utiliser glossaries, je ne vais m'amsuer dans reledmac à faire des tests pour savoir si effectivement glossaries est utilisés par reledmac, ou si sa présence est lié à autre chose. La solution est tout simplement de suivre les conseils de reledmac, en ajoutant 

```
\usepackage{glossaries-extra}
```

**Comment by JPapir** [comment]
C'est peut-être leipzig qui décide d'utiliser glossaries, mais c'est reledmac qui soulève une erreur arbitraire quand leipzig utilise glossaries. Comme précisé dans le premier message, glossaries-extra fait planter leipzig en redéfinissant certaines fonctions de glossaries. Merci pour votre réponse tout de même.

**Comment by maieul** [comment]
L'erreur n'est pas arbitraire, elle est là pour s'assurer que les interaction reledmac/glossaries fonctionne.SI glossaries-extra est incompatible avec Leiptig, ce serait de ce coté là qu'il faudrait voir. Et désolé de ne pas avoir vu le message sur l'erreur côté Leipzig. 

Cela étant vous pouvez désactiver l'erreur avec ces lignes.

```
\makeatletter
\let\led@error@require@glossariesextra\relax
\makeatother

```

Je ne pense pas pour l'heure que ce soit pertinent de fournir une option, sans en tout cas une serieuse étude de toutes les conséquences que cela pourrait avoir (sachant que je connais mal glossaries, et surtout que je n'ai plus vraiment de temps, helas, pour reledmac)

**Comment by JPapir** [comment]
En effet, redéfinir l'erreur est le plus simple pour le moment, merci. (et je comprends tout à fait que ce n'est pas un problème prioritaire, ni pour reledmac, ni pour la plupart des utilisateurs, et ni pour vous ! Une solution de contournement comme celle-ci me suffit)
