### ISSUE TITLE
example 2-reledmac-right-to-left.tex

### ISSUE THREAD

**Issue by hvoss49** [maieul/ledmac#946]
# Version

up-to-date TL 2022

# TeX Engine

lualatex

the example 2-reledmac-right-to-left.tex. from the documentation does not
work with lualatex:

```
! Package reledmac Error: \pstart must be used within a numbered section (\beginnumbering ... \endnumbering).
```

**Comment by maieul** [comment]
Well, it seems that babel changed the way language should be loaded (as an error happens). So I have to look on the new way, but honestyl I have no time.
