### ISSUE TITLE
Possible bug: reledmac + polyglossia conflict when \numberlinefalse command is used

### ISSUE THREAD

**Issue by jeffdod** [maieul/ledmac#948]
# Version
reledmac 2022/02/04 v2.39.1

# TeX Engine
XeTeX, Version 3.141592653-2.6-0.999994 (MiKTeX 23.1) (preloaded format=xelatex 2023.2.16)  17 FEB 2023 19:04

# Description
If you use the polyglossia package together with reledmac, then reledmac will issue potentially hundreds of erroneous warning messages during compile time. This occurs if (a) you have footnotes in a \stanza, and (b) if you have the \numberlinefalse command invoked.

The warning reads as follows:

"The number of the footnotes in this section has changed since the last run. You will need to run LaTeX two more times before the footnote placement and line numbering in this section are correct."

The warning appears to occur for each instance of a footnote in a stanza. Thus if you have many stanzas and footnotes, you'll see so many of these warning messages during compile time that it becomes very difficult to see any real warning messages hidden within them.

What I'm trying to do is show text formatted in poetic style, but with no line numbers. However, in the minimum working example below, you can see that either (a) commenting out the polyglossia package and commands eliminates the warning messages, or (b) commenting out the \numberlinefalse command eliminates the warning messages.

I'm also numbering footnotes on a per-page basis. What's erroneous about the warning message coming from reledmac is that in fact after a couple of compiles, the per-page footnotes are numbered properly. But according to the warning message, which never goes away no matter how many times you compile, you need to run twice more.

# Minimal Working Example

```latex
\documentclass[11pt]{book}

\usepackage[paperheight=9in,paperwidth=6in]{geometry}
\usepackage{ragged2e}
\usepackage{reledmac}
\usepackage{perpage}

% >>>>>> THESE LINES CAUSE AN ISSUE WITH RELEDMAC <<<<<<<
\usepackage{polyglossia}
\setmainfont{Times New Roman}
\setmainlanguage{english}
% >>>>>> THESE LINES CAUSE AN ISSUE WITH RELEDMAC <<<<<<<

\arrangementX[A]{twocol}
\colalignX[A]{\RaggedRight}
\hsizetwocolX[A]{0.48\hsize}
\MakePerPage{footnoteA}
\setstanzaindents{2,1}
\setcounter{stanzaindentsrepetition}{1}
\setlength{\stanzaindentbase}{30pt}

% >>>>>> IF YOU COMMENT OUT THIS LINE, THE WARNING MESSAGES STOP <<<<<<
\numberlinefalse
% >>>>>> IF YOU COMMENT OUT THIS LINE, THE WARNING MESSAGES STOP <<<<<<

\begin{document}

\beginnumbering
\stanza
    Now is the time for all good men&
    To come \footnoteA{This is a footnote}to the aid&
    of their country.\&
\endnumbering

\end{document}
```

# Workaround
Obviously since I was using the \numberlinefalse command, I didn't want stanza lines numbered. The only workaround I could see at present was to invoke \firstlinenum{} with a very high number, so that for all practical purposes, no lines in the stanza are numbered.

**Comment by maieul** [comment]
As explained in the handbook `\numberlinefalse` won't be debuged anymore. It is to stricky. Please use a big `firstlinenum`.
