### ISSUE TITLE
Error (STOP) in compilation with pdflatex 

### ISSUE THREAD

**Issue by heinrichffleck** [maieul/ledmac#957]
Cher Maieul,  aujourd'hui, après la derniere mise à  jour de  TeXlive ( pdfTeX 3.141592653-2.6-1.40.25 - TeX Live 2023), et , par conséquent,  du paquet reledmac (2.39.6 2023-08-15)  j'ai eu un blocage dans la compilation avec <<pdflatex file.tex>> ici joint en format minimale.

%INCIPIT FILE MWE
% !TeX encoding = UTF-8 Unicode
% !TEX TS-program = pdflatex

\documentclass[10pt,a4paper,twoside]{memoir}
\usepackage[T1]{fontenc}
\usepackage[french,english,classiclatin,greek,italian]{babel}

\usepackage[font={small}]{caption}

%==========================RELEDMAC/RELEDPAR====================
\usepackage[series={A,B,C,D},noledgroup,nopbinverse,noeledsec,noend]{reledmac}
\usepackage{reledpar}
\AtBeginDocument{\Xmaxhnotes{0.5\textheight}}% 
\newcounter{Atest}
\def\Atest{\stepcounter{Atest}(\theAtest\ - A)}
\newcounter{Btest}
\def\Btest{\stepcounter{Btest}(\theBtest\ - B)}
%\fi
%****************************************************************
%ATTENTION:  CODICE INTRODOTTO DOPO IL DIAGNOSTICO ERRORE!!!!!!!!
%****************************************************************
%\iffalse
\makeatletter
\RenewDocumentCommand\pagenumbering{s m}{%
\IfBooleanTF{#1}{}{\c@page=\@ne}%
\renewcommand\thepage{\csuse{@#2}\c@page}%
}\makeatother
%******************************************

\begin{document}%
\mainmatter
\setcounter{page}{1}
\cleardoublepage
testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo testo  testo testo 
\end{document}
%FINIS FILE

Reledmac arrete maintenant la compilation lorsqu'il rencontre les commandes  \mainmatter e \setcounter{page}{1}.  On peut vérifier le problème si on supprime \ifalse et \fi aux lignes 23 .et 29 de la fichier jointe.

Comme vous pouvez le voir, merci aussi  à l'aide d'un de mes amis, j'ai résoulu le problème en ajoutant un certain nombre d'instructions:

\makeatletter
\RenewDocumentCommand\pagenumbering{s m}{%
\IfBooleanTF{#1}{}{\c@page=\@ne}%
\renewcommand\thepage{\csuse{@#2}\c@page}%
}\makeatother

qui, comme on peut voir recourt au code de LaTex3. 

Je voulais seulment te signaler ce problème et te soumettre le code si tu désires l'utiliser, car, pour ma part, le problème est résolu.

Merci pour travail,  et... pardon pour mon français,  cordialement Enrico (Heinrich)

**Comment by Doc73** [comment]
Have you seen issue #955 ?
