### ISSUE TITLE
footnote directions not correctly initialized 

### ISSUE THREAD

**Issue by u-fischer** [maieul/ledmac#962]
# Version

reledmac 2023/08/21 v2.39.7

# TeX Engine

Lualatex

# Regression

no, the problem is old.

# Description

Footnote directions are not correctly setup up if the first footnote is created with `\footnoteAtext`.

# Minimal Working Example

```latex
\documentclass{book}
\usepackage{reledmac}
\begin{document}
\makeatletter
%\footnoteA{xxx}
xxxx\footnoteAmark\footnoteAtext{blub}
\end{document} 
```

errors with

~~~~
! Undefined control sequence.
\footfmtA ...tex \textdir \footnote@luatextextdir 
                                                  \pardir \footnote@luatexpa...
l.7 xxxx\footnoteAmark\footnoteAtext{blub}
                                        
? 
! Undefined control sequence.
\footfmtA ...xtdir \pardir \footnote@luatexpardir 
                                                  \fi \protected@edef \@curr...
l.7 xxxx\footnoteAmark\footnoteAtext{blub}
                                        
? x
~~~~

# Workaround

Predefine the commands (or use `\footnoteA{something}` first).

**Comment by maieul** [comment]
May you propose a PR ?

**Comment by maieul** [comment]
Please try branch issue_962_footnotedirection_withAmark

**Comment by maieul** [comment]
@u-fischer may I ask again to try the branch ?

**Comment by maieul** [comment]
will be released tomorrow night
