### ISSUE TITLE
`edtabular` and `edarray` still break `edlabel`s

### ISSUE THREAD

**Issue by marquinho78** [maieul/ledmac#965]
# Version

Latest version of reledmac that was included in TeXLive 2024: version 2.40.0 of 2023-09-30.

# TeX Engine

I use pdflatex with help from pdflatexmk to ensure that all references are resolved.

# Regression

The last working version I used was the one included in TeXLive 2023, so that would be version 2.39.1 of 2022-02-04.

(This appears to be a continuation of some problems with \edlabels in tabular environments over the past year, according to the reledmac changelog, but I didn't use any of those versions, so cannot confirm.)

# Description

With reledmac loaded and nothing else, I see that the `\edlabel`s that are inside an `edtabular` or `edarray` environment are not recognized and the corresponding references are treated as undefined. That is, the referencing mechanism gives back a "0" for the page/line number, f.i. when making critical notes with `\xxref{label1}{label2}`.

This issue compromises several tables in our book where we need to append critical footnotes to specific lines; the tables used to work fine with v 2.39. The book (https://nebula.bbaw.de/s/oje3ji5ok5Xmp2c) is scheduled for publication this year, so it would be very nice to have a solution.

# Minimal Working Example

```
\documentclass{article}
\usepackage{reledmac}

\begin{document}
\beginnumbering
\pstart
%
\begin{edtabularc}
1 & 2 & 3 \\
a & bb & ccc\edlabel{Label-1} \\  % <----- This edlabel inside a tabular environment
AAA & BB & C
\end{edtabularc}
%
Some text\edlabel{Label-2}
containing\edlabel{Label-3}
some labels.\edlabel{Label-4}
%
\edtext{}{\xxref{Label-1}{Label-2}\lemma{Some text}%
\Afootnote{This note is broken, apparently because Label-1 is inside the tabular.}}
%
\edtext{}{\xxref{Label-3}{Label-4}\lemma{Some text}%
\Afootnote{This note works fine.}}
\pend
\endnumbering
\end{document} 
```

# Workaround

No known workarounds.

<img width="518" alt="Screenshot 2024-03-18 at 19 38 27" src="https://github.com/maieul/ledmac/assets/59567469/c081979b-084d-464b-9b0e-94d3325686e3">

**Comment by marquinho78** [comment]
Hey @maieul, sorry to bother you. Do you think the edtabular function can be repaired?
Alternatively, could you please make a small package option to (1) disable whatever new function was introduced in 2023 that broke the tabulars + (2) bring back the tabulars to how they were before they were broken?

So far, the only way to go is to tell all our collaborators to stick to TeXLive 2023 (which in time is not sustainable) or use TL 2024 but put reledmac.sty 2023 in all the folders and devices where compilation happens (not scalable).
We'd greatly appreciate your help!

**Comment by maieul** [comment]
I will try tommorow in the train, without garanty.

**Comment by marquinho78** [comment]
Thanks for taking the time!

**Comment by maieul** [comment]
Please try banch issue_965_edtabular_edlabel

**Comment by marquinho78** [comment]
I've tested it both with the MWE above and "in the wild" with our book.
Your solution works perfectly!
Thanks again for your time and effort.

**Comment by maieul** [comment]
Nice. I wait some day for feedback of @u-fischer on #963 and #964, but I will release soon.

**Comment by maieul** [comment]
Will be released tomorrow night
