### ISSUE TITLE
Example '2-reledmac-right-to-left.tex' fails

### ISSUE THREAD

**Issue by adamb924** [maieul/ledmac#970]
# Version

Package: reledmac 2023/08/21 v2.39.7 typesetting critical editions

# TeX Engine

The error occurs with XeLaTeX.

# Regression

N/A

# Description
An error message:
```
! Undefined control sequence.
\Xbhookgroup@A ->\textdir 
                          TRT
l.25 \Xlemmaseparator
                     {[}%Will be reversed by Ezra SIL font
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
```

# Minimal Working Example
It occurs with the included example '2-reledmac-right-to-left.tex'.

# Workaround

N/A

**Comment by maieul** [comment]
That is because, as explicily mentionned in the abstract, this exemple must be run with lualatex, not xelatex.
