### ISSUE TITLE
Code-breaking typo in the documentation

### ISSUE THREAD

**Issue by marquinho78** [maieul/ledmac#971]
# Version

2023/08/21 v2.39.7, but it is also present in the latest version of 2024 (reledmac.dtx).

# Description

In the usage sample of `edtabular` in the manual, the `\begin{edtabularl}` and `\end{edtabularr}` environments are mismatched. This breaks the code and may be confusing to new users.

User asked about it 4 years ago but forgot to file an issue: https://tex.stackexchange.com/questions/537932/reledmac-tabular-numbering

reledmac.dtx line 3952 sqq.

```
% For example:
% \begin{verbatim}
% \beginnumbering
% \pstart
% \begin{edtabularl}                                % <-------- LEFT
% \textbf{\Large I} & wish I was a little bug\edindex{bug} &
% \textbf{\Large I} & eat my peas with honey\edindex{honey} \\
%  & With whiskers \edtext{round}{\Afootnote{around}} my tummy &
%  & I've done it all my life. \\
%  & I'd climb into a honey\edindex{honey} pot &
%  & It makes the peas taste funny \\
%  & And get my tummy gummy.\edindex{gummy} &
%  & But it keeps them on the knife.
% \end{edtabularr}                                  % <-------- RIGHT
% \pend
% \endnumbering
% \end{verbatim}
%  produces the following parallel pair of verses.
```

**Comment by maieul** [comment]
Thanks. Corrected with c1af81e5
