### ISSUE TITLE
Apparat: référence à la ligne ou au paragraphe?

### ISSUE THREAD

**Issue by BattistaSalvi** [maieul/ledmac#972]
# Version

Je utilize Overleaf, je ne sais pas. Pardon.

# TeX Engine

XeLateX, mais je crois qu'il ne soit pas relevant 

# Description

J'aimerais que l'apparat fasse référence à la section et au paragraphe du texte (par exemple, 1.4 pour le chapitre 1, paragraphe 4), plutôt qu'à la ligne. Ce serait possible? Merci beaucoup pour votre aide. 

J'ai traduit le texte avec Google, je m'excuse pour les incohérences.

**Comment by maieul** [comment]
Ceci n'est pas un bug, donc merci d'éviter d'ouvrir un ticket pour cela. Préférez les listes d'entraides.

```
\numberpstarttrue% Show the pstart number in the text
\Xtxtbeforenumber{\thechapter}% Afficher le numéro de chapitre
\Xpstart% Show the pstart number in the apparatus
\Xonlypstart% Show only the pstart, not the line number
```
Devrait marcher.

**Comment by BattistaSalvi** [comment]
Merci beaucoup!
